Changed if [ $noOpt = 1 ] to [[ $noOpt = 1 ]] to eliminate if statement.

diff --git a/snippets/use_getopts b/snippets/use_getopts
--- a/snippets/use_getopts
+++ b/snippets/use_getopts
@@ -55,7 +55,7 @@ while getopts "$optstr" opt; do
 	esac
 	noOpt=0
 done
-# if [ $noOpt = 1 ];then echo "${lightred}ERROR:${normal} No argument passed." >&2;help 1;fi
-if [ $noOpt = 1 ];then printf "%s No argument passed.\n" "$red_error" >&2;help 1;fi
+# [[ "$noOpt" = 1 ]] && { echo "${lightred}ERROR:${normal} No argument passed." >&2; help 1; }
+[[ "$noOpt" = 1 ]] && { printf "%s No argument passed.\n" "$red_error" >&2; help 1; }
 
 exit
