snippets/use_getopts: changed case format and made printf default instead of echo.

diff --git a/snippets/use_getopts b/snippets/use_getopts
--- a/snippets/use_getopts
+++ b/snippets/use_getopts
@@ -24,33 +24,33 @@ while getopts "$optstr" opt; do
 	case "$opt" in
 		h )
 			help 0
-			;;
+		;;
 		i )
 			# argI="$OPTARG"
 			install_application
 			apply_settings	# optional custom configuration
-			;;
+		;;
 		r )
 			# argR="$OPTARG"
 			remove_application
-			;;
+		;;
 		s )
 			apply_settings
-			;;
+		;;
 		u )
 			exists application || leave "Application is not installed. run '$_script -i' to install."
 			update_application
-			;;
+		;;
 		: )
+		  # echo "${lightred}ERROR:${normal} Must supply an argument to -${OPTARG}." >&2
 			# printf "\e[91mERROR:\e[0m Must supply an argument to -%s.\n" "$OPTARG" >&2
-			# printf "%s Must supply an argument to -%s.\n" "$red_error" "$OPTARG" >&2
-		    echo "${lightred}ERROR:${normal} Must supply an argument to -${OPTARG}." >&2
-		    help 2
-		    ;;
+			printf "%s Must supply an argument to -%s.\n" "$red_error" "$OPTARG" >&2
+		  help 2
+		;;
 		? )
+			# echo "${lightred}ERROR:${normal} Invalid option -${OPTARG}" >&2
 			# printf "\e[91mERROR:\e[0m Invalid option -%s\n" "$OPTARG" >&2
-			# printf "%s Invalid option -%s\n" "$red_error" "$OPTARG" >&2
-			echo "${lightred}ERROR:${normal} Invalid option -${OPTARG}" >&2
+			printf "%s Invalid option -%s\n" "$red_error" "$OPTARG" >&2
 			help 2
 	esac
 	noOpt=0
