cronjobs/z-backup: created trim_log() and local_backup()

diff --git a/cronjobs/z-backup b/cronjobs/z-backup
--- a/cronjobs/z-backup
+++ b/cronjobs/z-backup
@@ -8,10 +8,10 @@
 # Author       : Copyright (C) 2020, Richard Romig, Mosfanet
 # Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
 # Created      : 07 Jun 2020
-# Updated      : 10 Oot 2025
-# Version      : 1.5.25283
+# Updated      : 15 Dec 2025
+# Version      : 2.0.25349
 # Comment      : Automatically limits log size to 30 entries.
-# TODO (Rick)  :
+# TODO (Rick)  : Consider new foremat for log file to include errors
 # License      : GNU General Public License, version 2.0
 # License URL  : https://github.com/RickRomig/scripts/blob/main/LICENSE
 #####################################################################
@@ -26,30 +26,42 @@
 # GNU General Public License for more details.
 #####################################################################
 
-main() {
-  local backup_dir error_log log_dir log_file
-  log_dir="/var/log"
-  log_file="backup.log"
-  backup_dir="/data/backup"
-  error_log="/error.log"
+trim_log() {
+  local log_dir="$1"
+  local log_file="$2"
+  local log_len
+  log_len=$(wc -l < "$log_dir/$log_file")
+  while [[ "$log_len" -gt 30 ]]; do
+    sed -i '1d' "$log_dir/$log_file"
+    (( log_len-- ))
+  done
+}
+
+local_backup() {
+  local log_dir="/var/log"
+  local log_file="backup.log"
+  local backup_dir="/data/backup"
+  local error_log="/error.log"
 
   [[ -d "$backup_dir" ]] || mkdir -p "$backup_dir"
   [[ -d "$log_dir" ]] || mkdir -p "$log_dir"
 
   {
     printf "%(%a|%F|%R)T|"
-    if rsync -aH --delete /etc /home "$backup_dir/" 2> "$backup_dir/$error_log"; then
+    if rsync -aH --delete --exclude="/backup/backup/" /etc /home /data "$backup_dir/" 2> "$backup_dir/$error_log"; then
       printf "successful\n"
-      echo "Local Backup was successful: $(date +%F)" > "$backup_dir/$error_log"
+      printf "%(%a, %F %R)T - Local Backup was successful.\n" > "$backup_dir/$error_log"
     else
-      printf "had errors %d\n" "$?"
-      echo "Local Backup had errors: $(date +%F)" >> "$backup_dir/$error_log"
+      printf "had errors (%d)\n" "$?"
+      printf "%(%a, %F %R)T - Local Backup had errors.\n" > "$backup_dir/$error_log"
     fi
     sync
-  } >> "$log_dir/$log_file" 2>&1
+  } >> "$log_dir/$log_file"
+  trim_log "$log_dir" "$log_file"
+}
 
-  log_len=$(wc -l < "$log_dir/$log_file")
-  [[ "$log_len" -gt 30 ]] && sed -i '1d' "$log_dir/$log_file"
+main() {
+  local_backup
   exit
 }
 
