apt-search: added functionlib; added option to decline package installation.

diff --git a/apt-search b/apt-search
--- a/apt-search
+++ b/apt-search
@@ -7,42 +7,72 @@
 # Author       : Copyright © 2023, Richard B. Romig, Mosfanet
 # Email        : rick.romig@gmail.com | rick.romig@mymetronet.com
 # Created      : 22 Nov 2023
-# Last updated : 25 Jun 2025
-# Comments     : Kris Occipinti, https://filmsbykris.com/v7/
+# Last updated : 15 Jul 2025
+# Comments     : Based on a script by Kris Occipinti, https://filmsbykris.com/v7/
 #              : https://gitlab.com/metalx1000/MyBin/-/blob/master/linux/shell/apt-search
 # TODO (Rick)  :
 # License      : GNU General Public License, version 2.0
+# License URL  : https://github.com/RickRomig/scripts/blob/main/LICENSE
+##########################################################################
+# This program is free software; you can redistribute it and/or modify
+# it under the terms of the GNU General Public License as published by
+# the Free Software Foundation; either version 2 of the License, or
+# (at your option) any later version.
+#
+# This program is distributed in the hope that it will be useful,
+# but WITHOUT ANY WARRANTY; without even the implied warranty of
+# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 ###############################################################################
 
-check_fzf() {
-	command -v fzf > /dev/null 2>&1 && return 0 || return 1
-}
+## Shellcheck Directives ##
+# shellcheck source=/home/rick/bin/functionlib
 
-leave() {
-	local script="${0##*/}"
-	local version="2.1.25176"
-	printf "%s %s\n" "$script" "$version"
-	exit
-}
+## Source function library ##
+
+if [[ -x "$HOME/bin/functionlib" ]]; then
+  source "$HOME/bin/functionlib"
+else
+  printf "\e[91mERROR:\e[0m functionlib not found!\n" >&2
+  exit 1
+fi
+
+## Funtions ##
 
 run_query() {
+	local query="$1"
 	local pkg
-	pkg="$(aptitude search "$query" | fzf --prompt "Select packages: " -m | awk '{print $2}' | tr "\n" " ")"
-	[[ "$pkg" ]] || leave
-	sudo apt install "$pkg"
+	pkg="$(aptitude search "$query" | fzf --prompt "Select packages: " -m | awk '{print $2}' | tr -d '\n')"
+	if [[ "$pkg" ]]; then
+		if default_no	"Install ${pkg}?"; then
+			sudo_login 2
+			sudo apt install "$pkg"
+		else
+			printf "%s was not installed.\n" "$pkg"
+		fi
+	else
+		printf "No package selected.\n" >&2
+	fi
 }
 
 main() {
+	local script="${0##*/}"
+	local version="3.0.25196"
 	local query
-	check_fzf || { echo "fzf is not installed." >&2; leave; }
+	check_package fzf
 	if [[ "$1" ]]; then
 		query="$1"
 	else
 		read -rp "Enter search query: " query
 	fi
-	[[ "$query" ]] || leave
-	run_query
-	leave
+	if [[ "$query" ]]; then
+		run_query "$query"
+	else
+		printf "No search query entered.\n"
+	fi
+	over_line "$script $version"
+	exit
 }
+
+## Execution ##
 
 main "$@"
