battery-check - added main() & battery_check() to check arguments and run operations.

diff --git a/battery-check b/battery-check
--- a/battery-check
+++ b/battery-check
@@ -7,9 +7,8 @@
 # Author       : Copyright (C) 2020, Richard B. Romig, Mosfanet
 # Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
 # Created      : 28 Jul 2020
-# Updated      : 23 Sep 2024
+# Updated      : 30 Sep 2024
 # Comments     : Uses data from /sys/class/power_supply/BAT*
-#              : Battery charge based on a script by Luke Smith (https://lukesmith.xyz)
 # TODO (Rick)  :
 # License      : GNU General Public License, version 2
 ###############################################################################
@@ -28,20 +27,20 @@ fi
 
 ## Global Variables ##
 
-_script=$(basename "$0"); readonly _script
-readonly _version="6.5.24267"
-readonly _updated="23 Sep 2024"
-
+  script=$(basename "$0"); readonly script
+  readonly version="6.6.24274"
 
 ## Functions ##
 
 help() {
-  local errcode="${1:-2}"
+  local errcode updated
+  errcode="${1:-2}"
+  updated="30 Sep 2024"
   cat << END_HELP
-${orange}$_script${normal} $_version, Upated: $_updated
+${orange}$script${normal} $version, Upated: $updated
 Shows battery charge and health information
 
-${green}Usage:${normal} $_script [OPTION]
+${green}Usage:${normal} $script [OPTION]
 
 ${orange}Available options:${normal}
   -h,--help     Show this help text
@@ -53,7 +52,7 @@ END_HELP
 
 version() {
   cat << VER_INFO
-$_script $_version, Updated: $_updated
+$script $version, Updated: $updated
 Displays the charge state and health of a laptop battery using data obtained
 from files in /sys/class/power_supply/BAT*. Capacity information may be shown
 in either Ampere-hours (Ah) or Watt-hours (Wh), depending on your system.
@@ -169,41 +168,49 @@ hidpp_battery() {
   done
 }
 
+battery_check() {
+  local battery_name battery_path
+  printf "%s%sBattery Information%s\n" "$bold" "$orange" "$normal"
+  if [[ -d /proc/acpi/button/lid/ ]]; then
+    battery_name=$(find /sys/class/power_supply/ -name "BAT*" | awk -F/ '/BAT/ {print $5}')
+    if [[ -n "$battery_name" ]]; then
+      battery_path="/sys/class/power_supply/$battery_name"
+      printf "\n%sBattery:%s %s\n" "$orange" "$normal" "$battery_name"
+      battery_status
+      battery_capacity
+      battery_specs
+    else
+      printf "\n%sNo battery detected%s\n" "$lightred" "$normal" >&2
+    fi
+    ac_power
+    hidpp_battery
+  else
+    printf "\nThis system is not a laptop.\n" >&2
+  fi
+  leave "$script v$version"
+
+}
+
+main() {
+  if [[ $# -gt 0 ]]; then
+    case "$1" in
+      -h|--help )
+        help 0
+      ;;
+      -v|--version )
+        version
+        exit
+      ;;
+      * )
+        printf "%s Invalid argument - %s\n" "$red_error" "$1" >&2
+        help 2
+    esac
+  fi
+  check_package bc
+  battery_check
+}
+
 ## Execution ##
 
-if [[ $# -gt 0 ]]; then
-  case "$1" in
-    -h|--help )
-      help 0
-    ;;
-    -v|--version )
-      version
-      exit
-    ;;
-    * )
-      printf "%s Invalid argument - %s\n" "$red_error" "$1" >&2
-      help 2
-  esac
-fi
-
-check_package bc
 clear
-printf "%s%sBattery Information%s\n" "$bold" "$orange" "$normal"
-if [[ -d /proc/acpi/button/lid/ ]]; then
-  battery_name=$(find /sys/class/power_supply/ -name "BAT*" | awk -F/ '/BAT/ {print $5}')
-  if [[ -n "$battery_name" ]]; then
-    battery_path="/sys/class/power_supply/$battery_name"
-    printf "\n%sBattery:%s %s\n" "$orange" "$normal" "$battery_name"
-    battery_status
-    battery_capacity
-    battery_specs
-  else
-    printf "\n%sNo battery detected%s\n" "$lightred" "$normal" >&2
-  fi
-  ac_power
-  hidpp_battery
-else
-  printf "\nThis system is not a laptop.\n" >&2
-fi
-printf "\n%s v%s\n" "$_script" "$_version"
-exit
+main "$@"
