battery-check 0.5.3: Updated help function. Corrected minor spelling, formatting.

diff --git a/battery-check b/battery-check
--- a/battery-check
+++ b/battery-check
@@ -30,8 +30,8 @@ fi
 ## Variables ##
 
 _script=$(basename "$0"); readonly _script
-readonly _version="0.5.2"
-readonly _updated="05 Apr 2023"
+readonly _version="0.5.3"
+readonly _updated="15 May 2023"
 
 ## Functions ##
 
@@ -43,6 +43,7 @@ help() {
   ${orange}OPTIONS:${normal}
   -h        # displays this help message.
   --help    # displays this help message.
+  -v        # displays the version and information about the script.
   --version # displays the version and information about the script.
   $_script $_version, Upated: $_updated
 EOF
@@ -51,7 +52,7 @@ EOF
 
 version() {
   cat <<- EOF
-  $_script $_version, Upated: $_updated
+  $_script $_version, Updated: $_updated
   Displays the charge state and health of a laptop battery using data obtained
   from files in /sys/class/power_supply/BAT*. Capacity information may be shown
   in either Ampere-hours (Ah) or Watt-hours (Wh), depending on your system.
@@ -64,7 +65,7 @@ battery_status() {
   bat_status=$(cat "$battery_path/status")
   [[ -f "$battery_path/capacity" ]] || die "Problem with the battery! Replace it!"
   bat_charge=$(cat "$battery_path/capacity")
-  [[ "$bat_status" = "Discharging" && "$bat_charge" -le 25 ]] && warn="\U26A0\UFE0F"
+  [[ "$bat_status" == "Discharging" && "$bat_charge" -le 25 ]] && warn="\U26A0\UFE0F"
   echo -e "\t${lightgreen}Status:${normal} $bat_status"
   echo -e "\t${lightgreen}Charge:${normal} $bat_charge%  $warn"
 }
@@ -128,9 +129,14 @@ ac_power() {
     ac_status="$(cat "$ac_path/online")"
     echo -en "\tLaptop"
     case "$ac_status" in
-      0 ) echo " is not plugged in to AC power." ;;
-      1 ) echo " is plugged in to AC power." ;;
-      * ) echo "'s AC power status cannot be determined." ;;
+      0 )
+        echo " is not plugged in to AC power."
+      ;;
+      1 )
+        echo " is plugged in to AC power."
+      ;;
+      * )
+        echo "'s AC power status cannot be determined."
     esac
   done
 }
@@ -153,9 +159,16 @@ hidpp_battery() {
 clear
 if [[ $# -gt 0 ]]; then
   case "$1" in
-    -h|--help ) help 0 ;;
-    -v|--version ) version; exit ;;
-    * ) echo "${lightred}Invalid argument: $1${normal}" >&2; help 2 ;;
+    -h|--help )
+      help 0
+    ;;
+    -v|--version )
+      version
+      exit
+    ;;
+    * )
+      echo "${lightred}Invalid argument: $1${normal}" >&2
+      help 2
   esac
 fi
 
