battery-check: battery_specs() process substituion for manufacturer name

diff --git a/battery-check b/battery-check
--- a/battery-check
+++ b/battery-check
@@ -7,13 +7,13 @@
 # Author       : Copyright (C) 2020, Richard B. Romig, Mosfanet
 # Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
 # Created      : 28 Jul 2020
-# Updated      : 10 Apr 2026
+# Updated      : 16 May 2026
 # Comments     : Uses data from /sys/class/power_supply/BAT*
 # TODO (Rick)  :
 # License      : GNU General Public License, version 2
 # License URL  : https://github.com/RickRomig/scripts/blob/main/LICENSE
 ##########################################################################
-# This program is free software; you can redistribute it and/or modify
+# This program is free s26100oftware; you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
 # the Free Software Foundation; either version 2 of the License, or
 # (at your option) any later version.
@@ -26,7 +26,7 @@
 
 ## Load function library ##
 # shellcheck source=/home/rick/bin/functionlib
-source functionlib || { printf "\e[91mERROR:\e[0m Unable to source functionlib\n"; exit 1; }
+source ~/bin/functionlib || { printf "\e[91mERROR:\e[0m Unable to source functionlib\n"; exit 1; }
 
 ## Global Variables ##
 
@@ -109,7 +109,7 @@ battery_specs() {
   battery_serial=$(awk -F= '/SERIAL/ {print $NF}' <<< "$battery_data")
   [[ -z "$battery_serial" || "$battery_serial" == " " ]] && battery_serial="Not specified"
   printf "\n%sBattery Data:%s\n" "$orange" "$normal"
-  printf "%4s%sManufacturer:%s  %s\n" " " "$lightgreen" "$normal" "$(awk -F= '/MANUFACTURER/ {print $NF}' <<< "$battery_data" | sed 's/^ //')"
+  printf "%4s%sManufacturer:%s  %s\n" " " "$lightgreen" "$normal" "$(sed 's/^ //' < <(awk -F= '/MANUFACTURER/ {print $NF}' <<< "$battery_data"))"
   printf "%4s%sModel name:%s    %s\n" " " "$lightgreen" "$normal" "$(awk -F= '/MODEL/ {print $NF}' <<< "$battery_data")"
   printf "%4s%sSerial number:%s %s\n" " " "$lightgreen" "$normal" "$battery_serial"
   printf "%4s%sTechnology:%s    %s\n" " " "$lightgreen" "$normal" "$(awk -F= '/TECHNOLOGY/ {print $NF}' <<< "$battery_data")"
@@ -170,7 +170,7 @@ battery_check() {
 
 main() {
   local script="${0##*/}"
-  local version="7.7.26100"
+  local version="7.8.26136"
   clear
   check_package bc
   battery_check
