battery-check - updated help & version functions; changed 'Invalid argument' to show 'ERROR' in red.

diff --git a/battery-check b/battery-check
--- a/battery-check
+++ b/battery-check
@@ -7,7 +7,7 @@
 # Author       : Copyright (C) 2020, Richard B. Romig, Mosfanet
 # Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
 # Created      : 28 Jul 2020
-# Updated      : 14 Jun 2024
+# Updated      : 23 Sep 2024
 # Comments     : Uses data from /sys/class/power_supply/BAT*
 #              : Battery charge based on a script by Luke Smith (https://lukesmith.xyz)
 # TODO (Rick)  :
@@ -26,37 +26,38 @@ else
   exit 1
 fi
 
-## Variables ##
+## Global Variables ##
 
 _script=$(basename "$0"); readonly _script
-readonly _version="6.4.24166"
-readonly _updated="14 Jun 2024"
+readonly _version="6.5.24267"
+readonly _updated="23 Sep 2024"
+
 
 ## Functions ##
 
 help() {
   local errcode="${1:-2}"
-  cat << EOF
+  cat << END_HELP
 ${orange}$_script${normal} $_version, Upated: $_updated
 Shows battery charge and health information
 
-${green}Usage:${normal} $_script [-h|--help]
-       $_script [-v|--version]
+${green}Usage:${normal} $_script [OPTION]
 
-${orange}Options:${normal}
+${orange}Available options:${normal}
   -h,--help     Show this help text
   -v,--version  Show version and information
-EOF
+  With no argument, displays battery health information.
+END_HELP
   exit "$errcode"
 }
 
 version() {
-  cat << EOF
+  cat << VER_INFO
 $_script $_version, Updated: $_updated
 Displays the charge state and health of a laptop battery using data obtained
 from files in /sys/class/power_supply/BAT*. Capacity information may be shown
 in either Ampere-hours (Ah) or Watt-hours (Wh), depending on your system.
-EOF
+VER_INFO
 }
 
 battery_status() {
@@ -104,9 +105,9 @@ battery_capacity() {
 }
 
 battery_condition() {
-  local warn_level warn
-  local cap_pct="$1"
-  local c_pct="${cap_pct%%.*}"
+  local cap_pct c_pct warn_level warn
+  cap_pct="$1"
+  c_pct="${cap_pct%%.*}"
   if [[ "$c_pct" -eq 0 ]]; then
     warn_level=0
   else
@@ -180,7 +181,7 @@ if [[ $# -gt 0 ]]; then
       exit
     ;;
     * )
-      printf "%sInvalid argument: %s%s\n" "$lightred" "$1" "$normal" >&2
+      printf "%s Invalid argument - %s\n" "$red_error" "$1" >&2
       help 2
   esac
 fi
