battery-check: tabs

diff --git a/battery-check b/battery-check
--- a/battery-check
+++ b/battery-check
@@ -7,8 +7,8 @@
 # Author       : Copyright (C) 2020, Richard B. Romig, Mosfanet
 # Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
 # Created      : 28 Jul 2020
-# Updated      : 06 Aug 2026
-# Version      : 7.9.26218
+# Updated      : 06 Sep 2026
+# Version      : 7.9.26249
 # Comments     : Uses data from /sys/class/power_supply/BAT*
 # TODO (Rick)  :
 # License      : GNU General Public License, version 2
@@ -30,156 +30,156 @@ source ~/bin/functionlib.bash || { printf "\e[91mERROR:\e[0m Unable to source fu
 BATTERY_PATH=''
 
 battery_status() {
-  local bat_status bat_charge
-  local warn=''
-  printf "\n%sBattery charge:%s\n" "$orange" "$normal"
-  [[ -f "$BATTERY_PATH/status" ]] || die "Problem with the battery! Replace it!" 99
-  bat_status=$(cat "$BATTERY_PATH/status")
-  [[ -f "$BATTERY_PATH/capacity" ]] || die "Problem with the battery! Replace it!" 99
-  bat_charge=$(cat "$BATTERY_PATH/capacity")
-  [[ "$bat_status" == "Discharging" && "$bat_charge" -le 25 ]] && warn="\U26A0\UFE0F"
-  printf "%4s%sStatus:%s %s\n" " " "$lightgreen" "$normal" "$bat_status"
-  printf "%4s%sCharge:%s %s%%%s\n" " " "$lightgreen" "$normal" "$bat_charge" "$warn"
-  return 0
+	local bat_status bat_charge
+	local warn=''
+	printf "\n%sBattery charge:%s\n" "$orange" "$normal"
+	[[ -f "$BATTERY_PATH/status" ]] || die "Problem with the battery! Replace it!" 99
+	bat_status=$(cat "$BATTERY_PATH/status")
+	[[ -f "$BATTERY_PATH/capacity" ]] || die "Problem with the battery! Replace it!" 99
+	bat_charge=$(cat "$BATTERY_PATH/capacity")
+	[[ "$bat_status" == "Discharging" && "$bat_charge" -le 25 ]] && warn="\U26A0\UFE0F"
+	printf "%4s%sStatus:%s %s\n" " " "$lightgreen" "$normal" "$bat_status"
+	printf "%4s%sCharge:%s %s%%%s\n" " " "$lightgreen" "$normal" "$bat_charge" "$warn"
+	return 0
 }
 
 battery_capacity() {
-  local actual_full design_full unit actual_max design_max int_design int_actual cap_percent bat_health
-  if [[ -f "$BATTERY_PATH/charge_full" ]]; then
-    actual_full="charge_full"
-    design_full="charge_full_design"
-    unit="Ah"
-  else
-    actual_full="energy_full"
-    design_full="energy_full_design"
-    unit="Wh"
-  fi
+	local actual_full design_full unit actual_max design_max int_design int_actual cap_percent bat_health
+	if [[ -f "$BATTERY_PATH/charge_full" ]]; then
+		actual_full="charge_full"
+		design_full="charge_full_design"
+		unit="Ah"
+	else
+		actual_full="energy_full"
+		design_full="energy_full_design"
+		unit="Wh"
+	fi
 
-  actual_max=$(awk 'NF{print $1/1000000}' OFMT="%2.2f" "$BATTERY_PATH/$actual_full")
-  design_max=$(awk 'NF{print $1/1000000}' OFMT="%2.2f" "$BATTERY_PATH/$design_full")
-  int_design="${design_max%%.*}"  # changes design_max to an integer value
-  int_actual="${actual_max%%.*}"  # changes actual_max to an integer value
+	actual_max=$(awk 'NF{print $1/1000000}' OFMT="%2.2f" "$BATTERY_PATH/$actual_full")
+	design_max=$(awk 'NF{print $1/1000000}' OFMT="%2.2f" "$BATTERY_PATH/$design_full")
+	int_design="${design_max%%.*}"  # changes design_max to an integer value
+	int_actual="${actual_max%%.*}"  # changes actual_max to an integer value
 
-  if [[ "$int_design" -eq 0 || "$int_actual" -eq 0 ]]; then
-    cap_percent="0"
-    bat_health="0"
-  else
-    cap_percent=$(bc -l <<< "100/${design_max}*${actual_max}")
-    bat_health=$(awk 'NF{print $1/1}' OFMT="%2.2f" <<< "$cap_percent")
-  fi
+	if [[ "$int_design" -eq 0 || "$int_actual" -eq 0 ]]; then
+		cap_percent="0"
+		bat_health="0"
+	else
+		cap_percent=$(bc -l <<< "100/${design_max}*${actual_max}")
+		bat_health=$(awk 'NF{print $1/1}' OFMT="%2.2f" <<< "$cap_percent")
+	fi
 
-  printf "\n%sBattery health:%s\n" "$orange" "$normal"
-  printf "%4s%sActual capacity:%s %s %s\n" " " "$lightgreen" "$normal" "$actual_max" "$unit"
-  printf "%4s%sDesign capacity:%s %s %s\n" " " "$lightgreen" "$normal" "$actual_max" "$unit"
-  printf "%4s%sBattery health%s   %s %%\n" " " "$lightgreen" "$normal" "$bat_health"
-  battery_condition "$cap_percent"
-  return 0
+	printf "\n%sBattery health:%s\n" "$orange" "$normal"
+	printf "%4s%sActual capacity:%s %s %s\n" " " "$lightgreen" "$normal" "$actual_max" "$unit"
+	printf "%4s%sDesign capacity:%s %s %s\n" " " "$lightgreen" "$normal" "$actual_max" "$unit"
+	printf "%4s%sBattery health%s   %s %%\n" " " "$lightgreen" "$normal" "$bat_health"
+	battery_condition "$cap_percent"
+	return 0
 }
 
 battery_condition() {
-  local -r cap_pct="$1"
-  local c_pct warn_level warn
-  c_pct="${cap_pct%%.*}"
-  if [[ "$c_pct" -eq 0 ]]; then
-    warn_level=0
-  else
-    warn_level=$(awk 'NF{print $1/1}' OFMT="%.0f" <<< "$cap_pct")
-  fi
+	local -r cap_pct="$1"
+	local c_pct warn_level warn
+	c_pct="${cap_pct%%.*}"
+	if [[ "$c_pct" -eq 0 ]]; then
+		warn_level=0
+	else
+		warn_level=$(awk 'NF{print $1/1}' OFMT="%.0f" <<< "$cap_pct")
+	fi
 
-  if [[ "$warn_level" -le "0" ]]; then
-    warn="\U1F4A9"
-    printf "%4s%sReplace the Battery!%s  %\n" " " "$red" "$normal" "$warn"
-  elif [[ "$warn_level" -le "35" ]]; then
-    warn="\U1F622"
-    printf "%4s%sThe battery should be replaced.%s  %\n" " " "$red" "$normal" "$warn"
-  elif [[ "$warn_level" -le "65" ]]; then
-    warn="\U26A0\UFE0F"
-    printf "%4s%sThe battery is getting weak.%s  %\n" " " "$orange" "$normal" "$warn"
-  else
-    printf "%4s%sThe battery is in good condition.%s\n" " " "$green" "$normal"
-  fi
-  return 0
+	if [[ "$warn_level" -le "0" ]]; then
+		warn="\U1F4A9"
+		printf "%4s%sReplace the Battery!%s  %\n" " " "$red" "$normal" "$warn"
+	elif [[ "$warn_level" -le "35" ]]; then
+		warn="\U1F622"
+		printf "%4s%sThe battery should be replaced.%s  %\n" " " "$red" "$normal" "$warn"
+	elif [[ "$warn_level" -le "65" ]]; then
+		warn="\U26A0\UFE0F"
+		printf "%4s%sThe battery is getting weak.%s  %\n" " " "$orange" "$normal" "$warn"
+	else
+		printf "%4s%sThe battery is in good condition.%s\n" " " "$green" "$normal"
+	fi
+	return 0
 }
 
 battery_specs() {
-  local battery_data battery_serial
-  battery_data=$(cat "$BATTERY_PATH"/uevent)
-  battery_serial=$(awk -F= '/SERIAL/ {print $NF}' <<< "$battery_data")
-  [[ -z "$battery_serial" || "$battery_serial" == " " ]] && battery_serial="Not specified"
-  printf "\n%sBattery Data:%s\n" "$orange" "$normal"
-  printf "%4s%sManufacturer:%s  %s\n" " " "$lightgreen" "$normal" "$(sed 's/^ //' < <(awk -F= '/MANUFACTURER/ {print $NF}' <<< "$battery_data"))"
-  printf "%4s%sModel name:%s    %s\n" " " "$lightgreen" "$normal" "$(awk -F= '/MODEL/ {print $NF}' <<< "$battery_data")"
-  printf "%4s%sSerial number:%s %s\n" " " "$lightgreen" "$normal" "$battery_serial"
-  printf "%4s%sTechnology:%s    %s\n" " " "$lightgreen" "$normal" "$(awk -F= '/TECHNOLOGY/ {print $NF}' <<< "$battery_data")"
-  return 0
+	local battery_data battery_serial
+	battery_data=$(cat "$BATTERY_PATH"/uevent)
+	battery_serial=$(awk -F= '/SERIAL/ {print $NF}' <<< "$battery_data")
+	[[ -z "$battery_serial" || "$battery_serial" == " " ]] && battery_serial="Not specified"
+	printf "\n%sBattery Data:%s\n" "$orange" "$normal"
+	printf "%4s%sManufacturer:%s  %s\n" " " "$lightgreen" "$normal" "$(sed 's/^ //' < <(awk -F= '/MANUFACTURER/ {print $NF}' <<< "$battery_data"))"
+	printf "%4s%sModel name:%s    %s\n" " " "$lightgreen" "$normal" "$(awk -F= '/MODEL/ {print $NF}' <<< "$battery_data")"
+	printf "%4s%sSerial number:%s %s\n" " " "$lightgreen" "$normal" "$battery_serial"
+	printf "%4s%sTechnology:%s    %s\n" " " "$lightgreen" "$normal" "$(awk -F= '/TECHNOLOGY/ {print $NF}' <<< "$battery_data")"
+	return 0
 }
 
 ac_power() {
-  local ac_path ac_status
-  ac_path=$(find /sys/class/power_supply/ -name "AC*")
-  ac_status="$(cat "$ac_path/online")"
-  printf "\n%sAC Power:%s\n" "$orange" "$normal"
-  printf "%4sLaptop" " "
-  case "$ac_status" in
-    0 )
-      printf " is not plugged in to AC power.\n" ;;
-    1 )
-      printf " is plugged in to AC power.\n" ;;
-    * )
-      printf "'s AC power status cannot be determined.\n"
-  esac
-  return 0
+	local ac_path ac_status
+	ac_path=$(find /sys/class/power_supply/ -name "AC*")
+	ac_status="$(cat "$ac_path/online")"
+	printf "\n%sAC Power:%s\n" "$orange" "$normal"
+	printf "%4sLaptop" " "
+	case "$ac_status" in
+		0 )
+			printf " is not plugged in to AC power.\n" ;;
+		1 )
+			printf " is plugged in to AC power.\n" ;;
+		* )
+			printf "'s AC power status cannot be determined.\n"
+	esac
+	return 0
 }
 
 hidpp_battery() {
-  local hidpp_path
-  printf "\n%sHID++ Battery:%s\n" "$orange" "$normal"
-  for hidpp_path in /sys/class/power_supply/hidpp_battery_?; do
-    if [[ "$hidpp_path" != "/sys/class/power_supply/hidpp_battery_?" ]]; then
-      printf "%4s%sDevice:%s %s\n" " " "$lightgreen" "$normal" "${hidpp_path##*/}"
-      printf "%4s%s%s %s:%s %s%%\n" " " "$lightgreen" "$(cat "$hidpp_path/manufacturer")" \
-      "$(cat "$hidpp_path/model_name")" "$normal" "$(cat "$hidpp_path/capacity")"
-    else
-      printf "%4sHID++ battery not present.\n" " "
-    fi
-  done
-  return 0
+	local hidpp_path
+	printf "\n%sHID++ Battery:%s\n" "$orange" "$normal"
+	for hidpp_path in /sys/class/power_supply/hidpp_battery_?; do
+		if [[ "$hidpp_path" != "/sys/class/power_supply/hidpp_battery_?" ]]; then
+			printf "%4s%sDevice:%s %s\n" " " "$lightgreen" "$normal" "${hidpp_path##*/}"
+			printf "%4s%s%s %s:%s %s%%\n" " " "$lightgreen" "$(cat "$hidpp_path/manufacturer")" \
+			"$(cat "$hidpp_path/model_name")" "$normal" "$(cat "$hidpp_path/capacity")"
+		else
+			printf "%4sHID++ battery not present.\n" " "
+		fi
+	done
+	return 0
 }
 
 battery_check() {
-  local battery_name
-  printf "%s%sBattery Information%s\n" "$bold" "$orange" "$normal"
-  if [[ ! -d /proc/acpi/button/lid/ ]]; then
-    printf "\nThis system is not a laptop.\n" >&2
-    return "$E_UNSUPPORTED"
-  fi
-  BATTERY_PATH=$(find /sys/class/power_supply/ -name "BAT*")
-  battery_name="${BATTERY_PATH##*/}"
-  if [[ -z "$battery_name" ]]; then
-    printf "\n%sNo battery detected%s\n" "$lightred" "$normal" >&2
-    ac_power
-    hidpp_battery
-    return "$E_NOT_DETECTED"
-  fi
-  printf "\n%sBattery:%s %s\n" "$orange" "$normal" "$battery_name"
-  battery_status
-  battery_capacity
-  battery_specs
-  ac_power
-  hidpp_battery
-  return 0
+	local battery_name
+	printf "%s%sBattery Information%s\n" "$bold" "$orange" "$normal"
+	if [[ ! -d /proc/acpi/button/lid/ ]]; then
+		printf "\nThis system is not a laptop.\n" >&2
+		return "$E_UNSUPPORTED"
+	fi
+	BATTERY_PATH=$(find /sys/class/power_supply/ -name "BAT*")
+	battery_name="${BATTERY_PATH##*/}"
+	if [[ -z "$battery_name" ]]; then
+		printf "\n%sNo battery detected%s\n" "$lightred" "$normal" >&2
+		ac_power
+		hidpp_battery
+		return "$E_NOT_DETECTED"
+	fi
+	printf "\n%sBattery:%s %s\n" "$orange" "$normal" "$battery_name"
+	battery_status
+	battery_capacity
+	battery_specs
+	ac_power
+	hidpp_battery
+	return 0
 }
 
 main() {
-  local -r script="${0##*/}"
-  local -r version="7.9.26218"
-  local -i exit_code=0
-  clear
-  check_package bc
-  battery_check
-  exit_code="$?"
-  over_line "$script $version"
-  exit "$exit_code"
+	local -r script="${0##*/}"
+	local -r version="7.9.26249"
+	local -i exit_code=0
+	clear
+	check_package bc
+	battery_check
+	exit_code="$?"
+	over_line "$script $version"
+	exit "$exit_code"
 }
 
 main "$@"
