bs-meter: changed sourcing of functionlib

diff --git a/bs-meter b/bs-meter
--- a/bs-meter
+++ b/bs-meter
@@ -7,7 +7,7 @@
 # Author       : Copyright (C) 2019, Richard B. Romig
 # Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
 # Created      : 17 Aug 2019
-# Last updated : 25 Feb 2026
+# Last updated : 04 Apr 2026
 # Comments     : For entertainiment purposes only.
 # TODO (Rick)  :
 # License      : GNU General Public License, version 2
@@ -28,13 +28,7 @@
 # shellcheck source=/home/rick/bin/functionlib
 
 ## Load function library ##
-
-if [[ -x "$HOME/bin/functionlib" ]]; then
-  source "$HOME/bin/functionlib"
-else
-  printf "\e[91mERROR:\e[0m functionlib not found!\n" >&2
-  exit 81
-fi
+source ~/bin/functionlib || { printf "\e[91mERROR:\e[0m Unable to source functionlib\n"; exit 1; }
 
 ## Global Variables ##
 
@@ -120,7 +114,7 @@ print_intro() {
 main() {
   local _statement bs_level
   local script="${0##*/}"
-  local version="5.7.26055"
+  local version="5.8.26094"
   bs_level=$(shuf -i 0-100 -n 1)
   clear
   print_intro
