bu - broke original help function into separate functions and included as options.

diff --git a/bu b/bu
--- a/bu
+++ b/bu
@@ -7,7 +7,7 @@
 # Author       : Copyright (C) 2023, Richard B. Romig
 # Email        : rick.romig@gmail.com | rick.romig@mymetronet.com
 # Created      : 04 Feb 2023
-# Last updated : 26 Apr 2024
+# Last updated : 14 Jun 2024
 # Comments     : Based on BU USB Backup Tool (Version 1.1) by Joe Collins. (https://www.ezeelinux.com)
 #              : Joe's code at: https://github.com/EzeeLinux/bu-usb_backup_tool
 # TODO (Rick)  :
@@ -33,7 +33,9 @@ fi
 
 ## Global Variables ##
 
-readonly _version="4.2.24117"
+_script=$(basename "$0"); readonly _script
+readonly _version="4.3.24166"
+readonly _updated="14 Jun 2024"
 readonly user=$USER
 readonly host="${HOSTNAME:-$(hostname)}"
 readonly mount_point="/media/$user/BU_Drive"
@@ -44,7 +46,7 @@ exit_status=0
 drive_test() {
 	printf "%sChecking Backup USB Drive%s\n" "$green" "$normal"
   check_usb || die "No USB drive connected!" 1
-	bu_drive_label || die "Invalid partition label. Run 'bu -h' for drive setup information." 1
+	bu_drive_label || die "Invalid partition label. Run 'bu -s' for drive setup information." 1
   check_uuid || die "Incorrect drive to backup $host." 1
   mount | grep -qw BU_Drive > /dev/null 2>&1 || mount_bu
   bu_drive_fs || die "Drive must be formatted with EXT4 or XFS." 1
@@ -100,15 +102,13 @@ sync_drives() {
 }
 
 unmount_usb_drive() {
-  sudo umount "$mount_point" && printf "BU_Drive unmounted.\n"
-  [[ -d "$mount_point" ]] && sudo rmdir "$mount_point"
-  printf "It is now safe to remove the USB drive.\n"
-}
-
-display_title() {
-  box "BU -- USB Backup Tool (Version $_version)"
-  printf "Copyright \UA9 2019, Joe Collins\n"
-  printf "Copyright \UA9 2023, Rick Romig\n\n"
+	if y_or_n "Unmount BU_Drive?"; then
+		sudo umount "$mount_point" && printf "BU_Drive unmounted.\n"
+		[[ -d "$mount_point" ]] && sudo rmdir "$mount_point"
+		printf "It is now safe to remove the USB drive.\n"
+	else
+		printf "BU_Drive is still mounted.\n"
+	fi
 }
 
 bu_prep() {
@@ -178,15 +178,25 @@ restore() {
 }
 
 help() {
-less << END_HELP
- Press "q" to exit this Help page.
+cat << END_HELP
+${orange}$_script${normal} $_version, Upated: $_updated
+Backup /etc/ and /home/ directories to an external drive.
 
- Commands:
+${green}Usage:${normal} $_script [OPTION]
 
- bu -b = Fully backs up the host /etc and /home directories.
- bu -h = Prints this help information.
- bu -r = Accesses BU Restore function to restore host /home directory.
+${orange}Available options:${normal}
+  -b  Fully backs up the host /etc and /home directories.
+  -d  Disclaimer
+  -h  Prints this help text.
+  -i  Information about this script.
+  -r  Restore the host /home directory.
+  -s  Setting up the BU_Drive
 
+END_HELP
+}
+
+show_description() {
+	cat << _DESCRIPTION_
  Description:
 
  BU is a program that makes keeping all of your user data safely backed up on
@@ -209,20 +219,30 @@ less << END_HELP
  made from. It is intended for emergency use, as when significant number of
  directories and files are accidentally removed from /home.
 
+_DESCRIPTION_
+}
+
+drive_setup() {
+	cat << _SETUP_
  BU_Drive Setup:
 
- You need to prepare a BU Drive with a tool like Gparted or Disks.
+ You need to prepare a BU Drive with a tool like Gparted or Gnone Disks.
  This can be any USB storage device. The dedicated USB drive MUST contain a
  partition formatted with a Linux native file system such as Ext4 or XFS. The
  partition MUST be labeled "BU_Drive" so BU can find it and use it for backups.
  The partition needs to have enough free capacity to store all data in /home on
  all of the machines you want to use the drive for. Note: The script will only
- allow media formatted with Ext4 or XFS. Bon-native file systems like FAT32 or NTFS
- will cause the script to exit with an error.
+ allow media formatted with Ext4 or XFS. Non-native file systems like FAT32 or
+ NTFS will cause the script to exit with an error.
 
+_SETUP_
+}
+
+show_disclaimer() {
+	cat << _DISCLAIMER_
  Disclaimer:
 
- THIS SOFTWARE IS PROVIDED BY EZEELINUX “AS IS” AND ANY EXPRESS OR IMPLIED
+ THIS SOFTWARE IS PROVIDED BY EZEELINUX "AS IS" AND ANY EXPRESS OR IMPLIED
  WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
  MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO
  EVENT SHALL EZEELINUX BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
@@ -233,49 +253,60 @@ less << END_HELP
  ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
  POSSIBILITY OF SUCH DAMAGE.
 
-END_HELP
+_DISCLAIMER_
 }
 
 ## Execution ##
 
 # Start timer
 SECONDS=0
+box "BU -- USB Backup Tool (Version $_version)"
+printf "Copyright \UA9 2019, Joe Collins\n"
+printf "Copyright \UA9 2023, Rick Romig\n\n"
 
 noOpt=1
-optstr=":bhr"
+optstr=":bdhirs"
 while getopts "$optstr" opt; do
 	case "$opt" in
 		b )
 			sudo_login 2
-			display_title
 			drive_test
 			check_package rsync
 			backup
 			sync_drives
 			unmount_usb_drive
 		;;
+		d )
+			show_disclaimer
+			mount | grep -qw BU_Drive > /dev/null 2>&1 && unmount_usb_drive
+		;;
 		h )
-			display_title
 			help
+			mount | grep -qw BU_Drive > /dev/null 2>&1 && unmount_usb_drive
+		;;
+		i )
+			show_description
 			mount | grep -qw BU_Drive > /dev/null 2>&1 && unmount_usb_drive
 		;;
 		r )
 			sudo_login 2
-			display_title
 			drive_test
 			check_package rsync
 			restore
 	    sync_drives
 			unmount_usb_drive
 		;;
+		s )
+			drive_setup
+			mount | grep -qw BU_Drive > /dev/null 2>&1 && unmount_usb_drive
+		;;
 		? )
 			printf "%s Invalid option -%s\n" "$red_error" "$OPTARG" >&2
-			printf "Valid options:\n" >&2
-			printf "\tbu -%s\n" "b = backup" "h = help" "r = restore" >&2
+			help
 	esac
 	noOpt=0
 done
-[[ "$noOpt" = 1 ]] && { printf "%s No argument passed.\n" "$red_error" >&2; show_options; }
+[[ "$noOpt" = 1 ]] && { printf "%s No argument passed.\n" "$red_error" >&2; help; }
 shift "$(( OPTIND - 1 ))"
 printf "Script completed in %s\n" "$(format_time $SECONDS)"
 if [[ "$exit_status" -eq 0 ]]; then
