bu: changed sourcing method for functionlib; is_deb_13() replace if-else with double bracket tests

diff --git a/bu b/bu
--- a/bu
+++ b/bu
@@ -7,7 +7,7 @@
 # Author       : Copyright (C) 2023, Richard B. Romig
 # Email        : rick.romig@gmail.com | rick.romig@mymetronet.com
 # Created      : 04 Feb 2023
-# Last updated : 02 Apr 2026
+# Last updated : 05 Apr 2026
 # Comments     : Based on BU USB Backup Tool (Version 1.1) by Joe Collins.
 # TODO (Rick)  :
 # License      : GNU General Public License, version 2.0
@@ -24,22 +24,14 @@
 # GNU General Public License for more details.
 ##############################################################################
 
-## Shellcheck Directives ##
+## Load function library ##
 # shellcheck source=/home/rick/bin/functionlib
-
-# Load function library
-
-if [[ -x "$HOME/bin/functionlib" ]]; then
-  source "$HOME/bin/functionlib"
-else
-  printf "\e[91mERROR:\e[0m functionlib not found!\n" >&2
-  exit 81
-fi
+source functionlib || { printf "\e[91mERROR:\e[0m Unable to source functionlib\n"; exit 1; }
 
 ## Global Variables ##
 
 readonly script="${0##*/}"
-readonly version="6.7.26092"
+readonly version="6.7.26095"
 user=$(whoami); readonly user
 readonly host="${HOSTNAME:-$(hostname)}"
 readonly mount_point="/media/$user/BU_Drive"
@@ -96,11 +88,9 @@ check_uuid() {
 
 is_deb_13() {
 	local deb_ver
-	if is_debian; then
-		deb_ver=$(cut -d'.' -f1 < /etc/debian_version)
-		[[ $deb_ver -ge 13 ]] && return "$TRUE" || return "$FALSE"
-	fi
-	return "$FALSE"
+	is_debian || return "$FALSE"
+	deb_ver=$(cut -d'.' -f1 < /etc/debian_version)
+	[[ $deb_ver -ge 13 ]] && return "$TRUE" || return "$FALSE"
 }
 
 mount_bu() {
@@ -234,7 +224,7 @@ restore() {
 
 help() {
 	local errcode="${1:-1}"
-	local updated="02 Apr 2026"
+	local updated="05 Apr 2026"
 	cat << _HELP_
 ${orange}$script${normal} $version, Updated: $updated
 Backup /etc/ and /home/ directories to an external USB drive.
