bu 2.1 - updated.

diff --git a/bu b/bu
--- a/bu
+++ b/bu
@@ -7,7 +7,7 @@
 # Author       : Copyright (C) 2023, Richard B. Romig, Created: 04 Feb 2023
 # Email        : rick.romig@gmail.com | rick.romig@mymetronet.com
 # Comments     : Based on USB Backup Tool (Version 1.1) by Joe Collins. (www.ezeelinux.com)
-# Last updated : 04 Feb 2023
+# Last updated : 05 Feb 2023
 # TODO (Rick)  : 
 # License      : GNU General Public License, version 2.0
 ###############################################################################
@@ -34,7 +34,7 @@ else
 fi
 
 # Declare static variables:
-readonly _version="2.0"
+readonly _version="2.1"
 readonly user=$USER
 readonly host=$HOSTNAME
 
@@ -276,8 +276,8 @@ elif [[ "$1" == "--restore" ]]; then
 	drive_test
 	restore
 elif  [[ -n "$1" ]]; then
-  echo "BU Error: Invalid argument. " >&2
-  echo "- Try 'bu --help' to see the available commands. :)" >&2
+  printf "BU Error: Invalid argument.\n" >&2
+  printf "- Try 'bu --help' to see the available commands.\n" >&2
   exit 1
 fi
 
