bu 3.0 - Broke drive_test down to call individual functions to test backup drive attributes. Made sync routine a function. Placed default action in the command line arguments check as the else condition if no arguments are passed.

diff --git a/bu b/bu
--- a/bu
+++ b/bu
@@ -3,7 +3,7 @@
 # Script Name  : bu
 # Description  : USB backup tool
 # Dependencies : rsync
-# Arguments    : --help, --restore
+# Arguments    : --help, --restore (runs backup by default)
 # Author       : Copyright (C) 2023, Richard B. Romig, Created: 04 Feb 2023
 # Email        : rick.romig@gmail.com | rick.romig@mymetronet.com
 # Comments     : Based on USB Backup Tool (Version 1.1) by Joe Collins. (www.ezeelinux.com)
@@ -13,18 +13,16 @@
 ###############################################################################
 
 # BU -- USB Backup Tool (Version 1.1) -- by Joe Collins. (www.ezeelinux.com)
-# A simple tool to create reliable backups of /etc/ and /home from multiple
 # Debian/Ubuntu Linux systems. (May 10, 2019)
 # (GNU/General Public License version 2.0)
-#
 # For Debian 9 and up, Ubuntu 16.04 and up and Linux Mint 18.x and up.
 
-## Shellcheck Directives ##  (R. Romig)
+## Shellcheck Directives ##
 # shellcheck source=/home/rick/bin/functionlib
 # shellcheck disable=SC1091,SC2034
 
-# Load function library (R. Romig)
-# Adds check_package, die, user_in_sudo and format_time functions
+# Load function library
+# Adds check_package, die, dots, user_in_sudo and format_time functions
 
 if [[ -x "$HOME/bin/functionlib" ]]; then
   source "$HOME/bin/functionlib"
@@ -33,83 +31,79 @@ else
   exit 1
 fi
 
-# Declare static variables:
+## Global Variables ##
 
-readonly _version="2.3"
+readonly _version="3.0"
 readonly user=$USER
 readonly host="${HOSTNAME:-$(hostname)}"
+readonly mount_point="/media/$user/BU_Drive"
 
-# Set functions:
-
-check_dependencies() {
-  local packages=( rsync less )
-  check_packages "${packages[@]}"
-}
+## Functions ##
 
 drive_test() {
-  # Checking for any USB drive:
-  if [[ ! $(lsblk -S -o  TRAN | grep 'usb') = *usb* ]]; then
-    printf "\n%s No USB drive connected!\n" >&2 "$red_error"
-    printf " Check to see that BU_Drive is plugged in.\n" >&2
-    printf " Please run 'bu --help' to learn about drive setup.\n" >&2
-    exit 1
-  fi
+	printf "Checking Backup USB Drive...\n"
+	check_usb || { printf "%s No USB drive connected!\n" >&2 "$red_error"; exit 1;  }
+	[[ -d "$mount_point" ]] || sudo mkdir -p "$mount_point"
+	check_mount || { printf "%s BU_Drive is not mounted. Run 'mount-bu' to mount the drive.\n" >&2 "$red_error"; exit 1; }
+	bu_drive_label || { printf "%s Invalid partition label. Run 'bu --help' for drive setup information." >&2 "$red_error"; exit 1; }
+	bu_drive_fs || { printf "%s Drive must be formatted with EXT4 or XFS." >&2 "$red_error"; exit 1; }
+	printf "Space available on BU_Drive: %s\n" "$(df -h "$mount_point" | tail -n1 | awk '{print $4}')"
+	printf "USB Backup Drive is mounted and meets all criteria.\n"
+}
 
-  # Checking for a USB drive that is setup for BU:
-  if [[ ! -d /media/"$user"/BU_Drive ]]; then
-    printf "\n%s No USB drive with a partition labeled "BU_Drive!"\n" >&2 "$red_error"
-    printf " The drive(s) you have plugged in are not ready for use with BU.\n" >&2
-    printf " Don't launch BU as root or with 'sudo bu.'\n" >&2
-    printf " Please run 'bu --help' to learn about drive setup.\n" >&2
-    exit 1
-  fi
+check_usb() {
+	[[ $(lsblk -S -o  TRAN | grep 'usb') = *usb* ]] && return "$TRUE" || return "$FALSE"
+}
 
-  # Check if the backup drive is mounted. (Romig)
-  mounted=$(mount | grep 'BU_Drive')
-  [ -z "$mounted" ] && die "BU_Drive is not mounted." 1
+check_mount() {
+	mounted=$(mount | grep 'BU_Drive')
+	[[ -n "$mounted" ]] && return "$TRUE" || return "$FALSE"
+}
+
+bu_drive_fs() {
+	fs_type="$(mount | awk '/BU_Drive/ {print $5}')"
+	[[ "$fs_type" == "ext4" || "$fs_type" == "XFS" ]] && return "$TRUE" || return "$FALSE"
+}
+
+bu_drive_label() {
+	bu_label="$(lsblk -o label | grep -w BU_Drive)"
+	[[ -n "$bu_label" ]] && return "$TRUE" || return "$FALSE"
+}
+
+sync_drives() {
+	printf "Wait! Syncing Drives...\n"
+	dots "."
+	sync
+	kill "$!"
+	printf "...done\n"
 }
 
 backup() {
-
-  # Check for sudo privileges:
-
   echo "Checking for sudo privileges..."
-  user_in_sudo     # functionlib
-
+  user_in_sudo
+  
   printf "Changing ownership of BU_Drive to %s...\n" "$user"
-  sudo chown "$user" /media/"${user}"/BU_Drive/
+  sudo chown "$user" "$mount_point"
 
   printf "Checking for/creating machine specific directories...\n"
-  if mkdir -p /media/"$user"/BU_Drive/BU_Backups/"$host"; then
-    printf "...Done. BU_Drive is ready.\n"
-  else
-    printf "\n%s Could not create directory for %s!\n" >&2 "$red_error" "$host"
-    printf "Backup aborted. Check the status of the BU_Drive.\n" >&2
-    exit 1
-  fi
+  [[ -d "$mount_point"/BU_Backups/"$host" ]] || mkdir -p "$mount_point"/BU_Backups/"$host"
+	printf "...Done. BU_Drive is ready.\n"
 
-  # Run rsync command:
-  # The '--exclude 'timeshift''  & 'if-then' added by R. Romig
   printf "Backing up /etc and /home to BU_Drive/BU_Backups/%s/...\n" "$host"
   if sudo rsync -aH --delete --exclude 'timeshift' --exclude '.local/share/libvirt/images' \
-   --info=progress2 /etc /home /media/"$user"/BU_Drive/BU_Backups/"$host"/; then
-    # Check for status of backup and exit:
-    # [ "$?" == "0" ]; then
+   --info=progress2 /etc /home "$mount_point"/BU_Backups/"$host"/; then
     # Clear any accidental input during backup:
     read -rt 1 -n 10000 discard
 
     box "All backed up!" "-"
 
     # Remove old and create new timestamp file:
-    rm -f /media/"$user"/BU_Drive/BU_Backups/"$host"/BU\ Backup* >/dev/null 2>&1
-    touch "/media/$user/BU_Drive/BU_Backups/$host/BU Backup was successful: $(date '+%F')"
+    rm -f /"$mount_point"/BU_Backups/"$host"/BU\ Backup* >/dev/null 2>&1
+    touch "$mount_point/BU_Backups/$host/BU Backup was successful: $(date '+%F')"
 
-    printf "Wait! Syncing Drives...\n"
-    dots "."
-    sync
-    kill "$!"
-    printf "...done\n"
-    sudo umount /media/"$user"/BU_Drive && printf "BU_Drive unmounted.\n"
+		sync_drives
+		
+    sudo umount "$mount_point" && printf "BU_Drive unmounted.\n"
     printf "It's now safe to remove the USB drive.\n"
     printf "Backup completed in %s\n" "$(format_time $SECONDS)"
     exit
@@ -118,12 +112,12 @@ backup() {
     read -rt 1 -n 10000 discard
 
     # Remove old and create new timestamp file:
-    rm -f /media/"$user"/BU_Drive/BU_Backups/"$host"/BU\ Backup* >/dev/null 2>&1
-    touch "/media/$user/BU_Drive/BU_Backups/$host/BU Backup had some errors: $(date)"
+    rm -f "$mount_point"/BU_Backups/"$host"/BU\ Backup* >/dev/null 2>&1
+    touch "$mount_point/BU_Backups/$host/BU Backup had some errors: $(date '+%F')"
 
     printf "There were errors! Try running the command again to correct them.\n" >&2
     printf "If errors persist then you may have corrupt files or failing hardware.\n" >&2
-    sudo umount /media/"$user"/BU_Drive && printf "BU_Drive unmounted.\n"
+    sudo umount "$mount_point" && printf "BU_Drive unmounted.\n"
     printf "It's now safe to remove the USB drive.\n"
     printf "Backup completed in %s\n" "$(format_time $SECONDS)"
     exit 1
@@ -131,13 +125,10 @@ backup() {
 }
 
 restore() {
-
   # Runs an rsync operation to restore host's /home directory.
 
-  # Check for the host's backup directory:
-
-  if [[ ! -d /media/"$user"/BU_Drive/BU_Backups/"$host"/ ]]; then
-    printf "BU Error: Cannot find valid backup directory for %s!\n" >&2 "$host"
+  if [[ ! -d "$mount_point"/BU_Backups/"$host"/ ]]; then
+    printf "%s Cannot find valid backup directory for %s!\n" >&2 "$red_error" "$host"
     printf "- This drive may not have been used to backup this machine.\n" >&2
     printf "- BU_Backups/%s directory may have been moved or deleted.\n" >&2 "$host"
     printf "- Hostname or username may have changed since last backup.\n" >&2
@@ -145,7 +136,7 @@ restore() {
   fi
 
   printf $'\n'$"\nBU Restore Function (Version %s)\n" "$_version"
-  printf $'\n'$"\nWARNING!\n"
+  printf $'\n'$"\n\e[91mWARNING!\e[0m\n"
   printf "Any new files created in /home since last backup WILL BE DELETED!\n"
   printf "Are you sure you want to restore now? [y/N]\n"
   read -rn 1 -s choice
@@ -154,19 +145,14 @@ restore() {
     printf "Close any running applications and press any key to continue.\n"
     read -rn 1 -s
     printf $"\nRestoring /home... Please DO NOT open any applications.\n"
-    # The '--exclude 'timeshift'' & 'if-then' added by R. Romig
     if sudo rsync -aH --delete --exclude 'timeshift' --info=progress2 \
-      /media/"$user"/BU_Drive/BU_Backups/"$host"/home/ /home/; then
+      "$mount_point"/BU_Backups/"$host"/home/ /home/; then
       # Prompt user to restart machine and exit:
       # Clear any accidental input during restore:
       read -rt 1 -n 10000 discard
       box " Restoration Complete!" "-"
-      printf "Wait! Syncing drives...\n"
-      dots "."
-      sync
-      kill "$!"
-      printf "...Done."
-      sudo umount /media/"$user"/BU_Drive && printf "BU_Drive unmounted.\n"
+			sync_drives
+      sudo umount "$mount_point" && printf "BU_Drive unmounted.\n"
       printf "It's now safe to remove BU_Drive.\n"
       printf "Restart machine for all changes to take effect.\n"
       printf "Restore completed in %s\n" "$(format_time $SECONDS)"
@@ -175,28 +161,25 @@ restore() {
       # If rsync fails:
       # Clear any accidental input during restore:
       read -rt 1 -n 10000 discard
-      printf "\nBU Error: rsync exited with errors!\n" >&2
+      printf "\n%s rsync exited with errors!\n" >&2 "$red_error"
       printf "DO NOT DO ANYTHING UNTIL YOU:\n" >&2
       printf $"\n    Make sure BU_Drive USB is still plugged in.\n" >&2
       printf "    Remount BU_Drive USB by unplugging it and plugging it back in.\n" >&2
       printf $'\n'$"Wait a few seconds and try running 'bu --restore' again.\n" >&2
       printf "You may need to manually restore your data if errors persist.\n" >&2
-      sudo umount /media/"$user"/BU_Drive && printf "BU_Drive unmounted.\n"
+      sudo umount "$mount_point" && printf "BU_Drive unmounted.\n"
       printf "It's now safe to remove BU_Drive.\n"
       exit 1
     fi
   else
     printf "Restoration canceled.\n"
-    sudo umount /media/"$user"/BU_Drive && printf "BU_Drive unmounted.\n"
+    sudo umount "$mount_point" && printf "BU_Drive unmounted.\n"
     printf "It's now safe to remove BU_Drive.\n"
     exit
   fi
 }
 
 help() {
-
-# Print help information using less utility:
-
 less << EOF
 
  BU - USB Backup Tool (Version $_version) -- Help
@@ -258,26 +241,26 @@ less << EOF
 EOF
 }
 
-# Execution.
+## Execution ##
 
 # Start timer (Added by R. Romig)
 SECONDS=0
 
 # Checking for command line arguments:
-# Double brackets for conditinoal statements added by R. Romig
 if [[ "$1" == "--help" ]]; then
 	help
 	exit
 elif [[ "$1" == "--restore" ]]; then
 	drive_test
+	check_package rsync
 	restore
-elif  [[ -n "$1" ]]; then
+elif [[ -n "$1" ]]; then
   printf "%s Invalid argument.\n" >&2 "$red_error"
   printf "- Try 'bu --help' to see the available commands.\n" >&2
   exit 1
+else
+	box "BU -- USB Backup Tool (Version $_version)"
+	drive_test
+	check_package rsync
+	backup
 fi
-
-check_dependencies
-box "BU -- USB Backup Tool (Version $_version)"
-drive_test
-backup
