bu: main(): changed ' = 1' to ' -eq 1'

diff --git a/bu b/bu
--- a/bu
+++ b/bu
@@ -300,7 +300,7 @@ main() {
 		esac
 		noOpt=0
 	done
-	[[ "$noOpt" = 1 ]] && { printf "%s No argument passed.\n" "$RED_ERROR" >&2; help 1; }
+	[[ "$noOpt" -eq 1 ]] && { printf "%s No argument passed.\n" "$RED_ERROR" >&2; help 1; }
 	shift "$(( OPTIND - 1 ))"
 	case "$exit_status" in
 		0 ) printf "Backup/Restore operation successful.\n" ;;
