updated header comments, fixed _script variable assignment and declaration

diff --git a/bu b/bu
--- a/bu
+++ b/bu
@@ -1,4 +1,16 @@
 #!/usr/bin/env bash
+###############################################################################
+# Script Name  : bu
+# Description  : USB backup tool
+# Dependencies : rsync
+# Arguments    : --help, --restore
+# Author       : Copyright (C) 2023, Richard B. Romig, Created: 04 Feb 2023
+# Email        : rick.romig@gmail.com | rick.romig@mymetronet.com
+# Comments     : Based on USB Backup Tool (Version 1.1) by Joe Collins. (www.ezeelinux.com)
+# Last updated : 04 Feb 2023
+# TODO (Rick)  : 
+# License      : GNU General Public License, version 2.0
+###############################################################################
 
 # BU -- USB Backup Tool (Version 1.1) -- by Joe Collins. (www.ezeelinux.com)
 # A simple tool to create reliable backups of /etc/ and /home from multiple
@@ -6,14 +18,6 @@
 # (GNU/General Public License version 2.0)
 #
 # For Debian 9 and up, Ubuntu 16.04 and up and Linux Mint 18.x and up.
-#
-# ...And away we go!
-
-# Mondifications to the original script:
-# Added sourcing of funtionlib functions.
-# 1 Feb 2021 - Added umount command to unmount backup drive.
-# 31 Mar 2021 - Added check to see if user is in sudo group.
-# And corrected syntax errors indicated by Shellcheck utility.
 
 ## Shellcheck Directives ##  (R. Romig)
 # shellcheck source=/home/rick/bin/functionlib
@@ -25,15 +29,14 @@
 if [[ -x "$HOME/bin/functionlib" ]]; then
   source "$HOME/bin/functionlib"
 else
-  echo -e "\e[91mERROR:\e[0m functionlib not found!" >&2
+  printf "\e[91mERROR:\e[0m functionlib not found!\n" >&2
   exit 1
 fi
 
 # Declare static variables:
-
-user=$USER
-
-host=$HOSTNAME
+readonly _version="2.0"
+readonly user=$USER
+readonly host=$HOSTNAME
 
 # Check for less and rsync, install if needed:
 
@@ -49,19 +52,19 @@ drive_test() {
   # Checking for any USB drive:
 
   if [[ ! $(lsblk -S -o  TRAN | grep 'usb') = *usb* ]]; then
-    echo $'\n'$"BU Error: No USB drive connected!" >&2
-    echo "- Check to see that BU_Drive is plugged in." >&2
-    echo "- Please run 'bu --help' to learn about drive setup. :)" >&2
+    printf "\nBU Error: No USB drive connected!\n" >&2
+    printf "- Check to see that BU_Drive is plugged in.\n" >&2
+    printf "- Please run 'bu --help' to learn about drive setup.\n" >&2
     exit 1
   fi
 
   # Checking for a USB drive that is setup for BU:
 
   if [[ ! -d /media/"$user"/BU_Drive ]]; then
-    echo $'\n'$"BU Error: No USB drive with a partition labeled "BU_Drive!"" >&2
-    echo "- The drive(s) you have plugged in are not ready for use with BU." >&2
-    echo "- Don't launch BU as root or with 'sudo bu.'" >&2
-    echo "- Please run 'bu --help' to learn about drive setup. :)" >&2
+    printf "\nBU Error: No USB drive with a partition labeled "BU_Drive!"\n" >&2
+    printf "- The drive(s) you have plugged in are not ready for use with BU.\n" >&2
+    printf "- Don't launch BU as root or with 'sudo bu.'\n" >&2
+    printf "- Please run 'bu --help' to learn about drive setup.\n" >&2
     exit 1
   fi
 
@@ -80,22 +83,22 @@ backup() {
 
   # Making sure user has ownership of the BU_Drive:
 
-  echo "Changing ownership of BU_Drive to $user..."
+  printf "Changing ownership of BU_Drive to $user...\n"
   sudo chown "$user" /media/"${user}"/BU_Drive/
 
   # Creating machine specific directories:
-  echo "Checking for/creating machine specific directories..."
+  printf "Checking for/creating machine specific directories...\n"
   if mkdir -p /media/"$user"/BU_Drive/BU_Backups/"$host"; then
-    echo "...Done. BU_Drive is ready."
+    printf "...Done. BU_Drive is ready.\n"
   else
-    echo $'\n'$"BU Error: Could not create directory for $host!" >&2
-    echo "- Backup aborted. Check the status of the BU_Drive." >&2
+    printf "\nBU Error: Could not create directory for $host!\n" >&2
+    printf "- Backup aborted. Check the status of the BU_Drive.\n" >&2
     exit 1
   fi
 
   # Run rsync command:
   # The '--exclude 'timeshift''  & 'if-then' added by R. Romig
-  echo "Backing up /etc and /home to BU_Drive/BU_Backups/$host/..."
+  printf "Backing up /etc and /home to BU_Drive/BU_Backups/$host/...\n"
   if sudo rsync -aH --delete --exclude 'timeshift' --exclude '.local/share/libvirt/images' \
    --info=progress2 /etc /home /media/"$user"/BU_Drive/BU_Backups/"$host"/; then
     # Check for status of backup and exit:
@@ -109,12 +112,12 @@ backup() {
     rm -f /media/"$user"/BU_Drive/BU_Backups/"$host"/BU\ Backup* >/dev/null 2>&1
     touch "/media/$user/BU_Drive/BU_Backups/$host/BU Backup was successful: $(date)"
 
-    echo "Wait! Syncing Drives..."
+    printf "Wait! Syncing Drives...\n"
     sync
-    echo "...done"
-    sudo umount /media/"$user"/BU_Drive && echo "BU_Drive unmounted."
-    echo "It's safe to remove the USB drive now."
-    echo "Backup completed in $(format_time $SECONDS)"
+    printf "...done\n"
+    sudo umount /media/"$user"/BU_Drive && printf "BU_Drive unmounted.\n"
+    printf "It's safe to remove the USB drive now.\n"
+    printf "Backup completed in %s\n" "$(format_time $SECONDS)"
     exit
   else
     # Clear any accidental input during backup:
@@ -124,11 +127,11 @@ backup() {
     rm -f /media/"$user"/BU_Drive/BU_Backups/"$host"/BU\ Backup* >/dev/null 2>&1
     touch "/media/$user/BU_Drive/BU_Backups/$host/BU Backup had some errors: $(date)"
 
-    echo "There were errors! Try running the command again to correct them." >&2
-    echo "- If errors persist then you may have corrupt files or failing hardware." >&2
-    sudo umount /media/"$user"/BU_Drive && echo "BU_Drive unmounted."
-    echo "It's safe to remove the USB drive now."
-    echo "Backup completed in $(format_time $SECONDS)"
+    printf "There were errors! Try running the command again to correct them.\n" >&2
+    printf "- If errors persist then you may have corrupt files or failing hardware.\n" >&2
+    sudo umount /media/"$user"/BU_Drive && printf "BU_Drive unmounted.\n"
+    printf "It's safe to remove the USB drive now.\n"
+    printf "Backup completed in %s\n" "$(format_time $SECONDS)"
     exit 1
   fi
 }
@@ -140,23 +143,23 @@ restore() {
   # Check for the host's backup directory:
 
   if [[ ! -d /media/"$user"/BU_Drive/BU_Backups/"$host"/ ]]; then
-    echo "BU Error: Cannot find valid backup directory for $host!" >&2
-    echo "- This drive may not have been used to backup this machine." >&2
-    echo "- BU_Backups/$host directory may have been moved or deleted." >&2
-    echo "- Hostname or username may have changed since last backup." >&2
+    printf "BU Error: Cannot find valid backup directory for $host!\n" >&2
+    printf "- This drive may not have been used to backup this machine.\n" >&2
+    printf "- BU_Backups/$host directory may have been moved or deleted.\n" >&2
+    printf "- Hostname or username may have changed since last backup.\n" >&2
     exit 1
   fi
 
-  echo $'\n'$"BU Restore Function (Version 1.1)"
-  echo $'\n'$"WARNING!"
-  echo "Any new files created in /home since last backup WILL BE DELETED!"
-  echo "Are you sure you want to restore now? [y/N]"
+  printf $'\n'$"\nBU Restore Function (Version 1.1)\n"
+  printf $'\n'$"\nWARNING!\n"
+  printf "Any new files created in /home since last backup WILL BE DELETED!\n"
+  printf "Are you sure you want to restore now? [y/N]\n"
   read -rn 1 -s choice
   if [ "$choice" == "y" ]; then
     # Giving user a chance to close other apps and starting rsync.
-    echo "Close any running applications and press any key to continue."
+    printf "Close any running applications and press any key to continue.\n"
     read -rn 1 -s
-    echo $'\n'$"Restoring /home... Please DO NOT open any applications."
+    printf $"\nRestoring /home... Please DO NOT open any applications.\n"
     # The '--exclude 'timeshift'' & 'if-then' added by R. Romig
     if sudo rsync -aH --delete --exclude 'timeshift' --info=progress2 \
       /media/"$user"/BU_Drive/BU_Backups/"$host"/home/ /home/; then
@@ -164,32 +167,32 @@ restore() {
       # Clear any accidental input during restore:
       read -rt 1 -n 10000 discard
       box " Restoration Complete!" "-"
-      echo "Wait! Syncing drives..."
+      printf "Wait! Syncing drives...\n"
       sync
-      echo "...Done."
-      sudo umount /media/"$user"/BU_Drive && echo "BU_Drive unmounted."
-      echo "It's now safe to remove BU_Drive."
-      echo "Restart machine for all changes to take effect."
-      echo "Restore completed in $(format_time $SECONDS)"
+      printf "...Done."
+      sudo umount /media/"$user"/BU_Drive && printf "BU_Drive unmounted.\n"
+      printf "It's now safe to remove BU_Drive.\n"
+      printf "Restart machine for all changes to take effect.\n"
+      printf "Restore completed in $(format_time $SECONDS)\n"
       exit
     else
       # If rsync fails:
       # Clear any accidental input during restore:
       read -rt 1 -n 10000 discard
-      echo $'\n'$"BU Error: rsync exited with errors!" >&2
-      echo "DO NOT DO ANYTHING UNTIL YOU:" >&2
-      echo $'\n'$"    Make sure BU_Drive USB is still plugged in." >&2
-      echo "    Remount BU_Drive USB by unplugging it and plugging it back in." >&2
-      echo $'\n'$"Wait a few seconds and try running 'bu --restore' again." >&2
-      echo "You may need to manually restore your data if errors persist." >&2
-      sudo umount /media/"$user"/BU_Drive && echo "BU_Drive unmounted."
-      echo "It's now safe to remove BU_Drive."
+      printf "\nBU Error: rsync exited with errors!\n" >&2
+      printf "DO NOT DO ANYTHING UNTIL YOU:\n" >&2
+      printf $"\n    Make sure BU_Drive USB is still plugged in.\n" >&2
+      printf "    Remount BU_Drive USB by unplugging it and plugging it back in.\n" >&2
+      printf $'\n'$"Wait a few seconds and try running 'bu --restore' again.\n" >&2
+      printf "You may need to manually restore your data if errors persist.\n" >&2
+      sudo umount /media/"$user"/BU_Drive && printf "BU_Drive unmounted.\n"
+      printf "It's now safe to remove BU_Drive.\n"
       exit 1
     fi
   else
-    echo "Restoration canceled."
-    sudo umount /media/"$user"/BU_Drive && echo "BU_Drive unmounted."
-    echo "It's now safe to remove BU_Drive."
+    printf "Restoration canceled.\n"
+    sudo umount /media/"$user"/BU_Drive && printf "BU_Drive unmounted.\n"
+    printf "It's now safe to remove BU_Drive.\n"
     exit
   fi
 }
@@ -200,7 +203,7 @@ help() {
 
 less << EOF
 
- BU - USB Backup Tool (Version 1.1) -- Help
+ BU - USB Backup Tool (Version $_version) -- Help
 
  Press "q" to exit this Help page.
 
@@ -278,9 +281,6 @@ elif  [[ -n "$1" ]]; then
   exit 1
 fi
 
-# Tell 'em who we are...
-
-# echo -en "\U1F427 "
-box "BU -- USB Backup Tool (Version 1.1)"
+box "BU -- USB Backup Tool (Version $_version)"
 drive_test
 backup
diff --git a/bu-cinnkeys b/bu-cinnkeys
--- a/bu-cinnkeys
+++ b/bu-cinnkeys
@@ -4,10 +4,10 @@
 # Description  : Backup Cinnamon keybindings to a file.
 # Dependencies : none
 # Arguments    : none
-# Author       : Richard B. Romig, 12 May 2021
-# Email        : rick.romig@gmail.com
-# Comments     : Backs up keybindings to ~/.config
-#              : Tested with Cinnamon DE on Mint 19.x & 20.x, LMDE 4, Debian 10/11
+# Author       : Copyright (C) 2021, Richard B. Romig, 12 May 2021
+# Email        : rick.romig@gmail.com | rick.romig@mymetronet.com
+# Comments     : Backs up Cinnamon keybindings to ~/.config
+#              : Tested with Cinnamon DE on Mint 19.x & 20.x, LMDE 5, Debian 10/11
 # TODO (Rick)  :
 # License      : GNU General Public License, version 2
 ##########################################################################
@@ -21,15 +21,15 @@
 if [[ -x "$HOME/bin/functionlib" ]]; then
   source "$HOME/bin/functionlib"
 else
-  echo -e "\e[91mERROR:\e[0m functionlib not found!" >&2
+  printf "\e[91mERROR:\e[0m functionlib not found!\n" >&2
   exit 1
 fi
 
 ## Variables ##
 
-readonly _script=$(basename "$0")
-readonly _version="0.1.5"
-readonly _updated="16 June 2022"
+_script=$(basename "$0"); readonly _script
+readonly _version="0.1.6"
+readonly _updated="04 Feb 2023"
 readonly bu_file="keybindings-backup.dconf"
 
 ## Execution ##
diff --git a/cal-todo b/cal-todo
--- a/cal-todo
+++ b/cal-todo
@@ -21,17 +21,18 @@
 if [[ -x "$HOME/bin/functionlib" ]]; then
   source "$HOME/bin/functionlib"
 else
-  echo -e "\e[91mERROR:\e[0m functionlib not found!" >&2
+  printf "\e[91mERROR:\e[0m functionlib not found!\n" >&2
   exit 1
 fi
 
 ## Variables ##
 
-readonly _script=$(basename "$0")
-readonly _version="0.2.1"
-readonly _updated="14 Jan 2023"
+_script=$(basename "$0"); readonly _script
+readonly _version="0.2.2"
+readonly _updated="04 Feb 2023"
 readonly localdoc="$HOME/.local/share/doc"
 readonly todolist="todo.lst"
+readonly red_error="${lightred}ERROR:${normal}"
 calendar=$(mktemp -q) || die "Failed to create temporary file." 1
 
 ## Functions ##
@@ -80,7 +81,7 @@ display_cal_todo() {
 trap cleanup EXIT
 
 if [[ "$#" -eq 0 ]]; then
-	echo "${lightred}ERROR:${normal} No argument passed." >&2
+	printf "%s No argument passed.\n" >&2 "$red_error"
 	help 1
 else
 	optstr=":cdeh"
@@ -105,7 +106,7 @@ else
 				help 0
 				;;
 			? )
-				echo "${lightred}ERROR${normal} Invalid option -${OPTARG}" >&2
+				printf "%s Invalid option -%s\n" >&2 "$OPTARG" "$red_error"
 				help 2
 		esac
 	done
diff --git a/check-battery b/check-battery
--- a/check-battery
+++ b/check-battery
@@ -4,13 +4,10 @@
 # Description  : Determine the health of a laptop battery
 # Dependencies : upower
 # Arguments    : None
-# Author       : Richard B. Romig, 30 Jul 2020
-# Email        : rick.romig@gmail.com
+# Author       : Copyright (C) 2020, Richard B. Romig, 30 Jul 2020
+# Email        : rick.romig@gmail.com | rick.romig@mymetronet.com
 # Comments     : Obtains battery data from upower utility.
 #              : Inspired by a script by Elias W (eliasw4u on Ezeetalk.com)
-# 19 Sep 2021  : Added charge status of HID++ battery, if present.
-# 16 Aug 2022  : Set variable for warning/status emojis.
-# 17 Aug 2022  : Battery name obtained from battery_data file.
 # TODO (Rick)  :
 # License      : GNU General Public License, version 2.0
 ###############################################################################
@@ -24,15 +21,15 @@
 if [[ -x "$HOME/bin/functionlib" ]]; then
   source "$HOME/bin/functionlib"
 else
-  echo -e "\e[91mERROR:\e[0m functionlib not found!" >&2
+  printf "\e[91mERROR:\e[0m functionlib not found!\n" >&2
   exit 1
 fi
 
 ## Variables ##
 
-readonly _script=$(basename "$0")
-readonly _version="0.2.14"
-readonly _updated="02 Feb 2023"
+_script=$(basename "$0"); readonly _script
+readonly _version="0.2.15"
+readonly _updated="04 Feb 2023"
 
 ## Functions ##
 
@@ -136,8 +133,8 @@ clear
 if [[ $# -gt 0 ]]; then
   case "$1" in
     -h|--help ) help 0 ;;
-    --version ) version; exit ;;
-    * ) echo "${lightred}Invalid argument: $1${normal}" >&2; help 2 ;;
+    -v|--version ) version; exit ;;
+    * ) echo "${lightred}Invalid argument:${normal} $1" >&2; help 2 ;;
   esac
 fi
 
diff --git a/check-cron b/check-cron
--- a/check-cron
+++ b/check-cron
@@ -5,13 +5,10 @@
 #              : crontabs for all normal and root users.
 # Dependencies : none
 # Arguments    : None
-# Author       : Richard Romig, 6 March 2018
+# Author       : Copyright (C) 2018, Richard Romig, 6 March 2018
 # Email        : rick.romig@gmail.com
 # Comments     : Requires sudo privileges
-# 16 Jul 2021  : displays cron jobs for all normal users.
-# 09 Feb 2022  : placed tasks in modular functions.
-# 04 Oct 2022  : allowed for case where anacron job has not run yet.
-#              : allowed for case where no jobs in /etc/cron.* .
+# TODO (Rick)  :
 # License      : GNU General Public License, version 2.0
 #####################################################################
 
@@ -24,7 +21,7 @@
 if [[ -x "$HOME/bin/functionlib" ]]; then
   source "$HOME/bin/functionlib"
 else
-  pirntf "\e[91mERROR:\e[0m functionlib not found!\n" >&2
+  printf "\e[91mERROR:\e[0m functionlib not found!\n" >&2
   exit 1
 fi
 
@@ -38,17 +35,17 @@ show_anacron() {
   echo $'\n'$"${orange}Anacron Daily: ${normal}Last run on $(sudo cat "$daily" 2>/dev/null)"
   echo -n "${orange}Jobs: ${normal}"
   ls /etc/cron.daily
-  [[ "$(ls -1 /etc/cron.daily | wc -l | cut -d' ' -f1)" == 0 ]] && echo "No jobs scheduled."
+  [[ "$(find /etc/cron.daily -maxdepth 1 -type f -iname \* | wc -l)" == 0 ]] && echo "No jobs scheduled."
 
   echo $'\n'$"${orange}Anacron Weekly: ${normal}Last run on $(sudo cat "$weekly" 2>/dev/null)"
   echo -n "${orange}Jobs: ${normal}"
   ls /etc/cron.weekly
-  [[ "$(ls -1 /etc/cron.weekly | wc -l | cut -d' ' -f1)" == 0 ]] &&echo "No jobs scheduled."
+  [[ "$(find /etc/cron.weekly -maxdepth 1 -type f -iname \* | wc -l)" == 0 ]] && echo "No jobs scheduled."
 
   echo $'\n'$"${orange}Anacron Monthly: ${normal}Last run on $(sudo cat "$monthly" 2>/dev/null)"
   echo -n "${orange}Jobs: ${normal}"
   ls /etc/cron.monthly
-  [[ "$(ls -1 /etc/cron.monthly | wc -l | cut -d' ' -f1)" == 0 ]] && echo "No jobs scheduled."
+  [[ "$(find /etc/cron.monthly -maxdepth 1 -type f -iname \* | wc -l)" == 0 ]] && echo "No jobs scheduled."
 }
 
 show_user_cron() {
@@ -73,9 +70,9 @@ show_root_cron() {
 }
 
 main() {
-  readonly _script=$(basename "$0")
-  readonly _version="0.4.0"
-  readonly _updated="04 Oct 2022"
+  _script=$(basename "$0"); local _script
+  local _version="0.4.1"
+  local _updated="04 Feb 2023"
 
   clear
   echo $'\n'$"${bold}${green}Jobs for $(uname -n)"
diff --git a/corona b/corona
--- a/corona
+++ b/corona
@@ -2,10 +2,10 @@
 ###############################################################################
 # Script Name  : corona
 # Description  : Status update for Corona (COVID-19) cases (selected countries)
-# Dependencies : awk, curl, sed
+# Dependencies : curl
 # Arguments    : none
-# Author       : Richard B. Romig, 21 Mar 2020
-# Email        : rick.romig@gmail.com
+# Author       : Copyright (C) 2020, Richard B. Romig, 21 Mar 2020
+# Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
 # Comments     : Code: https://github.com/sagarkarira/coronavirus-tracker-cli
 #              : Twitter: https://twitter.com/ekrysi
 # TODO (Rick)  : Create a version for public dissemination.
@@ -21,15 +21,15 @@
 if [[ -x "$HOME/bin/functionlib" ]]; then
   source "$HOME/bin/functionlib"
 else
-  echo -e "\e[91mERROR:\e[0m functionlib not found!" >&2
+  printf "\e[91mERROR:\e[0m functionlib not found!\n" >&2
   exit 1
 fi
 
 ## Variables ##
 
-readonly _script=$(basename "$0")
-readonly _version="0.3.6"
-readonly _updated="29 Aug 2022"
+_script=$(basename "$0"); readonly _script
+7readonly _version="0.3.6"
+readonly _updated="04 Feb 2023"
 readonly url="https://corona-stats.online/?minimal=true"
 readonly today=$(date '+%d %b %Y')
 readonly now=$(date '+%R %Z')
diff --git a/dl-webpage b/dl-webpage
--- a/dl-webpage
+++ b/dl-webpage
@@ -4,8 +4,8 @@
 # Description  : Downloads a page from the web to the current directory.
 # Dependencies : wget
 # Arguments    : URL of page to be downloaded
-# Author       : Richard B. Romig, 02 Nov 2019
-# Email        : rick.romig@gmail.com
+# Author       : Copyright (C) 2019, Richard B. Romig, 02 Nov 2019
+# Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
 # Comments     :
 # TODO (Rick)  :
 # License      : GNU General Public License, version 2.0
@@ -20,15 +20,15 @@
 if [[ -x "$HOME/bin/functionlib" ]]; then
   source "$HOME/bin/functionlib"
 else
-  echo -e "\e[91mERROR:\e[0m functionlib not found!" >&2
+  printf "\e[91mERROR:\e[0m functionlib not found!\n" >&2
   exit 1
 fi
 
 ## Variables ##
 
-readonly _script=$(basename "$0")
-readonly _version="0.1.8"
-readonly _updated="04 May 2022"
+_script=$(basename "$0"); readonly _script
+readonly _version="0.1.9"
+readonly _updated="04 Feb 2023"
 
 ## Functions ##
 
