bu: disabled mount_bu(); unmount_usb_drive(): disabled rmdir; added specific error codes displayed at exit

diff --git a/bu b/bu
--- a/bu
+++ b/bu
@@ -7,12 +7,12 @@
 # Author       : Copyright (C) 2023, Richard B. Romig
 # Email        : rick.romig@gmail.com | rick.romig@mymetronet.com
 # Created      : 04 Feb 2023
-# Last updated : 16 Jul 2025
+# Last updated : 29 Jul 2025
 # Comments     : Based on BU USB Backup Tool (Version 1.1) by Joe Collins.
 # TODO (Rick)  :
 # License      : GNU General Public License, version 2.0
 # License URL  : https://github.com/RickRomig/scripts/blob/main/LICENSE
-## License URL  : https://github.com/RickRomig/scripts/blob/main/LICENSE
+# License URL  : https://github.com/RickRomig/scripts/blob/main/LICENSE
 ##########################################################################
 # This program is free software; you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
@@ -22,7 +22,7 @@
 # This program is distributed in the hope that it will be useful,
 # but WITHOUT ANY WARRANTY; without even the implied warranty of
 # MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
-## GNU General Public License for more details.
+# GNU General Public License for more details.
 ##############################################################################
 
 ## Shellcheck Directives ##
@@ -42,7 +42,7 @@ set -eu
 ## Global Variables ##
 
 readonly script="${0##*/}"
-readonly version="4.12.25197"
+readonly version="4.13.25210"
 user=$(whoami); readonly user
 readonly host="${HOSTNAME:-$(hostname)}"
 readonly mount_point="/media/$user/BU_Drive"
@@ -56,7 +56,7 @@ drive_test() {
   check_usb || die "No USB drive connected!" 1
 	bu_drive_label || die "Invalid partition label. Run 'bu -s' for drive setup information." 1
   check_uuid || die "Incorrect drive to backup $host." 1
-  mount | grep -qw BU_Drive > /dev/null 2>&1 || mount_bu
+  # mount | grep -qw BU_Drive > /dev/null 2>&1 || mount_bu
   bu_drive_fs || die "Drive must be formatted with EXT4 or XFS." 1
 	printf "Space available on BU_Drive: %s\n" "$(df -h "$mount_point" | tail -n1 | awk '{print $4}')"
 	printf "USB Backup Drive is mounted and meets all criteria.\n"
@@ -91,12 +91,12 @@ check_uuid() {
 	fi
 }
 
-mount_bu() {
-  local usbdrv
-  usbdrv="$(lsblk -fs | awk '/BU_Drive/ {print $1}')"
-  [[ -d "$mount_point" ]] || sudo mkdir -p "$mount_point"
-  sudo mount /dev/"$usbdrv" "$mount_point"
-}
+# mount_bu() {
+#   local usbdrv
+#   usbdrv="$(lsblk -fs | awk '/BU_Drive/ {print $1}')"
+#   [[ -d "$mount_point" ]] || sudo mkdir -p "$mount_point"
+#   sudo mount /dev/"$usbdrv" "$mount_point"
+# }
 
 bu_drive_fs() {
   local fs_type
@@ -121,12 +121,12 @@ sync_drives() {
 
 unmount_usb_drive() {
 	printf "Unmountng %s...\n" "$mount_point"
-	if sudo umount "$mount_point"; then
-		[[ -d "$mount_point" ]] && rmdir "$mount_point"
+	if umount "$mount_point"; then	# sudo ?
+		# [[ -d "$mount_point" ]] && rmdir "$mount_point"
 		printf "BU_Drive unmounted.\nIt is now safe to remove the USB drive.\n"
 	else
 		printf "%s %s failed to unmount.\n" "$RED_ERROR" "$mount_point"
-		exit_status=1
+		exit_status=10
 	fi
 }
 
@@ -155,7 +155,7 @@ backup() {
 		printf "%s rsync exited with errors!\n" "$RED_ERROR" >&2
 		printf "* Try reinserting the backup drive and running the command again to correct them.\n" >&2
     printf "* If errors persist then you may have corrupt files or failing hardware.\n" >&2
-		exit_status=1
+		exit_status=42
   fi
 }
 
@@ -182,7 +182,7 @@ restore() {
 				printf "* Remount BU_Drive USB by unplugging it and plugging it back in.\n" >&2
 				printf "* Wait a few seconds and try running 'bu --restore' again.\n" >&2
 				printf "* You may need to manually restore your data if errors persist.\n" >&2
-	      exit_status=1
+	      exit_status=69
 			fi
 		else
 			printf "%Restoration canceled.%s\n" "$orange" "$normal"
@@ -192,37 +192,26 @@ restore() {
     printf "* This drive may not have been used to backup this machine.\n" >&2
     printf "* BU_Backups/%s directory may have been moved or deleted.\n" "$host" >&2
     printf "* Hostname or username may have changed since last backup.\n" >&2
-    exit_status=1
+    exit_status=13
 	fi
 }
 
 help() {
 	local errcode="${1:-2}"
-	local updated="16 Jul 2025"
+	local updated="29 Jul 2025"
 	cat << _HELP_
 ${orange}$script${normal} $version, Updated: $updated
 Backup /etc/ and /home/ directories to an external USB drive.
 
-${green}Usage:${normal} $script [-bhirsN]
+${green}Usage:${normal} $script [-bhirs]
 ${orange}Available options:${normal}
   -b  Backup the host /etc and /home directories.
   -h  Show this help message and exit.
   -i  Show information about this script.
   -r  Restore the host /home directory.
   -s  Instructions for setting up the BU_Drive.
-  -N  Display GPL Terms & Conditions notice
 _HELP_
   exit "$errcode"
-}
-
-show_notice() {
-	local script_dir
-	script_dir=$(dirname "$(readlink -f "${0}")")
-	printf "%s\n" "$script"
-	printf "Backup /etc/ and /home/ directories to an external USB drive.\n"
-	printf "Copyright (C) 2023, Richard B. Romig\n"
-	printf "Email: rick.romig@gmail.com\n\n"
-	cat "$script_dir/files/gpl_notice.txt"
 }
 
 show_description() {
@@ -274,7 +263,7 @@ main() {
 	box "${script^^} -- USB Backup Tool (Version $version)"
 
 	noOpt=1
-	optstr=":bdhirsN"
+	optstr=":bdhirs"
 	while getopts "$optstr" opt; do
 		case "$opt" in
 			b )
@@ -305,10 +294,6 @@ main() {
 				drive_setup
 				mount | grep -qw BU_Drive > /dev/null 2>&1 && unmount_usb_drive
 				;;
-			N )
-				show_notice
-				exit 0
-				;;
 			? )
 				printf "%s Invalid option -%s\n" "$RED_ERROR" "$OPTARG" >&2
 				help 2
@@ -317,13 +302,16 @@ main() {
 	done
 	[[ "$noOpt" = 1 ]] && { printf "%s No argument passed.\n" "$RED_ERROR" >&2; help 1; }
 	shift "$(( OPTIND - 1 ))"
-	if [[ "$exit_status" -eq 0 ]]; then
-		over_line "Script completed in $(format_time $SECONDS)" "-"
-	else
-		printf "%sThere were errors!%s\n" "$lightred" "$normal" >&2
-		over_line "Script completed in $(format_time $SECONDS)" "-"
-		exit "$exit_status"
-	fi
+	case "$exit_status" in
+		0 ) printf "Backup/Restore operation successful.\n" ;;
+		10 ) printf "Failed to unmount BU_Drive.\n" ;;
+		13 ) printf "Unable to find backup directory for restore.\n" ;;
+		42 ) printf "Backup operation had errors.\n" ;;
+		69 ) printf "Restore operation had errors.\n" ;;
+		* ) printf "Unknown error.\n"
+	esac
+	over_line "Script completed in $(format_time $SECONDS)" "-"
+	exit "$exit_status"
 }
 
 ## Execution ##
