bu 3.10 - replaced read command prompt in restore with y_or_n function. Added copyright under title box.

diff --git a/bu b/bu
--- a/bu
+++ b/bu
@@ -7,7 +7,8 @@
 # Author       : Copyright (C) 2023, Richard B. Romig, Created: 04 Feb 2023
 # Email        : rick.romig@gmail.com | rick.romig@mymetronet.com
 # Comments     : Based on USB Backup Tool (Version 1.1) by Joe Collins. (https://www.ezeelinux.com)
-# Last updated : 01 Jul 2023
+#              : Joe's original code at: https://github.com/EzeeLinux/bu-usb_backup_tool/blob/master/bu
+# Last updated : 23 Aug 2023
 # TODO (Rick)  : 
 # License      : GNU General Public License, version 2.0
 ###############################################################################
@@ -33,7 +34,7 @@ fi
 
 ## Global Variables ##
 
-readonly _version="3.9"
+readonly _version="3.10"
 readonly user=$USER
 readonly host="${HOSTNAME:-$(hostname)}"
 readonly mount_point="/media/$user/BU_Drive"
@@ -101,6 +102,10 @@ unmount_usb_drive() {
   printf "It's now safe to remove the USB drive.\n"
 }
 
+script_et() {
+  printf "Script completed in %s\n" "$(format_time $SECONDS)"
+}
+
 backup() {
   printf "Changing ownership of BU_Drive to %s...\n" "$user"
   sudo chown "$user" "$mount_point"
@@ -110,34 +115,33 @@ backup() {
 	printf "BU_Drive is ready.\n"
 
   printf "Backing up /etc and /home to BU_Drive/BU_Backups/%s/...\n" "$host"
-  if sudo rsync -aH --delete --exclude 'timeshift' --exclude '.local/share/libvirt/images' --info=progress2 /etc /home "$mount_point"/BU_Backups/"$host"/
-  then
+  if sudo rsync -aH --delete --exclude 'timeshift' --exclude '.local/share/libvirt/images' --info=progress2 /etc /home "$mount_point"/BU_Backups/"$host"/;   then
     # Clear any accidental input during backup:
     read -rt 1 -n 10000 discard
-    box "All backed up!" "-"
+    box "Backup completed." "*"
     # Remove old and create new timestamp file:
     rm -f /"$mount_point"/BU_Backups/"$host"/BU\ Backup* >/dev/null 2>&1
     touch "$mount_point/BU_Backups/$host/BU Backup was successful: $(date '+%F')"
 		sync_drives
     unmount_usb_drive
-    printf "Backup completed in %s\n" "$(format_time $SECONDS)"
+    script_et
     exit
   else
     # Clear any accidental input during backup:
     read -rt 1 -n 10000 discard
-    # Remove old and create new timestamp file:
+    # Remove old timestamp file and create a new one:
     rm -f "$mount_point"/BU_Backups/"$host"/BU\ Backup* >/dev/null 2>&1
     touch "$mount_point/BU_Backups/$host/BU Backup had some errors: $(date '+%F')"
-    printf "There were errors! Try running the command again to correct them.\n" >&2
+    printf "There were errors! Try reinserting the backup drive and running the command again to correct them.\n" >&2
     printf "If errors persist then you may have corrupt files or failing hardware.\n" >&2
     unmount_usb_drive
-    printf "Backup completed in %s\n" "$(format_time $SECONDS)"
+    script_et
     exit 1
   fi
 }
 
 restore() {
-  # Runs an rsync operation to restore host's /home directory.
+  # Restore host's /home directory.
 
   if [[ ! -d "$mount_point"/BU_Backups/"$host"/ ]]; then
     printf "%s Cannot find valid backup directory for %s!\n" >&2 "$red_error" "$host"
@@ -148,47 +152,44 @@ restore() {
   fi
 
   printf "\nBU Restore Function\n"
-  printf "\n%sWARNING!%s\n" "$lightred" "$normal"
+  printf "\n%s\n" "$red_warning"
   printf "Any new files created in /home since last backup WILL BE DELETED!\n"
-  printf "Are you sure you want to restore now? [y/N]\n"
-  read -rn 1 -s choice
-  if [ "$choice" == "y" ]; then
-    # Giving user a chance to close other apps and starting rsync.
+  if y_or_n "Are you sure you want to restore now? [y/n]"; then
     printf "Close any running applications and press any key to continue.\n"
     read -rn 1 -s
     printf $"\nRestoring /home... Please DO NOT open any applications.\n"
     if sudo rsync -aH --delete --exclude 'timeshift' --info=progress2 "$mount_point"/BU_Backups/"$host"/home/ /home/; then
-      # Prompt user to restart machine and exit:
       # Clear any accidental input during restore:
       read -rt 1 -n 10000 discard
-      box " Restoration Complete!" "-"
+      box "Restoration Complete!" "*"
 			sync_drives
       unmount_usb_drive
       printf "Restart machine for all changes to take effect.\n"
-      printf "Restore completed in %s\n" "$(format_time $SECONDS)"
+      script_et
       exit
     else
-      # If rsync fails:
-      # Clear any accidental input during restore:
+      # If rsync fails, clear any accidental input during restore:
       read -rt 1 -n 10000 discard
       printf "\n%s rsync exited with errors!\n" >&2 "$red_error"
       printf "DO NOT DO ANYTHING UNTIL YOU:\n" >&2
-      printf $"\n    Make sure BU_Drive USB is still plugged in.\n" >&2
-      printf "    Remount BU_Drive USB by unplugging it and plugging it back in.\n" >&2
-      printf $'\n'$"Wait a few seconds and try running 'bu --restore' again.\n" >&2
+      printf "\nMake sure BU_Drive USB is still plugged in.\n" >&2
+      printf "Remount BU_Drive USB by unplugging it and plugging it back in.\n" >&2
+      printf "Wait a few seconds and try running 'bu --restore' again.\n" >&2
       printf "You may need to manually restore your data if errors persist.\n" >&2
-      unmount_usb_drive
+      mount | grep -qw BU_Drive > /dev/null 2>&1 && unmount_usb_drive
+      script_et
       exit 1
     fi
   else
     printf "Restoration canceled.\n"
     unmount_usb_drive
+    script_et
     exit
   fi
 }
 
 help() {
-less << EOF
+less << END_HELP
 
  BU - USB Backup Tool (Version $_version) -- Help
 
@@ -247,7 +248,7 @@ less << EOF
  ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
  POSSIBILITY OF SUCH DAMAGE.
 
-EOF
+END_HELP
 }
 
 ## Execution ##
@@ -255,7 +256,9 @@ EOF
 # Start timer
 SECONDS=0
 box "BU -- USB Backup Tool (Version $_version)"
-# Checking command line arguments:
+printf "Copyright \UA9 2019, Joe Collions & Copyright \UA9 2023, Rick Romig"
+
+# Check command line arguments:
 if [[ "$#" -eq 0 ]]; then
   user_in_sudo
 	drive_test
