bu 2.2 - corrected numerous syntax errors.

diff --git a/bu b/bu
--- a/bu
+++ b/bu
@@ -7,7 +7,7 @@
 # Author       : Copyright (C) 2023, Richard B. Romig, Created: 04 Feb 2023
 # Email        : rick.romig@gmail.com | rick.romig@mymetronet.com
 # Comments     : Based on USB Backup Tool (Version 1.1) by Joe Collins. (www.ezeelinux.com)
-# Last updated : 12 Mar 2023
+# Last updated : 31 Mar 2023
 # TODO (Rick)  : 
 # License      : GNU General Public License, version 2.0
 ###############################################################################
@@ -34,7 +34,7 @@ else
 fi
 
 # Declare static variables:
-readonly _version="2.1"
+readonly _version="2.2"
 readonly user=$USER
 readonly host=$HOSTNAME
 
@@ -53,8 +53,8 @@ drive_test() {
 
   if [[ ! $(lsblk -S -o  TRAN | grep 'usb') = *usb* ]]; then
     printf "\nBU Error: No USB drive connected!\n" >&2
-    printf "- Check to see that BU_Drive is plugged in.\n" >&2
-    printf "- Please run 'bu --help' to learn about drive setup.\n" >&2
+    printf " Check to see that BU_Drive is plugged in.\n" >&2
+    printf " Please run 'bu --help' to learn about drive setup.\n" >&2
     exit 1
   fi
 
@@ -62,9 +62,9 @@ drive_test() {
 
   if [[ ! -d /media/"$user"/BU_Drive ]]; then
     printf "\nBU Error: No USB drive with a partition labeled "BU_Drive!"\n" >&2
-    printf "- The drive(s) you have plugged in are not ready for use with BU.\n" >&2
-    printf "- Don't launch BU as root or with 'sudo bu.'\n" >&2
-    printf "- Please run 'bu --help' to learn about drive setup.\n" >&2
+    printf " The drive(s) you have plugged in are not ready for use with BU.\n" >&2
+    printf " Don't launch BU as root or with 'sudo bu.'\n" >&2
+    printf " Please run 'bu --help' to learn about drive setup.\n" >&2
     exit 1
   fi
 
@@ -83,7 +83,7 @@ backup() {
 
   # Making sure user has ownership of the BU_Drive:
 
-  printf "Changing ownership of BU_Drive to $user...\n"
+  printf "Changing ownership of BU_Drive to %s...\n" "$user"
   sudo chown "$user" /media/"${user}"/BU_Drive/
 
   # Creating machine specific directories:
@@ -91,14 +91,14 @@ backup() {
   if mkdir -p /media/"$user"/BU_Drive/BU_Backups/"$host"; then
     printf "...Done. BU_Drive is ready.\n"
   else
-    printf "\nBU Error: Could not create directory for $host!\n" >&2
+    printf "\nBU Error: Could not create directory for %s!\n" >&2 "$host"
     printf "- Backup aborted. Check the status of the BU_Drive.\n" >&2
     exit 1
   fi
 
   # Run rsync command:
   # The '--exclude 'timeshift''  & 'if-then' added by R. Romig
-  printf "Backing up /etc and /home to BU_Drive/BU_Backups/$host/...\n"
+  printf "Backing up /etc and /home to BU_Drive/BU_Backups/%s/...\n" "$host"
   if sudo rsync -aH --delete --exclude 'timeshift' --exclude '.local/share/libvirt/images' \
    --info=progress2 /etc /home /media/"$user"/BU_Drive/BU_Backups/"$host"/; then
     # Check for status of backup and exit:
@@ -143,9 +143,9 @@ restore() {
   # Check for the host's backup directory:
 
   if [[ ! -d /media/"$user"/BU_Drive/BU_Backups/"$host"/ ]]; then
-    printf "BU Error: Cannot find valid backup directory for $host!\n" >&2
+    printf "BU Error: Cannot find valid backup directory for %s!\n" >&2 "$host"
     printf "- This drive may not have been used to backup this machine.\n" >&2
-    printf "- BU_Backups/$host directory may have been moved or deleted.\n" >&2
+    printf "- BU_Backups/%s directory may have been moved or deleted.\n" >&2 "$host"
     printf "- Hostname or username may have changed since last backup.\n" >&2
     exit 1
   fi
@@ -173,7 +173,7 @@ restore() {
       sudo umount /media/"$user"/BU_Drive && printf "BU_Drive unmounted.\n"
       printf "It's now safe to remove BU_Drive.\n"
       printf "Restart machine for all changes to take effect.\n"
-      printf "Restore completed in $(format_time $SECONDS)\n"
+      printf "Restore completed in %s\n" "$(format_time $SECONDS)"
       exit
     else
       # If rsync fails:
