bu - changed to getopts format, streamlined backup and restore functions, added functions to show options and prepare USB drive for backup.

diff --git a/bu b/bu
--- a/bu
+++ b/bu
@@ -1,14 +1,14 @@
 #!/usr/bin/env bash
 ###############################################################################
 # Script Name  : bu
-# Description  : USB backup tool
+# Description  : Backup /etc and /home directories to an external USB drive
 # Dependencies : rsync
-# Arguments    : --help, --backup --restore (runs backup by default)
+# Arguments    : -h, -b -r (See help or show_opts functions)
 # Author       : Copyright (C) 2023, Richard B. Romig, Created: 04 Feb 2023
 # Email        : rick.romig@gmail.com | rick.romig@mymetronet.com
-# Comments     : Based on USB Backup Tool (Version 1.1) by Joe Collins. (https://www.ezeelinux.com)
+# Comments     : Based on BU USB Backup Tool (Version 1.1) by Joe Collins. (https://www.ezeelinux.com)
 #              : Joe's code at: https://github.com/EzeeLinux/bu-usb_backup_tool
-# Last updated : 03 Apr 2024
+# Last updated : 04 Apr 2024
 # TODO (Rick)  :
 # License      : GNU General Public License, version 2.0
 ###############################################################################
@@ -33,17 +33,18 @@ fi
 
 ## Global Variables ##
 
-readonly _version="3.19"
+readonly _version="4.0"
 readonly user=$USER
 readonly host="${HOSTNAME:-$(hostname)}"
 readonly mount_point="/media/$user/BU_Drive"
+exit_status=0
 
 ## Functions ##
 
 drive_test() {
 	printf "%sChecking Backup USB Drive%s\n" "$green" "$normal"
   check_usb || die "No USB drive connected!" 1
-	bu_drive_label || die "Invalid partition label. Run 'bu --help' for drive setup information." 1
+	bu_drive_label || die "Invalid partition label. Run 'bu -h' for drive setup information." 1
   check_uuid || die "Incorrect drive to backup $host." 1
   mount | grep -qw BU_Drive > /dev/null 2>&1 || mount_bu
   bu_drive_fs || die "Drive must be formatted with EXT4 or XFS." 1
@@ -101,11 +102,7 @@ sync_drives() {
 unmount_usb_drive() {
   sudo umount "$mount_point" && printf "BU_Drive unmounted.\n"
   [[ -d "$mount_point" ]] && sudo rmdir "$mount_point"
-  printf "It's now safe to remove the USB drive.\n"
-}
-
-script_time() {
-  printf "Script completed in %s\n" "$(format_time $SECONDS)"
+  printf "It is now safe to remove the USB drive.\n"
 }
 
 display_title() {
@@ -114,101 +111,86 @@ display_title() {
   printf "Copyright \UA9 2023, Rick Romig\n\n"
 }
 
-backup() {
+bu_prep() {
   printf "Changing ownership of BU_Drive to %s...\n" "$user"
-  sudo chown "$user" "$mount_point"
-
-  printf "Checking for/creating machine specific directories...\n"
-  [[ -d "$mount_point"/BU_Backups/"$host" ]] || mkdir -p "$mount_point"/BU_Backups/"$host"
+	sudo chown "$user" "$mount_point"
+	printf "Checking for/creating machine specific directories...\n"
+	[[ -d "$mount_point"/BU_Backups/"$host" ]] || mkdir -p "$mount_point"/BU_Backups/"$host"
 	printf "BU_Drive is ready.\n"
+}
 
+backup() {
+	bu_prep
   printf "%sBacking up /etc and /home to BU_Drive/BU_Backups/%s/%s\n" "$green" "$host" "$normal"
-  if sudo rsync -aH --delete --exclude 'timeshift' --exclude '.local/share/libvirt/images' --exclude 'mnt' --exclude 'lost+found' --info=progress2 /etc /home "$mount_point"/BU_Backups/"$host"/;   then
+  if sudo rsync -aH --delete --exclude 'timeshift' --exclude '.local/share/libvirt/images' --exclude 'mnt' --exclude 'lost+found' --info=progress2 /etc /home "$mount_point"/BU_Backups/"$host"/; then
     # Clear any accidental input during backup:
     read -rt 1 -n 10000 discard
     printf "%sBackup completed.%s\n" "$green" "$normal"
-    # Remove old and create new timestamp file:
     rm -f /"$mount_point"/BU_Backups/"$host"/BU\ Backup* >/dev/null 2>&1
     touch "$mount_point/BU_Backups/$host/BU Backup was successful: $(date '+%F')"
-		sync_drives
-    unmount_usb_drive
-    script_time
-    exit 0
   else
     # Clear any accidental input during backup:
     read -rt 1 -n 10000 discard
-    # Remove old timestamp file and create a new one:
     rm -f "$mount_point"/BU_Backups/"$host"/BU\ Backup* >/dev/null 2>&1
     touch "$mount_point/BU_Backups/$host/BU Backup had some errors: $(date '+%F')"
-    printf "%sThere were errors!%s Try reinserting the backup drive and running the command again to correct them.\n" >&2 "$lightred" "$normal"
+    printf "%sThere were errors!%s Try reinserting the backup drive and running the command again to correct them.\n" "$lightred" "$normal" >&2
     printf "If errors persist then you may have corrupt files or failing hardware.\n" >&2
-		sync_drives
-    unmount_usb_drive
-    script_time
-    exit 1
+		exit_status=1
   fi
 }
 
 restore() {
   # Restore host's /home directory.
+  if [[ -d "$mount_point"/BU_Backups/"$host"/ ]]; then
+	  printf "%s\n" "$red_warning"
+		printf "Any new files created in /home since last backup WILL BE DELETED!\n"
+		if y_or_n "Are you sure you want to restore now? [y/n]"; then
+			printf "Close any running applications and press any key to continue.\n"
+			anykey
+			printf "\n%sRestoring /home... Please DO NOT open any applications.$s\n" "$green" "$normal"
+			if sudo rsync -aH --delete --exclude 'timeshift' --info=progress2 "$mount_point"/BU_Backups/"$host"/home/ /home/; then
+				# Clear any accidental input during restore:
+				read -rt 1 -n 10000 discard
+				printf "%sRestoration Complete!%s\n" "$green" "$normal"
+	      printf "Restart machine for all changes to take effect.\n"
+	      sync_drives
+				else
+				# If rsync fails, clear any accidental input during restore:
+				read -rt 1 -n 10000 discard
+				printf "%s rsync exited with errors!\n" >&2 "$red_error"
+				printf "DO NOT DO ANYTHING UNTIL YOU:\n" >&2
+				printf "Make sure BU_Drive USB is still plugged in.\n" >&2
+				printf "Remount BU_Drive USB by unplugging it and plugging it back in.\n" >&2
+				printf "Wait a few seconds and try running 'bu --restore' again.\n" >&2
+				printf "You may need to manually restore your data if errors persist.\n" >&2
+	      exit_status=1
+			fi
+		else
+			printf "%Restoration canceled.%s\n" "$orange" "$normal"
+	  fi
+	else
+		printf "%s Cannot find valid backup directory for %s!\n" "$red_error" "$host" >&2
+    printf "* This drive may not have been used to backup this machine.\n" >&2
+    printf "* BU_Backups/%s directory may have been moved or deleted.\n" "$host" >&2
+    printf "* Hostname or username may have changed since last backup.\n" >&2
+    exit_status=1
+	fi
+}
 
-  if [[ ! -d "$mount_point"/BU_Backups/"$host"/ ]]; then
-    printf "%s Cannot find valid backup directory for %s!\n" >&2 "$red_error" "$host"
-    printf "- This drive may not have been used to backup this machine.\n" >&2
-    printf "- BU_Backups/%s directory may have been moved or deleted.\n" >&2 "$host"
-    printf "- Hostname or username may have changed since last backup.\n" >&2
-    exit 1
-  fi
-
-  printf "%s\n" "$red_warning"
-  printf "Any new files created in /home since last backup WILL BE DELETED!\n"
-  if y_or_n "Are you sure you want to restore now? [y/n]"; then
-    printf "Close any running applications and press any key to continue.\n"
-    anykey
-    printf "\n%sRestoring /home... Please DO NOT open any applications.$s\n" "$green" "$normal"
-    if sudo rsync -aH --delete --exclude 'timeshift' --info=progress2 "$mount_point"/BU_Backups/"$host"/home/ /home/; then
-      # Clear any accidental input during restore:
-      read -rt 1 -n 10000 discard
-      printf "%sRestoration Complete!%s\n" "$green" "$normal"
-			sync_drives
-      unmount_usb_drive
-      printf "Restart machine for all changes to take effect.\n"
-      script_time
-      exit 0
-    else
-      # If rsync fails, clear any accidental input during restore:
-      read -rt 1 -n 10000 discard
-      printf "%s rsync exited with errors!\n" >&2 "$red_error"
-      printf "DO NOT DO ANYTHING UNTIL YOU:\n" >&2
-      printf "Make sure BU_Drive USB is still plugged in.\n" >&2
-      printf "Remount BU_Drive USB by unplugging it and plugging it back in.\n" >&2
-      printf "Wait a few seconds and try running 'bu --restore' again.\n" >&2
-      printf "You may need to manually restore your data if errors persist.\n" >&2
-      mount | grep -qw BU_Drive > /dev/null 2>&1 && unmount_usb_drive
-      script_time
-      exit 1
-    fi
-  else
-    printf "%Restoration canceled.%s\n" "$orange" "$normal"
-    unmount_usb_drive
-    script_time
-    exit 0
-  fi
+show_options() {
+	printf "Valid options:\n" >&2
+	printf "\tbu --%s\n" "backup" "help" "restore" >&2
 }
 
 help() {
 less << END_HELP
-
- BU - USB Backup Tool (Version $_version) -- Help
-
  Press "q" to exit this Help page.
 
  Commands:
 
- bu = Fully backs up host's /etc and /home directories to BU_Drive.
- bu --backup = Fully backs up host's /etc and /home directories.
- bu --help = Prints this help information.
- bu --restore = Accesses BU Restore function.
+ bu -b = Fully backs up the host /etc and /home directories.
+ bu -h = Prints this help information.
+ bu -r = Accesses BU Restore function to restore host /home directory.
 
  Description:
 
@@ -226,22 +208,22 @@ less << END_HELP
  access if they only need to retrieve a few files or directories using a file
  manager.
 
- The BU Restore function is an interactive tool that let's users restore their
- /home directories to a backup up state. This function will only work when
- restoring to a machine with the exact same hostname as the one the backs were
+ The BU Restore function is an interactive tool that lets users restore their
+ /home directories to a previous state. This function will only work when
+ restoring to a machine with the exact same hostname as the one the backups were
  made from. It is intended for emergency use, as when significant number of
  directories and files are accidentally removed from /home.
 
- BU_Drive Setup
+ BU_Drive Setup:
 
  You need to prepare a BU Drive with a tool like Gparted or Disks.
  This can be any USB storage device. The dedicated USB drive MUST contain a
  partition formatted with a Linux native file system such as Ext4 or XFS. The
  partition MUST be labeled "BU_Drive" so BU can find it and use it for backups.
  The partition needs to have enough free capacity to store all data in /home on
- all of the machines you want to use the drive for. Note: You will get many
- errors if you attempt to use BU to backup to a partition that is formatted with
- non-native file systems like FAT32 or NTFS.
+ all of the machines you want to use the drive for. Note: The script will only
+ allow media formatted with Ext4 or XFS. Bon-native file systems like FAT32 or NTFS
+ will cause the script to exit with an error.
 
  Disclaimer:
 
@@ -264,38 +246,43 @@ END_HELP
 # Start timer
 SECONDS=0
 
-# Check command line arguments:
-if [[ "$#" -eq 0 ]]; then
-  sudo_login 2
-  display_title
-	drive_test
-	check_package rsync
-	backup
+noOpt=1
+optstr=":bhr"
+while getopts "$optstr" opt; do
+	case "$opt" in
+		b )
+			sudo_login 2
+			display_title
+			drive_test
+			check_package rsync
+			backup
+			sync_drives
+			unmount_usb_drive
+		;;
+		h )
+			display_title
+			help
+			mount | grep -qw BU_Drive > /dev/null 2>&1 && unmount_usb_drive
+		;;
+		r )
+			sudo_login 2
+			display_title
+			drive_test
+			check_package rsync
+			restore
+			unmount_usb_drive
+		;;
+		? )
+			printf "%s Invalid option -%s\n" "$red_error" "$OPTARG" >&2
+			show_options
+	esac
+	noOpt=0
+done
+[[ "$noOpt" = 1 ]] && { printf "%s No argument passed.\n" "$red_error" >&2; show_options; }
+shift "$(( OPTIND - 1 ))"
+printf "Script completed in %s\n" "$(format_time $SECONDS)"
+if [[ "$exit_status" -eq 0 ]]; then
+	leave ""
 else
-  case "$1" in
-    "--backup" )
-      sudo_login 2
-      display_title
-	    drive_test
-	    check_package rsync
-	    backup
-    ;;
-    "--help" )
-      help
-      exit 0
-    ;;
-    "--restore" )
-      sudo_login 2
-      display_title
-	    drive_test
-	    check_package rsync
-	    restore
-    ;;
-    * )
-      printf "%s %s is not a valid option.\n" "$red_error" "$1" >&2
-      printf "Valid options:\n" >&2
-      printf "\tbu --%s\n" "backup" "help" "restore" >&2
-      printf "\tbu without an argument performs a backup of /etc/ and /home directories.\n" >&2
-      exit 1
-  esac
+	exit "$exit_status"
 fi
