cal-todo 0.1.2 - todolist is readonly, minor syntax corrections.

diff --git a/cal-todo b/cal-todo
--- a/cal-todo
+++ b/cal-todo
@@ -1,20 +1,20 @@
 #!/usr/bin/env bash
 ###############################################################################
 # Script Name  : cal-todo
-# Description  : Example script to display command output side by side.
+# Description  : Example script to display command output and file side by side.
 # Dependencies : none
 # Arguments    : none
 # Author       : Copyright (C) 2022, Richard B. Romig, Created: 28 Dec 2022
 # Email        : rick.romig@gmail.com | rick.romig@mymetronet.com
 # Comments     : base script Copyright (C) 2022 Kris Occhipinti https://filmsbykris.com
-#              : Limit to-do list to 6 items to maintain formating.
+#              : Limit to-do list to 7 items to maintain proper formating.
 # TODO (Rick)  : 
 # License      : GNU General Public License, version 2.0
 ###############################################################################
 
 ## Shellcheck Directives ##
 # shellcheck source=/home/rick/bin/functionlib
-# shellcheck disable=SC1091,SC2034
+# shellcheck disable=SC1091
 
 ## Load function library ##
 
@@ -28,10 +28,10 @@ fi
 ## Variables ##
 
 readonly _script=$(basename "$0")
-readonly _version="0.1.1"
-readonly _updated="28 Dec 2022"
+readonly _version="0.1.2"
+readonly _updated="29 Dec 2022"
 calendar=$(mktemp -q) || die "Failed to create temporary file." 1
-todolist="$HOME/.local/share/doc/todo.lst"
+readonly todolist="$HOME/.local/share/doc/todo.lst"
 
 ## Functions ##
 
@@ -48,7 +48,7 @@ OPTIONS:
 	-d  display 3 month calendar and to-do list.
 	-e  edit to-do list.
 	-h  display help
-	NOTE: To-do list should be limited to 6 short items.
+	NOTE: To-do list should be limited to 7 short items.
 END_HELP
 	echo "$_script v$_version ($_updated)"
 	exit "$errcode"	
@@ -67,7 +67,7 @@ edit_todo() {
 trap cleanup EXIT
 
 if [[ "$#" -eq 0 ]]; then
-	echo "$lightred}ERROR:${normal} No argument passed." >&2
+	echo "${lightred}ERROR:${normal} No argument passed." >&2
 	help 1
 else
 	optstr=":cdeh"
