Updated format of getopts case statements.

diff --git a/cal-todo b/cal-todo
--- a/cal-todo
+++ b/cal-todo
@@ -29,7 +29,7 @@ fi
 ## Variables ##
 
 _script=$(basename "$0"); readonly _script
-readonly _version="0.2.6"
+readonly _version="0.2 .7"
 readonly _updated="21 Apr 2023"
 readonly localdoc="$HOME/.local/share/doc"
 readonly todolist="todo.lst"
@@ -108,5 +108,5 @@ while getopts "$optstr" opt; do
 	esac
 	noOpt=0
 done
-if [ $noOpt = 1 ];then printf "%s No argument passed.\n" "$red_error" >&2;help 1;fi
+[[ "$noOpt" = 1 ]] && { printf "%s No argument passed.\n" "$red_error" >&2; help 1; }
 leave "$_script v$_version ($_updated)"
diff --git a/cronscripts b/cronscripts
--- a/cronscripts
+++ b/cronscripts
@@ -28,8 +28,8 @@ fi
 ## Global Variables ##
 
 _script=$(basename "$0"); readonly _script
-readonly _version="0.3.3"
-readonly _updated="06 Apr 2023"
+readonly _version="0.3.4"
+readonly _updated="21 Apr 2023"
 readonly user_cron_path="$HOME/.local/bin/"
 readonly opt_cron_path="/opt/bin/"
 readonly clean_sed_path="/usr/share/misc/"
@@ -190,44 +190,43 @@ while getopts "$optstr" opt; do
 			cp_updatelogsed
       cp_zytdlupdate
 			cp_ytdluplogsed
-      ;;
+    ;;
     b )
       cp_hbarchive
-      ;;
+    ;;
     d )
       cp_zdefrag
-      ;;
+    ;;
     f )
       cp_updatelogsed
-      ;;
+    ;;
     h )
       help 0
-      ;;
+    ;;
 		l )
 			cp_zbackup
-			;;
+		;;
     p )
       cp_passwdsync
-      ;;
+    ;;
     s )
       cp_scriptarchive
-      ;;
+    ;;
     u )
       cp_zupdate
-      ;;
+    ;;
     y )
       cp_zytdlupdate
-      ;;
+    ;;
 		z )
 			cp_ytdluplogsed
-			;;
+		;;
     ? )
       printf "%s Invalid option -%s\n" "$red_error" "$OPTARG" >&2
       help 2
-      ;;
   esac
 	noOpt=0
 done
-if [ $noOpt = 1 ];then printf "%s No argument passed.\n" "$red_error" >&2;help 1;fi
+[[ "$noOpt" = 1 ]] && { printf "%s No argument passed.\n" "$red_error" >&2; help 1; }
 printf "%s v%s (%s)\n" "$_script" "$_version" "$_updated"
 exit
diff --git a/i3configs b/i3configs
--- a/i3configs
+++ b/i3configs
@@ -85,34 +85,34 @@ while getopts "$optstr" opt; do
 	case "$opt" in
 		a )
 			copy_config_file "autostart.sh"
-			;;
+		;;
 		b )
 			copy_config_file "bar.conf"
-			;;
+		;;
 		c )
 			copy_config_file "config"
-			;;
+		;;
 		h )
 			help 0
-			;;
+		;;
 		k )
 			copy_config_file "bindings.list"
-			;;
+		;;
 		l )
 			copy_config_file "logout"
-			;;
+		;;
 		s )
 			copy_config_file "sxhkd/sxhkdrc"
-			;;
+		;;
 		w )
 			copy_config_file "workspaces.conf"
-			;;
+		;;
 		? )
 			printf "%s Invalid option -%s\n" "$red_error" "$OPTARG" >&2
 			help 2
 	esac
 	noOpt=0
 done
-if [[ $noOpt == 1 ]]; then printf "%s No argument passed.\n" "$red_error" >&2; help 1; fi
+[[ "$noOpt" = 1 ]] && { printf "%s No argument passed.\n" "$red_error" >&2; help 1; }
 printf "%s v%s (%s)\n" "$_script" "$_version" "$_updated"
 exit
diff --git a/install-brave b/install-brave
--- a/install-brave
+++ b/install-brave
@@ -28,8 +28,8 @@ fi
 ## Variables ##
 
 _script=$(basename "$0"); readonly _script
-readonly _version="0.4.5"
-readonly _updated="11 Apr 2023"
+readonly _version="0.4.6"
+readonly _updated="21 Apr 2023"
 readonly brave_key="/usr/share/keyrings/brave-browser-archive-keyring.gpg"
 readonly brave_list="/etc/apt/sources.list.d/brave-browser-release.list"
 
@@ -106,26 +106,30 @@ optstr=":hipr"
 while getopts "$optstr" opt; do
   case "$opt" in
     h )
-      help 0 ;;
+      help 0
+    ;;
     i )
       exists brave-browser && leave "$(brave_ver) is already installed."
       user_in_sudo
-      install_brave ;;
+      install_brave
+    ;;
     p )
       exists brave-browser || leave "Brave browser is not installed."
       user_in_sudo
       remove_brave
-      remove_configs ;;
+      remove_configs
+    ;;
     r )
       exists brave-browser || leave "Brave browser is not installed."
       user_in_sudo
-      remove_brave ;;
+      remove_brave
+    ;;
     ? )
       printf "%s Invalid option -%s\n" "$red_error" "$OPTARG" >&2
-      help 2 ;;
+      help 2
   esac
   noOpt=0
 done
-if [ $noOpt = 1 ];then printf "%s No argument passed.\n" "$red_error" >&2;help 2;fi
+[[ "$noOpt" = 1 ]] && { printf "%s No argument passed.\n" "$red_error" >&2; help 1; }
 printf "%s v%s (%s)\n" "$_script" "$_version" "$_updated"
 exit
diff --git a/install-geany b/install-geany
--- a/install-geany
+++ b/install-geany
@@ -27,8 +27,8 @@ fi
 ## Global Variables ##
 
 _script=$(basename "$0"); readonly _script
-readonly _version="0.2.5"
-readonly _updated="29 Mar 2023"
+readonly _version="0.2.6"
+readonly _updated="21 Apr 2023"
 
 ## Functions ##
 
@@ -107,28 +107,29 @@ while getopts "$optstr" opt; do
   case "$opt" in
     h )
       printf "%s help:\n" "$_script"
-      help 0 ;;
+      help 0
+    ;;
     i )
       exists geany && leave "Geany $(geany_version) is already installed."
       user_in_sudo
       install_geany
-      ;;
+    ;;
     r )
       exists geany || leave "Geany is not installed."
       user_in_sudo
       remove_geany
-      ;;
+    ;;
     t )
       exists geany || leave "Geany is not installed."
       clone_themes
       remove_dl_dir
-      ;;
+    ;;
     ? )
       printf "%s Invalid option -%s\n" "$red_error" "$OPTARG" >&2
-      help 2 ;;
+      help 2
   esac
   noOpt=0
 done
-if [ $noOpt = 1 ];then printf "%s No argument passed.\n" "$red_error" >&2;help 1;fi
+[[ "$noOpt" = 1 ]] && { printf "%s No argument passed.\n" "$red_error" >&2; help 1; }
 printf "%s v%s (%s)\n" "$_script" "$_version" "$_updated"
 exit
diff --git a/install-glow b/install-glow
--- a/install-glow
+++ b/install-glow
@@ -27,8 +27,8 @@ fi
 ## Variables ##
 
 _script=$(basename "$0"); readonly _script
-readonly _version="0.4.9"
-readonly _updated="11 Apr 2023"
+readonly _version="0.4.10"
+readonly _updated="21 Apr 2023"
 readonly src_list="/etc/apt/sources.list.d/charm.list"
 readonly keyring_dir="/etc/apt/keyrings"
 
@@ -96,31 +96,30 @@ do
   case "$opt" in
     h )
       help 0
-      ;;
+    ;;
     i )
       exists_glow && leave "Glow $(glow_ver) is already installed."
       user_in_sudo
       echo "${lightyellow}Installing Glow markdown reader...${normal}"
       install_glow
-      ;;
+    ;;
     r )
       exists_glow || leave "Glow is not installed."
       user_in_sudo
       remove_glow
-      ;;
+    ;;
     s )
       exists_glow || leave "Glow is not installed."
       user_in_sudo
       src_gpg
       echo "charm.list created, gpg key applied."
-      ;;
+    ;;
     ? )
       echo "${lightred}ERROR:${normal} Invalid option -${OPTARG}" >&2
       help 2
-      ;;
   esac
 	noOpt=0
 done
-if [ $noOpt = 1 ];then printf "%s No argument passed.\n" "$red_error" >&2;help 1;fi
+[[ "$noOpt" = 1 ]] && { printf "%s No argument passed.\n" "$red_error" >&2; help 1; }
 printf "%s v%s (%s)\n" "$_script" "$_version" "$_updated"
 exit
diff --git a/install-handbrake b/install-handbrake
--- a/install-handbrake
+++ b/install-handbrake
@@ -31,8 +31,8 @@ fi
 ## Variables ##
 
 _script=$(basename "$0"); readonly _script
-readonly _version="0.3.6"
-readonly _updated="29 Mar 2023"
+readonly _version="0.3.7"
+readonly _updated="21 Apr 2023"
 readonly handbrake_ppa="ppa:stebbins/handbrake-releases"
 
 ## Functions ##
@@ -85,19 +85,22 @@ optstr=":hir"
 while getopts "$optstr" opt; do
   case "$opt" in
     h )
-      help 0 ;;
+      help 0
+    ;;
     i )
       exists ghb && leave "Handbrake-GTK already installed."
-      install_handbrake ;;
+      install_handbrake
+    ;;
     r )
       exists ghb || leave "Handbrake is not installed."
-      remove_handbrake ;;
+      remove_handbrake
+    ;;
     ? )
       echo "${lightred}ERROR:${normal} Invalid option -$OPTARG" >&2
-      help 2 ;;
+      help 2
   esac
 	noOpt=0
 done
-if [ $noOpt = 1 ];then printf "%s No argument passed.\n" "$red_error" >&2;help 1;fi
+[[ "$noOpt" = 1 ]] && { printf "%s No argument passed.\n" "$red_error" >&2; help 1; }
 echo "$_script v$_version ($_updated)"
 exit
diff --git a/install-homebank b/install-homebank
--- a/install-homebank
+++ b/install-homebank
@@ -29,8 +29,8 @@ fi
 ## Variables ##
 
 _script=$(basename "$0"); readonly _script
-readonly _version="0.3.5"
-readonly _updated="29 Mar 2023"
+readonly _version="0.3.6"
+readonly _updated="21 Apr 2023"
 
 ## Functions ##
 
@@ -95,22 +95,26 @@ optstr=":hipr"
 while getopts "$optstr" opt; do
   case "$opt" in
     h )
-      help 0 ;;
+      help 0
+    ;;
     i )
       exists homebank && leave "HomeBank $(homebank_ver) is already installed."
-      install_homebank ;;
+      install_homebank
+    ;;
     p )
       exists hombank || leave "HomeBank is not installed."
-      purge_homebank ;;
+      purge_homebank
+    ;;
     r )
       exists hombank || leave "HomeBank is not installed."
-      remove_homebank ;;
+      remove_homebank
+    ;;
     ? )
       echo "${lightred}ERROR:${normal} Invalid option -$OPTARG" >&2
-      help 2 ;;
+      help 2
   esac
 	noOpt=0
 done
-if [ $noOpt = 1 ];then echo "${lightred}ERROR:${normal} No argument passed." >&2;help 1;fi
+[[ "$noOpt" = 1 ]] && { printf "%s No argument passed.\n" "$red_error" >&2; help 1; }
 echo "$_script v$_version ($_updated)"
 exit
diff --git a/install-kitty b/install-kitty
--- a/install-kitty
+++ b/install-kitty
@@ -27,8 +27,8 @@ fi
 ## Variables ##
 
 _script=$(basename "$0"); readonly _script
-readonly _version="0.1.7"
-readonly _updated="06 Apr 2023"
+readonly _version="0.1.8"
+readonly _updated="21 Apr 2023"
 readonly kitty_cfg="$HOME/.config/kitty"
 
 ## Functions ##
@@ -98,28 +98,27 @@ while getopts "$optstr" opt; do
       exists kitty || leave "Kitty is not installed."
       printf "Configuring Kitty %s...\n" "$(kitty_version)"
       kitty_config
-      ;;
+    ;;
     h )
       help 0
-      ;;
+    ;;
     i )
       exists kitty && leave "Kitty terminal emulator $(kitty_version) already installed."
       user_in_sudo
       install_kitty
-      ;;
+    ;;
     r )
       exists kitty || leave "Kitty is not installed."
       user_in_sudo
       remove_kitty
-      ;;
+    ;;
     ? )
       printf "%s Invalid option -%s\n" "$red_error" "$OPTARG" >&2
       help 2
-      ;;
   esac
 	noOpt=0
 done
-if [ $noOpt = 1 ];then printf "%s No argument passed.\n" "$red_error" >&2;help 1;fi
+[[ "$noOpt" = 1 ]] && { printf "%s No argument passed.\n" "$red_error" >&2; help 1; }
 printf "%s v%s (%s)\n" "$_script" "$_version" "$_updated"
 
 exit
diff --git a/install-neofetch b/install-neofetch
--- a/install-neofetch
+++ b/install-neofetch
@@ -27,8 +27,8 @@ fi
 ## Variables ##
 
 _script=$(basename "$0"); readonly _script
-readonly _version="0.1.2"
-readonly _updated="29 Mar 2023"
+readonly _version="0.1.3"
+readonly _updated="21 Apr 2023"
 readonly cfg_dir="${HOME}/.config/neofetch"
 readonly thumbnail_dir="${HOME}/.cache/thumbnails/neofetch"
 
@@ -96,23 +96,22 @@ while getopts "$optstr" opt; do
 		c )
 			apply_config
 			exit 0
-			;;
+		;;
 		h )
 			help 0
 			;;
 		i )
 			install_neofetch
-			;;
+		;;
 		r )
 			remove_neofetch
-			;;
+		;;
 		? )
 			echo "${lightred}ERROR:${normal}Invalid option -${OPTARG}" >&2
 			help 2
-			;;
 	esac
 	noOpt=0
 done
-if [ $noOpt = 1 ];then printf "%s No argument passed.\n" "$red_error" >&2;help 1;fi
+[[ "$noOpt" = 1 ]] && { printf "%s No argument passed.\n" "$red_error" >&2; help 1; }
 printf "%s v%s (%s)\n" "$_script" "$_version" "$_updated"
 exit
diff --git a/install-terminator b/install-terminator
--- a/install-terminator
+++ b/install-terminator
@@ -27,8 +27,8 @@ fi
 ## Variables ##
 
 _script=$(basename "$0"); readonly _script
-readonly _version="0.6.2"
-readonly _updated="03 Apr 2023"
+readonly _version="0.6.3"
+readonly _updated="21 Apr 2023"
 readonly term_cfg=$HOME"/.config/terminator"
 
 ## Functions ##
@@ -141,21 +141,25 @@ while getopts "$optstr" opt; do
         teminator_config
         is_debian && sed -i '/login_shell/s/False/True/' "$term_cfg/config"
         leave "Terminator configuration file written."
-      fi ;;
+      fi
+    ;;
     h )
-      help 0 ;;
+      help 0
+    ;;
     i )
       exists terminator && leave "Terminator $(terminator_version) is already installed."
       user_in_sudo
-      install_terminator ;;
+      install_terminator
+    ;;
     r )
       exists terminator || leave "Terminator is not installed."
       user_in_sudo
-      remove_terminator ;;
+      remove_terminator
+    ;;
     ? )
       echo "${lightred}ERROR:${normal} Invalid option -${OPTARG}" >&2
-      help 2 ;;
+      help 2
     esac
   	noOpt=0
 done
-if [ $noOpt = 1 ];then echo "${lightred}ERROR:${normal} No argument passed." >&2;help 1;fi
+[[ "$noOpt" = 1 ]] && { printf "%s No argument passed.\n" "$red_error" >&2; help 1; }
diff --git a/install-ufw b/install-ufw
--- a/install-ufw
+++ b/install-ufw
@@ -27,8 +27,8 @@ fi
 ## Global Variables ##
 
 _script=$(basename "$0"); readonly _script
-readonly _version="0.1.4"
-readonly _updated="01 Apr 2023"
+readonly _version="0.1.5"
+readonly _updated="21 Apr 2023"
 
 ## Functions ##
 
@@ -115,15 +115,16 @@ while getopts "$optstr" opt; do
       user_in_sudo
       ufw_status || leave "UFW $(ufw_version) is already disabled."
       disable_ufw
-      ;;
+    ;;
     e )
       dpkg -l | grep -qw ufw || leave "UFW is not installed."
       user_in_sudo
       ufw_status && leave "UFW $(ufw_version) is already enabled."
       enable_ufw
-      ;;
+    ;;
     h )
-      help 0 ;;
+      help 0
+    ;;
     i )
       debian_system || die "Not a Debian-based system."
       dpkg -l | grep -qw ufw && leave "UFW $(ufw_version) is already installed."
@@ -132,22 +133,24 @@ while getopts "$optstr" opt; do
       add_rules
       enable_ufw
       printf "UFW %s installed and configured.\n" "$(ufw_version)"
-      ;;
+    ;;
     r )
       debian_system || die "Not a Debian-based system."
       dpkg -l | grep -qw ufw || leave "UFW is not installed."
       user_in_sudo
       remove_ufw
-      ;;
+    ;;
     s )
       dpkg -l | grep -qw ufw || leave "UFW is not installed."
       user_in_sudo
       printf "UFW %s\n" "$(ufw_version)"
       sudo ufw status numbered
+    ? )
       printf "%s Invalid option -%s\n" "$red_error" "$OPTARG" >&2
+      help 2
   esac
   noOpt=0
 done
-if [ $noOpt = 1 ];then printf "%s No argument passed.\n" "$red_error" >&2;help 1;fi
+[[ "$noOpt" = 1 ]] && { printf "%s No argument passed.\n" "$red_error" >&2; help 1; }
 printf "%s v%s (%s)\n" "$_script" "$_version" "$_updated"
 exit
diff --git a/install-zoom b/install-zoom
--- a/install-zoom
+++ b/install-zoom
@@ -27,8 +27,8 @@ fi
 ## Global Variables ##
 
 _script=$(basename "$0"); readonly _script
-readonly _version="0.1.5"
-readonly _updated="29 Mar 2023"
+readonly _version="0.1.6"
+readonly _updated="21 Apr 2023"
 
 ## Functions ##
 
@@ -86,26 +86,25 @@ while getopts "$optstr" opt; do
 	case "$opt" in
 		h )
 			help 0
-			;;
+		;;
 		i )
 			exists zoom && printf "Zoom %s is installed.\n" "$(zoom_version)"
 			tmp_dir=$(mktemp -d) || die "Failed to create temporary directory." 1
 			trap cleanup EXIT
 			user_in_sudo
 			install_zoom
-			;;
+		;;
 		r )
 			exists zoom || leave "Zoom is not installed."
 			user_in_sudo
 			remove_zoom
-			;;
+		;;
 		? )
 			printf "%s Invalid option -%s\n" "$red_error" "$OPTARG" >&2
 			help 2
-			;;
 	esac
 	noOpt=0
 done
-if [ $noOpt = 1 ];then printf "%s No argument passed.\n" "$red_error" >&2;help 1;fi
+[[ "$noOpt" = 1 ]] && { printf "%s No argument passed.\n" "$red_error" >&2; help 1; }
 printf "%s v%s (%s)\n" "$_script" "$_version" "$_updated"
 exit
diff --git a/iru-bat b/iru-bat
--- a/iru-bat
+++ b/iru-bat
@@ -27,8 +27,8 @@ fi
 ## Variables ##
 
 _script=$(basename "$0"); readonly _script
-readonly _version="0.4.8"
-readonly _updated="29 Mar 2023"
+readonly _version="0.4.9"
+readonly _updated="21 Apr 2023"
 readonly url="https://github.com/sharkdp/bat/releases"
 readonly bat_cfg=$HOME"/.config/bat"
 
@@ -156,10 +156,10 @@ while getopts "$optstr" opt; do
     c )
       exists bat || leave "Bat is not installed. Run '$_script -i' to install."
       apply_config
-      ;;
+    ;;
     h )
       help 0
-      ;;
+    ;;
     i )
       exists bat && leave "Bat $(bat_ver) is already installed."
       tmp_file=$(mktemp) || die "Failed to create temporary file." 1
@@ -171,11 +171,11 @@ while getopts "$optstr" opt; do
       check_distro || echo "Bat $new_ver is the latest version compatible with $(get_distribution)."
       install_bat
       apply_config
-      ;;
+    ;;
     r )
       exists bat || leave "Bat is not installed. Run '$_script -i' to install."
       remove_bat
-      ;;
+    ;;
     u )
       exists bat || leave "Bat is not installed. Run '$_script -i' to install."
       tmp_file=$(mktemp) || die "Failed to create temporary file." 1
@@ -184,13 +184,12 @@ while getopts "$optstr" opt; do
       check_dependencies
       new_ver="$(newest_version)"
       compare_versions
-      ;;
+    ;;
     ? )
       echo "${lightred}ERROR:${normal}Invalid option -${OPTARG}" >&2
       help 2
-      ;;
   esac
 	noOpt=0
 done
-if [ $noOpt = 1 ];then printf "%s No argument passed.\n" "$red_error" >&2;help 1;fi
+[[ "$noOpt" = 1 ]] && { printf "%s No argument passed.\n" "$red_error" >&2; help 1; }
 
diff --git a/iru-chrome b/iru-chrome
--- a/iru-chrome
+++ b/iru-chrome
@@ -27,8 +27,8 @@ fi
 ## Variables ##
 
 _script=$(basename "$0"); readonly _script
-readonly _version="0.3.10"
-readonly _updated="29 Mar 2023"
+readonly _version="0.3.11"
+readonly _updated="21 Apr 2023"
 readonly chrome_list="/etc/apt/sources.list.d/google-chrome.list"
 readonly keyring_dir="/usr/share/keyrings"
 readonly trusted_key="google-chrome.gpg"
@@ -95,21 +95,25 @@ optstr=":hiru"
 while getopts "$optstr" opt; do
   case "$opt" in
     h )
-      help 0 ;;
+      help 0
+    ;;
     i )
       exists google-chrome-stable && leave "Google Chrome $(chrome_ver) already installed."
       check_dependencies
-      install_chrome ;;
+      install_chrome
+    ;;
     r )
       exists google-chrome-stable || leave "Google Chrome is not installed."
-      purge_chrome ;;
+      purge_chrome
+    ;;
     u )
       exists google-chrome-stable || leave "Google Chrome is not installed."
-      update_chrome ;;
+      update_chrome
+    ;;
     ? )
       echo "${lightred}ERROR:${normal} Invalid option -${OPTARG}." >&2
-    help 2 ;;
+    help 2
   esac
 	noOpt=0
 done
-if [ $noOpt = 1 ];then printf "%s No argument passed.\n" "$red_error" >&2;help 1;fi
+[[ "$noOpt" = 1 ]] && { printf "%s No argument passed.\n" "$red_error" >&2; help 1; }
diff --git a/iru-marktext b/iru-marktext
--- a/iru-marktext
+++ b/iru-marktext
@@ -27,8 +27,8 @@ fi
 ## Variables ##
 
 _script=$(basename "$0"); readonly _script
-readonly _version="0.3.7"
-readonly _updated="29 Mar 2023"
+readonly _version="0.3.8"
+readonly _updated="21 Apr 2023"
 readonly url="https://github.com/marktext/marktext/releases"
 
 ## Functions ##
@@ -108,7 +108,8 @@ optstr=":hiru"
 while getopts "$optstr" opt; do
   case "$opt" in
     h )
-      help 0 ;;
+      help 0
+    ;;
     i )
       exists marktext && leave "Marktext $(marktext_version) is already installed."
       tmp_file=$(mktemp) || die "Failed to create temporary file." 1
@@ -118,11 +119,11 @@ while getopts "$optstr" opt; do
       new_ver="$(newest_version)"
       echo "${lightyellow}Installing MarkText version $new_ver...${normal}"  
       install_marktext
-      ;;
+    ;;
     r )
       exists marktext || leave "Marktext is not installed. Run '$_script -i' to install."
       remove_marktext
-      ;;
+    ;;
     u )
       exists marktext || leave "Marktext is not installed. Run '$_script -i' to install."
       tmp_file=$(mktemp) || die "Failed to create temporary file." 1
@@ -131,13 +132,12 @@ while getopts "$optstr" opt; do
       check_dependencies
       new_ver="$(newest_version)"
       compare_versions
-      ;;
+    ;;
     ? )
       echo "${lightred}ERROR:${normal} Invalid option -${OPTARG}" >&2
       help 2
-      ;;
   esac
 	noOpt=0
 done
-if [ $noOpt = 1 ];then printf "%s No argument passed.\n" "$red_error" >&2;help 1;fi
+[[ "$noOpt" = 1 ]] && { printf "%s No argument passed.\n" "$red_error" >&2; help 1; }
 exit
diff --git a/iru-micro b/iru-micro
--- a/iru-micro
+++ b/iru-micro
@@ -27,8 +27,8 @@ fi
 ## Variables ##
 
 _script=$(basename "$0"); readonly _script
-readonly _version="0.4.8"
-readonly _updated="29 Mar 2023"
+readonly _version="0.4.9"
+readonly _updated="21 Apr 2023"
 readonly url="https://github.com/zyedidia/micro/releases"
 readonly micro_cfg=$HOME"/.config/micro"
 
@@ -149,10 +149,10 @@ while getopts "$optstr" opt; do
     b )
       exists micro || leave "Micro is not installed. Run '$_script -i' to install."
       apply_bindings
-      ;;
+    ;;
     h )
       help 0
-      ;;
+    ;;
     i )
       exists micro && leave "Micro $(micro_ver) is already installed."
       tmp_file=$(mktemp) || die "Failed to create temporary file." 1
@@ -164,15 +164,15 @@ while getopts "$optstr" opt; do
       install_micro
       apply_settings
       apply_bindings
-      ;;
+    ;;
     r )
       exists micro || leave "Micro is not installed. Run '$_script -i' to install."
       remove_micro
-      ;;
+    ;;
     s )
       exists micro || leave "Micro is not installed. Run '$_script -i' to install."
       apply_settings
-      ;;
+    ;;
     u )
       exists micro || leave "Micro is not installed. Run '$_script -i' to install."
       tmp_file=$(mktemp) || die "Failed to create temporary file." 1
@@ -181,13 +181,12 @@ while getopts "$optstr" opt; do
       check_dependencies
       new_ver="$(newest_version)"
       compare_versions
-      ;;
+    ;;
     ? )
       echo "${lightred}ERROR:${normal} Invalid option -${OPTARG}" >&2
       help 2
-      ;;
   esac
   noOpt=0
 done
-if [ $noOpt = 1 ];then printf "%s No argument passed.\n" "$red_error" >&2;help 1;fi
+[[ "$noOpt" = 1 ]] && { printf "%s No argument passed.\n" "$red_error" >&2; help 1; }
 exit
diff --git a/iru-vscodium b/iru-vscodium
--- a/iru-vscodium
+++ b/iru-vscodium
@@ -27,8 +27,8 @@ fi
 ## Variables ##
 
 _script=$(basename "$0"); readonly _script
-readonly _version="0.2.6"
-readonly _updated="16 Apr 2023"
+readonly _version="0.2.7"
+readonly _updated="21 Apr 2023"
 readonly url="https://github.com/VSCodium/vscodium/releases"
 
 ## Functions ##
@@ -145,7 +145,8 @@ optstr=":hirsu"
 while getopts "$optstr" opt; do
 	case "$opt" in
 		h )
-			help 0 ;;
+			help 0
+    ;;
 		i )
 			exists codium && leave "VSCodium $(codium_ver) is already installed."
       check_dependencies
@@ -156,15 +157,15 @@ while getopts "$optstr" opt; do
       echo "${lightyellow}Installing VSCodium $new_ver...${normal}"
 			install_vscodium
       apply_settings
-      ;;
+    ;;
 		r )
       exists codium || leave "VSCodium is not installed."
       remove_vscodium
-      ;;
+    ;;
 		s )
       exists codium || leave "VSCodium is not installed."
       apply_settings
-      ;;
+    ;;
 		u )
       exists codium || leave "VSCodium is not installed."
       check_dependencies
@@ -173,13 +174,12 @@ while getopts "$optstr" opt; do
 			trap cleanup EXIT
 			new_ver="$(newest_version)"
 			compare_versions
-      ;;
+    ;;
 		? )
       printf "%s Invalid option -%s\n" "$red_error" "$OPTARG" >&2
 			help 2
-      ;;
 	esac
 	noOpt=0
 done
-if [ $noOpt = 1 ];then printf "%s No argument passed.\n" "$red_error" >&2;help 1;fi
+[[ "$noOpt" = 1 ]] && { printf "%s No argument passed.\n" "$red_error" >&2; help 1; }
 exit
diff --git a/iru-youtube-dl b/iru-youtube-dl
--- a/iru-youtube-dl
+++ b/iru-youtube-dl
@@ -28,8 +28,8 @@ fi
 ## Global Variables ##
 
 _script=$(basename "$0"); readonly _script
-readonly _version="0.2.0"
-readonly _updated="04 Apr 2023"
+readonly _version="0.2.1"
+readonly _updated="21 Apr 2023"
 readonly ytdl_prg="youtube-dl"
 readonly update_script="z-ytdlupdate"
 readonly sed_file="ytdluplog.sed"
@@ -166,7 +166,7 @@ while getopts "$optstr" opt; do
 	case "$opt" in
 		h )
 			help 0
-			;;
+		;;
 		i )
 			[[ -f "$ytdl_location/$ytdl_prg" ]] && leave "$ytdl_prg $(ytdl_version) already installed."
 			user_in_sudo
@@ -174,32 +174,31 @@ while getopts "$optstr" opt; do
 			install_intro
 			dpkg -l | grep -qw youtube-dl && remove_repo_ver
 			install_youtubedl
-			;;
+		;;
 		r )
 			remove_intro
 			dpkg -l | grep -qw youtube-dl && remove_repo_ver
 			[[ -f "$ytdl_location/$ytdl_prg" ]] || leave "$ytdl_prg $(ytdl_version) is not installed."
 			user_in_sudo
 			remove_youtubedl
-			;;
+		;;
 		u )
 			[[ -f "$ytdl_location/$ytdl_prg" ]] || leave "$ytdl_prg $(ytdl_version) is not installed."
 			user_in_sudo
 			update_youtubedl
-			;;
+		;;
 		x )
 			dpkg -l | grep -qw youtube-dl || leave "The repo version of $ytdl_prg is not installed."
 			printf "Removing %s installed from the distribution repository.\n" "$ytdl_prg"
 			user_in_sudo
 			remove_repo_ver
-			;;
+		;;
 		? )
 			printf "%s Invalid option -%s\n" "$red_error" "$OPTARG" >&2
 			help 2
-			;;
 	esac
 	noOpt=0
 done
-if [ $noOpt = 1 ];then printf "%s No argument passed.\n" "$red_error" >&2;help 1;fi
+[[ "$noOpt" = 1 ]] && { printf "%s No argument passed.\n" "$red_error" >&2; help 1; }
 printf "%s v%s (%s)\n" "$_script" "$_version" "$_updated"
 exit
diff --git a/laptop-utils b/laptop-utils
--- a/laptop-utils
+++ b/laptop-utils
@@ -26,9 +26,8 @@ fi
 ## Global Variables ##
 
 _script=$(basename "$0"); readonly _script
-readonly _version="1.5.2"
-readonly _updated="29 Mar 2023"
-
+readonly _version="1.5.3"
+readonly _updated="21 Apr 2023"
 
 ## Funtions ##
 
@@ -153,19 +152,22 @@ optstr=":his"
 while getopts "$optstr" opt; do
   case "$opt" in
     h )
-      help 0 ;;
+      help 0
+    ;;
     i )
       intro
-      main ;;
+      main
+    ;;
     s )
       intro
-      util_status ;;
+      util_status
+    ;;
     ? )
       printf "%s Invalid option -%s\n" "$red_error" "$OPTARG" >&2
       help 2
   esac
 	noOpt=0
 done
-if [ $noOpt = 1 ];then printf "%s No argument passed.\n" "$red_error" >&2;help 1;fi
+[[ "$noOpt" = 1 ]] && { printf "%s No argument passed.\n" "$red_error" >&2; help 1; }
 printf "%s v%s (%s)\n" "$_script" "$_version" "$_updated"
 exit
diff --git a/lm20-snaps b/lm20-snaps
--- a/lm20-snaps
+++ b/lm20-snaps
@@ -28,8 +28,8 @@ fi
 ## Variables ##
 
 _script=$(basename "$0"); readonly _script
-readonly _version="0.2.5"
-readonly _updated="11 Apr 2023"
+readonly _version="0.2.6"
+readonly _updated="21 Apr 2023"
 readonly pref_file="/etc/apt/preferences.d/nosnap.pref"
 
 ## Functions ##
@@ -116,25 +116,25 @@ if lm20_plus; then
       d )
         user_in_sudo
         disable_snaps
-        break ;;
+      ;;
       e )
         user_in_sudo
         enable_snaps
-        break ;;
+      ;;
       h )
         help 0
-        break ;;
+      ;;
       s )
         printf "\nStatus of snapd and snap packages: "
         snap_status && printf "Snaps are enabled.\n" || printf "Snaps are disabled.\n"
-        break ;;
+      ;;
       ? )
         printf "\n%s Invalid option -%s\n" "$red_error" "$OPTARG" >&2
-        help 2 ;;
+        help 2
     esac
 	  noOpt=0
   done
-  if [ $noOpt = 1 ];then printf "%s No argument passed.\n" "$red_error" >&2;help 1;fi
+  [[ "$noOpt" = 1 ]] && { printf "%s No argument passed.\n" "$red_error" >&2; help 1; }
   exit
 else
   die "This script is only for use with Linux Mint 20 or later." 1
diff --git a/local-ip-up b/local-ip-up
--- a/local-ip-up
+++ b/local-ip-up
@@ -30,8 +30,8 @@ fi
 ## Variables ##
 
 _script=$(basename "$0"); readonly _script
-readonly _version="0.4.4"
-readonly _updated="29 Mar 2023"
+readonly _version="0.4..5"
+readonly _updated="21 Apr 2023"
 
 ## Functions ##
 
@@ -133,7 +133,7 @@ while getopts "$optstr" opt; do
       scan_static_addresses
       scan_dhcp_addresses
       tput cnorm
-      ;;
+      ;
     d )
       check_dependencies
       tput civis
@@ -141,10 +141,10 @@ while getopts "$optstr" opt; do
       echo -e "${underline}${green}IP Address\tHostname${normal}"
       scan_dhcp_addresses
       tput cnorm
-      ;;
+    ;;
     h )
       help 0
-      ;;
+    ;;
     s )
       check_dependencies
       tput civis
@@ -152,15 +152,13 @@ while getopts "$optstr" opt; do
       echo -e "${underline}${green}IP Address\tHostname${normal}"
       scan_static_addresses
       tput cnorm
-      ;;
+    ;;
     ? )
       echo "${lightred}ERROR:${normal} Invalid option -${OPTARG}" >&2
       help 2
-      ;;
   esac
 	noOpt=0
 done
-if [ $noOpt = 1 ];then printf "%s No argument passed.\n" "$red_error" >&2;help 1;fi
-
+[[ "$noOpt" = 1 ]] && { printf "%s No argument passed.\n" "$red_error" >&2; help 1; }
 printf "\n%s active addresses discovered in %s.\n\n" "$count" "$(format_time SECONDS)"
 leave "$_script v$_version ($_updated)"
diff --git a/mount-bu b/mount-bu
--- a/mount-bu
+++ b/mount-bu
@@ -27,8 +27,8 @@ fi
 ## Variables ##
 
 _script=$(basename "$0"); readonly _script
-readonly _version="0.2.4"
-readonly _updated="31 Mar 2023"
+readonly _version="0.2.5"
+readonly _updated="21 Apr 2023"
 readonly mount_location="/media/rick/BU_Drive"
 
 ## Functions ##
@@ -89,29 +89,29 @@ while getopts "$optstr" opt; do
   case "$opt" in
     h )
       help 0
-      ;;
+    ;;
     m )
       if bu_status; then
         printf "No further action necessary.\n"
       else
         mount_bu
       fi
-      ;;
+    ;;
     s )
       bu_status
-      ;;
+    ;;
     u )
       if bu_status; then
         umount_bu
       else
         printf "No further action necessary.\n"
       fi
-      ;;
+    ;;
     ? )
       printf "\e[91mERROR:\e[0m Invalid option -%s\n" "$OPTARG" >&2
-      help 2 ;;
+      help 2
   esac
 	noOpt=0
 done
-if [ $noOpt = 1 ];then printf "%s No argument passed.\n" "$red_error" >&2;help 1;fi
+[[ "$noOpt" = 1 ]] && { printf "%s No argument passed.\n" "$red_error" >&2; help 1; }
 exit
diff --git a/pwfeedback b/pwfeedback
--- a/pwfeedback
+++ b/pwfeedback
@@ -28,8 +28,8 @@ fi
 ## Variables ##
 
 _script=$(basename "$0"); readonly _script
-readonly _version="0.4.1"
-readonly _updated="29 Mar 2023"
+readonly _version="0.4.2"
+readonly _updated="21 Apr 2023"
 readonly pwfb_dir="/etc/sudoers.d"
 readonly pwfb_file="0pwfeedback"
 
@@ -99,24 +99,24 @@ while getopts "$optstr" opt; do
     e )
       user_in_sudo
       enable_pwfeedback
-      ;;
+    ;;
     d )
       user_in_sudo
       disable_pwfeedback
-      ;;
+    ;;
     h )
       help 0
-      ;;
+    ;;
     s )
       user_in_sudo
       pwfeedback_status
-      ;;
+    ;;
     ? )
       printf "%s Invalid option -%s\n" "$red_error" "$OPTARG" >&2
       help 2
   esac
 	noOpt=0
 done
-if [ $noOpt = 1 ];then printf "%s No argument passed.\n" "$red_error" >&2;help 1;fi
+[[ "$noOpt" = 1 ]] && { printf "%s No argument passed.\n" "$red_error" >&2; help 1; }
 printf "%s v%s (%s)\n" "$_script" "$_version" "$_updated"
 exit
