cal-todo: help() updated indentation of heredoc; main() noOpt check changed to if statement

diff --git a/cal-todo b/cal-todo
--- a/cal-todo
+++ b/cal-todo
@@ -7,8 +7,8 @@
 # Author       : Copyright (C) 2022, Richard B. Romig, Mosfanet
 # Email        : rick.romig@gmail.com | rick.romig@mymetronet.com
 # Created      : 28 Dec 2022
-# Updated      : 09 Jul 2026
-# Version      : 3.9.26218
+# Updated      : 09 Sep 2026
+# Version      : 3.10.26252
 # Comments     : base script Copyright (C) 2022 Kris Occhipinti https://filmsbykris.com
 #              : Uses default editor ($EDITOR) to edit to-do list.
 #              : Limit to-do list to 7 items to maintain proper formating.
@@ -40,18 +40,18 @@ cleanup() {
 help() {
 	local -r script="$1"
 	local -r version="$2"
-	local -r errcode="${3:-1}"
-	local -r updated="09 Jul 2026"
+	local -ri errcode="${3:-1}"
+	local -r updated="09 Sep 2026"
 	cat <<- _HELP_
-${orange}$script${normal} $version, Updated: $updated
-Creates/displays/edits a simple to-do list with a calendar.
+	${orange}$script${normal} $version, Updated: $updated
+	Creates/displays/edits a simple to-do list with a calendar.
 
-${green}Usage:${normal} $script [-e13h]
-${orange}Available options:${normal}
-	-1  Display current month calendar and to-do list.
-	-3  Display 3-month calendar and to-do list.
-	-e  Edit/create to-do list.
-	-h  Show this help message and exit.
+	${green}Usage:${normal} $script [-e13h]
+	${orange}Available options:${normal}
+	-1	Display current month calendar and to-do list.
+	-3	Display 3-month calendar and to-do list.
+	-e	Edit/create to-do list.
+	-h	Show this help message and exit.
 	NOTE: To-do list should be limited to 7 short items to maintain format.
 _HELP_
 	exit "$errcode"
@@ -100,25 +100,23 @@ show_three_months() {
 
 main() {
 	local -r script="${0##*/}"
-	local -r version="3.9.26218"
+	local -r version="3.10.26252"
 	local -i exit_code=0
-	local opt OPTARG OPTIND
 	local -r doc_dir=~/.local/share/doc
 	local -r todolist="todo.lst"
 	local -i noOpt=1
 	local -r optstr=":13eh"
+	local opt OPTARG OPTIND
 	trap cleanup EXIT
 	check_package ncal
 	while getopts "$optstr" opt; do
 		case "$opt" in
 			1 )
 				[[ -f "$doc_dir/$todolist" ]] || create_todo "$doc_dir" "$todolist"
-				show_one_month "$doc_dir" "$todolist"
-				;;
+				show_one_month "$doc_dir" "$todolist"  ;;
 			3 )
 				[[ -f "$doc_dir/$todolist" ]] || create_todo "$doc_dir" "$todolist"
-				show_three_months "$doc_dir" "$todolist"
-				;;
+				show_three_months "$doc_dir" "$todolist" ;;
 			e )
 				if [[ -f "$doc_dir/$todolist" ]]; then
 					$EDITOR "$doc_dir/$todolist"
@@ -126,11 +124,9 @@ main() {
 				else
 					create_todo "$doc_dir" "$todolist"
 					printf "To-Do list created.\n"
-				fi
-				;;
+				fi ;;
 			h )
-				help "$script" "$version" 0
-				;;
+				help "$script" "$version" 0 ;;
 			? )
 				printf "%s Invalid option: -%s\n" >&2 "$RED_ERROR" "$OPTARG"
 				help "$script" "$version" "$E_INVALID_ARG"
@@ -138,7 +134,10 @@ main() {
 		exit_code="$?"
 		noOpt=0
 	done
-	[[ "$noOpt" = 1 ]] && { printf "%s No argument passed.\n" "$RED_ERROR" >&2; help "$script" "$version" "$E_MISSING_ARG"; }
+	if (( noOpt == 1 )); then
+		printf "%s No argument passed.\n" "$RED_ERROR" >&2
+		help "$script" "$version" "$E_MISSING_ARG"
+	fi
 	shift "$(( OPTIND - 1 ))"
 	over_line "$script $version"
 	exit "$exit_code"
