cal-todo: show_three_months() process subsittion to sed before redirecting to temp file

diff --git a/cal-todo b/cal-todo
--- a/cal-todo
+++ b/cal-todo
@@ -7,7 +7,7 @@
 # Author       : Copyright (C) 2022, Richard B. Romig, Mosfanet
 # Email        : rick.romig@gmail.com | rick.romig@mymetronet.com
 # Created      : 28 Dec 2022
-# Updated      : 25 Feb 2026
+# Updated      : 16 May 2026
 # Comments     : base script Copyright (C) 2022 Kris Occhipinti https://filmsbykris.com
 #              : Uses default editor ($EDITOR) to edit to-do list.
 #              : Limit to-do list to 7 items to maintain proper formating.
@@ -26,22 +26,14 @@
 # GNU General Public License for more details.
 ##########################################################################
 
-## Shellcheck Directives ##
-# shellcheck source=/home/rick/bin/functionlib
-
 ## Load function library ##
-
-if [[ -x "$HOME/bin/functionlib" ]]; then
-  source "$HOME/bin/functionlib"
-else
-  printf "\e[91mERROR:\e[0m functionlib not found!\n" >&2
-  exit 81
-fi
+# shellcheck source=/home/rick/bin/functionlib
+source ~/bin/functionlib || { printf "\e[91mERROR:\e[0m Unable to source functionlib\n"; exit 1; }
 
 ## Global Variables ##
 
 readonly script="${0##*/}"
-readonly version="3.6.26056"
+readonly version="3.7.26136"
 script_dir=$(dirname "$(readlink -f "${0}")"); readonly script_dir
 calendar=$(mktemp -q) || die "Failed to create temporary file." "$E_TEMP_FILE"
 
@@ -55,7 +47,7 @@ cleanup() {
 
 help() {
 	local errcode="${1:-1}"
-	local updated="26 Jan 2026"
+	local updated="16 May 2026"
 	cat <<- _HELP_
 ${orange}$script${normal} $version, Updated: $updated
 Creates/displays/edits a simple to-do list with a calendar.
@@ -92,7 +84,7 @@ show_three_months() {
 	local doc_dir="$1"
 	local todolist="$2"
 	clear
-	sed '1d' <(cal -3) > "$calendar"	# strips off the year (1st line) to line up todo list with the month.
+	sed '1d' < <(cal -3) > "$calendar"	# strips off the year (1st line) to line up todo list with the month.
 	paste "$calendar" "$doc_dir/$todolist"
 }
 
