catless: removed EC variable; main() renamed variables, allow '-n' or 'n' as valid line number option

diff --git a/catless b/catless
--- a/catless
+++ b/catless
@@ -7,7 +7,7 @@
 # Author       : Copyright © 2020, Richard B. Romig, LudditeGeek@Mosfanet
 # Email        : rick.romig@gmail.com | rick.romig@mymetronet.com
 # Crated       : 02 Jan 2020
-# Updated      : 25 Jun 2026
+# Updated      : 01 Jul 2026
 # Comments     : Checks to see if passed argument is a valid text or json file.
 #              : To show line numbers, use -n after the file name.
 # TODO (Rick)  :
@@ -29,48 +29,25 @@
 # shellcheck source=/home/rick/bin/functionlib
 source ~/bin/functionlib || { printf "\e[91mERROR:\e[0m Unable to source functionlib\n"; exit 1; }
 
-## Global Variables ##
-
-readonly script="${0##*/}"
-readonly version="7.10.26176"
-EC=0
-
 ## Functions ##
 
 help() {
-  local -r errcode="${1:-1}"
-  local -r updated="25 Jun 2026"
+  local -r script="$1"
+  local -r version="$2"
+	local errcode="${3:-1}"
+  local -r updated="01 Jul 2026"
   cat <<- _HELP_
 	${orange}$script${normal} $version (updated $updated)
 	Displays a text file using either cat or less depending the number of lines in
 	the file and the number of rows in the current terminal window. Less is used when
 	the number of lines is greater than the 87% of the rows, otherwise cat is used.
 
-	${green}Usage:${normal} $script [-h] filename [-n]
+	${green}Usage:${normal} $script [-h] filename [-n|n]
 	${orange}Available options:${normal}
 	  -h  Show this help message and exit.
 	  -n  enable line numbers (follows filename and is case-insensitive).
 	_HELP_
   exit "$errcode"
-}
-
-check_file() {
-	local -r filename="$1"
-	if [[ ! -f "$filename" ]]; then
-		printf "%s %s not found.\n" "$RED_ERROR" "$filename" >&2
-		EC="$E_FILENOTFOUND"
-		return "$FALSE"
-	elif [[ ! -s "$filename" ]]; then
-		printf "%s %s is an empty file.\n" "$RED_ERROR" "$filename" >&2
-		EC="$E_INVALID_ARG"
-		return "$FALSE"
-	elif grep -qEi "text|json" < <(file -bL "$filename"); then
-		return "$TRUE"
-	else
-		printf "%s %s is not a valid text file.\n" "$RED_ERROR" "$filename" >&2
-		EC="$E_INVALID_ARG"
-		return "$FALSE"
-	fi
 }
 
 over_max() {
@@ -82,11 +59,27 @@ over_max() {
 	(( filelines > catmax )) && return "$TRUE" || return "$FALSE"
 }
 
+check_file() {
+	local -r filename="$1"
+	if [[ ! -f "$filename" ]]; then
+		printf "%s %s not found.\n" "$RED_ERROR" "$filename" >&2
+		return "$FALSE"
+	elif [[ ! -s "$filename" ]]; then
+		printf "%s %s is an empty file.\n" "$RED_ERROR" "$filename" >&2
+		return "$FALSE"
+	elif grep -qEi "text|json" < <(file -bL "$filename"); then
+		return "$TRUE"
+	else
+		printf "%s %s is not a valid text file.\n" "$RED_ERROR" "$filename" >&2
+		return "$FALSE"
+	fi
+}
+
 view_file() {
   local -r textfile="$1"
-  local -r linenumbers="$2"
+  local -r num_flag="$2"
   if over_max "$textfile"; then
-    case "$linenumbers" in
+    case "$num_flag" in
       0 )
         less -N "$textfile" ;;
       * )
@@ -94,7 +87,7 @@ view_file() {
     esac
     head -n5 "$textfile"
   else
-    case "$linenumbers" in
+    case "$num_flag" in
       0 )
         cat -n "$textfile" ;;
       * )
@@ -102,18 +95,23 @@ view_file() {
     esac
   fi
   printf "%sFile: %s%s\n" "$reverse" "$textfile" "$normal"
+	return 0
 }
 
 main() {
-	local linenumbers
-	[[ $1 == "-h" ]] && help 0
+	local -r script="${0##*/}"
+	local -r version="8.0.26182"
+	local -i exit_code=0
+	local num_flag=
+	[[ $1 == "-h" ]] && help "$script" "$version" 0
 	local -r filename="$1"
-	local arg2="${2,,}"	# make argument lowercase
-	arg2="${arg2:0:2}"	# take 1st two characters
-	[[ "$arg2" == "-n" ]] && linenumbers="$TRUE" || linenumbers="$FALSE"
-	check_file "$filename" && view_file "$filename" "$linenumbers"
+	local num_opt="${2,,}"		# make argument lowercase
+	num_opt="${num_opt:0:2}"	# take 1st two characters
+	[[ "$num_opt" == "-n" || "$num_opt" == "n" ]] && num_flag="$TRUE" || num_flag="$FALSE"
+	check_file "$filename" && view_file "$filename" "$num_flag"
+	exit_code="$?"
 	over_line "$script $version"
-	exit "$EC"
+	exit "$exit_code"
 }
 
 ## Execution ##
