Redirected 'not a text file' error to stderr.

diff --git a/catless b/catless
--- a/catless
+++ b/catless
@@ -27,8 +27,8 @@ fi
 ## Variables ##
 
 _script=$(basename "$0"); readonly _script
-readonly _version="0.4.0"
-readonly _updated="20 Nov 2023"
+readonly _version="0.4.1"
+readonly _updated="29 Nov 2023"
 
 ## Functions ##
 
@@ -83,7 +83,7 @@ elif is_text "$1"; then
   filename="$1"
   main "$filename"
 else
-  printf "%s %s is not a text file.\n" "$red_error" "$1"
+  printf "%s %s is not a text file.\n" "$red_error" "$1" >&2
   help 1
 fi
 exit
