catless: sourced functionlib.bash

diff --git a/catless b/catless
--- a/catless
+++ b/catless
@@ -7,42 +7,39 @@
 # Author       : Copyright © 2020, Richard B. Romig, LudditeGeek@Mosfanet
 # Email        : rick.romig@gmail.com | rick.romig@mymetronet.com
 # Crated       : 02 Jan 2020
-# Updated      : 02 Jul 2026
+# Updated      : 06 Aug 2026
+# Version      : 8.2.26218
 # Comments     : Checks to see if passed argument is a valid text or json file.
 #              : To show line numbers, use -n after the file name.
 # TODO (Rick)  :
 # License      : GNU General Public License, version 2.0
 # License URL  : https://github.com/RickRomig/scripts/blob/main/LICENSE
 ###############################################################################
-# This program is free software; you can redistribute it and/or modify
-# it under the terms of the GNU General Public License as published by
-# the Free Software Foundation; either version 2 of the License, or
-# (at your option) any later version.
+# This program is free software; you can redistribute it and/or modify it under
+# the terms of the GNU General Public License as published by the Free Software
+# Foundation; either version 2 of the License, or (at your option) any later
+# version.
 #
-# This program is distributed in the hope that it will be useful,
-# but WITHOUT ANY WARRANTY; without even the implied warranty of
-# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
-# GNU General Public License for more details.
+# This program is distributed in the hope that it will be useful, but WITHOUT
+# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
+# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
 ###############################################################################
 
-## Source function library ##
-# shellcheck source=/home/rick/bin/functionlib
-source ~/bin/functionlib || { printf "\e[91mERROR:\e[0m Unable to source functionlib\n"; exit 1; }
-
-## Functions ##
+# shellcheck source=/home/rick/bin/functionlib.bash
+source ~/bin/functionlib.bash || { printf "\e[91mERROR:\e[0m Unable to source functionlib.bash\n"; exit 1; }
 
 help() {
   local -r script="$1"
   local -r version="$2"
-	local errcode="${3:-1}"
-  local -r updated="02 Jul 2026"
+	local -ri errcode="${3:-1}"
+  local -r updated="06 Aug 2026"
   cat <<- _HELP_
 	${orange}$script${normal} $version (updated $updated)
 	Displays a text file using either cat or less depending the number of lines in
 	the file and the number of rows in the current terminal window. Less is used when
 	the number of lines is greater than the 87% of the rows, otherwise cat is used.
 
-	${green}Usage:${normal} $script [-h] filename [-n|n]
+	${green}Usage:${normal} $script [-h] [filename [-n|n]]
 	${orange}Available options:${normal}
 	  -h  Show this help message and exit.
 	  -n  enable line numbers (follows filename and is case-insensitive).
@@ -51,7 +48,6 @@ help() {
 }
 
 over_max() {
-	# Returns TRUE (0) if number of lines in file > number of rows in terminal
 	local -r textfile="$1"
 	local catmax filelines
 	catmax=$(( $(tput lines)*87/100 ))
@@ -77,7 +73,7 @@ check_file() {
 
 view_file() {
   local -r textfile="$1"
-  local -r num_flag="$2"
+  local -ri num_flag="$2"
   if over_max "$textfile"; then
     case "$num_flag" in
       0 )
@@ -100,13 +96,13 @@ view_file() {
 
 main() {
 	local -r script="${0##*/}"
-	local -r version="8.1.26183"
+	local -r version="8.2.26218"
 	local -i exit_code=0
 	local num_flag="$FALSE"
 	[[ $1 == "-h" ]] && help "$script" "$version" 0
 	local -r filename="$1"
 	local -l num_opt="$2"	# make argument lowercase
-	[[ "${num_opt:0:1}" == "-" ]] && num_opt="${num_opt:0:2}"	# take 1st two characters
+	[[ "${num_opt:0:1}" == "-" ]] && num_opt="${num_opt:0:2}"	# take 1st two characters if 1st is '-'
 	[[ "$num_opt" == "-n" || "$num_opt" == "n" ]] && num_flag="$TRUE" || num_flag="$FALSE"
 	check_file "$filename" && view_file "$filename" "$num_flag"
 	exit_code="$?"
