Removed is_text function, placing the functionality into the elif statement that originally called it. Added a check to determine if the selected file is empty.

diff --git a/catless b/catless
--- a/catless
+++ b/catless
@@ -27,28 +27,24 @@ fi
 ## Variables ##
 
 _script=$(basename "$0"); readonly _script
-readonly _version="0.4.1"
-readonly _updated="29 Nov 2023"
+readonly _version="0.4.2"
+readonly _updated="03 Dec 2023"
 
 ## Functions ##
 
 help() {
   local errcode="${1:-2}"
   cat << END_HELP
-  Usage: $_script [filename] [-h] [--help]
+  Usage: $_script filename [-h] [--help]
 
   $_script displays a text file using either cat or less depending the number of
   lines in the file and the number of rows in the current terminal window. Less 
   is used when the number of lines is greater than the 87% of the rows, otherwise
   cat is used.
 
-"$_script v$_version (updated $_updated)"
+$_script v$_version (updated $_updated)
 END_HELP
   exit "$errcode"
-}
-
-is_text() {
-  file -bL --mime "$1" | grep -q '^text' && return "$TRUE" || return "$FALSE"
 }
 
 main() {
@@ -79,7 +75,10 @@ elif [[ "$1" = "-h" || "$1" = "--help" ]]; then
 elif [[ ! -f "$1" ]]; then
   printf "%s %s not found.\n" "$red_error" "$1" >&2
   help 2
-elif is_text "$1"; then
+elif [[ ! -s "$1" ]]; then
+  printf "%s %s is an empty file.\n" "$red_error" "$1" >&2
+  exit 1
+elif file -bL --mime "$1" | grep -q '^text'; then
   filename="$1"
   main "$filename"
 else
