Revert "catless: GPL statement; if no option selected, default action is to display without line numbers"
This reverts commit 8adf2cc92269a984b96dd88829dc7a3e7a78d7d3.

diff --git a/catless b/catless
--- a/catless
+++ b/catless
@@ -4,24 +4,14 @@
 # Description  : view text file with less or cat based on terminal window size.
 # Dependencies : none
 # Arguments    : See help()
-# Author       : Copyright © 2020, Richard B. Romig, LudditeGeek@Mosfanet
+# Author       : Copyright ©  2020, Richard B. Romig, LudditeGeek@Mosfanet
 # Email        : rick.romig@gmail.com | rick.romig@mymetronet.com
 # Crated       : 02 Jan 2020
-# Updated      : 07 Aug 2025
+# Updated      : 16 Jul 2025
 # Comments     : Checks to see if passed argument is a valid text or json file.
 # TODO (Rick)  :
 # License      : GNU General Public License, version 2.0
 # License URL  : https://github.com/RickRomig/scripts/blob/main/LICENSE
-##########################################################################
-# This program is free software; you can redistribute it and/or modify
-# it under the terms of the GNU General Public License as published by
-# the Free Software Foundation; either version 2 of the License, or
-# (at your option) any later version.
-#
-# This program is distributed in the hope that it will be useful,
-# but WITHOUT ANY WARRANTY; without even the implied warranty of
-# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
-# GNU General Public License for more details.
 #############################################################################
 
 ## Shellcheck Directives ##
@@ -41,26 +31,37 @@ set -eu
 ## Global Variables ##
 
 readonly script="${0##*/}"
-readonly version="6.4.25218"
+readonly version="6.3.25197"
 
 ## Functions ##
 
 help() {
   local errcode="${1:-2}"
-  local updated="07 Aug 2025"
+  local updated="29 Jun 2025"
   cat << _HELP_
 ${orange}$script${normal} $version (updated $updated)
 Displays a text file using either cat or less depending the number of lines in
 the file and the number of rows in the current terminal window. Less is used when
 the number of lines is greater than the 87% of the rows, otherwise cat is used.
 
-${green}Usage:${normal} $script [-h] [-f filename] [-n filename]
+${green}Usage:${normal} $script [-h] [-f filename] [-n filename] [-N]
 ${orange}Available options:${normal}
   -f  View file without line numbers.
   -h  Show this help message and exit.
   -n  View file with line numbers.
+  -N  Display GPL Terms & Conditions notice.
 _HELP_
   exit "$errcode"
+}
+
+show_notice() {
+  local script_dir
+  script_dir=$(dirname "$(readlink -f "${0}")")
+	printf "%s\n" "$script"
+	printf "Displays a text file using either cat or less.\n"
+	printf "Copyright (C) 2020, Richard B. Romig\n"
+	printf "Email: rick.romig@gmail.com\n\n"
+	cat "$script_dir/files/gpl_notice.txt"
 }
 
 check_file() {
@@ -128,6 +129,9 @@ main() {
 			linenumbers="$TRUE"
 			check_file "$filename" && view_file "$filename" "$linenumbers"
 			;;
+		N )
+			show_notice
+			;;
 		: )
 			printf "%s Must supply an argument to -%s.\n" "$RED_ERROR" "$OPTARG" >&2
 			help 2
@@ -138,7 +142,7 @@ main() {
 	esac
 	noOpt=0
 	done
-	[[ "$noOpt" -eq 1 ]] && { filename="$1"; check_file "$filename" && view_file "$filename" "$linenumbers"; }
+	[[ "$noOpt" = 1 ]] && { printf "%s No option passed.\n" "$RED_ERROR" >&2; help 1; }
 	shift "$(( OPTIND - 1 ))"
 	over_line "$script $version"
 	exit
