check-updates: system-reboot() - check for /var/run/reboot-required.pkgs added

diff --git a/check-updates b/check-updates
--- a/check-updates
+++ b/check-updates
@@ -7,7 +7,7 @@
 # Author       : Copyright (C) 2018, Richard Romig, Mosfanet
 # Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
 # Crated       : 08 Dec 2018
-# Updated      : 25 May 2026
+# Updated      : 10 Jun 2026
 # Comments     : For Debian/Ubuntu-based Linux distributions
 #              : apt-get is better suited than apt for use in scripts.
 #              : Lists available updates. Updates can be deferred.
@@ -28,12 +28,12 @@
 
 ## Load function library ##
 # shellcheck source=/home/rick/bin/functionlib
-source functionlib || { printf "\e[91mERROR:\e[0m Unable to source functionlib\n"; exit 1; }
+source ~/bin/functionlib || { printf "\e[91mERROR:\e[0m Unable to source functionlib\n"; exit 1; }
 
 ## Global Variables ##
 
 readonly script="${0##*/}"
-readonly version="10.11.26145"
+readonly version="10.12.26161"
 SECONDS=0
 
 ## Functions ##
@@ -47,7 +47,7 @@ cleanup() {
 
 help() {
 	local errcode="${1:-1}"
-  local updated="25 May 2026"
+  local updated="10 Jun 2026"
 	cat << _HELP_
 ${orange}$script${normal} $version, Upated: $updated
 Performs a system update using either Apt-get or Nala.
@@ -75,7 +75,7 @@ check_disk_space() {
 }
 
 system_reboot() {
-  cat /var/run/reboot-required.pkgs
+  [[ -f /var/run/reboot-required.pkgs ]] && cat /var/run/reboot-required.pkgs
   printf "\n%s*** REBOOT REQUIRED ***%s\n" "$orange" "$normal"
   if default_no "Do you want to reboot now?"; then
     printf "Rebooting the system...\n"
