check-updates: main() - corrected call to help() for 'No arument passed error'

diff --git a/check-updates b/check-updates
--- a/check-updates
+++ b/check-updates
@@ -383,7 +383,7 @@ main() {
 		esac
 		noOpt=0
   done
-	[[ "$noOpt" = 1 ]] && { printf "%s No argument passed.\n" "$RED_ERROR" >&2; help "$E_MISSING_ARG"; }
+	[[ "$noOpt" = 1 ]] && { printf "%s No argument passed.\n" "$RED_ERROR" >&2; help "$script" "$version" "$E_MISSING_ARG"; }
 	shift "$(( OPTIND - 1 ))"
   over_line "$script $version"
   [[ -f /var/run/reboot-required || -f /run/reboot-required ]] && system_reboot
