checkiso 0.3.3 - assigned names to $1 & $2 arguments.

diff --git a/checkiso b/checkiso
--- a/checkiso
+++ b/checkiso
@@ -115,7 +115,7 @@ elif [[ -f "$isofile" && -f "$checksum" ]]; then
   done
 else
   printf "%s File(s) not found.\n" "$red_error" >&2
-  [[ -f "$1" ]] || printf "%s not found.\n" "$1" >&2
-  [[ -f "$2" ]] || printf "%s not found.\n" "$2" >&2
+  [[ -f "$1isofile" ]] || printf "%s not found.\n" "$1" >&2
+  [[ -f "$checksum" ]] || printf "%s not found.\n" "$2" >&2
 	usage 2
 fi
