check-versions - one method for getting the installed version of a package using current_version() function; standardize variable names for packages.

diff --git a/check-versions b/check-versions
--- a/check-versions
+++ b/check-versions
@@ -8,7 +8,7 @@
 # Author       : Copyright (C) 2021, Richard B. Romig
 # Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
 # Created      : 24 Aug 2021
-# Last updated : 01 Jul 2024
+# Last updated : 22 Jul 2024
 # Comments     : Ignores Beta and Release Candidate versions in GitHub releases.
 #              : Chromium browser does not create config directory until opened once.
 # TODO (Rick)  :
@@ -35,6 +35,13 @@ cleanup() {
 	[[ -f "$tmp_file" ]] && rm -f "$tmp_file"
 }
 
+current_version() {
+  local cv pkg
+  pkg="$1"
+  cv=$(dpkg -l "$pkg" 2>/dev/null | awk '/ii/ {print $3}' | sed 's/[~+-].*//')
+  echo "$cv"
+}
+
 github_versions() {
   local cur_ver github_url new_ver package packages release_path
   github_url="https://github.com"
@@ -47,23 +54,23 @@ github_versions() {
     case "$package" in
       "bat" )
         release_path="sharkdp/bat/releases"
-        cur_ver=$(dpkg -l | awk '$2 == "bat" {print $3}' | sed 's/[+-].*//')
+        cur_ver=$(current_version "$package")
       ;;
       "micro" )
         release_path="zyedidia/micro/releases"
-        cur_ver=$(dpkg -l | awk '$2 == "micro" {print $3}' | sed 's/[+-].*//')
+        cur_ver=$(current_version "$package")
       ;;
       "marktext" )
         release_path="marktext/marktext/releases"
-        cur_ver=$(dpkg -l | awk '$2 == "marktext" {print $3}' | sed 's/[+-].*//')
+        cur_ver=$(current_version "$package")
       ;;
 		  "codium" )
 			  release_path="VSCodium/vscodium/releases"
-			  cur_ver=$(dpkg -l | awk '$2 == "codium" {print $3}' | sed 's/[+-].*//')
+        cur_ver=$(current_version "$package")
       ;;
       "fastfetch" )
         release_path="fastfetch-cli/fastfetch/releases"
-			  cur_ver=$(dpkg -l | awk '$2 == "fastfetch" {print $3}' | sed 's/[+-].*//')
+        cur_ver=$(current_version "$package")
       ;;
       * )
         printf "%s Invalid package name - %s\n" "$red_error" "${package,,}" >&2
@@ -94,42 +101,52 @@ github_versions() {
 }
 
 apt_tools() {
-	local packages pkg
+	local cur_ver packages package
   packages=( bluefish featherpad geany gedit git glow nano shellcheck xed )
+
 	printf "%-15s%s\n" "Package" "Version"
-	for pkg in "${packages[@]}"; do
-		if exists "$pkg"; then
-		  printf "%s%-15s%s" "${darkgray}" "${pkg^}" "${gray}"
-			case "$pkg" in
+	for package in "${packages[@]}"; do
+		if exists "$package"; then
+		  printf "%s%-15s%s" "${darkgray}" "${package^}" "${gray}"
+			case "$package" in
         bluefish )
-          printf "%s\n" "$(bluefish --version | awk '/^Bluefish/ {print $NF}')"
+          cur_ver=$(current_version "$package")
+          printf "%s\n" "$cur_ver"
         ;;
         featherpad )
-          printf "%s\n" "$(dpkg -l | awk '$2 == "featherpad" {print $3}' | sed 's/[+-].*//')"
-        ;;
+          cur_ver=$(current_version "$package")
+          printf "%s\n" "$cur_ver"
+       ;;
 				geany )
-					printf "%s\n" "$(geany --version | cut -d' ' -f2)"
+          cur_ver=$(current_version "$package")
+          printf "%s\n" "$cur_ver"
         ;;
         gedit )
-					printf "%s\n" "$(gedit --version | cut -d' ' -f4)"
+          cur_ver=$(current_version "$package")
+          printf "%s\n" "$cur_ver"
         ;;
         git )
-          printf "%s\n" "$(git --version | cut -d' ' -f3)"
+          cur_ver=$(current_version "$package")
+          printf "%s\n" "$cur_ver"
         ;;
 				glow )
-					printf "%s\n" "$(glow --version | cut -d' ' -f3 | sed 's/^v//')"
+          cur_ver=$(current_version "$package")
+          printf "%s\n" "$cur_ver"
         ;;
 				nano )
-					printf "%s\n" "$(nano --version | awk '/version/ {print $NF}')"
+          cur_ver=$(current_version "$package")
+          printf "%s\n" "$cur_ver"
         ;;
         xed )
-          printf "%s\n" "$(xed --version | cut -d' ' -f4)"
+          cur_ver=$(current_version "$package")
+          printf "%s\n" "$cur_ver"
         ;;
         shellcheck )
-          printf "%s\n" "$(shellcheck --version | awk '/version:/ {print $NF}')"
+          cur_ver=$(current_version "$package")
+          printf "%s\n" "$cur_ver"
         ;;
 				* )
-          printf "%s Invalid package name - %s\n" "$red_error" "${pkg^}" >&2
+          printf "%s Invalid package name - %s\n" "$red_error" "${package^}" >&2
 			esac
 		fi
 	done
@@ -137,33 +154,40 @@ apt_tools() {
 }
 
 terminals() {
-	local packages pkg
+	local cur_ver packages package
   packages=( gnome-terminal kitty lxterminal terminator xfce4-terminal xterm )
+
 	printf "%-15s%s\n" "Terminal" "Version"
-	for pkg in "${packages[@]}"; do
-		if exists "$pkg"; then
-			printf "%s%-15s%s" "${darkgray}" "${pkg^}" "${gray}"
-			case "$pkg" in
+	for package in "${packages[@]}"; do
+		if exists "$package"; then
+			printf "%s%-15s%s" "${darkgray}" "${package^}" "${gray}"
+			case "$package" in
         kitty )
-          printf "%s\n" "$(dpkg -l | awk '$2 == "kitty" {print $3}' | sed 's/[+-].*//')"
+          cur_ver=$(current_version "$package")
+          printf "%s\n" "$cur_ver"
         ;;
         terminator )
-          printf "%s\n" "$(dpkg -l | awk '$2 == "terminator" {print $3}' | sed 's/[+-].*//')"
+          cur_ver=$(current_version "$package")
+          printf "%s\n" "$cur_ver"
         ;;
         gnome-terminal )
-          printf "%s\n" "$(dpkg -l | awk '$2 == "gnome-terminal" {print $3}' | sed 's/[+-].*//')"
+          cur_ver=$(current_version "$package")
+          printf "%s\n" "$cur_ver"
         ;;
         lxterminal )
-          printf "%s\n" "$(dpkg -l | awk '$2 == "lxterminal" {print $3}' | sed 's/[+-].*//')"
+          cur_ver=$(current_version "$package")
+          printf "%s\n" "$cur_ver"
         ;;
         xfce4-terminal )
-          printf "%s\n" "$(dpkg -l | awk '$2 == "xfce4-terminal" {print $3}' | sed 's/[+-].*//')"
+          cur_ver=$(current_version "$package")
+          printf "%s\n" "$cur_ver"
         ;;
         xterm )
-          printf "%s\n" "$(dpkg -l | awk '$2 == "xterm" {print $3}' | sed 's/[+-].*//')"
+          cur_ver=$(current_version "$package")
+          printf "%s\n" "$cur_ver"
         ;;
 				* )
-					printf "%s Invalid package name - %s\n" "$red_error" "${pkg^}" >&2
+					printf "%s Invalid package name - %s\n" "$red_error" "${package^}" >&2
 			esac
 		fi
 	done
@@ -171,27 +195,33 @@ terminals() {
 }
 
 browsers() {
-	local packages pkg
+	local cur_ver packages package
   packages=( brave-browser chromium firefox google-chrome )
+
 	printf "%-15s%s\n" "Browser" "Version"
-	for pkg in "${packages[@]}"; do
-		if exists "$pkg"; then
-			printf "%s%-15s%s" "${darkgray}" "${pkg^}" "${gray}"
-			case "$pkg" in
+	for package in "${packages[@]}"; do
+		if exists "$package"; then
+			printf "%s%-15s%s" "${darkgray}" "${package^}" "${gray}"
+			case "$package" in
 				brave-browser )
-					printf "%s\n" "$(brave-browser --version | cut -d' ' -f3)"
+          cur_ver=$(current_version "$package")
+          printf "%s\n" "$cur_ver"
         ;;
 				chromium )
-          printf "%s\n" "$(chromium --version | awk '/Chromium/ {print $2}')"
+          cur_ver=$(current_version "$package")
+          printf "%s\n" "$cur_ver"
         ;;
 				firefox )
-					printf "%s\n" "$(firefox --version | cut -d' ' -f3 | sed 's/esr/ ESR/')"
+          cur_ver=$(current_version "$package")
+          printf "%s\n" "$cur_ver"
         ;;
 				google-chrome )
-					printf "%s\n" "$(google-chrome --version | cut -d' ' -f3)"
+          package+="-stable"
+          cur_ver=$(current_version "$package")
+          printf "%s\n" "$cur_ver"
         ;;
 				* )
-					printf "%s Invalid package name - %s\n" "$red_error" "${pkg^}" >&2
+					printf "%s Invalid package name - %s\n" "$red_error" "${package^}" >&2
 			esac
 		fi
 	done
@@ -201,7 +231,7 @@ browsers() {
 main() {
   local _script _version
   _script; _script=$(basename "$0")
-  _version="11.8.24183"
+  _version="12.0.24204"
   clear
   printf "%s v%s\n" "$_script" "$_version"
   printf "Newest & installed versions of select programs.\n\n"
