check-versions: main() replaced clear with clearscreen() to eliminate scrollback

diff --git a/check-versions b/check-versions
--- a/check-versions
+++ b/check-versions
@@ -8,7 +8,7 @@
 # Author       : Copyright (C) 2021, Richard B. Romig
 # Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
 # Created      : 24 Aug 2021
-# Last updated : 04 May 2026
+# Last updated : 25 May 2026
 # Comments     : Starting with Micro 2.0.14, no deb package released. Uses tar.gz
 #              : Chromium browser does not create config directory until opened once.
 # TODO (Rick)  :
@@ -28,7 +28,7 @@
 
 ## Load function library ##
 # shellcheck source=/home/rick/bin/functionlib
-source functionlib || { printf "\e[91mERROR:\e[0m Unable to source functionlib\n"; exit 1; }
+source ~/bin/functionlib || { printf "\e[91mERROR:\e[0m Unable to source functionlib\n"; exit 1; }
 
 ## Global Variables ##
 
@@ -166,10 +166,10 @@ browsers() {
 
 main() {
   local script="${0##*/}"
-  local version="20.4.26124"
+  local version="20.5.26145"
   trap cleanup EXIT
   check_package curl
-  clear
+  clearscreen
   box "$script $version"
   printf "\n"
   github_packages
