Added variable to show number of last available option.

diff --git a/check-logs b/check-logs
--- a/check-logs
+++ b/check-logs
@@ -27,8 +27,8 @@ fi
 ## Variables ##
 
 _script=$(basename "$0"); readonly _script
-readonly _version="0.8.3"
-readonly _updated="21 Nov 2023"
+readonly _version="0.8.4"
+readonly _updated="26 Nov 2023"
 readonly lhost="${HOSTNAME:-$(hostname)}"
 
 ## Functions ##
@@ -309,7 +309,7 @@ while true; do
       15 )
         leave "${orange}Mischief managed.${normal}" ;;
       * )
-        printf "%sInvalid choice. Try again.%s\n" "$lightred" "$normal" >&2
+        printf "%sInvalid choice.%s Choose 1-%d.\n" "$lightred" "$normal" "${#options[@]}" >&2
     esac
   done
 done
diff --git a/check-updates b/check-updates
--- a/check-updates
+++ b/check-updates
@@ -31,8 +31,8 @@ set -euo pipefail
 ## Variables ##
 
 _script=$(basename "$0"); readonly _script
-readonly _version="2.0.8"
-readonly _updated="13 Oct 2023"
+readonly _version="2.0.9"
+readonly _updated="26 Nov 2023"
 
 ## Functions ##
 
@@ -148,7 +148,7 @@ apt_update() {
           break
         ;;
         * )
-          printf "%sInvalid option!%s Select 1..5\n" "$lightred" "$normal" >&2
+          printf "%sInvalid option!%s Select 1..%d\n" "$lightred" "$normal" "${#options[@]}" >&2
       esac
     done
   else
