check-updates - replaced word options with getopts; updated help(); expanded check for flatpak.

diff --git a/check-updates b/check-updates
--- a/check-updates
+++ b/check-updates
@@ -3,11 +3,11 @@
 # Script Name  : check-updates
 # Description  : check for updates and install if necessary.
 # Dependencies : apt-get (optional: nala, flatpak, cinnamon-spice-updater)
-# Arguments    : apt, nala, help
+# Arguments    : see help()
 # Author       : Copyright (C) 2018, Richard Romig, Mosfanet
 # Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
 # Crated       : 08 Dec 2018
-# Updated      : 15 Mar 2025
+# Updated      : 27 Mar 2025
 # Comments     : For Debian/Ubuntu-based Linux distributions
 #              : apt-get is better suited than apt for use in scripts.
 #              : Lists available updates. Updates can be deferred.
@@ -32,14 +32,14 @@ set -eu
 ## Global Variables ##
 
 script=$(basename "$0"); readonly script
-readonly version="5.0.25074"
+readonly version="6.0.25086"
 SECONDS=0
 
 ## Functions ##
 
 help() {
 	local errcode="${1:-2}"
-  local updated="15 Mar 2025"
+  local updated="27 Mar 2025"
 	cat << _HELP_
 ${orange}$script${normal} $version, Upated: $updated
 Performs a system update using Apt or Nala.
@@ -47,40 +47,13 @@ Performs a system update using Apt or Nala.
 ${green}Usage:${normal} $script [OPTION]
 
 ${orange}Available options:${normal}
-  apt	  Perform a system upgrade using apt-get
-  help	Show this help message and exit
-  nala	Perform a system upgrade using nala
+  -a	  Perform a system upgrade using apt-get
+  -h    Show this help message and exit
+  -n    Perform a system upgrade using nala
 ${orange}Notes:${normal}
-  1) No argument defaults to using nala
-  2) If nala is not installed, defers to using apt-get
-  3) Argument is not case-sensitive
+  If nala is not installed, defers to using apt-get
 _HELP_
   exit "$errcode"
-}
-
-check_action() {
-  local action="$1"
-  case "${action,,}" in
-    apt )
-      show_header
-      check_disk_space
-      sudo_login 2
-      apt_update ;;
-    nala )
-      show_header
-      check_disk_space
-      sudo_login 2
-      if exists nala; then
-        nala_update
-      else
-        apt_update
-      fi ;;
-    help )
-      help 0 ;;
-    * )
-      printf "%s Invalid argument - %s\n" "$RED_ERROR" "$action"
-      help 1
-  esac
 }
 
 check_disk_space() {
@@ -197,7 +170,7 @@ update_summary() {
 	nnew=$(echo "$summary" | cut -d' ' -f2)
 	nrem=$(echo "$summary" | cut -d' ' -f3)
 	ndef=$(echo "$summary" | cut -d' ' -f4)
-	printf "\n%s to upgrade, %s new packages, %s to remove, %s deferred.\n\n" "$nupd" "$nnew" "$nrem" "$ndef"
+	printf "\n%s to upgrade, %s new packages, %s to remove, %s deferred.\n" "$nupd" "$nnew" "$nrem" "$ndef"
 }
 
 count_updates() {
@@ -298,10 +271,36 @@ _HEADER_
 }
 
 main() {
-  local action="${1:-nala}" # Default is nala
-  check_action "$action"
+  local noOpt opt optstr
+	noOpt=1
+	optstr=":ahn"
+	while getopts "$optstr" opt; do
+    case "$opt" in
+      a )
+        show_header
+        check_disk_space
+        sudo_login 2
+        apt_update
+      ;;
+      h )
+        help 0
+      ;;
+      n )
+        show_header
+        check_disk_space
+        sudo_login 2
+        if exists nala; then nala_update; else apt_update; fi
+      ;;
+			? )
+				printf "%s Invalid option -%s\n" "$RED_ERROR" "$OPTARG" >&2
+				help 2
+		esac
+		noOpt=0
+  done
+	[[ "$noOpt" = 1 ]] && { printf "%s No argument passed.\n" "$RED_ERROR" >&2; help 1; }
+	shift "$(( OPTIND - 1 ))"
   exists cinnamon-spice-updater && update_spices
-  exists flatpak && update_flatpak
+  if exists flatpak; then update_flatpak; else printf "\nFlatpak is not installed.\n"; fi
   check_disk_space
   over_line "Update completed in $(format_time $SECONDS)"
   check_reboot_required
