check-updates: added tmp_file to getopts -n if nala is not installed

diff --git a/check-updates b/check-updates
--- a/check-updates
+++ b/check-updates
@@ -7,7 +7,7 @@
 # Author       : Copyright (C) 2018, Richard Romig, Mosfanet
 # Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
 # Crated       : 08 Dec 2018
-# Updated      : 12 Jul 2025
+# Updated      : 22 Jul 2025
 # Comments     : For Debian/Ubuntu-based Linux distributions
 #              : apt-get is better suited than apt for use in scripts.
 #              : Lists available updates. Updates can be deferred.
@@ -33,7 +33,7 @@ set -eu
 ## Global Variables ##
 
 readonly script="${0##*/}"
-readonly version="7.5.25193"
+readonly version="7.6.25203"
 SECONDS=0
 
 ## Functions ##
@@ -288,7 +288,13 @@ main() {
         show_header
         check_disk_space
         sudo_login 1
-        if exists nala; then nala_update; else apt_update; fi
+        if exists nala; then
+          nala_update
+        else
+          tmp_file=$(mktemp -q) || die "Failed to create temporary file." 1
+          trap cleanup EXIT
+          apt_update
+        fi
         ;;
 			N )
 				show_notice
