check-battery: fixed tabs

diff --git a/check-battery b/check-battery
--- a/check-battery
+++ b/check-battery
@@ -7,8 +7,8 @@
 # Author       : Copyright (C) 2020, Richard B. Romig, Mosfanet
 # Email        : rick.romig@gmail.com | rick.romig@mymetronet.com
 # Crated       : 30 Jul 2020
-# Updated      : 06 Aug 2026
-# Version      : 5.7.26218
+# Updated      : 06 Sep 2026
+# Version      : 5.7.26249
 # Comments     : Obtains battery data from upower utility.
 # TODO (Rick)  :
 # License      : GNU General Public License, version 2.0
@@ -33,124 +33,124 @@ BATTERY_DATA=
 # Don't warn about unreachable commands in this function
 # ShellCheck may incorrectly believe that code is unreachable if it's invoked by variable name or in a trap.
 cleanup() {
-  [[ -f "$BATTERY_DATA" ]] && rm -f "$BATTERY_DATA"
+	[[ -f "$BATTERY_DATA" ]] && rm -f "$BATTERY_DATA"
 }
 
 battery_status() {
-  printf "\n%sBattery charge:%s\n" "$orange" "$normal"
-  grep --color=never -E "state|to\ full|to\ empty|percentage" "$BATTERY_DATA"
-  return 0
+	printf "\n%sBattery charge:%s\n" "$orange" "$normal"
+	grep --color=never -E "state|to\ full|to\ empty|percentage" "$BATTERY_DATA"
+	return 0
 }
 
 battery_capacity() {
-  printf "\n%sBattery health:%s\n" "$orange" "$normal"
-  grep --color=never -E "energy-full:|energy-full-design:|capacity:" "$BATTERY_DATA"
-  return 0
+	printf "\n%sBattery health:%s\n" "$orange" "$normal"
+	grep --color=never -E "energy-full:|energy-full-design:|capacity:" "$BATTERY_DATA"
+	return 0
 }
 
 warning_level() {
-  local energy_design energy_actual
-  energy_design=$(awk '/energy-full-design:/ {printf "%i", $2}' "$BATTERY_DATA")
-  energy_actual=$(awk '/energy-full:/ {printf "%i", $2}' "$BATTERY_DATA")
-  if [[ "$energy_actual" -eq 0 || "$energy_design" -eq 0 ]]; then
-    echo "0"
-  else
-    awk '/capacity/ {printf "%i", $2}' "$BATTERY_DATA"
-  fi
-  return 0
+	local energy_design energy_actual
+	energy_design=$(awk '/energy-full-design:/ {printf "%i", $2}' "$BATTERY_DATA")
+	energy_actual=$(awk '/energy-full:/ {printf "%i", $2}' "$BATTERY_DATA")
+	if [[ "$energy_actual" -eq 0 || "$energy_design" -eq 0 ]]; then
+		echo "0"
+	else
+		awk '/capacity/ {printf "%i", $2}' "$BATTERY_DATA"
+	fi
+	return 0
 }
 
 battery_condition() {
-  local warn warn_level
-  warn_level="$(warning_level)"
-  if [[ "$warn_level" -le "0" ]]; then
-    warn="\U1F4A9"
-    printf "%4s%sReplace the battery!%s  %s\n" " " "$red" "$normal" "$warn"
-  elif [[ "$warn_level" -le "35" ]]; then
-    warn="\U1F622"
-    printf "%4s%sThe battery should be replaced.%s  %s\n" " " "$red" "$normal" "$warn"
-  elif [[ "$warn_level" -le "65" ]]; then
-    warn="\U26A0\UFE0F"
-    printf "%4s%sThe battery is getting weak.%s  %s\n" " " "$orange" "$normal" "$warn"
-  else
-    printf "%4s%sThe battery is in good condition.%s\n" " " "$green" "$normal"
-  fi
-  return 0
+	local warn warn_level
+	warn_level="$(warning_level)"
+	if [[ "$warn_level" -le "0" ]]; then
+		warn="\U1F4A9"
+		printf "%4s%sReplace the battery!%s  %s\n" " " "$red" "$normal" "$warn"
+	elif [[ "$warn_level" -le "35" ]]; then
+		warn="\U1F622"
+		printf "%4s%sThe battery should be replaced.%s  %s\n" " " "$red" "$normal" "$warn"
+	elif [[ "$warn_level" -le "65" ]]; then
+		warn="\U26A0\UFE0F"
+		printf "%4s%sThe battery is getting weak.%s  %s\n" " " "$orange" "$normal" "$warn"
+	else
+		printf "%4s%sThe battery is in good condition.%s\n" " " "$green" "$normal"
+	fi
+	return 0
 }
 
 battery_specs() {
-  local battery_serial battery_tech
-  battery_serial=$(awk '{$1=$1}1' <(awk -F: '/serial/ {print $NF}' "$BATTERY_DATA"))
-  [[ -z "$battery_serial" ]] && battery_serial="Not specified"
-  battery_tech=$(awk '{$1=$1}1' <(awk -F: '/technology/ {print $NF}' "$BATTERY_DATA"))
-  [[ -z "$battery_tech" ]] && battery_tech="Not specified"
-  printf "\n%sBattery Data:%s\n" "$orange" "$normal"
-  printf "%4sManufacturer:  %s\n" " " "$(awk '{$1=$1}1' <(awk -F: '/vendor/ {print $NF}' "$BATTERY_DATA"))"
-  printf "%4sModel name:    %s\n" " " "$(awk '{$1=$1}1' <(awk -F: '/model/ {print $NF}' "$BATTERY_DATA"))"
-  printf "%4sSerial number: %s\n" " " "$battery_serial"
-  printf "%4sTechnology:    %s\n" " " "$battery_tech"
-  return 0
+	local battery_serial battery_tech
+	battery_serial=$(awk '{$1=$1}1' <(awk -F: '/serial/ {print $NF}' "$BATTERY_DATA"))
+	[[ -z "$battery_serial" ]] && battery_serial="Not specified"
+	battery_tech=$(awk '{$1=$1}1' <(awk -F: '/technology/ {print $NF}' "$BATTERY_DATA"))
+	[[ -z "$battery_tech" ]] && battery_tech="Not specified"
+	printf "\n%sBattery Data:%s\n" "$orange" "$normal"
+	printf "%4sManufacturer:  %s\n" " " "$(awk '{$1=$1}1' <(awk -F: '/vendor/ {print $NF}' "$BATTERY_DATA"))"
+	printf "%4sModel name:    %s\n" " " "$(awk '{$1=$1}1' <(awk -F: '/model/ {print $NF}' "$BATTERY_DATA"))"
+	printf "%4sSerial number: %s\n" " " "$battery_serial"
+	printf "%4sTechnology:    %s\n" " " "$battery_tech"
+	return 0
 }
 
 ac_status() {
-  local status
-  status=$(awk '/online:/ {print $NF}' < <(/usr/bin/upower -i "$(grep 'AC' < <(/usr/bin/upower -e))"))
-  printf "\n%sAC Power:%s\n" "$orange" "$normal"
-  printf "%4sLaptop is" " "
-  [[ "$status" = "no" ]] && printf " not "
-  printf "plugged in to AC power.\n"
-  return 0
+	local status
+	status=$(awk '/online:/ {print $NF}' < <(/usr/bin/upower -i "$(grep 'AC' < <(/usr/bin/upower -e))"))
+	printf "\n%sAC Power:%s\n" "$orange" "$normal"
+	printf "%4sLaptop is" " "
+	[[ "$status" = "no" ]] && printf " not "
+	printf "plugged in to AC power.\n"
+	return 0
 }
 
 hidpp_battery() {
-  local hidpp_data
-  printf "\n%sHID++ Battery:%s\n" "$orange" "$normal"
-  if grep -q hidpp <(/usr/bin/upower -e); then
-    hidpp_data=$(/usr/bin/upower -i "$(grep hidpp < <(/usr/bin/upower -e))")
-    printf "%4sDevice: %s\n" " " "$(awk '/native-path/ {print $NF}' <<< "$hidpp_data")"
-    printf "%4s%s:   " " " "$(awk '/model/ {print $NF}' <<< "$hidpp_data")"
-    printf "%s\n" "$(awk '/percentage/ {print $NF}' <<< "$hidpp_data")"
-  else
-    printf "%4sNo HID++ battery present.\n" " "
-  fi
-  return 0
+	local hidpp_data
+	printf "\n%sHID++ Battery:%s\n" "$orange" "$normal"
+	if grep -q hidpp <(/usr/bin/upower -e); then
+	    hidpp_data=$(/usr/bin/upower -i "$(grep hidpp < <(/usr/bin/upower -e))")
+		printf "%4sDevice: %s\n" " " "$(awk '/native-path/ {print $NF}' <<< "$hidpp_data")"
+		printf "%4s%s:   " " " "$(awk '/model/ {print $NF}' <<< "$hidpp_data")"
+		printf "%s\n" "$(awk '/percentage/ {print $NF}' <<< "$hidpp_data")"
+	else
+		printf "%4sNo HID++ battery present.\n" " "
+	fi
+	return 0
 }
 
 battery_check() {
-  printf "%s%sBattery Information%s\n" "$bold" "$orange" "$normal"
-  if [[ ! -d /proc/acpi/button/lid/ ]]; then
-    printf "\nThis system is not a laptop.\n" >&2
-    return "$E_UNSUPPORTED"
-  fi
-  if ! grep -q 'BAT' < <(/usr/bin/upower -e); then
-    printf "\n%sNo battery detected.%s\n" "$lightred" "$normal" >&2
-    ac_status
-    hidpp_battery
-    return 0
-  fi
-  BATTERY_DATA=$(mktemp) || die "Failed to create temporary file." "$E_TEMP_DIR"
-  trap cleanup EXIT
-  /usr/bin/upower -i "$(grep 'BAT' < <(/usr/bin/upower -e))" > "$BATTERY_DATA"
-  printf "\n%sBattery:%s %s\n" "$orange" "$normal" "$(awk '/native-path:/ {print $NF}' "$BATTERY_DATA")"
-  battery_status
-  battery_capacity
-  battery_condition
-  battery_specs
-  ac_status
-  hidpp_battery
-  return 0
+	printf "%s%sBattery Information%s\n" "$bold" "$orange" "$normal"
+	if [[ ! -d /proc/acpi/button/lid/ ]]; then
+		printf "\nThis system is not a laptop.\n" >&2
+		return "$E_UNSUPPORTED"
+	fi
+	if ! grep -q 'BAT' < <(/usr/bin/upower -e); then
+		printf "\n%sNo battery detected.%s\n" "$lightred" "$normal" >&2
+		ac_status
+		hidpp_battery
+		return 0
+	fi
+	BATTERY_DATA=$(mktemp) || die "Failed to create temporary file." "$E_TEMP_DIR"
+	trap cleanup EXIT
+	/usr/bin/upower -i "$(grep 'BAT' < <(/usr/bin/upower -e))" > "$BATTERY_DATA"
+	printf "\n%sBattery:%s %s\n" "$orange" "$normal" "$(awk '/native-path:/ {print $NF}' "$BATTERY_DATA")"
+	battery_status
+	battery_capacity
+	battery_condition
+	battery_specs
+	ac_status
+	hidpp_battery
+	return 0
 }
 
 main() {
-  local -r script="${0##*/}"
-  local -r version="5.7.26218"
-  local -i exit_code=0
-  clear
-  check_package upower
-  battery_check
-  exit_code="$?"
-  over_line "$script $version"
-  exit "$exit_code"
+	local -r script="${0##*/}"
+	local -r version="5.7.26249"
+	local -i exit_code=0
+	clear
+	check_package upower
+	battery_check
+	exit_code="$?"
+	over_line "$script $version"
+	exit "$exit_code"
 }
 
 main "$@"
