check-updates - check_action(): checks argument and calls appropriated update function; updated help()

diff --git a/check-updates b/check-updates
--- a/check-updates
+++ b/check-updates
@@ -7,7 +7,7 @@
 # Author       : Copyright (C) 2018, Richard Romig, Mosfanet
 # Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
 # Crated       : 08 Dec 2018
-# Updated      : 11 Feb 2025
+# Updated      : 15 Mar 2025
 # Comments     : For Debian/Ubuntu-based Linux distributions
 #              : apt-get is better suited than apt for use in scripts.
 #              : Lists available updates. Updates can be deferred.
@@ -34,13 +34,14 @@ set -eu
 ## Global Variables ##
 
 script=$(basename "$0"); readonly script
-readonly version="4.1.25042"
+readonly version="5.0.25074"
 SECONDS=0
 
 ## Functions ##
 
 help() {
-  local updated="11 Feb 2025"
+	errcode="${1:-2}"
+  local updated="15 Mar 2025"
 	cat << _HELP_
 ${orange}$script${normal} $version, Upated: $updated
 Performs a system update using Apt or Nala.
@@ -49,25 +50,38 @@ ${green}Usage:${normal} $script [OPTION]
 
 ${orange}Available options:${normal}
   apt	  Perform a system upgrade using apt-get
-  help	Show help
+  help	Show this help message and exit
   nala	Perform a system upgrade using nala
 ${orange}Notes:${normal}
-  No argument defaults to using nala
-  Invalid argument defaults to using apt-get
-  Argument is case-insensitive
+  1) No argument defaults to using nala
+  2) If nala is not installed, defers to using apt-get
+  3) Argument is not case-sensitive
 _HELP_
-  exit 0
+  exit "$errcode"
 }
 
 check_action() {
-  local action
-  action="${1:-nala}"         # Default is nala
-  exists nala || action="apt" # if nala not installed, change default to apt
-  case "$action" in
-    apt | nala | help )
-      echo "$action" ;;
+  local action="$1"
+  case "${action,,}" in
+    apt )
+      show_header
+      check_disk_space
+      sudo_login 2
+      apt_update ;;
+    nala )
+      show_header
+      check_disk_space
+      sudo_login 2
+      if exists nala; then
+        nala_update
+      else
+        apt_update
+      fi ;;
+    help )
+      help 0 ;;
     * )
-      echo "apt"
+      printf "%s Invalid argument - %s\n" "$RED_ERROR" "$action"
+      help 1
   esac
 }
 
@@ -286,28 +300,14 @@ _HEADER_
 }
 
 main() {
-  local action
-  action="${1:-nala}"
-  action=$(check_action "${action,,}")
-    show_header
-    check_disk_space
-  case "$action" in
-    apt )
-      sudo_login 2
-      apt_update ;;
-    nala )
-      sudo_login 2
-      nala_update ;;
-    help )
-      help ;;
-    * )
-      diehard  "Invalid argument" "Enter 'apt' 'nala' or leave blank."
-  esac
+  local action="${1:-nala}" # Default is nala
+  check_action "$action"
   exists cinnamon-spice-updater && update_spices
   exists flatpak && update_flatpak
   check_disk_space
   over_line "Update completed in $(format_time $SECONDS)"
   check_reboot_required
+  over_line "$script $version"
   exit
 }
 
