cinnkeys - expanded option to load keybindings to dump them if backup file doesn't exist.

diff --git a/cinnkeys b/cinnkeys
--- a/cinnkeys
+++ b/cinnkeys
@@ -4,8 +4,10 @@
 # Description  : Backup/Restore Cinnamon keybindings to/from a file.
 # Dependencies : none
 # Arguments    : none
-# Author       : Copyright (C) 2021, Richard B. Romig, 12 May 2021
+# Author       : Copyright (C) 2021, Richard B. Romig, MosfaNet
 # Email        : rick.romig@gmail.com | rick.romig@mymetronet.com
+# Created      : 12 May 2021
+# Updated      : 19 Apr 2024
 # Comments     : Backup of Cinnamon keybindings in ~/.config
 #              : Tested with Cinnamon DE on Mint 19.x & 20.x, 21.x, LMDE 5/6, Debian 10/11/12
 # TODO (Rick)  :
@@ -14,7 +16,6 @@
 
 ## Shellcheck Directives ##
 # shellcheck source=/home/rick/bin/functionlib
-# shellcheck disable=SC1091
 
 ## Load function library ##
 
@@ -28,9 +29,10 @@ fi
 ## Variables ##
 
 _script=$(basename "$0"); readonly _script
-readonly _version="0.2.1"
-readonly _updated="01 Dec 2023"
+readonly _version="2.2.24110"
+readonly _updated="19 Apr 2024"
 readonly kb_bu="keybindings-backup.dconf"
+readonly cfg_dir="$HOME/.config"
 readonly verbose_mode="$FALSE"
 
 ## Functions ##
@@ -48,6 +50,7 @@ ${orange}OPTIONS:${normal}
   -v  Enable verbose mode
 $_script v$_version, updated: $_updated
 _END_HELP_
+  printf "%s v%s (updated: %s)\n" "$_script" "$_version" "$_updated"
   exit "$errcode"
 }
 
@@ -65,19 +68,22 @@ if is_cinnamon; then
     case "$opt" in
       d )
         showme "Dumping keybindings to backup file."
-        dconf dump /org/cinnamon/desktop/keybindings/ > "$HOME/.config/$kb_bu"
-        echo "Cinnamon Keybindings dumped to $HOME/.config/$kb_bu."
+        dconf dump /org/cinnamon/desktop/keybindings/ > "$cfg_dir/$kb_bu"
+        printf "Cinnamon Keybindings dumped to %s\n" "$cfg_dir/$kb_bu"
       ;;
       h )
         usage 0
       ;;
       l )
-        if [[ -f "$HOME/.config/$kb_bu" ]]; then
+        if [[ -f "$cfg_dir/$kb_bu" ]]; then
           showme "loading keybindings from backup file."
           dconf load /org/cinnamon/desktop/keybindings/ < "$HOME/.config/$kb_bu"
-          echo "Cinnamon Keybindings loaded from $HOME/.config/$kb_bu."
+          printf "Cinnamon Keybindings loaded from %s\n" "$cfg_dir/$kb_bu"
         else
-          echo "$kb_bu does not exist. Run $_script -b to create it." >&2
+          pirntf "%s does not exist. Creating it...\n" "$kb_bu" >&2
+          showme "Dumping keybindings to backup file."
+          dconf dump /org/cinnamon/desktop/keybindings/ > "$cfg_dir/$kb_bu"
+          printf "Cinnamon Keybindings dumped to %s\n" "$cfg_dir/$kb_bu"
         fi
       ;;
       v )
@@ -85,13 +91,15 @@ if is_cinnamon; then
         showme "Verbose mode enabled."
       ;;
       ? )
-        echo "$red_error Invalid option: -${OPTARG}" >&2
+        printf "%s Invalid option -%s\n" "$red_error" "$OPTARG" >&2
+        usage 2
     esac
     noOpt=0
   done
-  [[ "$noOpt" = 1 ]] && { echo "$red_error No argument passed." >&2; usage 1; }
+  [[ "$noOpt" = 1 ]] && { printf "%s No argument passed.\n" "$red_error" >&2; help 1; }
   shift "$(( OPTIND - 1 ))"
 else
-  echo "The desktop environment is not Cinnamon." >&2
+  pirntf "The desktop environment is not Cinnamon.\n" >&2
+  exit 1
 fi
-leave "$_script v$_version (updated: $_updated)"
+leave "$_script v$_version"
