cinnkeys: refactored main, help, load, & dump functions

diff --git a/cinnkeys b/cinnkeys
--- a/cinnkeys
+++ b/cinnkeys
@@ -1,5 +1,5 @@
 #!/usr/bin/env bash
-##########################################################################
+###############################################################################
 # Script Name  : cinnkeys
 # Description  : Backup/Restore Cinnamon keybindings to/from a file.
 # Dependencies : curl (to download keyubindings from GitHub repo)
@@ -7,121 +7,120 @@
 # Author       : Copyright (C) 2021, Richard B. Romig, MosfaNet
 # Email        : rick.romig@gmail.com | rick.romig@mymetronet.com
 # Created      : 12 May 2021
-# Updated      : 09 Apr 2026
+# Updated      : 05 Aug 2026
+# Version      : 5.0.26217
 # Comments     : Cinnamon keybindings backup file stored in ~/.config
 #              : Tested with Cinnamon DE on Mint 19+, LMDE 5+, Debian 10+
 # TODO (Rick)  :
 # License      : GNU General Public License, version 2
 # License URL  : https://github.com/RickRomig/scripts/blob/main/LICENSE
-##########################################################################
-# This program is free software; you can redistribute it and/or modify
-# it under the terms of the GNU General Public License as published by
-# the Free Software Foundation; either version 2 of the License, or
-# (at your option) any later version.
+###############################################################################
+# This program is free software; you can redistribute it and/or modify it under
+# the terms of the GNU General Public License as published by the Free Software
+# Foundation; either version 2 of the License, or (at your option) any later
+# version.
 #
-# This program is distributed in the hope that it will be useful,
-# but WITHOUT ANY WARRANTY; without even the implied warranty of
-# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
-# GNU General Public License for more details.
-##########################################################################
+# This program is distributed in the hope that it will be useful, but WITHOUT
+# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
+# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
+###############################################################################
 
-## Load function library ##
-# shellcheck source=/home/rick/bin/functionlib
-source functionlib || { printf "\e[91mERROR:\e[0m Unable to source functionlib\n"; exit 1; }
+# shellcheck source=/home/rick/bin/functionlib.bash
+source ~/bin/functionlib.bash || { printf "\e[91mERROR:\e[0m Unable to source functionlib.bash\n"; exit 1; }
 
-## Global Variables ##
-
-readonly script="${0##*/}"
-readonly version="4.2.26068"
-readonly config_dir=~/.config
-readonly bindings_file=keybindings-backup.dconf
-readonly bindings_path=/org/cinnamon/desktop/keybindings/
-
-## Functions ##
+readonly CONFIG_DIR=~/.config
+readonly KEYBINDS=keybindings-backup.dconf
 
 help() {
-  local errcode="${1:-1}"
-  local -r updated="09 Apr 2026"
+  local -r script="$1"
+  local -r version="$2"
+  local -ri errcode="${3:-1}"
+  local -r updated="05 Aug 2026"
   cat << _HELP_
 ${orange}$script${normal} $version, Upated: $updated
-Creates a backup file of Cinnamon keybindings and restores from a backup file.
+Manage Cinnamon keybinding backup.
 
-${green}Usage:${normal} $script [-vc] [-vd] [-h] [-vl]
+${green}Usage:${normal} $script [-cdhl]
 ${orange}Available options:${normal}
-  -c  Copy Cinnamon keybindings from GitHub repo to ~/.config and load keybindings.
-  -d  Dump Cinnamon keybindings to a file in ~/.config.
+  -c  Copy Cinnamon keybindings from repository to ~/.config/keybindings-backup.dconf and load keybindings.
+  -d  Dump current Cinnamon keybindings to ~/.config/keybindings-backup.dconf.
   -h  Show this help message and exit.
-  -l  Load Cinnamon keybindings from the ~/.config backup file.
+  -l  Load Cinnamon keybindings from ~/.config/keybindings-backup.dconf.
 _HELP_
   exit "$errcode"
 }
 
-dump_to_config() {
-  printf "Dumping keybindings to backup file.\n"
-  dconf dump "$bindings_path" > "$config_dir/$bindings_file"
-  printf "Cinnamon Keybindings dumped to %s/%s\n" "$config_dir" "$bindings_file"
+dump_to_backup() {
+  local -r keybinds_db="$1"
+  printf "Dumping current keybindings to %s/%s.\n" "${CONFIG_DIR##*/}" "$KEYBINDS"
+  dconf dump "$keybinds_db" > "$CONFIG_DIR/$KEYBINDS"
+  printf "Cinnamon Keybindings dumped to %s/%s\n" "${CONFIG_DIR##*/}" "$KEYBINDS"
+  return 0
 }
 
-load_from_config() {
-  printf "Loading keybindings from backup file.\n"
-  dconf load "$bindings_path" < "$config_dir/$bindings_file"
-  printf "Cinnamon Keybindings loaded from %s/%s\n" "$config_dir" "$bindings_file"
+load_from_backup() {
+  local -r keybinds_db="$1"
+  printf "Loading saved keybindings from %s/%s.\n" "${CONFIG_DIR##*/}" "$KEYBINDS"
+  dconf load "$keybinds_db" < "$CONFIG_DIR/$KEYBINDS"
+  printf "Cinnamon Keybindings loaded from %s/%s\n" "${CONFIG_DIR##*/}" "$KEYBINDS"
+  return 0
 }
 
 copy_from_repo() {
   local -r gh_url="https://raw.githubusercontent.com/RickRomig/configs/refs/heads/main/mint"
-  local dl_dir=~/Downloads/configs/mint
-  [[ -d ~/gitea/configs/mint ]] && dl_dir=~/gitea/configs/mint
+  local repository=~/Downloads/configs/mint
+  [[ -d ~/gitea/configs/mint ]] && repository=~/gitea/configs/mint
   printf "Copying Cinnamon keybindings from repository...\n"
-  if [[ -d $dl_dir ]]; then
-    cp -v "$dl_dir/$bindings_file" "$config_dir/"
+  if [[ -d $repository ]]; then
+    cp -v "$repository/$KEYBINDS" "$CONFIG_DIR/"
   else
-    curl -so "$config_dir/$bindings_file" "$gh_url/$bindings_file"
+    curl -so "$CONFIG_DIR/$KEYBINDS" "$gh_url/$KEYBINDS"
   fi
   printf "Cinnamon keybindings copied from respository.\n"
+  return 0
 }
 
 main() {
-  if is_cinnamon; then
-    local noOpt optstr opt OPTARG OPTIND
-    noOpt=1
-    optstr=":cdhl"
-    while getopts "$optstr" opt; do
-      case "$opt" in
-        c )
-          copy_from_repo
-          load_from_config
-          ;;
-        d )
-          dump_to_config
-          ;;
-        h )
-          help 0
-          ;;
-        l )
-          if [[ -f "$config_dir/$bindings_file" ]]; then
-            load_from_config
-          else
-            printf "Cinnamon Keybindings backup does not exist.\n" >&2
-            printf "%s -c to download keybindings from repository or\n" "$script"
-            printf "%s -d to dump current keybindings to %s/%s.\n" "$script" "${config_dir##*/}" "$bindings_file"
-          fi
-          ;;
-        ? )
-          printf "%s Invalid option -%s\n" "$RED_ERROR" "$OPTARG" >&2
-          help "$E_INVALID_ARG"
-      esac
-      noOpt=0
-    done
-    [[ $noOpt = 1 ]] && { printf "%s No argument passed.\n" "$RED_ERROR" >&2; help "$E_MISSING_ARG"; }
-    shift "$(( OPTIND - 1 ))"
-  else
-    printf "The desktop environment is not Cinnamon.\n" >&2
+  local -r script="${0##*/}"
+  local -r version="5.0.26217"
+  if ! is_cinnamon; then
+    printf "Cinnnamon is not the current desktop environment.\n"
+    over_line "$script $version"
+    exit "$E_UNSUPPORTED"
   fi
+  local -r keybinds_db=/org/cinnamon/desktop/keybindings/   # stored in the dconf database
+  local opt OPTARG OPTIND
+  local -i noOpt=1
+  local -r optstr=":cdhl"
+  while getopts "$optstr" opt; do
+    case "$opt" in
+      c )
+        copy_from_repo
+        load_from_backup "$keybinds_db"
+      ;;
+      d )
+        dump_to_backup "$keybinds_db"
+      ;;
+      h )
+        help "$script" "$version" 0
+      ;;
+      l )
+        if [[ -f "$CONFIG_DIR/$KEYBINDS" ]]; then
+          load_from_backup "$keybinds_db"
+        else
+          printf "Cinnamon Keybindings backup does not exist.\n" >&2
+          help "$script" "$version" "$E_FILENOTFOUND"
+        fi
+      ;;
+      ? )
+        printf "%s Invalid option -%s\n" "$RED_ERROR" "$OPTARG" >&2
+        help "$script" "$version" "$E_INVALID_ARG"
+    esac
+    noOpt=0
+  done
+  [[ $noOpt = 1 ]] && { printf "%s No argument passed.\n" "$RED_ERROR" >&2; help "$script" "$version" "$E_MISSING_ARG"; }
   over_line "$script $version"
   exit
 }
-
-## Execution ##
 
 main "$@"
