clone-repo 0.2.7: Expanded select loop case statements.

diff --git a/clone-repo b/clone-repo
--- a/clone-repo
+++ b/clone-repo
@@ -17,8 +17,8 @@
 ## Global Variables ##
 
 _script=$(basename "$0"); readonly _script
-readonly _version="0.2.6"
-readonly _updated="12 Apr 2023"
+readonly _version="0.2.7"
+readonly _updated="16 May 2023"
 readonly repos=( scripts configs i3debian openboxdebian fnloc fnloc-win )
 
 ## Functions ##
@@ -51,21 +51,35 @@ PS3="Choose a repository to clone: "
 select opt in "${options[@]}"; do
   case "$REPLY" in
     1 )
-      clone_repo "${repos[0]}"; break ;;
+      clone_repo "${repos[0]}"
+      break
+    ;;
     2 )
-      clone_repo "${repos[1]}"; break ;;
+      clone_repo "${repos[1]}"
+      break
+    ;;
     3 )
-      clone_repo "${repos[2]}"; break ;;
+      clone_repo "${repos[2]}"
+      break
+    ;;
     4 )
-      clone_repo "${repos[3]}"; break ;;
+      clone_repo "${repos[3]}"
+      break
+    ;;
     5 )
-      clone_repo "${repos[4]}"; break ;;
+      clone_repo "${repos[4]}"
+      break
+    ;;
     6 )
-      clone_repo "${repos[5]}"; break ;;
+      clone_repo "${repos[5]}"
+      break
+    ;;
     7 )
-      printf "Exiting. No repositories cloned.\n"; break ;;
+      printf "Exiting. No repositories cloned.\n"
+      break
+    ;;
     * )
-      printf "\e[91mERROR:\e[0m Invalid choice. Choose 1-7.\n" >&2 ;;
+      printf "\e[91mERROR:\e[0m Invalid choice. Choose 1-7.\n" >&2
   esac
 done
 exit
