clone-repo 0.2.4 - removed rederror variable because functionlib is not sourced.

diff --git a/clone-repo b/clone-repo
--- a/clone-repo
+++ b/clone-repo
@@ -20,7 +20,6 @@ _script=$(basename "$0"); readonly _script
 readonly _version="0.2.4"
 readonly _updated="20 Feb 2023"
 readonly repos=( scripts configs i3debian openboxdebian fnloc fnloc-win )
-readonly rederror="${lightred}ERROR:${normal}"
 
 ## Functions ##
 
@@ -64,7 +63,7 @@ select opt in "${options[@]}"; do
     7 )
       printf "Exiting. No repositories cloned.\n"; break ;;
     * )
-      printf "%s Invalid choice. Choose 1-7.\n" "$rederror" >&2 ;;
+      printf "\e[91mERROR:\e[0m Invalid choice. Choose 1-7.\n" >&2 ;;
   esac
 done
 exit
