clone-repo - clone_repo(): corrected spelling error.

diff --git a/clone-repo b/clone-repo
--- a/clone-repo
+++ b/clone-repo
@@ -7,7 +7,7 @@
 # Author       : Copyright (C) 2022, Richard B. Romig, LudditeGeek@Mosfanet
 # Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
 # Created      : 19 Oct 2022
-# Updated      : 10 Nov 2024
+# Updated      : 17 Jan 2025
 # Comments     :
 # TODO (Rick)  :
 # License      : GNU General Public License, version 2.0
@@ -46,7 +46,7 @@ clone_repo() {
     printf "%s exists.\n" "$dl_dir/$git_repo"
     if [[ -n $(ls -A "$dl_dir/$git_repo") ]]; then
       printf "%s is not empty.\n" "$dl_dir/$git_repo"
-      pushd "$dl_dir/$git_repo" || die "pushd failes"
+      pushd "$dl_dir/$git_repo" || die "pushd failed"
       git pull
       popd || die "popd failed"
     else
@@ -60,7 +60,7 @@ clone_repo() {
 main() {
   local index _repo repos script version
   script=$(basename "$0")
-  version="3.5.24345"
+  version="3.5.25017"
 
   exist_git
   printf "Clone a repository from the local Gitea server.\n\n"
