clone-repo: script & version are local variables, EC now local exit_code; pushd/popd failure returns exit codes

diff --git a/clone-repo b/clone-repo
--- a/clone-repo
+++ b/clone-repo
@@ -1,5 +1,5 @@
 #!/usr/bin/env bash
-##########################################################################
+###############################################################################
 # Script Name  : clone-repo
 # Description  : Clone a git repository from local Gitea server or GitHub
 # Dependencies : git
@@ -7,12 +7,12 @@
 # Author       : Copyright (C) 2022, Richard B. Romig, LudditeGeek@Mosfanet
 # Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
 # Created      : 19 Oct 2022
-# Updated      : 21 May 2026
+# Updated      : 02 Jul 2026
 # Comments     : clone_repo() is contained in functionlib
 # TODO (Rick)  :
 # License      : GNU General Public License, version 2.0
 # License URL  : https://github.com/RickRomig/scripts/blob/main/LICENSE
-##########################################################################
+###############################################################################
 # This program is free software; you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
 # the Free Software Foundation; either version 2 of the License, or
@@ -22,23 +22,19 @@
 # but WITHOUT ANY WARRANTY; without even the implied warranty of
 # MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 # GNU General Public License for more details.
-##########################################################################
+###############################################################################
 
 ## Source function library ##
 # shellcheck source=/home/rick/bin/functionlib
 source ~/bin/functionlib || { printf "\e[91mERROR:\e[0m Unable to source functionlib\n"; exit 1; }
 
-## Global Variables ##
-
-readonly script="${0##*/}"
-readonly version="5.0.26141"
-EC=0
-
 ## Functions ##
 
 help() {
-	local errcode="${1:-1}"
-	local -r updated="21 May 2026"
+  local -r script="$1"
+  local -r version="$2"
+	local -r errcode="${3:-1}"
+	local -r updated="02 Jul 2026"
 	cat << _HELP_
 ${orange}$script${normal} $version, Upated: $updated
 Clone a git repository from GitHub or the local Gitea server
@@ -62,12 +58,13 @@ check_repo() {
   local -r dl_dir=~/Downloads
   if [[ $(find "$dl_dir/$git_repo" -maxdepth 1 -type f 2>/dev/null) ]]; then
     printf "%s is not empty. Updating the repository clone...\n" "$dl_dir/$git_repo"
-    pushd "$dl_dir/$git_repo" || { EC="$E_POPD_PUSHD"; return; }
+    pushd "$dl_dir/$git_repo" || return "$E_POPD_PUSHD"
     git checkout .
     git pull
-    popd || { EC="$E_POPD_PUSHD"; return; }
+    popd || return "$E_POPD_PUSHD"
   else
     clone_repo "$git_repo" "$dl_dir/"
+    return 0
   fi
 }
 
@@ -82,31 +79,36 @@ clone_repo() {
       url="$GITEA_URL"
   esac
   git clone "$url/${git_repo}.git" "$dl_dir/"
+  return 0
 }
 
 main() {
-  local noOpt opt optstr OPTARG OPTIND
-  noOpt=1
-  optstr=":cfghilsw"
+  local -r script="${0##*/}"
+  local -r version="5.1.26183"
+  local exit_code=0
+  local opt OPTARG OPTIND
+  local -i noOpt=1
+  local -r optstr=":cfghilsw"
   check_package git
   while getopts "$optstr" opt; do
     case "$opt" in
       c ) check_repo "configs" ;;
       f ) check_repo "fnloc" ;;
       g ) check_repo "gitea-server" ;;
-      h ) help 0 ;;
+      h ) help "$script" "$version" 0 ;;
       i ) check_repo "i3wm-debian" ;;
       p ) check_repo "homepage" ;;
       s ) check_repo "scripts" ;;
       w ) check_repo "fnloc-win" ;;
-			? ) printf "%s Invalid option -%s\n" "$RED_ERROR" "$OPTARG" >&2; help "$E_INVALID_ARG"
+			? ) printf "%s Invalid option -%s\n" "$RED_ERROR" "$OPTARG" >&2; help "$script" "$version" "$E_INVALID_ARG"
     esac
+    exit_code="$?"
 		noOpt=0
   done
-	[[ "$noOpt" = 1 ]] && { printf "%s No argument passed.\n" "$RED_ERROR" >&2; help "$E_MISSING_ARG"; }
+	[[ "$noOpt" = 1 ]] && { printf "%s No argument passed.\n" "$RED_ERROR" >&2; help "$script" "$version" "$E_MISSING_ARG"; }
 	shift "$(( OPTIND - 1 ))"
 	over_line "$script $version"
-	exit "$EC"
+	exit "$exit_code"
 }
 
 ## Execution ##
