clone-repo: moved clone_repo() from functionlib to script

diff --git a/clone-repo b/clone-repo
--- a/clone-repo
+++ b/clone-repo
@@ -31,14 +31,14 @@ source ~/bin/functionlib || { printf "\e[91mERROR:\e[0m Unable to source functio
 ## Global Variables ##
 
 readonly script="${0##*/}"
-readonly version="4.4.26141"
+readonly version="5.0.26141"
 EC=0
 
 ## Functions ##
 
 help() {
 	local errcode="${1:-1}"
-	local -r updated="19 Apr 2026"
+	local -r updated="21 May 2026"
 	cat << _HELP_
 ${orange}$script${normal} $version, Upated: $updated
 Clone a git repository from GitHub or the local Gitea server
@@ -71,6 +71,19 @@ check_repo() {
   fi
 }
 
+clone_repo() {
+  local git_repo="$1"
+  local dl_dir="$2"
+  local url
+  case "$git_repo" in
+    configs | scripts | i3wm-debian )
+      url="$GITHUB_URL" ;;
+    * )
+      url="$GITEA_URL"
+  esac
+  git clone "$url/${git_repo}.git" "$dl_dir/"
+}
+
 main() {
   local noOpt opt optstr OPTARG OPTIND
   noOpt=1
@@ -78,25 +91,15 @@ main() {
   check_package git
   while getopts "$optstr" opt; do
     case "$opt" in
-      c )
-        check_repo "configs" ;;
-      f )
-        check_repo "fnloc" ;;
-      g )
-        check_repo "gitea-server" ;;
-      h )
-        help 0 ;;
-      i )
-        check_repo "i3wm-debian" ;;
-      p )
-        check_repo "homepage" ;;
-      s )
-        check_repo "scripts" ;;
-      w )
-        check_repo "fnloc-win" ;;
-			? )
-				printf "%s Invalid option -%s\n" "$RED_ERROR" "$OPTARG" >&2
-				help "$E_INVALID_ARG"
+      c ) check_repo "configs" ;;
+      f ) check_repo "fnloc" ;;
+      g ) check_repo "gitea-server" ;;
+      h ) help 0 ;;
+      i ) check_repo "i3wm-debian" ;;
+      p ) check_repo "homepage" ;;
+      s ) check_repo "scripts" ;;
+      w ) check_repo "fnloc-win" ;;
+			? ) printf "%s Invalid option -%s\n" "$RED_ERROR" "$OPTARG" >&2; help "$E_INVALID_ARG"
     esac
 		noOpt=0
   done
