clone-repo 0.2.4 - added rederror variable.

diff --git a/clone-repo b/clone-repo
--- a/clone-repo
+++ b/clone-repo
@@ -64,7 +64,7 @@ select opt in "${options[@]}"; do
     7 )
       printf "Exiting. No repositories cloned.\n"; break ;;
     * )
-      printf "%s Invalid choice. Choose 1-7.\n" "rederror" >&2 ;;
+      printf "%s Invalid choice. Choose 1-7.\n" "$rederror" >&2 ;;
   esac
 done
 exit
