config-restore: updated sourcing of functionlib; updated directory variables

diff --git a/config-restore b/config-restore
--- a/config-restore
+++ b/config-restore
@@ -7,7 +7,7 @@
 # Author       : Copyright (C) 2019,Richard B. Romig, MosfaNet
 # Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
 # Created      : 14 Apr 2019
-# Updated      : 22 Oct 2025
+# Updated      : 04 May 2026
 # Comments     :
 # TODO (rick)  :
 # License      : GNU General Public License, version 2.0
@@ -24,27 +24,20 @@
 # GNU General Public License for more details.
 ###############################################################################
 
-## Shellcheck Directives ##
-# shellcheck source=/home/rick/bin/functionlib
-
 ## Load function library ##
+# shellcheck source=/home/rick/bin/functionlib
+source functionlib || { printf "\e[91mERROR:\e[0m Unable to source functionlib\n"; exit 1; }
 
-if [[ -x "$HOME/bin/functionlib" ]]; then
-  source "$HOME/bin/functionlib"
-else
-  printf "\e[91mERROR:\e[0m functionlib not found!\n" >&2
-  exit 1
-fi
 
 ## Global Variables ##
 
 readonly script="${0##*/}"
-readonly version="6.1.25295"
+readonly version="6.2.26124"
 readonly lhost="${HOSTNAME:-$(hostname)}"
-readonly bu_dir="$HOME/.config/backup"
-readonly cfg_dir="$HOME/.config"
+readonly bu_dir=~/.config/backup
+readonly cfg_dir=~/.config
 PS3="Select option: "
-count=0
+COUNT=0
 
 ## Functions ##
 
@@ -52,8 +45,8 @@ res_home_cfg() {
   local file="$1"
   printf "\n%s" "$file"
   if [[ -f "$bu_dir/$file" ]]; then
-    cp -p "$bu_dir/$file" "$HOME/"
-    (( count++ ))
+    cp -p "$bu_dir/$file" ~/
+    (( COUNT++ ))
     printf " restored from the backup directory.\n"
   else
     printf " not found in the backup directory.\n"
@@ -68,7 +61,7 @@ res_config_cfg() {
   if [[ -f "$bu_dir/$folder/$file" ]]; then
     [[ -d "$cfg_dir/$folder" ]] || mkdir -p "$cfg_dir/$folder"
     cp -p "$bu_dir/$folder/$file" "$cfg_dir/$folder/"
-    (( count++ ))
+    (( COUNT++ ))
     printf " restored from the backup directory.\n"
   else
     printf " not found in the backup directory.\n"
@@ -83,7 +76,7 @@ res_misc_cfg() {
   if [[ -f "$bu_dir/$folder/$file" ]]; then
     [[ -d "$HOME/$folder/" ]] || mkdir -p "$HOME/$folder/"
     cp -p "$bu_dir/$folder/$file" "$HOME/$folder/"
-    (( count++ ))
+    (( COUNT++ ))
     printf " restored from the backup directory.\n"
  else
     printf " not found in the backup directory.\n"
@@ -97,7 +90,7 @@ res_cinnamon_keybindings() {
     if [[ -f "$bu_dir/$cinn_kb" ]]; then
       dconf load /org/cinnamon/desktop/keybindings/ < "$bu_dir/$cinn_kb"
       dconf dump /org/cinnamon/desktop/keybindings/ > "/$HOME/.config/$cinn_kb"
-      (( count++ ))
+      (( COUNT++ ))
       printf "\nCinnamon Keybindings restored.\n"
     else
       printf "\nCinnamon Keybindings not found in the backup directdory.\n"
@@ -133,7 +126,7 @@ main_menu() {
 		esac
 	done
 	printf "\nExiting the script...\n"
-	if (( count == 0 )); then
+	if (( COUNT == 0 )); then
 		leave "No configuration files restored."
 	else
 		leave "Configurations restored from backup."
@@ -381,7 +374,7 @@ misc_cfgs() {
           if [[ -f "$bu_dir/10-monitor.conf" ]]; then
             sudo_login 2
             sudo cp pv "$bu_dir/10-monitor.conf" /etc/X11/xorg.conf.d/
-            (( count++ ))
+            (( COUNT++ ))
           else
             printf "10-monitor.conf not found.\n"
           fi
