config-restore: updated indentation

diff --git a/config-restore b/config-restore
--- a/config-restore
+++ b/config-restore
@@ -7,8 +7,8 @@
 # Author       : Copyright (C) 2019,Richard B. Romig, MosfaNet
 # Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
 # Created      : 14 Apr 2019
-# Updated      : 06 Aug 2026
-# Version      : 6.3.26218
+# Updated      : 09 Sep 2026
+# Version      : 6.4.26252
 # Comments     :
 # TODO (rick)  :
 # License      : GNU General Public License, version 2.0
@@ -33,79 +33,79 @@ PS3="Select option: "
 COUNT=0
 
 restore_home_cfg() {
-  local -r file="$1"
-  printf "\n%s" "$file"
-  if [[ -f "$BU_DIR/$file" ]]; then
-    cp -p "$BU_DIR/$file" ~/
-    (( COUNT++ ))
-    printf " restored from the backup directory.\n"
-  else
-    printf " not found in the backup directory.\n"
-  fi
-  anykey
-  return 0
+	local -r file="$1"
+	printf "\n%s" "$file"
+	if [[ -f "$BU_DIR/$file" ]]; then
+		cp -p "$BU_DIR/$file" ~/
+		(( COUNT++ ))
+		printf " restored from the backup directory.\n"
+	else
+		printf " not found in the backup directory.\n"
+	fi
+	anykey
+	return 0
 }
 
 restore_config_cfg() {
-  local -r folder="$1"
+	local -r folder="$1"
 	local -r file="$2"
-  printf "\n%s" "$file"
-  if [[ -f "$BU_DIR/$folder/$file" ]]; then
-    [[ -d "$CFG_DIR/$folder" ]] || mkdir -p "$CFG_DIR/$folder"
-    cp -p "$BU_DIR/$folder/$file" "$CFG_DIR/$folder/"
-    (( COUNT++ ))
-    printf " restored from the backup directory.\n"
-  else
-    printf " not found in the backup directory.\n"
-  fi
-  anykey
-  return 0
+	printf "\n%s" "$file"
+	if [[ -f "$BU_DIR/$folder/$file" ]]; then
+		[[ -d "$CFG_DIR/$folder" ]] || mkdir -p "$CFG_DIR/$folder"
+		cp -p "$BU_DIR/$folder/$file" "$CFG_DIR/$folder/"
+		(( COUNT++ ))
+		printf " restored from the backup directory.\n"
+	else
+		printf " not found in the backup directory.\n"
+	fi
+	anykey
+	return 0
 }
 
 restore_misc_cfg() {
-  local -r folder="$1"
+	local -r folder="$1"
 	local -r file="$2"
-  printf "\n %s/%s" "$folder" "$file"
-  if [[ -f "$BU_DIR/$folder/$file" ]]; then
-    [[ -d "$HOME/$folder/" ]] || mkdir -p "$HOME/$folder/"
-    cp -p "$BU_DIR/$folder/$file" "$HOME/$folder/"
-    (( COUNT++ ))
-    printf " restored from the backup directory.\n"
- else
-    printf " not found in the backup directory.\n"
-  fi
-  anykey
-  return 0
+	printf "\n %s/%s" "$folder" "$file"
+	if [[ -f "$BU_DIR/$folder/$file" ]]; then
+		[[ -d "$HOME/$folder/" ]] || mkdir -p "$HOME/$folder/"
+		cp -p "$BU_DIR/$folder/$file" "$HOME/$folder/"
+		(( COUNT++ ))
+		printf " restored from the backup directory.\n"
+	else
+		printf " not found in the backup directory.\n"
+	fi
+	anykey
+	return 0
 }
 
 restore_cinnamon_keybindings() {
-  if is_cinnamon; then
-    local -r cinn_keys_db=/org/cinnamon/desktop/keybindings/
-    local cinn_kb=keybindings-backup.dconf
-    if [[ -f "$BU_DIR/$cinn_kb" ]]; then
-      dconf load "$cinn_keys_db" < "$BU_DIR/$cinn_kb"
-      dconf dump "$cinn_keys_db" > "/$HOME/.config/$cinn_kb"
-      (( COUNT++ ))
-      printf "\nCinnamon Keybindings restored.\n"
-    else
-      printf "\nCinnamon Keybindings not found in the backup directdory.\n"
-    fi
-  else
-    printf "\nThe desktop environment is not Cinnamon." >&2
-  fi
-  anykey
-  return 0
+	if ! is_cinnamon; then
+		printf "\nThe desktop environment is not Cinnamon." >&2
+		return "$E_UNSUPPORTED"
+	fi
+	local -r cinn_keys_db=/org/cinnamon/desktop/keybindings/
+	local -r cinn_kb=keybindings-backup.dconf
+	if [[ -f "$BU_DIR/$cinn_kb" ]]; then
+		dconf load "$cinn_keys_db" < "$BU_DIR/$cinn_kb"
+		dconf dump "$cinn_keys_db" > "/$HOME/.config/$cinn_kb"
+		(( COUNT++ ))
+		printf "\nCinnamon Keybindings restored.\n"
+	else
+		printf "\nCinnamon Keybindings not found in the backup directdory.\n"
+	fi
+	anykey
+	return 0
 }
 
 main_menu() {
-  local -r script="${0##*/}"
-  local -r version="6.3.26218"
+	local -r script="${0##*/}"
+	local -r version="6.4.26252"
 	local _opt options
-  options=("System Configs" "Editor Configs" "i3 Configs" "Misc Configs" "Quit")
+	options=("System Configs" "Editor Configs" "i3 Configs" "Misc Configs" "Quit")
 	clear
 	COLUMNS=20
-  printf "%s %s\n" "$script" "$version"
-  printf "Restore configuration files from local backup.\n"
+	printf "%s %s\n" "$script" "$version"
+	printf "Restore configuration files from local backup.\n"
 	printf "\nConfiguration Classes\n"
 	select _opt in "${options[@]}"; do
 		case "$REPLY" in
@@ -127,70 +127,69 @@ main_menu() {
 
 # System configuration files
 system_configs() {
-  local _opt options
-  local -r lhost="${HOSTNAME:-$(hostname)}"
+	local _opt options
+	local -r lhost="${HOSTNAME:-$(hostname)}"
 	while true; do
-		options=(".bashrc" ".bash_aliases" ".bash_logout" ".bash_profile" ".profile" ".face" \
-    "neofetch" "fastfetch" "Cinnamon keybindings" ".conkyrc" ".xinitrc" "System Info" "Main Menu")
+		options=(".bashrc" ".bash_aliases" ".bash_logout" ".bash_profile" ".profile" ".face" "neofetch" "fastfetch" "Cinnamon keybindings" ".conkyrc" ".xinitrc" "System Info" "Main Menu")
 		clear
 		COLUMNS=40
 		printf "\nSystem Configurations\n"
 		select _opt in "${options[@]}"; do
 			case "$REPLY" in
-        1 )
-          restore_home_cfg ".bashrc"
-          break ;;
+				1 )
+					restore_home_cfg ".bashrc"
+					break ;;
 				2 )
-          restore_home_cfg ".bash_aliases"
-          break ;;
-        3 )
-          restore_home_cfg ".bash_logout"
-          break ;;
+					restore_home_cfg ".bash_aliases"
+					break ;;
+				3 )
+					restore_home_cfg ".bash_logout"
+					break ;;
 				4 )
-          restore_home_cfg ".bash_profile"
-          break ;;
+					restore_home_cfg ".bash_profile"
+					break ;;
 				5 )
-          restore_home_cfg ".profile"
-          break ;;
+					restore_home_cfg ".profile"
+					break ;;
 				6 )
-          restore_home_cfg ".face"
-          break ;;
+					restore_home_cfg ".face"
+					break ;;
 				7 )
-          if [[ -f "$BU_DIR/neofetch/config" ]]; then
-            restore_config_cfg "neofetch" "config"
-          elif [[ -f "$BU_DIR/neofetch/config.conf" ]]; then
-            restore_config_cfg "neofetch" "config.conf"
-          else
-            printf "No neofetch configuration file found.\n"
-          fi
-          break ;;
-        8 )
-          restore_config_cfg "fastfetch" "config.jsonc"
-          break ;;
+					if [[ -f "$BU_DIR/neofetch/config" ]]; then
+						restore_config_cfg "neofetch" "config"
+					elif [[ -f "$BU_DIR/neofetch/config.conf" ]]; then
+						restore_config_cfg "neofetch" "config.conf"
+					else
+						printf "No neofetch configuration file found.\n"
+					fi
+					break ;;
+				8 )
+					restore_config_cfg "fastfetch" "config.jsonc"
+					break ;;
 				9 )
-          restore_cinnamon_keybindings
-          break ;;
+					restore_cinnamon_keybindings
+					break ;;
 				10 )
-          if [[ -f "$BU_DIR/.conkyrc" ]]; then
-            restore_home_cfg ".conkyrc"
-          elif [[ -f "$BU_DIR/conky/conky.conf" ]]; then
-            restore_config_cfg "conky" "conky.conf"
-          else
-            printf "No conky configuration file found.\n"
-          fi
-          break ;;
-        11 )
-          restore_home_cfg ".xinitrc" ;;
+					if [[ -f "$BU_DIR/.conkyrc" ]]; then
+						restore_home_cfg ".conkyrc"
+					elif [[ -f "$BU_DIR/conky/conky.conf" ]]; then
+						restore_config_cfg "conky" "conky.conf"
+					else
+						printf "No conky configuration file found.\n"
+					fi
+					break ;;
+				11 )
+					restore_home_cfg ".xinitrc" ;;
 				12 )
-          restore_home_cfg "$lhost.info"
-          break ;;
+					restore_home_cfg "$lhost.info"
+					break ;;
 				13 )
-          break ;;
+					break ;;
 				* )
-          echo "${lightred}Invalid choice${normal}" >&2
+					echo "${lightred}Invalid choice${normal}" >&2
 			esac
 		done
-    main_menu
+		main_menu
 	done
 }
 
@@ -205,125 +204,124 @@ editor_configs() {
 		select _opt in "${options[@]}"; do
 			case "$REPLY" in
 				1 )
-          restore_misc_cfg ".bluefish" "rcfile-2.0"
-          break ;;
+					restore_misc_cfg ".bluefish" "rcfile-2.0"
+					break ;;
 				2 )
-          restore_geany;
-          restore_config_cfg "geany" "geany.conf"
-          restore_config_cfg "geany" "keybindings.conf"
-          break ;;
-        3 )
-          restore_marktext;
-          restore_config_cfg "marktext" "preferences.json"
-          break ;;
+					restore_geany;
+					restore_config_cfg "geany" "geany.conf"
+					estore_config_cfg "geany" "keybindings.conf"
+					break ;;
+				3 )
+					restore_marktext;
+					restore_config_cfg "marktext" "preferences.json"
+					break ;;
 				4 )
-          restore_config_cfg "micro" "settings.json"
-          restore_config_cfg "micro" "bindings.json"
-          break ;;
+					restore_config_cfg "micro" "settings.json"
+					restore_config_cfg "micro" "bindings.json"
+					break ;;
 				5 )
-          if [[ -f "$BU_DIR/nano/nanorc" ]]; then
-            restore_config_cfg "nano" "nanorc"
-          elif [[ -f "$BU_DIR/.nanorc" ]]; then
-            restore_home_cfg ".nanorc"
-          else
-            printf "No nano configuration file found.\n"
-          fi
-          break ;;
+					if [[ -f "$BU_DIR/nano/nanorc" ]]; then
+						restore_config_cfg "nano" "nanorc"
+					elif [[ -f "$BU_DIR/.nanorc" ]]; then
+						restore_home_cfg ".nanorc"
+					else
+						printf "No nano configuration file found.\n"
+					fi
+					break ;;
 				6 )
-          restore_config_cfg "VSCodium/User" "settings.json"
-          break ;;
-        7 )
-          break ;;
+					restore_config_cfg "VSCodium/User" "settings.json"
+					break ;;
+				7 )
+					break ;;
 				* )
-          echo "${lightred}Invalid choice${normal}" >&2
+					echo "${lightred}Invalid choice${normal}" >&2
 			esac
 		done
-    main_menu
+		main_menu
 	done
 }
 
 # i3 configuration files
 i3_configs() {
-  local _opt options
+	local _opt options
 	while true; do
-		local options=("i3 config" "sxhkdrc" "bindings.list" "i3status.conf" "polybar" "bar.conf"  "rules.conf" \
-    "workspaces.conf" "autostart.sh" "backgrounds.sh" "logout" "rofi config" "rofi themes" "dunstrc" "Main Menu")
+		local options=("i3 config" "sxhkdrc" "bindings.list" "i3status.conf" "polybar" "bar.conf" "rules.conf" "workspaces.conf" "autostart.sh" "backgrounds.sh" "logout" "rofi config" "rofi themes" "dunstrc" "Main Menu")
 		clear
 		COLUMNS=40
 		printf "\ni3 Configurations\n"
 		select _opt in "${options[@]}"; do
 			case "$REPLY" in
 				1 )
-          restore_config_cfg "i3" "config"
-          break ;;
-        2 )
-          if [[ -f "$BU_DIR/i3/sxhkdrc" ]]; then
-            restore_config_cfg "i3" "sxhkdrc"
-          elif [[ -f "$BU_DIR/i3/sxhkd/sxhkdrc" ]]; then
-            restore_config_cfg "i3/sxhkd" "sxhkdrc"
-          else
-            printf "No sxhkdrc file found.\n"
-          fi
-          break ;;
-        3 )
-          restore_config_cfg "i3" "bindings.list"
-          break ;;
+					restore_config_cfg "i3" "config"
+					break ;;
+				2 )
+					if [[ -f "$BU_DIR/i3/sxhkdrc" ]]; then
+						restore_config_cfg "i3" "sxhkdrc"
+					elif [[ -f "$BU_DIR/i3/sxhkd/sxhkdrc" ]]; then
+						restore_config_cfg "i3/sxhkd" "sxhkdrc"
+					else
+						printf "No sxhkdrc file found.\n"
+					fi
+					break ;;
+				3 )
+					restore_config_cfg "i3" "bindings.list"
+					break ;;
 				4 )
-          if [[ -f "$BU_DIR/polybar/config" ]]; then
-            restore_config_cfg "polybar" "config"
-          elif [[ -f "$BU_DIR/polybar/config.ini" ]]; then
-            restore_config_cfg "polybar" "config.ini"
-          elif [[ -f "$BU_DIR/polybar/i3bar.ini" ]]; then
-            restore_config_cfg "polybar" "i3bar.ini"
-          else
-            printf "No polybar configuration file found.\n"
-          fi
-          break ;;
-        5 )
-          restore_config_cfg "i3" "i3status.conf"
-          break ;;
-        6 )
-          restore_config_cfg "i3" "bar.conf"
-          break ;;
-        7 )
-          restore_config_cfg "i3" "rules.conf"
-          break ;;
-        8 )
-          restore_config_cfg "i3" "workspaces.conf"
-          break ;;
-        9 )
-          restore_config_cfg "i3" "autostart.sh"
-          break ;;
-        10 )
-          restore_config_cfg "i3" "backgrounds.sh"
-          break ;;
-        11 )
-          restore_config_cfg "i3" "logout"
-          break ;;
+					if [[ -f "$BU_DIR/polybar/config" ]]; then
+						restore_config_cfg "polybar" "config"
+					elif [[ -f "$BU_DIR/polybar/config.ini" ]]; then
+						restore_config_cfg "polybar" "config.ini"
+					elif [[ -f "$BU_DIR/polybar/i3bar.ini" ]]; then
+						restore_config_cfg "polybar" "i3bar.ini"
+					else
+						printf "No polybar configuration file found.\n"
+					fi
+					break ;;
+				5 )
+					restore_config_cfg "i3" "i3status.conf"
+					break ;;
+				6 )
+					restore_config_cfg "i3" "bar.conf"
+					break ;;
+				7 )
+					restore_config_cfg "i3" "rules.conf"
+					break ;;
+				8 )
+					restore_config_cfg "i3" "workspaces.conf"
+					break ;;
+				9 )
+					restore_config_cfg "i3" "autostart.sh"
+					break ;;
+				10 )
+					restore_config_cfg "i3" "backgrounds.sh"
+					break ;;
+				11 )
+					restore_config_cfg "i3" "logout"
+					break ;;
 				12 )
-          restore_config_cfg "rofi" "config.rasi"
-          break ;;
+					restore_config_cfg "rofi" "config.rasi"
+					break ;;
 				13 )
-          restore_rofi_theme;
-          restore_config_cfg "rofi" "arc_dark_colors.rasi"
-          restore_config_cfg "rofi" "arc_dark_transparent_colors.rasi"
-          break ;;
-        14 )
-          restore_config_cfg "dunst" "dunstrc"
-          break ;;
+					restore_rofi_theme;
+					restore_config_cfg "rofi" "arc_dark_colors.rasi"
+					restore_config_cfg "rofi" "arc_dark_transparent_colors.rasi"
+					break ;;
+				14 )
+					restore_config_cfg "dunst" "dunstrc"
+					break ;;
 				15 )
-          break ;;
+					break ;;
 				* )
-          echo "${lightred}Invalid choice${normal}" >&2
+					echo "${lightred}Invalid choice${normal}" >&2
 			esac
 		done
-    main_menu
+		main_menu
 	done
 }
 
 # Miscellaneous configuration files
 misc_configs() {
-  local _opt options
+	local _opt options
 	while true; do
 		options=("Bat" "gitconfig" "git-credentials" "KeepassXC" "Kitty" "Monitor Config" "Terminator" "imwheelrc" "Redshift" "Main Menu")
 		clear
@@ -332,58 +330,58 @@ misc_configs() {
 		select _opt in "${options[@]}"; do
 			case "$REPLY" in
 				1 )
-          restore_config_cfg "bat" "config"
-          break ;;
+					restore_config_cfg "bat" "config"
+					break ;;
 				2 )
-          if [[ -f "$BU_DIR/.gitconfig" ]];then
-            restore_home_cfg ".gitconfig"
-          elif [[ -f "$BU_DIR/git/config" ]]; then
-            restore_config_cfg "git" "config"
-          else
-            printf "No git configuration file found.\n"
-          fi
-          break ;;
+					if [[ -f "$BU_DIR/.gitconfig" ]];then
+						restore_home_cfg ".gitconfig"
+					elif [[ -f "$BU_DIR/git/config" ]]; then
+						restore_config_cfg "git" "config"
+					else
+						printf "No git configuration file found.\n"
+					fi
+					break ;;
 				3 )
-          if [[ -f "$BU_DIR/git-credentials" ]];then
-            restore_home_cfg ".git-credentials"
-          elif [[ -f "$BU_DIR/git/credentials" ]]; then
-            restore_config_cfg "git" "credentials"
-          else
-            printf "No git credentials file found.\n"
-          fi
-          break ;;
+					if [[ -f "$BU_DIR/git-credentials" ]];then
+						restore_home_cfg ".git-credentials"
+					elif [[ -f "$BU_DIR/git/credentials" ]]; then
+						restore_config_cfg "git" "credentials"
+					else
+						printf "No git credentials file found.\n"
+					fi
+					break ;;
 				4 )
-          restore_config_cfg "keepassxc" "keepassxc.ini"
-          break ;;
+					restore_config_cfg "keepassxc" "keepassxc.ini"
+					break ;;
 				5 )
-          restore_config_cfg "kitty" "kitty.conf"
-          restore_config_cfg "kitty" "bindings.list"
-          break ;;
-        6 )
-          if [[ -f "$BU_DIR/10-monitor.conf" ]]; then
-            sudo_login 2
-            sudo cp pv "$BU_DIR/10-monitor.conf" /etc/X11/xorg.conf.d/
-            (( COUNT++ ))
-          else
-            printf "10-monitor.conf not found.\n"
-          fi
-          break ;;
+					restore_config_cfg "kitty" "kitty.conf"
+					restore_config_cfg "kitty" "bindings.list"
+					break ;;
+				6 )
+					if [[ -f "$BU_DIR/10-monitor.conf" ]]; then
+						sudo_login 2
+						sudo cp pv "$BU_DIR/10-monitor.conf" /etc/X11/xorg.conf.d/
+						(( COUNT++ ))
+					else
+						printf "10-monitor.conf not found.\n"
+					fi
+					break ;;
 				7 )
-          restore_config_cfg "terminator" "config"
-          break ;;
-        8 )
-          restore_home_cfg ".imwheelrc"
-          break ;;
-        9 )
-          restore_misc_cfg "config" "redshift.conf"
-          break ;;
-        10 )
-          break ;;
-			* )
-          echo "${lightred}Invalid choice${normal}" >&2
+					restore_config_cfg "terminator" "config"
+					break ;;
+				8 )
+					restore_home_cfg ".imwheelrc"
+					break ;;
+				9 )
+					restore_misc_cfg "config" "redshift.conf"
+					break ;;
+				10 )
+					break ;;
+				* )
+					echo "${lightred}Invalid choice${normal}" >&2
 			esac
 		done
-    main_menu
+		main_menu
 	done
 }
 
