config-restore - 0.5.1 - Rnameed res_bluefish_cfg to res_misc_cfg and changed it to restore files in directories in the root of the home folder not in .config. Removed unneed restores from misc configs.

diff --git a/config-restore b/config-restore
--- a/config-restore
+++ b/config-restore
@@ -27,7 +27,7 @@ fi
 ## Variables ##
 
 _script=$(basename "$0"); readonly _script
-readonly _version="0.5.0"
+readonly _version="0.5.1"
 readonly _updated="17 Aug 2023"
 readonly lhost="${HOSTNAME:-$(hostname)}"
 readonly bu_dir="${HOME}/.config/backup"
@@ -56,10 +56,26 @@ res_config_cfg() {
   printf "\n%s" "$file"
   if [[ -f "$bu_dir/$folder/$file" ]]; then
     printf " restored from the backup directory.\n"
+    [[ -d "$cfg_dir/$folder" ]] || mkdir -p "$cfg_dir/$folder"
     cp pv "$bu_dir/$folder/$file" "$cfg_dir/$folder/"
     (( count++ ))
   else
     printf " not found in the backup directory.\n"
+  fi
+  anykey
+}
+
+res_misc_cfg() {
+	local folder="$1"
+	local file="$2"
+  printf "\n %s/%s" "$folder" "$file"
+  if [[ -f "$bu_dir/$folder/$file" ]]; then
+   printf " restored from the backup directory.\n"
+  [[ -d "$HOME/$folder/" ]] || mkdir -p "$HOME/$folder/"
+   cp -p "$bu_dir/$folder/$file" "$HOME/$folder/"
+   (( count++ ))
+ else
+   printf " not found in the backup directory.\n"
   fi
   anykey
 }
@@ -80,30 +96,6 @@ res_cinnamon_keybindings() {
   anykey
 }
 
-res_bluefish() {
-  printf "\nBluefish rcfile"
-  if [[ -f "$bu_dir/.bluefish/rcfile-2.0" ]]; then
-   printf " restored from the backup directory.\n"
-   cp -p "$bu_dir/.bluefish/rcfile-2.0" "$HOME/.bluefish/"
-   (( count++ ))
- else
-   printf " not found in the backup directory.\n"
-  fi
-  anykey
-}
-
-res_sshpwd() {
-  printf "\nsshpwd_file"
-  if [[ -f "$bu_dir/sshpwd_file" ]]; then
-    printf " restored from the backup directory.\n"
-    cp -p "$bu_dir/sshpwd_file" "$HOME/.local/share/doc/"
-    (( count++ ))
-  else
-    printf " not found in the backup directory.\n"
-  fi
-  anykey
-}
-
 main_menu() {
 	local options=("System Configs" "Editor Configs" "i3 Configs" \
 	"BunsenLabs Configs" "Misc Configs" "Quit")
@@ -114,11 +106,26 @@ main_menu() {
 	printf "\nConfiguration Classes\n"
 	select opt in "${options[@]}"; do
 		case "$REPLY" in
-			1 )	sys_cfgs; break ;;
-			2 )	ed_cfgs; break ;;
-			3 ) i3_cfgs; break ;;
-			4 ) bl_cfgs; break ;;
-			5 ) misc_cfgs; break ;;
+			1 )
+        sys_cfgs
+        break
+      ;;
+			2 )
+        ed_cfgs
+        break
+      ;;
+			3 )
+        i3_cfgs
+        break
+      ;;
+			4 )
+        bl_cfgs
+        break
+      ;;
+			5 )
+        misc_cfgs
+        break
+      ;;
 			6 )
 				printf "\nExiting the script...\n"
 				if (( count == 0 )); then
@@ -126,8 +133,10 @@ main_menu() {
 				else
 					leave "Configurations restored from backup."
 				fi
-				break ;;
-			* ) echo "${lightred}Invalid choice${normal}" >&2
+				break
+      ;;
+			* )
+        echo "${lightred}Invalid choice${normal}" >&2
 		esac
 	done
 }
@@ -214,7 +223,7 @@ ed_cfgs() {
 		select opt in "${options[@]}"; do
 			case "$REPLY" in
 				1 )
-          res_bluefish; 
+          res_misc_cfg ".bluefish" "rcfile-2.0"
           break
         ;;
 				2 )
@@ -367,7 +376,7 @@ bl_cfgs() {
 # Miscellaneous configuration files
 misc_cfgs() {
 	while true; do
-		local options=("Bat" "gitconfig" "git-credentials" "KeepassXC" "Password Gorilla" "Kitty" "Terminator" ".pwd_file" "sshpwd" "Main Menu")
+		local options=("Bat" "gitconfig" "git-credentials" "KeepassXC" "Password Gorilla" "Kitty" "Terminator" "Main Menu")
 		clear
 		COLUMNS=60
     printf "%s %s (%s)\n" "$_script" "$_version" "$_updated"
@@ -416,14 +425,11 @@ misc_cfgs() {
           break
         ;;
         8 )
-          res_home_cfg ".pwd_file"
-        ;;
-        9 )
-          res_sshpwd
+          main_menu
           break
         ;;
-				10 ) main_menu; break ;;
-				* ) echo "${lightred}Invalid choice${normal}" >&2
+				* )
+          echo "${lightred}Invalid choice${normal}" >&2
 			esac
 		done
 	done
