create-script: import_metadata() updated local variables

diff --git a/create-script b/create-script
--- a/create-script
+++ b/create-script
@@ -7,7 +7,7 @@
 # Author       : Copyright (C) 2023, Richard Romig, Mosfanet
 # Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
 # Created      : 01 Jan 2023
-# Last updated : 01 Mar 2026
+# Last updated : 11 Jun 2026
 # Comments     : Creates the script in the current working directory.
 # TODO (rick)  :
 # License      : GNU General Public License, version 2.0
@@ -25,30 +25,21 @@
 # GNU General Public License for more details.
 ###############################################################################
 
-## Shellcheck Directives ##
+## Source function library ##
 # shellcheck source=/home/rick/bin/functionlib
-
-## Load function library ##
-
-if [[ -x "$HOME/bin/functionlib" ]]; then
-  source "$HOME/bin/functionlib"
-else
-  echo -e "\e[91mERROR:\e[0m functionlib not found!" >&2
-  exit 81
-fi
+source ~/bin/functionlib || { printf "\e[91mERROR:\e[0m Unable to source functionlib\n"; exit 1; }
 
 ## Global Variables ##
 
-script_dir=$(dirname "$(readlink -f "${0}")"); readonly script_dir
 readonly script="${0##*/}"
-readonly version="4.7.26060"
+readonly version="4.8.26162"
 verbose_mode="$FALSE"
 
 ## Functions ##
 
 help() {
 	local errcode="${1:-1}"
-	local updated="01 Mar 2026"
+	local updated="11 Jun 2026"
 	cat << _HELP_
 ${orange}$script${normal} $version ($updated)
 Creates a shell script with header comments (getopts optional)
@@ -72,16 +63,16 @@ show_message() {
 }
 
 import_metadata() {
-	local cur_yr init_ver script_name template_dir template_file today
-	script_name="$1"
-	template_file="$2"
-	template_dir="$script_dir/Templates"
+	local cur_yr init_ver today script_dir
+	local -r script_name="$1"
+	local -r template_file="$2"
+	script_dir=$(dirname "$(readlink -f "${0}")")
+	local -r template_dir="$script_dir/Templates"
 	today=$(date +"%d %b %Y")
-	cur_yr=$(echo -e "\UA9 $(date +%Y)")
+	cur_yr=$(printf "\UA9 %(%Y)T")
 	init_ver="1.0.$(date +%y%j)"
 
-	show_message "Creating BASH script: $script_name"
-	show_message "Filling in metadata from the template."
+	show_message "Entering metadata and creating the script..."
 
 	sed -e '1d' \
 		-e "s/<FILE>/$script_name/" \
@@ -108,7 +99,7 @@ main() {
 				fi
 				show_message "Script name: $script_name"
 				template_file="bash-template.txt"
-				show_message "Template: $template_file"
+				show_message "Template: ${template_file##*/}"
 			;;
 			h )
 				help 0
@@ -121,7 +112,7 @@ main() {
 				fi
 				show_message "Script name: $script_name"
 				template_file="bash-getopts.txt"
-				show_message "Template: $template_file"
+				show_message "Template: ${template_file##*/}"
 				;;
 			v )
 				verbose_mode="$TRUE"
