create-c-cpp: import_metadata() updated local variables

diff --git a/create-c-cpp b/create-c-cpp
--- a/create-c-cpp
+++ b/create-c-cpp
@@ -7,7 +7,7 @@
 # Author       : Copyright (C) 2023, Richard Romig, Mosfanet
 # Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
 # Created      : 01 Jan 2023
-# Last updated : 01 Mar 2026
+# Last updated : 11 Jun 2026
 # Comment      : C template includes GNU GPL v2 license
 # TODO (rick)  :
 # License      : GNU General Public License, version 2.0
@@ -24,29 +24,20 @@
 # GNU General Public License for more details.
 ###############################################################################
 
-## Shellcheck Directives ##
+## Source function library ##
 # shellcheck source=/home/rick/bin/functionlib
-
-## Load function library ##
-
-if [[ -x "$HOME/bin/functionlib" ]]; then
-  source "$HOME/bin/functionlib"
-else
-  echo -e "e[91mERROR:\e[0m functionlib not found!" >&2
-  exit 81
-fi
+source ~/bin/functionlib || { printf "\e[91mERROR:\e[0m Unable to source functionlib\n"; exit 1; }
 
 ## Global Variables ##
-script_dir=$(dirname "$(readlink -f "${0}")"); readonly script_dir
 readonly script="${0##*/}"
-readonly version="4.4.26060"
+readonly version="4.5.26162"
 verbose_mode="$FALSE"
 
 ## Functions ##
 
 help() {
   local errcode="${1:-2}"
-  local updated="01 Mar 2026"
+  local updated="11 Jun 2026"
 	cat << _HELP_
 ${orange}$script${normal} $version ($updated)
 Creates a C/C++ source code file with descriptive comments (GPL v2.0 license)
@@ -70,19 +61,22 @@ show_message() {
 }
 
 import_metadata() {
-	local code_file cur_yr template_dir template_file today
-	code_file="$1"
-	template_file="$2"
-	template_dir="$script_dir/Templates"
+	local cur_yr today script_dir
+	local -r script_name="$1"
+	local -r template_file="$2"
+	script_dir=$(dirname "$(readlink -f "${0}")")
+	local -r template_dir="$script_dir/Templates"
 	today=$(date +"%d %b %Y")
-	cur_yr=$(echo -e "\UA9 $(date +%Y)")
+	cur_yr=$(printf "\UA9 %(%Y)T")
 
 	show_message "Creating C/C++ source code file: $code_file"
-	show_message "Filling in metadata from the template."
+	show_message "Entering metadata..."
 	sed -e '1d' \
 		-e "s/<PROGNAME>/$code_file/" \
 		-e "s/<YEAR>/$cur_yr/" \
 		-e "s/<TODAY>/$today/"  "$template_dir/$template_file" > "$code_file"
+	show_message "Setting file permissions to 644 (rw-r--r--)."
+	chmod 755 "$script_name"
 	printf "%s has been created." "$code_file"
 }
 
