create-c-cpp: updated help() options; added check for C/C++ source file.

diff --git a/create-c-cpp b/create-c-cpp
--- a/create-c-cpp
+++ b/create-c-cpp
@@ -7,7 +7,7 @@
 # Author       : Copyright (C) 2023, Richard Romig, Mosfanet
 # Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
 # Created      : 01 Jan 2023
-# Last updated : 19 Jun 2025
+# Last updated : 25 Jun 2025
 # Comment      : C template includes GNU GPL v2 license
 # TODO (rick)  :
 # License      : GNU General Public License, version 2.0
@@ -28,28 +28,28 @@ fi
 ## Global Variables ##
 
 readonly script="${0##*/}"
-readonly version="4.1.25170"
+readonly version="4.2.25176"
 verbose_mode="$FALSE"
 
 ## Functions ##
 
 help() {
   local errcode="${1:-2}"
-  local updated="19 Jun 2025"
+  local updated="25 Jun 2025"
 	cat << _HELP_
 ${orange}$script${normal} $version ($updated)
 Creates a C/C++ source code file with descriptive comments (GPL v2.0 license)
 
-${green}Usage:${normal} $script [OPTION] [source-file]
+${green}Usage:${normal} $script [-h] [-vc source-file] [-vp source-file]
 
 ${orange}Available options:${normal}
   -c  Create a C source code file
-      $script -c <code-file>
+      $script -c <source-file>
   -h  Show this help message and exit
   -p  Create a C++ source code file
-      $script -p <code-file>
-  -v  Enable verbose mode (Must precede c or p flags)
-      $script -vc <code-file>
+      $script -p <source-file>
+  -v  Enable verbose mode (Must precede -c or -p flags)
+      $script -vc <source-file>
 _HELP_
   exit "$errcode"
 }
@@ -122,6 +122,7 @@ main() {
 	done
 	[[ "$noOpt" = 1 ]] && { printf "%s No argument passed.\n" "$RED_ERROR" >&2; help 1; }
 	shift "$(( OPTIND - 1 ))"
+	[[ "$code_file" ]] || { printf "%s No source code file provided.\n" "$RED_ERROR" >&2; help 2; }
 	import_metadata "$code_file" "$template_file"
 	edit_view_quit "$code_file"
 	over_line "$script $version"
