create-script: updated help() options; added check for script source file.

diff --git a/create-script b/create-script
--- a/create-script
+++ b/create-script
@@ -7,7 +7,7 @@
 # Author       : Copyright (C) 2023, Richard Romig, Mosfanet
 # Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
 # Created      : 01 Jan 2023
-# Last updated : 20 Jun 2025
+# Last updated : 25 Jun 2025
 # Comments     : Creates the script in the current working directory.
 # TODO (rick)  :
 # License      : GNU General Public License, version 2.0
@@ -28,19 +28,19 @@ fi
 ## Global Variables ##
 
 readonly script="${0##*/}"
-readonly version="4.1.25171"
+readonly version="4.2.25176"
 verbose_mode="$FALSE"
 
 ## Functions ##
 
 help() {
 	local errcode="${1:-2}"
-	local updated="25 Feb 2025"
+	local updated="25 Jun 2025"
 	cat << _HELP_
 ${orange}$script${normal} $version ($updated)
 Creates a shell script with header comments (getopts optional)
 
-${green}Usage:${normal} $script [OPTION] [script-name]
+${green}Usage:${normal} $script [-h] [-vb script-name] [-vg script-name]
 
 ${orange}Available options:${normal}
   -b  Create a standard BASH script
@@ -48,7 +48,7 @@ ${orange}Available options:${normal}
   -h  Show this help message and exit
   -g  Create a getopts BASH script
       $script -g <script-name>
-  -v  Enable verbose mode (Must precede b or g flags)
+  -v  Enable verbose mode (Must precede -b or -g flags)
       $script -vb <script-name>
 _HELP_
   exit "$errcode"
@@ -133,6 +133,7 @@ main() {
 	done
 	[[ "$noOpt" = 1 ]] && { printf "%s No argument passed.\n" "$RED_ERROR" >&2; help 1; }
 	shift "$(( OPTIND - 1 ))"
+	[[ "$script_name" ]] || { printf "%s No script file provided.\n" "$RED_ERROR" >&2; help 2; }
 	create_script "$script_name" "$template_file"
 	edit_view_quit "$script_name"
 	over_line "$script $version"
