create-script: help() - updated variables; main() - changed noOpt test to arithmetic expression

diff --git a/create-script b/create-script
--- a/create-script
+++ b/create-script
@@ -16,24 +16,24 @@
 ###############################################################################
 # This program is free software; you can redistribute it and/or modify it under
 # the terms of the GNU General Public License as published by the Free Software
-# Foundation; either version 2 of the License, or (at your option) any later version.
+# Foundation; either version 2 of the License, or (at your option) any later
+# version.
 #
 # This program is distributed in the hope that it will be useful, but WITHOUT
 # ANY  WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 # FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
 ###############################################################################
 
-## Source function library ##
-# shellcheck source=/home/rick/bin/functionlib
-source ~/bin/functionlib || { printf "\e[91mERROR:\e[0m Unable to source functionlib\n"; exit 1; }
+# shellcheck source=/home/rick/bin/functionlib.bash
+source ~/bin/functionlib.bash || { printf "\e[91mERROR:\e[0m Unable to source functionlib.bash\n"; exit 1; }
 
-VERBOSE_MODE="$FALSE"
+VERBOSE="$FALSE"
 
 help() {
   local -r script="$1"
   local -r version="$2"
-  local errcode="${3:-1}"
-  local updated="07 Jul 2026"
+  local -ri errcode="${3:-1}"
+  local -r updated="07 Jul 2026"
 	cat << _HELP_
 ${orange}$script${normal} $version ($updated)
 Creates a shell script with header comments (getopts optional)
@@ -53,7 +53,7 @@ _HELP_
 
 show_message() {
 	local message="$1"
-	[[ "$VERBOSE_MODE" == "$TRUE" ]] && echo "$message"
+	[[ "$VERBOSE" == "$TRUE" ]] && echo "$message"
 	return 0
 }
 
@@ -117,7 +117,7 @@ main() {
 				show_message "Template: ${template_file##*/}"
 				;;
 			v )
-				VERBOSE_MODE="$TRUE"
+				VERBOSE="$TRUE"
 				show_message "Verbose mode enabled."
 				;;
 			: )
@@ -130,7 +130,7 @@ main() {
 		esac
 		noOpt=0
 	done
-	[[ "$noOpt" = 1 ]] && { printf "%s No argument passed.\n" "$RED_ERROR" >&2; help "$script" "$version" "$E_MISSING_ARG"; }
+	(( noOpt == 1 )) && { printf "%s No argument passed.\n" "$RED_ERROR" >&2; help "$script" "$version" "$E_MISSING_ARG"; }
 	shift "$(( OPTIND - 1 ))"
 	import_metadata "$script_name" "$template_file"
 	edit_view_quit "$script_name"
