cronscripts: updated tabs, local variable declarations

diff --git a/cronscripts b/cronscripts
--- a/cronscripts
+++ b/cronscripts
@@ -7,8 +7,8 @@
 # Author       : Copyright (C) 2022, Richard B. Romig, Mosfanet
 # Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
 # Crated       : 17 Feb 2022
-# Updated      : 05 Aug 2026
-# Version      : 10.3.26217
+# Updated      : 05 Sep 2026
+# Version      : 10.4.26248
 # Comments     : Checks if the script in ~/bin/cronjobs is newer than the
 #              : script being run by anacron/cron
 # TODO (Rick)  :
@@ -41,240 +41,234 @@ help() {
 	local -r script="$1"
 	local -r version="$2"
 	local -ri errcode="${3:-1}"
-	local -r updated="05 Aug 2026"
-  cat << _HELP_
+	local -r updated="05 Sep 2026"
+	cat <<- _HELP_
 ${orange}$script${normal} $version, Updated: $updated
 Copies cronjob scripts to the appropriate directories.
 
 ${green}Usage:${normal} $script [-abdfghmrstuv]
 ${orange}Available options:${normal}
-  -a    Copy all applicable scripts.
-  -c    Copy cloned repo update script.
-  -d    Copy defrag script.
-  -f    Copy Finance backup scripts.
-  -g    Copy Git repository backup scripts.
-  -h    Show this help message and exit.
-  -m    Copy Main PC backup scripts.
-  -r    Copy Redshift notification script.
-  -s    Copy script archive script.
-  -t    Copy empty trash script.
-  -u    Copy system update script.
-  -y    Copy yt-dlp update script.
-  NOTE: Multiple arguments may be passed to the script.
+	-a    Copy all applicable scripts.
+	-c    Copy cloned repo update script.
+	-d    Copy defrag script.
+	-f    Copy Finance backup scripts.
+	-g    Copy Git repository backup scripts.
+	-h    Show this help message and exit.
+	-m    Copy Main PC backup scripts.
+	-r    Copy Redshift notification script.
+	-s    Copy script archive script.
+	-t    Copy empty trash script.
+	-u    Copy system update script.
+	-y    Copy yt-dlp update script.
+	NOTE: Multiple arguments may be passed to the script.
 _HELP_
-  exit "$errcode"
+	exit "$errcode"
 }
 
 is_older() {
-  local -r cron_script="$1"
-  local -r cron_path="$2"
-  [[ "$cron_path/$cron_script" -ot "$JOB_DIR/$cron_script" ]] && return "$TRUE" || return "$FALSE"
+	local -r cron_script="$1"
+	local -r cron_path="$2"
+	[[ "$cron_path/$cron_script" -ot "$JOB_DIR/$cron_script" ]] && return "$TRUE" || return "$FALSE"
 }
 
 no_copy() {
-  local -r message="$1"
-  printf "%s not applicable to this system and was not copied.\n" "$message"
-  return 0
+	local -r message="$1"
+	printf "%s not applicable to this system and not copied.\n" "$message"
+	return 0
 }
 
 cp_clone_update() {
-  case "$LOCALIP" in
-    10|16|22 )
-      no_copy "Cloned repository updates are" ;;
-    * )
-      is_older "clone-update.sh" "$USER_CRON_PATH" && awk '{print "==> "$NF}' < <(cp -pv "$JOB_DIR/clone-update.sh" "$USER_CRON_PATH")
-  esac
-  return 0
+	case "$LOCALIP" in
+		10|16|22 )
+			no_copy "Cloned repository updates are" ;;
+		* )
+			is_older "clone-update.sh" "$USER_CRON_PATH" && awk '{print "==> "$NF}' < <(cp -pv "$JOB_DIR/clone-update.sh" "$USER_CRON_PATH")
+	esac
+	return 0
 }
 
 cp_git_bu() {
-  case "$LOCALIP" in
-    10|16 )
-      is_older "git-dwm.sh" "$USER_CRON_PATH" && awk '{print "==> "$NF}' < <(cp -pv "$JOB_DIR/git-dwm.sh" "$USER_CRON_PATH")
-      is_older "git-bu.sh" "$USER_CRON_PATH" && awk '{print "==> "$NF}' < <(cp -pv "$JOB_DIR/git-bu.sh" "$USER_CRON_PATH")
-      ;;
-    * )
-      no_copy "Repository archives are"
-  esac
-  return 0
+	case "$LOCALIP" in
+		10|16 )
+			is_older "git-dwm.sh" "$USER_CRON_PATH" && awk '{print "==> "$NF}' < <(cp -pv "$JOB_DIR/git-dwm.sh" "$USER_CRON_PATH")
+			is_older "git-bu.sh" "$USER_CRON_PATH" && awk '{print "==> "$NF}' < <(cp -pv "$JOB_DIR/git-bu.sh" "$USER_CRON_PATH") ;;
+		* )
+			no_copy "Repository archives are"
+	esac
+	return 0
 }
 
 cp_main_bu() {
   local buScript buScripts
   buScripts=(sync-nas.sh sync6005.sh journal-bu.sh passwdsync.sh repo-backup.sh)
-  case "$LOCALIP" in
-  10 )
-      for buScript in "${buScripts[@]}"; do
-        is_older "$buScript" "$USER_CRON_PATH" && awk '{print "==> "$NF}' < <(cp -pv "$JOB_DIR/$buScript" "$USER_CRON_PATH")
-      done
-      ;;
-    * )
-      no_copy "Main system sync scripts are"
-  esac
-  return 0
+	case "$LOCALIP" in
+		10 )
+			for buScript in "${buScripts[@]}"; do
+				is_older "$buScript" "$USER_CRON_PATH" && awk '{print "==> "$NF}' < <(cp -pv "$JOB_DIR/$buScript" "$USER_CRON_PATH")
+			done ;;
+		* )
+			no_copy "Main system sync scripts are"
+	esac
+	return 0
 }
 
 cp_finance_bu() {
-  case "$LOCALIP" in
-    10 )
-      is_older "fin-bu.sh" "$USER_CRON_PATH" &&  awk '{print "==> "$NF}' < <(cp -pv "$JOB_DIR/fin-bu.sh" "$USER_CRON_PATH")
-      is_older "hb-archive.sh" "$USER_CRON_PATH" && awk '{print "==> "$NF}' < <(cp -pv "$JOB_DIR/hb-archive.sh" "$USER_CRON_PATH")
-      ;;
-    * )
-      no_copy "Finance archives are"
-  esac
-  return 0
+	case "$LOCALIP" in
+		10 )
+			is_older "fin-bu.sh" "$USER_CRON_PATH" &&  awk '{print "==> "$NF}' < <(cp -pv "$JOB_DIR/fin-bu.sh" "$USER_CRON_PATH")
+			is_older "hb-archive.sh" "$USER_CRON_PATH" && awk '{print "==> "$NF}' < <(cp -pv "$JOB_DIR/hb-archive.sh" "$USER_CRON_PATH") ;;
+		* )
+			no_copy "Finance archives are"
+	esac
+	return 0
 }
 
 cp_scriptarchive() {
-  case "$LOCALIP" in
-    17|21|22|24 )
-      no_copy "scriptarchive.sh is" ;;
-    * )
-      is_older "scriptarchive.sh" "$USER_CRON_PATH" && awk '{print "==> "$NF}' < <(cp -pv "$JOB_DIR/scriptarchive.sh" "$USER_CRON_PATH")
-  esac
-  return 0
+	case "$LOCALIP" in
+		17|21|22|24 )
+			no_copy "scriptarchive.sh is" ;;
+		* )
+			is_older "scriptarchive.sh" "$USER_CRON_PATH" && awk '{print "==> "$NF}' < <(cp -pv "$JOB_DIR/scriptarchive.sh" "$USER_CRON_PATH")
+	esac
+	return 0
 }
 
 cp_empty_trash() {
-  is_older "empty-trash.sh" "$USER_CRON_PATH" && awk '{print "==> "$NF}' < <(cp -pv "$JOB_DIR/empty-trash.sh" "$USER_CRON_PATH")
-  return 0
+	is_older "empty-trash.sh" "$USER_CRON_PATH" && awk '{print "==> "$NF}' < <(cp -pv "$JOB_DIR/empty-trash.sh" "$USER_CRON_PATH")
+	return 0
 }
 
 cp_redshift_notify() {
-  case "$LOCALIP" in
-    10|11|14|15|17|19|20|21 )
-      no_copy "redshift-notify.sh is" ;;
-    * )
-      is_older "redshift-notify.sh" "$USER_CRON_PATH" && awk '{print "==> "$NF}' < <(cp -pv "$JOB_DIR/redshift-notify.sh" "$USER_CRON_PATH")
-  esac
-  return 0
+	case "$LOCALIP" in
+		10|11|14|15|17|19|20|21 )
+			no_copy "redshift-notify.sh is" ;;
+		* )
+			is_older "redshift-notify.sh" "$USER_CRON_PATH" && awk '{print "==> "$NF}' < <(cp -pv "$JOB_DIR/redshift-notify.sh" "$USER_CRON_PATH")
+	esac
+	return 0
 }
 
 cp_zdefrag() {
-  local -r anacron_path="/etc/cron.monthly/"
-  case "$LOCALIP" in
-    10|12|13|14|15|17|19|20|21|22|23|24 )
-      if [[ ! -f "$anacron_path/z-defrag" ]]; then
-        sudo_login 1
-        awk '{print "==> "$NF} ' < <(sudo cp -v "$JOB_DIR/z-defrag" "$anacron_path")
-      elif is_older "z-defrag" "$anacron_path"; then
-        sudo_login 1
-        awk '{print "==> "$NF}' < <(sudo cp -v "$JOB_DIR/z-defrag" "$anacron_path")
-      fi
-      ;;
-    11|16 )
-      [[ -d "$SYSTEM_CRON_PATH" ]] || { sudo_login 1; sudo mkdir -p "$SYSTEM_CRON_PATH"; }
-      if [[ -f "$SYSTEM_CRON_PATH/z-defrag" ]]; then
-        sudo_login 1
-        awk '{print "==> "$NF}' < <(sudo cp -v "$JOB_DIR/z-defrag" "$SYSTEM_CRON_PATH")
-      elif is_older "z-defrag" "$SYSTEM_CRON_PATH"; then
-        sudo_login 1
-        awk '{print "==> "$NF}' < <(sudo cp -v "$JOB_DIR/z-defrag" "$SYSTEM_CRON_PATH")
-      fi
-      ;;
-    * )
-      no_copy "z-defrag is"
-  esac
-  return 0
+	local -r anacron_path="/etc/cron.monthly/"
+	case "$LOCALIP" in
+		11|16 )
+			[[ -d "$SYSTEM_CRON_PATH" ]] || { sudo_login 1; sudo mkdir -p "$SYSTEM_CRON_PATH"; }
+			if [[ -f "$SYSTEM_CRON_PATH/z-defrag" ]]; then
+				sudo_login 1
+				awk '{print "==> "$NF}' < <(sudo cp -v "$JOB_DIR/z-defrag" "$SYSTEM_CRON_PATH")
+			elif is_older "z-defrag" "$SYSTEM_CRON_PATH"; then
+				sudo_login 1
+				awk '{print "==> "$NF}' < <(sudo cp -v "$JOB_DIR/z-defrag" "$SYSTEM_CRON_PATH")
+			fi ;;
+		* )
+			if [[ ! -f "$anacron_path/z-defrag" ]]; then
+				sudo_login 1
+				awk '{print "==> "$NF} ' < <(sudo cp -v "$JOB_DIR/z-defrag" "$anacron_path")
+			elif is_older "z-defrag" "$anacron_path"; then
+				sudo_login 1
+				awk '{print "==> "$NF}' < <(sudo cp -v "$JOB_DIR/z-defrag" "$anacron_path")
+			fi ;;
+	esac
+	return 0
 }
 
 cp_zupdate() {
-  local -r sed_file="updatelog.sed"
-  local -r anacron_path="/etc/cron.weekly/"
-  case "$LOCALIP" in
-    10|12|13|14|15|17|19|20|21|22|23|24|25 )
-      if [[ -f "$anacron_path/z-update" ]]; then
-        sudo_login 1
-        awk '{print "==> "$NF}' < <(sudo cp -v "$JOB_DIR/z-update" "$anacron_path")
-      elif is_older "z-update" "$anacron_path"; then
-        sudo_login 1
-        awk '{print "==> "$NF}' < <(sudo cp -v "$JOB_DIR/z-update" "$anacron_path")
-      fi
-      ;;
-    11|16 )
-      [[ -d "$SYSTEM_CRON_PATH" ]] || { sudo_login 1; sudo mkdir -p "$SYSTEM_CRON_PATH"; }
-      if [[ -f "$SED_PATH/$sed_file" ]]; then
-        sudo_login 1
-        awk '{print "==> "$NF}' < <(sudo cp -v "$JOB_DIR/z-update" "$SYSTEM_CRON_PATH")
-      elif is_older "z-update" "$SYSTEM_CRON_PATH"; then
-        sudo_login 1
-        awk '{print "==> "$NF}' < <(sudo cp -v "$JOB_DIR/z-update" "$SYSTEM_CRON_PATH")
-      fi
-      ;;
-  esac
-  if [[ ! -f "$SED_PATH/$sed_file" ]]; then
-    sudo_login 1
-    awk '{print "==> "$NF}' < <(sudo cp -v "$FILES_DIR/$sed_file" "$SED_PATH")
-  elif [[ "$SED_PATH/$sed_file" -ot "$FILES_DIR/$sed_file" ]]; then
-    sudo_login 1
-    awk '{print "==> "$NF}' < <(sudo cp -v "$FILES_DIR/$sed_file" "$SED_PATH")
-  fi
-  return 0
+	local -r sed_file="updatelog.sed"
+	local -r anacron_path="/etc/cron.weekly/"
+	case "$LOCALIP" in
+		11|16 )
+			[[ -d "$SYSTEM_CRON_PATH" ]] || { sudo_login 1; sudo mkdir -p "$SYSTEM_CRON_PATH"; }
+			if [[ -f "$SED_PATH/$sed_file" ]]; then
+				sudo_login 1
+				awk '{print "==> "$NF}' < <(sudo cp -v "$JOB_DIR/z-update" "$SYSTEM_CRON_PATH")
+			elif is_older "z-update" "$SYSTEM_CRON_PATH"; then
+				sudo_login 1
+				awk '{print "==> "$NF}' < <(sudo cp -v "$JOB_DIR/z-update" "$SYSTEM_CRON_PATH")
+			fi ;;
+		* )
+			if [[ -f "$anacron_path/z-update" ]]; then
+				sudo_login 1
+				awk '{print "==> "$NF}' < <(sudo cp -v "$JOB_DIR/z-update" "$anacron_path")
+			elif is_older "z-update" "$anacron_path"; then
+				sudo_login 1
+				awk '{print "==> "$NF}' < <(sudo cp -v "$JOB_DIR/z-update" "$anacron_path")
+			fi
+	esac
+	if [[ ! -f "$SED_PATH/$sed_file" ]]; then
+		sudo_login 1
+		awk '{print "==> "$NF}' < <(sudo cp -v "$FILES_DIR/$sed_file" "$SED_PATH")
+	elif [[ "$SED_PATH/$sed_file" -ot "$FILES_DIR/$sed_file" ]]; then
+		sudo_login 1
+		awk '{print "==> "$NF}' < <(sudo cp -v "$FILES_DIR/$sed_file" "$SED_PATH")
+	fi
+	return 0
 }
 
 cp_zytdlpupdate() {
 	# local -r sed_file="ytdlp-uplog.sed"
-  local -r anacron_path="/etc/cron.daily/"
-  case "$LOCALIP" in
-    10|15|17 )
-      if [[ ! -f "$anacron_path/z-ytdlp-update" ]]; then
-        sudo_login 1
-        awk '{print "==> "$NF}' < <(sudo cp -v "$JOB_DIR/z-ytdlp-update" "$anacron_path")
-      elif is_older "z-ytdlp-update" "$anacron_path"; then
-        sudo_login 1
-        awk '{print "==> "$NF}' < <(sudo cp -v "$JOB_DIR/z-ytdlp-update" "$anacron_path")
-      fi
-      ;;
-    * )
-      no_copy "z-ytdlp-update is"
-  esac
-  return 0
+	local -r anacron_path="/etc/cron.daily/"
+	case "$LOCALIP" in
+		10|15|17 )
+			if [[ ! -f "$anacron_path/z-ytdlp-update" ]]; then
+				sudo_login 1
+				awk '{print "==> "$NF}' < <(sudo cp -v "$JOB_DIR/z-ytdlp-update" "$anacron_path")
+			elif is_older "z-ytdlp-update" "$anacron_path"; then
+				sudo_login 1
+				awk '{print "==> "$NF}' < <(sudo cp -v "$JOB_DIR/z-ytdlp-update" "$anacron_path")
+			fi ;;
+		* )
+			no_copy "z-ytdlp-update is"
+	esac
+	return 0
 }
 
 main() {
 	local -r script="${0##*/}"
-	local -r version="10.3.26217"
-	local exit_code=0
-  local opt OPTARG OPTIND
-  [[ -d "$USER_CRON_PATH" ]] || mkdir -p "$USER_CRON_PATH"
-  local -i noOpt=1
-  local -r optstr=":acdfghmrstuy"
-  printf "Copying updated cron scripts...\n"
-  while getopts "$optstr" opt; do
-    case "$opt" in
-      a )
-        cp_finance_bu
-        cp_git_bu
-        cp_scriptarchive
-        cp_empty_trash
-        cp_clone_update
-        cp_zupdate
-        cp_zdefrag
-        cp_zytdlpupdate
-        ;;
-      c ) cp_clone_update ;;
-      d ) cp_zdefrag ;;
-      f ) cp_finance_bu ;;
-      g ) cp_git_bu ;;
-      h ) help "$script" "$version" 0 ;;
-      m ) cp_main_bu ;;
-      r ) cp_redshift_notify ;;
-      s ) cp_scriptarchive ;;
-      t ) cp_empty_trash ;;
-      u ) cp_zupdate ;;
-      y ) cp_zytdlpupdate ;;
-      ? )
-        printf "%s Invalid option -%s\n" "$RED_ERROR" "$OPTARG" >&2
-        help "$script" "$version" "$E_INVALID_ARG"
-    esac
-    exit_code="$?"
-	  noOpt=0
-  done
-  (( noOpt == 1 )) && { printf "%s No arguments passed.\n" "$RED_ERROR" >&2; help "$script" "$version" "$E_MISSING_ARG"; }
-  shift "$(( OPTIND - 1 ))"
-  over_line "$script $version"
-  exit "$exit_code"
+	local -r version="10.4.26248"
+	local -i exit_code=0
+	local opt OPTARG OPTIND
+	local -i noOpt=1
+	local -r optstr=":acdfghmrstuy"
+	[[ -d "$USER_CRON_PATH" ]] || mkdir -p "$USER_CRON_PATH"
+	printf "Copying updated cron scripts...\n"
+	while getopts "$optstr" opt; do
+		case "$opt" in
+			a )
+				cp_main_bu
+				cp_finance_bu
+				cp_git_bu
+				cp_scriptarchive
+				cp_empty_trash
+				cp_clone_update
+				cp_redshift_notify
+				cp_zupdate
+				cp_zdefrag
+				cp_zytdlpupdate ;;
+			c ) cp_clone_update ;;
+			d ) cp_zdefrag ;;
+			f ) cp_finance_bu ;;
+			g ) cp_git_bu ;;
+			h ) help "$script" "$version" 0 ;;
+			m ) cp_main_bu ;;
+			r ) cp_redshift_notify ;;
+			s ) cp_scriptarchive ;;
+			t ) cp_empty_trash ;;
+			u ) cp_zupdate ;;
+			y ) cp_zytdlpupdate ;;
+			? )
+				printf "%s Invalid option -%s\n" "$RED_ERROR" "$OPTARG" >&2
+				help "$script" "$version" "$E_INVALID_ARG"
+		esac
+		exit_code="$?"
+		noOpt=0
+	done
+	if (( noOpt == 1 )); then
+		printf "%s No argument passed.\n" "$RED_ERROR" >&2
+		help "$script" "$version" "$E_MISSING_ARG"
+	fi
+	shift "$(( OPTIND - 1 ))"
+	over_line "$script $version"
+	exit "$exit_code"
 }
 
 main "$@"
