cronscripts - added a global variable to count updates made. If no updates, displays a message.

diff --git a/cronscripts b/cronscripts
--- a/cronscripts
+++ b/cronscripts
@@ -7,7 +7,7 @@
 # Author       : Copyright (C) 2022, Richard B. Romig, Mosfanet
 # Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
 # Crated       : 17 Feb 2022
-# Updated      : 17 Jan 2025
+# Updated      : 10 Feb 2025
 # Comments     :
 # TODO (Rick)  :
 # License      : GNU General Public License, version 2.0
@@ -28,13 +28,14 @@ fi
 ## Global Variables ##
 
 script=$(basename "$0"); readonly script
-readonly version="5.19.25017"
+readonly version="5.20.25041"
 localip="$(local_ip)"; readonly localip
 # path variables
 readonly script_path="$HOME/bin"
 readonly user_cron_path="$HOME/.local/bin/"
 readonly opt_cron_path="/opt/bin/"
 readonly sed_path="/usr/share/misc/"
+count=0
 
 ## Functions ##
 
@@ -42,9 +43,9 @@ cp_repo_backup() {
   case "$localip" in
     10|16 )
       [[ -d "$user_cron_path" ]] || mkdir -p "$user_cron_path"
-      cp -puv "$script_path/gitea-dwm-bu.sh" "$user_cron_path" | awk '{print "==> "$NF}'
-      cp -puv "$script_path/gitea-bu.sh" "$user_cron_path" | awk '{print "==> "$NF}'
-      cp -puv "$script_path/github-bu.sh" "$user_cron_path" | awk '{print "==> "$NF}'
+      cp -puv "$script_path/gitea-dwm-bu.sh" "$user_cron_path" | awk '{print "==> "$NF}' || (( count++ ))
+      cp -puv "$script_path/gitea-bu.sh" "$user_cron_path" | awk '{print "==> "$NF}' || (( count++ ))
+      cp -puv "$script_path/github-bu.sh" "$user_cron_path" | awk '{print "==> "$NF}' || (( count++ ))
     ;;
     * )
       no_copy "Repository archives are"
@@ -55,11 +56,11 @@ cp_main_bu() {
   case "$localip" in
   10 )
       [[ -d "$user_cron_path" ]] || mkdir -p "$user_cron_path"
-      cp -puv "$script_path/sync-nas.sh" "$user_cron_path" | awk '{print "==> "$NF}'
-      cp -puv "$script_path/sync6005.sh" "$user_cron_path" | awk '{print "==> "$NF}'
-      cp -puv "$script_path/journal-bu.sh" "$user_cron_path" | awk '{print "==> "$NF}'
-      cp -puv "$script_path/passwdsync.sh" "$user_cron_path" | awk '{print "==> "$NF}'
-      cp -puv $"$script_path/repo-backup.sh" "$user_cron_path" | awk '{print "==> "$NF}'
+      cp -puv "$script_path/sync-nas.sh" "$user_cron_path" | awk '{print "==> "$NF}' || (( count++ ))
+      cp -puv "$script_path/sync6005.sh" "$user_cron_path" | awk '{print "==> "$NF}' || (( count++ ))
+      cp -puv "$script_path/journal-bu.sh" "$user_cron_path" | awk '{print "==> "$NF}' || (( count++ ))
+      cp -puv "$script_path/passwdsync.sh" "$user_cron_path" | awk '{print "==> "$NF}' || (( count++ ))
+      cp -puv $"$script_path/repo-backup.sh" "$user_cron_path" | awk '{print "==> "$NF}' || (( count++ ))
   ;;
     * )
       no_copy "Main system sync scripts are"
@@ -70,8 +71,8 @@ cp_finance_bu() {
   case "$localip" in
     10 )
       [[ -d "$user_cron_path" ]] || mkdir -p "$user_cron_path"
-      cp -puv "$script_path/fin-bu.sh" "$user_cron_path" | awk '{print "==> "$NF}'
-      cp -puv "$script_path/hb-archive.sh" "$user_cron_path" | awk '{print "==> "$NF}'
+      cp -puv "$script_path/fin-bu.sh" "$user_cron_path" | awk '{print "==> "$NF}' || (( count++ ))
+      cp -puv "$script_path/hb-archive.sh" "$user_cron_path" | awk '{print "==> "$NF}' || (( count++ ))
     ;;
     * )
       no_copy "Finance archives are"
@@ -82,7 +83,7 @@ cpscriptarchive() {
   case "$localip" in
     10|11|12|13|14|15|16|19|20|23 )
       [[ -d "$user_cron_path" ]] || mkdir -p "$user_cron_path"
-      cp -puv "$script_path/scriptarchive.sh" "$user_cron_path" | awk '{print "==> "$NF}'
+      cp -puv "$script_path/scriptarchive.sh" "$user_cron_path" | awk '{print "==> "$NF}' || (( count++ ))
     ;;
     * )
       no_copy "scriptarchive.sh is"
@@ -93,7 +94,7 @@ cp_empty_trash() {
   case "$localip" in
     10|11|12|13|14|15|16|17|18|19|20|21|22|23|24|25 )
       [[ -d "$user_cron_path" ]] || mkdir -p "$user_cron_path"
-      cp -puv "$script_path/empty-trash.sh" "$user_cron_path" | awk '{print "==> "$NF}'
+      cp -puv "$script_path/empty-trash.sh" "$user_cron_path" | awk '{print "==> "$NF}' || (( count++ ))
     ;;
     * )
       no_copy "empty-trash.sh is"
@@ -104,7 +105,7 @@ cp_redshift_notify() {
   case "$localip" in
     10|11|12|13|14|15|16|17|18|19|20|21|22|23|24|25 )
       [[ -d "$user_cron_path" ]] || mkdir -p "$user_cron_path"
-      cp -puv "$script_path/redshift-notify.sh" "$user_cron_path" | awk '{print "==> "$NF}'
+      cp -puv "$script_path/redshift-notify.sh" "$user_cron_path" | awk '{print "==> "$NF}' || (( count++ ))
     ;;
     * )
       no_copy "redshift-notify.sh is"
@@ -115,7 +116,7 @@ cp_zbackup() {
 	case "$localip" in
 		11 )
 		  [[ -d "$opt_cron_path" ]] || sudo mkdir -p "$opt_cron_path"
-		  sudo cp -uv "$script_path/z-backup" "$opt_cron_path" | awk '{print "==> "$NF}'
+		  sudo cp -uv "$script_path/z-backup" "$opt_cron_path" | awk '{print "==> "$NF}' || (( count++ ))
     ;;
 		* )
 			no_copy "z-backup is"
@@ -126,11 +127,11 @@ cp_zdefrag() {
   local anacron_path="/etc/cron.monthly/"
   case "$localip" in
     10|12|13|15|20|23 )
-      sudo cp -uv "$script_path/z-defrag" "$anacron_path" | awk '{print "==> "$NF}'
+      sudo cp -uv "$script_path/z-defrag" "$anacron_path" | awk '{print "==> "$NF}' || (( count++ ))
     ;;
     11|14|16|19 )
       [[ -d "$opt_cron_path" ]] || sudo mkdir -p "$opt_cron_path"
-      sudo cp -uv "$script_path/z-defrag" "$opt_cron_path" | awk '{print "==> "$NF}'
+      sudo cp -uv "$script_path/z-defrag" "$opt_cron_path" | awk '{print "==> "$NF}' || (( count++ ))
     ;;
     * )
       no_copy "z-defrag is"
@@ -143,13 +144,13 @@ cp_zupdate() {
   anacron_path="/etc/cron.weekly/"
   case "$localip" in
     10|12|13|15|17|20|21|22|23|24|25|227 )
-      sudo cp -uv "$script_path/z-update" "$anacron_path" | awk '{print "==> "$NF}'
-      sudo cp -uv "$script_path/$sed_file" "$sed_path" | awk '{print "==> "$NF}'
+      sudo cp -uv "$script_path/z-update" "$anacron_path" | awk '{print "==> "$NF}' || (( count++ ))
+      sudo cp -uv "$script_path/$sed_file" "$sed_path" | awk '{print "==> "$NF}' || (( count++ ))
     ;;
     11|14|16|19 )
       [[ -d "$opt_cron_path" ]] || sudo mkdir -p "$opt_cron_path"
-      sudo cp -uv "$script_path/z-update" "$opt_cron_path" | awk '{print "==> "$NF}'
-      sudo cp -uv "$script_path/$sed_file" "$sed_path" | awk '{print "==> "$NF}'
+      sudo cp -uv "$script_path/z-update" "$opt_cron_path" | awk '{print "==> "$NF}' || (( count++ ))
+      sudo cp -uv "$script_path/$sed_file" "$sed_path" | awk '{print "==> "$NF}' || (( count++ ))
     ;;
     * )
       no_copy "z-update is"
@@ -162,8 +163,8 @@ cp_zytdlpupdate() {
   anacron_path="/etc/cron.daily/"
   case "$localip" in
     10|15|17 )
-      sudo cp -uv "$script_path/z-ytdlp-update" "$anacron_path" | awk '{print "==> "$NF}'
-      sudo cp -uv "$script_path/$sed_file" "$sed_path" | awk '{print "==> "$NF}'
+      sudo cp -uv "$script_path/z-ytdlp-update" "$anacron_path" | awk '{print "==> "$NF}' || (( count++ ))
+      sudo cp -uv "$script_path/$sed_file" "$sed_path" | awk '{print "==> "$NF}' || (( count++ ))
     ;;
     * )
       no_copy "z-ytdlp-update is"
@@ -178,7 +179,7 @@ no_copy() {
 help() {
   local errcode updated
   errcode="${1:-2}"
-  updated="17 Jan 2025
+  updated="10 Feb 2025
 # Comments     :"
   cat << _HELP_
 ${orange}$script${normal} $version, Updated: $updated
@@ -266,6 +267,7 @@ main() {
   done
   [[ "$noOpt" = 1 ]] && { printf "%s No arguments passed.\n" "$RED_ERROR" >&2; help 1; }
   shift "$(( OPTIND - 1 ))"
+  [[ "$count" -eq 0 ]] && printf "No updates required.\n"
   over_line "$script v$version"
   exit
 }
