cronscripts - getopts in main(); updated local variables.

diff --git a/cronscripts b/cronscripts
--- a/cronscripts
+++ b/cronscripts
@@ -7,7 +7,7 @@
 # Author       : Copyright (C) 2022, Richard B. Romig, Mosfanet
 # Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
 # Crated       : 17 Feb 2022
-# Updated      : 19 Aug 2024
+# Updated      : 30 Sep 2024
 # Comments     :
 # TODO (Rick)  :
 # License      : GNU General Public License, version 2.0
@@ -27,9 +27,8 @@ fi
 
 ## Global Variables ##
 
-_script=$(basename "$0"); readonly _script
-readonly _version="5.15.24232"
-readonly _updated="19 Aug 2024"
+script=$(basename "$0"); readonly script
+readonly version="5.16.24274"
 localip="$(local_ip)"; readonly localip
 # path variables
 readonly script_path="$HOME/bin"
@@ -79,7 +78,7 @@ cp_finance_bu() {
   esac
 }
 
-cp_scriptarchive() {
+cpscriptarchive() {
   case "$localip" in
     10|11|12|13|14|15|16|19|20|23 )
       [[ -d "$user_cron_path" ]] || mkdir -p "$user_cron_path"
@@ -128,8 +127,9 @@ cp_zdefrag() {
 }
 
 cp_zupdate() {
-  local sed_file="files/updatelog.sed"
-  local anacron_path="/etc/cron.weekly/"
+  local sed_file anacron_path
+  sed_file="files/updatelog.sed"
+  anacron_path="/etc/cron.weekly/"
   case "$localip" in
     10|12|13|15|17|20|21|22|23|24|25|227 )
       sudo cp -uv "$script_path/z-update" "$anacron_path" | awk '{print "==> "$NF}'
@@ -146,8 +146,9 @@ cp_zupdate() {
 }
 
 cp_zytdlpupdate() {
-	local sed_file="files/ytdlp-uplog.sed"
-  local anacron_path="/etc/cron.daily/"
+  local sed_file anacron_path
+	sed_file="files/ytdlp-uplog.sed"
+  anacron_path="/etc/cron.daily/"
   case "$localip" in
     10|15|17 )
       sudo cp -uv "$script_path/z-ytdlp-update" "$anacron_path" | awk '{print "==> "$NF}'
@@ -164,12 +165,14 @@ no_copy() {
 }
 
 help() {
-  local errcode="${1:-2}"
-  cat << END_HELP
-${orange}$_script${normal} $_version, Upated: $_updated
+  local errcode updated
+  errcode="${1:-2}"
+  updated="30 Sep 2024"
+  cat << _HELP_
+${orange}$script${normal} $version, Updated: $updated
 Copies updated cron scripts to the appropriate directories.
 
-${green}Usage:${normal} $_script [OPTIONS]
+${green}Usage:${normal} $script [OPTIONS]
 
 ${orange}Available options:${normal}
   -a    Copy all applicable scripts.
@@ -184,67 +187,72 @@ ${orange}Available options:${normal}
   -u    Copy system update script.
   -y    Copy yt-dlp update script.
   NOTE: Multiple arguments may be passed to the script.
-END_HELP
+_HELP_
   exit "$errcode"
+}
+
+main() {
+  local noOpt opt optstr
+  noOpt=1
+  optstr=":abdfhmrstuy"
+  while getopts "$optstr" opt; do
+    case "$opt" in
+      a )
+        cp_finance_bu
+        cp_repo_backup
+        cpscriptarchive
+        cp_empty_trash
+        sudo_login 2
+        cp_zupdate
+        cp_zdefrag
+        cp_zytdlpupdate
+        cp_zbackup
+      ;;
+		  b )
+        sudo_login 2
+			  cp_zbackup
+		  ;;
+      d )
+        sudo_login 2
+        cp_zdefrag
+      ;;
+      f )
+        cp_finance_bu
+      ;;
+      h )
+        help 0
+      ;;
+      m )
+        cp_main_bu
+      ;;
+      r )
+        cp_repo_backup
+      ;;
+      s )
+        cpscriptarchive
+      ;;
+      t )
+        cp_empty_trash
+      ;;
+      u )
+        sudo_login 2
+        cp_zupdate
+      ;;
+      y )
+        sudo_login 2
+        cp_zytdlpupdate
+      ;;
+      ? )
+        printf "%s Invalid option -%s\n" "$RED_ERROR" "$OPTARG" >&2
+        help 2
+    esac
+	  noOpt=0
+  done
+  [[ "$noOpt" = 1 ]] && { printf "%s No arguments passed.\n" "$RED_ERROR" >&2; help 1; }
+  shift "$(( OPTIND - 1 ))"
+  leave "$script v$version"
 }
 
 ## Execution ##
 
-noOpt=1
-optstr=":abdfhmrstuy"
-while getopts "$optstr" opt; do
-  case "$opt" in
-    a )
-      cp_finance_bu
-      cp_repo_backup
-      cp_scriptarchive
-      cp_empty_trash
-      sudo_login 2
-      cp_zupdate
-      cp_zdefrag
-      cp_zytdlpupdate
-      cp_zbackup
-    ;;
-		b )
-      sudo_login 2
-			cp_zbackup
-		;;
-    d )
-      sudo_login 2
-      cp_zdefrag
-    ;;
-    f )
-      cp_finance_bu
-    ;;
-    h )
-      help 0
-    ;;
-    m )
-      cp_main_bu
-    ;;
-    r )
-      cp_repo_backup
-    ;;
-    s )
-      cp_scriptarchive
-    ;;
-    t )
-      cp_empty_trash
-    ;;
-    u )
-      sudo_login 2
-      cp_zupdate
-    ;;
-    y )
-      sudo_login 2
-      cp_zytdlpupdate
-    ;;
-    ? )
-      printf "%s Invalid option -%s\n" "$red_error" "$OPTARG" >&2
-      help 2
-  esac
-	noOpt=0
-done
-[[ "$noOpt" = 1 ]] && { printf "%s No arguments passed.\n" "$red_error" >&2; help 1; }
-shift "$(( OPTIND - 1 ))"
-leave "$_script v$_version"
+main "$@"
