cronscripts: cp_main_bu() - traverse array of scripts; implemented process substitution

diff --git a/cronscripts b/cronscripts
--- a/cronscripts
+++ b/cronscripts
@@ -7,7 +7,7 @@
 # Author       : Copyright (C) 2022, Richard B. Romig, Mosfanet
 # Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
 # Crated       : 17 Feb 2022
-# Updated      : 12 Jan 2026
+# Updated      : 08 Feb 2026
 # Comments     : For jobs needinng root access, checks if repo script is
 #              : newer than the one run by anacron/cron
 # TODO (Rick)  :
@@ -34,13 +34,13 @@ if [[ -x "$HOME/bin/functionlib" ]]; then
   source "$HOME/bin/functionlib"
 else
   printf "\e[91mERROR:\e[0m functionlib not found!\n" >&2
-  exit 1
+  exit 81
 fi
 
 ## Global Variables ##
 
 readonly script="${0##*/}"
-readonly version="9.2.26012"
+readonly version="10.0.26039"
 localip="$(local_ip)"; readonly localip
 # path variables
 script_dir=$(dirname "$(readlink -f "${0}")"); readonly script_dir
@@ -53,8 +53,8 @@ readonly sed_path="/usr/share/misc/"
 ## Functions ##
 
 help() {
-  local errcode="${1:-2}"
-  local updated="12 Jan 2026"
+  local errcode="${1:-1}"
+  local updated="08 Feb 2026"
   cat << _HELP_
 ${orange}$script${normal} $version, Updated: $updated
 Copies cronjob scripts to the appropriate directories.
@@ -94,17 +94,15 @@ cp_clone_update() {
     10|16|22 )
       no_copy "Cloned repository updates are" ;;
     * )
-      [[ -d "$user_cron_path" ]] || mkdir -p "$user_cron_path"
-      is_older "clone-update.sh" "$user_cron_path" && cp -pv "$job_dir/clone-update.sh" "$user_cron_path" | awk '{print "==> "$NF}'
+      is_older "clone-update.sh" "$user_cron_path" && awk '{print "==> "$NF}' <(cp -pv "$job_dir/clone-update.sh" "$user_cron_path")
   esac
 }
 
-cp_repo_backup() {
+cp_git_bu() {
   case "$localip" in
     10|16 )
-      [[ -d "$user_cron_path" ]] || mkdir -p "$user_cron_path"
-      is_older "git-dwm.sh" "$user_cron_path"  && cp -pv "$job_dir/git-dwm.sh" "$user_cron_path" | awk '{print "==> "$NF}'
-      is_older "git-bu.sh" "$user_cron_path"  && cp -pv "$job_dir/git-bu.sh" "$user_cron_path" | awk '{print "==> "$NF}'
+      is_older "git-dwm.sh" "$user_cron_path" && awk '{print "==> "$NF}' <(cp -pv "$job_dir/git-dwm.sh" "$user_cron_path")
+      is_older "git-bu.sh" "$user_cron_path" && awk '{print "==> "$NF}' <(cp -pv "$job_dir/git-bu.sh" "$user_cron_path")
       ;;
     * )
       no_copy "Repository archives are"
@@ -112,14 +110,13 @@ cp_repo_backup() {
 }
 
 cp_main_bu() {
+  local buscript buscripts
+  buscripts=(sync-nas.sh sync6005.sh journal-bu.sh passwdsync.sh repo-backup.sh)
   case "$localip" in
   10 )
-      [[ -d "$user_cron_path" ]] || mkdir -p "$user_cron_path"
-      is_older "sync-nas.sh" "$user_cron_path" && cp -pv "$job_dir/sync-nas.sh" "$user_cron_path" | awk '{print "==> "$NF}'
-      is_older "sync6005.sh" "$user_cron_path" && cp -pv "$job_dir/sync6005.sh" "$user_cron_path" | awk '{print "==> "$NF}'
-      is_older "journal-bu.sh" "$user_cron_path" && cp -pv "$job_dir/journal-bu.sh" "$user_cron_path" | awk '{print "==> "$NF}'
-      is_older "passwdsync.sh" "$user_cron_path" && cp -pv "$job_dir/passwdsync.sh" "$user_cron_path" | awk '{print "==> "$NF}'
-      is_older "repo-backup.sh" "$user_cron_path" && cp -pv $"$job_dir/repo-backup.sh" "$user_cron_path" | awk '{print "==> "$NF}'
+      for buscript in "${buscripts[@]}"; do
+        is_older "$buscript" "$user_cron_path" && awk '{print "==> "$NF}' <(cp -pv "$job_dir/$buscript" "$user_cron_path")
+      done
       ;;
     * )
       no_copy "Main system sync scripts are"
@@ -129,9 +126,8 @@ cp_main_bu() {
 cp_finance_bu() {
   case "$localip" in
     10 )
-      [[ -d "$user_cron_path" ]] || mkdir -p "$user_cron_path"
-      is_older "fin-bu.sh" "$user_cron_path" &&  cp -pv "$job_dir/fin-bu.sh" "$user_cron_path" | awk '{print "==> "$NF}'
-      is_older "hb-archive.sh" "$user_cron_path" && cp -pv "$job_dir/hb-archive.sh" "$user_cron_path" | awk '{print "==> "$NF}'
+      is_older "fin-bu.sh" "$user_cron_path" &&  awk '{print "==> "$NF}' <(cp -pv "$job_dir/fin-bu.sh" "$user_cron_path")
+      is_older "hb-archive.sh" "$user_cron_path" && awk '{print "==> "$NF}' <(cp -pv "$job_dir/hb-archive.sh" "$user_cron_path")
       ;;
     * )
       no_copy "Finance archives are"
@@ -143,14 +139,12 @@ cp_scriptarchive() {
     17|21|22|24 )
       no_copy "scriptarchive.sh is" ;;
     * )
-      [[ -d "$user_cron_path" ]] || mkdir -p "$user_cron_path"
-      is_older "scriptarchive.sh" "$user_cron_path" && cp -pv "$job_dir/scriptarchive.sh" "$user_cron_path" | awk '{print "==> "$NF}'
+      is_older "scriptarchive.sh" "$user_cron_path" && awk '{print "==> "$NF}' <(cp -pv "$job_dir/scriptarchive.sh" "$user_cron_path")
   esac
 }
 
 cp_empty_trash() {
-  [[ -d "$user_cron_path" ]] || mkdir -p "$user_cron_path"
-  is_older "empty-trash.sh" "$user_cron_path" && cp -pv "$job_dir/empty-trash.sh" "$user_cron_path" | awk '{print "==> "$NF}'
+  is_older "empty-trash.sh" "$user_cron_path" && awk '{print "==> "$NF}' <(cp -pv "$job_dir/empty-trash.sh" "$user_cron_path")
 }
 
 cp_redshift_notify() {
@@ -158,8 +152,7 @@ cp_redshift_notify() {
     10|11|14|15|17|19|20|21 )
       no_copy "redshift-notify.sh is" ;;
     * )
-      [[ -d "$user_cron_path" ]] || mkdir -p "$user_cron_path"
-      is_older "redshift-notify.sh" "$user_cron_path" && cp -pv "$job_dir/redshift-notify.sh" "$user_cron_path" | awk '{print "==> "$NF}'
+      is_older "redshift-notify.sh" "$user_cron_path" && awk '{print "==> "$NF}' <(cp -pv "$job_dir/redshift-notify.sh" "$user_cron_path")
   esac
 }
 
@@ -167,13 +160,23 @@ cp_zdefrag() {
   local -r anacron_path="/etc/cron.monthly/"
   case "$localip" in
     10|12|13|14|15|17|19|20|21|22|23|24 )
-      [[ -f "$anacron_path/z-defrag" ]] || { sudo_login 1; sudo cp -v "$job_dir/z-defrag" "$anacron_path" | awk '{print "==> "$NF}'; }
-      is_older "z-defrag" "$anacron_path" && { sudo_login 1; sudo cp -v "$job_dir/z-defrag" "$anacron_path" | awk '{print "==> "$NF}'; }
+      if [[ ! -f "$anacron_path/z-defrag" ]]; then
+        sudo_login 1
+        awk '{print "==> "$NF}' <(sudo cp -v "$job_dir/z-defrag" "$anacron_path")
+      elif is_older "z-defrag" "$anacron_path"; then
+        sudo_login 1
+        awk '{print "==> "$NF}' <(sudo cp -v "$job_dir/z-defrag" "$anacron_path")
+      fi
       ;;
     11|16 )
       [[ -d "$opt_cron_path" ]] || { sudo_login 1; sudo mkdir -p "$opt_cron_path"; }
-      [[ -f "$opt_cron_path/z-defrag" ]] || { sudo_login 1; sudo cp -v "$job_dir/z-defrag" "$opt_cron_path" | awk '{print "==> "$NF}'; }
-      is_older "z-defrag" "$opt_cron_path" && { sudo_login 1; sudo cp -v "$job_dir/z-defrag" "$opt_cron_path" | awk '{print "==> "$NF}'; }
+      if [[ -f "$opt_cron_path/z-defrag" ]]; then
+        sudo_login 1
+        awk '{print "==> "$NF}' <(sudo cp -v "$job_dir/z-defrag" "$opt_cron_path")
+      elif is_older "z-defrag" "$opt_cron_path"; then
+        sudo_login 1
+        awk '{print "==> "$NF}' <(sudo cp -v "$job_dir/z-defrag" "$opt_cron_path")
+      fi
       ;;
     * )
       no_copy "z-defrag is"
@@ -185,17 +188,32 @@ cp_zupdate() {
   local -r anacron_path="/etc/cron.weekly/"
   case "$localip" in
     10|12|13|14|15|17|19|20|21|22|23|24|25 )
-			[[ -f "$anacron_path/z-update" ]] || { sudo_login 1; sudo cp -v "$job_dir/z-update" "$anacron_path" | awk '{print "==> "$NF}'; }
-			is_older "z-update" "$anacron_path" && { sudo_login 1; sudo cp -v "$job_dir/z-update" "$anacron_path" | awk '{print "==> "$NF}'; }
+      if [[ -f "$anacron_path/z-update" ]]; then
+        sudo_login 1
+        awk '{print "==> "$NF}' <(sudo cp -v "$job_dir/z-update" "$anacron_path")
+      elif is_older "z-update" "$anacron_path"; then
+        sudo_login 1
+        awk '{print "==> "$NF}' <(sudo cp -v "$job_dir/z-update" "$anacron_path")
+      fi
       ;;
     11|16 )
       [[ -d "$opt_cron_path" ]] || { sudo_login 1; sudo mkdir -p "$opt_cron_path"; }
-			[[ -f "$opt_cron_path/z-update" ]] || { sudo_login 1; sudo cp -v "$job_dir/z-update" "$opt_cron_path" | awk '{print "==> "$NF}'; }
-      is_older "z-update" "$opt_cron_path" && { sudo_login 1; sudo cp -v "$job_dir/z-update" "$opt_cron_path" | awk '{print "==> "$NF}'; }
+      if [[ -f "$sed_path/$sed_file" ]]; then
+        sudo_login 1
+        awk '{print "==> "$NF}' <(sudo cp -v "$job_dir/z-update" "$opt_cron_path")
+      elif s_older "z-update" "$opt_cron_path"; then
+        sudo_login 1
+        awk '{print "==> "$NF}' <(sudo cp -v "$job_dir/z-update" "$opt_cron_path")
+      fi
       ;;
   esac
-  [[ -f "$sed_path/$sed_file" ]] || { sudo_login 1; sudo cp -v "$files_dir/$sed_file" "$sed_path" | awk '{print "==> "$NF}'; }
-  [[ "$sed_path/$sed_file" -ot "$files_dir/$sed_file" ]] && { sudo_login 1; sudo cp -v "$files_dir/$sed_file" "$sed_path" | awk '{print "==> "$NF}'; }
+  if [[ -f "$sed_path/$sed_file" ]]; then
+    sudo_login 1
+    awk '{print "==> "$NF}' <(sudo cp -v "$files_dir/$sed_file" "$sed_path")
+  elif [[ "$sed_path/$sed_file" -ot "$files_dir/$sed_file" ]]; then
+    sudo_login 1
+    awk '{print "==> "$NF}' <(sudo cp -v "$files_dir/$sed_file" "$sed_path")
+  fi
 }
 
 cp_zytdlpupdate() {
@@ -203,10 +221,21 @@ cp_zytdlpupdate() {
   local -r anacron_path="/etc/cron.daily/"
   case "$localip" in
     10|15|17 )
-      [[ -f "$anacron_path/z-ytdlp-update" ]] || { sudo_login 1; sudo cp -v "$job_dir/z-ytdlp-update" "$anacron_path" | awk '{print "==> "$NF}'; }
-			is_older "z-ytdlp-update" "$anacron_path" && { sudo_login 1; sudo cp -v "$job_dir/z-ytdlp-update" "$anacron_path" | awk '{print "==> "$NF}'; }
-      [[ -f "$sed_path/$sed_file" ]] || { sudo_login 1; sudo cp -v "$files_dir/$sed_file" "$sed_path" | awk '{print "==> "$NF}'; }
-      [[ "$sed_path/$sed_file" -ot "$files_dir/$sed_file" ]] && { sudo_login 1; sudo cp -v "$files_dir/$sed_file" "$sed_path" | awk '{print "==> "$NF}'; }
+      if [[ -f "$anacron_path/z-ytdlp-update" ]]; then
+        sudo_login 1
+        awk '{print "==> "$NF}' <(sudo cp -v "$job_dir/z-ytdlp-update" "$anacron_path")
+      elif is_older "z-ytdlp-update" "$anacron_path"; then
+        sudo_login 1
+        awk '{print "==> "$NF}' <(sudo cp -v "$job_dir/z-ytdlp-update" "$anacron_path")
+      fi
+      if [[ -f "$sed_path/$sed_file" ]]; then
+        sudo_login 1
+        awk '{print "==> "$NF}' <(sudo cp -v "$files_dir/$sed_file" "$sed_path")
+      elif [[ "$sed_path/$sed_file" -ot "$files_dir/$sed_file" ]]; then
+        sudo_login 1
+        sudo_login 1
+        awk '{print "==> "$NF}' <(sudo cp -v "$files_dir/$sed_file" "$sed_path")
+      fi
       ;;
     * )
       no_copy "z-ytdlp-update is"
@@ -215,6 +244,7 @@ cp_zytdlpupdate() {
 
 main() {
   local noOpt opt optstr OPTARG OPTIND
+  [[ -d "$user_cron_path" ]] || mkdir -p "$user_cron_path"
   noOpt=1
   optstr=":acdfghmrstuy"
   printf "Copying updated cron scripts...\n"
@@ -222,7 +252,7 @@ main() {
     case "$opt" in
       a )
         cp_finance_bu
-        cp_repo_backup
+        cp_git_bu
         cp_scriptarchive
         cp_empty_trash
         cp_clone_update
@@ -237,7 +267,7 @@ main() {
       f )
         cp_finance_bu ;;
       g )
-        cp_repo_backup ;;
+        cp_git_bu ;;
       h )
         help 0 ;;
       m )
@@ -254,11 +284,11 @@ main() {
         cp_zytdlpupdate ;;
       ? )
         printf "%s Invalid option -%s\n" "$RED_ERROR" "$OPTARG" >&2
-        help 2
+        help "$E_INVALID_ARG"
     esac
 	  noOpt=0
   done
-  [[ "$noOpt" = 1 ]] && { printf "%s No arguments passed.\n" "$RED_ERROR" >&2; help 1; }
+  [[ "$noOpt" = 1 ]] && { printf "%s No arguments passed.\n" "$RED_ERROR" >&2; help "$E_MISSING_ARG"; }
   shift "$(( OPTIND - 1 ))"
   over_line "$script $version"
   exit
