cronscripts: added return codes; correct process subsitutions;script & verions variables now local in main()

diff --git a/cronscripts b/cronscripts
--- a/cronscripts
+++ b/cronscripts
@@ -1,5 +1,5 @@
 #!/usr/bin/env bash
-##########################################################################
+###############################################################################
 # Script Name  : cronscripts
 # Description  : Copies cron scripts to the appropriate directories.
 # Dependencies : None
@@ -7,47 +7,44 @@
 # Author       : Copyright (C) 2022, Richard B. Romig, Mosfanet
 # Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
 # Crated       : 17 Feb 2022
-# Updated      : 03 May 2026
-# Comments     : For jobs needinng root access, checks if repo script is
-#              : newer than the one run by anacron/cron
+# Updated      : 04 Jul 2026
+# Comments     : Checks if the script in ~/bin/cronjobs is newer than the
+#              : script being run by anacron/cron
 # TODO (Rick)  :
 # License      : GNU General Public License, version 2.0
 # License URL  : https://github.com/RickRomig/scripts/blob/main/LICENSE
-##########################################################################
-# This program is free software; you can redistribute it and/or modify
-# it under the terms of the GNU General Public License as published by
-# the Free Software Foundation; either version 2 of the License, or
-# (at your option) any later version.
+###############################################################################
+# This program is free software; you can redistribute it and/or modify it under
+# the terms of the GNU General Public License as published by the Free Software
+# Foundation; either version 2 of the License, or (at your option) any later version.
 #
-# This program is distributed in the hope that it will be useful,
-# but WITHOUT ANY WARRANTY; without even the implied warranty of
-# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
-# GNU General Public License for more details.
-##########################################################################
+# This program is distributed in the hope that it will be useful, but WITHOUT
+# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
+# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
+###############################################################################
 
-## Load function library ##
+## Source function library ##
 # shellcheck source=/home/rick/bin/functionlib
-source functionlib || { printf "\e[91mERROR:\e[0m Unable to source functionlib\n"; exit 1; }
-
+source ~/bin/functionlib || { printf "\e[91mERROR:\e[0m Unable to source functionlib\n"; exit 1; }
 
 ## Global Variables ##
 
-readonly script="${0##*/}"
-readonly version="10.1.26123"
 localip="$(local_ip)"; readonly localip
 # path variables
 script_dir=$(dirname "$(readlink -f "${0}")"); readonly script_dir
 readonly job_dir="$script_dir/cronjobs"
 readonly files_dir="$script_dir/files"
 readonly user_cron_path="$HOME/.local/bin/"
-readonly opt_cron_path="/opt/bin/"
+readonly system_cron_path="/opt/bin/"
 readonly sed_path="/usr/share/misc/"
 
 ## Functions ##
 
 help() {
-  local errcode="${1:-1}"
-  local updated="03 May 2026"
+	local -r script="$1"
+	local -r version="$2"
+	local errcode="${3:-1}"
+	local updated="04 Jul 2026"
   cat << _HELP_
 ${orange}$script${normal} $version, Updated: $updated
 Copies cronjob scripts to the appropriate directories.
@@ -80,6 +77,7 @@ is_older() {
 no_copy() {
   local message="$1"
   printf "%s not applicable to this system and was not copied.\n" "$message"
+  return 0
 }
 
 cp_clone_update() {
@@ -87,19 +85,21 @@ cp_clone_update() {
     10|16|22 )
       no_copy "Cloned repository updates are" ;;
     * )
-      is_older "clone-update.sh" "$user_cron_path" && awk '{print "==> "$NF}' <(cp -pv "$job_dir/clone-update.sh" "$user_cron_path")
+      is_older "clone-update.sh" "$user_cron_path" && awk '{print "==> "$NF}' < <(cp -pv "$job_dir/clone-update.sh" "$user_cron_path")
   esac
+  return 0
 }
 
 cp_git_bu() {
   case "$localip" in
     10|16 )
-      is_older "git-dwm.sh" "$user_cron_path" && awk '{print "==> "$NF}' <(cp -pv "$job_dir/git-dwm.sh" "$user_cron_path")
-      is_older "git-bu.sh" "$user_cron_path" && awk '{print "==> "$NF}' <(cp -pv "$job_dir/git-bu.sh" "$user_cron_path")
+      is_older "git-dwm.sh" "$user_cron_path" && awk '{print "==> "$NF}' < <(cp -pv "$job_dir/git-dwm.sh" "$user_cron_path")
+      is_older "git-bu.sh" "$user_cron_path" && awk '{print "==> "$NF}' < <(cp -pv "$job_dir/git-bu.sh" "$user_cron_path")
       ;;
     * )
       no_copy "Repository archives are"
   esac
+  return 0
 }
 
 cp_main_bu() {
@@ -108,23 +108,25 @@ cp_main_bu() {
   case "$localip" in
   10 )
       for buscript in "${buscripts[@]}"; do
-        is_older "$buscript" "$user_cron_path" && awk '{print "==> "$NF}' <(cp -pv "$job_dir/$buscript" "$user_cron_path")
+        is_older "$buscript" "$user_cron_path" && awk '{print "==> "$NF}' < <(cp -pv "$job_dir/$buscript" "$user_cron_path")
       done
       ;;
     * )
       no_copy "Main system sync scripts are"
   esac
+  return 0
 }
 
 cp_finance_bu() {
   case "$localip" in
     10 )
-      is_older "fin-bu.sh" "$user_cron_path" &&  awk '{print "==> "$NF}' <(cp -pv "$job_dir/fin-bu.sh" "$user_cron_path")
-      is_older "hb-archive.sh" "$user_cron_path" && awk '{print "==> "$NF}' <(cp -pv "$job_dir/hb-archive.sh" "$user_cron_path")
+      is_older "fin-bu.sh" "$user_cron_path" &&  awk '{print "==> "$NF}' < <(cp -pv "$job_dir/fin-bu.sh" "$user_cron_path")
+      is_older "hb-archive.sh" "$user_cron_path" && awk '{print "==> "$NF}' < <(cp -pv "$job_dir/hb-archive.sh" "$user_cron_path")
       ;;
     * )
       no_copy "Finance archives are"
   esac
+  return 0
 }
 
 cp_scriptarchive() {
@@ -132,12 +134,14 @@ cp_scriptarchive() {
     17|21|22|24 )
       no_copy "scriptarchive.sh is" ;;
     * )
-      is_older "scriptarchive.sh" "$user_cron_path" && awk '{print "==> "$NF}' <(cp -pv "$job_dir/scriptarchive.sh" "$user_cron_path")
+      is_older "scriptarchive.sh" "$user_cron_path" && awk '{print "==> "$NF}' < <(cp -pv "$job_dir/scriptarchive.sh" "$user_cron_path")
   esac
+  return 0
 }
 
 cp_empty_trash() {
-  is_older "empty-trash.sh" "$user_cron_path" && awk '{print "==> "$NF}' <(cp -pv "$job_dir/empty-trash.sh" "$user_cron_path")
+  is_older "empty-trash.sh" "$user_cron_path" && awk '{print "==> "$NF}' < <(cp -pv "$job_dir/empty-trash.sh" "$user_cron_path")
+  return 0
 }
 
 cp_redshift_notify() {
@@ -145,8 +149,9 @@ cp_redshift_notify() {
     10|11|14|15|17|19|20|21 )
       no_copy "redshift-notify.sh is" ;;
     * )
-      is_older "redshift-notify.sh" "$user_cron_path" && awk '{print "==> "$NF}' <(cp -pv "$job_dir/redshift-notify.sh" "$user_cron_path")
+      is_older "redshift-notify.sh" "$user_cron_path" && awk '{print "==> "$NF}' < <(cp -pv "$job_dir/redshift-notify.sh" "$user_cron_path")
   esac
+  return 0
 }
 
 cp_zdefrag() {
@@ -155,25 +160,26 @@ cp_zdefrag() {
     10|12|13|14|15|17|19|20|21|22|23|24 )
       if [[ ! -f "$anacron_path/z-defrag" ]]; then
         sudo_login 1
-        awk '{print "==> "$NF}' <(sudo cp -v "$job_dir/z-defrag" "$anacron_path")
+        awk '{print "==> "$NF} <' <(sudo cp -v "$job_dir/z-defrag" "$anacron_path")
       elif is_older "z-defrag" "$anacron_path"; then
         sudo_login 1
-        awk '{print "==> "$NF}' <(sudo cp -v "$job_dir/z-defrag" "$anacron_path")
+        awk '{print "==> "$NF}' < <(sudo cp -v "$job_dir/z-defrag" "$anacron_path")
       fi
       ;;
     11|16 )
-      [[ -d "$opt_cron_path" ]] || { sudo_login 1; sudo mkdir -p "$opt_cron_path"; }
-      if [[ -f "$opt_cron_path/z-defrag" ]]; then
+      [[ -d "$system_cron_path" ]] || { sudo_login 1; sudo mkdir -p "$system_cron_path"; }
+      if [[ -f "$system_cron_path/z-defrag" ]]; then
         sudo_login 1
-        awk '{print "==> "$NF}' <(sudo cp -v "$job_dir/z-defrag" "$opt_cron_path")
-      elif is_older "z-defrag" "$opt_cron_path"; then
+        awk '{print "==> "$NF}' < <(sudo cp -v "$job_dir/z-defrag" "$system_cron_path")
+      elif is_older "z-defrag" "$system_cron_path"; then
         sudo_login 1
-        awk '{print "==> "$NF}' <(sudo cp -v "$job_dir/z-defrag" "$opt_cron_path")
+        awk '{print "==> "$NF}' < <(sudo cp -v "$job_dir/z-defrag" "$system_cron_path")
       fi
       ;;
     * )
       no_copy "z-defrag is"
   esac
+  return 0
 }
 
 cp_zupdate() {
@@ -183,30 +189,31 @@ cp_zupdate() {
     10|12|13|14|15|17|19|20|21|22|23|24|25 )
       if [[ -f "$anacron_path/z-update" ]]; then
         sudo_login 1
-        awk '{print "==> "$NF}' <(sudo cp -v "$job_dir/z-update" "$anacron_path")
+        awk '{print "==> "$NF}' < <(sudo cp -v "$job_dir/z-update" "$anacron_path")
       elif is_older "z-update" "$anacron_path"; then
         sudo_login 1
         awk '{print "==> "$NF}' <(sudo cp -v "$job_dir/z-update" "$anacron_path")
       fi
       ;;
     11|16 )
-      [[ -d "$opt_cron_path" ]] || { sudo_login 1; sudo mkdir -p "$opt_cron_path"; }
+      [[ -d "$system_cron_path" ]] || { sudo_login 1; sudo mkdir -p "$system_cron_path"; }
       if [[ -f "$sed_path/$sed_file" ]]; then
         sudo_login 1
-        awk '{print "==> "$NF}' <(sudo cp -v "$job_dir/z-update" "$opt_cron_path")
-      elif is_older "z-update" "$opt_cron_path"; then
+        awk '{print "==> "$NF}' < <(sudo cp -v "$job_dir/z-update" "$system_cron_path")
+      elif is_older "z-update" "$system_cron_path"; then
         sudo_login 1
-        awk '{print "==> "$NF}' <(sudo cp -v "$job_dir/z-update" "$opt_cron_path")
+        awk '{print "==> "$NF}' < <(sudo cp -v "$job_dir/z-update" "$system_cron_path")
       fi
       ;;
   esac
-  if [[ -f "$sed_path/$sed_file" ]]; then
+  if [[ ! -f "$sed_path/$sed_file" ]]; then
     sudo_login 1
-    awk '{print "==> "$NF}' <(sudo cp -v "$files_dir/$sed_file" "$sed_path")
+    awk '{print "==> "$NF}' < <(sudo cp -v "$files_dir/$sed_file" "$sed_path")
   elif [[ "$sed_path/$sed_file" -ot "$files_dir/$sed_file" ]]; then
     sudo_login 1
-    awk '{print "==> "$NF}' <(sudo cp -v "$files_dir/$sed_file" "$sed_path")
+    awk '{print "==> "$NF}' < <(sudo cp -v "$files_dir/$sed_file" "$sed_path")
   fi
+  return 0
 }
 
 cp_zytdlpupdate() {
@@ -214,31 +221,28 @@ cp_zytdlpupdate() {
   local -r anacron_path="/etc/cron.daily/"
   case "$localip" in
     10|15|17 )
-      if [[ -f "$anacron_path/z-ytdlp-update" ]]; then
+      if [[ ! -f "$anacron_path/z-ytdlp-update" ]]; then
         sudo_login 1
-        awk '{print "==> "$NF}' <(sudo cp -v "$job_dir/z-ytdlp-update" "$anacron_path")
+        awk '{print "==> "$NF}' < <(sudo cp -v "$job_dir/z-ytdlp-update" "$anacron_path")
       elif is_older "z-ytdlp-update" "$anacron_path"; then
         sudo_login 1
-        awk '{print "==> "$NF}' <(sudo cp -v "$job_dir/z-ytdlp-update" "$anacron_path")
+        awk '{print "==> "$NF}' < <(sudo cp -v "$job_dir/z-ytdlp-update" "$anacron_path")
       fi
-      # if [[ -f "$sed_path/$sed_file" ]]; then
-      #   sudo_login 1
-      #   awk '{print "==> "$NF}' <(sudo cp -v "$files_dir/$sed_file" "$sed_path")
-      # elif [[ "$sed_path/$sed_file" -ot "$files_dir/$sed_file" ]]; then
-      #   sudo_login 1
-      #   awk '{print "==> "$NF}' <(sudo cp -v "$files_dir/$sed_file" "$sed_path")
-      # fi
       ;;
     * )
       no_copy "z-ytdlp-update is"
   esac
+  return 0
 }
 
 main() {
-  local noOpt opt optstr OPTARG OPTIND
+	local -r script="${0##*/}"
+	local -r version="10.2.26185"
+	local exit_code=0
+  local opt OPTARG OPTIND
   [[ -d "$user_cron_path" ]] || mkdir -p "$user_cron_path"
-  noOpt=1
-  optstr=":acdfghmrstuy"
+  local -i noOpt=1
+  local -r optstr=":acdfghmrstuy"
   printf "Copying updated cron scripts...\n"
   while getopts "$optstr" opt; do
     case "$opt" in
@@ -252,38 +256,28 @@ main() {
         cp_zdefrag
         cp_zytdlpupdate
         ;;
-      c )
-        cp_clone_update ;;
-      d )
-        cp_zdefrag ;;
-      f )
-        cp_finance_bu ;;
-      g )
-        cp_git_bu ;;
-      h )
-        help 0 ;;
-      m )
-        cp_main_bu ;;
-      r )
-        cp_redshift_notify ;;
-      s )
-        cp_scriptarchive ;;
-      t )
-        cp_empty_trash ;;
-      u )
-        cp_zupdate ;;
-      y )
-        cp_zytdlpupdate ;;
+      c ) cp_clone_update ;;
+      d ) cp_zdefrag ;;
+      f ) cp_finance_bu ;;
+      g ) cp_git_bu ;;
+      h ) help "$script" "$version" 0 ;;
+      m ) cp_main_bu ;;
+      r ) cp_redshift_notify ;;
+      s ) cp_scriptarchive ;;
+      t ) cp_empty_trash ;;
+      u ) cp_zupdate ;;
+      y ) cp_zytdlpupdate ;;
       ? )
         printf "%s Invalid option -%s\n" "$RED_ERROR" "$OPTARG" >&2
-        help "$E_INVALID_ARG"
+        help "$script" "$version" "$E_INVALID_ARG"
     esac
+    exit_code="$?"
 	  noOpt=0
   done
-  [[ "$noOpt" = 1 ]] && { printf "%s No arguments passed.\n" "$RED_ERROR" >&2; help "$E_MISSING_ARG"; }
+  [[ "$noOpt" = 1 ]] && { printf "%s No arguments passed.\n" "$RED_ERROR" >&2; help "$script" "$version" "$E_MISSING_ARG"; }
   shift "$(( OPTIND - 1 ))"
   over_line "$script $version"
-  exit
+  exit "$exit_code"
 }
 
 ## Execution ##
