dl-webpage: sourced functionlib.bash; added check_arguments()

diff --git a/dl-webpage b/dl-webpage
--- a/dl-webpage
+++ b/dl-webpage
@@ -1,5 +1,5 @@
 #!/usr/bin/env bash
-#############################################################################
+##############################################################################
 # Script Name  : dl-webpage
 # Description  : Downloads a page from the web to the current directory.
 # Dependencies : wget
@@ -7,38 +7,31 @@
 # Author       : Copyright (C) 2019, Richard B. Romig, 02 Nov 2019
 # Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
 # Created      : 02 Nov 2019
-# Updated      : 05 May 2026
-# Comments     :
-# TODO (Rick)  : Array of wget exit codes
+# Updated      : 06 Aug 2026
+# Version      : 2.2.26218
+# Comments     : Appears to function, but haven't been able to download a page.'
+# TODO (Rick)  :
 # License      : GNU General Public License, version 2.0
 # License URL  : https://github.com/RickRomig/scripts/blob/main/LICENSE
-##########################################################################
-# This program is free software; you can redistribute it and/or modify
-# it under the terms of the GNU General Public License as published by
-# the Free Software Foundation; either version 2 of the License, or
-# (at your option) any later version.
+##############################################################################
+# This program is free software; you can redistribute it and/or modify it under
+# the terms of the GNU General Public License as published by the Free Software
+# Foundation; either version 2 of the License, or (at your option) any later
+# version.
 #
-# This program is distributed in the hope that it will be useful,
-# but WITHOUT ANY WARRANTY; without even the implied warranty of
-# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
-# GNU General Public License for more details.
-#############################################################################
+# This program is distributed in the hope that it will be useful, but WITHOUT
+# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
+# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
+###############################################################################
 
-## Load function library ##
-# shellcheck source=/home/rick/bin/functionlib
-source functionlib || { printf "\e[91mERROR:\e[0m Unable to source functionlib\n"; exit 1; }
-
-## Global Variables ##
-
-readonly script="${0##*/}"
-readonly version="2.4.26125"
-EC=0
-
-## Functions ##
+# shellcheck source=/home/rick/bin/functionlib.bash
+source ~/bin/functionlib.bash || { printf "\e[91mERROR:\e[0m Unable to source functionlib.bash\n"; exit 1; }
 
 help() {
-  local errcode="${1:-1}"
-  local updated="05 May 2026"
+  local -r script="$1"
+  local -r version="$2"
+  local -ri errcode="${3:-1}"
+  local -r updated="05 May 2026"
   cat << _HELP_
 ${orange}$script${normal} $version, Updated: $updated
 Downloads a web page to the current directory.
@@ -53,16 +46,18 @@ _HELP_
 
 download_page() {
   local -r url="$1"
-  local domain
+  local domain status
   domain=$(sed 's|^[^/]*//||; s|^www\.||; s|/.*$||' <<< "$url")
   printf "Downloading %s to %s\n" "$url" "$PWD"
   wget --quiet --recursive --page-requisites --html-extension --convert-links --restrict-file-names=windows --domains "$domain" --no-parent "$url"
-  EC="$?"
-  print_status
+  status="$?"
+  print_status "$status"
+  return "$status"
 }
 
 print_status() {
-  exitcodes=(
+  local -r status="$1"
+  local -ra exit_codes=(
     "No problems occurred"
     "Generic error code"
     "Parse error"
@@ -73,34 +68,42 @@ print_status() {
     "Protocol errors"
     "Server issued an error response"
   )
-  if [[ "$EC" -eq 0 ]]; then
+  if [[ "$status" -eq 0 ]]; then
     printf "Page succesfully downloaded.\n"
   else
-    printf "Download failed with exit code: %s.\n" "$EC"
-    printf "Error: %s\n" "${exitcodes[EC]}"
+    printf "Download failed with exit code: %s.\n" "$status"
+    printf "Error: %s\n" "${exit_codes[status]}"
+  fi
+  return "$status"
+}
+
+check_arguments() {
+  local re="^https?:\/\/.*"
+  local url
+  if [[ "$#" -eq 0 ]]; then
+    printf "%s No argument passed.\n" "$RED_ERROR" >&2
+    help "$script" "$version" "$E_MISSING_ARG"
+  elif [[ "$1" = "--help" || "$1" = "-h" ]]; then
+    help "$script" "$version" 0
+  elif [[ $1 =~ $re ]]; then
+    url="$*"
+    download_page "$url"
+    return "$?"
+  else
+    printf "%s Invalid argument - %s\n" "$RED_ERROR" "$1" >&2
+    help "$script" "$version" "$E_INVALID_ARG"
   fi
 }
 
 main() {
-  local url
-  local re="^https?:\/\/.*"
+  local -r script="${0##*/}"
+  local -r version="2.4.26125"
+  local -i exit_code=0
   check_package wget
-  if [[ "$#" -eq 0 ]]; then
-    printf "%s No argument passed.\n" "$RED_ERROR" >&2
-    help "$E_MISSING_ARG"
-  elif [[ "$1" = "--help" || "$1" = "-h" ]]; then
-    help 0
-  elif [[ $1 =~ $re ]]; then
-    url="$*"
-    download_page "$url"
-    over_line "$script $version"
-    exit "$EC"
-  else
-    printf "%s Invalid argument - %s\n" "$RED_ERROR" "$1" >&2
-    help "$E_INVALID_ARG"
-  fi
+  check_arguments "$@"
+  exit_code="$?"
+  over_line "$script $version"
+  exit "$exit_code"
 }
-
-## Execution ##
 
 main "$@"
