functionlib: valid_ip(): changed line 457.

diff --git a/functionlib b/functionlib
--- a/functionlib
+++ b/functionlib
@@ -454,7 +454,7 @@ valid_ip() {
       # Valid address - test if reachable or local machine
       if [[ "$localip" -eq "$octet" ]]; then
         status=2
-        printf "%s %s.%s is the local client computer.\n" "$RED_ERROR" "$LOCALNET" "$octet" >&2
+        printf "%s %s.%s is the local client.\n" "$RED_ERROR" "$LOCALNET" "$octet" >&2
       elif ping -c 1 "$LOCALNET.$octet" > /dev/null 2>&1; then
         status=0
         printf "%s.%s is a valid and reachable IP address.\n" "$LOCALNET" "$octet"
