functionlib: added error code to die() & dielog();process substitution to line and box functions

diff --git a/functionlib b/functionlib
--- a/functionlib
+++ b/functionlib
@@ -103,7 +103,7 @@ DEFAULT=$(echo -en "\e[49m")
 die() {
   local -r errmsg="${1:-You screwed up}"
   local -r errcode="${2:-1}"
-  printf "\e[91mERROR:\e[0m %s\n" "$errmsg" >&2
+  printf "\e[91mERROR:\e[0m %s ($errcode)\n" "$errmsg" >&2
   exit "$errcode"
 }
 
@@ -131,7 +131,7 @@ dielog() {
   local message="${1:-You screwed up}"
   local log_file="$2"
   local err_code="${3:-1}"
-  printf "%(%F %R)T: \e[91mERROR:\e[0m %s\n" -1 "$message" | tee -a "$log_file"
+  printf "%(%F %R)T: \e[91mERROR:\e[0m %s (%s)\n" -1 "$message" "$err_code" | tee -a "$log_file"
   exit "$err_code"
 }
 
@@ -581,7 +581,7 @@ print_line() {
   [[ "$width" ]] || width=$(tput cols)
   len=${#char}
   (( len > 1 )) && char=${char::1}
-  printf "%${width}s\n" | sed "s/ /$char/g"
+  sed "s/ /$char/g" <(printf "%${width}s\n")
 }
 
 ###############################################################################
@@ -601,7 +601,7 @@ box() {
   len=${#char}
   (( len > 1 )) && char=${char::1}
   title="$char $1 $char"
-  edge=$(echo "$title" | sed "s/./$char/g")
+  edge=$(sed "s/./$char/g" <(echo "$title"))
   printf "%s\n%s\n%s\n" "$edge" "$title" "$edge"
 }
 
@@ -622,7 +622,7 @@ under_line() {
   char="${2:--}"
   len=${#char}
   (( len > 1 )) && char=${char::1}
-  line=$(echo "$title" | sed "s/./$char/g")
+  line=$(sed "s/./$char/g" <(echo "$title"))
   printf "%s\n%s\n" "$title" "$line"
 }
 
@@ -643,7 +643,7 @@ over_line() {
   char="${2:--}"
   len=${#char}
   (( len > 1 )) && char=${char::1}
-  line=$(echo "$title" | sed "s/./$char/g")
+  line=$(sed "s/./$char/g" <(echo "$title"))
   printf "%s\n%s\n"  "$line" "$title"
 }
 
