functionlib: updated function comments

diff --git a/functionlib b/functionlib
--- a/functionlib
+++ b/functionlib
@@ -7,7 +7,7 @@
 # Author       : Copyright (C) 2019, Richard B. Romig, Mosfanet
 # Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
 # Created      : 21 Sep 2019
-# Last updated : 24 Aug 2025
+# Last updated : 04 Sep 2025
 # Comments     : source into the current shell environment by entering at the beginning of the script:
 #              : # shellcheck source=/home/rick/bin/functionlib.
 #              : # shellcheck disable=SC1091  # not necessary if using shellcheck -x to run shelllcheck
@@ -193,7 +193,7 @@ user_exists() {
 # Purpose: Prompts for user password if user is in the sudo group.
 # If user is not in the sudo group, displays error message and exits.
 # Argument:
-#   $1 -> number or seconds to sleep before blanking the prompt line. If delay is 0, blanking line is skippped.
+#   $1 -> number of seconds to sleep before blanking the prompt line. If delay is 0, blanking line is skippped.
 ###############################################################################
 sudo_login() {
   local delay="${1:-2}"
@@ -206,7 +206,7 @@ sudo_login() {
       fi
     fi
  else
-    diehard "$USER is not a member of the sudo group. Access denied." "This incident will be reported to Big Brother."
+    die "$USER is not a member of the sudo group. Access denied."
   fi
 }
 
@@ -222,7 +222,7 @@ bin_in_path() {
 
 ###############################################################################
 # exists
-# Purpose: Returns true if command/program is installed.
+# Purpose: Returns true if command/program is in the user's path.
 # Argument:
 #   $1 -> command/program to be checked.
 # Returns: True or False
@@ -233,7 +233,7 @@ exists() {
 
 ###############################################################################
 # get_distribution
-# Purpose: Sets global variable 'distro' to the full name of the current distribution.
+# Purpose: Prints the full name of the current distribution.
 # Arguments: none
 ###############################################################################
 get_distribution() {
@@ -258,8 +258,7 @@ is_debian() {
   codename=$(/usr/bin/lsb_release --codename --short | awk 'NR = 1 {print $0}')
   case "$codename" in
     trixie|bookworm|bullseye|faye|boron )
-      return "$TRUE"
-    ;;
+      return "$TRUE" ;;
     * )
       return "$FALSE"
   esac
@@ -298,8 +297,7 @@ support_ppa() {
   codename=$(/usr/bin/lsb_release --codename --short)
   case "$codename" in
     jammy|noble|vanessa|vera|victoria|virginia|wilma|xia )
-      return "$TRUE"
-    ;;
+      return "$TRUE" ;;
     * )
       return "$FALSE"
   esac
@@ -511,7 +509,7 @@ edit_view_quit() {
       1 )
         $EDITOR "$filename" || /usr/bin/nano "$filename"
         break
-      ;;
+        ;;
       2 )
         if exists batcat; then
           "$HOME"/.local/bin/bat "$filename"
@@ -521,11 +519,11 @@ edit_view_quit() {
           viewtext "$filename"
         fi
         break
-      ;;
+        ;;
       3 )
         printf "\nExiting.\n"
         break
-      ;;
+        ;;
       * )
         printf "%sInvalid choice. Try again.%s\n" "$orange" "$normal" >&2
     esac
@@ -653,7 +651,7 @@ over_line() {
 # center_file
 # Purpose: Display the contents of a text file centered.
 # Argument:
-#   $1 => a text file
+#   $1 -> a text file
 # Ouput: File contents displayed with lines centered.
 ###############################################################################
 center_file() {
@@ -668,7 +666,7 @@ center_file() {
 # center_text
 # Purpose: Display a string of text centered.
 # Argument:
-#  $1 => a string of text
+#  $1 -> a string of text
 # String displayed with lines centered.
 ###############################################################################
 center_text() {
@@ -945,7 +943,7 @@ dots() {
   char="${1:-.}"
   len="${#char}"
   (( len > 1 )) && char=${char::1}  # takes the firt character.
-  tput civis  # rempves cursor
+  tput civis  # removes cursor
   while true; do echo -n "."; sleep 0.5; done &
 }
 
@@ -964,14 +962,11 @@ y_or_n() {
     read -rp "$yn_prompt [y/n] " yn
     case "$yn" in
       [Yy]* )
-        return "$TRUE"
-      ;;
+        return "$TRUE" ;;
       [Nn]* )
-        return "$FALSE"
-      ;;
+        return "$FALSE" ;;
       '' )
-        printf "%s Response required -- try again.\n" "$RED_WARNING" >&2
-      ;;
+        printf "%s Response required -- try again.\n" "$RED_WARNING" >&2 ;;
       * )
         printf "%s Invalid choice. Enter y or n.\n" "$RED_ERROR" >&2
     esac
@@ -993,14 +988,11 @@ yes_or_no() {
     read -rp "$yn_prompt [yes/no] " yn
     case "${yn,,}" in
       yes )
-        return "$TRUE"
-      ;;
+        return "$TRUE" ;;
       no )
-        return "$FALSE"
-      ;;
+        return "$FALSE" ;;
       '' )
-        printf "%s Response required -- try again.\n" "$RED_WARNING" >&2
-      ;;
+        printf "%s Response required -- try again.\n" "$RED_WARNING" >&2 ;;
       * )
         printf "%s Invalid choice. Enter yes or no.\n" "$RED_ERROR" >&2
     esac
@@ -1022,11 +1014,9 @@ default_yes() {
     read -rp "$yn_prompt [Y/n] " yn
     case "$yn" in
       [Yy]*|'' )
-        return "$TRUE"
-      ;;
+        return "$TRUE" ;;
       [Nn]* )
-        return "$FALSE"
-      ;;
+        return "$FALSE" ;;
       * )
         printf "%s Invalid choice. Enter y or n.\n" "$RED_ERROR" >&2
     esac
@@ -1048,11 +1038,9 @@ default_no() {
     read -rp "$yn_prompt [y/N] " yn
     case "$yn" in
       [Yy]* )
-        return "$TRUE"
-      ;;
+        return "$TRUE" ;;
       [Nn]*|'' )
-        return "$FALSE"
-      ;;
+        return "$FALSE" ;;
       * )
         printf "%s Invalid choice. Enter y or n.\n" "$RED_ERROR" >&2
     esac
