functionlib: added assign_cfg_repo() for use in installation scripts.

diff --git a/functionlib b/functionlib
--- a/functionlib
+++ b/functionlib
@@ -7,7 +7,7 @@
 # Author       : Copyright (C) 2019, Richard B. Romig, Mosfanet
 # Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
 # Created      : 21 Sep 2019
-# Last updated : 25 Apr 2025
+# Last updated : 03 May 2025
 # Comments     : source into the current shell environment by entering at the beginning of the script:
 #              : # shellcheck source=/home/rick/bin/functionlib.
 #              : # shellcheck disable=SC1091  # not necessary if using shellcheck -x to run shelllcheck
@@ -857,6 +857,33 @@ clone_repo() {
       url="$GITEA_URL"
   esac
   git clone "$url/${git_repo}.git" "$HOME/Downloads/$git_repo"
+}
+
+###############################################################################
+# assign_cfg_repo
+# Purpose: assign repoitory directiory for install scripts
+# Argument: None
+# Output: path of repository or cloned repository
+###############################################################################
+
+assign_cfg_repo() {
+	local localip repo_dir
+	localip=$(local_ip)
+	repo_dir="$HOME/Downloads/configs"
+	case "$localip" in
+		10|16|22 )
+			repo_dir="$HOME/gitea/configs" ;;
+		* )
+			if [[ -d "$repo_dir" ]]; then
+				pushd "$repo_dir" || die "pushd failed"
+				git pull
+				popd || die "popd failed"
+			else
+				git clone "$GITHUB_URL/configs.git" "$repo_dir/configs"
+			fi
+			# repo="$repo_dir"
+	esac
+	printf "%s" "$repo_dir"
 }
 
 ###############################################################################
