functionlib - updated comments in the yes/no functions and change default response to y or n where an explicit yes or no is not required.

diff --git a/functionlib b/functionlib
--- a/functionlib
+++ b/functionlib
@@ -9,7 +9,7 @@
 # Comments     : source into the current shell environment by entering:
 # . /home/rick/bin/functionlib or . functionlib or source "$HOME/bin/functionlib"
 # Environmental variables like $HOME or $USER cannot be used with the . alias.
-# Last updated : 26 Sep 2023
+# Last updated : 01 Oct 2023
 # License      : GNU General Public License, version 2.0
 ###############################################################################
 ## Shellcheck Directives ##
@@ -758,7 +758,7 @@ y_or_n() {
         printf "%s Response required -- try again.\n" "$red_warning" >&2
       ;;
       * )
-        printf "%s Invalid choice. Enter yes or no.\n" "$red_error" >&2
+        printf "%s Invalid choice. Enter y or n.\n" "$red_error" >&2
     esac
   done
 }
@@ -791,7 +791,7 @@ yes_or_no() {
 
 ###############################################################################
 # default_yes
-# Purpose: Displays a yes or no prompt (Y|n), defaulsts to yes. 
+# Purpose: Displays a yes or no prompt (Y|n), defaulsts to yes if pressing Enter. 
 # Arguement: A string requiring a yes or no response.
 # Returns: True or False
 # Example: yes_or_no "Question" && do_something || do_something_else
@@ -807,14 +807,14 @@ default_yes() {
         return "$FALSE"
       ;;
       * )
-        printf "%s Invalid choice. Enter yes or no.\n" "$red_error" >&2
+        printf "%s Invalid choice. Enter y or n.\n" "$red_error" >&2
     esac
   done
 }
 
 ###############################################################################
 # default_no
-# Purpose: Displays a yes or no prompt (y|N), defaults to no. 
+# Purpose: Displays a yes or no prompt (y|N), defaults to no if pressing Enter. 
 # Arguement: A string requiring a yes or no response.
 # Returns: True or False
 # Example: yes_or_no "Question" && do_something || do_something_else
@@ -830,7 +830,7 @@ default_no() {
         return "$FALSE"
       ;;
       * )
-        printf "%s Invalid choice. Enter yes or no.\n" "$red_error" >&2
+        printf "%s Invalid choice. Enter y or n.\n" "$red_error" >&2
     esac
   done
 }
