functionlib - added is_url_good() to check if a URL is accessible.

diff --git a/functionlib b/functionlib
--- a/functionlib
+++ b/functionlib
@@ -451,28 +451,28 @@ valid_ip() {
   localip="$(local_ip)"
   if [[ -z "$octet" ]]; then
     status=1
-    printf "%s No argument passed. No host IP.\nEnter the last octet of the target IP address (1 - 254).\n" "$red_error" >&2
+    printf "%s No argument passed. No host IP.\nEnter the last octet of the target IP address (1 - 254).\n" "$RED_ERROR" >&2
   elif [[ "$1" =~ ^[0-9]+$ ]] 2>/dev/null; then
     # Argument is an integer value
     if (( octet > 0 )) && (( octet < 255 )); then
       # Valid address - test if reachable or local machine
       if [[ "$localip" -eq "$octet" ]]; then
         status=2
-        printf "%s %s.%s is the local client computer.\n" "$red_error" "$localnet" "$octet" >&2
+        printf "%s %s.%s is the local client computer.\n" "$RED_ERROR" "$localnet" "$octet" >&2
       elif ping -c 1 "$localnet.$octet" > /dev/null 2>&1; then
         status=0
         printf "%s.%s is a valid and reachable IP address.\n" "$localnet" "$octet"
       else
         status=3
-        printf "%s %s.%s is valid IP address but is unreachable.\nCheck to see if it is on the network.\n" "$red_error" "$localnet" "$octet" >&2
+        printf "%s %s.%s is valid IP address but is unreachable.\nCheck to see if it is on the network.\n" "$RED_ERROR" "$localnet" "$octet" >&2
       fi
     else
       status=4
-      printf "%s %s.%s is not a valid IP address.\nEnter the last octet of the target IP address (1 - 254).\n" "$red_error" "$localnet" "$octet" >&2
+      printf "%s %s.%s is not a valid IP address.\nEnter the last octet of the target IP address (1 - 254).\n" "$RED_ERROR" "$localnet" "$octet" >&2
     fi
   else
     status=5
-    printf "%s Invalid argument: %s\nEnter the last octet of the target IP address (1 - 254).\n" "$red_error" "$octet" >&2
+    printf "%s Invalid argument: %s\nEnter the last octet of the target IP address (1 - 254).\n" "$RED_ERROR" "$octet" >&2
   fi
 
   (( status == 0 )) && return "$status" || exit "$status"
@@ -892,10 +892,10 @@ y_or_n() {
         return "$FALSE"
       ;;
       '' )
-        printf "%s Response required -- try again.\n" "$red_warning" >&2
+        printf "%s Response required -- try again.\n" "$RED_WARNING" >&2
       ;;
       * )
-        printf "%s Invalid choice. Enter y or n.\n" "$red_error" >&2
+        printf "%s Invalid choice. Enter y or n.\n" "$RED_ERROR" >&2
     esac
   done
 }
@@ -921,10 +921,10 @@ yes_or_no() {
         return "$FALSE"
       ;;
       '' )
-        printf "%s Response required -- try again.\n" "$red_warning" >&2
+        printf "%s Response required -- try again.\n" "$RED_WARNING" >&2
       ;;
       * )
-        printf "%s Invalid choice. Enter yes or no.\n" "$red_error" >&2
+        printf "%s Invalid choice. Enter yes or no.\n" "$RED_ERROR" >&2
     esac
   done
 }
@@ -950,7 +950,7 @@ default_yes() {
         return "$FALSE"
       ;;
       * )
-        printf "%s Invalid choice. Enter y or n.\n" "$red_error" >&2
+        printf "%s Invalid choice. Enter y or n.\n" "$RED_ERROR" >&2
     esac
   done
 }
@@ -976,7 +976,19 @@ default_no() {
         return "$FALSE"
       ;;
       * )
-        printf "%s Invalid choice. Enter y or n.\n" "$red_error" >&2
+        printf "%s Invalid choice. Enter y or n.\n" "$RED_ERROR" >&2
     esac
   done
+}
+
+###############################################################################
+# is_url_good
+# Purpose: Returns true if URL is accessible
+# Argument:
+# $1 -> URL to be checked
+# Returns: True or False
+###############################################################################
+is_url_good() {
+  local url="$1"
+  wget --spider -q "$url" && return "$TRUE" || return "$FALSE"
 }
