grevert - incorporated main(); added check if main directory of a git repo, created git_revert()

diff --git a/grevert b/grevert
--- a/grevert
+++ b/grevert
@@ -7,21 +7,42 @@
 # Author       : Copyright © 2024 Richard B. Romig, Mosfanet
 # Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
 # Created      : 19 May 2024
-# Last updated : 03 Aug 2024
+# Last updated : 10 Oct 2024
 # Comments     :
 # TODO (Rick)  :
 # License      : GNU General Public License, version 2.0
 ##########################################################################
 
+## Shellcheck Directives ##
+# shellcheck source=/home/rick/bin/functionlib
+
+## Source function library ##
+
+if [[ -x "$HOME/bin/functionlib" ]]; then
+  source "$HOME/bin/functionlib"
+else
+  printf "\e[91mERROR:\e[0m functionlib not found!\n" >&2
+  exit 1
+fi
+
 set -eu
 
-_script=$(basename "$0"); readonly _script
-readonly _version="1.2.24216"
+git_revert() {
+	local hash
+	printf "Reverting the most recent pushed commit to the previous version.\n"
+	hash=$(git log --oneline | head -n 1 | cut -d' ' -f1)
+	git revert "$hash" --no-edit
+	git log --oneline | head -n 2
+	git push
+}
 
-printf "Reverting the most recent commit to the previous version.\n"
-hash=$(git log --oneline | head -n 1 | cut -d' ' -f1)
-git revert "$hash" --no-edit
-git log --oneline | head -n 2
-git push
-echo "$_script v$_version"
-exit
+main() {
+	local script version
+	script=$(basename "$0")
+	version="2.0.24284"
+	[[ -d "$PWD/.git" ]] || die "You are not in the main directory of a git repositiory." 1
+	git_revert
+	leave "$script v$version"
+}
+
+main "$@"
