hidpp-battery: updated return codes and local variables; no argument calls help and exits with error

diff --git a/hidpp-battery b/hidpp-battery
--- a/hidpp-battery
+++ b/hidpp-battery
@@ -7,8 +7,8 @@
 # Author       : Copyright © 2023 Richard B. Romig, Mosfanet
 # Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
 # Created      : 23 Sep 2023
-# Updated      : 07 Aug 2026
-# Version      : 1.10.26219"
+# Updated      : 22 Aug 2026
+# Version      : 1.11.26234"
 # Comments     : Defaults to using /sys/class/power_supply
 # TODO (Rick)  :
 # License      : GNU General Public License, version 2.0
@@ -30,8 +30,8 @@ source ~/bin/functionlib.bash || { printf "\e[91mERROR:\e[0m Unable to source fu
 help() {
 	local -r script="$1"
 	local -r version="$2"
-	local errcode="${3:-1}"
-	local updated="07 Aug 2026"
+	local -ri errcode="${3:-1}"
+	local -r updated="07 Aug 2026"
 	cat << _HELP_
 ${orange}$script${normal} $version, Upated: $updated
 Displays HIDPP battery status.
@@ -50,8 +50,8 @@ sys_class_data() {
   local hidpp_path device brand model charge serial
   for hidpp_path in /sys/class/power_supply/hidpp_battery_?; do
     if [[ "$hidpp_path" == "/sys/class/power_supply/hidpp_battery_?" ]]; then
-      printf "HID++ battery not present.\n"
-			return 0
+      printf "HID++ battery not present.\n" >&2
+			return "$E_NOT_DETECTED"
     fi
 		device="${hidpp_path##*/}"
 		brand=$(< "$hidpp_path/manufacturer")
@@ -69,7 +69,7 @@ upower_data() {
 	check_package upower
 	if ! grep -q hidpp <(/usr/bin/upower -e); then
 	  printf "HID++ battery not present.\n"
-		return 0
+		return "$E_NOT_DETECTED"
 	fi
 	local hidpp_data
 	hidpp_data=$(/usr/bin/upower -i "$(grep hidpp <(/usr/bin/upower -e))")
@@ -84,7 +84,7 @@ upower_data() {
 main() {
 	local -r script="${0##*/}"
 	local -r version="1.10.26219"
-	local exit_code=0
+	local -i exit_code=0
 	local opt OPTARG OPTIND
 	local -i noOpt=1
 	local -r optstr=":hsu"
@@ -100,7 +100,10 @@ main() {
 		exit_code="$?"
 		noOpt=0
 	done
-	[[ "$noOpt" = 1 ]] && sys_class_data
+	if (( noOpt == 1 )); then
+		printf "%s No argument passed.\n" "$RED_ERROR" >&2
+		help "$script" "$version" "$E_MISSING_ARG"
+	fi
 	shift "$(( OPTIND - 1 ))"
 	over_line "$script $version"
 	exit "$exit_code"
