hidpp-battery - incorporated main()

diff --git a/hidpp-battery b/hidpp-battery
--- a/hidpp-battery
+++ b/hidpp-battery
@@ -7,7 +7,7 @@
 # Author       : Copyright © 2023 Richard B. Romig, Mosfanet
 # Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
 # Created      : 23 Sep 2023
-# Last updated : 14 Jun 2024
+# Last updated : 10 Oct 2024
 # Comments     : Defaults to using /sys/class/power_supply
 # TODO (Rick)  :
 # License      : GNU General Public License, version 2.0
@@ -27,26 +27,27 @@ fi
 
 ## Global Variables ##
 
-_script=$(basename "$0"); readonly _script
-readonly _version="1.2.24183"
-readonly _updated="14 Jun 2024"
+script=$(basename "$0"); readonly script
+readonly version="1.3.24284"
 
 ## Functions ##
 
 help() {
+	local errcode updated
 	errcode="${1:-2}"
-	cat << END_HELP
-${orange}$_script${normal} $_version, Upated: $_updated
+	updated="10 Oct 2024"
+	cat << _HELP_
+${orange}$script${normal} $version, Upated: $updated
 Displays HIDPP battery status.
 
-${green}Usage:${normal} $_script [OPTION]
+${green}Usage:${normal} $script [OPTION]
 
 ${orange}Available options:${normal}
 	-h	Display help
 	-s	HID++ battery status using /sys/class/power_supply
 	-u	HID++ battery status using upower utility
 	Defaults to using /sys/class/power_supply if no argument passed.
-END_HELP
+_HELP_
   exit "$errcode"
 }
 
@@ -77,27 +78,32 @@ upower_data() {
 	fi
 }
 
+main() {
+	local noOpt optstr opt
+	noOpt=1
+	optstr=":hsu"
+	while getopts "$optstr" opt; do
+		case "$opt" in
+			h )
+				help 0
+			;;
+			s )
+				sys_class_data
+			;;
+			u )
+				upower_data
+			;;
+			? )
+				printf "%s Invalid option -%s\n" "$RED_ERROR" "$OPTARG" >&2
+				help 2
+		esac
+		noOpt=0
+	done
+	[[ "$noOpt" = 1 ]] && sys_class_data
+	shift "$(( OPTIND - 1 ))"
+	leave "$script v$version"
+}
+
 ## Execution ##
 
-noOpt=1
-optstr=":hsu"
-while getopts "$optstr" opt; do
-	case "$opt" in
-		h )
-			help 0
-		;;
-		s )
-			sys_class_data
-		;;
-		u )
-			upower_data
-		;;
-		? )
-			printf "%s Invalid option -%s\n" "$red_error" "$OPTARG" >&2
-			help 2
-	esac
-	noOpt=0
-done
-[[ "$noOpt" = 1 ]] && sys_class_data
-shift "$(( OPTIND - 1 ))"
-leave "$_script v$_version"
+main "$@"
