i3configs - incorporated main(); moved checks for i3 and curl to check_dependencies()

diff --git a/i3configs b/i3configs
--- a/i3configs
+++ b/i3configs
@@ -7,7 +7,7 @@
 # Author       : Copyright © 2023 Richard B. Romig, Mosfanet
 # Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
 # Created      : 18 Apr 2023
-# Updated      : 15 Jun 2024
+# Updated      : 10 Oct 2024
 # Comments     : Assumes i3wm, polybar, rofi, dunst have been previously installed
 # TODO (Rick)  :
 # License      : GNU General Public License, version 2.0
@@ -27,9 +27,8 @@ fi
 
 ## Global Variables ##
 
-_script=$(basename "$0"); readonly _script
-readonly _version="3.2.24167"
-readonly _updated="15 Jun 2024"
+script=$(basename "$0"); readonly script
+readonly version="3.3.24284"
 readonly repository="configs/raw/branch/main/"
 readonly local_repo="$HOME/gitea/configs"
 readonly config_dir="$HOME/.config"
@@ -38,12 +37,14 @@ localip="$(local_ip)"; readonly localip
 ## Functions ##
 
 help() {
+	local errcode updated
 	errcode="${1:-2}"
-	cat << END_HELP
-${orange}$_script${normal} $_version, Updated $_updated
+	updated="10 Oct 2024"
+	cat << _HELP_
+${orange}$script${normal} $version, Updated $updated
 Copies default i3 configuration files from the local Gitea server.
 
-${green}Usage:${normal} $_script [OPTIONS]
+${green}Usage:${normal} $script [OPTIONS]
 
 ${orange}Available options:${normal}
   -a  Copy autostart.sh (Launches programs necessary for i3 to run.)
@@ -63,8 +64,7 @@ ${orange}Available options:${normal}
 ${bold}NOTES${normal}
 1. Some files may need to be modified to fit a particular system configuration.
 2. Assumes i3wm has been installed from the i3debian repository on the local Gitea server.
-END_HELP
-	printf "%s v%s (%s)\n" "$_script" "$_version" "$_updated"
+_HELP_
   exit "$errcode"
 }
 
@@ -175,74 +175,82 @@ copy_dmconf() {
 	printf "%s copied from the Gitea Server.\n" "$file"
 }
 
+check_dependencies() {
+	if exists i3; then
+		printf "i3wm is installed.\n"
+		sleep 2
+		printf '\e[A\e[K'
+		check_package curl
+	else
+		printf "i3wm is not installed.\n"
+		help 0
+	fi
+}
+
+main() {
+	local noOpt optstr opt
+	check_dependencies
+	noOpt=1
+	optstr=":abcdehklmprsw"
+	while getopts "$optstr" opt; do
+		case "$opt" in
+			a )
+				copy_i3_config "autostart.sh"
+			;;
+			b )
+				copy_polybar_config
+			;;
+			c )
+				copy_i3_config "config"
+			;;
+			d )
+				copy_dunst_config
+			;;
+			e )
+				copy_all_i3_configs
+				copy_polybar_config
+				copy_polybar_launch
+				copy_rofi_config
+				copy_dunst_config
+			;;
+			h )
+				help 0
+			;;
+			i )
+				copy_all_i3_configs
+			;;
+			k )
+				copy_i3_config "bindings.list"
+			;;
+			l )
+				copy_i3_config "logout"
+			;;
+			m )
+				copy_dmconf
+			;;
+			p )
+				copy_polybar_launch
+			;;
+			r )
+				copy_rofi_configs
+			;;
+			s )
+				copy_i3_config "sxhkdrc"
+			;;
+			w )
+				copy_i3_config "workspaces.conf"
+			;;
+			? )
+				printf "%s Invalid option -%s\n" "$RED_ERROR" "$OPTARG" >&2
+				help 2
+		esac
+		noOpt=0
+	done
+	[[ "$noOpt" = 1 ]] && { printf "%s No argument passed.\n" "$RED_ERROR" >&2; help 1; }
+	shift "$(( OPTIND - 1 ))"
+	leave "$script v$version"
+}
+
 ## Execution ##
 
-if exists i3; then
-	printf "i3wm is installed.\n"
-	sleep 2
-	printf '\e[A\e[K'
-	check_package curl
-else
-	printf "i3wm is not installed.\n"
-	help 0
-fi
-noOpt=1
-optstr=":abcdehklmprsw"
-while getopts "$optstr" opt; do
-	case "$opt" in
-		a )
-			copy_i3_config "autostart.sh"
-		;;
-		b )
-			copy_polybar_config
-		;;
-		c )
-			copy_i3_config "config"
-		;;
-		d )
-			copy_dunst_config
-		;;
-		e )
-			copy_all_i3_configs
-			copy_polybar_config
-			copy_polybar_launch
-			copy_rofi_config
-			copy_dunst_config
-		;;
-		h )
-			help 0
-		;;
-		i )
-			copy_all_i3_configs
-		;;
-		k )
-			copy_i3_config "bindings.list"
-		;;
-		l )
-			copy_i3_config "logout"
-		;;
-		m )
-			copy_dmconf
-		;;
-		p )
-			copy_polybar_launch
-		;;
-		r )
-			copy_rofi_configs
-		;;
-		s )
-			copy_i3_config "sxhkdrc"
-		;;
-		w )
-			copy_i3_config "workspaces.conf"
-		;;
-		? )
-			printf "%s Invalid option -%s\n" "$red_error" "$OPTARG" >&2
-			help 2
-	esac
-	noOpt=0
-done
-[[ "$noOpt" = 1 ]] && { printf "%s No argument passed.\n" "$red_error" >&2; help 1; }
-shift "$(( OPTIND - 1 ))"
-printf "%s v%s\n" "$_script" "$_version"
-exit
+main "$@"
