i3kb: sourced functionlib.bash;updated return codes & local variables

diff --git a/i3kb b/i3kb
--- a/i3kb
+++ b/i3kb
@@ -1,66 +1,64 @@
 #!/usr/bin/env bash
 ###############################################################################
 # Script Name  : i3kb
-# Description  : Displays i3 keybindings
+# Description  : Displays i3 keybindings in a table format
 # Dependencies : None
 # Arguments    : None
 # Author       : Copyright © 2023 Richard B. Romig, Mosfanet
 # Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
 # Created      : 16 Apr 2023
-# Updated      : 22 Jun 2026
-# Comments     : Install with bindings.list in ~/.config/i3/
+# Updated      : 07 Aug 2026
+# Version      : 1.11.26219
+# Comments     : Install with keybindings.conf in ~/.config/i3/
 # TODO (Rick)  :
 # License      : GNU General Public License, version 2.0
 # License URL  : https://github.com/RickRomig/scripts/blob/main/LICENSE
 ###############################################################################
-# This program is free software; you can redistribute it and/or modify
-# it under the terms of the GNU General Public License as published by
-# the Free Software Foundation; either version 2 of the License, or
-# (at your option) any later version.
+# This program is free software; you can redistribute it and/or modify it under
+# the terms of the GNU General Public License as published by the Free Software
+# Foundation; either version 2 of the License, or (at your option) any later
+# version.
 #
-# This program is distributed in the hope that it will be useful,
-# but WITHOUT ANY WARRANTY; without even the implied warranty of
-# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
-# GNU General Public License for more details.
+# This program is distributed in the hope that it will be useful, but WITHOUT
+# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
+# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
 ###############################################################################
 
-## Source function library ##
-# shellcheck source=/home/rick/bin/functionlib
-source ~/bin/functionlib || { printf "\e[91mERROR:\e[0m Unable to source functionlib\n"; exit 1; }
-
-## Global Variables ##
-
-readonly i3_dir=~/.config/i3
-readonly bindings="bindings.list"
-
-## Functions ##
+# shellcheck source=/home/rick/bin/functionlib.bash
+source ~/bin/functionlib.bash || { printf "\e[91mERROR:\e[0m Unable to source functionlib.bash\n"; exit 1; }
 
 copy_bindings() {
+	local -r i3_dir="$1"
+	local -r bindings="$2"
 	local repository
 	repository=$(assign_cfg_repo)
 	printf "Copying i3 keyboard bindings...\n"
 	cp -v "$repository/$bindings" "$i3_dir/$bindings"
+	return 0
 }
 
 show_bindings() {
-	[[ -f "$i3_dir/$bindings" ]] || copy_bindings
+	local -r i3_dir="$1"
+	local -r bindings="$2"
+	[[ -f "$i3_dir/$bindings" ]] || copy_bindings "$i3_dir" "$bindings"
 	printf "i3wm keybindings:\n"
 	column -t -s "|" -N Binding,Action,Binding,Action "$i3_dir/$bindings"
+	return 0
 }
 
 main() {
 	local -r script="${0##*/}"
-	local -r version="1.10.26173"
+	local -r version="1.11.26219"
+	local -r i3_dir=~/.config/i3
+	local -r i3_bindings=keybindings.conf
 	if [[ "$DESKTOP_SESSION" == "i3" ]]; then
 		clearscreen
-		show_bindings
+		show_bindings "$i3_dir" "$i3_bindings"
 	else
 		printf "i3wm is not the current desktop session.\n"
 	fi
 	over_line "$script $version"
 	exit
 }
-
-## Execution ##
 
 main "$@"
