insert-license: updated variables and case statements

diff --git a/insert-license b/insert-license
--- a/insert-license
+++ b/insert-license
@@ -7,7 +7,7 @@
 # Author       : Copyright (C) 2019, Richard B. Romig, Moafanet
 # Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
 # Created      : 05 Jun 2019
-# Updated      : 14 Nov 2025
+# Updated      : 26 Feb 2026
 # Comments     : Inserts the license immediately after the file's header.
 #              : Assumes the standard script or C/C++ header is present.
 # TODO (rick)  :
@@ -35,19 +35,19 @@ if [[ -x "$HOME/bin/functionlib" ]]; then
   source "$HOME/bin/functionlib"
 else
   printf "\e[91mERROR:\e[0m functionlib not found!\n" >&2
-  exit 1
+  exit 81
 fi
 
 ## Global Variables ##
 
 readonly script="${0##*/}"
-readonly version="4.6.25318"
+readonly version="4.7.26057"
 
 ## Functions ##
 
 help() {
-  local errcode="${1:-2}"
-  local updated="14 Nov 2025"
+  local errcode="${1:-1}"
+  local updated="26 Feb 2026"
   cat << _HELP_
 ${orange}$script${normal} $version ($updated)
 Inserts an Open Source license into a shell script or a C/C++ source code file.
@@ -73,19 +73,19 @@ cleanup() {
 
 create_tmp_file() {
 	printf "Creating temporary file.\n"
-	tmp_file=$(mktemp -q) || die "Failed to create temporary file." 1
+	tmp_file=$(mktemp -q) || die "Failed to create temporary file." "$E_TEMP_FILE"
 	trap cleanup EXIT
 }
 
 insert_license() {
-	local cur_yr licenses script_dir
+	local cur_yr licenses
 	local code_type="$1"
 	local code_file="$2"
 	local copy_holder="Richard B. Romig"
 	local email_addr="rick.romig@gmail.com"
 	cur_yr=$(echo -e "\UA9 $(date +%Y)")
-	script_dir=$(dirname "$(readlink -f "${0}")")
-	local template_dir="$script_dir/Templates"
+	script_dir=$(dirname "$(readlink -f "${0}")"); local -r script_dir
+	local -r template_dir="$script_dir/Templates"
 
 	# Select license type
 	printf "\n%sLicense type:%s\n" "$orange" "$normal"
@@ -94,17 +94,13 @@ insert_license() {
 	select lic_type in "${licenses[@]}"; do
 		case $REPLY in
     1 )
-      lic_file="gpl_v1.txt"
-      break ;;
+      lic_file="gpl_v1.txt"; break ;;
     2 )
-      lic_file="gpl_v2.txt"
-      break ;;
+      lic_file="gpl_v2.txt"; break ;;
     3 )
-      lic_file="gpl_v3.txt"
-      break ;;
+      lic_file="gpl_v3.txt"; break ;;
     4 )
-      lic_file="mit_lic.txt"
-      break ;;
+      lic_file="mit_lic.txt"; break ;;
     * )
       printf "%sInvalid option. Try again.%s\n" "$lightred" "$normal" >&2
 		esac
@@ -114,32 +110,32 @@ insert_license() {
 	# Insert the license into the source file
 	printf "Inserting %a license into %s.\n" "$lic_type" "$code_file"
 	case $code_type in
-	"C" )
-		sed -e '1d' \
-			-e "s/<YEAR>/$cur_yr/" \
-			-e "s/<COPYRIGHT HOLDER>/$copy_holder/" \
-			-e "s/<EMAIL>/$email_addr/" \
-			-e "s/^/ * /" "$template_dir/$lic_file" > "$tmp_file"
-		sed -i -e "22r ${tmp_file}" "$code_file"
-		;;
-	"C++" )
-		sed -e '1d' \
-			-e "s/<YEAR>/$cur_yr/" \
-			-e "s/<COPYRIGHT HOLDER>/$copy_holder/" \
-			-e "s/<EMAIL>/$email_addr/" \
-			-e "s/^/\/\/ /" "$template_dir/$lic_file" > "$tmp_file"
-		sed -i -e "23r ${tmp_file}" "$code_file"
-		;;
-	"Shell" )
-		sed -e '1d' \
-			-e "s/<YEAR>/$cur_yr/" \
-			-e "s/<COPYRIGHT HOLDER>/$copy_holder/" \
-			-e "s/<EMAIL>/$email_addr/" \
-			-e "s/^/# /" "$template_dir/$lic_file" > "$tmp_file"
-		sed -i -e "15r ${tmp_file}" "$code_file"
-		;;
-	* )
-		die "Invalid code type. Exiting the script." 1
+		"C" )
+			sed -e '1d' \
+				-e "s/<YEAR>/$cur_yr/" \
+				-e "s/<COPYRIGHT HOLDER>/$copy_holder/" \
+				-e "s/<EMAIL>/$email_addr/" \
+				-e "s/^/ * /" "$template_dir/$lic_file" > "$tmp_file"
+			sed -i -e "22r ${tmp_file}" "$code_file"
+			;;
+		"C++" )
+			sed -e '1d' \
+				-e "s/<YEAR>/$cur_yr/" \
+				-e "s/<COPYRIGHT HOLDER>/$copy_holder/" \
+				-e "s/<EMAIL>/$email_addr/" \
+				-e "s/^/\/\/ /" "$template_dir/$lic_file" > "$tmp_file"
+			sed -i -e "23r ${tmp_file}" "$code_file"
+			;;
+		"Shell" )
+			sed -e '1d' \
+				-e "s/<YEAR>/$cur_yr/" \
+				-e "s/<COPYRIGHT HOLDER>/$copy_holder/" \
+				-e "s/<EMAIL>/$email_addr/" \
+				-e "s/^/# /" "$template_dir/$lic_file" > "$tmp_file"
+			sed -i -e "15r ${tmp_file}" "$code_file"
+			;;
+		* )
+			die "Invalid code type. Exiting the script." "$E_INVALID_ARG"		# Should never occur
 	esac
 
 	printf "\n%s license has been inserted into %s." "$lic_type" "$code_file"
@@ -150,47 +146,46 @@ main() {
 	local noOpt=1
 	local optstr=":c:hp:s:"
 	while getopts "$optstr" opt; do
-	case "$opt" in
-		c )
-			code_file="$OPTARG"
-			[[ -f "$code_file" ]] || { printf "%s %s not found\n" "$RED_ERROR" "$code_file" >&2; help 2; }
-			printf "File: %s\n" "$code_file"
-			code_type="C"
-			printf "Code type: %s source code\n" "$code_type"
-			create_tmp_file
-			;;
-		h )
-			help 0
-			;;
-		p )
-			code_file="$OPTARG"
-			[[ -f "$code_file" ]] || { printf "%s %s not found\n" "$RED_ERROR" "$code_file" >&2; help 2; }
-			printf "File: %s\n" "$code_file"
-			code_type="C++"
-			printf "Code type: %s source code\n" "$code_type"
-			create_tmp_file
-			;;
-		s )
-			code_file="$OPTARG"
-			[[ -f "$code_file" ]] || { printf "%s %s not found\n" "$RED_ERROR" "$code_file" >&2; help 2; }
-			printf "File: %s\n" "$code_file"
-			code_type="Shell"
-			printf "Code type: %s source code\n" "$code_type"
-			create_tmp_file
-			;;
-		: )
-			printf "%s Must supply an argument to -%s.\n" "$RED_ERROR" "$OPTARG" >&2
-			help 2
-			;;
-		? )
-			printf "%s Invalid option -%s\n" "$RED_ERROR" "$OPTARG" >&2
-			help 2
+		case "$opt" in
+			c )
+				code_file="$OPTARG"
+				[[ -f "$code_file" ]] || { printf "%s %s not found\n" "$RED_ERROR" "$code_file" >&2; help "$E_FILENOTFOUND"; }
+				printf "File: %s\n" "$code_file"
+				code_type="C"
+				printf "Code type: %s source code\n" "$code_type"
+				create_tmp_file
+				;;
+			h )
+				help 0
+				;;
+			p )
+				code_file="$OPTARG"
+				[[ -f "$code_file" ]] || { printf "%s %s not found\n" "$RED_ERROR" "$code_file" >&2; help "$E_FILENOTFOUND"; }
+				printf "File: %s\n" "$code_file"
+				code_type="C++"
+				printf "Code type: %s source code\n" "$code_type"
+				create_tmp_file
+				;;
+			s )
+				code_file="$OPTARG"
+				[[ -f "$code_file" ]] || { printf "%s %s not found\n" "$RED_ERROR" "$code_file" >&2; help "$E_FILENOTFOUND"; }
+				printf "File: %s\n" "$code_file"
+				code_type="Shell"
+				printf "Code type: %s source code\n" "$code_type"
+				create_tmp_file
+				;;
+			: )
+				printf "%s Must supply an argument to -%s.\n" "$RED_ERROR" "$OPTARG" >&2
+				help "$E_MISSING_ARG"
+				;;
+			? )
+				printf "%s Invalid option -%s\n" "$RED_ERROR" "$OPTARG" >&2
+				help "$E_INVALID_ARG"
 		esac
 		noOpt=0
 	done
-	[[ "$noOpt" = 1 ]] && { printf "%s No argument passed.\n" "$RED_ERROR" >&2; help 1; }
+	[[ "$noOpt" = 1 ]] && { printf "%s No argument passed.\n" "$RED_ERROR" >&2; help "$E_MISSING_ARG"; }
 	shift "$(( OPTIND - 1 ))"
-	[[ "$code_file" ]] || { printf "%s No code file provided.\n" "$RED_ERROR" >&2; help 2; }
 	insert_license "$code_type" "$code_file"
 	edit_view_quit "$code_file"
 	over_line "$script $version"
