insert-header: temp file creation after getops loop, removed create_temp_file()

diff --git a/insert-header b/insert-header
--- a/insert-header
+++ b/insert-header
@@ -7,7 +7,7 @@
 # Author       : Copyright (C) 2019, Richard B. Romig, Mosfanet
 # Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
 # Created      : 05 Jun 2019
-# Updated      : 16 Apr 2026
+# Updated      : 18 May 2026
 # Comments     : Assumes first line of the target file is either a hash-bang or a C/C++ comment
 # TODO (rick)  :
 # License      : GNU General Public License, version 2.0
@@ -26,18 +26,25 @@
 
 ## Load function library ##
 # shellcheck source=/home/rick/bin/functionlib
-source functionlib || { printf "\e[91mERROR:\e[0m Unable to source functionlib\n"; exit 1; }
+source ~/bin/functionlib || { printf "\e[91mERROR:\e[0m Unable to source functionlib\n"; exit 1; }
 
 ## Global Variables ##
 
 readonly script="${0##*/}"
-readonly version="4.8.26106"
+readonly version="4.9.26138"
 
 ## Functions ##
 
+# Don't warn about unreachable commands in this function
+# ShellCheck may incorrectly believe that code is unreachable if it's invoked by variable name or in a trap.
+# shellcheck disable=SC2317
+cleanup() {
+  [[ -f "$TMP_FILE" ]] && rm -f "$TMP_FILE"
+}
+
 help() {
   local errcode="${1:-1}"
-  local updated="16 Apr 2026"
+  local updated="18 May 2026"
   cat << _HELP_
 ${orange}$script${normal} $version ($updated)
 Inserts a header into a shell script or a C/C++ source file.
@@ -53,18 +60,6 @@ ${orange}Available options:${normal}
       $script -s <shell-script>
 _HELP_
   exit "$errcode"
-}
-
-# shellcheck disable=SC2317
-# Don't warn about unreachable commands in this function
-# ShellCheck may incorrectly believe that code is unreachable if it's invoked by variable name or in a trap.
-cleanup() {
-  [[ -f "$TMP_FILE" ]] && rm -f "$TMP_FILE"
-}
-
-create_temp_file() {
-	TMP_FILE=$(mktemp -q) || die "Failed to create temporary file." "$E_TEMP_FILE"
-	trap cleanup EXIT
 }
 
 insert_header() {
@@ -108,7 +103,6 @@ main() {
 				[[ -f "$code_file" ]] || { printf "%s %s not found\n" "$RED_ERROR" "$code_file" >&2; help "$E_FILENOTFOUND"; }
         code_type="C"
         template_file="c-header.txt"
-        create_temp_file
         ;;
       h )
         help 0
@@ -118,14 +112,12 @@ main() {
 				[[ -f "$code_file" ]] || { printf "%s %s not found\n" "$RED_ERROR" "$code_file" >&2; help "$E_FILENOTFOUND"; }
         code_type="C++"
         template_file="cpp-header.txt"
-        create_temp_file
         ;;
       s )
 				code_file="$OPTARG"
 				[[ -f "$code_file" ]] || { printf "%s %s not found\n" "$RED_ERROR" "$code_file" >&2; help "$E_FILENOTFOUND"; }
         code_type="Shell"
         template_file="bash-header.txt"
-        create_temp_file
         ;;
      : )
         printf "%s Must supply an argument to -%s.\n" "$RED_ERROR" "$OPTARG" >&2
@@ -139,6 +131,8 @@ main() {
 	done
 	[[ "$noOpt" = 1 ]] && { printf "%s No argument passed.\n" "$RED_ERROR" >&2; help "$E_MISSING_ARG"; }
 	shift "$(( OPTIND - 1 ))"
+	TMP_FILE=$(mktemp -q) || die "Failed to create temporary file." "$E_TEMP_FILE"
+	trap cleanup EXIT
 	insert_header "$code_file" "$code_type" "$template_file"
 	edit_view_quit "$code_file"
 	over_line "$script $version"
