insert-header: sourced functionlib.bash; updated local variables

diff --git a/insert-header b/insert-header
--- a/insert-header
+++ b/insert-header
@@ -7,7 +7,8 @@
 # Author       : Copyright (C) 2019, Richard B. Romig, Mosfanet
 # Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
 # Created      : 05 Jun 2019
-# Updated      : 06 Jul 2026
+# Updated      : 07 Aug 2026
+# Version      : 4.11.26219
 # Comments     : Assumes first line of the target file is either a hash-bang or a C/C++ comment
 # TODO (rick)  :
 # License      : GNU General Public License, version 2.0
@@ -22,17 +23,14 @@
 # FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
 ###############################################################################
 
-## Source function library ##
-# shellcheck source=/home/rick/bin/functionlib
-source ~/bin/functionlib || { printf "\e[91mERROR:\e[0m Unable to source functionlib\n"; exit 1; }
-
-## Functions ##
+# shellcheck source=/home/rick/bin/functionlib.bash
+source ~/bin/functionlib.bash || { printf "\e[91mERROR:\e[0m Unable to source functionlib.bash\n"; exit 1; }
 
 help() {
   local -r script="$1"
   local -r version="$2"
-  local errcode="${3:-1}"
-  local updated="06 Jul 2026"
+  local -ri errcode="${3:-1}"
+  local -r updated="06 Jul 2026"
   cat << _HELP_
 ${orange}$script${normal} $version ($updated)
 Inserts a header into a shell script or a C/C++ source file.
@@ -98,7 +96,7 @@ insert_header() {
 
 main() {
   local -r script="${0##*/}"
-  local -r version="4.10.26187"
+  local -r version="4.11.26219"
 	local code_file code_type template_file opt OPTARG OPTIND
 	local -i noOpt=1
 	local -r optstr=":c:hp:s:v"
@@ -144,7 +142,5 @@ main() {
 	over_line "$script $version"
 	printf "MOTD: "; leave ""
 }
-
-## Execution ##
 
 main "$@"
