insert-header: changed source functionlib; rename tmp_file to TMP_FILE; insert_header() changed cur_yr assigment

diff --git a/insert-header b/insert-header
--- a/insert-header
+++ b/insert-header
@@ -7,7 +7,7 @@
 # Author       : Copyright (C) 2019, Richard B. Romig, Mosfanet
 # Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
 # Created      : 05 Jun 2019
-# Updated      : 26 Feb 2026
+# Updated      : 16 Apr 2026
 # Comments     : Assumes first line of the target file is either a hash-bang or a C/C++ comment
 # TODO (rick)  :
 # License      : GNU General Public License, version 2.0
@@ -24,28 +24,20 @@
 # GNU General Public License for more details.
 ###############################################################################
 
-## Shellcheck Directives ##
-# shellcheck source=/home/rick/bin/functionlib
-
 ## Load function library ##
-
-if [[ -x "$HOME/bin/functionlib" ]]; then
-  source "$HOME/bin/functionlib"
-else
-  echo -e "\e[91mERROR:\e[0m functionlib not found!" >&2
-  exit 81
-fi
+# shellcheck source=/home/rick/bin/functionlib
+source functionlib || { printf "\e[91mERROR:\e[0m Unable to source functionlib\n"; exit 1; }
 
 ## Global Variables ##
 
 readonly script="${0##*/}"
-readonly version="4.7.26057"
+readonly version="4.8.26106"
 
 ## Functions ##
 
 help() {
   local errcode="${1:-1}"
-  local updated="26 Feb 2026"
+  local updated="16 Apr 2026"
   cat << _HELP_
 ${orange}$script${normal} $version ($updated)
 Inserts a header into a shell script or a C/C++ source file.
@@ -63,14 +55,15 @@ _HELP_
   exit "$errcode"
 }
 
-# shellcheck disable=SC2317 # Don't warn about unreachable commands in this function
+# shellcheck disable=SC2317
+# Don't warn about unreachable commands in this function
 # ShellCheck may incorrectly believe that code is unreachable if it's invoked by variable name or in a trap.
 cleanup() {
-  [[ -f "$tmp_file" ]] && rm -f "$tmp_file"
+  [[ -f "$TMP_FILE" ]] && rm -f "$TMP_FILE"
 }
 
-create_tmp_file() {
-	tmp_file=$(mktemp -q) || die "Failed to create temporary file." "$E_TEMP_FILE"
+create_temp_file() {
+	TMP_FILE=$(mktemp -q) || die "Failed to create temporary file." "$E_TEMP_FILE"
 	trap cleanup EXIT
 }
 
@@ -81,22 +74,22 @@ insert_header() {
 	local -r template_file="$3"
 	local -r template_dir=~/bin/Templates
 	today=$(date +"%d %b %Y")
-  cur_yr=$(printf "\UA9 %s" "$(date +%Y)")
+  cur_yr=$(printf "\UA9 %(%Y)T")
 
 	case $code_type in
     "C"|"C++" )
       sed -e '1d' \
         -e "s/<PROGNAME>/$code_file/" \
         -e "s/<YEAR>/$cur_yr/" \
-        -e "s/<TODAY>/$today/" "$template_dir/$template_file" > "$tmp_file"
-      sed -i -e "1r ${tmp_file}" "$code_file"
+        -e "s/<TODAY>/$today/" "$template_dir/$template_file" > "$TMP_FILE"
+      sed -i -e "1r ${TMP_FILE}" "$code_file"
       ;;
     "Shell" )
 	    sed -e '1d' \
         -e "s/<FILE>/$code_file/" \
         -e "s/<YEAR>/$cur_yr/" \
-        -e "s/<TODAY>/$today/" "$template_dir/$template_file" > "$tmp_file"
-      sed -i -e "1r ${tmp_file}" "$code_file"
+        -e "s/<TODAY>/$today/" "$template_dir/$template_file" > "$TMP_FILE"
+      sed -i -e "1r ${TMP_FILE}" "$code_file"
       ;;
     * )
       printf "%sInvalid code type.%s\n" "$lightred" "$normal" >&2
@@ -115,7 +108,7 @@ main() {
 				[[ -f "$code_file" ]] || { printf "%s %s not found\n" "$RED_ERROR" "$code_file" >&2; help "$E_FILENOTFOUND"; }
         code_type="C"
         template_file="c-header.txt"
-        create_tmp_file
+        create_temp_file
         ;;
       h )
         help 0
@@ -125,14 +118,14 @@ main() {
 				[[ -f "$code_file" ]] || { printf "%s %s not found\n" "$RED_ERROR" "$code_file" >&2; help "$E_FILENOTFOUND"; }
         code_type="C++"
         template_file="cpp-header.txt"
-        create_tmp_file
+        create_temp_file
         ;;
       s )
 				code_file="$OPTARG"
 				[[ -f "$code_file" ]] || { printf "%s %s not found\n" "$RED_ERROR" "$code_file" >&2; help "$E_FILENOTFOUND"; }
         code_type="Shell"
         template_file="bash-header.txt"
-        create_tmp_file
+        create_temp_file
         ;;
      : )
         printf "%s Must supply an argument to -%s.\n" "$RED_ERROR" "$OPTARG" >&2
