insert-header - changed red_error variable to uppercase.

diff --git a/insert-header b/insert-header
--- a/insert-header
+++ b/insert-header
@@ -7,7 +7,7 @@
 # Author       : Copyright (C) 2019, Richard B. Romig, Mosfanet
 # Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
 # Created      : 05 Jun 2019
-# Updated      : 04 Aug 2024
+# Updated      : 31 Oct 2024
 # Comments     : Assumes first line or the target file is either a hash-bang or
 #              : a C-style comment
 #              : bat - https://github.com/sharkdp/bat/releases/
@@ -31,8 +31,8 @@ fi
 ## Variables ##
 
 _script=$(basename "$0"); readonly _script
-readonly _version="v3.3.24217"
-readonly _updated="04 Aug 2024"
+readonly _version="v3.3.24305"
+readonly _updated="31 Oct 2024"
 readonly conf_dir="$HOME/.config/scripts"
 readonly conf_file="$_script.conf"
 today=$(date +"%d %b %Y"); readonly today
@@ -65,7 +65,7 @@ create_conf() {
 
 help() {
   local errcode="${1:-2}"
-  cat << END_HELP
+  cat << _HELP_
 ${orange}$_script${normal} $_version ($_updated)
 Inserts a header into a shell script or a C/C++ source file.
 
@@ -81,7 +81,7 @@ ${orange}Available options:${normal}
   -s  Shell script header
       $_script -s <shell-script>
   -v  Enable verbose mode
-END_HELP
+_HELP_
   exit "$errcode"
 }
 
@@ -107,7 +107,7 @@ while getopts "$optstr" opt; do
   case "$opt" in
     c )
 			code_file="$OPTARG"
-			[[ -f "$code_file" ]] || { printf "%s %s not found\n" "$red_error" "$code_file" >&2; help 2; }
+			[[ -f "$code_file" ]] || { printf "%s %s not found\n" "$RED_ERROR" "$code_file" >&2; help 2; }
       show_message "File: $code_file"
       code_type="C"
       show_message "Code type: $code_type header"
@@ -127,7 +127,7 @@ while getopts "$optstr" opt; do
     ;;
     p )
 			code_file="$OPTARG"
-			[[ -f "$code_file" ]] || { printf "%s %s not found\n" "$red_error" "$code_file" >&2; help 2; }
+			[[ -f "$code_file" ]] || { printf "%s %s not found\n" "$RED_ERROR" "$code_file" >&2; help 2; }
       show_message "File: $code_file"
       code_type="C++"
       show_message "Code type: $code_type header"
@@ -136,7 +136,7 @@ while getopts "$optstr" opt; do
    ;;
     s )
 			code_file="$OPTARG"
-			[[ -f "$code_file" ]] || { printf "%s %s not found\n" "$red_error" "$code_file" >&2; help 2; }
+			[[ -f "$code_file" ]] || { printf "%s %s not found\n" "$RED_ERROR" "$code_file" >&2; help 2; }
       show_message "File: $code_file"
       code_type="Shell"
       show_message "Code type: $code_type header"
@@ -148,16 +148,16 @@ while getopts "$optstr" opt; do
 			show_message "Verbose mode enabled."
 		;;
     : )
-      printf "%s Must supply an argument to -%s.\n" "$red_error" "$OPTARG" >&2
+      printf "%s Must supply an argument to -%s.\n" "$RED_ERROR" "$OPTARG" >&2
       help 2
     ;;
     ? )
-			printf "%s Invalid option -%s\n" "$red_error" "$OPTARG" >&2
+			printf "%s Invalid option -%s\n" "$RED_ERROR" "$OPTARG" >&2
 			help 2
   esac
 	noOpt=0
 done
-[[ "$noOpt" = 1 ]] && { printf "%s No argument passed.\n" "$red_error" >&2; help 1; }
+[[ "$noOpt" = 1 ]] && { printf "%s No argument passed.\n" "$RED_ERROR" >&2; help 1; }
 shift "$(( OPTIND - 1 ))"
 
 [[ -z "$code_file" ]] && leave "No file selected."
