install-audacious: fixed tabs

diff --git a/install-audacious b/install-audacious
--- a/install-audacious
+++ b/install-audacious
@@ -7,8 +7,8 @@
 # Author       : Copyright (C) 2020, Richard B. Romig, LudditeGeek@Mosfanet
 # Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
 # Created      : 23 Mar 2020
-# Updated      : 13 Aug 2026
-# Version      : 2.12.26225
+# Updated      : 07 Sep 2026
+# Version      : 2.12.26250
 # Comments     : Script does not currently support installation from Ubuntu PPAs or flatpak.
 # TODO (Rick)  :
 # License      : GNU General Public License, version 2.0
@@ -27,85 +27,85 @@
 source ~/bin/functionlib.bash || { printf "\e[91mERROR:\e[0m Unable to source functionlib.bash\n"; exit 1; }
 
 help() {
-  local -r script="$1"
-  local -r version="$2"
-  local -ri errcode="${3:-1}"
-  local -r updated="13 Aug 2026"
-	cat << _HELP_
+	local -r script="$1"
+	local -r version="$2"
+	local -ri errcode="${3:-1}"
+	local -r updated="07 Sep 2026"
+	cat <<- _HELP_
 ${orange}$script${normal} $version ($updated)
 Install or remove Audacious audio player
 
 ${green}Usage:${normal} $script [OPTION]
 ${orange}Available options:${normal}
-  -h  Show this help message and exit.
-  -i  Install Audacious audio player.
-  -r  Remove Audacious audio player.
+	-h	Show this help message and exit.
+	-i	Install Audacious audio player.
+	-r	Remove Audacious audio player.
 _HELP_
-  exit "$errcode"
+	exit "$errcode"
 }
 
 install_audacious() {
-  if installed audacious; then
-    printf "Audacious audio player is already installed.\n" >&2
-    return 1
-  fi
-  if ! in_repos audacious; then
-    printf "Audacious is not in repositories. Audacious audio player not installed.\n" >&2
-    return "$E_UNSUPPORTED"
-  fi
-  sudo_login 2
-  printf "Installing Audacious audio player...\n"
-  sudo apt update -qq
-  sudo apt install audacious audacious-plugins -yy
-  if ! installed audacious; then
-    printf "%s Audacious installation failed.\n" "$RED_ERROR" >&2
-    return "$E_INSTALLATION"
-  fi
-  printf "Audacious audio player installed from distro repository.\n"
-  return 0
+	if installed audacious; then
+		printf "Audacious audio player is already installed.\n" >&2
+		return "$E_FILE_EXISTS"
+	fi
+	if ! in_repos audacious; then
+		printf "Audacious is not in repositories. Audacious audio player not installed.\n" >&2
+		return "$E_UNSUPPORTED"
+	fi
+	sudo_login 2
+	printf "Installing Audacious audio player...\n"
+	sudo apt update -qq
+	sudo apt install audacious audacious-plugins -yy
+	if ! installed audacious; then
+		printf "%s Audacious installation failed.\n" "$RED_ERROR" >&2
+		return "$E_INSTALLATION"
+	fi
+	printf "Audacious audio player installed from distro repository.\n"
+	return 0
 }
 
 remove_audacious() {
-  if ! installed audacious; then
-    printf "Audacious audio player is not installed.\n" >&2
-    return 1
-  fi
-  sudo_login 2
-  printf "Removing Audacious audio player....\n"
-  sudo apt remove --autoremove audacious audacious-plugins
-  printf "Audacious audio player removed.\n"
-  return 0
+	if ! installed audacious; then
+		printf "Audacious audio player is not installed.\n" >&2
+		return "$E_NOT_INSTALLED"
+	fi
+	sudo_login 2
+	printf "Removing Audacious audio player....\n"
+	sudo apt remove --autoremove audacious audacious-plugins
+	printf "Audacious audio player removed.\n"
+	return 0
 }
 
 main() {
-  local -r script="${0##*/}"
-  local -r version="2.12.26225"
-  local -i exit_code=0
-  local opt OPTARG OPTIND
-  local -i noOpt=1
-  local -r optstr=":hir"
-  while getopts "$optstr" opt; do
-	  case "$opt" in
-		  h )
-			  help "$script" "$version" 0 ;;
-      i )
-          install_audacious ;;
-      r )
-          remove_audacious ;;
-      ? )
-        printf "%s Invalid option -%s\n" "$RED_ERROR" "$OPTARG" >&2
-        help "$script" "$version" "$E_INVALID_ARG"
-    esac
-    exit_code="$?"
-    noOpt=0
-  done
+	local -r script="${0##*/}"
+	local -r version="2.12.26250"
+	local -i exit_code=0
+	local opt OPTARG OPTIND
+	local -i noOpt=1
+	local -r optstr=":hir"
+	while getopts "$optstr" opt; do
+		case "$opt" in
+			h )
+				help "$script" "$version" 0 ;;
+			i )
+				install_audacious ;;
+			r )
+				remove_audacious ;;
+			? )
+				printf "%s Invalid option -%s\n" "$RED_ERROR" "$OPTARG" >&2
+				help "$script" "$version" "$E_INVALID_ARG"
+		esac
+		exit_code="$?"
+		noOpt=0
+	done
 	if (( noOpt == 1 )); then
 		printf "%s No argument passed.\n" "$RED_ERROR" >&2
 		help "$script" "$version" "$E_MISSING_ARG"
 	fi
-  shift "$(( OPTIND - 1 ))"
-  over_line "$script $version"
-  exit "$exit_code"
+	shift "$(( OPTIND - 1 ))"
+	over_line "$script $version"
+	exit "$exit_code"
 }
 
 main "$@"
