install-timeshift - added sourcing functionlib, fixed paths to timeshift .json files and .sed file

diff --git a/install-timeshift b/install-timeshift
--- a/install-timeshift
+++ b/install-timeshift
@@ -13,18 +13,31 @@
 # License      : GNU General Public License, version 2.0
 ###############################################################################
 
+## Shellcheck Directives ##
+# shellcheck source=/home/rick/bin/functionlib
+
+## Load function library ##
+
+if [[ -x "$HOME/bin/functionlib" ]]; then
+  source "$HOME/bin/functionlib"
+else
+  echo -e "\e[91mERROR:\e[0m functionlib not found!" >&2
+  exit 1
+fi
+
 ## Global variables ##
 _script=$(basename "$0"); readonly _script
 _version="1.0.24155"
 
 ## Execution ##
 
+sudo_login 2
 echo "$_script v$_version"
 # Install timeshift
 sudo apt-get -y timeshift
 # configure timeshift
-[[ -f ./timeshift.json ]] || cp /etc/timeshift/default.json ./timeshift.json
-sed -i.bak -f ./timeshift.sed ./timeshift.json
-sed -i 's/^"/    "/' ./timeshift.json
+[[ -f /etc/timeshift/timeshift.json ]] || sudo cp /etc/timeshift/default.json /etc/timeshift/timeshift.json
+sudo sed -i -f "$HOME/bin/files/timeshift.sed" /etc/timeshift/timeshift.json
+sudo sed -i 's/^"/    "/' /etc/timeshift/timeshift.json
 echo "Timeshift installed and configured."
 exit
