install-homebank: error code variables & process substitution

diff --git a/install-homebank b/install-homebank
--- a/install-homebank
+++ b/install-homebank
@@ -7,7 +7,7 @@
 # Author       : Copyright (C) 2018, Richard Romig, LudditeGeek@Mosfanet
 # Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
 # Created      : 29 Nov 2018
-# Updated      : 16 Nov 2025
+# Updated      : 30 Jan 2026
 # Comments     : Available as a flatpak (preferred method)
 #              : https://flathub.org/apps/details/fr.free.Homebank
 #              : Linux Mint Sofware Manager
@@ -35,19 +35,19 @@ if [[ -x "$HOME/bin/functionlib" ]]; then
   source "$HOME/bin/functionlib"
 else
   printf "\e[91mERROR:\e[0m functionlib not found!\n" >&2
-  exit 1
+  exit 81
 fi
 
 ## Global Variables ##
 
 readonly script="${0##*/}"
-readonly version="6.2.253230"
+readonly version="6.3.26030"
 
 ## Functions ##
 
 help() {
-	local errcode="${1:-2}"
-	local updated="16 Nov 2025"
+	local errcode="${1:-1}"
+	local updated="30 Jan 2026"
   cat << _HELP_
 ${orange}$script${normal} $version ($updated)
 Installs/Removes HomeBank Personal Finance Software.
@@ -64,7 +64,7 @@ _HELP_
 
 flatpak_homebank() {
   exists flatpak || return "$FALSE"
-  flatpak list | grep -qw HomeBank && return "$TRUE" || return "$FALSE"
+  grep -qw HomeBank <(flatpak list) && return "$TRUE" || return "$FALSE"
 }
 
 homebank_version() {
@@ -169,11 +169,11 @@ main() {
         ;;
       ? )
         printf "%s Invalid option: -%s\n" "$RED_ERROR" "$OPTARG" >&2
-        help 2
+        help "$E_INVALID_ARG"
     esac
 	  noOpt=0
   done
-  [[ "$noOpt" = 1 ]] && { printf "%s No argument passed.\n" "$RED_ERROR" >&2; help 1; }
+  [[ "$noOpt" = 1 ]] && { printf "%s No argument passed.\n" "$RED_ERROR" >&2; help "$E_MISSING_ARG"; }
   shift "$(( OPTIND - 1 ))"
   over_line "$script $version"
   exit
