install-cmatrix: updated local variables/return codes

diff --git a/install-cmatrix b/install-cmatrix
--- a/install-cmatrix
+++ b/install-cmatrix
@@ -1,14 +1,14 @@
 #!/usr/bin/env bash
 ###############################################################################
 # Script Name  : install-cnatrix
-# Description  : installs/removes cmatrix
+# Description  : installs/removes cmatrix & cmatrix-xfont
 # Dependencies : none
 # Arguments    : none
-# Author       : Copyright (C) 2024, Richard B. Romig, Mosfanet
+# Author       : Copyright © 2024, Richard B. Romig, Mosfanet
 # Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
 # Created      : 2024
-# Updated      : 13 Aug 2026
-# Version      : 1.13.26225
+# Updated      : 02 Sep 2026
+# Version      : 1.14.26245
 # Comment      :
 # TODO (rick)  :
 # License      : GNU General Public License, version 2.0
@@ -31,7 +31,7 @@ help() {
   local -r script="$1"
   local -r version="$2"
   local -ri errcode="${3:=-1}"
-  local -r updated="13 Aug 2026"
+  local -r updated="02 Sep 2026"
   cat << _HELP_
 ${orange}$script${normal} $version ($updated)
 Installs/Removes C-Matrix
@@ -48,14 +48,14 @@ _HELP_
 install_cmatrix() {
   if installed cmatrix; then
     printf "C-Matrix already installed.\n"
-    return 1
+    return 2
   fi
   sudo_login 2
   printf "Installing C-Matrix...\n"
   sudo apt-get update -qq
   sudo apt-get install cmatrix cmatrix-xfont -yy
-  if ! installed cmatrix; then
-    printf "%s cmatrix installation failed.\n" "$RED_ERROR" >&2
+  if ! installed cmatrix || ! installed matrix-xfont; then
+    printf "%s Installation failed.\n" "$RED_ERROR" >&2
     return "$E_INSTALLATION"
   fi
   printf "C-Matrix installed.\n"
@@ -65,7 +65,7 @@ install_cmatrix() {
 remove_cmatrix() {
   if ! installed cmatrix; then
     printf "C-Matrix is not installed.\n"
-    return 1
+    return "$E_NOT_INSTALLED"
   fi
   printf "Removing C-Matrix...\n"
   sudo_login 2
@@ -76,7 +76,7 @@ remove_cmatrix() {
 
 main() {
   local -r script="${0##*/}"
-  local -r version="1.13.26225"
+  local -r version="1.14.26245"
 	local -i exit_code=0
   local opt OPTARG OPTIND
   local -i noOpt=1
@@ -104,7 +104,5 @@ main() {
   over_line "$script $version"
   exit "$exit_code"
 }
-
-## Execution ##
 
 main "$@"
