install-audacious: script & version now local variables in main() & passed to help()

diff --git a/install-audacious b/install-audacious
--- a/install-audacious
+++ b/install-audacious
@@ -7,40 +7,30 @@
 # Author       : Copyright (C) 2020, Richard B. Romig, LudditeGeek@Mosfanet
 # Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
 # Created      : 23 Mar 2020
-# Updated      : 27 Jun 2026
+# Updated      : 06 Jul 2026
 # Comments     : Does not support installation from Ubuntu PPAs or flatpak.
 # TODO (Rick)  :
 # License      : GNU General Public License, version 2.0
 # License URL  : https://github.com/RickRomig/scripts/blob/main/LICENSE
 ###############################################################################
-# This program is free software; you can redistribute it and/or modify
-# it under the terms of the GNU General Public License as published by
-# the Free Software Foundation; either version 2 of the License, or
-# (at your option) any later version.
+# This program is free software; you can redistribute it and/or modify it under
+# the terms of the GNU General Public License as published by the Free Software
+# Foundation; either version 2 of the License, or (at your option) any later version.
 #
-# This program is distributed in the hope that it will be useful,
-# but WITHOUT ANY WARRANTY; without even the implied warranty of
-# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
-# GNU General Public License for more details.
+# This program is distributed in the hope that it will be useful, but WITHOUT
+# ANY  WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
+# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
 ###############################################################################
 
 ## Source function library ##
 # shellcheck source=/home/rick/bin/functionlib
 source ~/bin/functionlib || { printf "\e[91mERROR:\e[0m Unable to source functionlib\n"; exit 1; }
 
-## Global Variables ##
-
-readonly script="${0##*/}"
-readonly version="2.8.25178"
-readonly E_NOT_IN_REPO=102
-EC=0
-
-## Functions ##
-
 help() {
-	local -r errcode="${1:-1}"
-  local -r updated="27 Jun 2026"
-
+  local -r script="$1"
+  local -r version="$2"
+  local errcode="${3:-1}"
+  local updated="06 Jul 2026"
 	cat << _HELP_
 ${orange}$script${normal} $version ($updated)
 Install or remove Audacious audio player
@@ -57,8 +47,7 @@ _HELP_
 install_audacious() {
   if ! in_repos audacious; then
     printf "Audacious is not in repositories. Audacious audio player not installed.\n"
-    EC="$E_NOT_IN_REPO"
-    return
+    return 1
   fi
   sudo_login 2
   printf "Installing Audacious audio player...\n"
@@ -66,10 +55,10 @@ install_audacious() {
   sudo apt install audacious audacious-plugins -yy
   if ! installed audacious; then
     printf "%s Audacious installation failed.\n" "$RED_ERROR" >&2
-    EC="$E_INSTALLATION"
-    return
+    return "$E_INSTALLATION"
   fi
   printf "Audacious audio player installed from distro repository.\n"
+  return 0
 }
 
 remove_audacious() {
@@ -77,12 +66,16 @@ remove_audacious() {
   printf "Removing Audacious audio player....\n"
   sudo apt remove --autoremove audacious audacious-plugins
   printf "Audacious audio player removed.\n"
+  return 0
 }
 
 main() {
-  local noOpt opt optstr OPTARG OPTIND
-  noOpt=1
-  optstr=":hir"
+  local -r script="${0##*/}"
+  local -r version="2.9.26187"
+  local exit_code
+  local opt  OPTARG OPTIND
+  local -i noOpt=1
+  local -r optstr=":hir"
   while getopts "$optstr" opt; do
 	  case "$opt" in
 		  h )
@@ -90,7 +83,7 @@ main() {
 		    ;;
       i )
         if installed audacious; then
-          printf "Audacious audio player is already installed.\n" >&2
+          printf "Audacious audio player is already installed.\n"
         else
           install_audacious
         fi
@@ -99,21 +92,20 @@ main() {
         if installed audacious; then
           remove_audacious
         else
-          printf "Audacious audio player is not installed." >&2
+          printf "Audacious audio player is not installed."
         fi
         ;;
       ? )
         printf "%s Invalid option -%s\n" "$RED_ERROR" "$OPTARG" >&2
-        help "$E_INVALID_ARG"
+        help "$script" "$version" "$E_INVALID_ARG"
     esac
+    exit_code="$?"
     noOpt=0
   done
-  [[ "$noOpt" = 1 ]] && { printf "%s No argument passed.\n" "$RED_ERROR" >&2; help "$E_MISSING_ARG"; }
+  [[ "$noOpt" = 1 ]] && { printf "%s No argument passed.\n" "$RED_ERROR" >&2; help "$script" "$version" "$E_MISSING_ARG"; }
   shift "$(( OPTIND - 1 ))"
   over_line "$script $version"
-  exit "$EC"
+  exit "$exit_code"
 }
-
-## Execution ##
 
 main "$@"
