install-nerdfonts: chanaged indentation tabs from 2 to 4 tabs; updated return codes

diff --git a/install-nerdfonts b/install-nerdfonts
--- a/install-nerdfonts
+++ b/install-nerdfonts
@@ -7,8 +7,8 @@
 # Author       : Copyright © 2023 Richard B. Romig, Mosfanet
 # Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
 # Created      : 28 Sep 2023
-# Last updated : 24 Aug 2026
-# Version      : 2.1.26236
+# Last updated : 08 Sep 2026
+# Version      : 2.2.26251
 # Comments     : system install directory = /usr/local/share/fonts
 # TODO (Rick)  :
 # License      : GNU General Public License, version 2.0
@@ -28,59 +28,59 @@
 source functionlib.bash || { printf "\e[91mERROR:\e[0m Unable to source functionlib.bash\n"; exit 1; }
 
 install_NerdFonts() {
-  local -r font_dir="$1"
-  local -i return_code=0
-  local -r font_repo="https://github.com/ryanoasis/nerd-fonts/releases/download/v3.4.0"
-  local font fonts
-  fonts=( "FiraCode" "Go-Mono" "Hack" "Inconsolata" "Iosevka" "JetBrainsMono" "Mononoki" "RobotoMono" "SourceCodePro" )
-  create_tmp "dir"
-  for font in "${fonts[@]}"; do
-    printf "\e[03mInstalling %s ...\e[0m\n" "$font"
-    wget -q -P "$TMP_DIR" "$font_repo/$font.tar.xz"
-    mkdir -p "$font_dir/$font/"
-    tar xvf "$TMP_DIR/$font.tar.xz" -C "$font_dir/$font/"
-    return_code="$?"
-    (( return_code > 0 )) && break
-  done
-  if (( return_code > 0 )); then
-    printf "%s NerdFonts installation failed.\n" "$RED_ERROR" >&2
-  else
-    printf "Nerd fonts installed.\n"
-  fi
-  return "$return_code"
+	local -r font_dir="$1"
+	local -i code=0
+	local -r font_repo="https://github.com/ryanoasis/nerd-fonts/releases/download/v3.4.0"
+	local -r fonts=( "FiraCode" "Go-Mono" "Hack" "Inconsolata" "Iosevka" "JetBrainsMono" "Mononoki" "RobotoMono" "SourceCodePro" )
+	local font
+	create_tmp "dir"
+	for font in "${fonts[@]}"; do
+		printf "\e[03mInstalling %s ...\e[0m\n" "$font"
+		wget -q -P "$TMP_DIR" "$font_repo/$font.tar.xz"
+		mkdir -p "$font_dir/$font/"
+		tar xvf "$TMP_DIR/$font.tar.xz" -C "$font_dir/$font/"
+		code="$?"
+		(( code > 0 )) && break
+	done
+	if (( code > 0 )); then
+		printf "%s NerdFonts installation failed.\n" "$RED_ERROR" >&2
+	else
+		printf "Nerd fonts installed.\n"
+	fi
+	return "$code"
 }
 
 install_SymbolNerdFonts() {
-  local -r font_dir="$1"
-  local repository=~/Downloads/configs
-  [[ -d ~/gitea/configs ]] && repository=~/gitea/configs
-  if [[ ! -d "$repository" ]]; then
-    printf "%s Repository directory not found!\n" "$RED_ERROR" >&2
-    printf "Symbols Nerd Fonts not installed.\n" >&2
-    return "$E_FILENOTFOUND"
-  fi
-  cp -v "$repository"/local/nerdfonts/*.ttf "$font_dir/"
-  printf "Symbols Nerd Fonts installed.\n"
-  return 0
+	local -r font_dir="$1"
+	local repository=~/Downloads/configs
+	[[ -d ~/gitea/configs ]] && repository=~/gitea/configs
+	if [[ ! -d "$repository" ]]; then
+		printf "%s Repository directory not found!\n" "$RED_ERROR" >&2
+		printf "Symbols Nerd Fonts not installed.\n" >&2
+		return "$E_FILENOTFOUND"
+	fi
+	cp -v "$repository"/local/nerdfonts/*.ttf "$font_dir/"
+	printf "Symbols Nerd Fonts installed.\n"
+	return 0
 }
 
 NerdFont_install() {
-  local -r font_dir=~/.local/share/fonts
-  [[ -d "$font_dir" ]] || mkdir -p "$font_dir"
-  install_NerdFonts "$font_dir" && install_SymbolNerdFonts "$font_dir"
-  return "$?"
+	local -r font_dir=~/.local/share/fonts
+	[[ -d "$font_dir" ]] || mkdir -p "$font_dir"
+	install_NerdFonts "$font_dir" && install_SymbolNerdFonts "$font_dir"
+	return "$?"
 }
 
 main() {
-  local -r script="${0##*/}"
-  local -r version="2.1.26236"
-  local -i exit_code=0
-  check_packages wget
-  NerdFont_install
-  exit_code="$?"
-  fc-cache
-  over_line "$script $version"
-  exit "$exit_code"
+	local -r script="${0##*/}"
+	local -r version="2.2.26251"
+	local -i exit_code=0
+	check_packages wget
+	NerdFont_install
+	exit_code="$?"
+	fc-cache
+	over_line "$script $version"
+	exit "$exit_code"
 }
 
 main "$@"
