install-brave - placed getopts code in main()

diff --git a/install-brave b/install-brave
--- a/install-brave
+++ b/install-brave
@@ -7,7 +7,7 @@
 # Author       : Copyright (C) 2019, Richard B. Romig, 12 Dec 2019
 # Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
 # Created      : 12 Dec 2019
-# Updated      : 16 Jun 2024
+# Updated      : 01 Oct 2024
 # Comments     : For Debian, Ubuntu, Mint ... (Code from Brave's instructions)
 #              : Brave is only supported on 64-bit AMD/Intel architectures (amd64/x86_64).
 # TODO (Rick)  :
@@ -28,9 +28,8 @@ fi
 
 ## Variables ##
 
-_script=$(basename "$0"); readonly _script
-readonly _version="4.8.24168"
-readonly _updated="16 Jun 2024"
+script=$(basename "$0"); readonly script
+readonly version="4.8.24168"
 readonly brave_key="/usr/share/keyrings/brave-browser-archive-keyring.gpg"
 readonly brave_list="/etc/apt/sources.list.d/brave-browser-release.list"
 
@@ -82,12 +81,14 @@ remove_configs() {
 }
 
 help() {
-  local errcode="${1:-2}"
+  local errcode updated
+  errcode="${1:-2}"
+  updated="01 Oct 2024"
   cat << END_HELP
-${orange}$_script${normal} $_version ($_updated)
+${orange}$script${normal} $version ($updated)
 Installs/Removes the Brave browser
 
-${green}Usage:${normal} $_script [OPTION]
+${green}Usage:${normal} $script [OPTION]
 
 ${orange}Available options:${normal}
   -h  Show this help text.
@@ -110,42 +111,47 @@ check_dependencies() {
   fi
 }
 
+main(){
+  local noOpt opt optstr
+  noOpt=1
+  optstr=":hipr"
+  while getopts "$optstr" opt; do
+    case "$opt" in
+      h )
+        help 0
+      ;;
+      i )
+        exists brave-browser && leave "$(brave_ver) is already installed."
+        sudo_login 2
+        printf "Installs/Removes the Brave browser.\n\n"
+        check_dependencies
+        install_brave
+      ;;
+      p )
+        exists brave-browser || leave "Brave browser is not installed."
+        sudo_login 2
+        printf "Installs/Removes the Brave browser.\n\n"
+        remove_brave
+        remove_configs
+      ;;
+      r )
+        exists brave-browser || leave "Brave browser is not installed."
+        sudo_login 2
+        printf "Installs/Removes the Brave browser.\n\n"
+        remove_brave
+      ;;
+      ? )
+        printf "%s Invalid option -%s\n" "$RED_ERROR" "$OPTARG" >&2
+        help 2
+    esac
+    noOpt=0
+  done
+  [[ "$noOpt" = 1 ]] && { printf "%s No argument passed.\n" "$RED_ERROR" >&2; help 1; }
+  shift "$(( OPTIND - 1 ))"
+  printf "%s v%s\n" "$script" "$version"
+  exit
+}
+
 ## Execution ##
 
-noOpt=1
-optstr=":hipr"
-while getopts "$optstr" opt; do
-  case "$opt" in
-    h )
-      help 0
-    ;;
-    i )
-      exists brave-browser && leave "$(brave_ver) is already installed."
-      sudo_login 2
-      printf "Installs/Removes the Brave browser.\n\n"
-      check_dependencies
-      install_brave
-    ;;
-    p )
-      exists brave-browser || leave "Brave browser is not installed."
-      sudo_login 2
-      printf "Installs/Removes the Brave browser.\n\n"
-      remove_brave
-      remove_configs
-    ;;
-    r )
-      exists brave-browser || leave "Brave browser is not installed."
-      sudo_login 2
-      printf "Installs/Removes the Brave browser.\n\n"
-      remove_brave
-    ;;
-    ? )
-      printf "%s Invalid option -%s\n" "$red_error" "$OPTARG" >&2
-      help 2
-  esac
-  noOpt=0
-done
-[[ "$noOpt" = 1 ]] && { printf "%s No argument passed.\n" "$red_error" >&2; help 1; }
-shift "$(( OPTIND - 1 ))"
-printf "%s v%s\n" "$_script" "$_version"
-exit
+main "$@"
