install-codium: set_src_list() copies modernized sources from ~/bin/files & removes old-style list file

diff --git a/install-codium b/install-codium
--- a/install-codium
+++ b/install-codium
@@ -7,7 +7,7 @@
 # Author       : Copyright © 2023 Richard B. Romig, Mosfanet
 # Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
 # Created      : 04 Aug 2023
-# Updated      : 07 May 2026
+# Updated      : 24 May 2026
 # Comments     : Alternative to downloading directly from GitHub repo.
 # TODO (Rick)  : add flatpak installation...
 # License      : GNU General Public License, version 2.0
@@ -26,12 +26,12 @@
 
 ## Load function library ##
 # shellcheck source=/home/rick/bin/functionlib
-source functionlib || { printf "\e[91mERROR:\e[0m Unable to source functionlib\n"; exit 1; }
+source ~/bin/functionlib || { printf "\e[91mERROR:\e[0m Unable to source functionlib\n"; exit 1; }
 
 ## Global Variables ##
 
 readonly script="${0##*/}"
-readonly version="3.1.26127"
+readonly version="4.0.26144"
 verbose_mode="$FALSE"
 EC=0
 
@@ -39,7 +39,7 @@ EC=0
 
 help() {
 	local errcode="${1:-1}"
-	local updated="07 May 2026"
+	local updated="24 May 2026"
 	cat << _HELP_
 ${orange}$script${normal} $version, updated: ($updated)
 Install/Remove VSCodium and apply settings
@@ -56,18 +56,13 @@ _HELP_
   exit "$errcode"
 }
 
-codium_version() {
-	# head -n 1 < <(codium --version)
-	awk '/^ii/ {print $3}' < <(dpkg -l codium)
+check_dependencies() {
+  local packages=( git wget )
+  check_packages "${packages[@]}"
 }
 
-is_trixie() {
-  local codename
-  codename=$(/usr/bin/lsb_release --codename --short 2>/dev/null)
-  case "$codename" in
-    trixie|gigi ) return "$TRUE" ;;
-    * ) return "$FALSE"
-  esac
+codium_version() {
+	awk '/^ii/ {print $3}' < <(dpkg -l codium)
 }
 
 set_gpg_key() {
@@ -76,30 +71,26 @@ set_gpg_key() {
 		return
 	fi
 	show_message "Setting the GPG key..."
-	sudo wget https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/raw/master/pub.gpg \
-	-O /usr/share/keyrings/vscodium-archive-keyring.asc
+	sudo wget https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/raw/master/pub.gpg -O /usr/share/keyrings/vscodium-archive-keyring.asc
 	show_message "GPG key is set."
 }
 
 set_src_list() {
-	if [[ -f /etc/apt/sources.list.d/vscodium.list || -f /etc/apt/sources.list.d/vscodium.sources ]]; then
-		printf "VCCodium source list already exists.\n"
+	local script_dir
+	script_dir=$(dirname "$(readlink -f "${0}")")
+	local -r sources_list_d=/etc/apt/sources.list.d
+	if [[ -f /etc/apt/sources.list.d/vscodium.sources ]]; then
+		printf "VCCodium sources list already exists.\n"
 		return
 	fi
-	show_message "Creating the source list file..."
-	if is_trixie; then
-		echo '
-Types: deb
-Architectures: amd64 arm64
-URIs: https://paulcarroty.gitlab.io/vscodium-deb-rpm-repo/debs
-Suites: vscodium
-Components: main
-Signed-By: /usr/share/keyrings/vscodium-archive-keyring.asc
-' | sudo tee /etc/apt/sources.list.d/vscodium.sources
+	show_message "Creating the sources list file..."
+	if [[ -f "$script_dir/files/vscodium.sources" ]]; then
+		[[ -f "$sources_list_d/vscodium.list" ]] && sudo rm "$sources_list_d/vscodium.list"
+		sudo cp -v "$script_dir/files/vscodium.sources" "$sources_list_d/"
 	else
-		echo 'deb [ arch=amd64,arm64 signed-by=/usr/share/keyrings/vscodium-archive-keyring.asc ] https://paulcarroty.gitlab.io/vscodium-deb-rpm-repo/debs vscodium main' | sudo tee /etc/apt/sources.list.d/vscodium.list
+		die "$script_dir/files/vscodium.sources not found." "$E_FILENOTFOUND"
 	fi
-	show_message "VCCodium source list has been created."
+	show_message "VCCodium sources list has been created."
 }
 
 install_vscodium() {
@@ -109,13 +100,13 @@ install_vscodium() {
 	show_message "Updating apt cache and installing VSCodium..."
 	sudo apt-get update
 	sudo apt-get install codium
-	if grep -q '^ii' <(dpkg -l codium 2>/dev/null); then
-		printf "VSCodium %s successfully installed.\n" "$(codium_version)"
-		apply_settings
-	else
+	if ! installed codium; then
 		printf "%s VSCodium installation failed.\n" "$RED_ERROR" >&2
     EC="$E_INSTALLATION"
+		return
   fi
+	printf "VSCodium %s successfully installed.\n" "$(codium_version)"
+	apply_settings
 }
 
 apply_settings() {
@@ -135,9 +126,9 @@ remove_vscodium() {
 	show_message "Removing VSCodium..."
 	sudo apt-get purge codium
 	show_message "Removing VSCodium configuration files ..."
-	[[ -L ~/.config/VSCodium/User//settings.json ]] && unlink ~/.config/VSCodium/User/settings.json
+	[[ -L ~/.config/VSCodium/User/settings.json ]] && unlink ~/.config/VSCodium/User/settings.json
 	find ~/.config -maxdepth 2 -type d -name VSCodium -exec rm -rf {} \;
-	show_message "Removing VSCodium source list ..."
+	show_message "Removing VSCodium sources ..."
 	find /etc/apt/sources.list.d -maxdepth 1 -type f -name "vscodium*" -exec sudo rm {} \;
 	show_message "Removing VSCodium GPG key and insiders files ..."
 	find /usr/share -type f -name "*vscodium*" -exec sudo rm {} \;
@@ -150,7 +141,6 @@ show_message() {
 }
 
 main() {
-	# check_dependencies
   local noOpt opt optstr OPTARG OPTIND
 	noOpt=1
 	optstr=":ahirsv"
@@ -158,7 +148,7 @@ main() {
 		case "$opt" in
 			a)
 				# Set apt gpg key and source list
-				if exists codium; then
+				if installed codium; then
 					sudo_login 2
 					set_gpg_key
 					set_src_list
@@ -171,16 +161,17 @@ main() {
 				;;
 			i )
 				# Install VSCodium via apt
-				if exists codium; then
+				if installed codium; then
 					printf "VSCodium %s is already installed.\n" "$(codium_version)"
 				else
 					sudo_login 2
+					check_dependencies
 					install_vscodium
 				fi
 				;;
 			r )
 				# Remove VSCodium
-				if exists codium; then
+				if installed codium; then
 					sudo_login 2
 					remove_vscodium
 				else
@@ -189,7 +180,7 @@ main() {
 				;;
 			s )
 				# Apply VSCodium settings
-				if exists codium; then
+				if installed codium; then
 					apply_settings
 				else
 					printf "VSCodium is not installed.\n" >&2
