install-zram: added check for failed install; added check_for_swap()

diff --git a/install-zram b/install-zram
--- a/install-zram
+++ b/install-zram
@@ -7,7 +7,7 @@
 # Author       : Copyright © 2025 Richard B. Romig, Mosfanet
 # Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
 # Created      : 18 Jan 2025
-# Updaged      : 26 Oct 2025
+# Updaged      : 28 Oct 2025
 # Comments     : Option to disable current swap && install ZRam.
 # TODO (Rick)  :
 # License      : GNU General Public License, version 2.0
@@ -47,6 +47,7 @@ find_current_swap() {
 
 disable_swap() {
   local swap_dev="$1"
+  sudo_login 2
   sudo sed -i.bak '/swap/s/^UUID=/# UUID=/' /etc/fstab
   sudo swapoff "$swap_dev"
   printf "%s is disabled as swap.\n" "$swap_dev"
@@ -56,39 +57,42 @@ install_zram() {
   local script_dir sed_file
   script_dir=$(dirname "$(readlink -f "${0}")")
   sed_file="zramswap.sed"
+  sudo_login 2
 	sudo apt install -y zram-tools
-  exists zramawap || "zram-tools installation failed!" 1
+  dpkg -l zram-tools | grep -q '^ii' || die "zram-tools installation failed!" 1
 	# sudo sed -i.bak '/ALGO/s/^#//;/PERCENT/s/^#//;s/50$/25/' /etc/default/zramswap
   sudo sed -i.bak -f "$script_dir/files/$sed_file" /etc/default/zramswap
   sudo systemctl restart zramswap.service
 	printf "Zram-tools installed and configured.\n"
 }
 
-main() {
-  local -r script="${0##*/}"
-  local -r version="3.4.25299"
+check_for_swap() {
   local swap_dev
   swap_dev=$(find_current_swap)
-  sudo_login 2
-  if [[ "$swap_dev" ]]; then
-    case "$swap_dev" in
-      "/dev/zram0" )
-        printf "zram-tools is installed and the active swap.\n"
-        ;;
-      * )
-        printf "Current swap is %s\n" "$swap_dev"
-        if yes_or_no "Do you want to disable $swap_dev and install zram-tools?"; then
-          disable_swap "$swap_dev"
-          install_zram
-        else
-					printf "%s remains enabled as swap.\n" "$swap_dev"
-          printf "zram-tools was not installed.\n"
-        fi
-    esac
-  else
+	if [[ -z "$swap_dev" ]]; then
     printf "No swap device detected. Installing zram-tools...\n"
     install_zram
-  fi
+		return
+	fi
+	case "$swap_dev" in
+	  "/dev/zram0" )
+	    printf "zram-tools is installed and the active swap device.\n" ;;
+	  * )
+	    printf "Current swap is %s\n" "$swap_dev"
+	    if yes_or_no "Do you want to disable $swap_dev and install zram-tools?"; then
+	      disable_swap "$swap_dev"
+	      install_zram
+	    else
+				printf "%s remains enabled as swap.\n" "$swap_dev"
+	      printf "zram-tools not installed.\n"
+	    fi
+	esac
+}
+
+main() {
+  local -r script="${0##*/}"
+  local -r version="4.0.25301"
+  check_for_swap
   printf "Active swap devices:\n"
   sudo swapon --show
   over_line "$script $version"
