install-keepassxc 0.3.5: Added space in Invalid option statement.

diff --git a/install-keepassxc b/install-keepassxc
--- a/install-keepassxc
+++ b/install-keepassxc
@@ -27,8 +27,8 @@ fi
 ## Variables ##
 
 _script=$(basename "$0"); readonly _script
-readonly _version="0.3.4"
-readonly _updated="21 Apr 2023"
+readonly _version="0.3.5"
+readonly _updated="22 May 2023"
 
 ## Functions ##
 
@@ -124,7 +124,7 @@ while getopts "$optstr" opt; do
       fi
     ;;
     ? )
-      printf "%sInvalid option -%s\n" "$red_error" "$OPTARG" >&2
+      printf "%s Invalid option -%s\n" "$red_error" "$OPTARG" >&2
       help 2
   esac
 	noOpt=0
