install-cmatrix: incorporated installed() into install_cmatrix() and main()

diff --git a/install-cmatrix b/install-cmatrix
--- a/install-cmatrix
+++ b/install-cmatrix
@@ -7,7 +7,7 @@
 # Author       : Copyright (C) 2024, Richard B. Romig, Mosfanet
 # Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
 # Created      : 2024
-# Updated      : 09 Feb 2026
+# Updated      : 24 May 2026
 # Comment      :
 # TODO (rick)  :
 # License      : GNU General Public License, version 2.0
@@ -24,30 +24,20 @@
 # GNU General Public License for more details.
 ###############################################################################
 
-### Shellcheck Directives ##
+### Source function library ##
 # shellcheck source=/home/rick/bin/functionlib
-
-## Load function library ##
-
-if [[ -x "$HOME/bin/functionlib" ]]; then
-  source "$HOME/bin/functionlib"
-else
-  printf "\e[91mERROR:\e[0m functionlib not found!\n" >&2
-  exit 1
-fi
-
-set -eu
+source ~/bin/functionlib || { printf "\e[91mERROR:\e[0m Unable to source functionlib\n"; exit 1; }
 
 ## Global Variables ##
 
 readonly script="${0##*/}"
-readonly version="1.9.26040"
+readonly version="1.10.26144"
 
 ## Functions ##
 
 help() {
   local errcode="${1:=-1}"
-  local updated="09 Feb 2026"
+  local updated="24 May 2026"
   cat << _HELP_
 ${orange}$script${normal} $version ($updated)
 Installs/Removes C-Matrix
@@ -63,18 +53,20 @@ _HELP_
 
 install_cmatrix() {
   printf "Installing C-Matrix...\n"
+  sudo_login 2
   sudo apt-get update -qq
   sudo apt-get install cmatrix cmatrix-xfont -yy
-  if grep -q '^ii' <(dpkg -l cmatrix 2>/dev/null); then
-    printf "C-Matrix installed.\n"
-  else
+  if ! installed cmatrix; then
     printf "%s cmatrix installation failed.\n" "$RED_ERROR" >&2
     EC="$E_INSTALLATION"
+    return
   fi
+  printf "C-Matrix installed.\n"
 }
 
 remove_cmatrix() {
   printf "Removing C-Matrix...\n"
+  sudo_login 2
   sudo apt-get remove cmatrix cmatrix-xfont -yy
   printf "C-Matrix removed.\n"
 }
@@ -89,16 +81,14 @@ main() {
         help 0
         ;;
       i )
-        if exists cmatrix; then
+        if installed cmatrix; then
           printf "C-Matrix already installed.\n"
         else
-          sudo_login 2
           install_cmatrix
         fi
         ;;
       r )
-        if exists cmatrix; then
-          sudo_login 2
+        if installed cmatrix; then
           remove_cmatrix
         else
           printf "C-Matrix is not installed.\n"
