install-ufw: add_default_rules() - allow SSH from local network; updated variables

diff --git a/install-ufw b/install-ufw
--- a/install-ufw
+++ b/install-ufw
@@ -1,5 +1,5 @@
 #!/usr/bin/env bash
-##########################################################################
+###############################################################################
 # Script Name  : install-ufw
 # Description  : Installs and configures the UFW firewall.
 # Dependencies : None
@@ -7,39 +7,32 @@
 # Author       : Copyright (C) Richard B. Romig, LudditeGeek@Mosfanet
 # Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
 # Created      : 05 Oct 2022
-# Updated      : 26 May 2026
-# Comments     : Install & remove for Debian-based systems only.
+# Updated      : 23 Jul 2026
+# Comments     : Install & remove for Debian-based systems (Debian, antiX, MX, BunsenLabs).
 #              : UFW should already be installed on Linux Mint & LMDE.
 # TODO (Rick)  :
 # License      : GNU General Public License, version 2.0
 # License URL  : https://github.com/RickRomig/scripts/blob/main/LICENSE
-##########################################################################
-# This program is free software; you can redistribute it and/or modify
-# it under the terms of the GNU General Public License as published by
-# the Free Software Foundation; either version 2 of the License, or
-# (at your option) any later version.
+###############################################################################
+# This program is free software; you can redistribute it and/or modify it under
+# the terms of the GNU General Public License as published by# the Free Software
+#  Foundation; either version 2 of the License, or (at your option) any later
+# version.
 #
-# This program is distributed in the hope that it will be useful,
-# but WITHOUT ANY WARRANTY; without even the implied warranty of
-# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
-# GNU General Public License for more details.
-##########################################################################
+# This program is distributed in the hope that it will be useful, but WITHOUT ANY
+# WARRANTY; without even the implied warranty of# MERCHANTABILITY or FITNESS FOR
+# A PARTICULAR PURPOSE. See the# GNU General Public License for more details.
+###############################################################################
 
-## Load function library ##
-# shellcheck source=/home/rick/bin/functionlib
-source ~/bin/functionlib || { printf "\e[91mERROR:\e[0m Unable to source functionlib\n"; exit 1; }
-
-## Global Variables ##
-
-readonly script="${0##*/}"
-readonly version="2.0.26146"
-EC=0
-
-## Functions ##
+## Source function library ##
+# shellcheck source=/home/rick/bin/functionlib.bash
+source ~/bin/functionlib,bash || { printf "\e[91mERROR:\e[0m Unable to source functionlib.bash\n"; exit 1; }
 
 help() {
-	local errcode="${1:-1}"
-	local -r updated="26 May 2026"
+  local -r script="$1"
+  local -r version="$2"
+	local -i errcode="${3:-1}"
+	local -r updated="23 Jul 2026"
 	cat << _HELP_
 ${orange}$script${normal} $version ($updated)
 Installs UFW on Debian, BunsenLabs, and MX Linux systems.
@@ -47,8 +40,8 @@ UFW/GUFW is installed by default in Linux Mint, LMDE, and Ubuntu.
 
 ${green}Usage:${normal} $script [-adehinrs]
 ${orange}Available options:${normal}
-  -a  Add rules for CUPS and SSH (XRDP if installed)
-  -d  Delete rules
+  -a  Add default rules for CUPS and SSH (Gitea/XRDP if installed)
+  -d  Delete rules by rule number
   -e  Toggle Enable/Disable UFW
   -h  Show this help message and exit
   -i  Install UFW on a Debian-based system
@@ -64,12 +57,12 @@ install_ufw() {
   sudo apt-get install ufw -yy
   if ! installed ufw; then
     printf "%s UFW installation failed.\n" "$RED_ERROR" >&2
-    EC="$E_INSTALLATION"
-    return
+    return "$E_INSTALLATION"
   fi
-  default_rules
+  add_default_rules
   enable_ufw
   printf "UFW %s installed and configured.\n" "$(ufw_version)"
+  return 0
 }
 
 remove_ufw() {
@@ -77,28 +70,36 @@ remove_ufw() {
   printf "Removing UFW (Uncomplicated Firewall) version %s...\n" "$(ufw_version)"
   sudo ufw reset  # disable UFW and delete all active rules
   sudo  apt-get purge ufw
+  return "$?"
 }
 
-default_rules() {
+add_default_rules() {
   printf "Adding rules for CUPS, SSH, XRDP...\n"
   sudo sed -i '/IPV6=no/s/no/yes/' /etc/default/ufw
   sudo ufw allow 631 && printf "CUPS (port 631) allowed.\n"
-  sudo ufw allow SSH && printf "SSH (port 22/tcp) allowed.\n"
+  # sudo ufw allow SSH && printf "SSH (port 22/tcp) allowed.\n"
+  sudo ufw allow from 192.168.0.0/24 to any port 22
+  if exists gitea; then
+    sudo ufw allow 3000/tcp
+    printf "Gitea (port 3000/tcp) allowed.\n"
+  fi
   if installed xrdp; then
     sudo ufw allow 3389/tcp
     printf "XRDP (port 3389/tcp) allowed.\n"
   fi
+  return 0
 }
 
-new_rules() {
+add_new_rules() {
   local rule="deny foo"
   sudo ufw status
   printf "Add new rules in the following format:\n"
   printf "allow/deny <protocol> or allow/deny <port-number>\n"
   while [[ "$rule" != "" ]]; do
     read -rp "Rule to be added (done to exit): " rule
-    [[ "$rule" != "" ]] && sudo ufw "$rule"
+    [[ "$rule" != "" ]] && sudo ufw delete "$rule"
   done
+  return 0
 }
 
 delete_rules() {
@@ -108,18 +109,21 @@ delete_rules() {
     read -rp "Rule to be removed (by number): " rule
     [[ "$rule" != "" ]] && sudo ufw delete "$rule"
   done
+  return 0
 }
 
 enable_ufw() {
   printf "Enabling UFW...\n"
   sudo ufw enable
   sudo ufw status verbose
+  return 0
 }
 
 disable_ufw() {
   printf "Disabling UFW...\n"
   sudo ufw disable
-  sudo ufw status
+  sudo ufw status verbose
+  return 0
 }
 
 ufw_active() {
@@ -128,18 +132,22 @@ ufw_active() {
 
 ufw_version() {
   awk 'NR==1 {print $NF}' < <(/usr/sbin/ufw version)
+  return 0
 }
 
 main() {
-  local noOpt opt optstr OPTARG OPTIND
-  noOpt=1
-  optstr=":adehinrs"
+  local -r script="${0##*/}"
+  local -r version="2.1.26204"
+  local -i exit_code=0
+  local opt OPTARG OPTIND
+  local -i noOpt=1
+  local -r optstr=":adehinrs"
   while getopts "$optstr" opt; do
     case "$opt" in
       a )
         if installed ufw; then
           sudo_login 2
-          default_rules
+          add_default_rules
           ufw_active || enable_ufw
         else
           printf "UFW is not installed.\n" >&2
@@ -149,6 +157,7 @@ main() {
         if installed ufw; then
           sudo_login 2
           delete_rules
+          ufw_active || enable_ufw
         else
           printf "UFW is not installed.\n" >&2
         fi
@@ -160,6 +169,7 @@ main() {
             printf "UFW %s is enabled.\n" "$(ufw_version)"
             default_no "Disable UFW?" && disable_ufw
           else
+            printf "UFW %s is disabled.\n" "$(ufw_version)"
             enable_ufw
           fi
         else
@@ -167,7 +177,7 @@ main() {
         fi
         ;;
       h )
-        help 0
+        help "$script" "$version" 0
         ;;
       i )
         if installed ufw; then
@@ -180,15 +190,18 @@ main() {
       n )
         if installed ufw; then
           sudo_login 2
-          new_rules
+          add_new_rules
         else
           printf "UFW is not installed.\n" >&2
         fi
         ;;
       r )
         if installed ufw; then
-          is_debian && remove_ufw
-          printf "Not a Debian system. UFW was not removed.\n" >&2
+          if is_debian; then
+            remove_ufw
+          else
+            printf "Not a Debian system. UFW was not removed.\n"
+          fi
         else
           printf "UFW is not installed.\n" >&2
         fi
@@ -197,23 +210,22 @@ main() {
         if installed ufw; then
           sudo_login 2
           printf "UFW %s\n" "$(ufw_version)"
-          sudo ufw status numbered
+          sudo ufw status verbose
         else
           printf "UFW is not installed.\n" >&2
         fi
         ;;
       ? )
         printf "%s Invalid option -%s\n" "$RED_ERROR" "$OPTARG" >&2
-        help "$E_INVALID_ARG"
+        help "$script" "$version" "$E_INVALID_ARG"
     esac
+    exit_code "$?"
     noOpt=0
   done
-  [[ "$noOpt" = 1 ]] && { printf "%s No argument passed.\n" "$RED_ERROR" >&2; help "$E_MISSING_ARG"; }
+  [[ "$noOpt" = 1 ]] && { printf "%s No argument passed.\n" "$RED_ERROR" >&2; help "$script" "$version" "$E_MISSING_ARG"; }
   shift "$(( OPTIND - 1 ))"
   over_line "$script $version"
-  exit "$EC"
+  exit "$exit_code"
 }
-
-## Execution ##
 
 main "$@"
