install-batcat: changed bat_config() to use symbolic link to cloned configs repo.

diff --git a/install-batcat b/install-batcat
--- a/install-batcat
+++ b/install-batcat
@@ -7,7 +7,7 @@
 # Author       : Copyright © 2024 Richard B. Romig, Mosfanet
 # Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
 # Created      : 03 Aug 2024
-# Last updated : 23 Feb 2025
+# Last updated : 02 May 2025
 # Comments     : the executable and its manpage will be renamed from ‘bat’ to ‘batcat’
 #              : because of a file name clash with another Debian package.
 #              : Mint 22 installs current repo version with Ubuntu version appended to the package name.
@@ -32,8 +32,8 @@ set -eu
 ## Global Variables ##
 
 script=$(basename "$0"); readonly script
-readonly version="1.7.25054"
-readonly cfg_d=$HOME"/.config/bat"
+readonly version="1.8.25123"
+# readonly cfg_d=$HOME"/.config/bat"
 
 ## Functions ##
 
@@ -57,23 +57,22 @@ _HELP_
 }
 
 assign_repo() {
-	local localip repo
+	local localip repo_dir
 	localip=$(local_ip)
+	repo_dir="$HOME/Downloads/configs"
 	case "$localip" in
 		10|16|22 )
-			repo="$HOME/gitea/configs"
-		;;
+			repo_dir="$HOME/gitea/configs" ;;
 		* )
-			if [[ -d "$HOME/Downloads/configs" ]]; then
-				pushd "$HOME/Downloads/configs" || die "pushd failed"
-				git pull --quiet origin main
+			if [[ -d "$repo_dir" ]]; then
+				pushd "$repo_dir" || die "pushd failed"
+				git pull --quiet
 				popd || die "popd failed"
 			else
-				git clone --quiet "$GITEA_URL/configs.git" "$HOME/Downloads/configs"
+				git clone --quiet "$GITHUB_URL/configs.git" "$repo_dir/configs"
 			fi
-			repo="$HOME/Downloads/configs"
 	esac
-	printf "%s" "$repo"
+	printf "%s" "$repo_dir"
 }
 
 bat_version() {
@@ -89,8 +88,8 @@ install_bat() {
 purge_config() {
   local bu_d="$HOME/.config/backup/bat"
 	if default_no "Remove configuration files?"; then
-		[[ -d "$cfg_d" ]] && rm -rf "$cfg_d"
 		[[ -d "$bu_d" ]] && rm -rf "$bu_d"
+		unlink "$HOME/.config/bat/"
 		printf "Bat configuration files removed.\n"
 	else
 		printf "Kept user configuration files.\n"
@@ -106,18 +105,17 @@ remove_bat() {
 }
 
 bat_config() {
-  local cfg_file repository
-	repository="$1"
-  cfg_file="config"
-  [[ -d "$cfg_d" ]] || mkdir -p "$cfg_d"
+  # local cfg_file repository
+	local repository="$1"
+	[[ -d "$HOME/.config/bat" ]] && rm -rf "$HOME/.config/bat"
   printf "Applying Bat configuration...\n"
-  cp -v "$repository/bat/$cfg_file" "$cfg_d/"
+	ln -s "$repository/bat" "$HOME/.config/bat/"
   printf "Bat configuration applied.\n"
 }
 
 main() {
 	local noOpt opt optstr repository
-	repository=$(assign_repo)
+	repository=$(assign_cfg_repo)
 	noOpt=1
 	optstr=":chir"
 	while getopts "$optstr" opt; do
