install-librewolf: error code variables & process substitution

diff --git a/install-librewolf b/install-librewolf
--- a/install-librewolf
+++ b/install-librewolf
@@ -7,7 +7,7 @@
 # Author       : Copyright © 2025 Richard B. Romig, Mosfanet
 # Email        : rick.romig@gmail | rick.romig@mymetronet.net
 # Created      : 01 Mar 2025
-# Updated      : 01 Dec 2025
+# Updated      : 30 Jan 2026
 # Comments     : instructions from https://librewolf.net/
 # TODO (Rick)  :
 # License      : GNU General Public License, version 2.0
@@ -33,20 +33,20 @@ if [[ -x "$HOME/bin/functionlib" ]]; then
   source "$HOME/bin/functionlib"
 else
   printf "\e[91mERROR:\e[0m functionlib not found!\n" >&2
-  exit 1
+  exit 81
 fi
 
 ## Global Variables ##
 
 readonly script="${0##*/}"
-readonly version="1.4.25335"
+readonly version="1.5.26030"
 verbose_mode="$FALSE"
 
 ## Functions ##
 
 help() {
-	local errcode="${1:-2}"
-	local -r updated=" 01 Dec 2025"
+	local errcode="${1:-1}"
+	local -r updated="30 Jan 2026"
 	cat << _HELP_
 ${orange}$script${normal} $version, Upated: $updated
 Installs/removes LibreWolf browser.
@@ -62,8 +62,8 @@ _HELP_
 }
 
 lw_version() {
-	# librewolf --version | awk '{print $NF}'
-	awk '/ii/ {print $3}' <(dpkg -l librewolf)
+	# awk '{print $NF}' <(librewolf --version)
+	awk '/^ii/ {print $3}' <(dpkg -l librewolf)
 }
 
 show_message() {
@@ -148,11 +148,11 @@ main() {
 				;;
 			? )
 				printf "%s Invalid option -%s\n" "$RED_ERROR" "$OPTARG" >&2
-				help 2
+        help "$E_INVALID_ARG"
 		esac
 		noOpt=0
 	done
-	[[ "$noOpt" = 1 ]] && { printf "%s No argument passed.\n" "$RED_ERROR" >&2; help 1; }
+  [[ "$noOpt" = 1 ]] && { printf "%s No argument passed.\n" "$RED_ERROR" >&2; help "$E_MISSING_ARG"; }
 	shift "$(( OPTIND - 1 ))"
 	over_line "$script $version"
 	exit
