install-audacious: install_audadcious() corrected process substitution redirection

diff --git a/install-audacious b/install-audacious
--- a/install-audacious
+++ b/install-audacious
@@ -7,7 +7,7 @@
 # Author       : Copyright (C) 2020, Richard B. Romig, LudditeGeek@Mosfanet
 # Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
 # Created      : 23 Mar 2020
-# Updated      : 06 May 2026
+# Updated      : 18 May 2026
 # Comments     : Does not support installation from Ubuntu PPAs or flatpak.
 # TODO (Rick)  :
 # License      : GNU General Public License, version 2.0
@@ -26,12 +26,12 @@
 
 ## Load function library ##
 # shellcheck source=/home/rick/bin/functionlib
-source functionlib || { printf "\e[91mERROR:\e[0m Unable to source functionlib\n"; exit 1; }
+source ~/bin/functionlib || { printf "\e[91mERROR:\e[0m Unable to source functionlib\n"; exit 1; }
 
 ## Global Variables ##
 
 readonly script="${0##*/}"
-readonly version="2.6.25126"
+readonly version="2.7.25138"
 E_NOT_IN_REPO=102
 EC=0
 
@@ -39,7 +39,7 @@ EC=0
 
 help() {
 	local -r errcode="${1:-1}"
-  local -r updated="06 May 2026"
+  local -r updated="18 May 2026"
 
 	cat << _HELP_
 ${orange}$script${normal} $version ($updated)
@@ -64,7 +64,7 @@ install_audacious() {
   printf "Installing Audacious audio player...\n"
   sudo apt update -qq
   sudo apt install audacious audacious-plugins -yy
-  if ! grep -q '^ii' <(dpkg -l audacious); then
+  if ! grep -q '^ii' < <(dpkg -l audacious); then
     printf "%s Audacious installation failed.\n" "$RED_ERROR" >&2
     EC="$E_INSTALLATION"
     return
