install-glow: error code variables & process substitution

diff --git a/install-glow b/install-glow
--- a/install-glow
+++ b/install-glow
@@ -7,7 +7,7 @@
 # Author       : Copyright (C) 2022, Richard B. Romig, Mosfanet
 # Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
 # Created      : 10 Jan 2022
-# Updated      : 15 Nov 2025
+# Updated      : 30 Jan 2026
 # Comments     :
 # TODO (Rick)  :
 # License      : GNU General Public License, version 2.0
@@ -33,13 +33,13 @@ if [[ -x "$HOME/bin/functionlib" ]]; then
   source "$HOME/bin/functionlib"
 else
   printf "\e[91mERROR:\e[0m functionlib not found!\n" >&2
-  exit 1
+  exit 81
 fi
 
 ## Global Variables ##
 
 readonly script="${0##*/}"
-readonly version="5.3.25319"
+readonly version="5.4.26030"
 readonly charm_url="https://repo.charm.sh/apt"
 readonly src_list="/etc/apt/sources.list.d/charm.list"
 readonly charm_key="/etc/apt/keyrings/charm.gpg"
@@ -47,8 +47,8 @@ readonly charm_key="/etc/apt/keyrings/charm.gpg"
 ## Functions ##
 
 help() {
-  local errcode="${1:-2}"
-  local updated="15 Nov 2025"
+  local errcode="${1:-1}"
+  local updated="30 Jan 2026"
   cat << _HELP_
 ${orange}$script${normal} $version ($updated)
 Installs/Removed Glow Markdown reader
@@ -64,7 +64,7 @@ _HELP_
 }
 
 glow_version() {
-  glow --version | cut -d' ' -f3
+  cut -d' ' -f3 <(glow --version)
 }
 
 add_gpg() {
@@ -155,11 +155,11 @@ main() {
         ;;
       ? )
         printf "%s Invalid option -%s\n" "$RED_ERROR" "$OPTARG" >&2
-        help 2
+        help "$E_INVALID_ARG"
     esac
 	  noOpt=0
   done
-  [[ "$noOpt" = 1 ]] && { printf "%s No argument passed.\n" "$RED_ERROR" >&2; help 1; }
+  [[ "$noOpt" = 1 ]] && { printf "%s No argument passed.\n" "$RED_ERROR" >&2; help "$E_MISSING_ARG"; }
   shift "$(( OPTIND - 1 ))"
   over_line "$script $version"
   exit
