install-zram: refactored install_zram() so function returns on failures

diff --git a/install-zram b/install-zram
--- a/install-zram
+++ b/install-zram
@@ -1,5 +1,5 @@
 #!/usr/bin/env bash
-##########################################################################
+###############################################################################
 # Script Name  : install-zram
 # Description  : installs and configures Zram-tools.
 # Dependencies : none
@@ -7,12 +7,12 @@
 # Author       : Copyright © 2025 Richard B. Romig, Mosfanet
 # Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
 # Created      : 18 Jan 2025
-# Updaged      : 04 Feb 2026
+# Updaged      : 12 May 2026
 # Comments     : Option to disable current swap && install ZRam.
 # TODO (Rick)  :
 # License      : GNU General Public License, version 2.0
 # License URL  : https://github.com/RickRomig/scripts/blob/main/LICENSE
-##########################################################################
+###############################################################################
 # This program is free software; you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
 # the Free Software Foundation; either version 2 of the License, or
@@ -22,19 +22,11 @@
 # but WITHOUT ANY WARRANTY; without even the implied warranty of
 # MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 # GNU General Public License for more details.
-##########################################################################
+###############################################################################
 
-## Shellcheck Directives ##
+## Load function library ##
 # shellcheck source=/home/rick/bin/functionlib
-
-## Source function library ##
-
-if [[ -x "$HOME/bin/functionlib" ]]; then
-  source "$HOME/bin/functionlib"
-else
-  printf "\e[91mERROR:\e[0m functionlib not found!\n" >&2
-  exit 81
-fi
+source ~/bin/functionlib || { printf "\e[91mERROR:\e[0m Unable to source functionlib\n"; exit 1; }
 
 ## Functions ##
 
@@ -58,19 +50,19 @@ install_zram() {
   sed_file="zramswap.sed"
   sudo_login 2
 	sudo apt install -y zram-tools
-  if ! grep -q '^ii' <(dpkg -l zram-tools 2</dev/null); then
-    if [[ -f "$script_dir/files/$sed_file" ]]; then
-      sudo sed -i.bak -f "$script_dir/files/$sed_file" /etc/default/zramswap
-      sudo systemctl restart zramswap.service
-	    printf "Zram-tools installed and configured.\n"
-    else
-      printf "%s not found.\n" "$sed_file" >&2
-      EC="$E_FILENOTFOUND"
-    fi
-  else
+  if ! grep -q '^ii' < <(dpkg -l zram-tools 2>/dev/null); then
     printf "zram-tools installation failed!\n"
     EC="$E_INSTALLATION"
+    return
   fi
+  if [[ ! -f "$script_dir/files/$sed_file" ]]; then
+    printf "%s not found.\n" "$sed_file" >&2
+    EC="$E_FILENOTFOUND"
+    return
+  fi
+  sudo sed -i.bak -f "$script_dir/files/$sed_file" /etc/default/zramswap
+  sudo systemctl restart zramswap.service
+	printf "Zram-tools installed and configured.\n"
 }
 
 check_for_swap() {
@@ -98,7 +90,7 @@ check_for_swap() {
 
 main() {
   local -r script="${0##*/}"
-  local -r version="4.4.26035"
+  local -r version="4.5.26132"
   EC=0
   check_for_swap
   printf "Active swap devices:\n"
