install-zram - added functionlib; install_zram(): added call to sed file and restart service.

diff --git a/install-zram b/install-zram
--- a/install-zram
+++ b/install-zram
@@ -1,26 +1,41 @@
 #!/usr/bin/env bash
 ##########################################################################
 # Script Name  : install-zram
-# Description  : installs and configures Zram swap file.
+# Description  : installs and configures Zram-tools.
 # Dependencies : none
 # Arguments    : none
 # Author       : Copyright © 2025 Richard B. Romig, Mosfanet
 # Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
 # Created      : 18 Jan 2025
-# Last updated : 18 Jan 2025
+# Updaged      : 26 Jan 2025
 # Comments     :
 # TODO (Rick)  :
 # License      : GNU General Public License, version 2.0
 ##########################################################################
+
+## Shellcheck Directives ##
+# shellcheck source=/home/rick/bin/functionlib
+
+## Source function library ##
+
+if [[ -x "$HOME/bin/functionlib" ]]; then
+  source "$HOME/bin/functionlib"
+else
+  printf "\e[91mERROR:\e[0m functionlib not found!\n" >&2
+  exit 1
+fi
 
 set -eu
 
 ## Functions ##
 
 install_zram() {
+  local sed_file="$HOME/bin/files/zramswap.sed"
 	sudo apt install -y zram-tools
-	sudo sed -i.bak '/ALGO/s/^#//;/PERCENT/s/^#//;s/50$/25/' /etc/default/zramswap
-	printf "Zram swap file installed.\n"
+	# sudo sed -i.bak '/ALGO/s/^#//;/PERCENT/s/^#//;s/50$/25/' /etc/default/zramswap
+  sudo sed -i.bak -f "$sed_file" /etc/default/zramswap
+  sudo systemctl restart zramswap.service
+	printf "Zram-tools installed.\n"
 }
 
 get_swap_type() {
@@ -29,44 +44,10 @@ get_swap_type() {
   echo "$s_type"
 }
 
-die() {
-  local errmsg errcode
-  errmsg="${1:-Undefined error}"
-  errcode="${2:-1}"
-  printf "\e[91mERROR:\e[0m %s\n" "$errmsg" >&2
-  exit "$errcode"
-}
-
-sudo_login() {
-  local delay="${1:-2}"
-  if id -nG "$USER" | grep -qw sudo; then
-    if ! sudo -vn 2>/dev/null; then
-      sudo ls > /dev/null 2>&1
-      if [[ "$delay" -gt 0 ]]; then
-        sleep "$delay"
-        printf '\e[A\e[K'
-      fi
-    fi
- else
-    die "$USER is not a member of the sudo group. Access denied."
-  fi
-}
-
-# shellcheck disable=SC2001
-over_line() {
-  local char len line title
-  title="$1"
-  char="${2:--}"
-  len=${#char}
-  (( len > 1 )) && char=${char::1}
-  line=$(echo "$title" | sed "s/./$char/g")
-  printf "%s\n%s\n"  "$line" "$title"
-}
-
 main() {
   local script version swap_type
   script=$(basename "$0")
-  version="1.1.25018"
+  version="2.0.25026"
   swap_type=$(get_swap_type)
   case "$swap_type" in
     disk )
@@ -74,7 +55,7 @@ main() {
     part )
       printf "Swap partition already exists.\n" ;;
     * )
-      printf  "No swap exists. Installing Zram swap file...\n"
+      printf  "No swap currently exists. Installing Zram-tools ...\n"
       sudo_login 2
       install_zram
   esac
