install-polybar: corrected indention

diff --git a/install-polybar b/install-polybar
--- a/install-polybar
+++ b/install-polybar
@@ -7,8 +7,8 @@
 # Author       : Copyright © 2023 Richard B. Romig, Mosfanet
 # Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
 # Created      : 16 Nov 2023
-# Updated      : 28 Jul 2026
-# Version      : 2.11.26209
+# Updated      : 08 Sep 2026
+# Version      : 2.12.26251
 # Comments     :
 # TODO (Rick)  :
 # License      : GNU General Public License, version 2.0
@@ -30,9 +30,9 @@ copy_polybar_config() {
 	local repository=~/Downloads/configs/polybar
 	[[ -d ~/gitea/configs/polybar ]] && repository=~/gitea/configs/polybar
 	if [[ ! -d "$repository" ]]; then
-    printf "%s Repository not found!\n" "$RED_ERROR" >&2
-    return "$E_FILENOTFOUND"
-  fi
+		printf "%s Repository not found!\n" "$RED_ERROR" >&2
+		return "$E_FILENOTFOUND"
+	fi
 	local -r polybar_d=~/.config/polybar
 	[[ -d "$polybar_d" ]] || mkdir -p "$polybar_d"
 	printf "Copying the Polybar configuration files ...\n"
@@ -84,9 +84,9 @@ install_polybar() {
 }
 
 main() {
-  local script="${0##*/}"
-  local version="2.11.26209"
-  local -i exit_code=0
+	local script="${0##*/}"
+	local version="2.12.26251"
+	local -i exit_code=0
 	printf "Installs Polybar on Debian with i3wm.\n"
 	if installed polybar; then
 		printf "Polybar is already installed.\n"
@@ -96,7 +96,7 @@ main() {
 	fi
 	exit_code="$?"
 	over_line "$script $version"
-  exit "$exit_code"
+	exit "$exit_code"
 }
 
 main "$@"
