install-nerdfonts: refactored - added NerdFont_inatall() to call individual functions; updated error checking

diff --git a/install-nerdfonts b/install-nerdfonts
--- a/install-nerdfonts
+++ b/install-nerdfonts
@@ -1,39 +1,32 @@
 #!/usr/bin/env bash
-##########################################################################
+###############################################################################
 # Script Name  : install-nerdfonts
-# Description  : installs nerdfonts
-# Dependencies : wget unzip
+# Description  : installs nerdfonts to ~/.local/share/fonts
+# Dependencies : wget
 # Arguments    : none
 # Author       : Copyright © 2023 Richard B. Romig, Mosfanet
 # Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
 # Created      : 28 Sep 2023
-# Last updated : 16 Apr 2026
+# Last updated : 26 Jul 2026
+# Version      : 2.0.26207
 # Comments     : system install directory = /usr/local/share/fonts
 # TODO (Rick)  :
 # License      : GNU General Public License, version 2.0
 # License URL  : https://github.com/RickRomig/scripts/blob/main/LICENSE
-##########################################################################
-# This program is free software; you can redistribute it and/or modify
-# it under the terms of the GNU General Public License as published by
-# the Free Software Foundation; either version 2 of the License, or
-# (at your option) any later version.
+###############################################################################
+# This program is free software; you can redistribute it and/or modify it under
+# the terms of the GNU General Public License as published by the Free Software
+# Foundation; either version 2 of the License, or (at your option) any later
+# version.
 #
-# This program is distributed in the hope that it will be useful,
-# but WITHOUT ANY WARRANTY; without even the implied warranty of
-# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
-# GNU General Public License for more details.
-##########################################################################
+# This program is distributed in the hope that it will be useful, but WITHOUT
+# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
+# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
+###############################################################################
 
-## Load function library ##
-# shellcheck source=/home/rick/bin/functionlib
-source functionlib || { printf "\e[91mERROR:\e[0m Unable to source functionlib\n"; exit 1; }
-
-## Global Variables ##
-
-TMP_DIR=$(mktemp -d) || die "Failed to create temporary directory." "$E_TEMP_DIR"
-
-
-## Functions ##
+## Source function library ##
+# shellcheck source=/home/rick/bin/functionlib.bash
+source functionlib.bash || { printf "\e[91mERROR:\e[0m Unable to source functionlib.bash\n"; exit 1; }
 
 # shellcheck disable=SC2317
 # Don't warn about unreachable commands in this function
@@ -44,45 +37,59 @@ cleanup() {
 
 install_NerdFonts() {
   local -r font_dir="$1"
-  local font fonts
+  local -i return_code=0
   local -r font_repo="https://github.com/ryanoasis/nerd-fonts/releases/download/v3.4.0"
+  local font fonts
   fonts=( "FiraCode" "Go-Mono" "Hack" "Inconsolata" "Iosevka" "JetBrainsMono" "Mononoki" "RobotoMono" "SourceCodePro" )
-  [[ -d "$font_dir" ]] || mkdir -p "$font_dir"
   for font in "${fonts[@]}"; do
     printf "\e[03mInstalling %s ...\e[0m\n" "$font"
     wget -q -P "$TMP_DIR" "$font_repo/$font.tar.xz"
     mkdir -p "$font_dir/$font/"
     tar xvf "$TMP_DIR/$font.tar.xz" -C "$font_dir/$font/"
+    return_code="$?"
+    (( return_code > 0 )) && break
   done
-  printf "Nerd fonts installed.\n"
+  if (( return_code > 0 )); then
+    printf "%s NerdFonts installation failed.\n" "$RED_ERROR" >&2
+  else
+    printf "Nerd fonts installed.\n"
+  fi
+  return "$return_code"
 }
 
 install_SymbolNerdFonts() {
   local -r font_dir="$1"
   local repository=~/Downloads/configs
   [[ -d ~/gitea/configs ]] && repository=~/gitea/configs
-  if [[ -d "$repository" ]]; then
-    cp -v "$repository"/local/nerdfonts/*.ttf "$font_dir/"
-    printf "Symbols Nerd Fonts installed.\n"
-  else
-    printf "%s Cloned repository not found!\n" "$RED_WARNING" >&2
-    printf "Symbols Nerd Fonts not installed.\n"
+  if [[ ! -d "$repository" ]]; then
+    printf "%s Repository directory not found!\n" "$RED_ERROR" >&2
+    printf "Symbols Nerd Fonts not installed.\n" >&2
+    return "$E_FILENOTFOUND"
   fi
+  cp -v "$repository"/local/nerdfonts/*.ttf "$font_dir/"
+  printf "Symbols Nerd Fonts installed.\n"
+  return 0
+}
+
+NerdFont_inatall() {
+  local -r font_dir=~/.local/share/fonts
+  [[ -d "$font_dir" ]] || mkdir -p "$font_dir"
+  TMP_DIR=$(mktemp -d) || die "Failed to create temporary directory." "$E_TEMP_DIR"
+  trap cleanup EXIT
+  install_NerdFonts "$font_dir" && install_SymbolNerdFonts "$font_dir"
+  return "$?"
 }
 
 main() {
   local -r script="${0##*/}"
-  local -r version="1.13.26106"
-  local -r font_dir=~/.local/share/fonts
+  local -r version="2.0.26207"
+  local -i exit_code=0
   check_packages wget
-  trap cleanup EXIT
-  install_NerdFonts "$font_dir"
-  install_SymbolNerdFonts "$font_dir"
+  NerdFont_inatall
+  exit_code="$?"
   fc-cache
   over_line "$script $version"
-  exit
+  exit "$exit_code"
 }
-
-## Execution ##
 
 main "$@"
