install-glow: charm_url & charm_key local variables passed to functions; updated remove_glow()

diff --git a/install-glow b/install-glow
--- a/install-glow
+++ b/install-glow
@@ -7,7 +7,7 @@
 # Author       : Copyright (C) 2022, Richard B. Romig, Mosfanet
 # Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
 # Created      : 10 Jan 2022
-# Updated      : 11 Apr 2026
+# Updated      : 25 May 2026
 # Comments     :
 # TODO (Rick)  :
 # License      : GNU General Public License, version 2.0
@@ -24,31 +24,21 @@
 # GNU General Public License for more details.
 ##########################################################################
 
-## Shellcheck Directives ##
-# shellcheck source=/home/rick/bin/functionlib
-
 ## Source function library ##
-
-if [[ -x "$HOME/bin/functionlib" ]]; then
-  source "$HOME/bin/functionlib"
-else
-  printf "\e[91mERROR:\e[0m functionlib not found!\n" >&2
-  exit 81
-fi
+# shellcheck source=/home/rick/bin/functionlib
+source ~/bin/functionlib || { printf "\e[91mERROR:\e[0m Unable to source functionlib\n"; exit 1; }
 
 ## Global Variables ##
 
 readonly script="${0##*/}"
-readonly version="5.7.26101"
-readonly charm_url="https://repo.charm.sh/apt"
-readonly charm_key="/etc/apt/keyrings/charm.gpg"
+readonly version="5.8.26145"
 EC=0
 
 ## Functions ##
 
 help() {
   local errcode="${1:-1}"
-  local updated="11 Apr 2026"
+  local updated="25 May 2026"
   cat << _HELP_
 ${orange}$script${normal} $version ($updated)
 Installs/Removed Glow Markdown reader
@@ -68,6 +58,8 @@ glow_version() {
 }
 
 add_gpg() {
+  local -r charm_url="$1"
+  local -r charm_key="$2"
   if [[ -f "$charm_key" ]]; then
     printf "%s already exists.\n" "${charm_key##*/}"
     return
@@ -80,6 +72,8 @@ add_gpg() {
 }
 
 add_src_list() {
+  local -r charm_url="$1"
+  local -r charm_key="$2"
   local -r src_list="/etc/apt/sources.list.d/charm.list"
   if [[ -f "$src_list" ]]; then
     printf "%s already exists.\n" "${src_list##*/}"
@@ -91,10 +85,12 @@ add_src_list() {
 }
 
 install_glow() {
+  local -r charm_url="https://repo.charm.sh/apt"
+  local -r charm_key="/etc/apt/keyrings/charm.gpg"
   printf "Installing the Glow markdown reader...\n"
   sudo_login 2
-  add_gpg
-  add_src_list
+  add_gpg "$charm_url" "$charm_key"
+  add_src_list "$charm_url" "$charm_key"
   sudo apt update && sudo apt install -y glow
   if ! grep -q '^ii' <(dpkg -l glow 2>/dev/null); then
     printf "%s Glow installation failed.\n" "$RED_ERROR" >&2
@@ -108,8 +104,9 @@ install_glow() {
 remove_glow() {
   printf "Removing the Glow markdown reader...\n"
   sudo_login 2
-  sudo apt-get -y remove glow
-  find /etc/apt =type f -name "charm*" -exec sudo rm -f {} \;
+  sudo apt-get -y purge glow
+  find /etc/apt -type f -name "charm*" -exec sudo rm -f {} \;
+  [[ -f /usr/share/man/man1/glow.1.gz ]] && sudo rm -f /usr/share/man/man1/glow.1.gz
   find ~/ -maxdepth 3 -type d -path "$HOME/Downloads" -prune -o -path "$HOME/gitea" -prune -o -type d -name glow -exec rm -rf {} \;
   printf "Glow markdown reader has been removed.\n"
 }
