install-batcat - applied main()

diff --git a/install-batcat b/install-batcat
--- a/install-batcat
+++ b/install-batcat
@@ -7,7 +7,7 @@
 # Author       : Copyright © 2024 Richard B. Romig, Mosfanet
 # Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
 # Created      : 03 Aug 2024
-# Last updated : 22 Aug 2024
+# Last updated : 30 Sep 2024
 # Comments     : the executable and its manpage will be renamed from ‘bat’ to ‘batcat’
 #              : because of a file name clash with another Debian package.
 # TODO (Rick)  :
@@ -30,27 +30,28 @@ set -eu
 
 ## Global Variables ##
 
-_script=$(basename "$0"); readonly _script
-readonly _version="1.4.24235"
-readonly _updated="22 Aug 2024"
+script=$(basename "$0"); readonly script
+readonly version="1.5.24274"
 readonly cfg_d=$HOME"/.config/bat"
 
 ## Functions ##
 
 help() {
+	local errcode updated
 	errcode="${1:-2}"
-	cat << END_HELP
-${orange}$_script${normal} $_version, Upated: $_updated
+	updated="30 Sep 2024"
+	cat << _HELP_
+${orange}$script${normal} $version, Upated: $updated
 Installs/removes/configures bat/batcat
 
-${green}Usage:${normal} $_script [OPTION]
+${green}Usage:${normal} $script [OPTION]
 
 ${orange}Available options:${normal}
-  -c  Install bat configuration
-	-h	Show help
-	-i	Install bat from Debian/Ubuntu repositories
-	-r	Remove bat and configuration
-END_HELP
+  -c	Install bat configuration
+  -h	Show help
+  -i	Install bat from Debian/Ubuntu repositories
+  -r	Remove bat and configuration
+_HELP_
   exit "$errcode"
 }
 
@@ -100,36 +101,41 @@ purge_config() {
 	fi
 }
 
+main() {
+	local noOpt opt optstr
+	noOpt=1
+	optstr=":chir"
+	while getopts "$optstr" opt; do
+		case "$opt" in
+			c )
+				exists bat || leave "Bat is not installed."
+				bat_config
+			;;
+			h )
+				help 0
+			;;
+			i )
+				exists bat && leave "Bat $(bat_version) is already installed."
+				sudo_login 2
+				check_package curl
+				install_bat
+			;;
+			r )
+				exists bat || leave "Bat is not installed."
+				sudo_login 2
+				remove_bat
+			;;
+			? )
+				printf "%s Invalid option -%s\n" "$RED_ERROR" "$OPTARG" >&2
+				help 2
+		esac
+		noOpt=0
+	done
+	[[ "$noOpt" = 1 ]] && { printf "%s No argument passed.\n" "$RED_ERROR" >&2; help 1; }
+	shift "$(( OPTIND - 1 ))"
+	leave "$script $version"
+}
+
 ## Execution ##
 
-check_package curl
-noOpt=1
-optstr=":chir"
-while getopts "$optstr" opt; do
-	case "$opt" in
-		c )
-			exists bat || leave "Bat is not installed."
-			bat_config
-		;;
-		h )
-			help 0
-		;;
-		i )
-			exists bat && leave "Bat $(bat_version) is already installed."
-			sudo_login 2
-			install_bat
-		;;
-		r )
-			exists bat || leave "Bat is not installed."
-			sudo_login 2
-			remove_bat
-		;;
-		? )
-			printf "%s Invalid option -%s\n" "$red_error" "$OPTARG" >&2
-			help 2
-	esac
-	noOpt=0
-done
-[[ "$noOpt" = 1 ]] && { printf "%s No argument passed.\n" "$red_error" >&2; help 1; }
-shift "$(( OPTIND - 1 ))"
-leave "$_script $_version"
+main "$@"
