install-codium: moved install checks to install, remove, & settings functions

diff --git a/install-codium b/install-codium
--- a/install-codium
+++ b/install-codium
@@ -7,7 +7,8 @@
 # Author       : Copyright © 2023 Richard B. Romig, Mosfanet
 # Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
 # Created      : 04 Aug 2023
-# Updated      : 19 Jul 2026
+# Updated      : 12 Aug 2026
+# Version      : 5.3.26224
 # Comments     : Alternative to downloading directly from GitHub repo.
 # TODO (Rick)  : add flatpak installation...
 # License      : GNU General Public License, version 2.0
@@ -23,15 +24,16 @@
 # OR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
 ################################################################################
 
-## Source function library ##
 # shellcheck source=/home/rick/bin/functionlib.bash
 source ~/bin/functionlib.bash || { printf "\e[91mERROR:\e[0m Unable to source functionlib.bash\n"; exit 1; }
+
+VERBOSE="FALSE"
 
 help() {
 	local -r script="$1"
 	local -r version="$2"
-	local -r errcode="${3:-1}"
-	local -f updated="19 Jul 2026"
+	local -ri errcode="${3:-1}"
+	local -f updated="12 Aug 2026"
 	cat << _HELP_
 ${orange}$script${normal} $version, updated: ($updated)
 Install/Remove VSCodium and apply settings
@@ -49,7 +51,10 @@ _HELP_
 }
 
 check_dependencies() {
-  [[ $(uname -m) == "x86_64" ]] || die "System architecture is not 64-bit." 1
+	if [[ $(uname -m) == "x86_64" ]]; then
+    printf "%s System architecture is not 64-bit.\n" "$RED_ERROR" >&2
+    return "$E_UNSUPPORTED"
+	fi
   local packages=( git wget )
   check_packages "${packages[@]}"
 	return 0
@@ -63,6 +68,7 @@ codium_version() {
 set_gpg_key() {
 	local -r key_file="$1"
 	local -r key_url="https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/raw/master/pub.gpg"
+	sudo_login 2
 	show_message "Setting the GPG key..."
 	sudo wget "$key_url" -O "$key_file"
 	show_message "GPG key is set."
@@ -73,6 +79,7 @@ set_sources() {
 	local -r key_file="$1"
 	local -r sources_file=/etc/apt/sources.list.d/vscodium.sources
 	local -r sources_uri="https://paulcarroty.gitlab.io/vscodium-deb-rpm-repo/debs"
+	sudo_login 2
 	if [[ -f /etc/apt/sources.list.d/vscodium.list ]]; then
 		show_message "Renaming old source list file..."
 		sudo mv /etc/apt/sources.list.d/vscodium.list /etc/apt/sources.list.d/vscodium.list.bak
@@ -90,7 +97,12 @@ Signed-By: $key_file"
 }
 
 install_vscodium() {
+	if installed codium; then
+    printf "VSCodium %s is already installed." "$(codium_version)"
+    return 0
+	fi
 	local -r key_file="$1"
+	sudo_login 2
 	show_message "Installing VSCodium..."
 	set_gpg_key "$key_file"
 	set_sources "$key_file"
@@ -107,6 +119,10 @@ install_vscodium() {
 }
 
 apply_settings() {
+	if installed codium; then
+    printf "VSCodium %s is already installed." "$(codium_version)"
+    return 0
+	fi
 	if [[ ! -d ~/Downloads/configs && ! -d ~/gitea/configs ]]; then
 		printf "%s Repository not found!\n" "$RED_WARNING" >&2
 		return "$E_FILENOTFOUND"
@@ -121,6 +137,11 @@ apply_settings() {
 }
 
 remove_vscodium() {
+  if ! installed codium; then
+    printf "VSCodium is not installed.\n"
+    return 0
+  fi
+	sudo_login 2
 	show_message "Removing VSCodium..."
 	sudo apt-get purge codium
 	show_message "Removing VSCodium configuration files ..."
@@ -141,9 +162,8 @@ show_message() {
 }
 
 main() {
-	VERBOSE="$FALSE"
 	local -r script="${0##*/}"
-	local -r version="5.2.26200"
+	local -r version="5.3.26224"
 	local -i exit_code=0
 	local -r key_file="/usr/share/keyrings/vscodium-archive-keyring.asc"
   local opt OPTARG OPTIND
@@ -152,9 +172,8 @@ main() {
 	while getopts "$optstr" opt; do
 		case "$opt" in
 			a)
-				# Set apt gpg key and source list
+				# Set apt gpg key and source list for existing installation
 				if installed codium; then
-					sudo_login 2
 					set_gpg_key "$key_file"
 					set_sources "$key_file"
 				else
@@ -165,31 +184,14 @@ main() {
 				help "$script" "$version" 0
 				;;
 			i )
-				# Install VSCodium via apt
-				if installed codium; then
-					printf "VSCodium %s is already installed.\n" "$(codium_version)"
-				else
-					sudo_login 2
 					check_dependencies
-					install_vscodium "$key_file"
-				fi
+					install_vscodium "$key_file" && apply_settings
 				;;
 			r )
-				# Remove VSCodium
-				if installed codium; then
-					sudo_login 2
-					remove_vscodium
-				else
-					printf "VSCodium is not installed.\n" >&2
-				fi
+				remove_vscodium
 				;;
 			s )
-				# Apply VSCodium settings
-				if installed codium; then
 					apply_settings
-				else
-					printf "VSCodium is not installed.\n" >&2
-				fi
 				;;
 			v )
 				VERBOSE="$TRUE"
@@ -202,7 +204,10 @@ main() {
 		exit_code="$?"
 		noOpt=0
 	done
-	[[ "$noOpt" = 1 ]] && { printf "%s No argument passed.\n" "$RED_ERROR" >&2; help "$script" "$version" "$E_MISSING_ARG"; }
+	if (( noOpt == 1 )); then
+		printf "%s No argument passed.\n" "$RED_ERROR" >&2
+		help "$script" "$version" "$E_MISSING_ARG"
+	fi
 	shift "$(( OPTIND - 1 ))"
   over_line "$script $version"
   exit "$exit_code"
