install-batcat: replaced EC variable with return codes; script & version local vars in main()

diff --git a/install-batcat b/install-batcat
--- a/install-batcat
+++ b/install-batcat
@@ -7,7 +7,7 @@
 # Author       : Copyright © 2024 Richard B. Romig, Mosfanet
 # Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
 # Created      : 03 Aug 2024
-# Last updated : 14 Jun 2026
+# Last updated : 09 Jul 2026
 # Comments     : executable and its manpage will be renamed from ‘bat’ to ‘batcat’
 #              : because of a file name clash with another Debian package.
 #              : Mint 22 installs version 0.24.0 with suffix.
@@ -27,21 +27,15 @@
 # GNU General Public License for more details.
 ##########################################################################
 
-## Load function library ##
+## Source function library ##
 # shellcheck source=/home/rick/bin/functionlib
 source ~/bin/functionlib || { printf "\e[91mERROR:\e[0m Unable to source functionlib\n"; exit 1; }
 
-## Global Variables ##
-
-readonly script="${0##*/}"
-readonly version="2.13.26165"
-EC=0
-
-## Functions ##
-
 help() {
-	local errcode="${1:-1}"
-	local updated="14 Jun 2026"
+	local -r script="$1"
+	local -r version="$2"
+	local -r errcode="${3:-1}"
+	local -r updated="09 Jul 2026"
 	cat << _HELP_
 ${orange}$script${normal} $version, Updated: $updated
 Installs/removes/configures bat/batcat
@@ -59,6 +53,7 @@ _HELP_
 
 bat_version() {
   awk '/^ii/ {print $3}' < <(dpkg -l bat)
+	return 0
 }
 
 install_batcat() {
@@ -66,11 +61,11 @@ install_batcat() {
 	sudo apt-get install -yy bat
 	if ! exists batcat; then
 		printf "%s Batcat failed to install."  "$RED_ERROR" >&2
-    EC="$E_INSTALLATION"
-		return
+		return "$E_INSTALLATION"
 	fi
 	printf "Bat (Batcat) version %s installed.\n" "$(bat_version)"
 	bat_config
+	return 0
 }
 
 remove_batcat() {
@@ -86,14 +81,14 @@ remove_batcat() {
 		printf "User configuration files retained.\n"
 	fi
   printf "Batcat has been removed.\n"
+	return 0
 }
 
 bat_config() {
 	[[ -d ~/.config/bat ]] || mkdir -p ~/.config/bat
 	if [[ ! -d ~/Downloads/configs && ! -d ~/gitea/configs ]]; then
 		printf "%s Cloned repository not found!\n" "$RED_WARNING" >&2
-		EC="$E_FILENOTFOUND"
-		return
+		return "$E_FILENOTFOUND"
 	fi
   printf "Applying Bat configuration...\n"
 	[[ -f ~/.config/bat/config ]] && rm ~/.config/bat/config
@@ -104,12 +99,16 @@ bat_config() {
 		ln -sv /usr/bin/batcat ~/.local/bin/bat
 	fi
   printf "Bat configuration applied.\n"
+	return 0
 }
 
 main() {
-	local noOpt opt optstr OPTARG OPTIND
-	noOpt=1
-	optstr=":chir"
+	local -r script="${0##*/}"
+	local -r version="2.14.26190"
+	local -i exit_code=0
+	local opt OPTARG OPTIND
+	local -i noOpt=1
+	local -r optstr=":chir"
 	while getopts "$optstr" opt; do
 		case "$opt" in
 			c )
@@ -120,7 +119,7 @@ main() {
 				fi
 				;;
 			h )
-				help 0
+				help "$script" "$version" 0
 				;;
 			i )
 				if installed bat; then
@@ -138,16 +137,15 @@ main() {
 				;;
 			? )
 				printf "%s Invalid option -%s\n" "$RED_ERROR" "$OPTARG" >&2
-				help "$E_INVALID_ARG"
+				help "$script" "$version" "$E_INVALID_ARG"
 		esac
+		exit_code="$?"
 		noOpt=0
 	done
-	[[ "$noOpt" = 1 ]] && { printf "%s No argument passed.\n" "$RED_ERROR" >&2; help "$E_MISSING_ARG"; }
+	[[ "$noOpt" = 1 ]] && { printf "%s No argument passed.\n" "$RED_ERROR" >&2; help "$script" "$version" "$E_MISSING_ARG"; }
 	shift "$(( OPTIND - 1 ))"
 	over_line "$script $version"
-	exit "$EC"
+	exit "$exit_code"
 }
-
-## Execution ##
 
 main "$@"
