install-firefox-deb: mozilla_deb() changed grep pattern to check for DEB version; mozilla_asc is now local variable

diff --git a/install-firefox-deb b/install-firefox-deb
--- a/install-firefox-deb
+++ b/install-firefox-deb
@@ -7,7 +7,7 @@
 # Author       : Copyright © 2024 Richard B. Romig, Mosfanet
 # Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
 # Created      : 24 Jan 2024
-# Updated      : 11 Apr 2026
+# Updated      : 25 May 2026
 # Comments     : Remove Distro, Flatpak, or Snap version before installing.
 # TODO (Rick)  :
 # License      : GNU General Public License, version 2.0
@@ -26,13 +26,12 @@
 
 ## Source function library ##
 # shellcheck source=/home/rick/bin/functionlib
-source functionlib || { printf "\e[91mERROR:\e[0m Unable to source functionlib\n"; exit 1; }
+source ~/bin/functionlib || { printf "\e[91mERROR:\e[0m Unable to source functionlib\n"; exit 1; }
 
 ## Global Variables ##
 
 readonly script="${0##*/}"
-readonly version="6.5.26101"
-readonly mozilla_asc="/etc/apt/keyrings/packages.mozilla.org.asc"
+readonly version="6.6.26145"
 verbose_mode="$FALSE"
 EC=0
 
@@ -40,7 +39,7 @@ EC=0
 
 help() {
 	local errcode="${1:-1}"
-	local -r updated="11 Apr 2026"
+	local -r updated="25 May 2026"
 	cat << _HELP_
 ${orange}$script${normal} $version, Upated: $updated
 Installs/Removes Mozilla repository version of Firefox.
@@ -65,14 +64,14 @@ firefox_version() {
 }
 
 mozilla_deb() {
-	grep -q 'Mozilla Firefox' <(dpkg -l firefox) && return "$TRUE" || return "$FALSE"
+	grep -q 'ii.*build' < <(dpkg -l firefox) && return "$TRUE" || return "$FALSE"
 }
 
 other_firefox() {
-	grep -q '^ii' <(dpkg -l firefox-esr) && return "$TRUE"
-	grep -q 'ii.*linuxmint' <(dpkg -l firefox) && return "$TRUE"
+	grep -q '^ii' < <(dpkg -l firefox-esr) && return "$TRUE"
+	grep -q 'ii.*linuxmint' < <(dpkg -l firefox) && return "$TRUE"
 	if exist flatpak; then
-		grep -q firefox <(flatpak list) && return "$TRUE"
+		grep -q firefox < <(flatpak list) && return "$TRUE"
 	fi
 	return "$FALSE"
 }
@@ -89,6 +88,7 @@ Pin-Priority: 1000
 }
 
 set_gpg_key() {
+	local -r mozilla_asc="$1"
 	local -r key_url="https://packages.mozilla.org/apt/repo-signing-key.gpg"
 	if [[ -f "$mozilla_asc" ]]; then
 		printf "%s already exists.\n" "${mozilla_asc##*/}"
@@ -101,6 +101,7 @@ set_gpg_key() {
 }
 
 set_sources_list() {
+	local -r mozilla_asc="$1"
 	local -r mozilla_list="/etc/apt/sources.list.d/mozilla.list"
 	local -r list_url="https://packages.mozilla.org/apt"
 	if [[ -f "$mozilla_list" ]]; then
@@ -117,15 +118,16 @@ install_mozilla_deb() {
 		printf "Remove before installing the Mozilla package.\n" >&2
 		return
 	fi
+	local -r mozilla_asc="/etc/apt/keyrings/packages.mozilla.org.asc"
 	printf "Installing the Mozilla Firefox DEB package...\n"
-	set_gpg_key
-	set_sources_list
+	set_gpg_key "$mozilla_asc"
+	set_sources_list "$mozilla_asc"
 	create_preference_file
 	show_message "Updating apt cache..."
 	sudo apt-get update
 	show_message "Installing Firefox..."
 	sudo apt-get install -y firefox
-	if ! grep -q '^ii' <(dpkg -l firefox 2>/dev/null); then
+	if ! installed firefox; then
 		printf "%s Firefox installation failed.\n" "$RED_ERROR" >&2
     EC="$E_INSTALLATION"
     return
