install-boxes: functions return if EC is set to non-zero value to exit with EC exit code

diff --git a/install-boxes b/install-boxes
--- a/install-boxes
+++ b/install-boxes
@@ -7,7 +7,7 @@
 # Author       : Copyright (C) 2020, Richard B. Romig
 # Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
 # Created      : 29 Feb 2020
-# Updated      : 21 Mar 2026
+# Updated      : 11 Apr 2026
 # Comments     : Based on instructions from Joe Collins.
 # TODO (Rick)  : check entry in flatpak list
 # License      : GNU General Public License, version 2.0
@@ -38,15 +38,15 @@ fi
 
 ## Global Variables ##
 readonly script="${0##*/}"
-readonly version="3.0.26080"
-readonly E_BIOS_SETTING=99
+readonly version="4.0.26101"
+readonly E_BIOS_SETTING=100
 EC=0
 
 ## Functions ##
 
 help() {
 	local errcode="${1:-1}"
-	local updated="21 Mar 2026"
+	local updated="11 Apr 2026"
 	cat << _HELP_
 ${orange}$script${normal} $version, Upated: $updated
 Install Gnome Boxes from either distribution repositories or flatpak from Flathub.
@@ -66,23 +66,24 @@ check_bios() {
   printf "Checking if virtualization is enabled in BIOS...\n"
   vcpu=$(grep -Ec 'vmx|svm' /proc/cpuinfo)
   printf "Virtualization is "
-  if [[ "$vcpu" -eq 0 ]]; then
+  if [[ $vcpu -eq 0 ]]; then
     printf "not enabled in the BIOS.\n" >&2
     printf "Enable virtualization before installing Gnome Boxes.\n" >&2
-    exit "$E_BIOS_SETTING"
+    EC="$E_BIOS_SETTING"
+    return
   fi
   printf "enabled in the BIOS. (%d threads)\n" "$vcpu"
   vmx_svm=$(grep -E -m 1 'vmx|svm' /proc/cpuinfo )
   case "$vmx_svm" in
     *vmx* )
-      # sudo sh -c 'echo "options kvm_intel nested=1" >> /etc/modprobe.d/qemu-system-x86.conf' ;;
-      echo "options kvm_intel nested=1" | sudo tee -a "$qemu_conf" >/dev/null ;;
+      # echo "options kvm_intel nested=1" | sudo tee -a "$qemu_conf" >/dev/null ;;
+      sudo tee -a "$qemu_conf" >/dev/null <<< "options kvm_intel nested=1" ;;
     *svm* )
-      # sudo sh -c 'echo "options kvm_amd nested=1" >> /etc/modprobe.d/qemu-system-x86.conf' ;;
-      echo "options kvm_amd nested=1" | sudo tee -a "$qemu_conf" >/dev/null ;;
+      # echo "options kvm_amd nested=1" | sudo tee -a "$qemu_conf" >/dev/null ;;
+      sudo tee -a "$qemu_conf" >/dev/null <<< "options kvm_amd nested=1"
   esac
-  # sudo sh -c 'echo "group=kvm" >> /etc/modprobe.d/qemu-system-x86.conf'
-  echo "group=kvm" | sudo tee -a "$qemu_conf" >/dev/null
+  # echo "group=kvm" | sudo tee -a "$qemu_conf" >/dev/null
+  sudo tee -a "$qemu_conf" >/dev/null <<< "group=kvm"
 }
 
 enable_libvirtd() {
@@ -103,39 +104,42 @@ add_to_kvm_group() {
     printf "added to "
   fi
   printf "the kvm group.\n"
-  if [[ -f /etc/libvirt/qemu.conf ]]; then
-    printf "Allow users in the kvm group to start VMs.\n"
-    sudo sed -i.bak 's/\#group\ =\ "root"/group\ =\ "kvm"/' /etc/libvirt/qemu.conf
-    enable_libvirtd
-  else
+
+  if [[ ! -f /etc/libvirt/qemu.conf ]]; then
     printf "/etc/libvirt/qemu.conf not found!\n" >&2
     EC="$E_FILENOTFOUND"
+    return
   fi
+  printf "Allow users in the kvm group to start VMs.\n"
+  sudo sed -i.bak 's/\#group\ =\ "root"/group\ =\ "kvm"/' /etc/libvirt/qemu.conf
+  enable_libvirtd
 }
 
 install_boxes() {
+  [[ EC -ne 0 ]] && return
   printf "\nInstalling GNOME Boxes (distro)...\n"
   sudo apt update -qq
   sudo apt install -yy gnome-boxes qemu-kvm
-  if exists gnome-boxes; then
-    printf "Gnome-boxes installed.\n"
-    add_to_kvm_group
-  else
+  if ! exists gnome-boxes; then
     printf "%s Gnome-boxes installation failed.\n" "$RED_ERROR" >&2
     EC="$E_INSTALLATION"
+    return
   fi
+  printf "Gnome-boxes installed.\n"
+  add_to_kvm_group
 }
 
 install_flatpak() {
+  [[ EC -ne 0 ]] && return
   printf "\nInstalling GNOME Boxes (flatpak)...\n"
   flatpak install --user flathub org.gnome.Boxes
-  if grep -qi 'boxes' <(flatpak list); then
-    printf "Gnome-Boxes installed.\n"
-    add_to_kvm_group
-  else
+  if ! grep -qi 'boxes' <(flatpak list); then
     printf "%s Gnome-boxes installation failed.\n" "$RED_ERROR" >&2
     EC="$E_INSTALLATION"
+    return
   fi
+  printf "Gnome-Boxes installed.\n"
+  add_to_kvm_group
 }
 
 main() {
@@ -163,9 +167,9 @@ main() {
     esac
     noOpt=0
   done
-	[[ "$noOpt" = 1 ]] && { printf "%s No argument passed.\n" "$RED_ERROR" >&2; help "$E_MISSING_ARG"; }
+	[[ $noOpt -eq 1 ]] && { printf "%s No argument passed.\n" "$RED_ERROR" >&2; help "$E_MISSING_ARG"; }
 	shift "$(( OPTIND - 1 ))"
-  [[ "$EC" -eq 0 ]] && printf "Gnome boxes installed and configured.\n"
+  [[ $EC -eq 0 ]] && printf "Gnome boxes installed and configured.\n"
   over_line "$script $version"
   exit "$EC"
 }
