install-batcat: bat_config() - added check for config repositories

diff --git a/install-batcat b/install-batcat
--- a/install-batcat
+++ b/install-batcat
@@ -7,7 +7,7 @@
 # Author       : Copyright © 2024 Richard B. Romig, Mosfanet
 # Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
 # Created      : 03 Aug 2024
-# Last updated : 22 Oct 2025
+# Last updated : 24 Oct 2025
 # Comments     : executable and its manpage will be renamed from ‘bat’ to ‘batcat’
 #              : because of a file name clash with another Debian package.
 #              : Mint 22 installs version 0.24.0 with suffix.
@@ -42,13 +42,13 @@ fi
 ## Global Variables ##
 
 readonly script="${0##*/}"
-readonly version="2.7.25295"
+readonly version="2.7.25297"
 
 ## Functions ##
 
 help() {
 	local errcode="${1:-2}"
-	local updated="22 Oct 2025"
+	local updated="24 Oct 2025"
 	cat << _HELP_
 ${orange}$script${normal} $version, Updated: $updated
 Installs/removes/configures bat/batcat
@@ -91,6 +91,10 @@ remove_batcat() {
 
 bat_config() {
 	[[ -d ~/.config/bat ]] || mkdir -p ~/.config/bat
+	if [[ ! -d ~/Downloads/configs && ! -d ~/gitea/configs ]]; then
+		printf "%s Cloned repository not found!\n" "$RED_WARNING" >&2
+		return
+	fi
   printf "Applying Bat configuration...\n"
 	[[ -f ~/.config/bat/config ]] && rm ~/.config/bat/config
 	[[ -d ~/gitea/configs ]] && ln -sv ~/gitea/configs/bat/config ~/.config/bat/config
