install-chrome: install_chrome() - added check if installation successful

diff --git a/install-chrome b/install-chrome
--- a/install-chrome
+++ b/install-chrome
@@ -7,7 +7,7 @@
 # Author       : Copyright (C) 2019 Richard B. Romig, Mosfanet
 # Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
 # Created      : 18 Jul 2019
-# Updated      : 19 Jul 2025
+# Updated      : 22 Oct 2025
 # Comments     : Google Chrome updates through apt from source list
 # TODO (rick)  :
 # License      : GNU General Public License, version 2.0
@@ -39,7 +39,7 @@ fi
 ## Variables ##
 
 readonly script="${0##*/}"
-readonly version="4.0.25200"
+readonly version="4.9.25295"
 readonly chrome_list="/etc/apt/sources.list.d/google-chrome.list"
 readonly keyring_dir="/usr/share/keyrings"
 readonly trusted_key="google-chrome.gpg"
@@ -48,7 +48,7 @@ readonly trusted_key="google-chrome.gpg"
 
 help() {
 	local errcode="${1:-2}"
-	local -r updated="19 Jul 2025"
+	local -r updated="22 Oct 2025"
 	cat << _HELP_
 ${orange}$script${normal} $version ($updated)
 Installs, updated, or removes Google Chrome.
@@ -58,13 +58,13 @@ ${orange}Available options:${normal}
   -h  Show this help message and exit
   -i  Install Google Chrome
   -r  Remove Google Chrome
-  -u  Update Google Chrome (normally throught apt updates)
+  -u  Update Google Chrome (normally through apt updates)
 _HELP_
   exit "$errcode"
 }
 
 chrome_version() {
-  google-chrome-stable --version | cut -d' ' -f3
+  google-chrome-stable --version
 }
 
 install_chrome() {
@@ -73,12 +73,10 @@ install_chrome() {
   source_list="deb [arch=amd64 signed-by=/usr/share/keyrings/google-chrome.gpg] http://dl.google.com/linux/chrome/deb/ stable main"
   curl -fSsL "$trusted_key_url" | gpg --dearmor | sudo tee "$keyring_dir/$trusted_key" > /dev/null
   echo "$source_list" | sudo tee "$chrome_list" > /dev/null
-  sudo apt update
-  if sudo apt-get install -y google-chrome-stable; then
-    printf "Google Chrome %s successfully installed.\n" "$(chrome_version)"
-  else
-    printf "Google Chrome installation failed.\n" >&2
-  fi
+  sudo apt update -qq
+  sudo apt-get install -y google-chrome-stable
+  exists google-chrome-stable || die "Google Chrome installation failed." 1
+  printf "%s successfully installed.\n" "$(chrome_version)"
 }
 
 purge_chrome() {
@@ -101,7 +99,7 @@ main() {
         ;;
       i )
         if exists google-chrome-stable; then
-          printf "Google Chrome %s is already installed.\n" "$(chrome_version)" >&2
+          printf "%s is already installed.\n" "$(chrome_version)" >&2
         else
           sudo_login 2
           check_package wget
