install-chrome: updated error handling

diff --git a/install-chrome b/install-chrome
--- a/install-chrome
+++ b/install-chrome
@@ -7,7 +7,7 @@
 # Author       : Copyright (C) 2019 Richard B. Romig, Mosfanet
 # Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
 # Created      : 18 Jul 2019
-# Updated      : 30 Nov 2025
+# Updated      : 02 Feb 2026
 # Comments     : Google Chrome updates through apt from source list
 # TODO (rick)  :
 # License      : GNU General Public License, version 2.0
@@ -33,21 +33,22 @@ if [[ -x "$HOME/bin/functionlib" ]]; then
   source "$HOME/bin/functionlib"
 else
   printf "\e[91mERROR:\e[0m functionlib not found!\n" >&2
-  exit 1
+  exit 81
 fi
 
 ## Variables ##
 
 readonly script="${0##*/}"
-readonly version="5.1.25331"
+readonly version="5.2.26033"
 readonly chrome_list="/etc/apt/sources.list.d/google-chrome.list"
 readonly trusted_key="/usr/share/keyrings/google-chrome.gpg"
+EC=0
 
 ## Functions ##
 
 help() {
-	local errcode="${1:-2}"
-	local -r updated="15 No 2025"
+	local errcode="${1:-1}"
+	local -r updated="02 Feb 2026"
 	cat << _HELP_
 ${orange}$script${normal} $version ($updated)
 Installs, updated, or removes Google Chrome.
@@ -93,7 +94,12 @@ install_chrome() {
   sudo apt update -qq
   sudo apt-get install -y google-chrome-stable
   exists google-chrome-stable || die "Google Chrome installation failed." 1
-  printf "%s successfully installed.\n" "$(chrome_version)"
+  if grep '^ii' <(dpkg -l google-chrome-stable); then
+    printf "%s successfully installed.\n" "$(chrome_version)"
+  else
+    printf "%s Google Chrome installation failed.\n" "$RED_ERROR" >&2
+    EC="$E_INSTALLATION"
+  fi
 }
 
 purge_chrome() {
@@ -133,14 +139,14 @@ main() {
         ;;
       ? )
         printf "%s Invalid option -%s\n" "$RED_ERROR" "$OPTARG" >&2
-        help 2
+        help "$E_INVALID_ARG"
     esac
 	  noOpt=0
   done
-  [[ "$noOpt" = 1 ]] && { printf "%s No argument passed.\n" "$RED_ERROR" >&2; help 1; }
+  [[ "$noOpt" = 1 ]] && { printf "%s No argument passed.\n" "$RED_ERROR" >&2; help "$E_MISSING_ARG"; }
   shift "$(( OPTIND - 1 ))"
   over_line "$script $version"
-  exit
+  exit "$EC"
 }
 
 ## Execution ##
