install-brave-browser: moved existence checks to appropriate functions

diff --git a/install-brave-browser b/install-brave-browser
--- a/install-brave-browser
+++ b/install-brave-browser
@@ -1,13 +1,14 @@
 #!/usr/bin/env bash
 ###############################################################################
-# Script Name  : install-brave
+# Script Name  : install-brave-browser
 # Description  : installs the Brave broswer
 # Dependencies : apt-transport-https, curl, libu2f-udev
 # Arguments    : see help function
 # Author       : Copyright (C) 2019, Richard B. Romig
 # Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
 # Created      : 12 Dec 2019
-# Updated      : 19 Jul 2026
+# Updated      : 12 Aug 2026
+# Version      : 7.4.26224
 # Comments     : For Debian, Ubuntu, Mint ... (Code from Brave's instructions)
 #              : Brave is only supported on 64-bit AMD/Intel architectures (amd64/x86_64).
 # TODO (Rick)  :
@@ -24,15 +25,16 @@
 # FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
 ###############################################################################
 
-## Source function library ##
 # shellcheck source=/home/rick/bin/functionlib.bash
 source functionlib.bash || { printf "\e[91mERROR:\e[0m Unable to source functionlib.bash\n"; exit 1; }
+
+VERBOSE="FALSE"
 
 help() {
   local -r script="$1"
   local -r version="$2"
-  local -r errcode="${3:-1}"
-  local -r updated="18 Jul 2026"
+  local -ri errcode="${3:-1}"
+  local -r updated="12 Aug 2026"
   cat << _HELP_
 ${orange}$script${normal} $version, Updated: ($updated)
 Installs/Removes the Brave browser
@@ -49,6 +51,10 @@ _HELP_
 
 check_dependencies() {
   [[ $(uname -m) == "x86_64" ]] || die "System architecture is not 64-bit." 1
+  if [[ ! $(uname -m) == "x86_64" ]]; then
+    printf "%s System architecture is not 64-bit.\n" "$RED_ERROR" >&2
+    return "$E_UNSUPPORTED"
+  fi
   local packages=( apt-transport-https curl libu2f-udev )
   check_packages "${packages[@]}"
   return 0
@@ -98,7 +104,12 @@ Signed-By: $key_file"
 }
 
 install_brave() {
+  if installed brave-browser; then
+    printf "%s is already installed." "$(brave_ver)"
+    return 0
+  fi
   local -r brave_key=/usr/share/keyrings/brave-browser-archive-keyring.gpg
+  sudo_login 2
   printf "Installing the Brave Browser ...\n"
   set_gpg_key "$brave_key"
   set_sources "$brave_key"
@@ -114,6 +125,11 @@ install_brave() {
 }
 
 remove_brave() {
+  if ! installed brave-browser; then
+    printf "Brave Browser is not installed.\n"
+    return 0
+  fi
+  sudo_login 2
   printf "Uninstalling %s...\n" "$(brave_ver)"
   sudo apt-get remove brave-browser brave-keyring -yy
   show_message "Removing Brave sources..."
@@ -127,9 +143,8 @@ remove_brave() {
 }
 
 main(){
-  VERBOSE="FALSE"
   local -r script="${0##*/}"
-  local -r version="7.3.26200"
+  local -r version="7.4.26224"
   local -i exit_code=0
   local opt OPTARG OPTIND
   local -i noOpt=1
@@ -137,29 +152,14 @@ main(){
   while getopts "$optstr" opt; do
     case "$opt" in
       h )
-        help "$script" "$version" 0
-        ;;
+        help "$script" "$version" 0 ;;
       i )
-        if installed brave-browser; then
-          printf "%s is already installed." "$(brave_ver)"
-        else
-          sudo_login 2
-          check_dependencies
-          install_brave
-        fi
-        ;;
+        check_dependencies && install_brave ;;
       r )
-        if installed brave-browser; then
-          sudo_login 2
-          remove_brave
-        else
-          printf "Brave Browser is not installed.\n"
-        fi
-        ;;
+        remove_brave ;;
 			v )
 				VERBOSE="$TRUE"
-				show_message "Verbose mode enabled."
-			  ;;
+				show_message "Verbose mode enabled." ;;
       ? )
         printf "%s Invalid option -%s\n" "$RED_ERROR" "$OPTARG" >&2
         help "$script" "$version" "$E_INVALID_ARG"
@@ -167,7 +167,10 @@ main(){
     exit_code="$?"
     noOpt=0
   done
-  [[ "$noOpt" = 1 ]] && { printf "%s No argument passed.\n" "$RED_ERROR" >&2; help "$script" "$version" "$E_MISSING_ARG"; }
+	if (( noOpt == 1 )); then
+		printf "%s No argument passed.\n" "$RED_ERROR" >&2
+		help "$script" "$version" "$E_MISSING_ARG"
+	fi
   shift "$(( OPTIND - 1 ))"
   over_line "$script $version"
   exit "$exit_code"
