install-audioapps: moved sudo_login & apt-get update to install_audio_apps(); replaced exists() with installed()

diff --git a/install-audioapps b/install-audioapps
--- a/install-audioapps
+++ b/install-audioapps
@@ -7,7 +7,7 @@
 # Author       : Copyright (C) 2019, Richard B. Romig, MosfaNet
 # Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
 # Created      : 01 Mar 2019
-# Updated      : 02 Feb 2026
+# Updated      : 19 May 2026
 # Comments     :
 # TODO (rick)  :
 # License      : GNU General Public License, version 2.0
@@ -24,22 +24,16 @@
 # GNU General Public License for more details.
 ###############################################################################
 
-## Shellcheck Directives ##
-# shellcheck source=/home/rick/bin/functionlib
-
 ## Load function library ##
-
-if [[ -x "$HOME/bin/functionlib" ]]; then
-  source "$HOME/bin/functionlib"
-else
-  printf "\e[91mERROR:\e[0m functionlib not found!" >&2
-  exit 81
-fi
+# shellcheck source=/home/rick/bin/functionlib
+source ~/bin/functionlib || { printf "\e[91mERROR:\e[0m Unable to source functionlib\n"; exit 1; }
 
 ## Functions ##
 
 install_audio_apps() {
   printf "\nInstalling audio applications and utilities from repositories.\n"
+  sudo_login 2
+  sudo apt-get update -qq
   sudo apt-get install -yy asunder audacity easytag lame mp3gain
 }
 
@@ -48,15 +42,13 @@ list_installed_apps() {
   apps=( asunder audacity easytag lame mp3gain )
   printf "Audio applications installed:\n"
   for app in "${apps[@]}"; do
-    exists "$app" && printf "\t%s\n" "${app^}"
+    installed "$app" && printf "\t%s\n" "${app^}"
   done
 }
 
 main() {
-  local script="${0##*/}"
-  local version="1.6.26033"
-  sudo_login 2
-  sudo apt-get update -qq
+  local -r script="${0##*/}"
+  local -r version="1.7.26139"
   printf "Installs audio applications on Debian/Ubuntu-based systems.\n"
   install_audio_apps
   list_installed_apps
