install-glow 0.4.8 - Replaced if-else for getopts with noOpt variable. Displays help and exits if no argument passed.

diff --git a/install-glow b/install-glow
--- a/install-glow
+++ b/install-glow
@@ -1,4 +1,4 @@
-#!/usr/bin/env bash
+#!/bin/bash
 ##########################################################################
 # Script Name  : install-glow
 # Description  : Installs, updates, and removes the Glow markdown reader.
@@ -27,8 +27,8 @@ fi
 ## Variables ##
 
 _script=$(basename "$0"); readonly _script
-readonly _version="0.4.7"
-readonly _updated="03 Feb 2023"
+readonly _version="0.4.8"
+readonly _updated="29 Mar 2023"
 readonly src_list="/etc/apt/sources.list.d/charm.list"
 readonly keyring_dir="/etc/apt/keyrings"
 
@@ -80,7 +80,7 @@ ${orange}OPTIONS:${normal}
   -r    Removes the glow markdown reader from the system.
   -s    Apply charm.list and gpg key
 END_HELP
-  printf "\U1F427 %s v%s (%s)\n" "$_script" "$_version" "$_updated"
+  printf "%s v%s (%s)\n" "$_script" "$_version" "$_updated"
   exit "$errcode"
 }
 
@@ -89,40 +89,38 @@ END_HELP
 check_dependencies
 printf "Installs or removes the Glow markdown reader.\n"
 
-if [[ "$#" -eq 0 ]]; then
-  echo "${lightred}ERROR:${normal} No argument passed." >&2
-  help 2
-else
-  optstr=":hirs"
-  while getopts "$optstr" opt
-  do
-    case "$opt" in
-      h )
-        help 0
-        ;;
-      i )
-        exists_glow && leave "Glow $(glow_ver) is already installed."
-        user_in_sudo
-        echo "${lightyellow}Installing Glow markdown reader...${normal}"
-        install_glow
-        ;;
-      r )
-        exists_glow || leave "Glow is not installed."
-        user_in_sudo
-        remove_glow
-        ;;
-      s )
-        exists_glow || leave "Glow is not installed."
-        user_in_sudo
-        src_gpg
-        echo "charm.list created, gpg key applied."
-        ;;
-      ? )
-        echo "${lightred}ERROR:${normal} Invalid option -${OPTARG}" >&2
-        help 2
-        ;;
-    esac
-  done
-fi
+noOpt=1
+optstr=":hirs"
+while getopts "$optstr" opt
+do
+  case "$opt" in
+    h )
+      help 0
+      ;;
+    i )
+      exists_glow && leave "Glow $(glow_ver) is already installed."
+      user_in_sudo
+      echo "${lightyellow}Installing Glow markdown reader...${normal}"
+      install_glow
+      ;;
+    r )
+      exists_glow || leave "Glow is not installed."
+      user_in_sudo
+      remove_glow
+      ;;
+    s )
+      exists_glow || leave "Glow is not installed."
+      user_in_sudo
+      src_gpg
+      echo "charm.list created, gpg key applied."
+      ;;
+    ? )
+      echo "${lightred}ERROR:${normal} Invalid option -${OPTARG}" >&2
+      help 2
+      ;;
+  esac
+	noOpt=0
+done
+if [ $noOpt = 1 ];then printf "%s No argument passed.\n" "$red_error" >&2;help 1;fi
 printf "%s v%s (%s)\n" "$_script" "$_version" "$_updated"
 exit
