install-keepassxc 0.3.2 - changed rederror to red_error, removed sleep after check_dependencies.

diff --git a/install-keepassxc b/install-keepassxc
--- a/install-keepassxc
+++ b/install-keepassxc
@@ -1,4 +1,4 @@
-#!/usr/bin/env bash
+#!/bin/bash
 ##########################################################################
 # Script Name  : install-keepassxc
 # Description  : Installs/removes KeePassXC from Flathub or distro repos
@@ -27,9 +27,8 @@ fi
 ## Variables ##
 
 _script=$(basename "$0"); readonly _script
-readonly _version="0.3.1"
-readonly _updated="04 Feb 2023"
-readonly rederror="${lightred}ERROR:${normal} "
+readonly _version="0.3.2"
+readonly _updated="12 Mar 2023"
 
 ## Functions ##
 
@@ -97,7 +96,7 @@ END_HELP
 echo "$_script v$_version ($_updated)"
 echo "Installs KeePassXC password manager"
 if [[ "$#" -eq 0 ]]; then
-  printf "%sNo argument passed." "$rederror" >&2
+  printf "%sNo argument passed." "$red_error" >&2
   help 1
 else
   optstr=":dfhmr"
@@ -128,7 +127,7 @@ else
         fi
         ;;
       ? )
-        printf "%sInvalid option -%s\n" "$rederror" "$OPTARG" >&2
+        printf "%sInvalid option -%s\n" "$red_error" "$OPTARG" >&2
         help 2
     esac
   done
