install-audacious 0.2.0 - Removed support for Ubuntu PPA. Converted to getopts.

diff --git a/install-audacious b/install-audacious
--- a/install-audacious
+++ b/install-audacious
@@ -1,13 +1,13 @@
 #!/usr/bin/env bash
 #############################################################################
 # Script Name  : install-audacious
-# Description  : Installs or removes Audacious audio player from PPA
+# Description  : Installs/Removes Audacious audio player
 # Dependencies : none
 # Arguments    : none
 # Author       : Copyright (C) 2020, Richard B. Romig, 23 Mar 2020
 # Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
-# Comments     :
-# TODO (Rick)  : PPA uninstall
+# Comments     : Does not support installation from Ubuntu PPAs.
+# TODO (Rick)  : 
 # License      : GNU General Public License, version 2.0
 #############################################################################
 
@@ -27,15 +27,27 @@ fi
 ## Variables ##
 
 _script=$(basename "$0"); readonly _script
-readonly _version="0.1.6"
-readonly _updated="04 Feb 2023"
+readonly _version="0.2.0"
+readonly _updated="30 Oct 2023"
 
 ## Functions ##
 
-install_audacious() {
-  exists audacious && leave "Audacious audio player is installed."
+help() {
+	errcode="${1:-2}"
+	cat << END_HELP
+${green}Usage:${normal} $_script [OPTION]
+${orange}OPTIONS:${normal}
+	-h	Display help
+	-i	Install Audacious audio player
+	-r	Remove Audacious audio player
+$_script $_version (Updated $_updated)	
+END_HELP
+  exit "$errcode"
+}
 
+install_audacious() {
   if in_repos audacious; then
+    user_in_sudo
     sudo apt update -qq
     sudo apt install audacious audacious-plugins -yy
     leave "Audacious audio player installed from distro repository."
@@ -45,31 +57,13 @@ install_audacious() {
 }
 
 remove_audacious() {
-  if exists audacious; then
-    echo "Removing Audacious audio player."
-    sudo apt remove --autoremove audacious audacious-plugins
-    leave "Audacious audio player removed."
-  else
-    leave "Audacious audio player is not installed."
-  fi
+  echo "Removing Audacious audio player."
+  user_in_sudo
+  sudo apt remove --autoremove audacious audacious-plugins
+  leave "Audacious audio player removed."
 }
 
 ## Execution ##
-
-clear
-echo "$_script v$_version ($_updated)"
-echo "Installs/removes the Audacious audio player."
-echo $'\n'$"Options:"
-PS3="Select an option: "
-options=( "Install Audacious" "Remove Audacious" "Quit")
-select opt in "${options[@]}"; do
-  case $REPLY in
-    1 ) user_in_sudo; install_audacious; break ;;
-    2 ) user_in_sudo; remove_audacious; break ;;
-    3 ) leave "No action taken. Exiting the script." ;;
-    * ) echo "${lightred}Invalid option.${normal} Please try again." >&2 ;;
-  esac
-done
 
 noOpt=1
 optstr=":hir"
@@ -79,9 +73,19 @@ while getopts "$optstr" opt; do
 			help 0
 		;;
     i )
+      exists audacious && leave "Audacious audio player is already installed."
+      install_audacious
     ;;
     r )
+      exists audacious || leave "Audacious audio player is not installed."
+      remove_audacious
     ;;
     ? )
+      printf "%s Invalid option -%s\n" "$red_error" "$OPTARG" >&2
+      help 2
   esac
+  noOpt=0
 done
+[[ "$noOpt" = 1 ]] && { printf "%s No argument passed.\n" "$red_error" >&2; help 1; }
+shift "$(( OPTIND - 1 ))"
+leave "$_script v$_version (Updated: $_updated)"
