install-virtmgr: chanaged indentation tabs from 2 to 4 tabs

diff --git a/install-virtmgr b/install-virtmgr
--- a/install-virtmgr
+++ b/install-virtmgr
@@ -7,8 +7,8 @@
 # Author       : Copyright (C) 2011, Richard B. Romig, MosfaNet
 # Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
 # Created      : 10 Feb 2021
-# Updated      : 13 Aug 2026
-# Version      : 4.0.26225
+# Updated      : 08 Sep 2026
+# Version      : 4.1.26251
 # Comments     : Based on Chris Titus video for installing virt-manager:
 #              : https://www.youtube.com/watch?v=ozYKkaVK0_A
 # TODO (Rick)  : Set up default image pool in home directory.
@@ -28,167 +28,166 @@
 source ~/bin/functionlib.bash || { printf "\e[91mERROR:\e[0m Unable to source functionlib.bash\n"; exit 1; }
 
 check_kernel() {
-  local kernel64
-  kernel64=$(uname -m)
-  printf "* Kernel is "
-  if [[ "$kernel64" == "x86_64" ]]; then
-	  printf "64-bit.\n"
-    return 0
-  else
-	  printf "not 64-bit.\n"
-	  return "$E_UNSUPPORTED"
-  fi
+	local kernel64
+	kernel64=$(uname -m); declare -r
+	printf "* Kernel is "
+	if [[ "$kernel64" == "x86_64" ]]; then
+		printf "64-bit.\n"
+		return 0
+	else
+		printf "not 64-bit.\n"
+		return "$E_UNSUPPORTED"
+	fi
 }
 
 check_processor() {
-  local proc64
-	proc64=$(grep -Ec ' lm ' /proc/cpuinfo)  # egrep -c ' lm ' /proc/cpuinfo
-  printf "* Processor is "
-  if [[ "$proc64" -gt 0 ]]; then
-	  printf "64-bit.\n"
-    return 0
-  else
-	  printf "not 64-bit.\n"
-	  return "$E_UNSUPPORTED"
-  fi
+	local proc64
+	proc64=$(grep -Ec ' lm ' /proc/cpuinfo); declare -r
+	printf "* Processor is "
+	if [[ "$proc64" -gt 0 ]]; then
+		printf "64-bit.\n"
+		return 0
+	else
+		printf "not 64-bit.\n"
+		return "$E_UNSUPPORTED"
+	fi
 }
 
 check_bios() {
-  local vcpu
-	vcpu=$(grep -Ec 'vmx|svm' /proc/cpuinfo)  # egrep -c '(vmx|svm)' /proc/cpuinfo
-  printf "* Virtualization is "
-  if [[ "$vcpu" -gt 0 ]]; then
-    printf "enabled in the BIOS.\n"
-    return 0
-  else
-    printf "not enabled in the BIOS.\n "
-	  return "$E_UNSUPPORTED"
-  fi
+	local vcpu
+	vcpu=$(grep -Ec 'vmx|svm' /proc/cpuinfo); declare -r
+	printf "* Virtualization is "
+	if [[ "$vcpu" -gt 0 ]]; then
+		printf "enabled in the BIOS.\n"
+		return 0
+	else
+		printf "not enabled in the BIOS.\n "
+		return "$E_UNSUPPORTED"
+	fi
 }
 
 check_requirements() {
-  local -i virt_flag=0
-  is_systemd || virt_flag="$E_UNSUPPORTED"
-  check_kernel || virt_flag="$E_UNSUPPORTED"
-  check_processor || virt_flag="$E_UNSUPPORTED"
-  check_bios || virt_flag="$E_UNSUPPORTED"
-  if [[ "$virt_flag" -ne 0 ]]; then
-    printf "\nSystem does not meet all requirements to install KVM/QEMU.\n" >&2
-	  printf "KVM/QEMU requires a 64-bit kernel, a 64-bit processor,\n" >&2
-	  printf "and virtualization to be enabled in the BIOS.\n" >&2
-    printf "Systemd is required to run background services.\n" >&2
-    return "$E_UNSUPPORTED"
-  fi
-  printf "\nSystem meets all requirements to install KVM/QEMU.\n"
-  return 0
+	local -i virt_flag=0
+	is_systemd || virt_flag="$E_UNSUPPORTED"
+	check_kernel || virt_flag="$E_UNSUPPORTED"
+	check_processor || virt_flag="$E_UNSUPPORTED"
+	check_bios || virt_flag="$E_UNSUPPORTED"
+	if [[ "$virt_flag" -ne 0 ]]; then
+		printf "\nSystem does not meet all requirements to install KVM/QEMU.\n" >&2
+		printf "KVM/QEMU requires a 64-bit kernel, a 64-bit processor,\n" >&2
+		printf "and virtualization to be enabled in the BIOS.\n" >&2
+		printf "Systemd is required to run background services.\n" >&2
+		return "$E_UNSUPPORTED"
+	fi
+	printf "\nSystem meets all requirements to install KVM/QEMU.\n"
+	return 0
 }
 
 enable_libvirtd() {
-  printf "Enabling and starting the libvirtd service...\n"
-  sudo systemctl enable libvirtd
-  sudo systemctl start libvirtd
-  # sudo systemctl restart libvirtd
-  sudo systemctl status libvirtd.service
-  return 0
+	printf "Enabling and starting the libvirtd service...\n"
+	sudo systemctl enable libvirtd
+	sudo systemctl start libvirtd
+	sudo systemctl status libvirtd.service
+	return 0
 }
 
 start_networking() {
-  printf "Starting default network for networking...\n"
-  sudo virsh net-start default
-  sudo virsh net-autostart default
-  sudo virsh net-list --all
-  return 0
+	printf "Starting default network for networking...\n"
+	sudo virsh net-start default
+	sudo virsh net-autostart default
+	sudo virsh net-list --all
+	return 0
 }
 
 add_to_libvirt() {
-  local in_libvirt_grp
-  # Add user to the libvirt group
-  getent group libvirt || sudo groupadd libvirt > /dev/null 2>&1
-  in_libvirt_grp=$(awk '/libvirt:/ && /'"$USER"'/' /etc/group)
-  printf "%s " "$USER"
-  if [[ "$in_libvirt_grp" ]]; then
-    printf "is already a member of "
-  else
-    sudo adduser "$USER" libvirt > /dev/null  # sudo usermod -aG libvirt "$USER"
-    printf "added to "
-  fi
-  printf "the libvirt group.\n"
-  return 0
+	local in_libvirt_grp
+	# Add user to the libvirt group
+	getent group libvirt || sudo groupadd libvirt > /dev/null 2>&1
+	in_libvirt_grp=$(awk '/libvirt:/ && /'"$USER"'/' /etc/group)
+	printf "%s " "$USER"
+	if [[ "$in_libvirt_grp" ]]; then
+		printf "is already a member of "
+	else
+		sudo adduser "$USER" libvirt > /dev/null  # sudo usermod -aG libvirt "$USER"
+		printf "added to "
+	fi
+	printf "the libvirt group.\n"
+	return 0
 }
 
 add_to_libvirtqemu() {
-  local in_libvirt_qemu_grp
-  # Add user to the libvirt-qemu group
-  getent group libvirt-qemu || sudo groupadd libvirt-qemu > /dev/null 2>&1
-  in_libvirt_qemu_grp=$(awk '/libvirt-qemu:/ && /'"$USER"'/' /etc/group)
-  printf "User %s " "$USER"
-  if [[ -n "$in_libvirt_qemu_grp" ]]; then
-    printf "is already a member of "
-  else
-    sudo adduser "$USER" libvirt-qemu > /dev/null   # sudo usermod -aG libvirt-qemu "$USER"
-    printf "added to "
-  fi
-  printf "the libvirt-qemu group.\n"
-  return 0
+	local in_libvirt_qemu_grp
+	# Add user to the libvirt-qemu group
+	getent group libvirt-qemu || sudo groupadd libvirt-qemu > /dev/null 2>&1
+	in_libvirt_qemu_grp=$(awk '/libvirt-qemu:/ && /'"$USER"'/' /etc/group)
+	printf "User %s " "$USER"
+	if [[ -n "$in_libvirt_qemu_grp" ]]; then
+		printf "is already a member of "
+	else
+		sudo adduser "$USER" libvirt-qemu > /dev/null   # sudo usermod -aG libvirt-qemu "$USER"
+		printf "added to "
+	fi
+	printf "the libvirt-qemu group.\n"
+	return 0
 }
 
 add_to_kvm() {
-  local in_kvm_grp
-  # Add user to the kvm group
-  getent group kvm || sudo groupadd kvm > /dev/null 2>&1
-  in_kvm_grp=$(awk '/kvm:/ && /'"$USER"'/' /etc/group)
-  printf "User %s " "$USER"
-  if [[ -n "$in_kvm_grp" ]]; then
-    printf "is already a member of "
-  else
-    sudo adduser "$USER" kvm > /dev/null  # sudo usermod -aG kvm "$USER"
-    printf "added to "
-  fi
-  printf "the kvm group.\n"
-  return 0
+	local in_kvm_grp
+	# Add user to the kvm group
+	getent group kvm || sudo groupadd kvm > /dev/null 2>&1
+	in_kvm_grp=$(awk '/kvm:/ && /'"$USER"'/' /etc/group)
+	printf "User %s " "$USER"
+	if [[ -n "$in_kvm_grp" ]]; then
+		printf "is already a member of "
+	else
+		sudo adduser "$USER" kvm > /dev/null  # sudo usermod -aG kvm "$USER"
+		printf "added to "
+	fi
+	printf "the kvm group.\n"
+	return 0
 }
 
 install_packages() {
-  printf "Installing virt-manager, KVM/QEMU, and assoiciated tools...\n"
-  # Absolutely required:
-  sudo apt-get install qemu-kvm libvirt-daemon-system bridge-utils virt-manager -yy
-  # Optional or installed as dependencies:
-  sudo apt-get install virtinst virt-viewer qemu-utils libvirt-daemon libguestfs-tools genisoimage libosinfo-bin libvirt-clients -yy
-  sudo apt-get install dnsmasq vde2 openbsd-netcat
-  sudo apt-get install spice-vdagent
-  sudo modprobe vhost_net
-  return "$?"
+	printf "Installing virt-manager, KVM/QEMU, and assoiciated tools...\n"
+	# Absolutely required:
+	sudo apt-get install qemu-kvm libvirt-daemon-system bridge-utils virt-manager -yy
+	# Optional or installed as dependencies:
+	sudo apt-get install virtinst virt-viewer qemu-utils libvirt-daemon libguestfs-tools genisoimage libosinfo-bin libvirt-clients -yy
+	sudo apt-get install dnsmasq vde2 openbsd-netcat
+	sudo apt-get install spice-vdagent
+	sudo modprobe vhost_net
+	return "$?"
 }
 
 install_and_setup() {
-  sudo_login 2
-  if ! install_packages; then
-    printf "%s Installation failed.\n" "$RED_ERROR" >&2
-    return "$E_INSTALLATION"
-  fi
-  start_networking
-  printf "Adding %s to libvirt, libvirt-qemu, and kvm groups...\n" "$USER"
-  add_to_libvirt
-  add_to_libvirtqemu
-  add_to_kvm
-  enable_libvirtd
-  printf "Virt-Manager installed. %s added to libvirt, libvirt-qemu, and kvm groups." "$USER"
+	sudo_login 2
+	if ! install_packages; then
+		printf "%s Installation failed.\n" "$RED_ERROR" >&2
+		return "$E_INSTALLATION"
+	fi
+	start_networking
+	printf "Adding %s to libvirt, libvirt-qemu, and kvm groups...\n" "$USER"
+	add_to_libvirt
+	add_to_libvirtqemu
+	add_to_kvm
+	enable_libvirtd
+	printf "Virt-Manager installed. %s added to libvirt, libvirt-qemu, and kvm groups." "$USER"
 }
 
 main() {
-  local -r script="${0##*/}"
-  local -r version="4.0.26225"
-  local -i exit_code=0
-  printf "Installs Virt-Manager and KVM/QEMU...\n\n"
-  if check_requirements; then
-    install_and_setup
-    exit_code="$?"
-  else
-    printf "KVM/QEMU cannot be installed.\n" >&2
-    exit_code="$E_INSTALLATION"
-  fi
-  over_line "$script $version"
-  exit "$exit_code"
+	local -r script="${0##*/}"
+	local -r version="4.1.26251"
+	local -i exit_code=0
+	printf "Installs Virt-Manager and KVM/QEMU...\n\n"
+	if check_requirements; then
+		install_and_setup
+		exit_code="$?"
+	else
+		printf "KVM/QEMU cannot be installed.\n" >&2
+		exit_code="$E_INSTALLATION"
+	fi
+	over_line "$script $version"
+	exit "$exit_code"
 }
 
 main "$@"
