install-cmatrix: updated error handling

diff --git a/install-cmatrix b/install-cmatrix
--- a/install-cmatrix
+++ b/install-cmatrix
@@ -7,7 +7,7 @@
 # Author       : Copyright (C) 2024, Richard B. Romig, Mosfanet
 # Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
 # Created      : 2024
-# Updated      : 15 Nov 2025
+# Updated      : 02 Feb 2026
 # Comment      :
 # TODO (rick)  :
 # License      : GNU General Public License, version 2.0
@@ -41,13 +41,13 @@ set -eu
 ## Global Variables ##
 
 readonly script="${0##*/}"
-readonly version="1.7.25319"
+readonly version="1.8.26033"
 
 ## Functions ##
 
 help() {
-  local errcode="${1:=-2}"
-  local updated="15 Nov 2025"
+  local errcode="${1:=-1}"
+  local updated="02 Feb 2026"
   cat << _HELP_
 ${orange}$script${normal} $version ($updated)
 Installs/Removes C-Matrix
@@ -66,7 +66,12 @@ install_cmatrix() {
   sudo apt-get update -qq
   sudo apt-get install cmatrix cmatrix-xfont -yy
   exists cmatrix || die "cmatrix installation failed." 1
-  printf "C-Matrix installed.\n"
+  if grep -q '^ii' <(dpkg -l cmatrix 2>/dev/null); then
+    printf "C-Matrix installed.\n"
+  else
+    printf "%s cmatrix installation failed.\n" "$RED_ERROR" >&2
+    EC="$E_INSTALLATION"
+  fi
 }
 
 remove_cmatrix() {
@@ -102,14 +107,14 @@ main() {
         ;;
       ? )
         printf "%s Invalid option -%s\n" "$RED_ERROR" "$OPTARG" >&2
-        help 2
+        help "$E_INVALID_ARG"
     esac
     noOpt=0
   done
-  [[   "$noOpt" == 1 ]] && { printf "%s No argument passed.\n" "$RED_ERROR" >&2; help 1; }
+  [[   "$noOpt" == 1 ]] && { printf "%s No argument passed.\n" "$RED_ERROR" >&2; help "$E_MISSING_ARG"; }
   shift "$(( OPTIND - 1 ))"
   over_line "$script $version"
-  exit
+  exit "$EC"
 }
 
 ## Execution ##
