install-flatpak: Refactored.

diff --git a/install-flatpak b/install-flatpak
--- a/install-flatpak
+++ b/install-flatpak
@@ -7,8 +7,8 @@
 # Author       : Copyright (C) 2020, Richard B. Romig, LudditeGeek@Mosfanet
 # Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
 # Created      : 01 Mar 2020
-# Updated      : 27 Jul 2026
-# Version      : 1.8.26208
+# Updated      : 07 Sep 2026
+# Version      : 2.0.26250
 # Comments     :
 # TODO (Rick)  :
 # License      : GNU General Public License, version 2
@@ -28,52 +28,49 @@
 source ~/bin/functionlib.bash || { printf "\e[91mERROR:\e[0m Unable to source functionlib.bash\n"; exit 1; }
 
 install_flatpak() {
-  echo "Installing Flatpak..."
-  sudo_login 2
-  sudo apt update -qq
-  sudo apt install -y flatpak
-  if ! installed flatpak; then
-    printf "%s Flatpak installation failed.\n" "$RED_ERROR" >&2
-    return "$E_INSTALLATION"
-  fi
-  printf "%s installed.\n" "$(flatpak --version)"
-  install_flathub
-  install_gnome_plugin
-  return 0
+	printf "Installing Flatpak...\n"
+	sudo_login 2
+	sudo apt update -qq
+	sudo apt install -y flatpak
+	if ! installed flatpak; then
+		printf "%s Flatpak installation failed.\n" "$RED_ERROR" >&2
+		return "$E_INSTALLATION"
+	fi
+	printf "%s installed.\n" "$(flatpak --version)"
+	return 0
 }
 
 install_flathub() {
-  printf "Installing the Flathub repository ...\n"
-  sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
-  printf "Flatbhub installed.\n"
-  return 0
+	printf "Installing the Flathub repository ...\n"
+	sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
+	printf "Flatbhub installed.\n"
+	return 0
 }
 
 install_gnome_plugin() {
-  # Install only if using Gnome Desktop Environment or Gnome Software Store is installed
-  exists gnome-software-plugin-flatpak && { printf "Gnome Plugin already installed.\n"; return 0; }
-  exists gnome-software || { printf "Gnome Software Store is not installed.\n"; return 0; }
-  printf "Installing the Gnome software plugin for Flatpak ...\n"
-  sudo apt install -y gnome-software-plugin-flatpak
-  printf "Gnome software plugin installed.\n"
-  return 0
+	# Install only if using Gnome Desktop Environment or Gnome Software Store is installed
+	if installed flatpak && installed gnome-software; then
+		exists gnome-software-plugin-flatpak || sudo apt-get install -y gnome-software-plugin-flatpak
+		printf "Gnome software plugin installed.\n"
+	fi
+	return 0
 }
 
 main() {
-  local -r script="${0##*/}"
-  local -r version="1.8.26208"
-  exit_code=0
-  printf "Installs Flatpak and Flathub repository.\n"
-  if exists flatpack; then
-    printf "%s is already installed.\n" "$(flatpak --version)"
-    install_flathub
-    install_gnome_plugin
-  else
-    install_flatpak
-  fi
-  exit_code="$?"
-  over_line "$script $version"
-  exit "$exit_code"
+	local -r script="${0##*/}"
+	local -r version="2.0.26250"
+	exit_code=0
+	printf "Installs Flatpak and Flathub repository.\n"
+	if installed flatpak; then
+		printf "%s is already installed.\n" "$(flatpak --version)"
+	else
+		install_flatpak
+		exit_code="$?"
+	fi
+	installed flatpak && install_flathub
+	install_gnome_plugin
+	over_line "$script $version"
+	exit "$exit_code"
 }
 
 main "$@"
