install-batcat: install_bat() - added check if installation successful

diff --git a/install-batcat b/install-batcat
--- a/install-batcat
+++ b/install-batcat
@@ -7,7 +7,7 @@
 # Author       : Copyright © 2024 Richard B. Romig, Mosfanet
 # Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
 # Created      : 03 Aug 2024
-# Last updated : 14 Oct 2025
+# Last updated : 22 Oct 2025
 # Comments     : executable and its manpage will be renamed from ‘bat’ to ‘batcat’
 #              : because of a file name clash with another Debian package.
 #              : Mint 22 installs version 0.24.0 with suffix.
@@ -42,13 +42,13 @@ fi
 ## Global Variables ##
 
 readonly script="${0##*/}"
-readonly version="2.6.25287"
+readonly version="2.7.25295"
 
 ## Functions ##
 
 help() {
 	local errcode="${1:-2}"
-	local updated="14 Oct 2025"
+	local updated="22 Oct 2025"
 	cat << _HELP_
 ${orange}$script${normal} $version, Updated: $updated
 Installs/removes/configures bat/batcat
@@ -65,12 +65,12 @@ _HELP_
 }
 
 bat_version() {
-	# bat --version | cut -d' ' -f2
   dpkg -l bat | awk '/ii/ {print $3}'
 }
 
 install_bat() {
 	sudo apt-get install -yy bat
+	exists batcat || die "Batcat failed to install." 1
 	bat_config
 	printf "bat (batcat) version %s installed.\n" "$(bat_version)"
 }
@@ -84,7 +84,7 @@ remove_batcat() {
 		find ~/.config -type d -name bat -exec rm -rf {} \;
 		printf "Bat configuration files removed.\n"
 	else
-		printf "Kept user configuration files.\n"
+		printf "User configuration files retained.\n"
 	fi
   printf "Batcat has been removed.\n"
 }
@@ -122,7 +122,6 @@ main() {
 				if exists bat || exists batcat; then
 					printf "Bat %s is already installed.\n" "$(bat_version)"
 				else
-					# grep -q '^13' /etc/debian_version || { printf "Install Bat with iru-bat.\n"; exit 1; }
 					sudo_login 2
 					install_bat
 				fi
