install-codium: error code variables & process substitution

diff --git a/install-codium b/install-codium
--- a/install-codium
+++ b/install-codium
@@ -7,7 +7,7 @@
 # Author       : Copyright © 2023 Richard B. Romig, Mosfanet
 # Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
 # Created      : 04 Aug 2023
-# Updated      : 20 Nov 2025
+# Updated      : 30 Jan 2026
 # Comments     : Alternative to downloading directly from GitHub repo.
 # TODO (Rick)  :
 # License      : GNU General Public License, version 2.0
@@ -33,13 +33,13 @@ if [[ -x "$HOME/bin/functionlib" ]]; then
   source "$HOME/bin/functionlib"
 else
   printf "\e[91mERROR:\e[0m functionlib not found!\n" >&2
-  exit 1
+  exit 81
 fi
 
 ## Global Variables ##
 
 readonly script="${0##*/}"
-readonly version="2.12.25324"
+readonly version="2.13.26030"
 readonly key_file="/usr/share/keyrings/vscodium-archive-keyring.asc"
 readonly src_list="/etc/apt/sources.list.d/vscodium.list"
 verbose_mode="$FALSE"
@@ -47,8 +47,8 @@ verbose_mode="$FALSE"
 ## Functions ##
 
 help() {
-	local errcode="${1:-2}"
-	local updated="20 Nov 2025"
+	local errcode="${1:-1}"
+	local updated="30 Jan 2026"
 	cat << _HELP_
 ${orange}$script${normal} $version, updated: ($updated)
 Install/Remove VSCodium and apply settings
@@ -67,8 +67,8 @@ _HELP_
 }
 
 codium_version() {
-	# codium --version | head -n 1
-	dpkg -l codium | awk '/ii/ {print $3}'
+	# head -n 1 <(codium --version)
+	awk '/^ii/ {print $3}' <(dpkg -l codium)
 }
 
 set_gpg_key() {
@@ -189,11 +189,11 @@ main() {
 				;;
 			? )
 				printf "%s Invalid option -%s\n" "$RED_ERROR" "$OPTARG" >&2
-				help 2
+				help "$E_INVALID_ARG"
 		esac
 		noOpt=0
 	done
-	[[ "$noOpt" = 1 ]] && { printf "%s No argument passed.\n" "$RED_ERROR" >&2; help 1; }
+	[[ "$noOpt" = 1 ]] && { printf "%s No argument passed.\n" "$RED_ERROR" >&2; help "$E_MISSING_ARG"; }
 	shift "$(( OPTIND - 1 ))"
   over_line "$script $version"
   exit
