install-batcat - corrected repo download path in assign_repo(); corrected copy path in bat_config().

diff --git a/install-batcat b/install-batcat
--- a/install-batcat
+++ b/install-batcat
@@ -7,7 +7,7 @@
 # Author       : Copyright © 2024 Richard B. Romig, Mosfanet
 # Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
 # Created      : 03 Aug 2024
-# Last updated : 25 Oct 2024
+# Last updated : 15 Nov 2024
 # Comments     : the executable and its manpage will be renamed from ‘bat’ to ‘batcat’
 #              : because of a file name clash with another Debian package.
 # TODO (Rick)  :
@@ -31,7 +31,7 @@ set -eu
 ## Global Variables ##
 
 script=$(basename "$0"); readonly script
-readonly version="1.5.24299"
+readonly version="1.6.24320"
 readonly cfg_d=$HOME"/.config/bat"
 
 ## Functions ##
@@ -39,7 +39,7 @@ readonly cfg_d=$HOME"/.config/bat"
 help() {
 	local errcode updated
 	errcode="${1:-2}"
-	updated="25 Oct 2024"
+	updated="15 Nov 2024"
 	cat << _HELP_
 ${orange}$script${normal} $version, Upated: $updated
 Installs/removes/configures bat/batcat
@@ -63,14 +63,14 @@ assign_repo() {
 			repo="$HOME/gitea/configs"
 		;;
 		* )
-			if [[ -d "$HOME/Download/configs" ]]; then
-				pushd "$HOME/Download/configs" || die "pushd failed"
+			if [[ -d "$HOME/Downloads/configs" ]]; then
+				pushd "$HOME/Downloads/configs" || die "pushd failed"
 				git pull --quiet origin main
 				popd || die "popd failed"
 			else
-				git clone --quiet "$GITEA_URL/configs.git" "$HOME/Download/configs"
+				git clone --quiet "$GITEA_URL/configs.git" "$HOME/Downloads/configs"
 			fi
-			repo="$HOME/Download/configs"
+			repo="$HOME/Downloads/configs"
 	esac
 	printf "%s" "$repo"
 }
@@ -99,7 +99,7 @@ bat_config() {
   cfg_file="config"
   [[ -d "$cfg_d" ]] || mkdir -p "$cfg_d"
   printf "Applying Bat configuration...\n"
-  cp -v "$repository/$cfg_file" "$cfg_d/"
+  cp -v "$repository/bat/$cfg_file" "$cfg_d/"
   printf "Bat configuration applied.\n"
 }
 
