install-geany: install_geany() - updated installation failure routine

diff --git a/install-geany b/install-geany
--- a/install-geany
+++ b/install-geany
@@ -7,7 +7,7 @@
 # Author       : Copyright (C) 2022, Richard B. Romig,Mosfanet
 # Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
 # Created      : 25 Dec 2022
-# Updated      : 31 Jan 2026
+# Updated      : 03 Feb 2026
 # Comments     :
 # TODO (Rick)  :
 # License      : GNU General Public License, version 2.0
@@ -39,7 +39,7 @@ fi
 ## Global Variables ##
 
 readonly script="${0##*/}"
-readonly version="3.2.26031"
+readonly version="3.3.26034"
 verbose_mode="$FALSE"
 EC=0
 
@@ -47,7 +47,7 @@ EC=0
 
 help() {
 	local errcode="${1:-1}"
-	local updated="31 Jan 2026"
+	local updated="03 Feb 2026"
   cat << _HELP_
 ${orange}$script${normal} $version ($updated)
 Installs/Removes Geany text editor and themes
@@ -82,7 +82,11 @@ clone_themes() {
 install_geany() {
   show_message "Installing Geany from repositories..."
   sudo apt-get install -y geany libvte9
-  exists geany || die "Geany installation failed." "$E_INSTALLATION"
+  if ! grep -q '^ii' <(dpkg -l geany 2>/dev/null); then
+    printf "%s Geany installation failed.\n" "$RED_ERROR" >&2
+    EC="$E_INSTALLATION"
+    return
+  fi
   printf "Geany %s installed.\n" "$(geany_version)"
   geany_config
 }
