install-nerdfonts: error code variables

diff --git a/install-nerdfonts b/install-nerdfonts
--- a/install-nerdfonts
+++ b/install-nerdfonts
@@ -7,7 +7,7 @@
 # Author       : Copyright © 2023 Richard B. Romig, Mosfanet
 # Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
 # Created      : 28 Sep 2023
-# Last updated : 30 Dec 2025
+# Last updated : 30 Jan 2026
 # Comments     : system install directory = /usr/local/share/fonts
 # TODO (Rick)  :
 # License      : GNU General Public License, version 2.0
@@ -33,7 +33,7 @@ if [[ -x "$HOME/bin/functionlib" ]]; then
   source "$HOME/bin/functionlib"
 else
   printf "\e[91mERROR:\e[0m functionlib not found!\n" >&2
-  exit 1
+  exit 81
 fi
 
 ## Functions ##
@@ -74,11 +74,11 @@ install_SymbolNerdFonts() {
 
 main() {
   local -r script="${0##*/}"
-  local -r version="1.11.25364"
+  local -r version="1.12.06030"
   local -r font_dir="$HOME/.local/share/fonts"
   sudo_login 2
   check_packages wget
-  tmp_dir=$(mktemp -d) || die "Failed to create temporary directory." 1
+  tmp_dir=$(mktemp -d) || die "Failed to create temporary directory." "$E_TEMP_DIR"
   trap cleanup EXIT
   install_NerdFonts "$font_dir"
   install_SymbolNerdFonts "$font_dir"
