install-glow: updated indentation

diff --git a/install-glow b/install-glow
--- a/install-glow
+++ b/install-glow
@@ -7,8 +7,8 @@
 # Author       : Copyright (C) 2022, Richard B. Romig, Mosfanet
 # Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
 # Created      : 10 Jan 2022
-# Updated      : 13 Aug 2026
-# Version      : 5.2.26225
+# Updated      : 07 Sep2026
+# Version      : 5.2.26250
 # Comments     :
 # TODO (Rick)  :
 # License      : GNU General Public License, version 2.0
@@ -28,48 +28,48 @@
 source functionlib.bash || { printf "\e[91mERROR:\e[0m Unable to source functionlib.bash\n"; exit 1; }
 
 help() {
-  local -r script="$1"
-  local -r version="$2"
+	local -r script="$1"
+	local -r version="$2"
 	local -ri errcode="${3:-1}"
-	local -r updated="13 Aug 2026"
-  cat << _HELP_
-${orange}$script${normal} $version ($updated)
-Installs/Removed Glow Markdown reader
+	local -r updated="07 Sep 2026"
+	cat <<- _HELP_
+	${orange}$script${normal} $version ($updated)
+	Installs/Removed Glow Markdown reader
 
-${green}Usage:${normal} $script [-hir]
-${orange}Available options:${normal}
-  -c  Apply Glow configuration.
-  -h  Show this help message and exit.
-  -i  Installs the glow markdown reader.
-  -r  Removes the glow markdown reader from the system.
+	${green}Usage:${normal} $script [-hir]
+	${orange}Available options:${normal}
+	-c	Apply Glow configuration.
+	-h	Show this help message and exit.
+	-i	Installs the glow markdown reader.
+	-r	Removes the glow markdown reader from the system.
 _HELP_
-  exit "$errcode"
+	exit "$errcode"
 }
 
 glow_version() {
-  cut -d' ' -f3 <(glow --version)
+	cut -d' ' -f3 <(glow --version)
 	return 0
 }
 
 set_gpg_key() {
-  local -r charm_url="$1"
-  local -r charm_key="$2"
-  printf "Adding the Charm GPG key...\n"
-  [[ -d /etc/apt/keyrings ]] || sudo mkdir -p /etc/apt/keyrings
-  check_package curl
-  # sudo doesn't affect redirects. [SC2024]
-  curl -fsSL "$charm_url/gpg.key" | sudo gpg --dearmor -o "$charm_key"
-  printf "Charm GPG key applied.\n"
+	local -r charm_url="$1"
+	local -r charm_key="$2"
+	printf "Adding the Charm GPG key...\n"
+	[[ -d /etc/apt/keyrings ]] || sudo mkdir -p /etc/apt/keyrings
+	check_package curl
+	# sudo doesn't affect redirects. [SC2024]
+	curl -fsSL "$charm_url/gpg.key" | sudo gpg --dearmor -o "$charm_key"
+	printf "Charm GPG key applied.\n"
 	return 0
 }
 
 set_sources() {
-  local -r sources_uri="$1"
-  local -r key_file="$2"
-  local -r sources_file=/etc/apt/sources.list.d/charm.sources
-  [[ -f /etc/apt/sources.list.d/charm.list ]] && sudo mv /etc/apt/sources.list.d/charm.list /etc/apt/sources.list.d/charm.list.bak
-  printf "Creating the the Charm apt source list...\n"
-  sudo tee "$sources_file" <<< \
+	local -r sources_uri="$1"
+	local -r key_file="$2"
+	local -r sources_file=/etc/apt/sources.list.d/charm.sources
+	[[ -f /etc/apt/sources.list.d/charm.list ]] && sudo mv /etc/apt/sources.list.d/charm.list /etc/apt/sources.list.d/charm.list.bak
+	printf "Creating the the Charm apt source list...\n"
+	sudo tee "$sources_file" <<< \
 "Types: deb
 URIs: $sources_uri
 Suites: *
@@ -79,90 +79,89 @@ Signed-By: $key_file"
 }
 
 install_glow() {
-  if installed glow; then
-    printf "Glow %s is alredy installed.\n" "$(glow_version)"
-    return 1
-  fi
-  local -r charm_url="https://repo.charm.sh/apt"
-  local -r charm_key=/etc/apt/keyrings/charm.gpg
-  printf "Installing the Glow markdown reader...\n"
-  sudo_login 2
-  set_gpg_key "$charm_url" "$charm_key"
-  set_sources "$charm_url" "$charm_key"
-  sudo apt update && sudo apt install -y glow
-  if ! grep -q '^ii' <(dpkg -l glow 2>/dev/null); then
-    printf "%s Glow installation failed.\n" "$RED_ERROR" >&2
-    return "$E_INSTALLATION"
-  fi
-  printf "Glow %s successfully installed.\n" "$(glow_version)"
-  glow_config
+	if installed glow; then
+		printf "Glow %s is alredy installed.\n" "$(glow_version)" >&2
+		return "$E_FILE_EXISTS"
+	fi
+	local -r charm_url="https://repo.charm.sh/apt"
+	local -r charm_key=/etc/apt/keyrings/charm.gpg
+	printf "Installing the Glow markdown reader...\n"
+	sudo_login 2
+	set_gpg_key "$charm_url" "$charm_key"
+	set_sources "$charm_url" "$charm_key"
+	sudo apt update && sudo apt install -y glow
+	if ! grep -q '^ii' <(dpkg -l glow 2>/dev/null); then
+		printf "%s Glow installation failed.\n" "$RED_ERROR" >&2
+		return "$E_INSTALLATION"
+	fi
+	printf "Glow %s successfully installed.\n" "$(glow_version)"
 	return 0
 }
 
 remove_glow() {
-  if ! installed glow; then
-    printf "Glow is not installed.\n"
-    return 1
-  fi
-  printf "Removing the Glow markdown reader...\n"
-  sudo_login 2
-  sudo apt-get -y purge glow
-  find /etc/apt -type f -name "charm*" -exec sudo rm -f {} \;
-  [[ -f /usr/share/man/man1/glow.1.gz ]] && sudo rm -f /usr/share/man/man1/glow.1.gz
-  find ~/ -maxdepth 3 -type d -path "$HOME/Downloads" -prune -o -path "$HOME/gitea" -prune -o -type d -name glow -exec rm -rf {} \;
-  printf "Glow markdown reader has been removed.\n"
+	if ! installed glow; then
+		printf "Glow is not installed.\n" >&2
+		return "$E_NOT_INSTALLED"
+	fi
+	printf "Removing the Glow markdown reader...\n"
+	sudo_login 2
+	sudo apt-get -y purge glow
+	find /etc/apt -type f -name "charm*" -exec sudo rm -f {} \;
+	[[ -f /usr/share/man/man1/glow.1.gz ]] && sudo rm -f /usr/share/man/man1/glow.1.gz
+	find ~/ -maxdepth 3 -type d -path "$HOME/Downloads" -prune -o -path "$HOME/gitea" -prune -o -type d -name glow -exec rm -rf {} \;
+	printf "Glow markdown reader has been removed.\n"
 	return 0
 }
 
 glow_config() {
-  if ! installed glow; then
-    printf "Glow is not installed.\n"
-    return 1
-  fi
-  if [[ ! -d ~/Downloads/configs && ! -d ~/gitea/configs ]]; then
+	if ! installed glow; then
+		printf "Glow is not installed.\n" >&2
+		return "$E_NOT_INSTALLED"
+	fi
+	if [[ ! -d ~/Downloads/configs && ! -d ~/gitea/configs ]]; then
 		printf "%s Cloned repository not found!\n" "$RED_WARNING" >&2
 		return "$E_FILENOTFOUND"
 	fi
-  printf "Installing glow.yml...\n"
-  [[ -d ~/.config/glow ]] || mkdir -p ~/.config/glow
-  [[ -f ~/.config/glow/glow.yml ]] && rm ~/.config/glow/glow.yml
-  [[ -d ~/gitea/configs ]] && ln -sv ~/gitea/configs/glow/glow.yml ~/.config/glow/glow.yml
-  [[ -d ~/Downloads/configs ]] && ln -sv ~/Downloads/configs/glow/glow.yml ~/Downloads/configs/glow/glow.yml
-  printf "Glow configuration applied.\n"
+	printf "Installing glow.yml...\n"
+	[[ -d ~/.config/glow ]] || mkdir -p ~/.config/glow
+	[[ -f ~/.config/glow/glow.yml ]] && rm ~/.config/glow/glow.yml
+	[[ -d ~/gitea/configs ]] && ln -sv ~/gitea/configs/glow/glow.yml ~/.config/glow/glow.yml
+	[[ -d ~/Downloads/configs ]] && ln -sv ~/Downloads/configs/glow/glow.yml ~/Downloads/configs/glow/glow.yml
+	printf "Glow configuration applied.\n"
 	return 0
 }
 
 main() {
 	local -r script="${0##*/}"
-	local -r version="5.2.26225"
+	local -r version="5.2.26250"
 	local -i exit_code=0
-  local opt OPTARG OPTIND
 	local -i noOpt=1
-  local -r optstr=":chir"
-  while getopts "$optstr" opt; do
-    case "$opt" in
-      c )
-        glow_config ;;
-      h )
-        help "$script" "$version" 0 ;;
-      i )
-        install_glow && glow_config ;;
-      r )
-        remove_glow ;;
-      ? )
-        printf "%s Invalid option -%s\n" "$RED_ERROR" "$OPTARG" >&2
-        help "$script" "$version" "$E_INVALID_ARG"
-    esac
+	local -r optstr=":chir"
+	local opt OPTARG OPTIND
+	while getopts "$optstr" opt; do
+		case "$opt" in
+			c )
+				glow_config ;;
+			h )
+				help "$script" "$version" 0 ;;
+			i )
+				install_glow && glow_config ;;
+			r )
+				remove_glow ;;
+			? )
+				printf "%s Invalid option -%s\n" "$RED_ERROR" "$OPTARG" >&2
+				help "$script" "$version" "$E_INVALID_ARG"
+		esac
 		exit_code="$?"
-	  noOpt=0
-  done
+		noOpt=0
+	done
 	if (( noOpt == 1 )); then
 		printf "%s No argument passed.\n" "$RED_ERROR" >&2
 		help "$script" "$version" "$E_MISSING_ARG"
 	fi
-  shift "$(( OPTIND - 1 ))"
-  over_line "$script $version"
-  exit "$exit_code"
+	shift "$(( OPTIND - 1 ))"
+	over_line "$script $version"
+	exit "$exit_code"
 }
 
 main "$@"
