install-cmatrix: install_cmatrix() - added check if installation successful

diff --git a/install-cmatrix b/install-cmatrix
--- a/install-cmatrix
+++ b/install-cmatrix
@@ -7,7 +7,7 @@
 # Author       : Copyright (C) 2024, Richard B. Romig, Mosfanet
 # Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
 # Created      : 2024
-# Updated      : 17 Jul 2025
+# Updated      : 22 Oct 2025
 # Comment      :
 # TODO (rick)  :
 # License      : GNU General Public License, version 2.0
@@ -41,34 +41,35 @@ set -eu
 ## Global Variables ##
 
 readonly script="${0##*/}"
-readonly version="1.6.25198"
+readonly version="1.7.25295"
 
 ## Functions ##
 
 help() {
   local errcode="${1:=-2}"
-  local updated="17 Jul 2025"
+  local updated="22 Oct 2025"
   cat << _HELP_
 ${orange}$script${normal} $version ($updated)
 Installs/Removes C-Matrix
 
 ${green}Usage:${normal} $script [-hir]
 ${orange}Available options:${normal}
-  -h  Show this help message and exit
-  -i  Install C-Matrix
-  -r  Remove C-Matrix
+  -h  Show this help message and exit.
+  -i  Install C-Matrix.
+  -r  Remove C-Matrix.
 _HELP_
   exit "$errcode"
 }
 
-install_matrix() {
+install_cmatrix() {
   printf "Installing C-Matrix...\n"
   sudo apt-get update -qq
   sudo apt-get install cmatrix cmatrix-xfont -yy
+  exists cmatrix || die "cmatrix installation failed." 1
   printf "C-Matrix installed.\n"
 }
 
-remove_matrix() {
+remove_cmatrix() {
   printf "Removing C-Matrix...\n"
   sudo apt-get remove cmatrix cmatrix-xfont -yy
   printf "C-Matrix removed.\n"
@@ -84,14 +85,20 @@ main() {
         help 0
         ;;
       i )
-        exists cmatrix && leave "C-Matrix already installed."
-        sudo_login 2
-        install_matrix
+        if exists cmatrix; then
+          printf "C-Matrix already installed.\n"
+        else
+          sudo_login 2
+          install_cmatrix
+        fi
         ;;
       r )
-        exists cmatrix || leave "C-Matrix is not installed."
-        sudo_login 2
-        remove_matrix
+        if exists cmatrix; then
+          sudo_login 2
+          remove_cmatrix
+        else
+          printf "C-Matrix is not installed.\n"
+        fi
         ;;
       ? )
         printf "%s Invalid option -%s\n" "$RED_ERROR" "$OPTARG" >&2
