install-geany 0.2.0 - added getops, help, removal, install themes.

diff --git a/install-geany b/install-geany
--- a/install-geany
+++ b/install-geany
@@ -1,7 +1,7 @@
 #!/usr/bin/env bash
 ##########################################################################
 # Script Name  : install-geany
-# Description  : Installs and configures the Geany editor/IDE.
+# Description  : Installs the Geany editor/IDE with themes.
 # Dependencies : git
 # Arguments    : none
 # Author       : Copyright (C) 2022 Richard B. Romig, created: 25 Dec 2022
@@ -27,14 +27,28 @@ fi
 ## Global Variables ##
 
 readonly _script=$(basename "$0")
-readonly _version="0.1.0"
+readonly _version="0.2.0"
 readonly _updated="25 Dec 2022"
-# readonly red_error="${lightred}ERROR:${normal}"
+readonly red_error="${lightred}ERROR:${normal}"
 
 ## Functions ##
 
 check_dependencies() {
   check_package git
+}
+
+help() {
+  errcode="${1:-2}"
+  cat << END_HELP
+Usage: $_script [OPTION]
+OPTIONS:
+  -h  Display help
+  -i  Install Geany
+  -r  Remove Geany
+  -t  Install themes
+END_HELP
+  printf "\U1F427 %s v%s (%s)\n" "$_script" "$_version" "$_updated"
+  exit "$errcode"
 }
 
 geany_version() {
@@ -44,10 +58,7 @@ geany_version() {
 clone_themes() {
   local theme_url="https://github.com/geany/geany-themes.git"
   local dl_dir="$HOME/Downloads/geany-themes"
-  if [[ -d "$dl_dir" ]]; then
-    printf "%s already exists.\n" "$dl_dir"
-    remove_dl_dir
-  fi
+  [[ -d "$dl_dir" ]] && remove_dl_dir
   printf "Downloading Geany themes..."
   git clone "$theme_url" "$dl_dir"
   install_themes
@@ -59,11 +70,12 @@ install_themes() {
   [[ -d "$cs_dir" ]] || mkdir -p "$cs_dir"
   printf "Copying Geany colorschemes into %s\n" "$cs_dir"
   cp "$dl_dir"/*.conf "$cs_dir/"
+  printf "Geany themes installed."
 }
 
 remove_dl_dir() {
   local dl_dir="$HOME/Downloads/geany-themes"
-  printf "Removing %s\n" "$dl_dir"
+  printf "Removing %s...\n" "$dl_dir"
   rm -rf "$dl_dir"
 }
 
@@ -78,7 +90,6 @@ install_cc_fonts() {
 }
 
 install_geany() {
-  exists geany && leave "Geany $(geany_version) is already installed."
   sudo apt-get install geany libvte9 -yy
   clone_themes
   install_cc_fonts
@@ -86,10 +97,46 @@ install_geany() {
   printf "Geany %s installed.\n" "$(geany_version)"
 }
 
+remove_geany() {
+  local cfg_dir="$HOME/.config/geany"
+  sudo apt remove geany -yy
+  [[ -d "$cfg_dir" ]] && rm -rf "$cfg_dir"
+  print "Geany and configuration files removed.\n"
+}
+
 ## Execution ##
 
-printf "\U1F427 %s v%s (%s)\n" "$_script" "$_version" "$_updated"
-user_in_sudo
 check_dependencies
-install_geany
+if [[ "$#" -eq 0 ]]; then
+  printf "%s No argument passed.\n" "$red_error" >&2
+  help 1
+else
+  optstr=":hirt"
+  while getopts "$optstr" opt; do
+    case "$opt" in
+      h )
+        printf "%s help:\n" "$_script"
+        help 0 ;;
+      i )
+        exists geany && leave "Geany $(geany_version) is already installed."
+        user_in_sudo
+        install_geany
+        break ;;
+      r )
+        exists geany || leave "Geany is not installed."
+        user_in_sudo
+        remove_geany
+        break ;;
+      t )
+        exists geany || leave "Geany is not installed."
+        clone_themes
+        remove_dl_dir
+        break ;;
+      ? )
+        printf "%s Invalid option -%s\n" "$red_error" "$OPTARG" >&2
+        help 2 ;;
+    esac
+  done
+fi
+printf "\U1F427 %s v%s (%s)\n" "$_script" "$_version" "$_updated"
 exit
