install-atom-deb v1.5.0 -  installs version 1.63.0. Uses getopts.

diff --git a/install-atom-deb b/install-atom-deb
--- a/install-atom-deb
+++ b/install-atom-deb
@@ -2,11 +2,12 @@
 ###############################################################################
 # Script Name  : install-atom-deb
 # Description  : Installs Atom Editor from deb package
-# Dependencies : wget, sshfs
+# Dependencies : gdebi, git, wget, sshfs
 # Arguments    : none
 # Author       : Richard B. Romig, 14 July 2019
 # Email        : rick.romig@gmail.com
 # Comments     : This method does not support automatic updates
+#              : Version 1.63.0 is the final version of Atom (Sundown 15 Dec 2022)
 # Ubuntu dependencies: git libasound2 libcurl4 libgbm1 libgcrypt20 libgtk-3-0
 # libnotify4 libnss3 libglib2.0-bin xdg-utils libx11-xcb1 libxcb-dri3-0 libxss1
 # libxtst6 libxkbfile1
@@ -30,8 +31,8 @@ fi
 ## Variables ##
 
 readonly _script=$(basename "$0")
-readonly _version="1.4.2"
-readonly _updated="22 Sep 2022"
+readonly _version="1.5.0"
+readonly _updated="18 Nov 2022"
 readonly atom_cfg_dir=$HOME"/.local/share/atom"
 readonly atom_dir=$HOME"/.atom/"
 readonly config_dir="$HOME/.config/Atom"
@@ -42,30 +43,72 @@ atom_ver() {
   atom --version | awk '/Atom/ {print $NF}'
 }
 
+server_mount() {
+    tmp_dir=$(mktemp -d) || die "Failed to create temporary directory."
+    mount_server
+    trap unmount_server EXIT
+}
+
+local_install() {
+  local pkg_dir="/data/installation/Packages"
+  local package="atom-amd64.deb"
+  sudo gdebi -n "$pkg_dir/$package"
+}
+
+server_install() {
+  local pkg_dir="/mnt/HP-6005/installs/Packages"
+  local package="atom-amd64.deb"
+  server_mount
+  cp "$pkg_dir/$package" "$tmp_dir/"
+  sudo gdebi -n "$tmp_dir/$package"
+
+}
 install_atom() {
-	cp "$pkg_src/atom-amd64.deb" "$tmp_dir/"
-  sudo gdebi -n "$tmp_dir/atom-amd64.deb"
+  ip_addr="$(local_ip)"
+  echo "Installing Atom Editor..."
+  case "$ip_addr" in
+    11 )
+      local_install ;;
+    * )
+      server_install ;;
+  esac
   # Install dependencies if they are missing
+  sudo apt upgrade -yyq
   sudo apt install libasound2 libcurl4 libgbm1 libgcrypt20 libgtk-3-0 libnotify4 libnss3 libglib2.0-bin xdg-utils libx11-xcb1 libxcb-dri3-0 libxss1 libxtst6 libxkbfile1
   sudo apt install -f
+  # Install fonts, configuration file, and styles file
   cascadia_code
   atom_config
 	atom_styles
-  leave "Atom Editor v$(atom_ver) installed from .deb package"
+  echo "Atom Editor v$(atom_ver) installed from .deb package"
+}
+
+update_atom() {
+  ip_addr="$(local_ip)"
+  echo "Updating from Atom $(atom_ver) ..."
+  case "$ip_addr" in
+    11 )
+      local_install ;;
+    * )
+      server_install ;;
+  esac
+  echo "Atom updated from version $(atom_ver)"
 }
 
 remove_atom() {
+  local atom_list="/etc/apt/sources.list.d/atom.list"
   sudo apt-get remove --purge atom -yy
+  [[ -f "$atom_list" ]] && rm "$atom_list"
 	[[ -d "$atom_cfg_dir" ]] && rm -rf "$atom_cfg_dir"
   [[ -d "$atom_dir" ]] && rm -rf "$atom_dir"
   [[ -d "$config_dir" ]] && rm -rf "$config_dir"
-  leave "Atom editor and configuration files removed."
+  echo "Atom editor and configuration files removed."
 }
 
 cascadia_code() {
-  if [[ ! -d "$/usr/share/fonts/truetype/cascadia-code" ]]; then
+  local font_dir="/usr/share/fonts/truetype/cascadia-code"
+  if [[ ! -d "$font_dir" ]]; then
     echo "Installing Cascadia-Code fonts."
-    sudo apt upgrade -yyq
     sudo apt-get install fonts-cascadia-code -yyq
     echo "Cascadia-Code fonts installed."
   fi
@@ -87,7 +130,7 @@ atom_config() {
 	editor:
 		fontFamily: " 'Cascadia Code', Menlo, Consolas, DejaVu Sans Mono, monospace"
 		fontSize: 17
-		scrollPastEnd: true
+		scrollPastEnd: pkg_dir="/data/installation/Packages"true
 		showIndentGuide: true
 		softTabs: true
 		softWrap: true
@@ -132,7 +175,7 @@ atom_styles() {
     // color: white;
     // background-color: hsl(180, 24%, 12%);
 
-    // Enaable Cascadia Code ligatures
+    // Enable Cascadia Code ligatures
     text-rendering: optimizeLegibility;
 
     &.editor .syntax--string.syntax--quoted,
@@ -163,42 +206,43 @@ check_dependencies() {
 
 check_dependencies
 
-# Check local IP address
-ip_addr="$(local_ip)"
-if [[ "$ip_addr" -eq "11" ]]; then
-  cfg_src="/data/installation/configs"
-	pkg_src="/data/installation/Packages"
-else
-  mount_server
-  cfg_src="/mnt/HP-6005/installs/configs"
-	pkg_src="/mnt/HP-6005/installs/Packages"
-fi
-
-tmp_dir=$(mktemp -d) || die "Failed to create temporary directory."
-tmp_file=$(mktemp) || die "Failed to create temporary file."
-trap unmount_server EXIT
-[[ -d "$atom_cfg_dir" ]] || mkdir -p "$atom_cfg_dir"
-
 clear
 printf "%s v%s (%s)\n" "$_script" "$_version" "$_updated"
 printf "Installs the Atom Editor from a .deb package.\n"
 
-if exists atom; then
-  printf "Atom Editor v%s is installed.\n" "$(atom_ver)"
+if [[ "$#" -eq 0 ]]; then
+  echo "${lightred}ERROR:${normal} No argument passed." >&2
+  help 1
 else
-  printf "Atom Editor is not installed.\n"
+  optstr=":h:i:r:s:u"
+  while getopts "$optstr" opt; do
+    case "$opt" in
+      h )
+        help 0
+        ;;
+      i )
+        exists atom && leave "Atom $(atom_ver) is already installed."
+        [[ -d "$atom_cfg_dir" ]] || mkdir -p "$atom_cfg_dir"
+        install_atom
+        ;;
+      r )
+        exists atom || leave "Atom is not installed."
+        remove_atom
+        ;;
+      s )
+        exists atom || leave "Atom is not installed."
+        [[ -d "$atom_cfg_dir" ]] || mkdir -p "$atom_cfg_dir"
+        atom_config
+        atom_styles
+        ;;
+      u )
+        exists atom || leave "Atom is not installed."
+        update_atom
+        ;;
+      ? )
+        echo "${lightred}ERROR:${normal} Invalid option -${OPTARG}" >&2
+        help 2
+        ;;
+    esac
+  done
 fi
-
-cur_rel="$(newest_version)"
-printf "The latest available version is %s\n\n" "$cur_rel"
-
-printf "Options:\n"
-PS3="Choice: "
-select opt in "Install Atom Editor" "Remove Atom Editor" "Exit"; do
-  case $REPLY in
-    1 ) user_in_sudo; install_atom; break ;;
-    2 ) user_in_sudo; remove_atom; break ;;
-    3 ) leave "Exiting the script. No action taken."; break ;;
-    * ) echo "${lightred}Invalid selection.${normal} Try again." ;;
-  esac
-done
