install-batcat: check if bat installed moved to install_bat(), remove_bat(), bat_configs()

diff --git a/install-batcat b/install-batcat
--- a/install-batcat
+++ b/install-batcat
@@ -7,8 +7,8 @@
 # Author       : Copyright © 2024 Richard B. Romig, Mosfanet
 # Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
 # Created      : 03 Aug 2024
-# Updated      : 27 Jul 2026
-# Version      : 1.7.26208
+# Updated      : 12 Aug 2026
+# Version      : 2.13.26224
 # Comments     : executable and its manpage will be renamed from ‘bat’ to ‘batcat’
 #              : because of a file name clash with another Debian package.
 #              : Mint 22 installs version 0.24.0 with suffix.
@@ -34,8 +34,8 @@ source ~/bin/functionlib.bash || { printf "\e[91mERROR:\e[0m Unable to source fu
 help() {
 	local -r script="$1"
 	local -r version="$2"
-	local -r errcode="${3:-1}"
-	local -r updated="27 Jul 2026"
+	local -ri errcode="${3:-1}"
+	local -r updated="12 Aug 2026"
 	cat << _HELP_
 ${orange}$script${normal} $version, Updated: $updated
 Installs/removes/configures bat/batcat
@@ -56,6 +56,10 @@ bat_version() {
 }
 
 install_batcat() {
+	if installed bat; then
+		printf "Bat (Batcat) %s is already installed.\n" "$(bat_version)"
+		return 0
+	fi
 	sudo_login 2
 	sudo apt-get install -yy bat
 	if ! exists batcat; then
@@ -67,6 +71,10 @@ install_batcat() {
 }
 
 remove_batcat() {
+	if ! installed bat; then
+		printf "Bat (Batcat) is not installed.\n"
+		return 0
+	fi
 	sudo_login 2
   printf "Removing Bat %s...\n" "$(bat_version)"
 	[[ -L ~/.local/bin/bat ]] && unlink ~/.local/bin/bat
@@ -74,6 +82,8 @@ remove_batcat() {
 	if default_no "Remove configuration files?"; then
 		[[ -L ~/.config/bat/config ]] && unlink ~/.config/bat/config
 		find ~/.config -type d -name bat -exec rm -rf {} \;
+		[[ -d /usr/share/doc/bat ]] && sudo rm -rf /usr/share/doc/bat
+		[[ -f /usr/share/man/man1/bat.1.gz ]] && sudo rm /usr/share/man/man1/bat.1.gz
 		printf "Bat configuration files removed.\n"
 	else
 		printf "User configuration files retained.\n"
@@ -83,6 +93,10 @@ remove_batcat() {
 }
 
 bat_config() {
+	if ! installed bat; then
+		printf "Bat (Batcat) is not installed.\n"
+		return 0
+	fi
 	[[ -d ~/.config/bat ]] || mkdir -p ~/.config/bat
 	if [[ ! -d ~/Downloads/configs && ! -d ~/gitea/configs ]]; then
 		printf "%s Cloned repository not found!\n" "$RED_WARNING" >&2
@@ -102,7 +116,7 @@ bat_config() {
 
 main() {
 	local -r script="${0##*/}"
-	local -r version="2.12.26208"
+	local -r version="2.13.26224"
 	local -i exit_code=0
 	local opt OPTARG OPTIND
 	local -i noOpt=1
@@ -110,29 +124,13 @@ main() {
 	while getopts "$optstr" opt; do
 		case "$opt" in
 			c )
-				if installed bat; then
-					bat_config
-				else
-					printf "Bat (Batcat) is not installed.\n"
-				fi
-				;;
+				bat_config ;;
 			h )
-				help "$script" "$version" 0
-				;;
+				help "$script" "$version" 0 ;;
 			i )
-				if installed bat; then
-					printf "Bat (Batcat) %s is already installed.\n" "$(bat_version)"
-				else
-					install_batcat && bat_config
-				fi
-				;;
+				install_batcat && bat_config ;;
 			r )
-				if installed bat; then
-					printf "Bat (Batcat) is not installed.\n"
-				else
-					remove_batcat
-				fi
-				;;
+				remove_batcat ;;
 			? )
 				printf "%s Invalid option -%s\n" "$RED_ERROR" "$OPTARG" >&2
 				help "$script" "$version" "$E_INVALID_ARG"
@@ -140,7 +138,10 @@ main() {
 		exit_code="$?"
 		noOpt=0
 	done
-	[[ "$noOpt" = 1 ]] && { printf "%s No argument passed.\n" "$RED_ERROR" >&2; help "$script" "$version" "$E_MISSING_ARG"; }
+	if (( noOpt == 1 )); then
+		printf "%s No argument passed.\n" "$RED_ERROR" >&2
+		help "$script" "$version" "$E_MISSING_ARG"
+	fi
 	shift "$(( OPTIND - 1 ))"
 	over_line "$script $version"
 	exit "$exit_code"
