install-ufw: chanaged indentation tabs from 2 to 4 tabs; add_default_rules() - included rules for VMs

diff --git a/install-ufw b/install-ufw
--- a/install-ufw
+++ b/install-ufw
@@ -7,8 +7,8 @@
 # Author       : Copyright (C) Richard B. Romig, LudditeGeek@Mosfanet
 # Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
 # Created      : 05 Oct 2022
-# Updated      : 13 Aug 2026
-# Version      : 2.4.26225
+# Updated      : 08 Sep 2026
+# Version      : 2.5.26251
 # Comments     : Install & remove for Debian-based systems (Debian, antiX, MX, BunsenLabs).
 #              : UFW should already be installed on Linux Mint & LMDE.
 # TODO (Rick)  :
@@ -30,189 +30,201 @@
 source ~/bin/functionlib.bash || { printf "\e[91mERROR:\e[0m Unable to source functionlib.bash\n"; exit 1; }
 
 help() {
-  local -r script="$1"
-  local -r version="$2"
+	local -r script="$1"
+	local -r version="$2"
 	local -i errcode="${3:-1}"
-	local -r updated="13 Aug 2026"
-	cat << _HELP_
-${orange}$script${normal} $version ($updated)
-Installs UFW on Debian, BunsenLabs, and MX Linux systems.
-UFW/GUFW is installed by default in Linux Mint, LMDE, and Ubuntu.
+	local -r updated="08 Sep 2026"
+	cat <<- _HELP_
+	${orange}$script${normal} $version ($updated)
+	Installs UFW on Debian, BunsenLabs, and MX Linux systems.
+	UFW/GUFW is installed by default in Linux Mint, LMDE, and Ubuntu.
 
-${green}Usage:${normal} $script [-adhinrst]
-${orange}Available options:${normal}
-  -a  Add default rules for CUPS and SSH (Gitea/XRDP if installed)
-  -d  Delete rules by rule number
-  -h  Show this help message and exit
-  -i  Install UFW on a Debian-based system
-  -n  Add New rules
-  -r  Remove UFW from a Debian-based system
-  -s  UFW Status
-  -t  Toggle Enable/Disable UFW
+	${green}Usage:${normal} $script [-adhinrst]
+	${orange}Available options:${normal}
+	-a	Add default rules for CUPS and SSH (Gitea/XRDP if installed)
+	-d	Delete rules by rule number
+	-h	Show this help message and exit
+	-i	Install UFW on a Debian-based system
+	-n	Add New rules
+	-r	Remove UFW from a Debian-based system
+	-s	UFW Status
+	-t	Toggle Enable/Disable UFW
 _HELP_
-  exit "$errcode"
+	exit "$errcode"
 }
 
 ufw_active() {
-  grep -qw active < <(sudo /usr/sbin/ufw status) && return "$TRUE" || return "$FALSE"
+	grep -qw active < <(sudo /usr/sbin/ufw status) && return "$TRUE" || return "$FALSE"
 }
 
 ufw_version() {
-  awk 'NR==1 {print $NF}' < <(/usr/sbin/ufw version)
-  return 0
+	awk 'NR==1 {print $NF}' < <(/usr/sbin/ufw version)
+	return 0
 }
 
 ufw_status() {
-  if ! installed ufw; then
-    printf "UFW is not installed.\n" >&2
-    return 1
-  fi
-  sudo_login 2
-  printf "UFW %s\n" "$(ufw_version)"
-  sudo ufw status verbose
-  return 0
+	if ! installed ufw; then
+		printf "UFW is not installed.\n" >&2
+		return "$E_NOT_INSTALLED"
+	fi
+	sudo_login 2
+	printf "UFW %s\n" "$(ufw_version)"
+	sudo ufw status verbose
+	return 0
 }
 
 install_ufw() {
-  if installed ufw; then
-    printf "UFW %s is already installed.\n" "$(ufw_version)" >&2
-    return 1
-  fi
-  sudo_login 2
-  printf "Installing UFW (Uncomplicated Firewall)...\n"
-  sudo apt-get install ufw -yy
-  if ! installed ufw; then
-    printf "%s UFW installation failed.\n" "$RED_ERROR" >&2
-    return "$E_INSTALLATION"
-  fi
-  add_default_rules
-  sudo ufw status verbose
-  printf "UFW %s installed and configured.\n" "$(ufw_version)"
-  return 0
+	if installed ufw; then
+		printf "UFW %s is already installed.\n" "$(ufw_version)" >&2
+		return "$E_FILE_EXISTS"
+	fi
+	sudo_login 2
+	printf "Installing UFW (Uncomplicated Firewall)...\n"
+	sudo apt-get install ufw -yy
+	if ! installed ufw; then
+		printf "%s UFW installation failed.\n" "$RED_ERROR" >&2
+		return "$E_INSTALLATION"
+	fi
+	add_default_rules
+	sudo ufw status verbose
+	printf "UFW %s installed and configured.\n" "$(ufw_version)"
+	return 0
 }
 
 remove_ufw() {
-  if ! installed ufw; then
-    printf "UFW is not installed.\n" >&2
-    return 1
-  fi
-  if ! is_debian; then
-    printf "Not a Debian system. UFW will not be removed.\n" >&2
-    return 1
-  fi
-  sudo_login 2
-  printf "Removing UFW (Uncomplicated Firewall) version %s...\n" "$(ufw_version)"
-  sudo ufw reset  # disable UFW and delete all active rules
-  sudo  apt-get purge ufw
-  return "$?"
+	if ! installed ufw; then
+		printf "UFW is not installed.\n" >&2
+		return "$E_NOT_INSTALLED"
+	fi
+	if ! is_debian; then
+		printf "Not a Debian system. UFW will not be removed.\n" >&2
+	return "$E_UNSUPPORTED"
+	fi
+	sudo_login 2
+	printf "Removing UFW (Uncomplicated Firewall) version %s...\n" "$(ufw_version)"
+	sudo ufw reset  # disable UFW and delete all active rules
+	sudo  apt-get purge ufw
+	return "$?"
 }
 
 add_default_rules() {
-  if ! installed ufw; then
-    printf "UFW is not installed.\n" >&2
-    return 1
-  fi
-  sudo_login 2
-  printf "Adding rules for CUPS, SSH, ...\n"
-  sudo sed -i '/IPV6=no/s/no/yes/' /etc/default/ufw
-  sudo ufw allow from 192.168.0.0/24 to any port 22 comment 'SSH' && printf "SSH (port 22) allowd on 192.168.0.0.\n"
-  sudo ufw allow from 192.168.0.0/24 to any port 631 comment 'CUPS' && printf "CUPS (port 631) allowed on 192.168.0.0.\n"
-  if exists gitea; then
-    sudo ufw allow 3000/tcp comment 'GITEA' && printf "GITEA (port 3000) allowed.\n"
-  fi
-  if installed xrdp; then
-    sudo ufw allow 3389/tcp comment 'XRDP' && printf "XRDP (port 3389) allowed.\n"
-  fi
-  ufw_active || sudo ufw enable
-  return 0
+	if ! installed ufw; then
+		printf "UFW is not installed.\n" >&2
+		return "$E_NOT_INSTALLED"
+	fi
+	sudo_login 2
+	printf "Adding rules for CUPS, SSH, ...\n"
+	sudo sed -i '/IPV6=no/s/no/yes/' /etc/default/ufw
+	if [[ "$LOCALNET" == "192.168.122" || "$LOCALNET" == "10.0.2" ]]; then
+		sudo ufw allow 22 comment 'SSH'
+		printf "SSH (port 22) allowed\n"
+	else
+		sudo ufw allow from "$LOCALNET"/24 to any port 22 comment 'SSH'
+		printf "SSH (port 22) allowed on %s\n" "$LOCALNET"
+		sudo ufw allow from "$LOCALNET"/24 to any port 631 comment 'CUPS'
+		printf "CUPS (port 631) allowed on %s\n" "$LOCALNET"
+		if exists gitea; then
+			sudo ufw allow 3000/tcp comment 'GITEA'
+			printf "GITEA (port 3000) allowed.\n"
+		fi
+		if installed xrdp; then
+			sudo ufw allow 3389/tcp comment 'XRDP'
+			printf "XRDP (port 3389) allowed.\n"
+		fi
+	fi
+	ufw_active || sudo ufw enable
+	return 0
 }
 
 add_new_rules() {
-  if ! installed ufw; then
-    printf "UFW is not installed.\n" >&2
-    return 1
-  fi
-  local rule="deny foo"
-  sudo_login 2
-  sudo ufw status
-  printf "Add new rules in the following format:\n"
-  printf "allow/deny <protocol> or allow/deny <port-number>\n"
-  while [[ "$rule" != "" ]]; do
-    read -rp "Rule to be added (done to exit): " rule
-    [[ "$rule" != "" ]] && sudo ufw delete "$rule"
-  done
-  ufw_active || sudo ufw enable
-  return 0
+	if ! installed ufw; then
+		printf "UFW is not installed.\n" >&2
+		return "$E_NOT_INSTALLED"
+	fi
+	local rule="deny foo"
+	sudo_login 2
+	sudo ufw status
+	printf "Add new rules in the following format:\n"
+	printf "allow/deny <protocol> or allow/deny <port-number>\n"
+	while [[ "$rule" != "" ]]; do
+		read -rp "Rule to be added (done to exit): " rule
+		[[ "$rule" != "" ]] && sudo ufw allow "$rule"
+	done
+	ufw_active || sudo ufw enable
+	return 0
 }
 
 delete_rules() {
-  if ! installed ufw; then
-    printf "UFW is not installed.\n" >&2
-    return 1
-  fi
-  local -i rule=0
-  sudo_login 2
-  while [[ "$rule" != "" ]]; do
-    sudo ufw status numbered
-    read -rp "Rule to be removed (by number): " rule
-    [[ "$rule" != "" ]] && sudo ufw delete "$rule"
-  done
-  ufw_active || sudo ufw enable
-  return 0
+	if ! installed ufw; then
+		printf "UFW is not installed.\n" >&2
+		return "$E_NOT_INSTALLED"
+	fi
+	local -i rule=0
+	sudo_login 2
+	while [[ "$rule" != "" ]]; do
+		sudo ufw status numbered
+		read -rp "Rule to be removed (by number): " rule
+		[[ "$rule" != "" ]] && sudo ufw delete "$rule"
+	done
+	ufw_active || sudo ufw enable
+	return 0
 }
 
 toggle_ufw() {
-  if ! installed ufw; then
-    printf "UFW is not installed.\n" >&2
-    return 1
-  fi
-  sudo_login 2
-  if ufw_active; then
-    sudo ufw disable
-    printf "UFW has been disabled.\n"
-  else
-    sudo ufw enable
-    printf "UFW is now enabled.\n"
-  fi
-  return 0
+	if ! installed ufw; then
+		printf "UFW is not installed.\n" >&2
+		return "$E_NOT_INSTALLED"
+	fi
+	sudo_login 2
+	if ufw_active; then
+		sudo ufw disable
+		printf "UFW has been disabled.\n"
+	else
+		sudo ufw enable
+		printf "UFW is now enabled.\n"
+	fi
+	return 0
 }
 
 main() {
-  local -r script="${0##*/}"
-  local -r version="2.4.26225"
-  local -i exit_code=0
-  local opt OPTARG OPTIND
-  local -i noOpt=1
-  local -r optstr=":adhinrst"
-  while getopts "$optstr" opt; do
-    case "$opt" in
-      a )
-        add_default_rules ;;
-      d )
-        delete_rules;;
-      h )
-        help "$script" "$version" 0 ;;
-      i )
-        install_ufw ;;
-      n )
-        add_new_rules ;;
-      r )
-        remove_ufw ;;
-      s )
-        ufw_status ;;
-      t )
-        toggle_ufw ;;
-      ? )
-        printf "%s Invalid option -%s\n" "$RED_ERROR" "$OPTARG" >&2
-        help "$script" "$version" "$E_INVALID_ARG"
-    esac
-    exit_code="$?"
-    noOpt=0
-  done
-  [[ "$noOpt" = 1 ]] && { printf "%s No argument passed.\n" "$RED_ERROR" >&2; help "$script" "$version" "$E_MISSING_ARG"; }
-  shift "$(( OPTIND - 1 ))"
-  over_line "$script $version"
-  exit "$exit_code"
+	local -r script="${0##*/}"
+	local -r version="2.5.26251"
+	local -i exit_code=0
+	local -i noOpt=1
+	local -r optstr=":adhinrst"
+	local opt OPTARG OPTIND
+	while getopts "$optstr" opt; do
+		case "$opt" in
+			a )
+				add_default_rules ;;
+			d )
+				delete_rules;;
+			h )
+				help "$script" "$version" 0 ;;
+			i )
+				install_ufw ;;
+			n )
+				add_new_rules ;;
+			r )
+				remove_ufw ;;
+			s )
+				ufw_status ;;
+			t )
+				toggle_ufw ;;
+			? )
+				printf "%s Invalid option -%s\n" "$RED_ERROR" "$OPTARG" >&2
+				help "$script" "$version" "$E_INVALID_ARG"
+		esac
+		exit_code="$?"
+		noOpt=0
+	done
+	if (( noOpt == 1 )); then
+		printf "%s No argument passed.\n" "$RED_ERROR" >&2
+		help "$script" "$version" "$E_MISSING_ARG"
+	fi
+	shift "$(( OPTIND - 1 ))"
+	over_line "$script $version"
+	exit "$exit_code"
 }
 
 main "$@"
