install-cmatrix - placed getopts in main()

diff --git a/install-cmatrix b/install-cmatrix
--- a/install-cmatrix
+++ b/install-cmatrix
@@ -4,8 +4,9 @@
 # Description  : installs cmatrix
 # Dependencies : none
 # Arguments    : none
-# Author       : Richard Romig
-# Email        : rick.romig@gmail.com
+# Author       : Copyright (C) 2024, Richard B. Romig, Mosfanet
+# Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
+# Updated      : 01 Oct 2024
 # Comment      :
 # TODO (rick)  :
 # License      : GNU General Public License, version 2.0
@@ -23,11 +24,10 @@ else
   exit 1
 fi
 
-## Variables ##
+## Global Variables ##
 
 _script=$(basename "$0"); readonly _script
-readonly _version="1.2.24168"
-readonly _updated="15 Jun 2024"
+readonly _version="1.3.24275"
 
 ## Functions ##
 
@@ -45,7 +45,9 @@ remove_matrix() {
 }
 
 help() {
+  local errcode _updated
   errcode="${1:=-2}"
+  _updated="04 Oct 2024"
   cat << END_HELP
 ${orange}$_script${normal} $_version ($_updated)
 Installs/Removes C-Matrix
@@ -60,32 +62,37 @@ END_HELP
   exit "$errcode"
 }
 
+main() {
+  local noOpt opt optstr
+  noOpt=1
+  optstr=":hir"
+  while getopts "$optstr" opt; do
+    case "$opt" in
+      h )
+        help 0
+      ;;
+      i )
+        exists cmatrix && leave "C-Matrix already installed."
+        sudo_login 2
+        install_matrix
+      ;;
+      r )
+        exists cmatrix || leave "C-Matrix is not installed."
+        sudo_login 2
+        remove_matrix
+      ;;
+      ? )
+        printf "%s Invalid option -%s\n" "$RED_ERROR" "$OPTARG" >&2
+        help 2
+    esac
+    noOpt=0
+  done
+  [[   "$noOpt" == 1 ]] && { printf "%s No argument passed.\n" "$RED_ERROR" >&2; help 1; }
+  shift "$(( OPTIND - 1 ))"
+  printf "%s v%s\n" "$_script" "$_version"
+  exit
+}
+
 ## Execution ##
 
-noOpt=1
-optstr=":hir"
-while getopts "$optstr" opt; do
-  case "$opt" in
-    h )
-      help 0
-    ;;
-    i )
-      exists cmatrix && leave "C-Matrix already installed."
-      sudo_login 2
-      install_matrix
-    ;;
-    r )
-      exists cmatrix || leave "C-Matrix is not installed."
-      sudo_login 2
-      remove_matrix
-    ;;
-    ? )
-      printf "%s Invalid option -%s\n" "$red_error" "$OPTARG" >&2
-      help 2
-  esac
-  noOpt=0
-done
-[[ "$noOpt" == 1 ]] && { printf "%s No argument passed.\n" "$red_error" >&2; help 1; }
-shift "$(( OPTIND - 1 ))"
-printf "%s v%s\n" "$_script" "$_version"
-exit
+main "$@"
