install-kitty: error code variables

diff --git a/install-kitty b/install-kitty
--- a/install-kitty
+++ b/install-kitty
@@ -7,7 +7,7 @@
 # Author       : Copyright (C) 2022, Richard B. Romig, LudditeGeek
 # Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
 # Created      : 26 Sep 2022
-# Updated      : 16 Nov 2025
+# Updated      : 01 Feb 2026
 # Comments     : Configures as login terminal for Debian-based distros.
 # TODO (Rick)  :
 # License      : GNU General Public License, version 2.0
@@ -33,19 +33,20 @@ if [[ -x "$HOME/bin/functionlib" ]]; then
   source "$HOME/bin/functionlib"
 else
   printf "\e[91mERROR:\e[0m functionlib not found!\n" >&2
-  exit 1
+  exit 81
 fi
 
 ## Global Variables ##
 
 readonly script="${0##*/}"
-readonly version="2.3.25320"
+readonly version="2.4.26032"
+EC=0
 
 ## Functions ##
 
 help() {
-	local errcode="${1:-2}"
-	local -r updated="16 Nov 2025"
+	local errcode="${1:-1}"
+	local -r updated="01 Feb 2026"
 	cat << _HELP_
 ${orange}$script${normal} $version ($updated)
 Installs/Removes/Configures Kitty terminal emulator
@@ -66,8 +67,13 @@ kitty_version() {
 install_kitty() {
   printf "Installing the kitty terminal emulator.\n"
   sudo apt-get install -y kitty imagemagick
-  exists kitty || die "Kitty installation failed." 1
+  if grep -q '^ii' <(dpkg -l kitty); then
+    printf "%s Kitty installation failed.\n" "$RED_ERROR"
+    EC="$E_INSTALLATION"
+    return
+  fi
   printf "Kitty %s installed.\n" "$(kitty_version)"
+  kitty_config
 }
 
 remove_kitty() {
@@ -82,8 +88,9 @@ remove_kitty() {
 kitty_config() {
   local repository=~/Downloads/configs/kitty
   [[ -d ~/gitea/configs/geany ]] && repository=~/gitea/configs/kitty
-  if ! [[ -d "$repository" ]]; then
+  if [[ ! -d "$repository" ]]; then
     printf "%s Configs repository not found!\n" "$RED_WARNING" >&2
+    EC="$E_FILENOTFOUND"
     return
   fi
   [[ -d ~/.config/kitty ]] || mkdir -p ~/.config/kitty
@@ -109,7 +116,6 @@ main() {
         else
           sudo_login 2
           install_kitty
-          kitty_config
         fi
         ;;
       r )
@@ -122,14 +128,14 @@ main() {
         ;;
       ? )
         printf "%s Invalid option -%s\n" "$RED_ERROR" "$OPTARG" >&2
-        help 2
+        help "$E_INVALID_ARG"
     esac
 	  noOpt=0
   done
-  [[ "$noOpt" = 1 ]] && { printf "%s No argument passed.\n" "$RED_ERROR" >&2; help 1; }
+  [[ "$noOpt" = 1 ]] && { printf "%s No argument passed.\n" "$RED_ERROR" >&2; help "$E_MISSING_ARG"; }
   shift "$(( OPTIND - 1 ))"
   over_line "$script $version"
-  exit
+  exit "$EC"
 }
 
 ## Execution ##
