install-cmatrix: moved existence checks to install and remove functions

diff --git a/install-cmatrix b/install-cmatrix
--- a/install-cmatrix
+++ b/install-cmatrix
@@ -7,8 +7,8 @@
 # Author       : Copyright (C) 2024, Richard B. Romig, Mosfanet
 # Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
 # Created      : 2024
-# Updated      : 27 Jul 2026
-# Version      : 1.11.26208
+# Updated      : 12 Aug 2026
+# Version      : 1.12.26224
 # Comment      :
 # TODO (rick)  :
 # License      : GNU General Public License, version 2.0
@@ -31,7 +31,7 @@ help() {
   local -r script="$1"
   local -r version="$2"
   local -ri errcode="${3:=-1}"
-  local -r updated="27 Jul 2026"
+  local -r updated="12 Aug 2026"
   cat << _HELP_
 ${orange}$script${normal} $version ($updated)
 Installs/Removes C-Matrix
@@ -46,8 +46,12 @@ _HELP_
 }
 
 install_cmatrix() {
-  printf "Installing C-Matrix...\n"
+  if installed cmatrix; then
+    printf "C-Matrix already installed.\n"
+    return 0
+  fi
   sudo_login 2
+  printf "Installing C-Matrix...\n"
   sudo apt-get update -qq
   sudo apt-get install cmatrix cmatrix-xfont -yy
   if ! installed cmatrix; then
@@ -59,6 +63,10 @@ install_cmatrix() {
 }
 
 remove_cmatrix() {
+  if ! installed cmatrix; then
+    printf "C-Matrix is not installed.\n"
+    return 0
+  fi
   printf "Removing C-Matrix...\n"
   sudo_login 2
   sudo apt-get remove cmatrix cmatrix-xfont -yy
@@ -68,7 +76,7 @@ remove_cmatrix() {
 
 main() {
   local -r script="${0##*/}"
-  local -r version="1.11.26208"
+  local -r version="1.12.26224"
 	local -i exit_code=0
   local opt OPTARG OPTIND
   local -i noOpt=1
@@ -76,22 +84,11 @@ main() {
   while getopts "$optstr" opt; do
     case "$opt" in
       h )
-        help "$script" "$version" 0
-        ;;
+        help "$script" "$version" 0 ;;
       i )
-        if installed cmatrix; then
-          printf "C-Matrix already installed.\n"
-        else
-          install_cmatrix
-        fi
-        ;;
+        install_cmatrix ;;
       r )
-        if installed cmatrix; then
-          remove_cmatrix
-        else
-          printf "C-Matrix is not installed.\n"
-        fi
-        ;;
+        remove_cmatrix ;;
       ? )
         printf "%s Invalid option -%s\n" "$RED_ERROR" "$OPTARG" >&2
         help "$script" "$version" "$E_INVALID_ARG"
@@ -99,7 +96,10 @@ main() {
     exit_code="$?"
     noOpt=0
   done
-  [[   "$noOpt" == 1 ]] && { printf "%s No argument passed.\n" "$RED_ERROR" >&2; help "$script" "$version" "$E_MISSING_ARG"; }
+	if (( noOpt == 1 )); then
+		printf "%s No argument passed.\n" "$RED_ERROR" >&2
+		help "$script" "$version" "$E_MISSING_ARG"
+	fi
   shift "$(( OPTIND - 1 ))"
   over_line "$script $version"
   exit "$exit_code"
