install-batcat: bat_version() - changed from awk to cut to extract version number

diff --git a/install-batcat b/install-batcat
--- a/install-batcat
+++ b/install-batcat
@@ -1,5 +1,5 @@
 #!/usr/bin/env bash
-##########################################################################
+###############################################################################
 # Script Name  : install-batcat
 # Description  : install/remove/configure bat/batcat (repo version)
 # Dependencies : git
@@ -7,41 +7,40 @@
 # Author       : Copyright © 2024 Richard B. Romig, Mosfanet
 # Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
 # Created      : 03 Aug 2024
-# Last updated : 09 Jul 2026
+# Updated      : 27 Jul 2026
+# Version      : 1.7.26208
 # Comments     : executable and its manpage will be renamed from ‘bat’ to ‘batcat’
 #              : because of a file name clash with another Debian package.
 #              : Mint 22 installs version 0.24.0 with suffix.
-#              : Debian 13 & LMDE 7 installs version 0.25.0 or 0.22.1 (LMDE 7) with suffix.
+#              : Debian 13 installs version 0.25.0  with suffix.
+#              : LMDE 7 installs version 0.22.1 with suffix.
 # TODO (Rick)  :
 # License      : GNU General Public License, version 2.0
 # License URL  : https://github.com/RickRomig/scripts/blob/main/LICENSE
-##########################################################################
-# This program is free software; you can redistribute it and/or modify
-# it under the terms of the GNU General Public License as published by
-# the Free Software Foundation; either version 2 of the License, or
-# (at your option) any later version.
+###############################################################################
+# This program is free software; you can redistribute it and/or modify it under
+# the terms of the GNU General Public License as published by the Free Software
+# Foundation; either version 2 of the License, or (at your option) any later
+# version.
 #
-# This program is distributed in the hope that it will be useful,
-# but WITHOUT ANY WARRANTY; without even the implied warranty of
-# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
-# GNU General Public License for more details.
-##########################################################################
+# This program is distributed in the hope that it will be useful, but WITHOUT
+# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
+# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
+###############################################################################
 
-## Source function library ##
-# shellcheck source=/home/rick/bin/functionlib
-source ~/bin/functionlib || { printf "\e[91mERROR:\e[0m Unable to source functionlib\n"; exit 1; }
+# shellcheck source=/home/rick/bin/functionlib.bash
+source ~/bin/functionlib.bash || { printf "\e[91mERROR:\e[0m Unable to source functionlib.bash\n"; exit 1; }
 
 help() {
 	local -r script="$1"
 	local -r version="$2"
 	local -r errcode="${3:-1}"
-	local -r updated="09 Jul 2026"
+	local -r updated="27 Jul 2026"
 	cat << _HELP_
 ${orange}$script${normal} $version, Updated: $updated
 Installs/removes/configures bat/batcat
 
 ${green}Usage:${normal} $script [-chir]
-
 ${orange}Available options:${normal}
   -c	Install bat configuration file.
   -h	Show this help message and exit.
@@ -52,7 +51,7 @@ _HELP_
 }
 
 bat_version() {
-  awk '/^ii/ {print $3}' < <(dpkg -l bat)
+	cut -d' ' -f2 < <(bat --version)
 	return 0
 }
 
@@ -64,7 +63,6 @@ install_batcat() {
 		return "$E_INSTALLATION"
 	fi
 	printf "Bat (Batcat) version %s installed.\n" "$(bat_version)"
-	bat_config
 	return 0
 }
 
@@ -104,7 +102,7 @@ bat_config() {
 
 main() {
 	local -r script="${0##*/}"
-	local -r version="2.14.26190"
+	local -r version="2.12.26208"
 	local -i exit_code=0
 	local opt OPTARG OPTIND
 	local -i noOpt=1
@@ -125,7 +123,7 @@ main() {
 				if installed bat; then
 					printf "Bat (Batcat) %s is already installed.\n" "$(bat_version)"
 				else
-					install_batcat
+					install_batcat && bat_config
 				fi
 				;;
 			r )
