install-kitty: functions return exit codes to main() or calling functions and assigned to local exit_code variable; script & versions passed to help()

diff --git a/install-kitty b/install-kitty
--- a/install-kitty
+++ b/install-kitty
@@ -1,5 +1,5 @@
 #!/usr/bin/env bash
-##########################################################################
+###############################################################################
 # Script Name  : install-kitty
 # Description  : Installs kitty terminal emulator with basic configuration.
 # Dependencies : git
@@ -7,12 +7,12 @@
 # Author       : Copyright (C) 2022, Richard B. Romig, LudditeGeek
 # Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
 # Created      : 26 Sep 2022
-# Updated      : 26 May 2026
+# Updated      : 30 Jun 2026
 # Comments     : Configures as login terminal for Debian-based distros.
 # TODO (Rick)  :
 # License      : GNU General Public License, version 2.0
 # License URL  : https://github.com/RickRomig/scripts/blob/main/LICENSE
-##########################################################################
+###############################################################################
 # This program is free software; you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
 # the Free Software Foundation; either version 2 of the License, or
@@ -22,31 +22,19 @@
 # but WITHOUT ANY WARRANTY; without even the implied warranty of
 # MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 # GNU General Public License for more details.
-##########################################################################
-
-## Shellcheck Directives ##
-# shellcheck source=/home/rick/bin/functionlib
+###############################################################################
 
 ## Source function library ##
-
-if [[ -x "$HOME/bin/functionlib" ]]; then
-  source "$HOME/bin/functionlib"
-else
-  printf "\e[91mERROR:\e[0m functionlib not found!\n" >&2
-  exit 81
-fi
-
-## Global Variables ##
-
-readonly script="${0##*/}"
-readonly version="2.6.21462"
-EC=0
+# shellcheck source=/home/rick/bin/functionlib
+source functionlib || { printf "\e[91mERROR:\e[0m Unable to source functionlib\n"; exit 1; }
 
 ## Functions ##
 
 help() {
-	local errcode="${1:-1}"
-	local -r updated="26 May 2026"
+  local -r script="$1"
+  local -r version="$2"
+	local errcode="${3:-1}"
+	local -r updated="30 Jun 2026"
 	cat << _HELP_
 ${orange}$script${normal} $version ($updated)
 Installs/Removes/Configures Kitty terminal emulator
@@ -62,6 +50,7 @@ _HELP_
 
 kitty_version() {
   cut -d' ' -f2 < <(kitty --version)
+  return 0
 }
 
 install_kitty() {
@@ -69,11 +58,11 @@ install_kitty() {
   sudo apt-get install -y kitty imagemagick
   if ! installed kitty; then
     printf "%s Kitty installation failed.\n" "$RED_ERROR"
-    EC="$E_INSTALLATION"
-    return
+    return "$E_INSTALLATION"
   fi
   printf "Kitty %s installed.\n" "$(kitty_version)"
   kitty_config
+  return "$?"
 }
 
 remove_kitty() {
@@ -83,6 +72,7 @@ remove_kitty() {
   [[ -L ~/.config/kitty/bindings.list ]] && unlink ~/.config/kitty/bindings.list
   find ~/ -maxdepth 3 -type d -path ~/Downloads -prune -o -path ~/gitea -prune -o -type d -name "kitty*" -exec rm -rf {} \;
   printf "The Kitty terminal emulator and configuration files have been removed.\n"
+  return 0
 }
 
 kitty_config() {
@@ -90,25 +80,28 @@ kitty_config() {
   [[ -d ~/gitea/configs/geany ]] && repository=~/gitea/configs/kitty
   if [[ ! -d "$repository" ]]; then
     printf "%s Configs repository not found!\n" "$RED_WARNING" >&2
-    EC="$E_FILENOTFOUND"
-    return
+    return "$E_FILENOTFOUND"
   fi
   [[ -d ~/.config/kitty ]] || mkdir -p ~/.config/kitty
   printf "Applying configuration files ...\n"
   cp -v "$repository"/kitty.conf "$repository"/bindings.list ~/.config/kitty/
   [[ "$DESKTOP_SESSION" != "i3" ]] && sed -i.bak '/hide_window_decorations/s/yes/no/' ~/.config/kitty/kitty.conf
   printf "kitty configuration files applied.\n"
+  return 0
 }
 
 main() {
   check_package git
   local noOpt opt optstr OPTARG OPTIND
+  local -r script="${0##*/}"
+  local -r version="2.7.26181"
+  local exit_code=0
   noOpt=1
   optstr=":hir"
   while getopts "$optstr" opt; do
     case "$opt" in
       h )
-        help 0
+        help "$script" "$version" 0
         ;;
       i )
         if installed kitty; then
@@ -116,26 +109,28 @@ main() {
         else
           sudo_login 2
           install_kitty
+          exit_code="$?"
         fi
         ;;
       r )
         if installed kitty; then
           sudo_login 2
           remove_kitty
+          exit_code="$?"
         else
           printf "Kitty is not installed.\n"
         fi
         ;;
       ? )
         printf "%s Invalid option -%s\n" "$RED_ERROR" "$OPTARG" >&2
-        help "$E_INVALID_ARG"
+        help "$script" "$version" "$E_INVALID_ARG"
     esac
 	  noOpt=0
   done
-  [[ "$noOpt" = 1 ]] && { printf "%s No argument passed.\n" "$RED_ERROR" >&2; help "$E_MISSING_ARG"; }
+  [[ "$noOpt" = 1 ]] && { printf "%s No argument passed.\n" "$RED_ERROR" >&2; help "$script" "$version" "$E_MISSING_ARG"; }
   shift "$(( OPTIND - 1 ))"
   over_line "$script $version"
-  exit "$EC"
+  exit "$exit_code"
 }
 
 ## Execution ##
