install-timeshift - move installation commands to install_timeshift(); added checks for required files; added check if already installed.

diff --git a/install-timeshift b/install-timeshift
--- a/install-timeshift
+++ b/install-timeshift
@@ -2,7 +2,7 @@
 ###############################################################################
 # Script Name  : install-timeshift
 # Description  : installs and configures timeshift
-# Dependencies : none
+# Dependencies : ~/bin/files/timeshift.sed
 # Arguments    : none
 # Author       : Copyright © 2024, Richard B. Romig, Mosfanet
 # Email        : rick.romig@gmail.com | rick.romig@mymetronet.com
@@ -25,9 +25,11 @@ else
   exit 1
 fi
 
+set -eu
+
 ## Global variables ##
 _script=$(basename "$0"); readonly _script
-readonly _version="1.2.24225"
+readonly _version="2.0.24225"
 
 ## Functions ##
 
@@ -37,18 +39,30 @@ configure_timeshift() {
   ts_json="timeshift.json"
   sed_dir="$HOME/bin/files"
   sed_file="timeshift.sed"
-  [[ -f "$ts_dir/$ts_json" ]] || sudo cp -v "$ts_dir/default.json" "$ts_dir/$ts_json"
-  sudo sed -i -f "$sed_dir/$sed_file" "$ts_dir/$ts_json"
-  sudo sed -i 's/^"\//    "\//;s/^"/  "/' "$ts_dir/$ts_json"
+  if [[ ! -f "$sed_dir/$sed_file" ]]; then
+    echo "Configuring Timeshift..."
+    sudo cp -v "$ts_dir/default.json" "$ts_dir/$ts_json"
+    sudo sed -i -f "$sed_dir/$sed_file" "$ts_dir/$ts_json"
+    sudo sed -i 's/^"\//    "\//;s/^"/  "/' "$ts_dir/$ts_json"
+  else
+    echo "The $sed_file configuration script was not found. Configure using the GUI application."
+  fi
+}
+
+install_timeshift() {
+  echo "Installing Timeshift..."
+  sudo_login 2
+  sudo apt-get -y timeshift
+  configure_timeshift
+  echo "$(timeshift --version) installed and configured."
 }
 
 ## Execution ##
 
-sudo_login 2
-box "$_script v$_version"
-echo "Installing Timeshift..."
-sudo apt-get -y timeshift
-echo "Configuring Timeshift..."
-configure_timeshift
-echo "$(timeshift --version) installed and configured."
-exit
+in_repo timeshift || leave "Timeshift is not availabe in $(get_distribution) repositories."
+if exists timeeshift; then
+  echo "Timeshift is already installed."
+else
+  install_timeshift
+fi
+leave "$_script v$_version"
