install-google-chrome: moved existence checks to install and remove functions; updated variables

diff --git a/install-google-chrome b/install-google-chrome
--- a/install-google-chrome
+++ b/install-google-chrome
@@ -7,8 +7,9 @@
 # Author       : Copyright (C) 2019 Richard B. Romig, Mosfanet
 # Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
 # Created      : 18 Jul 2019
-# Updated      : 19 Jul 2026
-# Comments     : Google Chrome updates through apt from the sources file
+# Updated      : 12 Aug 2026
+# Version      : 6.1.26224
+# Comments     :
 # TODO (rick)  :
 # License      : GNU General Public License, version 2.0
 # License URL  : https://github.com/RickRomig/scripts/blob/main/LICENSE
@@ -23,15 +24,14 @@
 # FOR A PARTICULAR PURPOSE. See the# GNU General Public License for more details.
 ###############################################################################
 
-## Source function library ##
 # shellcheck source=/home/rick/bin/functionlib.bash
 source functionlib.bash || { printf "\e[91mERROR:\e[0m Unable to source functionlib.bash\n"; exit 1; }
 
 help() {
   local -r script="$1"
   local -r version="$2"
-	local -r errcode="${3:-1}"
-	local -r updated="19 Jul 2026"
+	local -ri errcode="${3:-1}"
+	local -r updated="12 Aug 2026"
 	cat << _HELP_
 ${orange}$script${normal} $version ($updated)
 Installs, updated, or removes Google Chrome.
@@ -75,7 +75,12 @@ Signed-By: $key_file"
   return 0
 }
 
-install_chrome() {
+install_google_chrome() {
+  if installed google-chrome-stable; then
+    printf "%s is already installed." "$(chrome_version)"
+    return 0
+  fi
+  sudo_login 2
   local -r trusted_key="/usr/share/keyrings/google-chrome.gpg"
   printf "Updating apt cache and installing Google Chrome...\n"
   set_gpg_key "$trusted_key"
@@ -90,7 +95,12 @@ install_chrome() {
   return 0
 }
 
-purge_chrome() {
+remove_google_chrome() {
+  if ! installed google-chrome-stable; then
+    printf "Google Chrome is not installed.\n"
+    return 0
+  fi
+  sudo_login 2
   printf "Removing %s...\n" "$(chrome_version)"
   sudo apt purge google-chrome-stable
   find /etc/apt -maxdepth 2 -type f -iname "google*" -exec sudo rm {} \;
@@ -101,7 +111,7 @@ purge_chrome() {
 
 main() {
   local -r script="${0##*/}"
-  local -r version="6.0.26200"
+  local -r version="6.1.26224"
   local -i exit_code=0
   local opt OPTARG OPTIND
   local -i noOpt=1
@@ -109,25 +119,12 @@ main() {
   while getopts "$optstr" opt; do
     case "$opt" in
       h )
-        help "$script" "$version" 0
-        ;;
+        help "$script" "$version" 0 ;;
       i )
-        if installed google-chrome-stable; then
-          printf "%s is already installed.\n" "$(chrome_version)"
-        else
-          sudo_login 2
-          check_package wget
-          install_chrome
-        fi
-        ;;
+        check_package wget
+        install_google_chrome ;;
       r )
-        if installed google-chrome-stable; then
-          sudo_login 2
-          purge_chrome
-        else
-          printf "Google Chrome is not installed.\n"
-        fi
-        ;;
+        remove_google_chrome ;;
       ? )
         printf "%s Invalid option -%s\n" "$RED_ERROR" "$OPTARG" >&2
         help "$script" "$version" "$E_INVALID_ARG"
@@ -135,7 +132,10 @@ main() {
     exit_code="$?"
 	  noOpt=0
   done
-  [[ "$noOpt" = 1 ]] && { printf "%s No argument passed.\n" "$RED_ERROR" >&2; help "$script" "$version" "$E_MISSING_ARG"; }
+	if (( noOpt == 1 )); then
+		printf "%s No argument passed.\n" "$RED_ERROR" >&2
+		help "$script" "$version" "$E_MISSING_ARG"
+	fi
   shift "$(( OPTIND - 1 ))"
   over_line "$script $version"
   exit "$exit_code"
