install-batcat: error code variables & process substitution

diff --git a/install-batcat b/install-batcat
--- a/install-batcat
+++ b/install-batcat
@@ -7,7 +7,7 @@
 # Author       : Copyright © 2024 Richard B. Romig, Mosfanet
 # Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
 # Created      : 03 Aug 2024
-# Last updated : 14 Nov 2025
+# Last updated : 30 Jan 2026
 # Comments     : executable and its manpage will be renamed from ‘bat’ to ‘batcat’
 #              : because of a file name clash with another Debian package.
 #              : Mint 22 installs version 0.24.0 with suffix.
@@ -36,19 +36,19 @@ if [[ -x "$HOME/bin/functionlib" ]]; then
   source "$HOME/bin/functionlib"
 else
   printf "\e[91mERROR:\e[0m functionlib not found!\n" >&2
-  exit 1
+  exit 81
 fi
 
 ## Global Variables ##
 
 readonly script="${0##*/}"
-readonly version="2.8.25318"
+readonly version="2.9.26030"
 
 ## Functions ##
 
 help() {
-	local errcode="${1:-2}"
-	local updated="14 Nov 2025"
+	local errcode="${1:-1}"
+	local updated="30 Jan 2026"
 	cat << _HELP_
 ${orange}$script${normal} $version, Updated: $updated
 Installs/removes/configures bat/batcat
@@ -65,7 +65,7 @@ _HELP_
 }
 
 bat_version() {
-  dpkg -l bat | awk '/ii/ {print $3}'
+  awk '/^ii/ {print $3}' <(dpkg -l bat)
 }
 
 install_bat() {
@@ -140,11 +140,11 @@ main() {
 				;;
 			? )
 				printf "%s Invalid option -%s\n" "$RED_ERROR" "$OPTARG" >&2
-				help 2
+				help "$E_INVALID_ARG"
 		esac
 		noOpt=0
 	done
-	[[ "$noOpt" = 1 ]] && { printf "%s No argument passed.\n" "$RED_ERROR" >&2; help 1; }
+	[[ "$noOpt" = 1 ]] && { printf "%s No argument passed.\n" "$RED_ERROR" >&2; help "$E_MISSING_ARG"; }
 	shift "$(( OPTIND - 1 ))"
 	over_line "$script $version"
 	exit 0
