install-codium: fixed exist to exists

diff --git a/install-codium b/install-codium
--- a/install-codium
+++ b/install-codium
@@ -7,7 +7,7 @@
 # Author       : Copyright © 2023 Richard B. Romig, Mosfanet
 # Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
 # Created      : 04 Aug 2023
-# Updated      : 15 Nov 2025
+# Updated      : 20 Nov 2025
 # Comments     : Alternative to downloading directly from GitHub repo.
 # TODO (Rick)  :
 # License      : GNU General Public License, version 2.0
@@ -39,7 +39,7 @@ fi
 ## Global Variables ##
 
 readonly script="${0##*/}"
-readonly version="2.12.25319"
+readonly version="2.12.25324"
 readonly key_file="/usr/share/keyrings/vscodium-archive-keyring.asc"
 readonly src_list="/etc/apt/sources.list.d/vscodium.list"
 verbose_mode="$FALSE"
@@ -48,7 +48,7 @@ verbose_mode="$FALSE"
 
 help() {
 	local errcode="${1:-2}"
-	local updated="15 Nov 2025"
+	local updated="20 Nov 2025"
 	cat << _HELP_
 ${orange}$script${normal} $version, updated: ($updated)
 Install/Remove VSCodium and apply settings
@@ -101,7 +101,7 @@ install_vscodium() {
 	show_message "Updating apt cache and installing VSCodium..."
 	sudo apt-get update
 	sudo apt-get install codium
-	exist codium || die "VSCodium installation failed." 1
+	exists codium || die "VSCodium installation failed." 1
 	apply_settings
 	printf "VSCodium %s successfully installed.\n" "$(codium_version)"
 }
