install-firefox-deb: set_sources_list() here-string to create mozilla.list

diff --git a/install-firefox-deb b/install-firefox-deb
--- a/install-firefox-deb
+++ b/install-firefox-deb
@@ -7,7 +7,7 @@
 # Author       : Copyright © 2024 Richard B. Romig, Mosfanet
 # Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
 # Created      : 24 Jan 2024
-# Updated      : 03 Mar 2026
+# Updated      : 11 Apr 2026
 # Comments     : Remove Distro, Flatpak, or Snap version before installing.
 # TODO (Rick)  :
 # License      : GNU General Public License, version 2.0
@@ -24,22 +24,14 @@
 # GNU General Public License for more details.
 ##########################################################################
 
-## Shellcheck Directives ##
-# shellcheck source=/home/rick/bin/functionlib
-
 ## Source function library ##
-
-if [[ -x "$HOME/bin/functionlib" ]]; then
-  source "$HOME/bin/functionlib"
-else
-  printf "\e[91mERROR:\e[0m functionlib not found!\n" >&2
-  exit 81
-fi
+# shellcheck source=/home/rick/bin/functionlib
+source functionlib || { printf "\e[91mERROR:\e[0m Unable to source functionlib\n"; exit 1; }
 
 ## Global Variables ##
 
 readonly script="${0##*/}"
-readonly version="6.4.26062"
+readonly version="6.5.26101"
 readonly mozilla_asc="/etc/apt/keyrings/packages.mozilla.org.asc"
 verbose_mode="$FALSE"
 EC=0
@@ -48,7 +40,7 @@ EC=0
 
 help() {
 	local errcode="${1:-1}"
-	local -r updated="03 Mar 2026"
+	local -r updated="11 Apr 2026"
 	cat << _HELP_
 ${orange}$script${normal} $version, Upated: $updated
 Installs/Removes Mozilla repository version of Firefox.
@@ -116,7 +108,7 @@ set_sources_list() {
 		return
 	fi
 	show_message "Adding Mozilla APT repository to sources list..."
-	echo "deb [signed-by=$mozilla_asc] $list_url mozilla main" | sudo tee -a "$mozilla_list" > /dev/null
+	sudo tee -a "$mozilla_list" >/dev/null <<< "deb [signed-by=$mozilla_asc] $list_url mozilla main"
 }
 
 install_mozilla_deb() {
