install-geany: updated variables; added option to copy config files from cloned repository

diff --git a/install-geany b/install-geany
--- a/install-geany
+++ b/install-geany
@@ -1,5 +1,5 @@
 #!/usr/bin/env bash
-##########################################################################
+###############################################################################
 # Script Name  : install-geany
 # Description  : Installs the Geany editor/IDE with themes.
 # Dependencies : git
@@ -7,56 +7,66 @@
 # Author       : Copyright (C) 2022, Richard B. Romig,Mosfanet
 # Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
 # Created      : 25 Dec 2022
-# Updated      : 25 May 2026
+# Updated      : 26 Jul 2026
 # Comments     :
 # TODO (Rick)  :
 # License      : GNU General Public License, version 2.0
 # License URL  : https://github.com/RickRomig/scripts/blob/main/LICENSE
-##########################################################################
-# This program is free software; you can redistribute it and/or modify
-# it under the terms of the GNU General Public License as published by
-# the Free Software Foundation; either version 2 of the License, or
-# (at your option) any later version.
+###############################################################################
+# This program is free software; you can redistribute it and/or modify it under
+# the terms of the GNU General Public License as published by the Free Software
+# Foundation; either version 2 of the License, or (at your option) any later
+# version.
 #
-# This program is distributed in the hope that it will be useful,
-# but WITHOUT ANY WARRANTY; without even the implied warranty of
-# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
-# GNU General Public License for more details.
-##########################################################################
+# This program is distributed in the hope that it will be useful, but WITHOUT
+# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
+# FOR A PARTICULAR PURPOSE. See the# GNU General Public License for more details.
+###############################################################################
 
 ## Source function library ##
-# shellcheck source=/home/rick/bin/functionlib
-source ~/bin/functionlib || { printf "\e[91mERROR:\e[0m Unable to source functionlib\n"; exit 1; }
-
-## Global Variables ##
-
-readonly script="${0##*/}"
-readonly version="3.4.26145"
-verbose_mode="$FALSE"
-EC=0
-
-## Functions ##
+# shellcheck source=/home/rick/bin/functionlib.bash
+source ~/bin/functionlib.bash || { printf "\e[91mERROR:\e[0m Unable to source functionlib.bash\n"; exit 1; }
 
 help() {
-	local errcode="${1:-1}"
-	local updated="25 May 2026"
+  local -r script="$1"
+  local -r version="$2"
+	local -ri errcode="${3:-1}"
+	local updated=" 26 Jul 2026"
   cat << _HELP_
 ${orange}$script${normal} $version ($updated)
 Installs/Removes Geany text editor and themes
 
-${green}Usage:${normal} $script [-h] [-vi] [-vit] [-vr] [-vt]
+${green}Usage:${normal} $script [-h] [-v[cirt]]
 ${orange}Available options:${normal}
+  -c  Apply Geany configuration.
   -h  Show this help message and exit.
-  -i  Install Geany editor.
-  -r  Remove Geany editor.
+  -i  Install the Geany editor.
+  -r  Remove the Geany editor.
   -t  Install Geany themes.
   -v  Enable verbose mode. If used, must precede other flags.
+NOTE: for a full installation with cofniguation and themes, enter '$script =ict'
 _HELP_
   exit "$errcode"
 }
 
 geany_version() {
-  cut -d' ' -f2 < <(geany --version)
+  awk '/^ii/ {print $3}' < <(dpkg -l geany)
+  return 0
+}
+
+geany_config() {
+  local -r geany_cfg_d=~/.config/geany
+  local repository=~/Downloads/configs/geany
+  [[ -d ~/gitea/configs/geany ]] && repository=~/gitea/configs/geany
+  if [[ ! -d "$repository" ]]; then
+    printf "%s Configs repository not found!\n" "$RED_ERROR" >&2
+    return "$E_FILENOTFOUND"
+  fi
+  [[ -d "$geany_cfg_d" ]] || mkdir -p "$geany_cfg_d"
+  show_message "Applying configuration files."
+  cp -av "$repository"/. "$geany_cfg_d"
+  printf "Geany configuration files applied.\n"
+  return 0
 }
 
 clone_themes() {
@@ -69,69 +79,68 @@ clone_themes() {
   show_message "Copying Geany colorschemes..."
   awk -F"/" '{print "=> " $NF}' < <(cp -av "$cloned_dir"/colorschemes/. "$colorschemes_dir/") | sed "s/'//"
   printf "Geany themes installed.\n"
+  return 0
 }
 
 install_geany() {
+  sudo_login 2
   show_message "Installing Geany from repositories..."
-  sudo apt-get install -y geany libvte9
+  sudo apt-get install -y geany
   if ! installed geany; then
     printf "%s Geany installation failed.\n" "$RED_ERROR" >&2
-    EC="$E_INSTALLATION"
-    return
+    return "$E_INSTALLATION"
   fi
   printf "Geany %s installed.\n" "$(geany_version)"
-  geany_config
-}
-
-geany_config() {
-  local repository=~/Downloads/configs/geany
-  [[ -d ~/gitea/configs/geany ]] && repository=~/gitea/configs/geany
-  if [[ ! -d "$repository" ]]; then
-    printf "%s Configs repository not found!\n" "$RED_WARNING" >&2
-    EC="$E_FILENOTFOUND"
-    return
-  fi
-  [[ -d ~/.config/geany ]] || mkdir -p ~/.config/geany
-  show_message "Applying configuration files."
-  cp -av "$repository"/. ~/.config/geany/
-  printf "Geany configuration files applied.\n"
+  return 0
 }
 
 remove_geany() {
+  sudo_login 2
   show_message "Removing Geany $(geany_version)..."
   sudo apt-get purge -y geany
   show_message "Removing Geany configuration files ..."
   find ~/.config -type d -name geany -exec rm -rf {} \;
-  sudo find /usr/share -type f -name "geany*" -exec rm {} \;
+  sudo find /usr/share -type f,d -name "geany*" -exec sudo rm -rf {} \;
   printf "Geany and configuration files removed.\n"
+  return 0
 }
 
 show_message() {
-	local message="$1"
-	[[ "$verbose_mode" == "$TRUE" ]] && echo "$message"
+	local -r message="$1"
+	[[ "$VERBOSE" == "$TRUE" ]] && echo "$message"
+  return 0
 }
 
 main() {
-  local noOpt opt optstr OPTARG OPTIND
-  noOpt=1
-  optstr=":hirtv"
+  VERBOSE="$FALSE"
+  local -r script="${0##*/}"
+  local -r version="3.4.26145"
+  local -i exit_code=0
+  local opt OPTARG OPTIND
+  local -i noOpt=1
+  local -r optstr=":chirtv"
   check_package git
   while getopts "$optstr" opt; do
     case "$opt" in
+      c )
+        if installed geany; then
+          geany_config
+        else
+          printf "Geany is not installed.\n"
+        fi
+       ;;
       h )
-        help 0
+        help "$script" "$version" 0
         ;;
       i )
         if installed geany; then
           printf "Geany %s is already installed.\n" "$(geany_version)"
         else
-          sudo_login 2
           install_geany
         fi
         ;;
       r )
         if installed geany; then
-          sudo_login 2
           remove_geany
         else
           printf "Geany is not installed.\n"
@@ -145,21 +154,20 @@ main() {
         fi
         ;;
       v )
-        verbose_mode="$TRUE"
+        VERBOSE="$TRUE"
 			  show_message "Verbose mode enabled."
         ;;
       ? )
         printf "%s Invalid option -%s\n" "$RED_ERROR" "$OPTARG" >&2
-        help "$E_INVALID_ARG"
+        help "$script" "$version" "$E_INVALID_ARG"
     esac
+    exit_code="$?"
     noOpt=0
   done
-  [[ "$noOpt" = 1 ]] && { printf "%s No argument passed.\n" "$RED_ERROR" >&2; help "$E_MISSING_ARG"; }
+  [[ "$noOpt" = 1 ]] && { printf "%s No argument passed.\n" "$RED_ERROR" >&2; help "$script" "$version" "$E_MISSING_ARG"; }
   shift "$(( OPTIND - 1 ))"
   over_line "$script $version"
-  exit "$EC"
+  exit "$exit_code"
 }
-
-## Execution ##
 
 main "$@"
