Replaced if-else for getopts with noOpt variable. Displays help and exits if no argument passed.

diff --git a/install-kitty b/install-kitty
--- a/install-kitty
+++ b/install-kitty
@@ -1,4 +1,4 @@
-#!/usr/bin/env bash
+#!/bin/bash
 ##########################################################################
 # Script Name  : install-kitty
 # Description  : Installs kitty terminal emulator with basic configuration.
@@ -27,8 +27,8 @@ fi
 ## Variables ##
 
 _script=$(basename "$0"); readonly _script
-readonly _version="0.1.5"
-readonly _updated="04 Feb 2023"
+readonly _version="0.1.6"
+readonly _updated="29 Mar 2023"
 readonly kitty_cfg="$HOME/.config/kitty"
 
 ## Functions ##
@@ -90,39 +90,36 @@ kitty_config() {
 
 ## Execution ##
 
-# clear
-if [[ "$#" -eq 0 ]]; then
-  printf "%s No argument passed.\n" "$red_error" >&2
-  help 1
-else
-  optstr=":chir"
-  while getopts "$optstr" opt; do
-    case "$opt" in
-      c )
-        exists kitty || leave "Kitty is not installed."
-        printf "Configuring Kitty %s...\n" "$(kitty_version)"
-        kitty_config
-        break ;;
-      h )
-        help 0
-        ;;
-      i )
-        exists kitty && leave "Kitty terminal emulator $(kitty_version) already installed.\n"
-        user_in_sudo
-        install_kitty
-        break ;;
-      r )
-        exists kitty || leave "Kitty is not installed."
-        user_in_sudo
-        remove_kitty
-        break ;;
-      ? )
-        printf "%s Invalid option -%s\n" "$red_error" "$OPTARG" >&2
-        help 2
-        ;;
-    esac
-  done
-fi
-printf "\U1F427 %s v%s (%s)\n" "$_script" "$_version" "$_updated"
+noOpt=1
+optstr=":chir"
+while getopts "$optstr" opt; do
+  case "$opt" in
+    c )
+      exists kitty || leave "Kitty is not installed."
+      printf "Configuring Kitty %s...\n" "$(kitty_version)"
+      kitty_config
+      break ;;
+    h )
+      help 0
+      ;;
+    i )
+      exists kitty && leave "Kitty terminal emulator $(kitty_version) already installed."
+    user_in_sudo
+      install_kitty
+      break ;;
+    r )
+      exists kitty || leave "Kitty is not installed."
+      user_in_sudo
+      remove_kitty
+      break ;;
+    ? )
+      printf "%s Invalid option -%s\n" "$red_error" "$OPTARG" >&2
+      help 2
+      ;;
+  esac
+	noOpt=0
+done
+if [ $noOpt = 1 ];then printf "%s No argument passed.\n" "$red_error" >&2;help 1;fi
+printf "%s v%s (%s)\n" "$_script" "$_version" "$_updated"
 
 exit
diff --git a/install-neofetch b/install-neofetch
--- a/install-neofetch
+++ b/install-neofetch
@@ -27,8 +27,8 @@ fi
 ## Variables ##
 
 _script=$(basename "$0"); readonly _script
-readonly _version="0.1.1"
-readonly _updated="04 Feb 2023"
+readonly _version="0.1.2"
+readonly _updated="29 Mar 2023"
 readonly cfg_dir="${HOME}/.config/neofetch"
 readonly thumbnail_dir="${HOME}/.cache/thumbnails/neofetch"
 
@@ -44,6 +44,7 @@ ${orange}OPTIONS:${normal}
 	-i	Install and configure Neofetch
 	-r	Remove Neofetch and configuration
 EOL
+	printf "%s v%s (%s)\n" "$_script" "$_version" "$_updated"
   exit "$errcode"
 }
 
@@ -86,36 +87,32 @@ remove_neofetch() {
 
 ## Execution ##
 
-clear
-printf "\U1F427 %s v%s (%s)\n" "$_script" "$_version" "$_updated"
 printf "Install/Remove Neofetch or apply configuration\n\n"
 
-if [[ "$#" -eq 0 ]]; then
-	echo "${lightred}ERROR:${normal} No argument passed." >&2
-	help 1
-else
-	optstr=":chir"
-	while getopts "$optstr" opt; do
-		case "$opt" in
-			c )
-				apply_config
-				exit 0
-				;;
-			h )
-				help 0
-				;;
-			i )
-				install_neofetch
-				;;
-			r )
-				remove_neofetch
-				;;
-			? )
-				echo "${lightred}ERROR:${normal}Invalid option -${OPTARG}" >&2
-				help 2
-				;;
-		esac
-	done
-fi
-
+noOpt=1
+optstr=":chir"
+while getopts "$optstr" opt; do
+	case "$opt" in
+		c )
+			apply_config
+			exit 0
+			;;
+		h )
+			help 0
+			;;
+		i )
+			install_neofetch
+			;;
+		r )
+			remove_neofetch
+			;;
+		? )
+			echo "${lightred}ERROR:${normal}Invalid option -${OPTARG}" >&2
+			help 2
+			;;
+	esac
+	noOpt=0
+done
+if [ $noOpt = 1 ];then printf "%s No argument passed.\n" "$red_error" >&2;help 1;fi
+printf "%s v%s (%s)\n" "$_script" "$_version" "$_updated"
 exit
diff --git a/install-terminator b/install-terminator
--- a/install-terminator
+++ b/install-terminator
@@ -2,19 +2,11 @@
 ##########################################################################
 # Script Name  : install-terminator
 # Description  : Installs the Terminator terminal emulator from repos.
-# Dependencies : sshfs
+# Dependencies : None
 # Arguments    : -c -h -i -r (See help function)
 # Author       : Richard B. Romig, 14 Dec 2020
 # Email        : rick.romig@gmail.com
 # Comments     : Installs config file & Cascadia Code font from HP-6005
-# 31 Jan 2022  : Added option to write config file. Updated help.
-# 23 Feb 2022  : Incorporated `getopts` to process options.
-# 25 Feb 2022  : Modified code to check if Debian-based distro.
-# 29 Mar 2022  : Added $OPTARG to Invalid option message.
-# 10 Jul 2022  : Added optstr and opt variables to getopts routine.
-# 10 Sep 2022  : Installs Cascadia-Code fonts if needed.
-# 30 Dec 2022  : Modified function to install cascadia code fonts.
-# 02 Jan 2023  : Added function to get version. Checks exists in getopts case.
 # TODO (Rick)  :
 # License      : GNU General Public License, version 2.0
 ##########################################################################
@@ -35,10 +27,9 @@ fi
 ## Variables ##
 
 _script=$(basename "$0"); readonly _script
-readonly _version="0.6.0"
-readonly _updated="02 Jan 2023"
+readonly _version="0.6.1"
+readonly _updated="29 Mar 2023"
 readonly term_cfg=$HOME"/.config/terminator"
-readonly svr_ip="11"
 
 ## Functions ##
 
@@ -56,14 +47,14 @@ ${bold}NOTES:${normal}
      Configuration changes should be made through the Preferences menu.
   2. For Debian and Debian-based distributions (Antix, MX Linux, LMDE),
      Terminator will be configured in the config file as a login shell.
-  3. Cascadia Code 14 font is installed by default (from local server).
+  3. Cascadia Code 14 font is installed by default.
 EOF
   exit "$errcode"
 }
 
 remove_terminator() {
   sudo apt-get purge terminator
-  [[ -d "$Hterm_cfg" ]] && rm -rf "$term_cfg"
+  [[ -d "$term_cfg" ]] && rm -rf "$term_cfg"
   leave "Terminator and its configuration files have been removed."
 }
 
@@ -128,10 +119,6 @@ install_cascadia_code() {
   fi
 }
 
-check_dependencies() {
-  check_package sshfs
-}
-
 terminator_version() {
   dpkg -l | awk '$2 == "terminator" {print $3}' | sed 's/[+-].*//'
 }
@@ -141,38 +128,36 @@ terminator_version() {
 check_dependencies
 
 echo "$_script v$_version ($_updated)"
-echo -e "Installs or removes Terminator with config and Cascadia Code font."
+echo -e  "Installs or removes Terminator with config and Cascadia Code font.\n"
 
-if [[ "$#" -eq 0 ]]; then
-  echo $'\n'$"${lightred}ERROR:${normal} No argument passed." >&2
-  help 2
-else
-  optstr=":chir"
-  while getopts "$optstr" opt; do
-    case "$opt" in
-      c )
-        exists terminator || leave "Terminator is not installed."
-        if bunsenlabs; then
-          echo "Terminator configuration for BunsenLabs was not overwritten."
-          leave "Configuration changes should be made through the Preferences menu."
-        else
-          teminator_config
-          is_debian && sed -i '/login_shell/s/False/True/' "$term_cfg/config"
-          leave "Terminator configuration file written."
-        fi ;;
-      h )
-        help 0 ;;
-      i )
-        exists terminator && leave "Terminator $(terminator_version) is already installed."
-        user_in_sudo
-        install_terminator ;;
-      r )
-        exists terminator || leave "Terminator is not installed."
-        user_in_sudo
-        remove_terminator ;;
-      ? )
-        echo "${lightred}ERROR:${normal} Invalid option -${OPTARG}" >&2
-        help 2 ;;
+noOpt=1
+optstr=":chir"
+while getopts "$optstr" opt; do
+  case "$opt" in
+    c )
+      exists terminator || leave "Terminator is not installed."
+      if bunsenlabs; then
+        echo "Terminator configuration for BunsenLabs was not overwritten."
+        leave "Configuration changes should be made through the Preferences menu."
+      else
+        teminator_config
+        is_debian && sed -i '/login_shell/s/False/True/' "$term_cfg/config"
+        leave "Terminator configuration file written."
+      fi ;;
+    h )
+      help 0 ;;
+    i )
+      exists terminator && leave "Terminator $(terminator_version) is already installed."
+      user_in_sudo
+      install_terminator ;;
+    r )
+      exists terminator || leave "Terminator is not installed."
+      user_in_sudo
+      remove_terminator ;;
+    ? )
+      echo "${lightred}ERROR:${normal} Invalid option -${OPTARG}" >&2
+      help 2 ;;
     esac
-  done
-fi
+  	noOpt=0
+done
+if [ $noOpt = 1 ];then echo "${lightred}ERROR:${normal} No argument passed." >&2;help 1;fi
diff --git a/install-ufw b/install-ufw
--- a/install-ufw
+++ b/install-ufw
@@ -27,8 +27,8 @@ fi
 ## Global Variables ##
 
 _script=$(basename "$0"); readonly _script
-readonly _version="0.1.2"
-readonly _updated="23 Jan 2023"
+readonly _version="0.1.3"
+readonly _updated="29 Mar 2023"
 
 ## Functions ##
 
@@ -104,55 +104,50 @@ debian_system() {
 
 ## Execution ##
 
-# clear
 printf "For Debian, BunsenLabs, and MX Linux systems.\n"
 printf "UFW/GUFW is installed by default on Mint & Ubuntu.\n"
-if [[ "$#" -eq 0 ]]; then
-  printf "%s No argument passed.\n" "$red_error" >&2
-  help 1
-else
-  optstr=":dehirs"
-  while getopts "$optstr" opt; do
-    case "$opt" in
-      d )
-        dpkg -l | grep -qw ufw || leave "UFW is not installed."
-        user_in_sudo
-        ufw_status || leave "UFW $(ufw_version) is already disabled."
-        disable_ufw
-        break ;;
-      e )
-        dpkg -l | grep -qw ufw || leave "UFW is not installed."
-        user_in_sudo
-        ufw_status && leave "UFW $(ufw_version) is already enabled."
-        enable_ufw
-        break ;;
-      h )
-        help 0 ;;
-      i )
-        debian_system || die "Not a Debian-based system."
-        dpkg -l | grep -qw ufw && leave "UFW $(ufw_version) is already installed."
-        user_in_sudo
-        install_ufw
-        add_rules
-        enable_ufw
-        printf "UFW %s installed and configured.\n" "$(ufw_version)"
-        break ;;
-      r )
-        debian_system || die "Not a Debian-based system."
-        dpkg -l | grep -qw ufw || leave "UFW is not installed."
-        user_in_sudo
-        remove_ufw
-        break ;;
-      s )
-        dpkg -l | grep -qw ufw || leave "UFW is not installed."
-        user_in_sudo
-        printf "UFW %s\n" "$(ufw_version)"
-        sudo ufw status numbered
-        break ;;
-      ? )
-        printf "%s Invalid option -%s\n" "$red_error" "$OPTARG" >&2
-    esac
-  done
-fi
+noOpt=1
+optstr=":dehirs"
+while getopts "$optstr" opt; do
+  case "$opt" in
+    d )
+      dpkg -l | grep -qw ufw || leave "UFW is not installed."
+      user_in_sudo
+      ufw_status || leave "UFW $(ufw_version) is already disabled."
+      disable_ufw
+      break ;;
+    e )
+      dpkg -l | grep -qw ufw || leave "UFW is not installed."
+      user_in_sudo
+      ufw_status && leave "UFW $(ufw_version) is already enabled."
+      enable_ufw
+      break ;;
+    h )
+      help 0 ;;
+    i )
+      debian_system || die "Not a Debian-based system."
+      dpkg -l | grep -qw ufw && leave "UFW $(ufw_version) is already installed."
+      user_in_sudo
+      install_ufw
+      add_rules
+      enable_ufw
+      printf "UFW %s installed and configured.\n" "$(ufw_version)"
+      break ;;
+    r )
+      debian_system || die "Not a Debian-based system."
+      dpkg -l | grep -qw ufw || leave "UFW is not installed."
+      user_in_sudo
+      remove_ufw
+      break ;;
+    s )
+      dpkg -l | grep -qw ufw || leave "UFW is not installed."
+      user_in_sudo
+      printf "UFW %s\n" "$(ufw_version)"
+      sudo ufw status numbered
+      printf "%s Invalid option -%s\n" "$red_error" "$OPTARG" >&2
+  esac
+	noOpt=0
+done
+if [ $noOpt = 1 ];then printf "%s No argument passed.\n" "$red_error" >&2;help 1;fi
 printf "%s v%s (%s)\n" "$_script" "$_version" "$_updated"
 exit
diff --git a/install-zoom b/install-zoom
--- a/install-zoom
+++ b/install-zoom
@@ -27,8 +27,8 @@ fi
 ## Global Variables ##
 
 _script=$(basename "$0"); readonly _script
-readonly _version="0.1.4"
-readonly _updated="17 Mar 2023"
+readonly _version="0.1.5"
+readonly _updated="29 Mar 2023"
 
 ## Functions ##
 
@@ -51,7 +51,7 @@ ${orange}OPTIONS:${normal}
 	-i 	Install Zoom
 	-r 	Remove Zoom
 END_HELP
-	printf "\U1F427 %s v%s (%s)\n" "$_script" "$_version" "$_updated"
+	printf "%s v%s (%s)\n" "$_script" "$_version" "$_updated"
   exit "$errcode"
 }
 
@@ -80,36 +80,34 @@ remove_zoom() {
 
 ## Execution ##
 
-if [[ "$#" -eq 0 ]]; then
-	printf "%s No argument passed.\n" "$red_error"  >&2
-	help 1
-else
-	optstr=":hir"
-	while getopts "$optstr" opt; do
-		case "$opt" in
-			h )
-				help 0
-				;;
-			i )
-				exists zoom && printf "Zoom %s is installed.\n" "$(zoom_version)"
-				tmp_dir=$(mktemp -d) || die "Failed to create temporary directory." 1
-				trap cleanup EXIT
-				user_in_sudo
-				install_zoom
-				break
-				;;
-			r )
-				exists zoom || leave "Zoom is not installed."
-				user_in_sudo
-				remove_zoom
-				break
-				;;
-			? )
-				printf "%s Invalid option -%s\n" "$red_error" "$OPTARG" >&2
-				help 2
-				;;
-		esac
-	done
-fi
+noOpt=1
+optstr=":hir"
+while getopts "$optstr" opt; do
+	case "$opt" in
+		h )
+			help 0
+			;;
+		i )
+			exists zoom && printf "Zoom %s is installed.\n" "$(zoom_version)"
+			tmp_dir=$(mktemp -d) || die "Failed to create temporary directory." 1
+			trap cleanup EXIT
+			user_in_sudo
+			install_zoom
+			break
+			;;
+		r )
+			exists zoom || leave "Zoom is not installed."
+			user_in_sudo
+			remove_zoom
+			break
+			;;
+		? )
+			printf "%s Invalid option -%s\n" "$red_error" "$OPTARG" >&2
+			help 2
+			;;
+	esac
+	noOpt=0
+done
+if [ $noOpt = 1 ];then printf "%s No argument passed.\n" "$red_error" >&2;help 1;fi
 printf "\U1F427 %s v%s (%s)\n" "$_script" "$_version" "$_updated"
 exit
