install-librewolf: changed indentation tabs from 2 to 4 spaces; updated return codes

diff --git a/install-librewolf b/install-librewolf
--- a/install-librewolf
+++ b/install-librewolf
@@ -7,9 +7,9 @@
 # Author       : Copyright © 2025 Richard B. Romig, Mosfanet
 # Email        : rick.romig@gmail | rick.romig@mymetronet.net
 # Created      : 01 Mar 2025
-# Updated      : 13 Aug 2026
-# Version      : 1.10.26225
-# Comments     : instructions from https://librewolf.net/
+# Updated      : 08 Sep 2026
+# Version      : 1.11.26251
+# Comments     : Instructions obtained from https://librewolf.net/
 # TODO (Rick)  :
 # License      : GNU General Public License, version 2.0
 # License URL  : https://github.com/RickRomig/scripts/blob/main/LICENSE
@@ -30,33 +30,33 @@ source ~/bin/functionlib.bash || { printf "\e[91mERROR:\e[0m Unable to source fu
 VERBOSE="$FALSE"
 
 help() {
-  local -r script="$1"
-  local -r version="$2"
+	local -r script="$1"
+	local -r version="$2"
 	local -ri errcode="${3:-1}"
-	local -r updated="13 Aug 2026"
-	cat << _HELP_
-${orange}$script${normal} $version, Upated: $updated
-Installs/removes LibreWolf browser.
+	local -r updated="08 Sep 2026"
+	cat <<- _HELP_
+	${orange}$script${normal} $version, Upated: $updated
+	Installs/removes LibreWolf browser.
 
-${green}Usage:${normal} $script [-h] [-vi] [-vr]
-${orange}Available options:${normal}
-  -h  Show this help message and exit.
-  -i  Install LibreWolf.
-  -r  Remove LibreWolf.
-  -v  Enable verbose mode. If used, must prccede -i and -r.
+	${green}Usage:${normal} $script [-h] [-vi] [-vr]
+	${orange}Available options:${normal}
+	-h	Show this help message and exit.
+	-i	Install LibreWolf.
+	-r	Remove LibreWolf.
+	-v	Enable verbose mode. If used, must prccede -i and -r.
 _HELP_
-  exit "$errcode"
+	exit "$errcode"
 }
 
 lw_version() {
 	awk '{print $NF}' < <(librewolf --version)
-  return 0
+	return 0
 }
 
 show_message() {
-	local message="$1"
+	local -r message="$1"
 	[[ "$VERBOSE" == "$TRUE" ]] && echo "$message"
-  return 0
+	return 0
 }
 
 check_extrepo() {
@@ -71,13 +71,13 @@ check_extrepo() {
 	fi
 	sudo extrepo enable librewolf && sudo extrepo update librewolf
 	printf "extrepo installed and librewolf repo enabled.\n"
-  return 0
+	return 0
 }
 
 install_librewolf() {
 	if installed librewolf; then
 		printf "LibreWolf %s is already installed.\n" "$(lw_version)" >&2
-		return 1
+		return "$E_FILE_EXISTS"
 	fi
 	sudo_login 2
 	printf "Installing LibreWolf browser...\n"
@@ -85,17 +85,18 @@ install_librewolf() {
 	check_extrepo
 	show_message "Installing LibreWolf..."
 	sudo apt update && sudo apt install librewolf -y
-  if ! installed librewolf; then
-    printf "%s LibreWolf installation failed.\n" "$RED_ERROR" >&2
-    return "$E_INSTALLATION"
-  fi
+	if ! installed librewolf; then
+		printf "%s LibreWolf installation failed.\n" "$RED_ERROR" >&2
+		return "$E_INSTALLATION"
+	fi
 	printf "LibreWolf browser version %s installed.\n" "$(lw_version)"
+	return 0
 }
 
 remove_librewolf() {
 	if ! installed librewolf; then
 		printf "LibreWolf is not installed.\n" >&2
-		return 1
+		return "$E_NOT_INSTALLED"
 	fi
 	sudo_login 2
 	printf "Removing LibreWolf browser %s...\n" "$(lw_version)"
@@ -115,11 +116,11 @@ remove_librewolf() {
 
 main() {
 	local -r script="${0##*/}"
-	local -r version="1.10.26225"
-  local -i exit_code=0
-	local opt OPTARG OPTIND
+	local -r version="1.11.26251"
+	local -i exit_code=0
 	local -i noOpt=1
 	local -r optstr=":hirv"
+	local opt OPTARG OPTIND
 	while getopts "$optstr" opt; do
 		case "$opt" in
 			h )
@@ -133,7 +134,7 @@ main() {
 				show_message "Verbose mode enabled." ;;
 			? )
 				printf "%s Invalid option -%s\n" "$RED_ERROR" "$OPTARG" >&2
-        help "$script" "$version" "$E_INVALID_ARG"
+				help "$script" "$version" "$E_INVALID_ARG"
 		esac
 		exit_code="$?"
 		noOpt=0
