install-librewolf: installation checks in install/remove functions

diff --git a/install-librewolf b/install-librewolf
--- a/install-librewolf
+++ b/install-librewolf
@@ -7,7 +7,8 @@
 # Author       : Copyright © 2025 Richard B. Romig, Mosfanet
 # Email        : rick.romig@gmail | rick.romig@mymetronet.net
 # Created      : 01 Mar 2025
-# Updated      : 20 Jul 2026
+# Updated      : 13 Aug 2026
+# Version      : 1.10.26225
 # Comments     : instructions from https://librewolf.net/
 # TODO (Rick)  :
 # License      : GNU General Public License, version 2.0
@@ -23,15 +24,16 @@
 # FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
 ###############################################################################
 
-## Source function library ##
 # shellcheck source=/home/rick/bin/functionlib.bash
 source ~/bin/functionlib.bash || { printf "\e[91mERROR:\e[0m Unable to source functionlib.bash\n"; exit 1; }
+
+VERBOSE="$FALSE"
 
 help() {
   local -r script="$1"
   local -r version="$2"
-	local errcode="${3:-1}"
-	local -r updated="20 Jul 2026"
+	local -ri errcode="${3:-1}"
+	local -r updated="13 Aug 2026"
 	cat << _HELP_
 ${orange}$script${normal} $version, Upated: $updated
 Installs/removes LibreWolf browser.
@@ -73,6 +75,10 @@ check_extrepo() {
 }
 
 install_librewolf() {
+	if installed librewolf; then
+		printf "LibreWolf %s is already installed.\n" "$(lw_version)" >&2
+		return 1
+	fi
 	sudo_login 2
 	printf "Installing LibreWolf browser...\n"
 	show_message "Checking for extrepo..."
@@ -87,8 +93,12 @@ install_librewolf() {
 }
 
 remove_librewolf() {
-	printf "Removing LibreWolf browser %s...\n" "$(lw_version)"
+	if ! installed librewolf; then
+		printf "LibreWolf is not installed.\n" >&2
+		return 1
+	fi
 	sudo_login 2
+	printf "Removing LibreWolf browser %s...\n" "$(lw_version)"
 	show_message "Removing LibreWolf..."
 	sudo extrepo disable librewolf
 	sudo apt remove -y librewolf
@@ -104,9 +114,8 @@ remove_librewolf() {
 }
 
 main() {
-	VERBOSE="$FALSE"
 	local -r script="${0##*/}"
-	local -r version="1.9.26201"
+	local -r version="1.10.26225"
   local -i exit_code=0
 	local opt OPTARG OPTIND
 	local -i noOpt=1
@@ -114,40 +123,28 @@ main() {
 	while getopts "$optstr" opt; do
 		case "$opt" in
 			h )
-				help "$script" "$version" 0
-				;;
+				help "$script" "$version" 0 ;;
 			i )
-				if installed librewolf; then
-					printf "LibreWolf %s is already installed.\n" "$(lw_version)"
-				else
-					install_librewolf
-					exit_code="$?"
-				fi
-				;;
+				install_librewolf ;;
 			r )
-				if installed librewolf; then
-					remove_librewolf
-					exit_code="$?"
-				else
-					printf "LibreWolf is not installed.\n"
-				fi
-				;;
+				remove_librewolf ;;
 			v )
 				VERBOSE="$TRUE"
-				show_message "Verbose mode enabled."
-				;;
+				show_message "Verbose mode enabled." ;;
 			? )
 				printf "%s Invalid option -%s\n" "$RED_ERROR" "$OPTARG" >&2
         help "$script" "$version" "$E_INVALID_ARG"
 		esac
+		exit_code="$?"
 		noOpt=0
 	done
-  [[ "$noOpt" = 1 ]] && { printf "%s No argument passed.\n" "$RED_ERROR" >&2; help "$script" "$version" "$E_MISSING_ARG"; }
+	if (( noOpt == 1 )); then
+		printf "%s No argument passed.\n" "$RED_ERROR" >&2
+		help "$script" "$version" "$E_MISSING_ARG"
+	fi
 	shift "$(( OPTIND - 1 ))"
 	over_line "$script $version"
 	exit "$exit_code"
 }
-
-## Execution ##
 
 main "$@"
