install-kitty: changed indentation tabs from 2 to 4 spaces; updated return codes

diff --git a/install-kitty b/install-kitty
--- a/install-kitty
+++ b/install-kitty
@@ -2,13 +2,13 @@
 ###############################################################################
 # Script Name  : install-kitty
 # Description  : Installs kitty terminal emulator with basic configuration.
-# Dependencies : git
+# Dependencies : None
 # Arguments    : -c -h -i -p -r (see help function for more information)
 # Author       : Copyright (C) 2022, Richard B. Romig, LudditeGeek
 # Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
 # Created      : 26 Sep 2022
-# Updated      : 13 Aug 2026
-# Version      : 2.9.26225
+# Updated      : 08 Sep 2026
+# Version      : 2.10.26251
 # Comments     : Configures as a login terminal for Debian-based distros.
 # TODO (Rick)  :
 # License      : GNU General Public License, version 2.0
@@ -27,105 +27,104 @@
 source ~/bin/functionlib.bash || { printf "\e[91mERROR:\e[0m Unable to source functionlib.bash\n"; exit 1; }
 
 help() {
-  local -r script="$1"
-  local -r version="$2"
+	local -r script="$1"
+	local -r version="$2"
 	local -ri errcode="${3:-1}"
-	local -r updated="13 Aug 2026"
-	cat << _HELP_
-${orange}$script${normal} $version ($updated)
-Installs/Removes/Configures Kitty terminal emulator
+	local -r updated="08 Sep 2026"
+	cat <<- _HELP_
+	${orange}$script${normal} $version ($updated)
+	Installs/Removes/Configures Kitty terminal emulator
 
-${green}Usage:${normal} $script [-hir]
-${orange}Available options:${normal}
-  -h  Show this help message and exit
-  -i  Install Kitty from distro repositories
-  -r  Remove Kitty from system
+	${green}Usage:${normal} $script [-hir]
+	${orange}Available options:${normal}
+	-h	Show this help message and exit
+	-i	Install Kitty from distro repositories
+	-r	Remove Kitty from system
 _HELP_
-  exit "$errcode"
+	exit "$errcode"
 }
 
 kitty_version() {
-  cut -d' ' -f2 < <(kitty --version)
-  return 0
+	cut -d' ' -f2 < <(kitty --version)
+	return 0
 }
 
 install_kitty() {
-  if installed kitty; then
-    printf "Kitty %s already installed.\n" "$(kitty_version)"
-    return 1
-  fi
-  sudo_login 2
-  printf "Installing the kitty terminal emulator.\n"
-  sudo apt-get install -y kitty imagemagick
-  if ! installed kitty; then
-    printf "%s Kitty installation failed.\n" "$RED_ERROR" >&2
-    return "$E_INSTALLATION"
-  fi
-  printf "Kitty %s installed.\n" "$(kitty_version)"
-  return "$?"
+	if installed kitty; then
+		printf "Kitty %s already installed.\n" "$(kitty_version)"
+		return "$E_FILE_EXISTS"
+	fi
+	sudo_login 2
+	printf "Installing the kitty terminal emulator.\n"
+	sudo apt-get install -y kitty imagemagick
+	if ! installed kitty; then
+		printf "%s Kitty installation failed.\n" "$RED_ERROR" >&2
+		return "$E_INSTALLATION"
+	fi
+	printf "Kitty %s installed.\n" "$(kitty_version)"
+	return "$?"
 }
 
 remove_kitty() {
-  if ! installed kitty; then
-    printf "Kitty is not installed.\n"
-    return 1
-  fi
-  sudo_login 2
-  printf "Purging the Kitty %s terminal emulator...\n" "$(kitty_version)"
-  sudo apt-get purge kitty -yy
-  [[ -L ~/.config/kitty/kitty.conf ]] && unlink ~/.config/kitty/kitty.conf
-  [[ -L ~/.config/kitty/keybindings.conf ]] && unlink ~/.config/kitty/keybindings.conf
-  find ~/ -maxdepth 3 -path ~/Downloads -prune -o -path ~/gitea -prune -o -type d -name "kitty*" -exec rm -rf {} \;
-  find ~/ -maxdepth 2 -type f -iname "kitty*" -delete
-  printf "The Kitty terminal emulator and configuration files have been removed.\n"
-  return 0
+	if ! installed kitty; then
+		printf "Kitty is not installed.\n"
+		return "$E_NOT_INSTALLED"
+	fi
+	sudo_login 2
+	printf "Purging the Kitty %s terminal emulator...\n" "$(kitty_version)"
+	sudo apt-get purge kitty -yy
+	[[ -L ~/.config/kitty/kitty.conf ]] && unlink ~/.config/kitty/kitty.conf
+	[[ -L ~/.config/kitty/keybindings.conf ]] && unlink ~/.config/kitty/keybindings.conf
+	find ~/ -maxdepth 3 -path ~/Downloads -prune -o -path ~/gitea -prune -o -type d -name "kitty*" -exec rm -rf {} \;
+	find ~/ -maxdepth 2 -type f -iname "kitty*" -delete
+	printf "The Kitty terminal emulator and configuration files have been removed.\n"
+	return 0
 }
 
 kitty_config() {
-  local repository=~/Downloads/configs/kitty
-  [[ -d ~/gitea/configs/kitty ]] && repository=~/gitea/configs/kitty
-  if [[ ! -d "$repository" ]]; then
-    printf "%s Configs repository not found!\n" "$RED_ERROR" >&2
-    return "$E_FILENOTFOUND"
-  fi
-  [[ -d ~/.config/kitty ]] || mkdir -p ~/.config/kitty
-  printf "Applying configuration files ...\n"
-  cp -v "$repository"/*.conf ~/.config/kitty/
-  [[ "$DESKTOP_SESSION" != "i3" ]] && sed -i.bak '/hide_window_decorations/s/yes/no/' ~/.config/kitty/kitty.conf
-  printf "kitty configuration files applied.\n"
-  return 0
+	local repository=~/Downloads/configs/kitty
+	[[ -d ~/gitea/configs/kitty ]] && repository=~/gitea/configs/kitty
+	if [[ ! -d "$repository" ]]; then
+		printf "%s Configs repository not found!\n" "$RED_ERROR" >&2
+		return "$E_FILENOTFOUND"
+	fi
+	[[ -d ~/.config/kitty ]] || mkdir -p ~/.config/kitty
+	printf "Applying configuration files ...\n"
+	cp -v "$repository"/*.conf ~/.config/kitty/
+	[[ "$DESKTOP_SESSION" != "i3" ]] && sed -i.bak '/hide_window_decorations/s/yes/no/' ~/.config/kitty/kitty.conf
+	printf "kitty configuration files applied.\n"
+	return 0
 }
 
 main() {
-  check_package git
-  local opt OPTARG OPTIND
-  local -r script="${0##*/}"
-  local -r version="2.9.26225"
-  local -i exit_code=0
-  local -i noOpt=1
-  local -r optstr=":hir"
-  while getopts "$optstr" opt; do
-    case "$opt" in
-      h )
-        help "$script" "$version" 0 ;;
-      i )
-        install_kitty && kitty_config ;;
-      r )
-        remove_kitty;;
-      ? )
-        printf "%s Invalid option -%s\n" "$RED_ERROR" "$OPTARG" >&2
-        help "$script" "$version" "$E_INVALID_ARG"
-    esac
-    exit_code="$?"
-	  noOpt=0
-  done
+	local -r script="${0##*/}"
+	local -r version="2.10.26251"
+	local -i exit_code=0
+	local -i noOpt=1
+	local -r optstr=":hir"
+	local opt OPTARG OPTIND
+	while getopts "$optstr" opt; do
+		case "$opt" in
+			h )
+				help "$script" "$version" 0 ;;
+			i )
+				install_kitty && kitty_config ;;
+			r )
+				remove_kitty;;
+			? )
+				printf "%s Invalid option -%s\n" "$RED_ERROR" "$OPTARG" >&2
+				help "$script" "$version" "$E_INVALID_ARG"
+		esac
+		exit_code="$?"
+		noOpt=0
+	done
 	if (( noOpt == 1 )); then
 		printf "%s No argument passed.\n" "$RED_ERROR" >&2
 		help "$script" "$version" "$E_MISSING_ARG"
 	fi
-  shift "$(( OPTIND - 1 ))"
-  over_line "$script $version"
-  exit "$exit_code"
+	shift "$(( OPTIND - 1 ))"
+	over_line "$script $version"
+	exit "$exit_code"
 }
 
 main "$@"
