install-timeshift: install-timeshift() - added 'RED_ERROR' to error message

diff --git a/install-timeshift b/install-timeshift
--- a/install-timeshift
+++ b/install-timeshift
@@ -59,7 +59,7 @@ install_timeshift() {
   printf "Installing Timeshift...\n"
   sudo apt-get install -y timeshift
   if ! installed timeshift; then
-    printf "Timeshift installation failed." >&2
+    printf "%s Timeshift installation failed." "$RED_ERROR" >&2
     return "$E_INSTALLATION"
   fi
   printf "Timeshift %s installed.\n" "$(timeshift --version)"
