install-terminator: chanaged indentation tabs from 2 to 4 tabs; updated return codes

diff --git a/install-terminator b/install-terminator
--- a/install-terminator
+++ b/install-terminator
@@ -7,8 +7,8 @@
 # Author       : Copyright (C) 2020 Richard B. Romig, MosfaNet
 # Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
 # Created      : 14 Dec 2020
-# Updated      : 13 Aug 2026
-# Version      : 7.7.26225
+# Updated      : 08 Sep 2026
+# Version      : 7.8.26251
 # Comments     : By default, Terminator is configured as a login shell (Debian, Antix, MX Linux, LMDE)
 #              : Login shell is disabled for other distributions (Linux Mint)
 # TODO (Rick)  :
@@ -29,125 +29,126 @@
 source ~/bin/functionlib.bash || { printf "\e[91mERROR:\e[0m Unable to source functionlib.bash\n"; exit 1; }
 
 help() {
-  local -r script="$1"
-  local -r version="$2"
+	local -r script="$1"
+	local -r version="$2"
 	local -ri errcode="${3:-1}"
-	local -r updated="13 Aug 2026"
-	cat << _HELP_
-${orange}$script${normal} $version ($updated)
-Installs/Removes/Configures Terminator terminal emulator
+	local -r updated="08 Sep 2026"
+	cat <<- _HELP_
+	${orange}$script${normal} $version ($updated)
+	Installs/Removes/Configures Terminator terminal emulator
 
-${orange}Usage:${normal} $script [-chir]
-${green}OPTIONS:${normal}
-  -c  Apply configuration file.
-  -h  Show this help message and exit.
-  -i  Install Terminator & configuration files.
-  -r  Remove Terminator & configuration files.
-${bold}NOTES:${normal}
-  1. Script will not overwrite Terminator config for BunsenLabs installations. Configuration changes should be made through Terminator Preferences.
-  2. For Debian and Debian-based distributions (Antix, MX Linux, LMDE),Terminator will be configured as a login shell.
+	${orange}Usage:${normal} $script [-chir]
+	${green}OPTIONS:${normal}
+	-c	Apply configuration file.
+	-h	Show this help message and exit.
+	-i	Install Terminator & configuration files.
+	-r	Remove Terminator & configuration files.
+	${bold}NOTES:${normal}
+	1. Script will not overwrite Terminator config for BunsenLabs installations. Configuration changes should be made through Terminator Preferences.
+	2. For Debian and Debian-based distributions (Antix, MX Linux, LMDE),Terminator will be configured as a login shell.
 _HELP_
-  exit "$errcode"
+	exit "$errcode"
 }
 
 terminator_version() {
-  awk '/^ii/ {print $3}' < <(dpkg -l terminator) | sed 's/-.*//'
-  return 0
+	# terminator -- version requires an X environment. ssh -X remote-host
+	awk '/^ii/ {print $3}' < <(dpkg -l terminator) | sed 's/-.*//'
+	return 0
 }
 
 install_terminator() {
-  if installed terminator; then
-    printf "Terminator %s is installed.\n" "$(terminator_version)" >&2
-    return 1
-  fi
-  printf "Installing terminator...\n"
-  sudo_login 2
-  sudo apt-get -yq update
-  sudo apt-get install -y terminator
-  if ! installed terminator; then
-    printf "%s Terminator installation failed.\n" "$RED_ERROR" >&2
-    return "$E_INSTALLATION"
-  fi
-  printf "Terminator %s installed.\n" "$(terminator_version)"
-  return 0
+	if installed terminator; then
+		printf "Terminator %s is installed.\n" "$(terminator_version)" >&2
+		return "$E_FILE_EXISTS"
+	fi
+	printf "Installing terminator...\n"
+	sudo_login 2
+	sudo apt-get -yq update
+	sudo apt-get install -y terminator
+	if ! installed terminator; then
+		printf "%s Terminator installation failed.\n" "$RED_ERROR" >&2
+		return "$E_INSTALLATION"
+	fi
+	printf "Terminator %s installed.\n" "$(terminator_version)"
+	return 0
 }
 
 remove_terminator() {
-  if ! installed terminator; then
-    printf "Terminator is not installed.\n" >&2
-    return 1
-  fi
-  printf "Removing terminator %s and configuration files...\n" "$(terminator_version)"
-  sudo_login 2
-  sudo apt-get purge terminator
-  [[ -L ~/.config/terminator/config ]] && unlink ~/.config/terminator/config
-  find ~/.config -maxdepth 2 -type d -name terminator -exec rm -rf {} \;
-  find /usr/share -maxdepth 3 -type f,d -iname "terminator*" -exec sudo rm -rf {} \;
-  printf "Terminator and its configuration files have been removed.\n"
-  return 0
+	if ! installed terminator; then
+		printf "Terminator is not installed.\n" >&2
+		return "$E_NOT_INSTALLED"
+	fi
+	printf "Removing terminator %s and configuration files...\n" "$(terminator_version)"
+	sudo_login 2
+	sudo apt-get purge terminator
+	[[ -L ~/.config/terminator/config ]] && unlink ~/.config/terminator/config
+	find ~/.config -maxdepth 2 -type d -name terminator -exec rm -rf {} \;
+	find /usr/share -maxdepth 3 -type f,d -iname "terminator*" -exec sudo rm -rf {} \;
+	printf "Terminator and its configuration files have been removed.\n"
+	return 0
 }
 
 apply_config() {
-  if installed terminator; then
-    printf "Terminator %s is installed.\n" "$(terminator_version)" >&2
-    return 1
-  fi
-  if bunsenlabs; then
-    printf "BunsenLabs uses its own profiles based on the version of the distribution.\n"
-    printf "Configuration changes should be made through the Terminator Preferences menu.\n"
-    return 1
-  fi
-  local repository=~/Downloads/ccnfigs/
-  [[ -d ~/gitea/configs ]] && repository=~/gitea/configs
-  if ! [[ -d "$repository" ]]; then
-    printf "%s Repository not found!\n" "$RED_ERROR" >&2
-    return "$E_FILENOTFOUND"
-  fi
-  [[ -d /.config/terminator ]] && mkdir -p /.config/terminator
-  printf "Applying Terminator configuration...\n"
-  if is_debian; then
-    [[ -f ~/.config/terminator/config ]] && rm ~/.config/terminator/config
-    [[ -d ~/gitea/configs/terminator ]] && ln -s ~/gitea/configs/terminator/config ~/.config/terminator/config
-    [[ -d ~/Downloads/configs/terminator ]] && ln -sv ~/Downloads/configs/terminator/config ~/.config/terminator/config
-  else
-    cp -v "$repository"/terminator/config ~/.config/terminator/
-    sed -i '/login_shell/s/True/False/' ~/.config/terminator/config
-  fi
-  printf "Terminator %s configured.\n" "$(terminator_version)"
-  return 0
+	if ! installed terminator; then
+		printf "Terminator %s is installed.\n" "$(terminator_version)" >&2
+		return "$E_FILE_EXISTS"
+	fi
+	if bunsenlabs; then
+		printf "BunsenLabs uses its own profiles based on the version of the distribution.\n"
+		printf "Configuration changes should be made through the Terminator Preferences menu.\n"
+		return "$E_UNSUPPORTED"
+	fi
+	local repository=~/Downloads/ccnfigs/
+	[[ -d ~/gitea/configs ]] && repository=~/gitea/configs
+	if ! [[ -d "$repository" ]]; then
+		printf "%s Repository not found!\n" "$RED_ERROR" >&2
+		return "$E_FILENOTFOUND"
+	fi
+	[[ -d /.config/terminator ]] && mkdir -p /.config/terminator
+	printf "Applying Terminator configuration...\n"
+	if is_debian; then
+		[[ -f ~/.config/terminator/config ]] && rm ~/.config/terminator/config
+		[[ -d ~/gitea/configs/terminator ]] && ln -s ~/gitea/configs/terminator/config ~/.config/terminator/config
+		[[ -d ~/Downloads/configs/terminator ]] && ln -sv ~/Downloads/configs/terminator/config ~/.config/terminator/config
+	else
+		cp -v "$repository"/terminator/config ~/.config/terminator/
+		sed -i '/login_shell/s/True/False/' ~/.config/terminator/config
+	fi
+	printf "Terminator %s configured.\n" "$(terminator_version)"
+	return 0
 }
 
 main() {
-  local -r script="${0##*/}"
-  local -r version="7.7.26225"
-  local -i exit_code=0
-  local opt OPTARG OPTIND
-  local -i noOpt=1
-  local -r optstr=":chir"
-  while getopts "$optstr" opt; do
-    case "$opt" in
-      c )
-        apply_config ;;
-      h )
-        help "$script" "$version" 0 ;;
-      i )
-        install_terminator && apply_config ;;
-      r )
-        remove_terminator ;;
-      ? )
-      printf "%s Invalid option -%s\n" "$RED_ERROR" "$OPTARG" >&2
-      help "$script" "$version" "$E_INVALID_ARG"
-    esac
-    exit_code="$?"
-    noOpt=0
-  done
+	local -r script="${0##*/}"
+	local -r version="7.8.26251"
+	local -i exit_code=0
+	local -i noOpt=1
+	local -r optstr=":chir"
+	local opt OPTARG OPTIND
+	while getopts "$optstr" opt; do
+		case "$opt" in
+			c )
+				apply_config ;;
+			h )
+				help "$script" "$version" 0 ;;
+			i )
+				install_terminator && apply_config ;;
+			r )
+				remove_terminator ;;
+			? )
+				printf "%s Invalid option -%s\n" "$RED_ERROR" "$OPTARG" >&2
+				help "$script" "$version" "$E_INVALID_ARG"
+		esac
+		exit_code="$?"
+		noOpt=0
+	done
 	if (( noOpt == 1 )); then
 		printf "%s No argument passed.\n" "$RED_ERROR" >&2
 		help "$script" "$version" "$E_MISSING_ARG"
 	fi
-  shift "$(( OPTIND - 1 ))"
-  over_line "$script $version"
-  exit "$exit_code"
+	shift "$(( OPTIND - 1 ))"
+	over_line "$script $version"
+	exit "$exit_code"
 }
 
 main "$@"
