iru-marktext: updated help() and reorganized getopts loop.

diff --git a/iru-marktext b/iru-marktext
--- a/iru-marktext
+++ b/iru-marktext
@@ -2,12 +2,12 @@
 ##########################################################################
 # Script Name  : iru-marktext
 # Description  : Installs, updates, and removes the Mark Text markdown editor.
-# Dependencies : gdebi, wget
+# Dependencies : wget
 # Arguments    : [-h] [-i] [-r] [-u] (See help function)
 # Author       : Copyright (C) 2022, Richard B. Romig, Mosfanet
 # Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
 # Created      : 10 Jan 2022
-# Updated      : 19 Jun 2025
+# Updated      : 27 Jun 2025
 # Comments     :
 # TODO (Rick)  :
 # License      : GNU General Public License, version 2.0
@@ -28,27 +28,24 @@ fi
 ## Global Variables ##
 
 readonly script="${0##*/}"
-readonly version="4.13.25170"
+readonly version="4.14.25178"
 readonly gh_url="https://github.com/marktext/marktext/releases"
 
 ## Functions ##
 
 help() {
-  local errcode updated
-	errcode="${1:-2}"
-	updated="16 Jun 2025"
+	local errcode="${1:-2}"
+	local -r updated="27 Jun 2025"
 	cat << _HELP_
 ${orange}$script${normal} $version ($updated)
 Installs, configures, updates, removes the Mark Text markdown editor.
 
-${green}Usage:${normal} $script [OPTION]
-
+${green}Usage:${normal} $script [-h] [-i] [-r] [-u]
 ${orange}Available options:${normal}
-  -c  Applies Marktext preferences.
   -h  Show this help message and exit.
   -i  Installs the Marktext markdown editor.
   -r  Removes the Marktext markdown editor from the system.
-  -u  Updates the Marktext markdown editor to the latest version.
+  -u  Updates the Marktext markdown editor to the latest GitHub release.
 _HELP_
   exit "$errcode"
 }
@@ -58,11 +55,6 @@ _HELP_
 cleanup() {
   [[ -d "$tmp_dir" ]] && rm -rf "$tmp_dir"
   [[ -f "$tmp_file" ]] && rm -f "$tmp_file"
-}
-
-check_dependencies() {
-  local packages=( gdebi git wget )
-  check_packages "${packages[@]}"
 }
 
 marktext_version() {
@@ -89,9 +81,8 @@ compare_versions() {
 }
 
 install_marktext() {
-  local new_ver new_pkg
-  new_ver="$1"
-  new_pkg="marktext-amd64.deb"
+  local new_ver="$1"
+  local -r new_pkg="marktext-amd64.deb"
   printf "Downloading Mark Text markdown editor (v %s) from the marktext GitHub repository..." "$new_ver"
   dots "."
   wget -q -P "$tmp_dir/" "$gh_url/download/v$new_ver/$new_pkg"
@@ -103,7 +94,7 @@ install_marktext() {
 }
 
 remove_marktext() {
-  local cfg_dir="$1"
+  local -r cfg_dir="$HOME/.config"
   sudo_login 2
   printf "Removing the Mark Text markdown editor...\n"
   sudo apt-get remove --purge marktext -yy
@@ -114,7 +105,7 @@ remove_marktext() {
 
 marktext_config() {
   local repository cfg_dir
-  cfg_dir="$1"
+  cfg_dir="$HOME/.config"
 	repository=$(assign_cfg_repo)
   [[ -d "$cfg_dir" ]] || mkdir -p "$cfg_dir"
   printf "Applying MarkText preferences...\n"
@@ -124,43 +115,48 @@ marktext_config() {
 }
 
 main() {
-  local noOpt opt optstr new_ver cfg_dir
-  check_dependencies
+  local noOpt opt optstr new_ver
   cfg_dir="$HOME/.config/marktext"
+  check_package wget
   noOpt=1
   optstr=":chiru"
   while getopts "$optstr" opt; do
     case "$opt" in
-      c )
-        exists marktext || leave "Marktext is not installed."
-        marktext_config "$cfg_dir"
-      ;;
       h )
         help 0
-      ;;
+        ;;
       i )
-        exists marktext && leave "Marktext $(marktext_version) is already installed."
-        tmp_file=$(mktemp) || die "Failed to create temporary file." 1
-        tmp_dir=$(mktemp -d) || die "Failed to create temporary directory." 1
-        trap cleanup EXIT
-        new_ver="$(newest_version)"
-        printf "%sInstalling MarkText version %s...%s\n" "$lightyellow" "$new_ver" "$normal"
-        install_marktext "$new_ver"
-        marktext_config "$cfg_dir"
-      ;;
+        if exists marktext; then
+          printf "Marktext %s is already installed.\n" "$(marktext_version)" >&2
+        else
+          tmp_file=$(mktemp) || die "Failed to create temporary file." 1
+          tmp_dir=$(mktemp -d) || die "Failed to create temporary directory." 1
+          trap cleanup EXIT
+          new_ver="$(newest_version)"
+          printf "%sInstalling MarkText version %s...%s\n" "$lightyellow" "$new_ver" "$normal"
+          install_marktext "$new_ver"
+          marktext_config "$cfg_dir"
+        fi
+        ;;
       r )
-        exists marktext || leave "Marktext is not installed."
-        remove_marktext "$cfg_dir"
-      ;;
+        if exists marktext; then
+          remove_marktext "$cfg_dir"
+        else
+          printf "Marktext is not installed.\n" >&2
+        fi
+        ;;
       u )
-        exists marktext || leave "Marktext is not installed."
-        tmp_file=$(mktemp) || die "Failed to create temporary file." 1
-        tmp_dir=$(mktemp -d) || die "Failed to create temporary directory." 1
-        trap cleanup EXIT
-        new_ver="$(newest_version)"
-        [[ "$new_ver" ]] || die "No download available. Try again later." 1
-        compare_versions "$new_ver"
-      ;;
+        if exists marktext; then
+          tmp_file=$(mktemp) || die "Failed to create temporary file." 1
+          tmp_dir=$(mktemp -d) || die "Failed to create temporary directory." 1
+          trap cleanup EXIT
+          new_ver="$(newest_version)"
+          [[ "$new_ver" ]] || die "No download available. Try again later." 1
+          compare_versions "$new_ver"
+        else
+          printf "Marktext is not installed.\n" >&2
+        fi
+        ;;
       ? )
 				printf "%s Invalid option -%s\n" "$RED_ERROR" "$OPTARG" >&2
         help 2
