iru-fresh-editor: replaced convert_compare() with same function from functionlib.bash

diff --git a/iru-fresh-editor b/iru-fresh-editor
--- a/iru-fresh-editor
+++ b/iru-fresh-editor
@@ -2,13 +2,13 @@
 ##########################################################################
 # Script Name  : iru-fresh-editor
 # Description  : Installs, updates, and removes the Fresh Editor.
-# Dependencies : git, wget
+# Dependencies : wget
 # Arguments    : See the help function for details.
 # Author       : Copyright (C) 2025, Richard B. Romig, Mosfanet
 # Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
 # Created      : 25 Dec 2025
-# Updated      : 24 Aug 2026
-# Version      : 2.11.26236
+# Updated      : 08 Sep 2026
+# Version      : 2.12.26251
 # Comments     : Beginning with version 0.3.12, installs to /usr/bin/fresh
 # TODO (Rick)  :
 # License      : GNU General Public License, version 2.0
@@ -28,183 +28,155 @@
 source ~/bin/functionlib.bash || { printf "\e[91mERROR:\e[0m Unable to source functionlib.bash\n"; exit 1; }
 
 help() {
-  local -r script="$1"
-  local -r version="$2"
+	local -r script="$1"
+	local -r version="$2"
 	local -ri errcode="${3:-1}"
-	local -r updated="24 Aug 2026"
-	cat << _HELP_
-${orange}$script${normal} $version ($updated)
-Installs, updates, or removes the Fresh Editor.
+	local -r updated="08 Sep 2026"
+	cat <<- _HELP_
+	${orange}$script${normal} $version ($updated)
+	Installs, updates, or removes the Bat utililty.
 
-${green}Usage:${normal} $script [-hiru]
-${orange}Available options:${normal}
-  -h  Show this help message and exit
-  -i  Installs the Fresh Editor.
-  -r  Removes the Fresh Editor from the system.
-  -u  Updates the Fresh Editor to the latest GitHub release.
+	${green}Usage:${normal} $script [-hiru]
+	${orange}Available options:${normal}
+	-h	Show this help message and exit
+	-i	Installs the Fresh Editor.
+	-r	Removes the Fresh Editor from the system.
+	-u	Updates the Fresh Editor to the latest GitHub release.
 _HELP_
-  exit "$errcode"
-}
-
-check_dependencies() {
-  local packages=( git wget )
-  check_packages "${packages[@]}"
-  return 0
+	exit "$errcode"
 }
 
 fresh_version() {
-  cut -d' ' -f2 < <(fresh --version)
-  return 0
-}
-
-convert_compare() {
-  local -r newVer="$1"
-  local -r curVer="$2"
-  local -i newer="$FALSE"
-	local new_arr=()
-	local cur_arr=()
-  local -i index
-	IFS="." read -ra new_arr <<< "$newVer"
-	IFS="." read -ra cur_arr <<< "$curVer"
-	for (( index=0; index <=2; index++)) ; do
-    if (( "${new_arr[index]}" > "${cur_arr[index]}" )); then
-      newer="$TRUE"
-      break
-    fi
-	done
-	return "$newer"
+	cut -d' ' -f2 < <(fresh --version)
+	return 0
 }
 
 newest_version() {
-  local -r gh_url="$1"
+	local -r gh_url="$1"
 	local new_ver
-  wget -qO "$TMP_FILE" "$gh_url"
-  new_ver=$(sed 's/^v//' < <(awk -F'/' '/download/ && /x86/ {print $6;exit}' "$TMP_FILE"))
-  echo "$new_ver"
-  return 0
+	wget -qO "$TMP_FILE" "$gh_url"
+	new_ver=$(sed 's/^v//' < <(awk -F'/' '/download/ && /x86/ {print $6;exit}' "$TMP_FILE"))
+	echo "$new_ver"
+	return 0
 }
 
 compare_versions() {
 	local -r new_ver="$1"
-  local -r gh_url="$2"
-  local cur_ver
-  cur_ver="$(fresh_version)"
-  printf "Comparing current and newest versions...\n"
-  if [[ -z "$new_ver" ]]; then
-    printf "%s No download available. Try again later." "$RED_ERROR" >&2
-    return "$E_DOWNLOAD"
-  elif convert_compare "$new_ver" "$cur_ver"; then
-    printf "%sInstalled version of Fresh-editor is %s, updating to %s...%s\n" "$lightyellow" "$cur_ver" "$new_ver" "$normal"
-    install_fresh "$new_ver" "$gh_url"
-  else
-    printf "%sFresh-editor %s is the current version. No update required.%s\n" "$lightyellow" "$cur_ver" "$normal"
-  fi
-  return 0
+	local -r gh_url="$2"
+	local cur_ver
+	cur_ver="$(fresh_version)"
+	printf "Comparing current and newest versions...\n"
+	if [[ -z "$new_ver" ]]; then
+		printf "%s No download available. Try again later." "$RED_ERROR" >&2
+		return "$E_DOWNLOAD"
+	elif convert_compare "$new_ver" "$cur_ver"; then
+		printf "%sInstalled version of Fresh-editor is %s, updating to %s...%s\n" "$lightyellow" "$cur_ver" "$new_ver" "$normal"
+		install_fresh "$new_ver" "$gh_url"
+	else
+		printf "%sFresh-editor %s is the current version. No update required.%s\n" "$lightyellow" "$cur_ver" "$normal"
+	fi
+	return 0
 }
 
 install_fresh() {
 	local -r new_ver="$1"
 	local -r gh_url="$2"
-  local -r new_pkg="fresh-editor_${new_ver}-1_amd64.deb"
-  if [[ -z "$new_ver" ]]; then
-    printf "%s No download available. Try again later." "$RED_ERROR" >&2
-    return "$E_DOWNLOAD"
-  fi
-  printf "Downloading Fresh-editor %s from the sinelaw GitHub repository..." "$new_ver"
-  dots "." &
+	local -r new_pkg="fresh-editor_${new_ver}-1_amd64.deb"
+	if [[ -z "$new_ver" ]]; then
+		printf "%s No download available. Try again later." "$RED_ERROR" >&2
+		return "$E_DOWNLOAD"
+	fi
+	printf "Downloading Fresh-editor %s from the sinelaw GitHub repository..." "$new_ver"
+	dots "." &
 	DOTS_PID="$!"
-  wget -q -P "$TMP_DIR/" "$gh_url/download/v$new_ver/$new_pkg"
+	wget -q -P "$TMP_DIR/" "$gh_url/download/v$new_ver/$new_pkg"
 	kill_dots
-  printf "Installing Fresh-editor %s...\n" "$new_ver"
-  sudo_login 2
+	printf "Installing Fresh-editor %s...\n" "$new_ver"
+	sudo_login 2
 	sudo dpkg -i "$TMP_DIR/$new_pkg"; sudo apt-get install --fix-broken
-  if  [[ "$(fresh_version)" != "$new_ver" ]]; then
-    printf "%s Fresh-editor installation failed.\n" "$RED_ERROR" >&2
-    return "$E_INSTALLATION"
-  fi
-  printf "%sFresh-editor %s installed.%s\n" "$lightyellow" "$(fresh_version)" "$normal"
-  return 0
+	if  [[ "$(fresh_version)" != "$new_ver" ]]; then
+		printf "%s Fresh-editor installation failed.\n" "$RED_ERROR" >&2
+		return "$E_INSTALLATION"
+	fi
+	printf "%sFresh-editor %s installed.%s\n" "$lightyellow" "$(fresh_version)" "$normal"
+	return 0
 }
 
 remove_fresh() {
-  if ! installed fresh-editor; then
-    printf "Fresh-editor is not installed.\n" >&2
-    return "$E_NOT_DETECTED"
-  fi
-  sudo_login 2
-  printf "Removing Fresh-editor %s...\n" "$(fresh_version)"
-  sudo dpkg --remove fresh-editor
+	if ! installed fresh-editor; then
+		printf "Fresh-editor is not installed.\n" >&2
+		return "$E_NOT_DETECTED"
+	fi
+	sudo_login 2
+	printf "Removing Fresh-editor %s...\n" "$(fresh_version)"
+	sudo dpkg --remove fresh-editor
 	find ~/ -maxdepth 3 -type d -path "$HOME/Downloads" -prune -o -path "$HOME/gitea" -prune -o -type d -name fresh -exec rm -rf {} \;
-  find /usr/share -maxdepth 3 -type f,d -iname "fresh*" -exec rm -rf {} \;
-  printf "Fresh-editor and its configuration files have been removed.\n"
-  return 0
+	find /usr/share -maxdepth 3 -type f,d -iname "fresh*" -exec rm -rf {} \;
+	printf "Fresh-editor and its configuration files have been removed.\n"
+	return 0
 }
 
 fresh_config() {
-  local repository=~/Downloads/configs
-  [[ -d ~/gitea/configs ]] && repository=~/gitea/configs
-  if [[ ! -d "$repository" ]]; then
-    printf "%s Cloned repository not found!\n" "$RED_WARNING" >&2
-    return "$E_FILENOTFOUND"
-  fi
+	local repository=~/Downloads/configs
+	[[ -d ~/gitea/configs ]] && repository=~/gitea/configs
+	if [[ ! -d "$repository" ]]; then
+		printf "%s Cloned repository not found!\n" "$RED_WARNING" >&2
+		return "$E_FILENOTFOUND"
+	fi
 	[[ -d ~/.config/fresh ]] || mkdir -p ~/.config/fresh
-  printf "Applying Fresh-editor configuration...\n"
-  cp -v "$repository/fresh/config.json" ~/.config/fresh/
-  printf "Fresh-editor %s configuration applied.\n" "$(fresh_version)"
-  return 0
+	printf "Applying Fresh-editor configuration...\n"
+	cp -v "$repository/fresh/config.json" ~/.config/fresh/
+	printf "Fresh-editor %s configuration applied.\n" "$(fresh_version)"
+	return 0
 }
 
 main() {
-  local -r script="${0##*/}"
-  local -r version="2.10.26235"
+	local -r script="${0##*/}"
+	local -r version="2.12.26251"
 	local -i exit_code=0
-  local -r gh_url="https://github.com/sinelaw/fresh/releases"
-  local opt new_ver OPTARG OPTIND
-  local -i noOpt=1
-  local -r optstr=":hiru"
-  while getopts "$optstr" opt; do
-    case "$opt" in
-      h )
-        help "$script" "$version" 0
-        ;;
-      i )
-        if installed fresh-editor; then
-          printf "Fresh-editor %s is already installed.\n" "$(fresh_version)" >&2
-        else
-          check_dependencies
-          create_tmp "dirfile"
+	local -r gh_url="https://github.com/sinelaw/fresh/releases"
+	local -i noOpt=1
+	local -r optstr=":hiru"
+	local opt OPTARG OPTIND new_ver
+	while getopts "$optstr" opt; do
+		case "$opt" in
+			h )
+				help "$script" "$version" 0 ;;
+			i )
+				if installed fresh-editor; then
+					printf "Fresh-editor %s is already installed.\n" "$(fresh_version)" >&2
+				else
+					check_package wget
+					create_tmp "dirfile"
 					new_ver="$(newest_version "$gh_url")"
-          printf "%sInstalling Bat version %s...%s\n" "$lightyellow" "$new_ver" "$normal"
-          install_fresh "$new_ver" "$gh_url" && fresh_config
-        fi
-        ;;
-      r )
-        remove_fresh
-        ;;
-      u )
-        if installed fresh-editor; then
-          check_dependencies
-          create_tmp "dirfile"
-          new_ver="$(newest_version "$gh_url")"
-          compare_versions "$new_ver" "$gh_url"
-        else
-          printf "Fresh-editor is not installed.\n" >&2
-        fi
-        ;;
-      ? )
-        printf "%s Invalid option -%s\n" "$RED_ERROR" "$OPTARG" >&2
-        help "$script" "$version" "$E_INVALID_ARG"
-    esac
+					printf "%sInstalling Bat version %s...%s\n" "$lightyellow" "$new_ver" "$normal"
+					install_fresh "$new_ver" "$gh_url" && fresh_config
+				fi ;;
+			r )
+				remove_fresh ;;
+			u )
+				if installed fresh-editor; then
+					check_package wget
+					create_tmp "dirfile"
+					new_ver="$(newest_version "$gh_url")"
+					compare_versions "$new_ver" "$gh_url"
+				else
+					printf "Fresh-editor is not installed.\n" >&2
+				fi ;;
+			? )
+				printf "%s Invalid option -%s\n" "$RED_ERROR" "$OPTARG" >&2
+				help "$script" "$version" "$E_INVALID_ARG"
+		esac
 		exit_code="$?"
-	  noOpt=0
-  done
+		noOpt=0
+	done
 	if (( noOpt == 1 )); then
 		printf "%s No argument passed.\n" "$RED_ERROR" >&2
 		help "$script" "$version" "$E_MISSING_ARG"
 	fi
-  shift "$(( OPTIND - 1 ))"
+	shift "$(( OPTIND - 1 ))"
 	over_line "$script $version"
-  exit "$exit_code"
+	exit "$exit_code"
 }
 
 main "$@"
