Replaced if-else for getopts witn noOpt flag variable. Displays help function if no argument passed.

diff --git a/iru-bat b/iru-bat
--- a/iru-bat
+++ b/iru-bat
@@ -27,8 +27,8 @@ fi
 ## Variables ##
 
 _script=$(basename "$0"); readonly _script
-readonly _version="0.4.7"
-readonly _updated="21 Mar 2023"
+readonly _version="0.4.8"
+readonly _updated="29 Mar 2023"
 readonly url="https://github.com/sharkdp/bat/releases"
 readonly bat_cfg=$HOME"/.config/bat"
 
@@ -148,49 +148,49 @@ EOF
 
 printf "\U1F427 %s v%s (%s)\n" "$_script" "$_version" "$_updated"
 printf "Installs, updates, or removes the Bat utililty.\n"
-check_dependencies
 
-if [[ $# -eq 0 ]]; then
-  echo "${lightred}ERROR:${normal} No argument passed." >&2
-  help 2
-else
-  optstr=":chiru"
-  while getopts "$optstr" opt; do
-    case "$opt" in
-      c )
-        exists bat || leave "Bat is not installed. Run '$_script -i' to install."
-        apply_config
-        ;;
-      h )
-        help 0
-        ;;
-      i )
-        exists bat && leave "Bat $(bat_ver) is already installed."
-        tmp_file=$(mktemp) || die "Failed to create temporary file." 1
-        tmp_dir=$(mktemp -d) || die "Failed to create temporary directory." 1
-        trap cleanup EXIT
-        new_ver="$(newest_version)"
-        echo "${lightyellow}Installing Bat version $new_ver...${normal}"
-        check_distro || echo "Bat $new_ver is the latest version compatible with $(get_distribution)."
-        install_bat
-        apply_config
-        ;;
-      r )
-        exists bat || leave "Bat is not installed. Run '$_script -i' to install."
-        remove_bat
-        ;;
-      u )
-        exists bat || leave "Bat is not installed. Run '$_script -i' to install."
-        tmp_file=$(mktemp) || die "Failed to create temporary file." 1
-        tmp_dir=$(mktemp -d) || die "Failed to create temporary directory." 1
-        trap cleanup EXIT
-        new_ver="$(newest_version)"
-        compare_versions
-        ;;
-      ? )
-        echo "${lightred}ERROR:${normal}Invalid option -${OPTARG}" >&2
-        help 2
-        ;;
-    esac
-  done
-fi
+noOpt=1
+optstr=":chiru"
+while getopts "$optstr" opt; do
+  case "$opt" in
+    c )
+      exists bat || leave "Bat is not installed. Run '$_script -i' to install."
+      apply_config
+      ;;
+    h )
+      help 0
+      ;;
+    i )
+      exists bat && leave "Bat $(bat_ver) is already installed."
+      tmp_file=$(mktemp) || die "Failed to create temporary file." 1
+      tmp_dir=$(mktemp -d) || die "Failed to create temporary directory." 1
+      trap cleanup EXIT
+      check_dependencies
+      new_ver="$(newest_version)"
+      echo "${lightyellow}Installing Bat version $new_ver...${normal}"
+      check_distro || echo "Bat $new_ver is the latest version compatible with $(get_distribution)."
+      install_bat
+      apply_config
+      ;;
+    r )
+      exists bat || leave "Bat is not installed. Run '$_script -i' to install."
+      remove_bat
+      ;;
+    u )
+      exists bat || leave "Bat is not installed. Run '$_script -i' to install."
+      tmp_file=$(mktemp) || die "Failed to create temporary file." 1
+      tmp_dir=$(mktemp -d) || die "Failed to create temporary directory." 1
+      trap cleanup EXIT
+      check_dependencies
+      new_ver="$(newest_version)"
+      compare_versions
+      ;;
+    ? )
+      echo "${lightred}ERROR:${normal}Invalid option -${OPTARG}" >&2
+      help 2
+      ;;
+  esac
+	noOpt=0
+done
+if [ $noOpt = 1 ];then printf "%s No argument passed.\n" "$red_error" >&2;help 1;fi
+
diff --git a/iru-marktext b/iru-marktext
--- a/iru-marktext
+++ b/iru-marktext
@@ -27,8 +27,8 @@ fi
 ## Variables ##
 
 _script=$(basename "$0"); readonly _script
-readonly _version="0.3.6"
-readonly _updated="21 Mar 2023"
+readonly _version="0.3.7"
+readonly _updated="29 Mar 2023"
 readonly url="https://github.com/marktext/marktext/releases"
 
 ## Functions ##
@@ -100,46 +100,44 @@ EOF
 
 ## Execution ##
 
-check_dependencies
-printf "\U1F427 %s v%s (%s)\n" "$_script" "$_version" "$_updated"
+printf "%s v%s (%s)\n" "$_script" "$_version" "$_updated"
 printf "Installs, updates, or removes the Mark Text markdown editor.\n"
 
-if [[ $# -eq 0 ]]; then
-  echo "${lightred}ERROR:${normal} No argument passed." >&2
-  help 2
-else
-  optstr=":hiru"
-  while getopts "$optstr" opt; do
-    case "$opt" in
-      h )
-        help 0 ;;
-      i )
-        exists marktext && leave "Marktext $(marktext_version) is already installed."
-        tmp_file=$(mktemp) || die "Failed to create temporary file." 1
-        tmp_dir=$(mktemp -d) || die "Failed to create temporary directory." 1
-        trap cleanup EXIT
-        new_ver="$(newest_version)"
-        echo "${lightyellow}Installing MarkText version $new_ver...${normal}"  
-        install_marktext
-        ;;
-      r )
-        exists marktext || leave "Marktext is not installed. Run '$_script -i' to install."
-        remove_marktext
-        ;;
-      u )
-        exists marktext || leave "Marktext is not installed. Run '$_script -i' to install."
-        tmp_file=$(mktemp) || die "Failed to create temporary file." 1
-        tmp_dir=$(mktemp -d) || die "Failed to create temporary directory." 1
-        trap cleanup EXIT
-        new_ver="$(newest_version)"
-        compare_versions
-        ;;
-      ? )
-        echo "${lightred}ERROR:${normal} Invalid option -${OPTARG}" >&2
-        help 2
-        ;;
-    esac
-  done
-fi
-
+noOpt=1
+optstr=":hiru"
+while getopts "$optstr" opt; do
+  case "$opt" in
+    h )
+      help 0 ;;
+    i )
+      exists marktext && leave "Marktext $(marktext_version) is already installed."
+      tmp_file=$(mktemp) || die "Failed to create temporary file." 1
+      tmp_dir=$(mktemp -d) || die "Failed to create temporary directory." 1
+      trap cleanup EXIT
+      check_dependencies
+      new_ver="$(newest_version)"
+      echo "${lightyellow}Installing MarkText version $new_ver...${normal}"  
+      install_marktext
+      ;;
+    r )
+      exists marktext || leave "Marktext is not installed. Run '$_script -i' to install."
+      remove_marktext
+      ;;
+    u )
+      exists marktext || leave "Marktext is not installed. Run '$_script -i' to install."
+      tmp_file=$(mktemp) || die "Failed to create temporary file." 1
+      tmp_dir=$(mktemp -d) || die "Failed to create temporary directory." 1
+      trap cleanup EXIT
+      check_dependencies
+      new_ver="$(newest_version)"
+      compare_versions
+      ;;
+    ? )
+      echo "${lightred}ERROR:${normal} Invalid option -${OPTARG}" >&2
+      help 2
+      ;;
+  esac
+	noOpt=0
+done
+if [ $noOpt = 1 ];then printf "%s No argument passed.\n" "$red_error" >&2;help 1;fi
 exit
diff --git a/iru-micro b/iru-micro
--- a/iru-micro
+++ b/iru-micro
@@ -27,8 +27,8 @@ fi
 ## Variables ##
 
 _script=$(basename "$0"); readonly _script
-readonly _version="0.4.7"
-readonly _updated="21 Mar 2023"
+readonly _version="0.4.8"
+readonly _updated="29 Mar 2023"
 readonly url="https://github.com/zyedidia/micro/releases"
 readonly micro_cfg=$HOME"/.config/micro"
 
@@ -139,58 +139,55 @@ EOF
 
 ## Execution ##
 
-printf "\U1F427 %s v%s (%s)\n" "$_script" "$_version" "$_updated"
+printf "\%s v%s (%s)\n" "$_script" "$_version" "$_updated"
 printf "Installs, updates, or removes the Micro CLI text editor.\n"
-check_dependencies
 
-if [[ $# -eq 0 ]]; then
-  echo "${lightred}ERROR:${normal} No argument passed." >&2
-  help 2
-else
-  optstr=":bhirsu"
-  while getopts "$optstr" opt; do
-    case "$opt" in
-      b )
-        exists micro || leave "Micro is not installed. Run '$_script -i' to install."
-        apply_bindings
-        ;;
-      h )
-        help 0
-        ;;
-      i )
-        exists micro && leave "Micro $(micro_ver) is already installed."
-        tmp_file=$(mktemp) || die "Failed to create temporary file." 1
-        tmp_dir=$(mktemp -d) || die "Failed to create temporary directory." 1
-        trap cleanup EXIT
-        new_ver="$(newest_version)"
-        echo "${lightyellow}Installing Micro version $new_ver...${normal}"
-        install_micro
-        apply_settings
-        apply_bindings
-        ;;
-      r )
-        exists micro || leave "Micro is not installed. Run '$_script -i' to install."
-        remove_micro
-        ;;
-      s )
-        exists micro || leave "Micro is not installed. Run '$_script -i' to install."
-        apply_settings
-        ;;
-      u )
-        exists micro || leave "Micro is not installed. Run '$_script -i' to install."
-        tmp_file=$(mktemp) || die "Failed to create temporary file." 1
-        tmp_dir=$(mktemp -d) || die "Failed to create temporary directory." 1
-        trap cleanup EXIT
-        new_ver="$(newest_version)"
-        compare_versions
-        ;;
-      ? )
-        echo "${lightred}ERROR:${normal} Invalid option -${OPTARG}" >&2
-        echo "${lightred}Invalid option.${normal}" >&2
-        help 2
-        ;;
-    esac
-  done
-fi
-
+noOpt=1
+optstr=":bhirsu"
+while getopts "$optstr" opt; do
+  case "$opt" in
+    b )
+      exists micro || leave "Micro is not installed. Run '$_script -i' to install."
+      apply_bindings
+      ;;
+    h )
+      help 0
+      ;;
+    i )
+      exists micro && leave "Micro $(micro_ver) is already installed."
+      tmp_file=$(mktemp) || die "Failed to create temporary file." 1
+      tmp_dir=$(mktemp -d) || die "Failed to create temporary directory." 1
+      trap cleanup EXIT
+      check_dependencies
+      new_ver="$(newest_version)"
+      echo "${lightyellow}Installing Micro version $new_ver...${normal}"
+      install_micro
+      apply_settings
+      apply_bindings
+      ;;
+    r )
+      exists micro || leave "Micro is not installed. Run '$_script -i' to install."
+      remove_micro
+      ;;
+    s )
+      exists micro || leave "Micro is not installed. Run '$_script -i' to install."
+      apply_settings
+      ;;
+    u )
+      exists micro || leave "Micro is not installed. Run '$_script -i' to install."
+      tmp_file=$(mktemp) || die "Failed to create temporary file." 1
+      tmp_dir=$(mktemp -d) || die "Failed to create temporary directory." 1
+      trap cleanup EXIT
+      check_dependencies
+      new_ver="$(newest_version)"
+      compare_versions
+      ;;
+    ? )
+      echo "${lightred}ERROR:${normal} Invalid option -${OPTARG}" >&2
+      help 2
+      ;;
+  esac
+  noOpt=0
+done
+if [ $noOpt = 1 ];then printf "%s No argument passed.\n" "$red_error" >&2;help 1;fi
 exit
diff --git a/iru-vscodium b/iru-vscodium
--- a/iru-vscodium
+++ b/iru-vscodium
@@ -27,8 +27,8 @@ fi
 ## Variables ##
 
 _script=$(basename "$0"); readonly _script
-readonly _version="0.2.4"
-readonly _updated="21 Mar 2023"
+readonly _version="0.2.5"
+readonly _updated="29 Mar 2023"
 readonly url="https://github.com/VSCodium/vscodium/releases"
 
 ## Functions ##
@@ -136,51 +136,49 @@ EOF
 
 ## Execution ##
 
-printf "\U1F427 %s v%s (%s)\n" "$_script" "$_version" "$_updated"
+printf "%s v%s (%s)\n" "$_script" "$_version" "$_updated"
 printf "Installs, updates, or removes the VSCodium editor.\n"
-check_dependencies
 
-if [[ "$#" -eq 0 ]]; then
-  printf "%s No argument passed.\n" "$red_error" >&2
-	help 2
-else
-	optstr=":hirsu"
-	while getopts "$optstr" opt; do
-		case "$opt" in
-			h )
-				help 0 ;;
-			i )
-				exists codium && leave "VSCodium $(codium_ver) is already installed."
-        tmp_file=$(mktemp) || die "Failed to create temporary file." 1
-				tmp_dir=$(mktemp -d) || die "Failed to create temporary directory." 1
-				trap cleanup EXIT
-				new_ver="$(newest_version)"
-        echo "${lightyellow}Installing VSCodium $new_ver...${normal}"
-				install_vscodium
-        apply_settings
-        ;;
-			r )
-        exists codium || leave "VSCodium is not installed."
-        remove_vscodium
-        ;;
-			s )
-        exists codium || leave "VSCodium is not installed."
-        apply_settings
-        ;;
-			u )
-        exists codium || leave "VSCodium is not installed."
-				tmp_file=$(mktemp -q) || die "Failed to create temporary file." 1
-				tmp_dir=$(mktemp -d) || die "Failed to create temporary directory." 1
-				trap cleanup EXIT
-				new_ver="$(newest_version)"
-				compare_versions
-        ;;
-			? )
-        printf "%s Invalid option -%s\n" "$red_error" "$OPTARG" >&2
-				help 2
-        ;;
-		esac
-	done
-fi
-
+noOpt=1
+optstr=":hirsu"
+while getopts "$optstr" opt; do
+	case "$opt" in
+		h )
+			help 0 ;;
+		i )
+			exists codium && leave "VSCodium $(codium_ver) is already installed."
+      check_dependencies
+      tmp_file=$(mktemp) || die "Failed to create temporary file." 1
+			tmp_dir=$(mktemp -d) || die "Failed to create temporary directory." 1
+			trap cleanup EXIT
+			new_ver="$(newest_version)"
+      echo "${lightyellow}Installing VSCodium $new_ver...${normal}"
+			install_vscodium
+      apply_settings
+      ;;
+		r )
+      exists codium || leave "VSCodium is not installed."
+      remove_vscodium
+      ;;
+		s )
+      exists codium || leave "VSCodium is not installed."
+      apply_settings
+      ;;
+		u )
+      exists codium || leave "VSCodium is not installed."
+      check_dependencies
+			tmp_file=$(mktemp -q) || die "Failed to create temporary file." 1
+			tmp_dir=$(mktemp -d) || die "Failed to create temporary directory." 1
+			trap cleanup EXIT
+			new_ver="$(newest_version)"
+			compare_versions
+      ;;
+		? )
+      printf "%s Invalid option -%s\n" "$red_error" "$OPTARG" >&2
+			help 2
+      ;;
+	esac
+	noOpt=0
+done
+if [ $noOpt = 1 ];then printf "%s No argument passed.\n" "$red_error" >&2;help 1;fi
 exit
diff --git a/iru-youtube-dl b/iru-youtube-dl
--- a/iru-youtube-dl
+++ b/iru-youtube-dl
@@ -28,8 +28,8 @@ fi
 ## Global Variables ##
 
 _script=$(basename "$0"); readonly _script
-readonly _version="0.1.4"
-readonly _updated="21 Mar 2023"
+readonly _version="0.1.5"
+readonly _updated="29 Mar 2023"
 readonly conf_dir="$HOME/.config/scripts"
 readonly conf_file="$_script.conf"
 
@@ -155,7 +155,7 @@ ${orange}OPTIONS:${normal}
 	-u 	Update youtube-dl
 	-x	Remove youtube-dl (repo version)
 END_HELP
-	printf "\U1F427 %s v%s (%s)\n" "$_script" "$_version" "$_updated"
+	printf "%s v%s (%s)\n" "$_script" "$_version" "$_updated"
   exit "$errcode"
 }
 
@@ -184,52 +184,50 @@ EOF
 [[ -f "$conf_dir/$conf_file" ]] || create_conf
 source "$conf_dir/$conf_file"
 
-if [[ "$#" -eq 0 ]]; then
-	printf "%s No argument passed.\n" "$red_error"  >&2
-	help 1
-else
-	optstr=":hirux"
-	while getopts "$optstr" opt; do
-		case "$opt" in
-			h )
-				help 0
-				;;
-			i )
-				[[ -f "$ytdl_location/$ytdl_prg" ]] && leave "$ytdl_prg $(ytdl_version) already installed."
-				user_in_sudo
-				check_dependencies
-				install_intro
-				dpkg -l | grep -qw youtube-dl && remove_repo_ver
-				install_youtubedl
-				break
-				;;
-			r )
-				remove_intro
-				dpkg -l | grep -qw youtube-dl && remove_repo_ver
-				[[ -f "$ytdl_location/$ytdl_prg" ]] || leave "$ytdl_prg $(ytdl_version) is not installed."
-				user_in_sudo
-				remove_youtubedl
-				break
-				;;
-			u )
-				[[ -f "$ytdl_location/$ytdl_prg" ]] || leave "$ytdl_prg $(ytdl_version) is not installed."
-				user_in_sudo
-				update_youtubedl
-				break
-				;;
-			x )
-				dpkg -l | grep -qw youtube-dl || leave "The repo version of $ytdl_prg is not installed."
-				printf "Removing %s installed from the distribution repository.\n" "$ytdl_prg"
-				user_in_sudo
-				remove_repo_ver
-				break
-				;;
-			? )
-				printf "%s Invalid option -%s\n" "$red_error" "$OPTARG" >&2
-				help 2
-				;;
-		esac
-	done
-fi
-printf "\U1F427 %s v%s (%s)\n" "$_script" "$_version" "$_updated"
+noOpt=1
+optstr=":hirux"
+while getopts "$optstr" opt; do
+	case "$opt" in
+		h )
+			help 0
+			;;
+		i )
+			[[ -f "$ytdl_location/$ytdl_prg" ]] && leave "$ytdl_prg $(ytdl_version) already installed."
+			user_in_sudo
+			check_dependencies
+			install_intro
+			dpkg -l | grep -qw youtube-dl && remove_repo_ver
+			install_youtubedl
+			break
+			;;
+		r )
+			remove_intro
+			dpkg -l | grep -qw youtube-dl && remove_repo_ver
+			[[ -f "$ytdl_location/$ytdl_prg" ]] || leave "$ytdl_prg $(ytdl_version) is not installed."
+			user_in_sudo
+			remove_youtubedl
+			break
+			;;
+		u )
+			[[ -f "$ytdl_location/$ytdl_prg" ]] || leave "$ytdl_prg $(ytdl_version) is not installed."
+			user_in_sudo
+			update_youtubedl
+			break
+			;;
+		x )
+			dpkg -l | grep -qw youtube-dl || leave "The repo version of $ytdl_prg is not installed."
+			printf "Removing %s installed from the distribution repository.\n" "$ytdl_prg"
+			user_in_sudo
+			remove_repo_ver
+			break
+			;;
+		? )
+			printf "%s Invalid option -%s\n" "$red_error" "$OPTARG" >&2
+			help 2
+			;;
+	esac
+	noOpt=0
+done
+if [ $noOpt = 1 ];then printf "%s No argument passed.\n" "$red_error" >&2;help 1;fi
+printf "%s v%s (%s)\n" "$_script" "$_version" "$_updated"
 exit
diff --git a/laptop-utils b/laptop-utils
--- a/laptop-utils
+++ b/laptop-utils
@@ -26,8 +26,8 @@ fi
 ## Global Variables ##
 
 _script=$(basename "$0"); readonly _script
-readonly _version="1.5.0"
-readonly _updated="23 Mar 2023"
+readonly _version="1.5.2"
+readonly _updated="29 Mar 2023"
 
 
 ## Funtions ##
@@ -148,26 +148,24 @@ util_status() {
 ## Execution ##
 
 is_laptop || die "System is not a laptop." 1
-if [[ "$#" -eq 0 ]]; then
-  printf "%s No argument passed.\n" "$red_error" >&2
-  help 1
-else
-  optstr=":his"
-  while getopts "$optstr" opt; do
-    case "$opt" in
-      h )
-        help 0 ;;
-      i )
-        intro
-        main ;;
-      s )
-        intro
-        util_status ;;
-      ? )
-        printf "%s Invalid option -%s\n" "$red_error" "$OPTARG" >&2
-        help 2
-    esac
-  done
-fi
+noOpt=1
+optstr=":his"
+while getopts "$optstr" opt; do
+  case "$opt" in
+    h )
+      help 0 ;;
+    i )
+      intro
+      main ;;
+    s )
+      intro
+      util_status ;;
+    ? )
+      printf "%s Invalid option -%s\n" "$red_error" "$OPTARG" >&2
+      help 2
+  esac
+	noOpt=0
+done
+if [ $noOpt = 1 ];then printf "%s No argument passed.\n" "$red_error" >&2;help 1;fi
 printf "%s v%s (%s)\n" "$_script" "$_version" "$_updated"
 exit
