iru-micro: updated help() and main(); reorganized getopts loop.

diff --git a/iru-micro b/iru-micro
--- a/iru-micro
+++ b/iru-micro
@@ -3,11 +3,11 @@
 # Script Name  : iru-micro
 # Description  : Installs, updates, and removes the Micro CLI text editor.
 # Dependencies : curl wget
-# Arguments    : [-b] [-h] [-i] [-r] [-s] [-u] (See help function)
+# Arguments    : [-h] [-i] [-r]] [-u] (See help function)
 # Author       : Copyright (C) 2022, Richard B. Romig, Mosfanet
 # Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
 # Created      : 10 Jan 2022
-# Updated      : 04 Jun 2025
+# Updated      : 27 Jun 2025
 # Comments     :
 # TODO (Rick)  :
 # License      : GNU General Public License, version 2.0
@@ -30,26 +30,25 @@ set -eu
 ## Global Variables ##
 
 readonly script="${0##*/}"
-readonly version="6.7.25155"
+readonly version="6.8.25178"
 readonly gh_url="https://github.com/zyedidia/micro/releases"
 
 ## Functions ##
 
 help() {
-  local errcode updated
-	errcode="${1:-2}"
-	updated="04 Apr 2025"
+	local errcode="${1:-2}"
+	local -r updated="27 Jun 2025"
 	cat << _HELP_
 ${orange}$script${normal} $version ($updated)
 Installs, configures, updates, or removes the Micro CLI text editor.
 
-${green}Usage:${normal} $script [OPTION]
+${green}Usage:${normal} $script [-h] [-i] [-r] [-u]
 
 ${orange}Available options:${normal}
   -h  Show this help message and exit.
   -i  Installs the Micro CLI text editor.
   -r  Removes the Micro CLI text editor from the system.
-  -u  Updates the Micro CLI text editor to the latest version.
+  -u  Updates the Micro CLI text editor to the latest GitHub release.
 _HELP_
   exit "$errcode"
 }
@@ -61,22 +60,14 @@ cleanup() {
   [[ -f "$tmp_file" ]] && rm -f "$tmp_file"
 }
 
-check_dependencies() {
-  local packages=( git wget )
-  check_packages "${packages[@]}"
-}
-
 micro_version() {
   micro -version | awk '/Version/ {print $NF}'
 }
 
 newest_version() {
+  check_package wget
   wget -qO "$tmp_file" "$gh_url"
-  if check_distro; then
-    new_ver=$(sed 's/\// /g' "$tmp_file" | grep -Ev 'beta|-rc' | awk '/download/ && /linux/ {print $7;exit}' | sed 's/^v//')
-  else
-    new_ver="2.0.13"
-  fi
+  new_ver=$(sed 's/\// /g' "$tmp_file" | grep -Ev 'beta|-rc' | awk '/download/ && /linux/ {print $7;exit}' | sed 's/^v//')
   echo "$new_ver"
 }
 
@@ -93,6 +84,8 @@ compare_versions() {
 
 install_micro() {
   local new_pkg="micro-${new_ver}-linux64.tar.gz"
+  sudo_login 2
+  check_package wget
   printf "Downloading Micro %s from the zyedidia GitHub repository..." "$new_ver"
   dots "."
   wget -q -P "$tmp_dir/" "$gh_url/download/v$new_ver/$new_pkg"
@@ -107,8 +100,9 @@ install_micro() {
 
 remove_micro() {
   local cur_ver cfg_d
-  cfg_d="$1"
+  cfg_d="$HOME/.config/micro"
   cur_ver=$(micro_version)
+  sudo_login 2
   printf "Removing the Micro CLI text editor...\n"
   sudo dpkg --remove micro
   [[ -L "$cfg_d/settings.json" ]] && unlink "$cfg_d/settings.json"
@@ -119,7 +113,7 @@ remove_micro() {
 
 micro_configs() {
   local repository cfg_d
-  cfg_d="$1"
+  cfg_d="$HOME/.config/micro"
 	repository=$(assign_cfg_repo)
   [[ -d "$cfg_d" ]] || mkdir -p "$cfg_d"
   printf "Applying Micro settings and bindings...\n"
@@ -132,41 +126,45 @@ micro_configs() {
 
 main() {
   local noOpt opt optstr new_ver cfg_d
-  cfg_d="$HOME/.config/micro"
-  check_dependencies
   noOpt=1
   optstr=":hiru"
   while getopts "$optstr" opt; do
     case "$opt" in
       h )
         help 0
-      ;;
+        ;;
       i )
-        exists micro && leave "Micro $(micro_version) is already installed."
-        tmp_file=$(mktemp) || die "Failed to create temporary file." 1
-        tmp_dir=$(mktemp -d) || die "Failed to create temporary directory." 1
-        trap cleanup EXIT
-        sudo_login 2
-        new_ver="$(newest_version)"
-        printf "%sInstalling Micro version %s...%s\n" "$lightyellow" "$new_ver" "$normal"
-        install_micro
-        micro_configs "$cfg_d"
-      ;;
+        if  exists micro; then
+          printf "Micro %s is already installed.\n" "$(micro_version)" >&2
+        else
+          tmp_file=$(mktemp) || die "Failed to create temporary file." 1
+          tmp_dir=$(mktemp -d) || die "Failed to create temporary directory." 1
+          trap cleanup EXIT
+          new_ver="$(newest_version)"
+          printf "%sInstalling Micro version %s...%s\n" "$lightyellow" "$new_ver" "$normal"
+          install_micro
+          micro_configs
+        fi
+        ;;
       r )
-        exists micro || leave "Micro is not installed."
-        sudo_login 2
-        remove_micro "$cfg_d"
-      ;;
+        if  exists micro; then
+          remove_micro
+        else
+          printf "Micro is not installed.\n" >&2
+        fi
+        ;;
       u )
-        exists micro || leave "Micro is not installed."
-        tmp_file=$(mktemp) || die "Failed to create temporary file." 1
-        tmp_dir=$(mktemp -d) || die "Failed to create temporary directory." 1
-        trap cleanup EXIT
-        sudo_login 2
-        new_ver="$(newest_version)"
-        [[ "$new_ver" ]] || die "No download available. Try again later." 1
-        compare_versions
-      ;;
+        if  exists micro; then
+          tmp_file=$(mktemp) || die "Failed to create temporary file." 1
+          tmp_dir=$(mktemp -d) || die "Failed to create temporary directory." 1
+          trap cleanup EXIT
+          new_ver="$(newest_version)"
+          [[ "$new_ver" ]] || die "No download available. Try again later." 1
+          compare_versions
+        else
+          printf "Micro is not installed.\n" >&2
+        fi
+        ;;
       ? )
 				printf "%s Invalid option -%s\n" "$RED_ERROR" "$OPTARG" >&2
         help 2
@@ -175,7 +173,7 @@ main() {
   done
   [[ "$noOpt" = 1 ]] && { printf "%s No argument passed.\n" "$RED_ERROR" >&2; help 1; }
   shift "$(( OPTIND - 1 ))"
-  over_line "$script v$version"
+  over_line "$script $version"
   exit
 }
 
