iru-bat: updated bat_config() and remove_bat() to support symlinks.

diff --git a/iru-bat b/iru-bat
--- a/iru-bat
+++ b/iru-bat
@@ -7,8 +7,10 @@
 # Author       : Copyright (C) 2022, Richard B. Romig, Mosfanet
 # Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
 # Created      : 09 Jan 2022
-# Updated      : 03 Jun 2025
+# Updated      : 04 Jun 2025
 # Comments     : Use install-batcat if distro version equals latest GitHub release.
+#              : Mint 22 installs version 0.24.0 with the Ubuntu version appended.
+#              : Debian 13 installs version 0.25.0 with the Debian version appended.
 # TODO (Rick)  :
 # License      : GNU General Public License, version 2.0
 ##########################################################################
@@ -30,98 +32,15 @@ set -eu
 ## Global Variables ##
 
 script=$(basename "$0"); readonly script
-readonly version="5.15.25154"
+readonly version="6.0.25155"
 readonly gh_url="https://github.com/sharkdp/bat/releases"
-readonly cfg_d=$HOME"/.config/bat"
 
 ## Functions ##
-
-# shellcheck disable=SC2317 # Don't warn about unreachable commands in this function
-# ShellCheck may incorrectly believe that code is unreachable if it's invoked by variable name or in a trap.
-cleanup() {
-  [[ -d "$tmp_dir" ]] && rm -rf "$tmp_dir"
-  [[ -f "$tmp_file" ]] && rm -f "$tmp_file"
-}
-
-check_dependencies() {
-  local packages=( gdebi git wget )
-  check_packages "${packages[@]}"
-}
-
-check_distro() {
-  local codename
-  codename=$(lsb_release -c -s)
-  case "$codename" in
-    bookworm|trixie|bullseye|faye|jammy|noble|wilma|xia ) return "$TRUE" ;;
-    * ) return "$FALSE" ;;
-  esac
-}
-
-bat_version() {
-  bat --version | cut -d' ' -f2
-}
-
-newest_version() {
-  wget -qO "$tmp_file" "$gh_url"
-  new_ver=$(sed 's/\// /g' "$tmp_file" | grep -Ev 'beta|-rc' | awk '/download/ && /amd64.deb/ {print $7;exit}' | sed 's/^v//')
-  check_distro || new_ver="0.19.0"
-  echo "$new_ver"
-}
-
-compare_versions() {
-  local cur_ver
-  cur_ver="$(bat_version)"
-  if [[ "$cur_ver" == "$new_ver" ]]; then
-    echo "${lightyellow}Bat $cur_ver is the current version. No update required.${normal}"
-    check_distro || echo "Bat $new_ver is the latest version compatible with $(get_distribution)."
-  else
-    echo "${lightyellow}Installed version of Bat is $cur_ver, updating to $new_ver...${normal}"
-    check_distro || echo "Bat $new_ver is the latest version compatible with $(get_distribution)."
-    install_bat
-  fi
-}
-
-install_bat() {
-  local new_pkg="bat_${new_ver}_amd64.deb"
-  sudo_login 2
-  printf "Downloading Bat %s from the sharkdp GitHub repository..." "$new_ver"
-  dots "."
-  wget -q -P "$tmp_dir/" "$gh_url/download/v$new_ver/$new_pkg"
-  kill "$!"; tput cnorm
-  printf "done\nInstalling Bat %s...\n" "$new_ver"
-  # sudo gdebi -n "$tmp_dir/$new_pkg" 2>/dev/null
-	# sudo apt-get install "$tmp_dir/$new_pkg"
-	sudo dpkg -i "$tmp_dir/$new_pkg"; sudo apt-get install --fix-broken
-  printf "Bat %s installed.\n" "$(bat_version)"
-}
-
-remove_bat() {
-  local cfg_bu_d="$HOME/.config/backup/bat"
-  sudo_login 2
-  printf "Removing Bat %s...\n" "$(bat_version)"
-  sudo dpkg --remove bat
-  if [[ -L "$HOME/.config/bat" ]]; then
-    unlink "$HOME/.config/bat"
-  elif [[ -d "$cfg_d" ]]; then
-    rm -rf "$cfg_d"
-  fi
-  [[ -d "$cfg_bu_d" ]] && rm -rf "$cfg_bu_d"
-  printf "Bat and its configuration files have been removed.\n"
-}
-
-bat_config() {
-  local repository
-  repository=$(assign_cfg_repo)
-  [[ -d "$cfg_d" ]] &&  rm -rf "$cfg_d"
-  printf "Applying Bat configuration...\n"
-  ln -s "$repository/bat/config" "$HOME/.config/bat"
-  printf "Bat configuration applied.\n"
-}
 
 help() {
   local errcode updated
 	errcode="${1:-2}"
-	updated="04 Apr 2025"
+	updated="04 Jun 2025"
 	cat << _HELP_
 ${orange}$script${normal} $version ($updated)
 Installs, updates, or removes the Bat utililty.
@@ -135,6 +54,72 @@ ${orange}Available options:${normal}
   -u  Updates the Bat utility to the latest version.
 _HELP_
   exit "$errcode"
+}
+
+# shellcheck disable=SC2317 # Don't warn about unreachable commands in this function
+# ShellCheck may incorrectly believe that code is unreachable if it's invoked by variable name or in a trap.
+cleanup() {
+  [[ -d "$tmp_dir" ]] && rm -rf "$tmp_dir"
+  [[ -f "$tmp_file" ]] && rm -f "$tmp_file"
+}
+
+check_dependencies() {
+  local packages=( gdebi git wget )
+  check_packages "${packages[@]}"
+}
+
+bat_version() {
+  bat --version | cut -d' ' -f2
+}
+
+newest_version() {
+  wget -qO "$tmp_file" "$gh_url"
+  new_ver=$(sed 's/\// /g' "$tmp_file" | grep -Ev 'beta|-rc' | awk '/download/ && /amd64.deb/ {print $7;exit}' | sed 's/^v//')
+  echo "$new_ver"
+}
+
+compare_versions() {
+  local cur_ver
+  cur_ver="$(bat_version)"
+  if [[ "$cur_ver" == "$new_ver" ]]; then
+    printf "%s Bat %s is the current version. No update required.%s\n" "$lightyellow" "$cur_ver" "$normal"
+  else
+    printf "%sInstalled version of Bat is %s, updating to %s...%s\n" "$lightyellow" "$cur_ver" "$new_ver" "$normal"
+    install_bat
+  fi
+}
+
+install_bat() {
+  local new_pkg="bat_${new_ver}_amd64.deb"
+  sudo_login 2
+  printf "Downloading Bat %s from the sharkdp GitHub repository..." "$new_ver"
+  dots "."
+  wget -q -P "$tmp_dir/" "$gh_url/download/v$new_ver/$new_pkg"
+  kill "$!"; tput cnorm
+  printf "done\nInstalling Bat %s...\n" "$new_ver"
+	sudo dpkg -i "$tmp_dir/$new_pkg"; sudo apt-get install --fix-broken
+  printf "Bat %s installed.\n" "$(bat_version)"
+}
+
+remove_bat() {
+  sudo_login 2
+  printf "Removing Bat %s...\n" "$(bat_version)"
+  sudo dpkg --remove bat
+  [[ -L "$HOME/.config/bat/config" ]] && unlink "$HOME/.config/bat/config"
+  [[ -d "$HOME/.config/bat" ]] && rm -rf "$HOME/.config/bat"
+  [[ -d "$HOME/.config/backup/bat" ]] && rm -rf "$HOME/.config/backup/bat"
+  printf "Bat and its configuration files have been removed.\n"
+}
+
+bat_config() {
+  local repository
+  repository=$(assign_cfg_repo)
+	[[ -d "$HOME/.config/bat" ]] || mkdir -p "$HOME/.config/bat"
+  printf "Applying Bat configuration...\n"
+	[[ -f "$HOME/.config/bat/config" ]] && rm "$HOME/.config/bat/config"
+	ln -s "$repository/bat/config" "$HOME/.config/bat/config"
+	[[ -L "$HOME/.local/bin/bat" ]] && unlink "$HOME/.local/bin/bat"
+  printf "Configuration applied to Bat %s.\n" "$(bat_version)"
 }
 
 main() {
@@ -157,8 +142,7 @@ main() {
         tmp_dir=$(mktemp -d) || die "Failed to create temporary directory." 1
         trap cleanup EXIT
         new_ver="$(newest_version)"
-        echo "${lightyellow}Installing Bat version $new_ver...${normal}"
-        check_distro || echo "Bat $new_ver is the latest version compatible with $(get_distribution)."
+        printf "%sInstalling Bat version %s...%s\n" "$lightyellow" "$new_ver" "$normal"
         install_bat
         bat_config
       ;;
@@ -172,7 +156,7 @@ main() {
         tmp_dir=$(mktemp -d) || die "Failed to create temporary directory." 1
         trap cleanup EXIT
         new_ver="$(newest_version)"
-        [[ -z "$new_ver" ]] && die "No download available. Try again later." 1
+        [[ "$new_ver" ]] || die "No download available. Try again later." 1
         compare_versions
       ;;
       ? )
@@ -183,7 +167,7 @@ main() {
   done
   [[ "$noOpt" = 1 ]] && { printf "%s No argument passed.\n" "$RED_ERROR" >&2; help 1; }
   shift "$(( OPTIND - 1 ))"
-	over_line "$script v$version"
+	over_line "$script $version"
   exit
 }
 
