iru-fastfetch - incorporated assign_repositorty() and modified affected function.

diff --git a/iru-fastfetch b/iru-fastfetch
--- a/iru-fastfetch
+++ b/iru-fastfetch
@@ -7,7 +7,7 @@
 # Author       : Copyright © 2024 Richard B. Romig, Mosfanet
 # Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
 # Created      : 02 May 2024
-# Last updated : 31 Oct 2024
+# Last updated : 19 Nov 2024
 # Comments     : Fastfetch config.jsonc does not work with Terminator.
 # TODO (Rick)  :
 # License      : GNU General Public License, version 2.0
@@ -30,7 +30,7 @@ set -eu
 ## Global Variables ##
 
 script=$(basename "$0"); readonly script
-readonly version="1.14.24305"
+readonly version="1.15.24324"
 readonly gh_url="https://github.com/fastfetch-cli/fastfetch/releases"
 readonly cfg_d="$HOME/.config/fastfetch"
 readonly logo_d="$HOME/.local/share/fastfetch/logos"
@@ -45,8 +45,28 @@ cleanup() {
 }
 
 check_dependencies() {
-  local packages=( gdebi wget )
+  local packages=( gdebi git wget )
   check_packages "${packages[@]}"
+}
+
+assign_repo() {
+	local localip repo
+	localip=$(local_ip)
+	case "$localip" in
+		10|16|22 )
+			repo="$HOME/gitea/configs"
+		;;
+		* )
+			if [[ -d "$HOME/Downloads/configs" ]]; then
+				pushd "$HOME/Downloads/configs" || die "pushd failed"
+				git pull --quiet origin main
+				popd || die "popd failed"
+			else
+				git clone --quiet "$GITEA_URL/configs.git" "$HOME/Downloads/configs"
+			fi
+			repo="$HOME/Downloads/configs"
+	esac
+	printf "%s" "$repo"
 }
 
 check_distro() {
@@ -128,26 +148,17 @@ append_bashrc() {
 }
 
 fastfetch_config() {
-	local config ascii_logo localip png_logo repository
-	localip=$(local_ip)
+	local config ascii_logo png_logo repository
 	config="config.jsonc"
 	ascii_logo="atheist.txt"
 	png_logo="atheism.png"
 	[[ -d "$cfg_d" ]] || mkdir -p "$cfg_d"
 	[[ -d "$logo_d" ]] || mkdir -p "$logo_d"
 	printf "Installing configuration and logo files...\n"
-	if [[ "$localip" == "16" ]]; then
-		repository="$HOME/gitea/configs/fastfetch"
-		cp -v "$repository/$config" "$cfg_d/"
-		cp -v "$repository/$ascii_logo" "$logo_d/"
-		cp -v "$repository/$png_logo" "$logo_d/"
-	else
-		repository="configs/raw/branch/main/fastfetch"
-		[[ -f "$cfg_d/$config" ]] && mv -v "$cfg_d/$config" "$cfg_d/$config.bak"
-		wget -P "$cfg_d" "$GITEA_URL/$repository/$config"
-		wget -P  "$logo_d" "$GITEA_URL/$repository/$ascii_logo"
-		wget -P  "$logo_d" "$GITEA_URL/$repository/$png_logo"
-	fi
+	cp -v "$repository/fastfetch/$config" "$cfg_d/"
+	cp -v "$repository/fastfetch/$config.ascii" "$cfg_d/"
+	cp -v "$repository/fastfetch/$ascii_logo" "$logo_d/"
+	cp -v "$repository/fastfetch/$png_logo" "$logo_d/"
 	append_bashrc
 	printf "Fastfetch configuration applied.\n"
 }
@@ -155,7 +166,7 @@ fastfetch_config() {
 help() {
   local errcode updated
 	errcode="${1:-2}"
-	updated="31 Oct 2024"
+	updated="19 Nov 2024"
 	cat << _HELP_
 ${orange}$script${normal} $version ($updated)
 Installs, configures, removes, updates FastFetch
@@ -173,7 +184,9 @@ _HELP_
 }
 
 main() {
-  local noOpt opt optstr new_ver
+  local noOpt opt optstr new_ver repository
+	check_dependencies
+	repository=$(assign_repo)
 	noOpt=1
 	optstr=":chiru"
 	while getopts "$optstr" opt; do
@@ -181,7 +194,7 @@ main() {
 			c )
 				exists fastfetch || leave "Fastfetch is not installed."
 				echo "${lightyellow}Installing custom Fastfetch configuration...${normal}"
-				fastfetch_config
+				fastfetch_config"$repository"
 			;;
 			h )
 				help 0
@@ -191,13 +204,12 @@ main() {
 				tmp_file=$(mktemp) || die "Failed to create temporary file." 1
 				tmp_dir=$(mktemp -d) || die "Failed to create temporary directory." 1
 				trap cleanup EXIT
-				check_dependencies
 				new_ver="$(newest_version)"
 				[[ "$new_ver" ]] || die "No download available. Try again later." 1
 				check_distro || echo "Fastfetch $new_ver is the latest version compatible with $(get_distribution)"
 				echo "${lightyellow}Installing Fastfetch version $new_ver...${normal}"
 				install_fastfetch "$new_ver"
-				fastfetch_config
+				fastfetch_config"$repository"
 			;;
 			r )
 				exists fastfetch || leave "Fastfetch is not installed."
@@ -208,7 +220,6 @@ main() {
 				tmp_file=$(mktemp) || die "Failed to create temporary file." 1
 				tmp_dir=$(mktemp -d) || die "Failed to create temporary directory." 1
 				trap cleanup EXIT
-				check_dependencies
 				new_ver="$(newest_version)"
 				[[ "$new_ver" ]] || die "No download available. Try again later." 1
 				compare_versions "$new_ver"
