iru-marktext: added check for failed install and check for missing configs repo directory

diff --git a/iru-marktext b/iru-marktext
--- a/iru-marktext
+++ b/iru-marktext
@@ -7,7 +7,7 @@
 # Author       : Copyright (C) 2022, Richard B. Romig, Mosfanet
 # Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
 # Created      : 10 Jan 2022
-# Updated      : 04 Oct 2025
+# Updated      : 26 Oct 2025
 # Comments     :
 # TODO (Rick)  :
 # License      : GNU General Public License, version 2.0
@@ -39,14 +39,14 @@ fi
 ## Global Variables ##
 
 readonly script="${0##*/}"
-readonly version="4.17.25277"
+readonly version="4.18.25299"
 readonly gh_url="https://github.com/marktext/marktext/releases"
 
 ## Functions ##
 
 help() {
 	local errcode="${1:-2}"
-	local -r updated="04 Oct 2025"
+	local -r updated="26 Oct 2025"
 	cat << _HELP_
 ${orange}$script${normal} $version ($updated)
 Installs, configures, updates, removes the Mark Text markdown editor.
@@ -101,6 +101,7 @@ install_marktext() {
   sudo_login 2
   printf "Installing Mark Text %s...\n" "$new_ver"
 	sudo dpkg -i "$tmp_dir/$new_pkg"; sudo apt-get install --fix-broken
+  exist markktext || die "Marktext installation failed!" 1
   printf "Mark Text %s installed.\n" "$(marktext_version)"
 }
 
@@ -109,12 +110,17 @@ remove_marktext() {
   printf "Removing the Mark Text markdown editor...\n"
   sudo apt-get remove --purge marktext -yy
   [[ -L  ~/.config/marktext/preferences.json ]] && unlink  ~/.config/marktext/preferences.json
-  find ~.config -type d -name marktext -exec rm -rf {} \;
+  find ~/.config -type d -name marktext -exec rm -rf {} \;
   printf "Mark Text markdown editor has been removed.\n"
 }
 
 marktext_config() {
   printf "Applying MarkText preferences...\n"
+	if [[ ! -d ~/Downloads/configs && ! -d ~/gitea/configs ]]; then
+		printf "%s Cloned repository not found!\n" "$RED_WARNING" >&2
+		return
+	fi
+	[[ -d ~/.config/config_dir ]] || mkdir -p ~/.config/config_dir
   [[ -f ~/.config/marktext/preferences.json ]] && rm ~/.config//marktext/preferences.json
   [[ -d ~/gitea/configs ]] && ln -sv ~/gitea/configs/marktext/preferences.json ~/.config/marktext/preferences.json
   [[ -d ~/Downloads/configs ]] &&   ln -sv ~/Downloads/configs/marktext/preferences.json ~/.config/marktext/preferences.json
