iru-bat: added return codes to functions; updated local variables

diff --git a/iru-bat b/iru-bat
--- a/iru-bat
+++ b/iru-bat
@@ -1,5 +1,5 @@
 #!/usr/bin/env bash
-##########################################################################
+###############################################################################
 # Script Name  : iru-bat
 # Description  : Installs, updates, and removes the Bat utillity program.
 # Dependencies : gdebi, wget git
@@ -7,7 +7,7 @@
 # Author       : Copyright (C) 2022, Richard B. Romig, Mosfanet
 # Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
 # Created      : 09 Jan 2022
-# Updated      : 17 Jun 2026
+# Updated      : 13 Jul 2026
 # Comments     : Use install-batcat if distro version has same base version number as latest GitHub release.
 #              : Mint 22 installs version 0.24.0 with the Ubuntu version appended.
 #              : Debian 13 installs version 0.25.0 with the Debian version appended.
@@ -15,35 +15,24 @@
 # TODO (Rick)  :
 # License      : GNU General Public License, version 2.0
 # License URL  : https://github.com/RickRomig/scripts/blob/main/LICENSE
-##########################################################################
-# This program is free software; you can redistribute it and/or modify
-# it under the terms of the GNU General Public License as published by
-# the Free Software Foundation; either version 2 of the License, or
-# (at your option) any later version.
+###############################################################################
+# This program is free software; you can redistribute it and/or modify# it under
+# the terms of the GNU General Public License as published by the Free Software
+# Foundation; either version 2 of the License, or# (at your option) any later
+# version.
 #
-# This program is distributed in the hope that it will be useful,
-# but WITHOUT ANY WARRANTY; without even the implied warranty of
-# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
-# GNU General Public License for more details.
-##########################################################################
+# This program is distributed in the hope that it will be useful, but WITHOUT
+# ANY WARRANTY; without even the implied warranty of# MERCHANTABILITY or FITNESS
+# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
+###############################################################################
 
-## Load function library ##
+## Source function library ##
 # shellcheck source=/home/rick/bin/functionlib
 source ~/bin/functionlib || { printf "\e[91mERROR:\e[0m Unable to source functionlib\n"; exit 1; }
 
-## Global Variables ##
-
-readonly script="${0##*/}"
-readonly version="7.5.26168"
-readonly gh_url="https://github.com/sharkdp/bat/releases"
-DOTS_PID=
-EC=0
-
-## Functions ##
-
 help() {
 	local errcode="${1:-1}"
-	local -r updated=" 17 Jun 2026"
+	local -r updated=" 13 Jul 2026"
 	cat << _HELP_
 ${orange}$script${normal} $version ($updated)
 Installs, updates, or removes the Bat utililty.
@@ -69,15 +58,17 @@ cleanup() {
 check_dependencies() {
   local packages=( git wget )
   check_packages "${packages[@]}"
+  return 0
 }
 
 bat_version() {
   cut -d' ' -f2 < <(bat --version)
+  return 0
 }
 
 convert_compare() {
-  local newVer="$1"
-  local curVer="$2"
+  local -r newVer="$1"
+  local -r curVer="$2"
   local newer="$FALSE"
 	local new_arr=()
 	local cur_arr=()
@@ -94,34 +85,39 @@ convert_compare() {
 }
 
 newest_version() {
+  local -r gh_url="$1"
   wget -qO "$TMP_FILE" "$gh_url"
   new_ver=$(sed 's/^v//' < <(awk -F'/' '/download/ && /amd64.deb/ {print $6;exit}' "$TMP_FILE"))
   echo "$new_ver"
+  return 0
 }
 
 compare_versions() {
-  local new_ver="$1"
+  local -r new_ver="$1"
+  local -r gh_url="$2"
   local cur_ver
   cur_ver="$(bat_version)"
   printf "Comparing current and newest versions...\n"
   if [[ -z "$new_ver" ]]; then
     printf "%s No download available. Try again later." "$RED_ERROR" >&2
-    EC="$E_DOWNLOAD"
+    return "$E_DOWNLOAD"
   elif convert_compare "$new_ver" "$cur_ver"; then
     printf "%sInstalled version of Bat is %s, updating to %s...%s\n" "$lightyellow" "$cur_ver" "$new_ver" "$normal"
-    install_bat "$new_ver"
-  else
+    install_bat "$new_ver" "$gh_url"
+    return "$?"
+else
     printf "%sBat %s is the current version. No update required.%s\n" "$lightyellow" "$cur_ver" "$normal"
   fi
+  return 0
 }
 
 install_bat() {
-  local new_ver="$1"
+  local -r new_ver="$1"
+  local -r gh_url="$2"
   local new_pkg="bat_${new_ver}_amd64.deb"
   if [[ -z "$new_ver" ]]; then
     printf "%s No download available. Try again later." "$RED_ERROR" >&2
-    EC="$E_DOWNLOAD"
-    return
+    return "$E_DOWNLOAD"
   fi
   printf "Downloading Bat %s from the sharkdp GitHub repository..." "$new_ver"
   dots "." &
@@ -133,11 +129,11 @@ install_bat() {
 	sudo dpkg -i "$TMP_DIR/$new_pkg"; sudo apt-get install --fix-broken
   if [[ "$(bat_version)" != "$new_ver" ]]; then
     printf "%s Bat installation failed.\n" "$RED_ERROR" >&2
-    EC="$E_INSTALLATION"
-    return
+    return "$E_INSTALLATION"
   fi
   [[ -L ~/.local/bin/bat ]] && unlink ~/.local/bin/bat
   printf "Bat %s installed.\n" "$(bat_version)"
+  return 0
 }
 
 remove_bat() {
@@ -148,6 +144,7 @@ remove_bat() {
   [[ -L ~/.local/bin/bat ]] && unlink ~/.local/bin/bat
   find ~/.config -type d -name bat -exec rm -rf {} \;
   printf "Bat and its configuration files have been removed.\n"
+  return 0
 }
 
 bat_config() {
@@ -155,8 +152,7 @@ bat_config() {
 	[[ -d ~/.config/bat ]] || mkdir -p ~/.config/bat
 	if [[ ! -d ~/Downloads/configs && ! -d ~/gitea/configs ]]; then
 		printf "%s Cloned repository not found!\n" "$RED_WARNING" >&2
-    EC="$E_FILENOTFOUND"
-		return
+		return "$E_FILENOTFOUND"
 	fi
   printf "Applying Bat configuration...\n"
 	[[ -f ~/.config/bat/config ]] && rm ~/.config/bat/config
@@ -164,36 +160,40 @@ bat_config() {
 	[[ -d ~/Downloads/configs ]] && ln -sv ~/Downloads/configs/bat/config ~/.config/bat/config
   [[ -f /usr/bin/batcat ]] && ln -sv /usr/bin/batcat ~/.local/bin/bat
   printf "Bat %s configuration applied.\n" "$(bat_version)"
+  return 0
 }
 
 main() {
-  local noOpt opt optstr new_ver OPTARG OPTIND
-  noOpt=1
-  optstr=":hiru"
+  local -r  script="${0##*/}"
+  local -r version="7.6.26194"
+	local -i exit_code=0
+  local -r gh_url="https://github.com/sharkdp/bat/releases"
+  local opt new_ver OPTARG OPTIND
+  local -i noOpt=1
+  local -r optstr=":hiru"
   while getopts "$optstr" opt; do
     case "$opt" in
       h )
-        help 0
+        help "$script" "$version" 0
         ;;
       i )
         if exists bat || exists batcat; then
-          printf "Bat %s is already installed.\n" "$(bat_version)" >&2
+          printf "Bat %s is already installed.\n" "$(bat_version)"
         else
           check_dependencies
           TMP_FILE=$(mktemp) || die "Failed to create temporary file." "$E_TEMP_FILE"
           TMP_DIR=$(mktemp -d) || die "Failed to create temporary directory." "$E_TEMP_DIR"
           trap cleanup EXIT
-					new_ver="$(newest_version)"
+					new_ver="$(newest_version "$gh_url")"
           printf "%sInstalling Bat version %s...%s\n" "$lightyellow" "$new_ver" "$normal"
-          install_bat "$new_ver"
-          bat_config
+          install_bat "$new_ver" "$gh_url" && bat_config
         fi
         ;;
       r )
         if exist bat || exists batcat; then
           remove_bat
         else
-          printf "Bat is not installed.\n" >&2
+          printf "Bat is not installed.\n"
         fi
         ;;
       u )
@@ -202,22 +202,23 @@ main() {
           TMP_FILE=$(mktemp) || die "Failed to create temporary file." "$E_TEMP_FILE"
           TMP_DIR=$(mktemp -d) || die "Failed to create temporary directory." "$E_TEMP_DIR"
           trap cleanup EXIT
-          new_ver="$(newest_version)"
-          compare_versions "$new_ver"
+          new_ver="$(newest_version "$gh_url")"
+          compare_versions "$new_ver" "$gh_url"
         else
-          printf "Bat is not installed.\n" >&2
+          printf "Bat is not installed.\n"
         fi
         ;;
       ? )
         printf "%s Invalid option -%s\n" "$RED_ERROR" "$OPTARG" >&2
-        help "$E_INVALID_ARG"
+        help "$script" "$version" "$E_INVALID_ARG"
     esac
+    exit_code="$?"
 	  noOpt=0
   done
-  [[ "$noOpt" = 1 ]] && { printf "%s No argument passed.\n" "$RED_ERROR" >&2; help "$E_MISSING_ARG"; }
+  [[ "$noOpt" = 1 ]] && { printf "%s No argument passed.\n" "$RED_ERROR" >&2; help "$script" "$version" "$E_MISSING_ARG"; }
   shift "$(( OPTIND - 1 ))"
 	over_line "$script $version"
-  exit "$EC"
+  exit "$exit_code"
 }
 
 ## Execution ##
