iru-vscodium - enclosed getopts in main(); updated help()

diff --git a/iru-vscodium b/iru-vscodium
--- a/iru-vscodium
+++ b/iru-vscodium
@@ -7,7 +7,7 @@
 # Author       : Copyright (C) 2022, Richard B. Romig, Mosfanet
 # Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
 # Created      : 16 Jul 2022
-# Updated      : 16 Aug 2024
+# Updated      : 02 Oct 2024
 # Comments     :
 # TODO (Rick)  :
 # License      : GNU General Public License, version 2.0
@@ -25,11 +25,12 @@ else
   exit 1
 fi
 
-## Variables ##
+set -eu
 
-_script=$(basename "$0"); readonly _script
-readonly _version="2.18.24229"
-readonly _updated="16 Aug 2024"
+## Global Variables ##
+
+script=$(basename "$0"); readonly script
+readonly version="2.1.24276"
 readonly gh_url="https://github.com/VSCodium/vscodium/releases"
 
 ## Functions ##
@@ -44,6 +45,10 @@ cleanup() {
 check_dependencies() {
   local packages=( gdebi wget )
   check_packages "${packages[@]}"
+}
+
+codium_version() {
+	dpkg -l  codium | awk '/ii/ {print $3}'
 }
 
 newest_version() {
@@ -71,7 +76,7 @@ install_vscodium() {
   kill "$!";printf "done\n";tput cnorm
   printf "Installing VSCodium %s...\n" "$new_ver"
   sudo gdebi -n "$tmp_dir/$new_pkg"
-  printf "VSCodium %s successfully installed.\n" "$(codium_ver)"
+  printf "VSCodium %s successfully installed.\n" "$(codium_version)"
 }
 
 remove_vscodium() {
@@ -102,17 +107,15 @@ apply_settings() {
   printf "VSCodium settings applied.\n"
 }
 
-codium_ver() {
-	dpkg -l | grep -w codium | awk '{print $3}'
-}
-
 help() {
-  local errcode="${1:-2}"
-  cat << END_HELP
-${orange}$_script${normal} $_version ($_updated)
+  local errcode updated
+	errcode="${1:-2}"
+	updated="02 Oct 2024"
+	cat << _HELP_
+${orange}$script${normal} $version ($updated)
 Installs, configures, updates,  removes the VSCodium editor.
 
-${green}Usage:${normal} $_script [OPTION]
+${green}Usage:${normal} $script [OPTION]
 
 ${orange}Available options:${normal}
   -h  Displays help.
@@ -120,59 +123,63 @@ ${orange}Available options:${normal}
   -r  Removes the VSCodium editor from the system.
   -s  Applies VSCodium settings.
   -u  Updates the VSCodium editor to the latest version.
-END_HELP
+_HELP_
   exit "$errcode"
+}
+
+main() {
+  local noOpt opt optstr
+  check_dependencies
+  noOpt=1
+  optstr=":hirsu"
+  while getopts "$optstr" opt; do
+	  case "$opt" in
+		  h )
+			  help 0
+      ;;
+		  i )
+			  exists codium && leave "VSCodium $(codium_version) is already installed."
+        sudo_login 2
+        tmp_file=$(mktemp) || die "Failed to create temporary file." 1
+			  tmp_dir=$(mktemp -d) || die "Failed to create temporary directory." 1
+			  trap cleanup EXIT
+			  new_ver="$(newest_version)"
+        [[ -z "$new_ver" ]] && die "No download available. Try again later." 1
+        echo "${lightyellow}Installing VSCodium $new_ver...${normal}"
+			  install_vscodium
+        apply_settings
+      ;;
+		  r )
+        exists codium || leave "VSCodium is not installed."
+        sudo_login 2
+        remove_vscodium
+      ;;
+		  s )
+        exists codium || leave "VSCodium is not installed."
+        apply_settings
+      ;;
+		  u )
+        exists codium || leave "VSCodium is not installed."
+        sudo_login 2
+			  tmp_file=$(mktemp -q) || die "Failed to create temporary file." 1
+			  tmp_dir=$(mktemp -d) || die "Failed to create temporary directory." 1
+			  trap cleanup EXIT
+			  new_ver="$(newest_version)"
+        [[ "$new_ver" ]] || die "No download available. Try again later." 1
+			  compare_versions
+      ;;
+		  ? )
+        printf "%s Invalid option -%s\n" "$RED_ERROR" "$OPTARG" >&2
+			  help 2
+	  esac
+	  noOpt=0
+  done
+  [[ "$noOpt" = 1 ]] && { printf "%s No argument passed.\n" "$RED_ERROR" >&2; help 1; }
+  shift "$(( OPTIND - 1 ))"
+  box "$script v$version"
+  exit
 }
 
 ## Execution ##
 
-noOpt=1
-optstr=":hirsu"
-while getopts "$optstr" opt; do
-	case "$opt" in
-		h )
-			help 0
-    ;;
-		i )
-			exists codium && leave "VSCodium $(codium_ver) is already installed."
-      sudo_login 2
-      check_dependencies
-      tmp_file=$(mktemp) || die "Failed to create temporary file." 1
-			tmp_dir=$(mktemp -d) || die "Failed to create temporary directory." 1
-			trap cleanup EXIT
-			new_ver="$(newest_version)"
-      [[ -z "$new_ver" ]] && die "No download available. Try again later." 1
-      echo "${lightyellow}Installing VSCodium $new_ver...${normal}"
-			install_vscodium
-      apply_settings
-    ;;
-		r )
-      exists codium || leave "VSCodium is not installed."
-      sudo_login 2
-      remove_vscodium
-    ;;
-		s )
-      exists codium || leave "VSCodium is not installed."
-      apply_settings
-    ;;
-		u )
-      exists codium || leave "VSCodium is not installed."
-      sudo_login 2
-      check_dependencies
-			tmp_file=$(mktemp -q) || die "Failed to create temporary file." 1
-			tmp_dir=$(mktemp -d) || die "Failed to create temporary directory." 1
-			trap cleanup EXIT
-			new_ver="$(newest_version)"
-      [[ -z "$new_ver" ]] && die "No download available. Try again later." 1
-			compare_versions
-    ;;
-		? )
-      printf "%s Invalid option -%s\n" "$red_error" "$OPTARG" >&2
-			help 2
-	esac
-	noOpt=0
-done
-[[ "$noOpt" = 1 ]] && { printf "%s No argument passed.\n" "$red_error" >&2; help 1; }
-shift "$(( OPTIND - 1 ))"
-box "$_script v$_version"
-exit
+main "$@"
