iru-vscodium: capitalized tmp_dir & tmp_file (globabl variables)

diff --git a/iru-vscodium b/iru-vscodium
--- a/iru-vscodium
+++ b/iru-vscodium
@@ -7,7 +7,7 @@
 # Author       : Copyright (C) 2022, Richard B. Romig, Mosfanet
 # Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
 # Created      : 16 Jul 2022
-# Updated      : 27 Feb 2026
+# Updated      : 17 Apr 2026
 # Comments     :
 # TODO (Rick)  :
 # License      : GNU General Public License, version 2.0
@@ -24,22 +24,14 @@
 # GNU General Public License for more details.
 ##########################################################################
 
-## Shellcheck Directives ##
+## Load function library ##
 # shellcheck source=/home/rick/bin/functionlib
-
-## Source function library ##
-
-if [[ -x "$HOME/bin/functionlib" ]]; then
-  source "$HOME/bin/functionlib"
-else
-  printf "\e[91mERROR:\e[0m functionlib not found!\n" >&2
-  exit 81
-fi
+source functionlib || { printf "\e[91mERROR:\e[0m Unable to source functionlib\n"; exit 1; }
 
 ## Global Variables ##
 
 readonly script="${0##*/}"
-readonly version="3.7.26058"
+readonly version="3.8.26107"
 readonly gh_url="https://github.com/VSCodium/vscodium/releases"
 DOTS_PID=
 EC=0
@@ -48,7 +40,7 @@ EC=0
 
 help() {
 	local errcode="${1:-1}"
-	local updated="27 Feb 2026"
+	local updated="17 Apr 2026"
 	cat << _HELP_
 ${orange}$script${normal} $version ($updated)
 Installs, configures, updates,  removes the VSCodium editor.
@@ -66,8 +58,8 @@ _HELP_
 # shellcheck disable=SC2317 # Don't warn about unreachable commands in this function
 # ShellCheck may incorrectly believe that code is unreachable if it's invoked by variable name or in a trap.
 cleanup() {
-  [[ -d "$tmp_dir" ]] && rm -rf "$tmp_dir"
-  [[ -f "$tmp_file" ]] && rm -f "$tmp_file"
+  [[ -d "$TMP_DIR" ]] && rm -rf "$TMP_DIR"
+  [[ -f "$TMP_FILE" ]] && rm -f "$TMP_FILE"
 }
 
 codium_version() {
@@ -76,8 +68,8 @@ codium_version() {
 
 newest_version() {
   local new_ver
-  wget -qO "$tmp_file" "$gh_url"
-  new_ver=$(grep -Ev 'beta|-rc' <(awk -F'/' '/download/ && /amd64.deb/ {print $8;exit}' "$tmp_file") | sed 's/^v//')
+  wget -qO "$TMP_FILE" "$gh_url"
+  new_ver=$(grep -Ev 'beta|-rc' <(awk -F'/' '/download/ && /amd64.deb/ {print $8;exit}' "$TMP_FILE") | sed 's/^v//')
   echo "$new_ver"
 }
 
@@ -108,11 +100,11 @@ install_vscodium() {
   printf "Downloading VSCodium %s from the VSCodium GitHub repository..." "$new_ver"
   dots "." &
   DOTS_PID="$!"
-  wget -q -P "$tmp_dir/" "$gh_url/download/$new_ver/$new_pkg"
+  wget -q -P "$TMP_DIR/" "$gh_url/download/$new_ver/$new_pkg"
   kill_dots
   printf "Installing VSCodium %s...\n" "$new_ver"
   sudo_login 2
-	sudo dpkg -i "$tmp_dir/$new_pkg"; sudo apt-get install --fix-broken
+	sudo dpkg -i "$TMP_DIR/$new_pkg"; sudo apt-get install --fix-broken
   if [[ "$(codium_version)" != "$new_ver" ]]; then
     printf "%s VSCodium installation failed.\n" "$RED_ERROR" >&2
     EC="$E_INSTALLATION"
@@ -158,8 +150,8 @@ main() {
         if exists codium; then
           printf "VSCodium %s is already installed.\n" "$(codium_version)" >&2
         else
-          tmp_file=$(mktemp) || die "Failed to create temporary file." "$E_TEMP_FILE"
-          tmp_dir=$(mktemp -d) || die "Failed to create temporary directory." "$E_TEMP_DIR"
+          TMP_FILE=$(mktemp) || die "Failed to create temporary file." "$E_TEMP_FILE"
+          TMP_DIR=$(mktemp -d) || die "Failed to create temporary directory." "$E_TEMP_DIR"
 			    trap cleanup EXIT
 			    new_ver="$(newest_version)"
           printf "%sInstalling VSCodium %s...%s\n" "$lightyellow" "$new_ver" "$normal"
@@ -176,8 +168,8 @@ main() {
         ;;
 		  u )
         if exists codium; then
-          tmp_file=$(mktemp) || die "Failed to create temporary file." "$E_TEMP_FILE"
-          tmp_dir=$(mktemp -d) || die "Failed to create temporary directory." "$E_TEMP_DIR"
+          TMP_FILE=$(mktemp) || die "Failed to create temporary file." "$E_TEMP_FILE"
+          TMP_DIR=$(mktemp -d) || die "Failed to create temporary directory." "$E_TEMP_DIR"
 			    trap cleanup EXIT
 					printf "VSCodium: Comparing current and newest versions...\n"
 			    new_ver="$(newest_version)"
