iru-fresh-editor: updated error handling

diff --git a/iru-fresh-editor b/iru-fresh-editor
--- a/iru-fresh-editor
+++ b/iru-fresh-editor
@@ -7,7 +7,7 @@
 # Author       : Copyright (C) 2025, Richard B. Romig, Mosfanet
 # Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
 # Created      : 25 Dec 2025
-# Updated      : 15 Jan 2026
+# Updated      : 04 Feb 2026
 # Comments     :
 # TODO (Rick)  :
 # License      : GNU General Public License, version 2.0
@@ -33,21 +33,22 @@ if [[ -x "$HOME/bin/functionlib" ]]; then
   source "$HOME/bin/functionlib"
 else
   printf "\e[91mERROR:\e[0m functionlib not found!\n" >&2
-  exit 1
+  exit 81
 fi
 
 ## Global Variables ##
 
 readonly script="${0##*/}"
-readonly version="1.3.26015"
+readonly version="1.4.26035"
 readonly gh_url="https://github.com/sinelaw/fresh/releases"
 DOTS_PID=
+EC=0
 
 ## Functions ##
 
 help() {
-	local errcode="${1:-2}"
-	local -r updated="15 Jan 2026"
+	local errcode="${1:-1}"
+	local -r updated="04 Feb 2026"
 	cat << _HELP_
 ${orange}$script${normal} $version ($updated)
 Installs, updates, or removes the Fresh Editor.
@@ -80,7 +81,7 @@ fresh_version() {
 
 newest_version() {
   wget -qO "$tmp_file" "$gh_url"
-  new_ver=$(awk -F'/' '/download/ && /x86/ {print $6;exit}' "$tmp_file" | sed 's/^v//')
+  new_ver=$(sed 's/^v//' <(awk -F'/' '/download/ && /x86/ {print $6;exit}' "$tmp_file"))
   echo "$new_ver"
 }
 
@@ -89,7 +90,8 @@ compare_versions() {
   local cur_ver
   cur_ver="$(fresh_version)"
   if [[ -z "$new_ver" ]]; then
-    printf "No download available. Try again later.\n" >&2
+    printf "%s No download available. Try again later.\n" "$RED_ERROR" >&2
+    EC="$E_DOWNLOAD"
     return
   elif [[ ! "$new_ver" > "$cur_ver" ]]; then
     printf "%s Fresh-editor %s is the current version. No update required.%s\n" "$lightyellow" "$cur_ver" "$normal"
@@ -102,9 +104,13 @@ compare_versions() {
 install_fresh() {
   local new_ver="$1"
   local new_pkg="fresh-editor_${new_ver}-1_amd64.deb"
-  [[ -z "$new_ver" ]] && die "No download available. Try again later." 1
+  if [[ -z "$new_ver" ]]; then
+    printf "%s No download available. Try again later." "$RED_ERROR" >&2
+    EC="$E_DOWNLOAD"
+    return
+  fi
   printf "Downloading Fresh-editor %s from the sinelaw GitHub repository..." "$new_ver"
-   dots "." &
+  dots "." &
 	DOTS_PID="$!"
   wget -q -P "$tmp_dir/" "$gh_url/download/v$new_ver/$new_pkg"
 	kill_dots
@@ -112,6 +118,11 @@ install_fresh() {
   sudo_login 2
 	sudo dpkg -i "$tmp_dir/$new_pkg"; sudo apt-get install --fix-broken
   dpkg -l fresh-editor | grep -qw '^ii' >/dev/null 2>&1 || die "Bat installation failed." 1
+  if grep -q '^ii' <(dpkg -l fresh-editor >/dev/null 2>&1); then
+    printf "%s Fresh-editor installation failed.\n" "$RED_ERROR" >&2
+    EC="$E_INSTALLATION"
+    return
+  fi
   [[ -L /usr/bin/fresh ]] || sudo ln -sf /usr/share/fresh-editor/fresh /usr/bin/fresh
   printf "Fresh-editor %s installed.\n" "$(fresh_version)"
 }
@@ -120,15 +131,20 @@ remove_fresh() {
   sudo_login 2
   printf "Removing Fresh-editor %s...\n" "$(fresh_version)"
   sudo dpkg --remove fresh-editor
-  find ~/.config -type d -name fresh -exec rm -rf {} \;
+	find ~/ -maxdepth 3 -type d -path "$HOME/Downloads" -prune -o -path "$HOME/gitea" -prune -o -type d -name fresh -exec rm -rf {} \;
   [[ -L /usr/bin/fresh ]] && sudo rm -f /usr/bin/fresh
   printf "Fresh-editor and its configuration files have been removed.\n"
 }
 
 fresh_config() {
+  [[ "$EC" -ne 0 ]] && return
   local repository=~/Downloads/configs
   [[ -d ~/gitea/configs ]] && repository=~/gitea/configs
-  [[ -d "$repository" ]] || { printf "%s Cloned repository not found!\n" "$RED_WARNING" >&2; return; }
+  if [[ ! -d "$repository" ]]; then
+    printf "%s Cloned repository not found!\n" "$RED_WARNING" >&2
+    EC="$E_FILENOTFOUND"
+    return
+  fi
 	[[ -d ~/.config/fresh ]] || mkdir -p ~/.config/fresh
   printf "Applying Fresh-editor configuration...\n"
   cp -v "$repository/fresh/config.json" ~/.config/fresh/
@@ -149,8 +165,8 @@ main() {
           printf "Fresh-editor %s is already installed.\n" "$(fresh_version)" >&2
         else
           check_dependencies
-          tmp_file=$(mktemp) || die "Failed to create temporary file." 1
-          tmp_dir=$(mktemp -d) || die "Failed to create temporary directory." 1
+          tmp_file=$(mktemp) || die "Failed to create temporary file." "$E_TEMP_FILE"
+          tmp_dir=$(mktemp -d) || die "Failed to create temporary directory." "$E_TEMP_DIR"
           trap cleanup EXIT
 					new_ver="$(newest_version)"
           printf "%sInstalling Bat version %s...%s\n" "$lightyellow" "$new_ver" "$normal"
@@ -168,8 +184,8 @@ main() {
       u )
         if exists fresh; then
           check_dependencies
-          tmp_file=$(mktemp) || die "Failed to create temporary file." 1
-          tmp_dir=$(mktemp -d) || die "Failed to create temporary directory." 1
+          tmp_file=$(mktemp) || die "Failed to create temporary file." "$E_TEMP_FILE"
+          tmp_dir=$(mktemp -d) || die "Failed to create temporary directory." "$E_TEMP_DIR"
           trap cleanup EXIT
 					printf "Fresh-editor: Comparing current and newest versions...\n"
           new_ver="$(newest_version)"
@@ -180,14 +196,14 @@ main() {
         ;;
       ? )
         printf "%s Invalid option -%s\n" "$RED_ERROR" "$OPTARG" >&2
-        help 2
+        help "$E_INVALID_ARG"
     esac
 	  noOpt=0
   done
-  [[ "$noOpt" = 1 ]] && { printf "%s No argument passed.\n" "$RED_ERROR" >&2; help 1; }
+  [[ "$noOpt" = 1 ]] && { printf "%s No argument passed.\n" "$RED_ERROR" >&2; help "$E_MISSING_ARG"; }
   shift "$(( OPTIND - 1 ))"
 	over_line "$script $version"
-  exit
+  exit "$EC"
 }
 
 ## Execution ##
