iru-bat: added convert_compare() to convert version numbers to all digits and compare them

diff --git a/iru-bat b/iru-bat
--- a/iru-bat
+++ b/iru-bat
@@ -7,7 +7,7 @@
 # Author       : Copyright (C) 2022, Richard B. Romig, Mosfanet
 # Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
 # Created      : 09 Jan 2022
-# Updated      :  17 Apr 2026
+# Updated      : 02 Jun 2026
 # Comments     : Use install-batcat if distro version has same base version number as latest GitHub release.
 #              : Mint 22 installs version 0.24.0 with the Ubuntu version appended.
 #              : Debian 13 installs version 0.25.0 with the Debian version appended.
@@ -34,7 +34,7 @@ source functionlib || { printf "\e[91mERROR:\e[0m Unable to source functionlib\n
 ## Global Variables ##
 
 readonly script="${0##*/}"
-readonly version="6.22.26107"
+readonly version="7.0.26153"
 readonly gh_url="https://github.com/sharkdp/bat/releases"
 DOTS_PID=
 EC=0
@@ -43,7 +43,7 @@ EC=0
 
 help() {
 	local errcode="${1:-1}"
-	local -r updated=" 17 Apr 2026"
+	local -r updated=" 02 Jun 2026"
 	cat << _HELP_
 ${orange}$script${normal} $version ($updated)
 Installs, updates, or removes the Bat utililty.
@@ -75,6 +75,15 @@ bat_version() {
   cut -d' ' -f2 <(bat --version)
 }
 
+convert_compare() {
+	local newVer="$1"
+	local curVer="$2"
+	local digitCur digitNew
+	digitNew=$(sed 's/^0*//' < <(tr -d . <<< "$newVer"))
+	digitCur=$(sed 's/^0*//;s/[-~+ud].*//' < <(tr -d . <<< "$curVer"))
+	(( digitNew > digitCur )) && return 0 || return 1
+}
+
 newest_version() {
   wget -qO "$TMP_FILE" "$gh_url"
   new_ver=$(grep -Ev 'beta|-rc' <(awk -F'/' '/download/ && /amd64.deb/ {print $6;exit}' "$TMP_FILE") | sed 's/^v//')
@@ -88,13 +97,22 @@ compare_versions() {
   if [[ -z "$new_ver" ]]; then
     printf "%s No download available. Try again later." "$RED_ERROR" >&2
     EC="$E_DOWNLOAD"
-    return
-  elif [[ ! "$new_ver" > "$cur_ver" ]]; then
+  elif convert_compare "$new_ver" "$cur_ver"; then
+    printf "%sInstalled version of Bat is %s, updating to %s...%s\n" "$lightyellow" "$cur_ver" "$new_ver" "$normal"
+  else
     printf "%s Bat %s is the current version. No update required.%s\n" "$lightyellow" "$cur_ver" "$normal"
-    return
   fi
-  printf "%sInstalled version of Bat is %s, updating to %s...%s\n" "$lightyellow" "$cur_ver" "$new_ver" "$normal"
-  install_bat "$new_ver"
+
+  # if [[ -z "$new_ver" ]]; then
+  #   printf "%s No download available. Try again later." "$RED_ERROR" >&2
+  #   EC="$E_DOWNLOAD"
+  #   return
+  # elif [[ ! "$new_ver" > "$cur_ver" ]]; then
+  #   printf "%s Bat %s is the current version. No update required.%s\n" "$lightyellow" "$cur_ver" "$normal"
+  #   return
+  # fi
+  # printf "%sInstalled version of Bat is %s, updating to %s...%s\n" "$lightyellow" "$cur_ver" "$new_ver" "$normal"
+  # install_bat "$new_ver"
 }
 
 install_bat() {
