iru-fastfetch - updated help()

diff --git a/iru-fastfetch b/iru-fastfetch
--- a/iru-fastfetch
+++ b/iru-fastfetch
@@ -7,7 +7,7 @@
 # Author       : Copyright © 2024 Richard B. Romig, Mosfanet
 # Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
 # Created      : 02 May 2024
-# Last updated : 05 Jun 2024
+# Last updated : 18 Jun 2024
 # Comments     :
 # TODO (Rick)  :
 # License      : GNU General Public License, version 2.0
@@ -30,8 +30,8 @@ set -eu
 ## Global Variables ##
 
 _script=$(basename "$0"); readonly _script
-readonly _version="1.4.24157"
-readonly _updated="05 Jun 2024"
+readonly _version="1.5.24170"
+readonly _updated="18 Jun 2024"
 readonly gh_url="https://github.com/fastfetch-cli/fastfetch/releases"
 readonly ff_cfg_d="$HOME/.config/fastfetch"
 readonly ff_logo_d="$HOME/.local/share/fastfetch/logos"
@@ -133,25 +133,32 @@ fastfetch_config() {
 help() {
 	errcode="${1:-2}"
 	cat << END_HELP
+${orange}$_script${normal} $_version ($_updated)
+Installs, configures, removes, updates FastFetch
+
 ${green}Usage:${normal} $_script [OPTION]
-${orange}OPTIONS:${normal}
-	-h	Display help
-	-i	Install Fastfetch
-	-r	Remove Fastfetch
-	-s	Apply Fastretch configuration and logo
-	-u	Update Fastfetch
-$_script $_version (Updated $_updated)
+
+${orange}Available options:${normal}
+  -c  Apply Fastretch configuration and logo
+  -h  Display help
+  -i  Install Fastfetch
+  -r  Remove Fastfetch
+  -u  Update Fastfetch
 END_HELP
   exit "$errcode"
 }
 
 ## Execution ##
 
-box "$_script $_version"
 noOpt=1
-optstr=":hirsu"
+optstr=":chiru"
 while getopts "$optstr" opt; do
 	case "$opt" in
+		c )
+			exists fastfetch || leave "Fastfetch is not installed."
+			echo "${lightyellow}Installing custom Fastfetch configuration...${normal}"
+			fastfetch_config
+		;;
 		h )
 			help 0
 		;;
@@ -174,11 +181,6 @@ while getopts "$optstr" opt; do
 			sudo_login 2
 			remove_fastfetch
 		;;
-		s )
-			exists fastfetch || leave "Fastfetch is not installed."
-			echo "${lightyellow}Installing custom Fastfetch configuration...${normal}"
-			fastfetch_config
-		;;
 		u )
 			exists fastfetch || leave "Fastfetch is not installed."
       tmp_file=$(mktemp) || die "Failed to create temporary file." 1
@@ -191,11 +193,12 @@ while getopts "$optstr" opt; do
 			compare_versions
 		;;
 		? )
-			echo "${lightred}ERROR:${normal} Invalid option -${OPTARG}" >&2
+			printf "%s Invalid option -%s\n" "$red_error" "$OPTARG" >&2
 			help 2
 	esac
 	noOpt=0
 done
-[[ "$noOpt" = 1 ]] && { echo "${lightred}ERROR:${normal} No argument passed." >&2; help 1; }
+[[ "$noOpt" = 1 ]] && { printf "%s No argument passed.\n" "$red_error" >&2; help 1; }
 shift "$(( OPTIND - 1 ))"
+printf "%s v%s\n" "$_script" "$_version"
 exit
