Added shift OPTIND to remove arguments after use.

diff --git a/iru-chrome b/iru-chrome
--- a/iru-chrome
+++ b/iru-chrome
@@ -27,8 +27,8 @@ fi
 ## Variables ##
 
 _script=$(basename "$0"); readonly _script
-readonly _version="0.3.13"
-readonly _updated="12 Oct 2023"
+readonly _version="0.3.14"
+readonly _updated="16 Oct 2023"
 readonly chrome_list="/etc/apt/sources.list.d/google-chrome.list"
 readonly keyring_dir="/usr/share/keyrings"
 readonly trusted_key="google-chrome.gpg"
@@ -51,9 +51,9 @@ install_chrome() {
   echo "source_list" | sudo tee "$chrome_list" > /dev/null
   sudo apt update
   if sudo apt-get install -y google-chrome-stable; then
-    leave "Google Chrome $(chrome_ver) successfully installed."
+    echo "Google Chrome $(chrome_ver) successfully installed."
   else
-    die "Google Chrome installation failed." 1
+    echo "Google Chrome installation failed." >&2
   fi
 }
 
@@ -64,13 +64,13 @@ purge_chrome() {
   # sudo apt-key del D38B4796 2>/dev/null #apt-key deprecated
   [[ -f "$chrome_list" ]] && sudo rm -v "$chrome_list"
   [[ -d "$HOME/google-chromme" ]] && rm -rf "$HOME/google-chromme"
-  leave "Google Chrome removed from this computer."
+  echo "Google Chrome removed from this computer."
 }
 
 update_chrome() {
   user_in_sudo
   sudo apt install google-chrome-stable
-  leave "Google Chrome updated to $(chrome_ver)."
+  echo "Google Chrome updated to $(chrome_ver)."
 }
 
 help() {
@@ -82,13 +82,13 @@ ${orange}OPTIONS:${normal}
   -i = Install Google Chrome
   -r = Remove Google Chrome
   -u = Update Google Chrome
+$_script v$_version ($_updated)
 END_HELP
   exit "$errcode"
 }
 
 ## Execution ##
 
-echo "$_script v$_version ($_updated)"
 echo "${orange}Installs Google Chrome${normal}"
 
 noOpt=1
@@ -118,3 +118,5 @@ while getopts "$optstr" opt; do
 	noOpt=0
 done
 [[ "$noOpt" = 1 ]] && { printf "%s No argument passed.\n" "$red_error" >&2; help 1; }
+shift "$(( OPTIND - 1 ))"
+leave "$_script v$_version ($_updated)"
