iru-fastfetch: added convert_compare() to convert version numbers to all digits and compare them

diff --git a/iru-fastfetch b/iru-fastfetch
--- a/iru-fastfetch
+++ b/iru-fastfetch
@@ -7,7 +7,7 @@
 # Author       : Copyright © 2024 Richard B. Romig, Mosfanet
 # Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
 # Created      : 02 May 2024
-# Last updated : 11 May 2026
+# Last updated : 02 Jun 2026
 # Comments     : .png logo does not work with Terminator.
 # TODO (Rick)  :
 # License      : GNU General Public License, version 2.0
@@ -26,12 +26,12 @@
 
 ## Load function library ##
 # shellcheck source=/home/rick/bin/functionlib
-source functionlib || { printf "\e[91mERROR:\e[0m Unable to source functionlib\n"; exit 1; }
+source ~/bin/functionlib || { printf "\e[91mERROR:\e[0m Unable to source functionlib\n"; exit 1; }
 
 ## Global Variables ##
 
 readonly script="${0##*/}"
-readonly version="3.20.26131"
+readonly version="4.0.26153"
 readonly gh_url="https://github.com/fastfetch-cli/fastfetch/releases"
 DOTS_PID=
 EC=0
@@ -40,7 +40,7 @@ EC=0
 
 help() {
 	local errcode="${1:-1}"
-	local -r updated="11 May 2026"
+	local -r updated="02 Jun 2026"
 	cat << _HELP_
 ${orange}$script${normal} $version ($updated)
 Installs, configures, removes, updates FastFetch
@@ -55,8 +55,9 @@ _HELP_
   exit "$errcode"
 }
 
-# shellcheck disable=SC2317 # Don't warn about unreachable commands in this function
+# Don't warn about unreachable commands in this function
 # ShellCheck may incorrectly believe that code is unreachable if it's invoked by variable name or in a trap.
+# shellcheck disable=SC2317
 cleanup() {
 	[[ -f "$TMP_FILE" ]] && rm "$TMP_FILE"
 	[[ -d "$TMP_DIR" ]] && rm -rf "$TMP_DIR"
@@ -64,6 +65,15 @@ cleanup() {
 
 ff_version() {
 	fastfetch --version-raw
+}
+
+convert_compare() {
+	local newVer="$1"
+	local curVer="$2"
+	local digitCur digitNew
+	digitNew=$(sed 's/^0*//' < <(tr -d . <<< "$newVer"))
+	digitCur=$(sed 's/^0*//;s/[-~+ud].*//' < <(tr -d . <<< "$curVer"))
+	(( digitNew > digitCur )) && return 0 || return 1
 }
 
 newest_version() {
@@ -80,13 +90,21 @@ compare_versions() {
   if [[ -z "$new_ver" ]]; then
     printf "%s No download available. Try again later." "$RED_ERROR" >&2
     EC="$E_DOWNLOAD"
-    return
-  elif [[ ! "$new_ver" > "$cur_ver" ]]; then
-		printf "%sFastFetch %s is the lastest version. No update required.%s\n" "$lightyellow" "$cur_ver" "$normal"
-		return
+  elif convert_compare "$new_ver" "$cur_ver"; then
+    printf "%sInstalled version of FastFetch is %s, updating to %s...%s\n" "$lightyellow" "$cur_ver" "$new_ver" "$normal"
+  else
+    printf "%s FastFetch %s is the current version. No update required.%s\n" "$lightyellow" "$cur_ver" "$normal"
 	fi
-	printf "%sThe installed version of FastFetch is %s, updating to %s...%s\n" "$lightyellow" "$cur_ver" "$new_ver" "$normal"
-	install_fastfetch "$new_ver"
+  # if [[ -z "$new_ver" ]]; then
+  #   printf "%s No download available. Try again later." "$RED_ERROR" >&2
+  #   EC="$E_DOWNLOAD"
+  #   return
+  # elif [[ ! "$new_ver" > "$cur_ver" ]]; then
+	# 	printf "%sFastFetch %s is the lastest version. No update required.%s\n" "$lightyellow" "$cur_ver" "$normal"
+	# 	return
+	# fi
+	# printf "%sThe installed version of FastFetch is %s, updating to %s...%s\n" "$lightyellow" "$cur_ver" "$new_ver" "$normal"
+	# install_fastfetch "$new_ver"
 }
 
 install_fastfetch(){
