iru-bat: convert_compare() - changed to compare numeric values instead of strings; updated local variablles

diff --git a/iru-bat b/iru-bat
--- a/iru-bat
+++ b/iru-bat
@@ -7,7 +7,8 @@
 # Author       : Copyright (C) 2022, Richard B. Romig, Mosfanet
 # Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
 # Created      : 09 Jan 2022
-# Updated      : 20 Jul 2026
+# Updated      : 23 Aug 2026
+# Version      : 7.8.26235
 # Comments     : Use install-batcat if distro version has same base version number as latest GitHub release.
 #              : Mint 22 installs version 0.24.0 with the Ubuntu version appended.
 #              : Debian 13 installs version 0.25.0 with the Debian version appended.
@@ -26,7 +27,6 @@
 # FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
 ###############################################################################
 
-## Source function library ##
 # shellcheck source=/home/rick/bin/functionlib.bash
 source ~/bin/functionlib.bash || { printf "\e[91mERROR:\e[0m Unable to source functionlib.bash\n"; exit 1; }
 
@@ -34,7 +34,7 @@ help() {
   local -r script="$1"
   local -r version="$2"
 	local -r errcode="${3:-1}"
-	local -r updated="13 Jul 2026"
+	local -r updated="23 Aug 2026"
 	cat << _HELP_
 ${orange}$script${normal} $version ($updated)
 Installs, updates, or removes the Bat utililty.
@@ -65,14 +65,14 @@ bat_version() {
 convert_compare() {
   local -r newVer="$1"
   local -r curVer="$2"
-  local newer="$FALSE"
+  local -i newer="$FALSE"
 	local new_arr=()
 	local cur_arr=()
   local -i index
 	IFS="." read -ra new_arr <<< "$newVer"
 	IFS="." read -ra cur_arr <<< "$curVer"
 	for (( index=0; index <=2; index++)) ; do
-		if [[ "${new_arr[index]}" > "${cur_arr[index]}" ]]; then
+    if (( "${new_arr[index]}" > "${cur_arr[index]}" )); then
       newer="$TRUE"
       break
     fi
@@ -82,6 +82,7 @@ convert_compare() {
 
 newest_version() {
   local -r gh_url="$1"
+  local new_ver
   wget -qO "$TMP_FILE" "$gh_url"
   new_ver=$(sed 's/^v//' < <(awk -F'/' '/download/ && /amd64.deb/ {print $6;exit}' "$TMP_FILE"))
   echo "$new_ver"
@@ -110,7 +111,7 @@ compare_versions() {
 install_bat() {
   local -r new_ver="$1"
   local -r gh_url="$2"
-  local new_pkg="bat_${new_ver}_amd64.deb"
+  local -r new_pkg="bat_${new_ver}_amd64.deb"
   if [[ -z "$new_ver" ]]; then
     printf "%s No download available. Try again later." "$RED_ERROR" >&2
     return "$E_DOWNLOAD"
@@ -163,7 +164,7 @@ bat_config() {
 
 main() {
   local -r  script="${0##*/}"
-  local -r version="7.7.26201"
+  local -r version="7.8.26235"
 	local -i exit_code=0
   local -r gh_url="https://github.com/sharkdp/bat/releases"
   local opt new_ver OPTARG OPTIND
@@ -213,7 +214,10 @@ main() {
     exit_code="$?"
 	  noOpt=0
   done
-  [[ "$noOpt" = 1 ]] && { printf "%s No argument passed.\n" "$RED_ERROR" >&2; help "$script" "$version" "$E_MISSING_ARG"; }
+	if (( noOpt == 1 )); then
+		printf "%s No argument passed.\n" "$RED_ERROR" >&2
+		help "$script" "$version" "$E_MISSING_ARG"
+	fi
   shift "$(( OPTIND - 1 ))"
 	over_line "$script $version"
   exit "$exit_code"
