iru-micro: replaced convert_compare() with same function from functionlib.bash

diff --git a/iru-micro b/iru-micro
--- a/iru-micro
+++ b/iru-micro
@@ -7,8 +7,8 @@
 # Author       : Copyright (C) 2022, Richard B. Romig, Mosfanet
 # Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
 # Created      : 10 Jan 2022
-# Updated      : 24 Aug 2026
-# Version      : 8.5.26236
+# Updated      : 08 Sep 2026
+# Version      : 8.6.26251
 # Comments     : Debian 13 & LMDE 7 installs version 2.0.14 from Debian repository
 #              : Debian 12, Ubuntu 24.04 & Mint 22 nstalls version 2.0.13 from repositories
 #              : iru-micro -u remove remove repo version and install latest from GitHub repository
@@ -33,207 +33,181 @@ help() {
 	local -r script="$1"
 	local -r version="$2"
 	local -ri errcode="${3:-1}"
-	local -r updated="24 Aug 2026"
-	cat << _HELP_
-${orange}$script${normal} $version ($updated)
-Installs, configures, updates, or removes the Micro CLI text editor.
+	local -r updated="08 Sep 2026"
+	cat <<- _HELP_
+	${orange}$script${normal} $version ($updated)
+	Installs, configures, updates, or removes the Micro CLI text editor.
 
-${green}Usage:${normal} $script [-hiru]
-${orange}Available options:${normal}
-  -c  Apply settings and bindings.
-  -h  Show this help message and exit.
-  -i  Installs the Micro CLI text editor.
-  -r  Removes the Micro CLI text editor from the system.
-  -u  Updates the Micro CLI text editor to the latest GitHub release.
+	${green}Usage:${normal} $script [-hiru]
+	${orange}Available options:${normal}
+	-c	Apply settings and bindings.
+	-h	Show this help message and exit.
+	-i	Installs the Micro CLI text editor.
+	-r	Removes the Micro CLI text editor from the system.
+	-u	Updates the Micro CLI text editor to the latest GitHub release.
 _HELP_
-  exit "$errcode"
-}
-
-check_dependencies() {
-  local packages=( git wget )
-  check_packages "${packages[@]}"
-  return 0
+	exit "$errcode"
 }
 
 micro_version() {
-  awk '/Version:/ {print $NF}' < <(micro -version)
-  return 0
-}
-
-convert_compare() {
-  local -r newVer="$1"
-  local -r curVer="$2"
-  local -i newer="$FALSE"
-	local new_arr=()
-	local cur_arr=()
-  local -i index
-	IFS="." read -ra new_arr <<< "$newVer"
-	IFS="." read -ra cur_arr <<< "$curVer"
-	for (( index=0; index <=2; index++)) ; do
-    if (( "${new_arr[index]}" > "${cur_arr[index]}" )); then
-      newer="$TRUE"
-      break
-    fi
-	done
-	return "$newer"
+	awk '/Version:/ {print $NF}' < <(micro -version)
+	return 0
 }
 
 newest_version() {
-  local -r gh_url="$1"
+	local -r gh_url="$1"
 	local new_ver
-  wget -qO "$TMP_FILE" "$gh_url"
-  new_ver=$(sed 's/^v//' < <(awk -F'/' '/download\/v/ {print $6;exit}' "$TMP_FILE"))
-  echo "$new_ver"
-  return 0
+	wget -qO "$TMP_FILE" "$gh_url"
+	new_ver=$(sed 's/^v//' < <(awk -F'/' '/download\/v/ {print $6;exit}' "$TMP_FILE"))
+	echo "$new_ver"
+	return 0
 }
 
 compare_versions() {
-  local -r new_ver="$1"
-  local -r gh_url="$2"
-  local cur_ver
-  cur_ver=$(micro_version)
-  printf "Comparing current and newest versions...\n"
-  if [[ -z "$new_ver" ]]; then
-    printf "%s No download available. Try again later." "$RED_ERROR" >&2
-    return "$E_DOWNLOAD"
-  elif convert_compare "$new_ver" "$cur_ver"; then
-    printf "%sInstalled version of Micro is %s, updating to %s...%s\n" "$lightyellow" "$cur_ver" "$new_ver" "$normal"
-    install_micro "$new_ver" "$gh_url"
-    return "$?"
-  else
-    printf "%sMicro %s is the current version. No update required.%s\n" "$lightyellow" "$cur_ver" "$normal"
-  fi
-  return 0
+	local -r new_ver="$1"
+	local -r gh_url="$2"
+	local cur_ver
+	cur_ver=$(micro_version)
+	printf "Comparing current and newest versions...\n"
+	if [[ -z "$new_ver" ]]; then
+		printf "%s No download available. Try again later." "$RED_ERROR" >&2
+		return "$E_DOWNLOAD"
+	elif convert_compare "$new_ver" "$cur_ver"; then
+		printf "%sInstalled version of Micro is %s, updating to %s...%s\n" "$lightyellow" "$cur_ver" "$new_ver" "$normal"
+		install_micro "$new_ver" "$gh_url"
+		return "$?"
+	else
+		printf "%sMicro %s is the current version. No update required.%s\n" "$lightyellow" "$cur_ver" "$normal"
+	fi
+	return 0
 }
 
 install_micro() {
-  local -r new_ver="$1"
-  local -r gh_url="$2"
-  local new_pkg="micro-${new_ver}-linux64.tar.gz"
-  if [[ -z "$new_ver" ]]; then
-    printf "%s No download available. Try again later." "$RED_ERROR" >&2
-    return "$E_DOWNLOAD"
-  fi
-  sudo_login 2
-  # if the repo verssion is installed, remove it.
-  installed micro && sudo apt-get remove -y micro
-  [[ -d /usr/share/micro/ ]] || sudo mkdir /usr/share/micro/
-  [[ -d /usr/share/doc/micro/ ]] || sudo mkdir /usr/share/doc/micro/
-  printf "Downloading Micro %s from the zyedidia GitHub repository..." "$new_ver"
-  dots "." &
-	DOTS_PID="$!"
-  wget -q -P "$TMP_DIR/" "$gh_url/download/v$new_ver/$new_pkg"
-	kill_dots
-  printf "Installing Micro %s...\n" "$new_ver"
-  tar -xzvf "$TMP_DIR/$new_pkg" -C "$TMP_DIR/"
-  sudo cp -v "$TMP_DIR/micro-$new_ver"/micro /usr/bin/
-  sudo cp -v "$TMP_DIR/micro-$new_ver"/micro.1 /usr/share/man/man1/
-  sudo cp -v "$TMP_DIR/micro-$new_ver"/micro.desktop /usr/share/applications/
-  sudo cp -v "$TMP_DIR/micro-$new_ver"/micro.svg /usr/share/micro/
-  sudo cp -v "$TMP_DIR/micro-$new_ver"/README.md /usr/share/doc/micro/
-  sudo cp -v "$TMP_DIR/micro-$new_ver"/LICENSE* /usr/share/doc/micro/
-  installed xclip || sudo apt-get install -y xclip
-  if [[ "$(micro_version)" != "$new_ver" ]]; then
-    printf "%s Micro installation failed.\n" "$RED_ERROR" >&2
-    return "$E_INSTALLATION"
+	local -r new_ver="$1"
+	local -r gh_url="$2"
+	local new_pkg="micro-${new_ver}-linux64.tar.gz"
+	if [[ -z "$new_ver" ]]; then
+		printf "%s No download available. Try again later." "$RED_ERROR" >&2
+		return "$E_DOWNLOAD"
 	fi
-  printf "Micro %s installed.\n" "$(micro_version)"
-  return 0
+	sudo_login 2
+	# if the repo verssion is installed, remove it.
+	installed micro && sudo apt-get remove -y micro
+	[[ -d /usr/share/micro/ ]] || sudo mkdir /usr/share/micro/
+	[[ -d /usr/share/doc/micro/ ]] || sudo mkdir /usr/share/doc/micro/
+	printf "Downloading Micro %s from the zyedidia GitHub repository..." "$new_ver"
+	dots "." &
+	DOTS_PID="$!"
+	wget -q -P "$TMP_DIR/" "$gh_url/download/v$new_ver/$new_pkg"
+	kill_dots
+	printf "Installing Micro %s...\n" "$new_ver"
+	tar -xzvf "$TMP_DIR/$new_pkg" -C "$TMP_DIR/"
+	sudo cp -v "$TMP_DIR/micro-$new_ver"/micro /usr/bin/
+	sudo cp -v "$TMP_DIR/micro-$new_ver"/micro.1 /usr/share/man/man1/
+	sudo cp -v "$TMP_DIR/micro-$new_ver"/micro.desktop /usr/share/applications/
+	sudo cp -v "$TMP_DIR/micro-$new_ver"/micro.svg /usr/share/micro/
+	sudo cp -v "$TMP_DIR/micro-$new_ver"/README.md /usr/share/doc/micro/
+	sudo cp -v "$TMP_DIR/micro-$new_ver"/LICENSE* /usr/share/doc/micro/
+	installed xclip || sudo apt-get install -y xclip
+	if [[ "$(micro_version)" != "$new_ver" ]]; then
+		printf "%s Micro installation failed.\n" "$RED_ERROR" >&2
+		return "$E_INSTALLATION"
+	fi
+	printf "Micro %s installed.\n" "$(micro_version)"
+	return 0
 }
 
 remove_micro() {
-  if ! exists micro; then
-    printf "Micro is not installed.\n" >&2
-    return "$E_NOT_DETECTED"
-  fi
-  sudo_login 2
-  printf "Removing the Micro CLI text editor...\n"
-  [[ -L  ~/.config/micro/settings.json ]] && unlink ~/.config/micro/settings.json
-  [[ -L  ~/.config/micro/bindings.json ]] && unlink ~/.config/micro/bindings.json
-  find ~/.config -type d -name micro -exec rm -rf {} \;
-  sudo rm -v /usr/bin/micro
-  sudo rm -rfv /usr/share/doc/micro
-  sudo find /usr/share -type f -name "micro." -exec rm -f {} ;\
-  printf "Micro and configuration files have been removed.\n"
-  return 0
+	if ! exists micro; then
+		printf "Micro is not installed.\n" >&2
+		return "$E_NOT_DETECTED"
+	fi
+	sudo_login 2
+	printf "Removing the Micro CLI text editor...\n"
+	[[ -L  ~/.config/micro/settings.json ]] && unlink ~/.config/micro/settings.json
+	[[ -L  ~/.config/micro/bindings.json ]] && unlink ~/.config/micro/bindings.json
+	find ~/.config -type d -name micro -exec rm -rf {} \;
+	sudo rm -v /usr/bin/micro
+	sudo rm -rfv /usr/share/doc/micro
+	sudo find /usr/share -type f -name "micro." -exec rm -f {} ;\
+	printf "Micro and configuration files have been removed.\n"
+	return 0
 }
 
 micro_configs() {
-  if ! exists micro; then
-    printf "Micro is not installed.\n" >&2
-    return "$E_NOT_DETECTED"
-  fi
-  printf "Applying Micro settings and bindings...\n"
-  [[ -d  ~/.config/micro ]] || mkdir -p  ~/.config/micro
+	if ! exists micro; then
+		printf "Micro is not installed.\n" >&2
+		return "$E_NOT_DETECTED"
+	fi
+	printf "Applying Micro settings and bindings...\n"
+	[[ -d  ~/.config/micro ]] || mkdir -p  ~/.config/micro
 	if [[ ! -d ~/Downloads/configs && ! -d ~/gitea/configs ]]; then
 		printf "%s Cloned repository not found!\n" "$RED_WARNING" >&2
 		return "$E_FILENOTFOUND"
 	fi
-  [[ -f  ~/.config/micro/settings.json ]] && rm ~/.config/micro/settings.json
-  [[ -f ~/.config/micro/bindings.json ]] && rm  ~/.config/micro/bindings.json
-  if [[ -d ~/gitea/configs ]]; then
-    ln -sv ~/gitea/configs/micro/settings.json  ~/.config/micro/settings.json
-    ln -sv ~/gitea/configs/micro/bindings.json  ~/.config/micro/bindings.json
-  elif [[ -d ~/Downloads/configs ]]; then
-    ln -sv ~/Downloads/configs/micro/settings.json  ~/.config/micro/settings.json
-    ln -sv ~/Downloads/configs/micro/bindings.json  ~/.config/micro/bindings.json
-  fi
-  micro -plugin install bookmark
-  printf "Micro setttings applied.\n"
-  return 0
+	[[ -f  ~/.config/micro/settings.json ]] && rm ~/.config/micro/settings.json
+	[[ -f ~/.config/micro/bindings.json ]] && rm  ~/.config/micro/bindings.json
+	if [[ -d ~/gitea/configs ]]; then
+		ln -sv ~/gitea/configs/micro/settings.json  ~/.config/micro/settings.json
+		ln -sv ~/gitea/configs/micro/bindings.json  ~/.config/micro/bindings.json
+	elif [[ -d ~/Downloads/configs ]]; then
+		ln -sv ~/Downloads/configs/micro/settings.json  ~/.config/micro/settings.json
+		ln -sv ~/Downloads/configs/micro/bindings.json  ~/.config/micro/bindings.json
+	fi
+	micro -plugin install bookmark
+	printf "Micro setttings applied.\n"
+	return 0
 }
 
 main() {
-  local -r script="${0##*/}"
-  local -r version="8.5.26236"
+	local -r script="${0##*/}"
+	local -r version="8.6.26251"
 	local -i exit_code=0
-  local -r gh_url="https://github.com/micro-editor/micro/releases"
-  local opt new_ver OPTARG OPTIND
-  local -i noOpt=1
-  local -r optstr=":chiru"
-  while getopts "$optstr" opt; do
-    case "$opt" in
-      c )
-        micro_configs ;;
-      h )
-        help "$script" "$version" 0 ;;
-      i )
-        if exists micro; then
-          printf "Micro %s is already installed.\n" "$(micro_version)" >&2
-        else
-          check_dependencies
-          create_tmp "dirfile"
-          new_ver="$(newest_version "$gh_url")"
-          printf "%sInstalling Micro version %s...%s\n" "$lightyellow" "$new_ver" "$normal"
-          install_micro "$new_ver" "$gh_url" && micro_configs
-        fi
-        ;;
-      r )
-        remove_micro ;;
-      u )
-        if exists micro; then
-          check_dependencies
-          create_tmp "dirfile"
-          new_ver="$(newest_version "$gh_url")"
-          compare_versions "$new_ver" "$gh_url"
-        else
-          printf "Micro is not installed.\n" >&2
-        fi
-        ;;
-      ? )
+	local -r gh_url="https://github.com/micro-editor/micro/releases"
+	local -i noOpt=1
+	local -r optstr=":chiru"
+	local opt OPTARG OPTIND new_ver
+	while getopts "$optstr" opt; do
+		case "$opt" in
+			c )
+				micro_configs ;;
+			h )
+				help "$script" "$version" 0 ;;
+			i )
+				if exists micro; then
+					printf "Micro %s is already installed.\n" "$(micro_version)" >&2
+				else
+					check_package wget
+					create_tmp "dirfile"
+					new_ver="$(newest_version "$gh_url")"
+					printf "%sInstalling Micro version %s...%s\n" "$lightyellow" "$new_ver" "$normal"
+					install_micro "$new_ver" "$gh_url" && micro_configs
+				fi ;;
+			r )
+				remove_micro ;;
+			u )
+				if exists micro; then
+					check_package wget
+					create_tmp "dirfile"
+					new_ver="$(newest_version "$gh_url")"
+					compare_versions "$new_ver" "$gh_url"
+				else
+					printf "Micro is not installed.\n" >&2
+				fi ;;
+			? )
 				printf "%s Invalid option -%s\n" "$RED_ERROR" "$OPTARG" >&2
-        help "$script" "$version" "$E_INVALID_ARG"
-    esac
-    exit_code="$?"
-    noOpt=0
-  done
+				help "$script" "$version" "$E_INVALID_ARG"
+		esac
+		exit_code="$?"
+		noOpt=0
+	done
 	if (( noOpt == 1 )); then
 		printf "%s No argument passed.\n" "$RED_ERROR" >&2
 		help "$script" "$version" "$E_MISSING_ARG"
 	fi
-  shift "$(( OPTIND - 1 ))"
-  over_line "$script $version"
-  exit "$exit_code"
+	shift "$(( OPTIND - 1 ))"
+	over_line "$script $version"
+	exit "$exit_code"
 }
 
 main "$@"
