iru-yt-dlp - getopts in main(); updated local variables; set up symbolic link to binary version in install_ytdlp(); added ytdlp_deb() & ytdlp_bin()

diff --git a/iru-yt-dlp b/iru-yt-dlp
--- a/iru-yt-dlp
+++ b/iru-yt-dlp
@@ -7,7 +7,7 @@
 # Author       : Copyright (C) 2023, Richard B. Romig, LudditeGeek@Mosfanet
 # Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
 # Created      : 20 Jun 2023
-# Updated      : 22 Jun 2024
+# Updated      : 02 Oct 2024
 # Comments     : Removes distro repo version if installed.
 # TODO (Rick)  :
 # License      : GNU General Public License, version 2.0
@@ -25,19 +25,17 @@ else
   exit 1
 fi
 
+set -eu
+
 ## Global Variables ##
 
-_script=$(basename "$0"); readonly _script
-readonly _version="1.5.24174"
-readonly _updated="22 Jun 2024"
-readonly ytdlp_prg="yt-dlp"
+script=$(basename "$0"); readonly script
+readonly version="1.6.24276"
 readonly update_script="z-ytdlp-update"
 readonly sed_file="ytdlp-uplog.sed"
-readonly script_dir="$HOME/bin"
-readonly sed_dir="$HOME/bin/files"
-readonly ytdlp_location="/usr/local/bin"
-readonly sed_location="/usr/share/misc"
-readonly cron_location="/etc/cron.daily"
+readonly bin_loc="/usr/local/bin"
+readonly sed_loc="/usr/share/misc"
+readonly cron_loc="/etc/cron.daily"
 
 ## Functions ##
 
@@ -46,73 +44,87 @@ check_dependencies() {
   check_packages "${packages[@]}"
 }
 
+ytdlp_deb() {
+	[[ -f /usr/bin/yt-dlp ]] && return "$TRUE" || return "$FALSE"
+}
+
+ytdlp_bin() {
+	[[ -f /usr/local/bin/yt-dlp ]] && return "$TRUE" || return "$FALSE"
+}
+
 ytdlp_version() {
-	"$ytdlp_location/$ytdlp_prg" --version
+	"$bin_loc/yt-dlp" --version
 }
 
 update_ytdlp() {
 	printf "Updating yt-dlp ...\n"
-	"$ytdlp_location/$ytdlp_prg" --update
+	"$bin_loc/yt-dlp" --update
 }
 
 install_ytdlp() {
-  local url="https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp"
-	printf "Installing %s, and update scripts...\n" "$ytdlp_prg"
-  sudo curl -# -L "$url" -o "$ytdlp_location/$ytdlp_prg"
+  local script_dir sed_dir url
+	url="https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp"
+	script_dir="$HOME/bin"
+	sed_dir="$HOME/bin/files"
+	printf "Installing yt-dlp, and update scripts...\n"
+  sudo curl -# -L "$url" -o "$bin_loc/yt-dlp"
   [[ -x /usr/bin/python3 ]] && sudo ln -s /usr/bin/python3 /usr/bin/python
-  sudo chmod a+rx "$ytdlp_location/$ytdlp_prg"
+  sudo chmod a+rx "$bin_loc/yt-dlp"
   # Copies update & log cleanup scripts
-  [[ -x "$script_dir/$update_script" ]] && sudo cp -v "$script_dir/$update_script" "$cron_location/"
-  [[ -f "$sed_dir/$sed_file" ]] && sudo cp -v "$sed_dir/$sed_file" "$sed_location"
-  printf "%s v%s installed.\n" "$ytdlp_prg" "$(ytdlp_version)"
+  [[ -x "$script_dir/$update_script" ]] && sudo cp -v "$script_dir/$update_script" "$cron_loc/"
+  [[ -f "$sed_dir/$sed_file" ]] && sudo cp -v "$sed_dir/$sed_file" "$sed_loc"
+	ln -s /usr/local/bin/yt-dlp ~/.local/bin/yt-dlp
+  printf "%s v%s installed.\n" "yt-dlp" "$(ytdlp_version)"
 }
 
 remove_repo_ver() {
+	local deb_version
+	deb_version=$(dpkg -l yt-dlp | awk '/ii/ {print $3}' | sed 's/[+-].*//')
   # Purges repo version of yt-dlp & removes orphaned dependencies
-	printf "%s v%s installed distro repos. Removing this version.\n" "$ytdlp_prg" "$(dpkg -l | awk '$2 == "yt-dlp" {print $3}' | sed 's/[+-].*//')"
-  sudo apt-get purge -yyq yt-dlp
-  sudo apt-get autoremove -yyq
-  printf "Repository version of %s removed from the system.\n" "$ytdlp_prg"
+	printf "yt-dlp v%s installed distro repos. Removing this version.\n" "$deb_version"
+  sudo apt-get purge -y yt-dlp
+  sudo apt-get autoremove -y
+  printf "Repository version of yt-dlp removed from the system.\n"
 }
 
 remove_ytdlp() {
   # Removes the yt-dl.org version
-  printf "Removing %s v%s...\n" "$ytdlp_prg" "$(ytdlp_version)"
-  sudo rm "$ytdlp_location/$ytdlp_prg"
+  printf "Removing yt-dlp v%s...\n" "$(ytdlp_version)"
+  sudo rm "$bin_loc/yt-dlp"
   remove_configs
   remove_updater
   remove_logs
-	printf "ytdlp.org version of %s removed.\n" "$ytdlp_prg"
+	printf "ytdlp.org version of yt-dlp removed.\n"
 }
 
 remove_configs() {
   # Remove yt-dl.org configuration file, if it exists
   if [[ -d "$HOME/.config/yt-dlp" ]]; then
-    printf "Removing user %s configuration file...\n" "$ytdlp_prg"
+    printf "Removing user yt-dlp configuration file...\n"
     rm -rf "$HOME/.config/yt-dlp"
-    printf "User %s configuration file removed.\n" "$ytdlp_prg"
+    printf "User yt-dlp configuration file removed.\n"
   else
-    printf "No user %s configuration file found.\n" "$ytdlp_prg"
+    printf "No user yt-dlp configuration file found.\n"
   fi
   # Remove global configuration file, if it exists
   if [[ -f "/etc/yt-dlp.conf" ]]; then
-    printf "Removing global %s configuration file...\n" "$ytdlp_prg"
+    printf "Removing global yt-dlp configuration file...\n"
     sudo rm "/etc/yt-dlp.conf"
-    printf "Global %s configuration file removed.\n" "$ytdlp_prg"
+    printf "Global yt-dlp configuration file removed.\n"
   else
-    printf "No global %s configuration file found.\n" "$ytdlp_prg"
+    printf "No global yt-dlp configuration file found.\n"
   fi
 }
 
 remove_updater() {
-	if [[ -f "$sed_location/$sed_file" ]]; then
-		sudo rm "$sed_location/$sed_file"
+	if [[ -f "$sed_loc/$sed_file" ]]; then
+		sudo rm "$sed_loc/$sed_file"
 		printf "%s removed.\n" "$sed_file"
 	else
 		printf "%s not found.\n"  "$sed_file"
 	fi
-	if [[ -x "$cron_location/$update_script" ]]; then
-		sudo rm "$cron_location/$update_script"
+	if [[ -x "$cron_loc/$update_script" ]]; then
+		sudo rm "$cron_loc/$update_script"
   	printf "%s script removed.\n" "$update_script"
 	else
 		printf "%s script not found.\n" "$update_script"
@@ -124,37 +136,39 @@ remove_logs() {
   # Remove update log file if it exists
   if [[ -f "$log_location" ]]; then
     sudo rm "$log_location"
-    printf "%s update log file removed.\n" "$ytdlp_prg"
+    printf "yt-dlp update log file removed.\n"
   else
-    printf "No %s log file found.\n" "$ytdlp_prg"
+    printf "No yt-dlp log file found.\n"
   fi
 }
 
 help() {
-	local errcode="${1:-2}"
-	cat << END_HELP
-${orange}$_script${normal} $_version ($_updated)
+  local errcode updated
+	errcode="${1:-2}"
+	updated="02 Oct 2024"
+	cat << _HELP_
+${orange}$script${normal} $version ($updated)
 Installs, removes, updates YouTube-dlp.
 
-${green}Usage:${normal} $_script [OPTION]
+${green}Usage:${normal} $script [OPTION]
 ${orange}Available options:${normal}
 	-h 	Display help
-	-i 	Install yt-dlp
-	-r 	Remove yt-dlp
-	-u 	Update yt-dlp
+	-i 	Install yt-dlp (binary)
+	-r 	Remove yt-dlp (binary)
+	-u 	Update yt-dlp (binary)
 	-x	Remove yt-dlp (repo version)
-END_HELP
+_HELP_
   exit "$errcode"
 }
 
 install_intro() {
-  cat << END_INTRO
+  cat << _INTRO_
 Installs yt-dlp from yt-dl.org to /usr/local/bin along with an update
 script that runs as a daily anacron job which saves the results to a log
 file at /var/log/ytdlpup.log. A sed file to cleanup and format the log file
 is installed at /usr/share/misc/ytdlpuplog.sed
 If the version from the distro's repostitory is installed, it will be removed.
-END_INTRO
+_INTRO_
 }
 
 remove_intro() {
@@ -165,48 +179,53 @@ from the yt-dl downloads page.
 END_INTRO
 }
 
+main() {
+  local noOpt opt optstr
+	noOpt=1
+	optstr=":hirux"
+	while getopts "$optstr" opt; do
+		case "$opt" in
+			h )
+				help 0
+			;;
+			i )
+				ytdlp_bin && leave "yt-dlp $(ytdlp_version) already installed."
+				sudo_login 2
+				install_intro
+				check_dependencies
+				ytdlp_deb && remove_repo_ver
+				install_ytdlp
+			;;
+			r )
+				remove_intro
+				ytdlp_deb && remove_repo_ver
+				ytdlp_bin || leave "yt-dlp is not installed."
+				sudo_login 2
+				remove_ytdlp
+			;;
+			u )
+				ytdlp_bin || leave "yt-dlp is not installed."
+				sudo_login 2
+				update_ytdlp
+			;;
+			x )
+				ytdlp_deb || leave "The repo version of yt-dlp is not installed."
+				printf "Removing %s installed from the distribution repository.\n" "yt-dlp"
+				sudo_login 2
+				remove_repo_ver
+			;;
+			? )
+				printf "%s Invalid option -%s\n" "$RED_ERROR" "$OPTARG" >&2
+				help 2
+		esac
+		noOpt=0
+	done
+	[[ "$noOpt" = 1 ]] && { printf "%s No argument passed.\n" "$RED_ERROR" >&2; help 1; }
+	shift "$(( OPTIND - 1 ))"
+	box "$script v$version"
+	exit
+}
+
 ## Execution ##
 
-noOpt=1
-optstr=":hirux"
-while getopts "$optstr" opt; do
-	case "$opt" in
-		h )
-			help 0
-		;;
-		i )
-			[[ -f "$ytdlp_location/$ytdlp_prg" ]] && leave "$ytdlp_prg $(ytdlp_version) already installed."
-			sudo_login 2
-			install_intro
-			check_dependencies
-			dpkg -l | grep -qw yt-dlp && remove_repo_ver
-			install_ytdlp
-		;;
-		r )
-			remove_intro
-			dpkg -l | grep -qw yt-dlp && remove_repo_ver
-			[[ -f "$ytdlp_location/$ytdlp_prg" ]] || leave "$ytdlp_prg $(ytdlp_version) is not installed."
-			sudo_login 2
-			remove_ytdlp
-		;;
-		u )
-			[[ -f "$ytdlp_location/$ytdlp_prg" ]] || leave "$ytdlp_prg $(ytdlp_version) is not installed."
-			sudo_login 2
-			update_ytdlp
-		;;
-		x )
-			dpkg -l | grep -qw yt-dlp || leave "The repo version of $ytdlp_prg is not installed."
-			printf "Removing %s installed from the distribution repository.\n" "$ytdlp_prg"
-			sudo_login 2
-			remove_repo_ver
-		;;
-		? )
-			printf "%s Invalid option -%s\n" "$red_error" "$OPTARG" >&2
-			help 2
-	esac
-	noOpt=0
-done
-[[ "$noOpt" = 1 ]] && { printf "%s No argument passed.\n" "$red_error" >&2; help 1; }
-shift "$(( OPTIND - 1 ))"
-box "$_script v$_version"
-exit
+main "$@"
