iru-vscodium: added convert_compare() to convert version numbers to all digits and compare them

diff --git a/iru-vscodium b/iru-vscodium
--- a/iru-vscodium
+++ b/iru-vscodium
@@ -7,7 +7,7 @@
 # Author       : Copyright (C) 2022, Richard B. Romig, Mosfanet
 # Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
 # Created      : 16 Jul 2022
-# Updated      : 17 Apr 2026
+# Updated      : 02 Jun 2026
 # Comments     :
 # TODO (Rick)  :
 # License      : GNU General Public License, version 2.0
@@ -31,7 +31,7 @@ source functionlib || { printf "\e[91mERROR:\e[0m Unable to source functionlib\n
 ## Global Variables ##
 
 readonly script="${0##*/}"
-readonly version="3.8.26107"
+readonly version="4.0.26153"
 readonly gh_url="https://github.com/VSCodium/vscodium/releases"
 DOTS_PID=
 EC=0
@@ -40,7 +40,7 @@ EC=0
 
 help() {
 	local errcode="${1:-1}"
-	local updated="17 Apr 2026"
+	local updated="02 Jun 2026"
 	cat << _HELP_
 ${orange}$script${normal} $version ($updated)
 Installs, configures, updates,  removes the VSCodium editor.
@@ -63,7 +63,16 @@ cleanup() {
 }
 
 codium_version() {
-	head -n1 <(codium --version)
+	head -n1 < <(codium --version)
+}
+
+convert_compare() {
+	local newVer="$1"
+	local curVer="$2"
+	local digitCur digitNew
+	digitNew=$(sed 's/^0*//' < <(tr -d . <<< "$newVer"))
+	digitCur=$(sed 's/^0*//;s/[-~+ud].*//' < <(tr -d . <<< "$curVer"))
+	(( digitNew > digitCur )) && return 0 || return 1
 }
 
 newest_version() {
@@ -76,17 +85,25 @@ newest_version() {
 compare_versions() {
   local new_ver="$1"
   local cur_ver
-  cur_ver=$(dpkg -l codium 2>/dev/null | awk '/ii/ {print $3}' | sed 's/[~+-].*//')
+  cur_ver=$(codium_version)
   if [[ -z "$new_ver" ]]; then
-    printf "%s No download available. Try again later.\n" "$RED_ERROR" >&2
+    printf "%s No download available. Try again later." "$RED_ERROR" >&2
     EC="$E_DOWNLOAD"
-    return
-  elif [[ ! "$new_ver" > "$cur_ver" ]]; then
-    printf "%sVSCodium %s is the latest version. No update required.%s\n" "$lightyellow" "$cur_ver" "$normal"
-    return
+  elif convert_compare "$new_ver" "$cur_ver"; then
+    printf "%sInstalled version of VSCodium is %s, updating to %s...%s\n" "$lightyellow" "$cur_ver" "$new_ver" "$normal"
+  else
+    printf "%sVSCodium %s is the current version. No update required.%s\n" "$lightyellow" "$cur_ver" "$normal"
   fi
-  printf "%sInstalled version of VSCodium is %s, updating to %s...%s\n" "$lightyellow" "$cur_ver" "$new_ver" "$normal"
-  install_vscodium "$new_ver"
+  # if [[ -z "$new_ver" ]]; then
+  #   printf "%s No download available. Try again later.\n" "$RED_ERROR" >&2
+  #   EC="$E_DOWNLOAD"
+  #   return
+  # elif [[ ! "$new_ver" > "$cur_ver" ]]; then
+  #   printf "%sVSCodium %s is the latest version. No update required.%s\n" "$lightyellow" "$cur_ver" "$normal"
+  #   return
+  # fi
+  # printf "%sInstalled version of VSCodium is %s, updating to %s...%s\n" "$lightyellow" "$cur_ver" "$new_ver" "$normal"
+  # install_vscodium "$new_ver"
 }
 
 install_vscodium() {
