iru-vscodium: updated convert_compare() and newest_version

diff --git a/iru-vscodium b/iru-vscodium
--- a/iru-vscodium
+++ b/iru-vscodium
@@ -7,7 +7,7 @@
 # Author       : Copyright (C) 2022, Richard B. Romig, Mosfanet
 # Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
 # Created      : 16 Jul 2022
-# Updated      : 03 Jun 2026
+# Updated      : 04 Jun 2026
 # Comments     :
 # TODO (Rick)  :
 # License      : GNU General Public License, version 2.0
@@ -26,12 +26,12 @@
 
 ## Load function library ##
 # shellcheck source=/home/rick/bin/functionlib
-source functionlib || { printf "\e[91mERROR:\e[0m Unable to source functionlib\n"; exit 1; }
+source ~/bin/functionlib || { printf "\e[91mERROR:\e[0m Unable to source functionlib\n"; exit 1; }
 
 ## Global Variables ##
 
 readonly script="${0##*/}"
-readonly version="4.1.26154"
+readonly version="4.2.26155"
 readonly gh_url="https://github.com/VSCodium/vscodium/releases"
 DOTS_PID=
 EC=0
@@ -40,7 +40,7 @@ EC=0
 
 help() {
 	local errcode="${1:-1}"
-	local updated="03 Jun 2026"
+	local updated="04 Jun 2026"
 	cat << _HELP_
 ${orange}$script${normal} $version ($updated)
 Installs, configures, updates,  removes the VSCodium editor.
@@ -72,13 +72,13 @@ convert_compare() {
 	local digitCur digitNew
 	digitNew=$(sed 's/^0*//' < <(tr -d . <<< "$newVer"))
 	digitCur=$(sed 's/^0*//;s/[-~+ud].*//' < <(tr -d . <<< "$curVer"))
-	(( digitNew > digitCur )) && return 0 || return 1
+	(( digitNew > digitCur )) && return "$TRUE" || return "$FALSE"
 }
 
 newest_version() {
   local new_ver
   wget -qO "$TMP_FILE" "$gh_url"
-  new_ver=$(grep -Ev 'beta|-rc' <(awk -F'/' '/download/ && /amd64.deb/ {print $8;exit}' "$TMP_FILE") | sed 's/^v//')
+  new_ver=$(sed 's/^v//' < <(awk -F'/' '/download/ && /amd64.deb/ {print $8;exit}' "$TMP_FILE"))
   echo "$new_ver"
 }
 
