iru-marktext - getopts in main(); updated help()

diff --git a/iru-marktext b/iru-marktext
--- a/iru-marktext
+++ b/iru-marktext
@@ -7,7 +7,7 @@
 # Author       : Copyright (C) 2022, Richard B. Romig, Mosfanet
 # Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
 # Created      : 10 Jan 2022
-# Updated      : 24 Aug 2024
+# Updated      : 02 Oct 2024
 # Comments     :
 # TODO (Rick)  :
 # License      : GNU General Public License, version 2.0
@@ -25,11 +25,10 @@ else
   exit 1
 fi
 
-## Variables ##
+## Global Variables ##
 
-_script=$(basename "$0"); readonly _script
-readonly _version="4.5.24237"
-readonly _updated="24 Aug  2024"
+script=$(basename "$0"); readonly script
+readonly version="4.6.24276"
 readonly gh_url="https://github.com/marktext/marktext/releases"
 readonly cfg_dir="$HOME/.config/marktext"
 
@@ -106,12 +105,14 @@ dl_preferences() {
 }
 
 help() {
-  local errcode="${1:-2}"
-  cat << END_HELP
-${orange}$_script${normal} $_version ($_updated)
+  local errcode updated
+	errcode="${1:-2}"
+	updated="02 Oct 2024"
+	cat << _HELP_
+${orange}$script${normal} $version ($updated)
 Installs, configures, updates, removes the Mark Text markdown editor.
 
-${green}Usage:${normal} $_script [OPTION]
+${green}Usage:${normal} $script [OPTION]
 
 ${orange}Available options:${normal}
   -c  Applies Marktext preferences.
@@ -119,57 +120,62 @@ ${orange}Available options:${normal}
   -i  Installs the Marktext markdown editor.
   -r  Removes the Marktext markdown editor from the system.
   -u  Updates the Marktext markdown editor to the latest version.
-END_HELP
+_HELP_
   exit "$errcode"
+}
+
+main() {
+  local noOpt opt optstr
+  noOpt=1
+  optstr=":chiru"
+  while getopts "$optstr" opt; do
+    case "$opt" in
+      c )
+        exists marktext || leave "Marktext is not installed."
+        dl_preferences
+      ;;
+      h )
+        help 0
+      ;;
+      i )
+        exists marktext && leave "Marktext $(marktext_version) is already installed."
+        tmp_file=$(mktemp) || die "Failed to create temporary file." 1
+        tmp_dir=$(mktemp -d) || die "Failed to create temporary directory." 1
+        trap cleanup EXIT
+        sudo_login 2
+        check_dependencies
+        new_ver="$(newest_version)"
+        echo "${lightyellow}Installing MarkText version $new_ver...${normal}"
+        install_marktext
+      ;;
+      r )
+        exists marktext || leave "Marktext is not installed."
+        sudo_login 2
+        remove_marktext
+      ;;
+      u )
+        exists marktext || leave "Marktext is not installed."
+        tmp_file=$(mktemp) || die "Failed to create temporary file." 1
+        tmp_dir=$(mktemp -d) || die "Failed to create temporary directory." 1
+        trap cleanup EXIT
+        sudo_login 2
+        check_dependencies
+        new_ver="$(newest_version)"
+        [[ "$new_ver" ]] || die "No download available. Try again later." 1
+        compare_versions
+      ;;
+      ? )
+				printf "%s Invalid option -%s\n" "$RED_ERROR" "$OPTARG" >&2
+        help 2
+    esac
+	  noOpt=0
+  done
+  [[ "$noOpt" = 1 ]] && { printf "%s No argument passed.\n" "$RED_ERROR" >&2; help 1; }
+  shift "$(( OPTIND - 1 ))"
+  box "$script v$version"
+  exit
 }
 
 ## Execution ##
 
-noOpt=1
-optstr=":chiru"
-while getopts "$optstr" opt; do
-  case "$opt" in
-    c )
-      exists marktext || leave "Marktext is not installed."
-      dl_preferences
-    ;;
-    h )
-      help 0
-    ;;
-    i )
-      exists marktext && leave "Marktext $(marktext_version) is already installed."
-      tmp_file=$(mktemp) || die "Failed to create temporary file." 1
-      tmp_dir=$(mktemp -d) || die "Failed to create temporary directory." 1
-      trap cleanup EXIT
-      sudo_login 2
-      check_dependencies
-      new_ver="$(newest_version)"
-      echo "${lightyellow}Installing MarkText version $new_ver...${normal}"
-      install_marktext
-    ;;
-    r )
-      exists marktext || leave "Marktext is not installed."
-      sudo_login 2
-      remove_marktext
-    ;;
-    u )
-      exists marktext || leave "Marktext is not installed."
-      tmp_file=$(mktemp) || die "Failed to create temporary file." 1
-      tmp_dir=$(mktemp -d) || die "Failed to create temporary directory." 1
-      trap cleanup EXIT
-      sudo_login 2
-      check_dependencies
-      new_ver="$(newest_version)"
-      [[ "$new_ver" ]] || die "No download available. Try again later." 1
-      compare_versions
-    ;;
-    ? )
-      echo "$red_error Invalid option -${OPTARG}" >&2
-      help 2
-  esac
-	noOpt=0
-done
-[[ "$noOpt" = 1 ]] && { printf "%s No argument passed.\n" "$red_error" >&2; help 1; }
-shift "$(( OPTIND - 1 ))"
-box "$_script v$_version"
-exit
+main "$@"
