iru-marktext: updated error checking

diff --git a/iru-marktext b/iru-marktext
--- a/iru-marktext
+++ b/iru-marktext
@@ -7,7 +7,7 @@
 # Author       : Copyright (C) 2022, Richard B. Romig, Mosfanet
 # Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
 # Created      : 10 Jan 2022
-# Updated      : 15 Jan 2026
+# Updated      : 04 Feb 2026
 # Comments     :
 # TODO (Rick)  :
 # License      : GNU General Public License, version 2.0
@@ -33,21 +33,22 @@ if [[ -x "$HOME/bin/functionlib" ]]; then
   source "$HOME/bin/functionlib"
 else
   printf "\e[91mERROR:\e[0m functionlib not found!\n" >&2
-  exit 1
+  exit 81
 fi
 
 ## Global Variables ##
 
 readonly script="${0##*/}"
-readonly version="4.22.26015"
+readonly version="4.23.26035"
 readonly gh_url="https://github.com/marktext/marktext/releases"
 DOTS_PID=
+EC=0
 
 ## Functions ##
 
 help() {
-	local errcode="${1:-2}"
-	local -r updated="15 Jan 2026"
+	local errcode="${1:-1}"
+	local -r updated="04 Feb 2026"
 	cat << _HELP_
 ${orange}$script${normal} $version ($updated)
 Installs, configures, updates, removes the Mark Text markdown editor.
@@ -76,16 +77,17 @@ marktext_version() {
 newest_version() {
   local new_ver
   wget -qO "$tmp_file" "$gh_url"
-  new_ver=$(awk -F'/' '/download/ && /amd64.deb/ {print $6;exit}' "$tmp_file" | grep -Ev 'beta|-rc' | sed 's/^v//')
+  new_ver=$(grep -Ev 'beta|-rc' <(awk -F'/' '/download/ && /amd64.deb/ {print $6;exit}' "$tmp_file") | sed 's/^v//')
   echo "$new_ver"
 }
 
 compare_versions() {
-  local cur_ver new_ver
-  new_ver="$1"
+	local new_ver="$1"
+	local cur_ver
   cur_ver=$(marktext_version)
   if [[ -z "$new_ver" ]]; then
-    printf "No download available. Try again later.\n" >&2
+    printf "%s No download available. Try again later." "$RED_ERROR" >&2
+    EC="$E_DOWNLOAD"
     return
   elif [[ ! "$new_ver" > "$cur_ver" ]]; then
     printf "%sMarktext %s is the latest version. No update required.%s\n" "$lightyellow" "$cur_ver" "$normal"
@@ -98,7 +100,11 @@ compare_versions() {
 install_marktext() {
   local new_ver="$1"
   local -r new_pkg="marktext-amd64.deb"
-  [[ -z "$new_ver" ]] && die "No download available. Try again later." 1
+  if [[ -z "$new_ver" ]]; then
+    printf "%s No download available. Try again later." "$RED_ERROR" >&2
+    EC="$E_DOWNLOAD"
+    return
+  fi
   printf "Downloading Mark Text markdown editor (v %s) from the marktext GitHub repository..." "$new_ver"
   dots "." &
   DOTS_PID="$!"
@@ -108,6 +114,11 @@ install_marktext() {
   printf "Installing Mark Text %s...\n" "$new_ver"
 	sudo dpkg -i "$tmp_dir/$new_pkg"; sudo apt-get install --fix-broken
   exists markktext || die "Marktext installation failed!" 1
+  if grep -q '^ii' <(dpkg -l markktext >/dev/null 2>&1); then
+    printf "%s Marktext installation failed.\n" "$RED_ERROR" >&2
+    EC="$E_INSTALLATION"
+    return
+	fi
   printf "Mark Text %s installed.\n" "$(marktext_version)"
 }
 
@@ -121,9 +132,11 @@ remove_marktext() {
 }
 
 marktext_config() {
+  [[ "$EC" -ne 0 ]] && return
   printf "Applying MarkText preferences...\n"
 	if [[ ! -d ~/Downloads/configs && ! -d ~/gitea/configs ]]; then
 		printf "%s Cloned repository not found!\n" "$RED_WARNING" >&2
+    EC="$E_FILENOTFOUND"
 		return
 	fi
 	[[ -d ~/.config/config_dir ]] || mkdir -p ~/.config/config_dir
@@ -147,8 +160,8 @@ main() {
         if exists marktext; then
           printf "Marktext %s is already installed.\n" "$(marktext_version)" >&2
         else
-          tmp_file=$(mktemp) || die "Failed to create temporary file." 1
-          tmp_dir=$(mktemp -d) || die "Failed to create temporary directory." 1
+					tmp_file=$(mktemp) || die "Failed to create temporary file." "$E_TEMP_FILE"
+					tmp_dir=$(mktemp -d) || die "Failed to create temporary directory." "$E_TEMP_DIR"
           trap cleanup EXIT
           new_ver="$(newest_version)"
           printf "%sInstalling MarkText version %s...%s\n" "$lightyellow" "$new_ver" "$normal"
@@ -165,8 +178,8 @@ main() {
         ;;
       u )
         if exists marktext; then
-          tmp_file=$(mktemp) || die "Failed to create temporary file." 1
-          tmp_dir=$(mktemp -d) || die "Failed to create temporary directory." 1
+					tmp_file=$(mktemp) || die "Failed to create temporary file." "$E_TEMP_FILE"
+					tmp_dir=$(mktemp -d) || die "Failed to create temporary directory." "$E_TEMP_DIR"
           trap cleanup EXIT
 					printf "Marktext: Comparing current and newest versions...\n"
           new_ver="$(newest_version)"
@@ -177,14 +190,14 @@ main() {
         ;;
       ? )
 				printf "%s Invalid option -%s\n" "$RED_ERROR" "$OPTARG" >&2
-        help 2
+        help "$E_INVALID_ARG"
     esac
 	  noOpt=0
   done
-  [[ "$noOpt" = 1 ]] && { printf "%s No argument passed.\n" "$RED_ERROR" >&2; help 1; }
+  [[ "$noOpt" = 1 ]] && { printf "%s No argument passed.\n" "$RED_ERROR" >&2; help "$E_MISSING_ARG"; }
   shift "$(( OPTIND - 1 ))"
   over_line "$script $version"
-  exit
+  exit "$EC"
 }
 
 ## Execution ##
