iru-fastfetch: updated help(); main(): reorganized getopts loop.

diff --git a/iru-fastfetch b/iru-fastfetch
--- a/iru-fastfetch
+++ b/iru-fastfetch
@@ -7,7 +7,7 @@
 # Author       : Copyright © 2024 Richard B. Romig, Mosfanet
 # Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
 # Created      : 02 May 2024
-# Last updated : 24 June 2025
+# Last updated : 27 June 2025
 # Comments     : Fastfetch config.jsonc does not work with Terminator.
 # TODO (Rick)  :
 # License      : GNU General Public License, version 2.0
@@ -30,27 +30,25 @@ set -eu
 ## Global Variables ##
 
 readonly script="${0##*/}"
-readonly version="2.6.25175"
+readonly version="2.6.25178"
 readonly gh_url="https://github.com/fastfetch-cli/fastfetch/releases"
 
 ## Functions ##
 
 help() {
-  local errcode updated
-	errcode="${1:-2}"
-	updated="24 June 2025"
+	local errcode="${1:-2}"
+	local -r updated="27 Jun 2025"
 	cat << _HELP_
 ${orange}$script${normal} $version ($updated)
 Installs, configures, removes, updates FastFetch
 
-${green}Usage:${normal} $script [OPTION]
+${green}Usage:${normal} $script [-h] [-i] [-r] [-u]
 
 ${orange}Available options:${normal}
-  -c  Apply Fastretch configuration and logo
   -h  Show this help message and exit
   -i  Install Fastfetch
   -r  Remove Fastfetch
-  -u  Update Fastfetch
+  -u  Update Fastfetch to the latest GitHub release
 _HELP_
   exit "$errcode"
 }
@@ -60,11 +58,6 @@ _HELP_
 cleanup() {
 	[[ -f "$tmp_file" ]] && rm "$tmp_file"
 	[[ -d "$tmp_dir" ]] && rm -rf "$tmp_dir"
-}
-
-check_dependencies() {
-  local packages=( git wget )
-  check_packages "${packages[@]}"
 }
 
 ff_version() {
@@ -92,7 +85,7 @@ compare_versions() {
 
 install_fastfetch(){
 	local new_ver="$1"
-  local new_pkg="fastfetch-linux-amd64.deb"
+  local -r new_pkg="fastfetch-linux-amd64.deb"
 	sudo_login 2
   printf "Downloading FastFetch %s from the fastfetch-cli GitHub repository..." "$new_ver"
   dots "."
@@ -111,7 +104,9 @@ remove_fastfetch() {
 	sudo dpkg --purge fastfetch
 	[[ -L "$cfg_d/config.jsonc" ]] && unlink "$cfg_d/config.jsonc"
 	[[ -L "$logo_d/logo.png" ]] && unlink "$logo_d/logo.png"
-	find "$HOME/.*" -type d -name fastfetch -exec rm -rf {} \;
+	find "$HOME/.config" -type d -name fastfetch -exec rm -rf {} \;
+	[[ -d "$HOME/.local/share/fastfetch" ]] && rm -rf "$HOME/.local/share/fastfetch"
+	[[ -d "$HOME/.cache/fastfetch" ]] && rm -rf "$HOME/.cache/fastfetch"
 	printf "Fastfetch and its configuration files have been removed.\n"
 }
 
@@ -137,45 +132,50 @@ fastfetch_config() {
 
 main() {
   local noOpt opt optstr new_ver cfg_d logo_d
-	check_dependencies
 	cfg_d="$HOME/.config/fastfetch"
 	logo_d="$HOME/.local/share/fastfetch/logos"
 	noOpt=1
 	optstr=":chiru"
 	while getopts "$optstr" opt; do
 		case "$opt" in
-			c )
-				exists fastfetch || leave "Fastfetch is not installed."
-				printf "%sInstalling custom Fastfetch configuration...%s\n" "$lightyellow" "$normal"
-				fastfetch_config "$cfg_d" "$logo_d"
-			;;
 			h )
 				help 0
-			;;
+				;;
 			i )
-				exists fastfetch && leave "Fastfetch $(ff_version) is already installed."
-				tmp_file=$(mktemp) || die "Failed to create temporary file." 1
-				tmp_dir=$(mktemp -d) || die "Failed to create temporary directory." 1
-				trap cleanup EXIT
-				new_ver="$(newest_version)"
-				[[ "$new_ver" ]] || die "No download available. Try again later." 1
-				printf "%sInstalling Fastfetch version %s...%s\n" "$lightyellow" "$new_ver" "$normal"
-				install_fastfetch "$new_ver"
-				fastfetch_config "$cfg_d" "$logo_d"
-			;;
+				if exists fastfetch; then
+					printf "Fastfetch %s is already installed.\n" "$(ff_version)" >&2
+				else
+					check_package wget
+					tmp_file=$(mktemp) || die "Failed to create temporary file." 1
+					tmp_dir=$(mktemp -d) || die "Failed to create temporary directory." 1
+					trap cleanup EXIT
+					new_ver="$(newest_version)"
+					[[ "$new_ver" ]] || die "No download available. Try again later." 1
+					printf "%sInstalling Fastfetch version %s...%s\n" "$lightyellow" "$new_ver" "$normal"
+					install_fastfetch "$new_ver"
+					fastfetch_config "$cfg_d" "$logo_d"
+				fi
+				;;
 			r )
-				exists fastfetch || leave "Fastfetch is not installed."
-				remove_fastfetch "$cfg_d" "$logo_d"
-			;;
+				if exists fastfetch; then
+					remove_fastfetch "$cfg_d" "$logo_d"
+				else
+					printf "Fastfetch is not installed.\n" >&2
+				fi
+				;;
 			u )
-				exists fastfetch || leave "Fastfetch is not installed."
-				tmp_file=$(mktemp) || die "Failed to create temporary file." 1
-				tmp_dir=$(mktemp -d) || die "Failed to create temporary directory." 1
-				trap cleanup EXIT
-				new_ver="$(newest_version)"
-				[[ "$new_ver" ]] || die "No download available. Try again later." 1
-				compare_versions "$new_ver"
-			;;
+				if exists fastfetch; then
+					check_package wget
+					tmp_file=$(mktemp) || die "Failed to create temporary file." 1
+					tmp_dir=$(mktemp -d) || die "Failed to create temporary directory." 1
+					trap cleanup EXIT
+					new_ver="$(newest_version)"
+					[[ "$new_ver" ]] || die "No download available. Try again later." 1
+					compare_versions "$new_ver"
+				else
+					printf "Fastfetch is not installed.\n" >&2
+				fi
+				;;
 			? )
 				printf "%s Invalid option -%s\n" "$RED_ERROR" "$OPTARG" >&2
 				help 2
