iru-vscodium: convert_compare() - changed to compare numeric values instead of strings; added create_temp()

diff --git a/iru-vscodium b/iru-vscodium
--- a/iru-vscodium
+++ b/iru-vscodium
@@ -7,7 +7,8 @@
 # Author       : Copyright (C) 2022, Richard B. Romig, Mosfanet
 # Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
 # Created      : 16 Jul 2022
-# Updated      : 21 Jul 2026
+# Updated      : 23 Aug 2026
+# Version      : 5.0.26235
 # Comments     :
 # TODO (Rick)  :
 # License      : GNU General Public License, version 2.0
@@ -23,7 +24,6 @@
 # FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
 ###############################################################################
 
-## Source function library ##
 # shellcheck source=/home/rick/bin/functionlib.bash
 source ~/bin/functionlib.bash || { printf "\e[91mERROR:\e[0m Unable to source functionlib.bash\n"; exit 1; }
 
@@ -31,7 +31,7 @@ help() {
   local -r script="$1"
   local -r version="$2"
 	local -r errcode="${3:-1}"
-	local updated="21 Jul 2026"
+	local updated="23 Aug 2026"
 	cat << _HELP_
 ${orange}$script${normal} $version ($updated)
 Installs, configures, updates,  removes the VSCodium editor.
@@ -44,6 +44,13 @@ ${orange}Available options:${normal}
   -u  Updates the VSCodium editor to the latest GitHub release.
 _HELP_
   exit "$errcode"
+}
+
+create_temp() {
+  TMP_FILE=$(mktemp) || die "Failed to create temporary file." "$E_TEMP_FILE"
+  TMP_DIR=$(mktemp -d) || die "Failed to create temporary directory." "$E_TEMP_DIR"
+	trap cleanup EXIT
+  return 0
 }
 
 # shellcheck disable=SC2317 # Don't warn about unreachable commands in this function
@@ -59,16 +66,16 @@ codium_version() {
 }
 
 convert_compare() {
-  local newVer="$1"
-  local curVer="$2"
-  local newer="$FALSE"
+  local -r newVer="$1"
+  local -r curVer="$2"
+  local -i newer="$FALSE"
 	local new_arr=()
 	local cur_arr=()
   local -i index
 	IFS="." read -ra new_arr <<< "$newVer"
 	IFS="." read -ra cur_arr <<< "$curVer"
 	for (( index=0; index <=2; index++)) ; do
-		if [[ "${new_arr[index]}" > "${cur_arr[index]}" ]]; then
+    if (( "${new_arr[index]}" > "${cur_arr[index]}" )); then
       newer="$TRUE"
       break
     fi
@@ -106,7 +113,7 @@ compare_versions() {
 install_vscodium() {
 	local -r new_ver="$1"
 	local -r gh_url="$2"
- local new_pkg="codium_${new_ver}_amd64.deb"
+  local new_pkg="codium_${new_ver}_amd64.deb"
   if [[ -z "$new_ver" ]]; then
     printf "%s No download available. Try again later." "$RED_ERROR" >&2
     return "$E_DOWNLOAD"
@@ -157,7 +164,7 @@ apply_settings() {
 
 main() {
   local -r script="${0##*/}"
-  local -r version="4.6.26202"
+  local -r version="5.0.26235"
 	local -i exit_code=0
   local -r gh_url="https://github.com/VSCodium/vscodium/releases"
   local opt new_ver OPTARG OPTIND
@@ -169,29 +176,25 @@ main() {
 			  help "$script" "$version" 0
         ;;
 		  i )
-        if exists codium; then
+        if installed codium; then
           printf "VSCodium %s is already installed.\n" "$(codium_version)" >&2
         else
-          TMP_FILE=$(mktemp) || die "Failed to create temporary file." "$E_TEMP_FILE"
-          TMP_DIR=$(mktemp -d) || die "Failed to create temporary directory." "$E_TEMP_DIR"
-			    trap cleanup EXIT
+          create_temp
 			    new_ver="$(newest_version "$gh_url")"
           printf "%sInstalling VSCodium %s...%s\n" "$lightyellow" "$new_ver" "$normal"
 			    install_vscodium "$new_ver" "$gh_url" && apply_settings
         fi
         ;;
 		  r )
-        if exists codium; then
+        if installed codium; then
           remove_vscodium
         else
           printf "VSCodium is not installed.\n" >&2
         fi
         ;;
 		  u )
-        if exists codium; then
-          TMP_FILE=$(mktemp) || die "Failed to create temporary file." "$E_TEMP_FILE"
-          TMP_DIR=$(mktemp -d) || die "Failed to create temporary directory." "$E_TEMP_DIR"
-			    trap cleanup EXIT
+        if installed codium; then
+          create_temp
 			    new_ver="$(newest_version "$gh_url")"
 			    compare_versions "$new_ver" "$gh_url"
         else
@@ -205,12 +208,13 @@ main() {
     exit_code="$?"
 	  noOpt=0
   done
-  [[ "$noOpt" = 1 ]] && { printf "%s No argument passed.\n" "$RED_ERROR" >&2; help "$script" "$version" "$E_MISSING_ARG"; }
+	if (( noOpt == 1 )); then
+		printf "%s No argument passed.\n" "$RED_ERROR" >&2
+		help "$script" "$version" "$E_MISSING_ARG"
+	fi
   shift "$(( OPTIND - 1 ))"
   over_line "$script $version"
   exit "$exit_code"
 }
-
-## Execution ##
 
 main "$@"
