iru-micro: convert_compare() - changed to compare numeric values instead of strings; updated local variablles

diff --git a/iru-micro b/iru-micro
--- a/iru-micro
+++ b/iru-micro
@@ -7,7 +7,8 @@
 # Author       : Copyright (C) 2022, Richard B. Romig, Mosfanet
 # Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
 # Created      : 10 Jan 2022
-# Updated      : 20 Jul 2026
+# Updated      : 23 Aug 2026
+# Version      : 8.4.26235
 # Comments     : Debian 13 & LMDE 7 installs version 2.0.14 from Debian repository
 #              : Debian 12, Ubuntu 24.04 & Mint 22 nstalls version 2.0.13 from repositories
 #              : iru-micro -u remove remove repo version and install latest from GitHub repository
@@ -25,15 +26,14 @@
 # FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
 ###############################################################################
 
-## Source function library ##
 # shellcheck source=/home/rick/bin/functionlib.bash
 source ~/bin/functionlib.bash || { printf "\e[91mERROR:\e[0m Unable to source functionlib.bash\n"; exit 1; }
 
 help() {
 	local -r script="$1"
 	local -r version="$2"
-	local -r errcode="${3:-1}"
-	local -r updated="20 Jul 2026"
+	local -ri errcode="${3:-1}"
+	local -r updated="23 Aug 2026"
 	cat << _HELP_
 ${orange}$script${normal} $version ($updated)
 Installs, configures, updates, or removes the Micro CLI text editor.
@@ -70,14 +70,14 @@ micro_version() {
 convert_compare() {
   local -r newVer="$1"
   local -r curVer="$2"
-  local newer="$FALSE"
+  local -i newer="$FALSE"
 	local new_arr=()
 	local cur_arr=()
   local -i index
 	IFS="." read -ra new_arr <<< "$newVer"
 	IFS="." read -ra cur_arr <<< "$curVer"
 	for (( index=0; index <=2; index++)) ; do
-		if [[ "${new_arr[index]}" > "${cur_arr[index]}" ]]; then
+    if (( "${new_arr[index]}" > "${cur_arr[index]}" )); then
       newer="$TRUE"
       break
     fi
@@ -87,6 +87,7 @@ convert_compare() {
 
 newest_version() {
   local -r gh_url="$1"
+	local new_ver
   wget -qO "$TMP_FILE" "$gh_url"
   new_ver=$(sed 's/^v//' < <(awk -F'/' '/download\/v/ {print $6;exit}' "$TMP_FILE"))
   echo "$new_ver"
@@ -183,7 +184,7 @@ micro_configs() {
 
 main() {
   local -r script="${0##*/}"
-  local -r version="8.3.26201"
+  local -r version="8.4.26235"
 	local -i exit_code=0
   local -r gh_url="https://github.com/micro-editor/micro/releases"
   local opt new_ver OPTARG OPTIND
@@ -240,7 +241,10 @@ main() {
     exit_code="$?"
     noOpt=0
   done
-  [[ "$noOpt" = 1 ]] && { printf "%s No argument passed.\n" "$RED_ERROR" >&2; help "$script" "$version" "$E_MISSING_ARG"; }
+	if (( noOpt == 1 )); then
+		printf "%s No argument passed.\n" "$RED_ERROR" >&2
+		help "$script" "$version" "$E_MISSING_ARG"
+	fi
   shift "$(( OPTIND - 1 ))"
   over_line "$script $version"
   exit "$exit_code"
