iru-bat: capitalized tmp_dir & tmp_file (globabl variables)

diff --git a/iru-bat b/iru-bat
--- a/iru-bat
+++ b/iru-bat
@@ -7,7 +7,7 @@
 # Author       : Copyright (C) 2022, Richard B. Romig, Mosfanet
 # Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
 # Created      : 09 Jan 2022
-# Updated      : 27 Feb 2026
+# Updated      :  17 Apr 2026
 # Comments     : Use install-batcat if distro version has same base version number as latest GitHub release.
 #              : Mint 22 installs version 0.24.0 with the Ubuntu version appended.
 #              : Debian 13 installs version 0.25.0 with the Debian version appended.
@@ -27,22 +27,14 @@
 # GNU General Public License for more details.
 ##########################################################################
 
-## Shellcheck Directives ##
+## Load function library ##
 # shellcheck source=/home/rick/bin/functionlib
-
-## Source function library ##
-
-if [[ -x "$HOME/bin/functionlib" ]]; then
-  source "$HOME/bin/functionlib"
-else
-  printf "\e[91mERROR:\e[0m functionlib not found!\n" >&2
-  exit 81
-fi
+source functionlib || { printf "\e[91mERROR:\e[0m Unable to source functionlib\n"; exit 1; }
 
 ## Global Variables ##
 
 readonly script="${0##*/}"
-readonly version="6.21.26058"
+readonly version="6.22.26107"
 readonly gh_url="https://github.com/sharkdp/bat/releases"
 DOTS_PID=
 EC=0
@@ -51,7 +43,7 @@ EC=0
 
 help() {
 	local errcode="${1:-1}"
-	local -r updated="27 Feb 2026"
+	local -r updated=" 17 Apr 2026"
 	cat << _HELP_
 ${orange}$script${normal} $version ($updated)
 Installs, updates, or removes the Bat utililty.
@@ -66,11 +58,12 @@ _HELP_
   exit "$errcode"
 }
 
-# shellcheck disable=SC2317 # Don't warn about unreachable commands in this function
+# Don't warn about unreachable commands in this function
 # ShellCheck may incorrectly believe that code is unreachable if it's invoked by variable name or in a trap.
+# shellcheck disable=SC2317
 cleanup() {
-  [[ -d "$tmp_dir" ]] && rm -rf "$tmp_dir"
-  [[ -f "$tmp_file" ]] && rm -f "$tmp_file"
+  [[ -d "$TMP_DIR" ]] && rm -rf "$TMP_DIR"
+  [[ -f "$TMP_FILE" ]] && rm -f "$TMP_FILE"
 }
 
 check_dependencies() {
@@ -83,8 +76,8 @@ bat_version() {
 }
 
 newest_version() {
-  wget -qO "$tmp_file" "$gh_url"
-  new_ver=$(grep -Ev 'beta|-rc' <(awk -F'/' '/download/ && /amd64.deb/ {print $6;exit}' "$tmp_file") | sed 's/^v//')
+  wget -qO "$TMP_FILE" "$gh_url"
+  new_ver=$(grep -Ev 'beta|-rc' <(awk -F'/' '/download/ && /amd64.deb/ {print $6;exit}' "$TMP_FILE") | sed 's/^v//')
   echo "$new_ver"
 }
 
@@ -115,11 +108,11 @@ install_bat() {
   printf "Downloading Bat %s from the sharkdp GitHub repository..." "$new_ver"
   dots "." &
 	DOTS_PID="$!"
-  wget -q -P "$tmp_dir/" "$gh_url/download/v$new_ver/$new_pkg"
+  wget -q -P "$TMP_DIR/" "$gh_url/download/v$new_ver/$new_pkg"
 	kill_dots
   printf "Installing Bat %s...\n" "$new_ver"
   sudo_login 2
-	sudo dpkg -i "$tmp_dir/$new_pkg"; sudo apt-get install --fix-broken
+	sudo dpkg -i "$TMP_DIR/$new_pkg"; sudo apt-get install --fix-broken
   if [[ "$(bat_version)" != "$new_ver" ]]; then
     printf "%s Bat installation failed.\n" "$RED_ERROR" >&2
     EC="$E_INSTALLATION"
@@ -169,8 +162,8 @@ main() {
           printf "Bat %s is already installed.\n" "$(bat_version)" >&2
         else
           check_dependencies
-          tmp_file=$(mktemp) || die "Failed to create temporary file." "$E_TEMP_FILE"
-          tmp_dir=$(mktemp -d) || die "Failed to create temporary directory." "$E_TEMP_DIR"
+          TMP_FILE=$(mktemp) || die "Failed to create temporary file." "$E_TEMP_FILE"
+          TMP_DIR=$(mktemp -d) || die "Failed to create temporary directory." "$E_TEMP_DIR"
           trap cleanup EXIT
 					new_ver="$(newest_version)"
           printf "%sInstalling Bat version %s...%s\n" "$lightyellow" "$new_ver" "$normal"
@@ -188,8 +181,8 @@ main() {
       u )
         if exists bat || exists batcat; then
           check_dependencies
-          tmp_file=$(mktemp) || die "Failed to create temporary file." "$E_TEMP_FILE"
-          tmp_dir=$(mktemp -d) || die "Failed to create temporary directory." "$E_TEMP_DIR"
+          TMP_FILE=$(mktemp) || die "Failed to create temporary file." "$E_TEMP_FILE"
+          TMP_DIR=$(mktemp -d) || die "Failed to create temporary directory." "$E_TEMP_DIR"
           trap cleanup EXIT
 					printf "Bat: Comparing current and newest versions...\n"
           new_ver="$(newest_version)"
