keepass2main: added GPL notice;created copy_passwords() to copy password vaults to main.

diff --git a/keepass2main b/keepass2main
--- a/keepass2main
+++ b/keepass2main
@@ -60,7 +60,7 @@ main() {
   local -r mhost="hp-800g2-sff"
   # Ensure script is not being run from HP-800-G2-SFF (10)
   if is_main_host "$mhost"; then
-    printf "%s cannot be run from %s\n" "$script" "$mhost"
+    printf "%s cannot be run from %s\n" "$script" "$mhost" >&2
   else
     copy_passwords  "$mhost"
   fi
