kkb: main() - refactored to use if-else-fi block instead of double brackets test

diff --git a/kkb b/kkb
--- a/kkb
+++ b/kkb
@@ -7,7 +7,7 @@
 # Author       : Copyright © 2023 Richard B. Romig, Mosfanet
 # Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
 # Created      : 25 Apr 2023
-# Last updated : 19 Jul 2025
+# Last updated : 22 Jun 2026
 # Comments     : Install with kitty-bindings.list in ~/.config/kitty/
 # TODO (Rick)  :
 # License      : GNU General Public License, version 2.0
@@ -24,23 +24,13 @@
 # GNU General Public License for more details.
 ##########################################################################
 
-## Shellcheck Directives ##
-# shellcheck source=/home/rick/bin/functionlib
-
 ## Source function library ##
-
-if [[ -x "$HOME/bin/functionlib" ]]; then
-  source "$HOME/bin/functionlib"
-else
-  printf "\e[91mERROR:\e[0m functionlib not found!\n" >&2
-  exit 1
-fi
-
-set -eu
+# shellcheck source=/home/rick/bin/functionlib
+source ~/bin/functionlib || { printf "\e[91mERROR:\e[0m Unable to source functionlib\n"; exit 1; }
 
 ## Global Variables ##
 
-readonly kitty_dir=$HOME/".config/kitty"
+readonly kitty_dir=~/.config/kitty
 readonly bindings="bindings.list"
 
 ## Functions ##
@@ -60,10 +50,13 @@ show_bindings() {
 
 main() {
 	local -r script="${0##*/}"
-	local -r version="1.9.25205"
-	[[ "$TERM" != "xterm-kitty" ]] && die "Terminal emulater is not Kitty." 1
-	clear
-	show_bindings
+	local -r version="1.10.26173"
+	if [[ "$TERM" == "xterm-kitty" ]]; then
+		clearscreen
+		show_bindings
+	else
+		printf "The current terminal emulator is not Kitty.\n"
+	fi
 	over_line "$script $version"
 	exit
 }
