laptop-lid: updated local variables

diff --git a/laptop-lid b/laptop-lid
--- a/laptop-lid
+++ b/laptop-lid
@@ -7,7 +7,8 @@
 # Author       : Copyright (C) 2020, Richard B. Romig, LudditeGeek@Mosfanet
 # Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
 # Created      : 22 Oct 2020
-# Updated      : 03 Jul 2026
+# Updated      : 30 Jul 2026
+# Version      : 4.7.26211
 # Comments     :
 # TODO (Rick)  :
 # License      : GNU General Public License, version 2.0
@@ -18,16 +19,13 @@
 # Foundation; either version 2 of the License, or (at your option) any later
 # version.
 #
-# This program is distributed in the hope that it will be useful, but WITHOUT ANY
-# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
-# A PARTICULAR PURPOSE. See the GNU General Public License for more details.
+# This program is distributed in the hope that it will be useful, but WITHOUT
+# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
+# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
 ###############################################################################
 
-## Source function library ##
-# shellcheck source=/home/rick/bin/functionlib
-source ~/bin/functionlib || { printf "\e[91mERROR:\e[0m Unable to source functionlib\n"; exit 1; }
-
-## Functions ##
+# shellcheck source=/home/rick/bin/functionlib.bash
+source ~/bin/functionlib.bash || { printf "\e[91mERROR:\e[0m Unable to source functionlib.bash\n"; exit 1; }
 
 modify_logind() {
   local script_dir
@@ -48,21 +46,19 @@ modify_logind() {
 
 main() {
   local -r script="${0##*/}"
-  local -r version="4.6.26184"
+  local -r version="4.7.26211"
   local -r lhost="${HOSTNAME:=-$(hostname)}"
-  exit_code=0
+  local -i exit_code=0
   printf "Allows a laptop's lid to be closed without the system going into suspend mode.\n"
   if is_laptop; then
     modify_logind
     exit_code="$?"
   else
     printf "%s is not a laptop. Operation canceled.\n" "$lhost" >&2
-    exit_code=1
+    exit_code="$E_UNSUPPORTED"
   fi
   over_line "$script $version" "-"
   exit "$exit_code"
 }
-
-## Execution ##
 
 main "$@"
