laptop-lid: updated indentation

diff --git a/laptop-lid b/laptop-lid
--- a/laptop-lid
+++ b/laptop-lid
@@ -7,8 +7,8 @@
 # Author       : Copyright (C) 2020, Richard B. Romig, LudditeGeek@Mosfanet
 # Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
 # Created      : 22 Oct 2020
-# Updated      : 30 Jul 2026
-# Version      : 4.7.26211
+# Updated      : 08 Sep 2026
+# Version      : 4.8.26251
 # Comments     :
 # TODO (Rick)  :
 # License      : GNU General Public License, version 2.0
@@ -28,37 +28,37 @@
 source ~/bin/functionlib.bash || { printf "\e[91mERROR:\e[0m Unable to source functionlib.bash\n"; exit 1; }
 
 modify_logind() {
-  local script_dir
-  script_dir=$(dirname "$(readlink -f "${0}")")
-  local -r logind_conf="/etc/systemd/logind.conf"
-  local -r sed_file="$script_dir/files/laptoplid.sed"
-  if [[ ! -f "$sed_file" ]]; then
-    printf "A required file, %s, was not found. Operation canceled.\n" "${sed_file##*/}" >&2
-    return "$E_FILENOTFOUND"
-  fi
-  sudo_login 2
-  printf "Modifying %s and restarting the systemd-logind service.\n" "${logind_conf##*/}"
-  sudo sed -i.bak -f "$sed_file" "$logind_conf"
-  sudo systemctl restart systemd-logind.service
-  printf "%s modified, backup created, and service restarted.\n" "$logind_conf"
-  return 0
+	local script_dir
+	script_dir=$(dirname "$(readlink -f "${0}")")
+	local -r logind_conf="/etc/systemd/logind.conf"
+	local -r sed_file="$script_dir/files/laptoplid.sed"
+	if [[ ! -f "$sed_file" ]]; then
+		printf "A required file, %s, was not found. Operation canceled.\n" "${sed_file##*/}" >&2
+		return "$E_FILENOTFOUND"
+	fi
+	sudo_login 2
+	printf "Modifying %s and restarting the systemd-logind service.\n" "${logind_conf##*/}"
+	sudo sed -i.bak -f "$sed_file" "$logind_conf"
+	sudo systemctl restart systemd-logind.service
+	printf "%s modified, backup created, and service restarted.\n" "$logind_conf"
+	return 0
 }
 
 main() {
-  local -r script="${0##*/}"
-  local -r version="4.7.26211"
-  local -r lhost="${HOSTNAME:=-$(hostname)}"
-  local -i exit_code=0
-  printf "Allows a laptop's lid to be closed without the system going into suspend mode.\n"
-  if is_laptop; then
-    modify_logind
-    exit_code="$?"
-  else
-    printf "%s is not a laptop. Operation canceled.\n" "$lhost" >&2
-    exit_code="$E_UNSUPPORTED"
-  fi
-  over_line "$script $version" "-"
-  exit "$exit_code"
+	local -r script="${0##*/}"
+	local -r version="4.8.26251"
+	local -r lhost="${HOSTNAME:=-$(hostname)}"
+	local -i exit_code=0
+	printf "Allows a laptop's lid to be closed without the system going into suspend mode.\n"
+	if is_laptop; then
+		modify_logind
+		exit_code="$?"
+	else
+		printf "%s is not a laptop. Operation canceled.\n" "$lhost" >&2
+		exit_code="$E_UNSUPPORTED"
+	fi
+	over_line "$script $version" "-"
+	exit "$exit_code"
 }
 
 main "$@"
