laptop-utils: added error code variables

diff --git a/laptop-utils b/laptop-utils
--- a/laptop-utils
+++ b/laptop-utils
@@ -7,7 +7,7 @@
 # Author       : Copyright (C) 2023, Richard Romig, LudditeGeek
 # Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
 # Created      : 23 Mar 2023
-# Updated      : 31 Dec 2025
+# Updated      : 27 Jan 2026
 # Comments     : Based on a script by Joe Collins.
 # TODO (rick)  :
 # License      : GNU General Public License, version 2.0
@@ -32,19 +32,19 @@
 if [[ -x "$HOME/bin/functionlib" ]]; then
   source "$HOME/bin/functionlib"
 else
-  printf "\e[91mERROR:\e[0m functionlib not found!\n" >&2; exit 1
+  printf "\e[91mERROR:\e[0m functionlib not found!\n" >&2; exit 81
 fi
 
 ## Global Variables ##
 
 readonly script="${0##*/}"
-readonly version="8.1.25365"
+readonly version="8.2.26027"
 
 ## Funtions ##
 
 help() {
-	local errcode="${1:-2}"
-	local updated="31 Dec 2025"
+	local errcode="${1:-1}"
+	local updated="27 Jan 2026"
 	cat << _HELP_
 ${orange}$script${normal} $version ($updated)
 Installs laptop-specific utlities.
@@ -164,11 +164,11 @@ main() {
         ;;
       ? )
         printf "%s Invalid option -%s\n" "$RED_ERROR" "$OPTARG" >&2
-        help 2
+        help "$E_INVALID_ARG"
     esac
 	  noOpt=0
   done
-  [[ "$noOpt" = 1 ]] && { printf "%s No argument passed.\n" "$RED_ERROR" >&2; help 1; }
+  [[ "$noOpt" = 1 ]] && { printf "%s No argument passed.\n" "$RED_ERROR" >&2; help "$E_MISSING_ARG"; }
   shift "$(( OPTIND - 1 ))"
   over_line "$script $version"
   exit
