v0.3.0 - Removed if-else. is_laptop = FALSE, leaves script.

diff --git a/laptoplid b/laptoplid
--- a/laptoplid
+++ b/laptoplid
@@ -4,12 +4,13 @@
 # Description  : Settings to close laptop lid without suspend
 # Dependencies : laptoplid.sed
 # Arguments    : None
-# Author       : Richard B. Romig, 22 Oct 2020
+# Author       : Copyright (C) 2020, Richard B. Romig, 22 Oct 2020
 # Email        : rick.romig@gmail.com
 # Comments     :
 # 07 Sep 2021  : Replaced sed commands with a .sed file.
 # 07 Oct 2021  : Added conditional for missing sed file.
 # 15 Feb 2022  : Placed operational code within an if-else statement.
+# 11 Oct 2022  : Removed if-else. is_laptop = FALSE, leaves script.
 # TODO (Rick)  :
 # License      : GNU General Public License, version 2.0
 ##########################################################################
@@ -30,8 +31,8 @@ fi
 ## Variables ##
 
 readonly _script=$(basename "$0")
-readonly _version="0.2.3"
-readonly _updated="15 Feb 2022"
+readonly _version="0.3.0"
+readonly _updated="11 Oct 2022"
 readonly logind_conf="/etc/systemd/logind.conf"
 readonly sed_file="$HOME/bin/files/laptoplid.sed"
 
@@ -41,11 +42,8 @@ clear
 printf "\U1F427 %s v%s (%s)\n" "$_script" "$_version" "$_updated"
 printf "\U1F4BB Allows a laptop lid to be closed without going into suspend mode.\n\n"
 
-if is_laptop; then
-  [[ -f "$sed_file" ]] || die "A required file ($(basename "$sed_file")) was not found." 1
-  user_in_sudo
-  sudo sed -i.bak -f "$sed_file" "$logind_conf"
-  leave "$logind_conf modified. Backup (${logind_conf}.bak) created."
-else
-  leave "This system is not a laptop. $logind_conf was not modified."
-fi
+is_laptop || leave "This system is not a laptop. $logind_conf was not modified."
+[[ -f "$sed_file" ]] || die "A required file ($(basename "$sed_file")) was not found." 1
+user_in_sudo
+sudo sed -i.bak -f "$sed_file" "$logind_conf"
+leave "$logind_conf modified. Backup (${logind_conf}.bak) created."
