laptop-utils: packages is now a local variable passed by main() to installed_packages() & install_packages()

diff --git a/laptop-utils b/laptop-utils
--- a/laptop-utils
+++ b/laptop-utils
@@ -7,7 +7,7 @@
 # Author       : Copyright (C) 2023, Richard Romig, LudditeGeek
 # Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
 # Created      : 23 Mar 2023
-# Updated      : 20 Mar 2026
+# Updated      : 27 May 2026
 # Comments     : Based on a script by Joe Collins.
 # TODO (rick)  :
 # License      : GNU General Public License, version 2.0
@@ -24,28 +24,20 @@
 # GNU General Public License for more details.
 ##########################################################################
 
-## Shellcheck Directives ##
-# shellcheck source=/home/rick/bin/functionlib
-
 ## Load function library ##
-
-if [[ -x "$HOME/bin/functionlib" ]]; then
-  source "$HOME/bin/functionlib"
-else
-  printf "\e[91mERROR:\e[0m functionlib not found!\n" >&2; exit 81
-fi
+# shellcheck source=/home/rick/bin/functionlib
+source ~/bin/functionlib || { printf "\e[91mERROR:\e[0m Unable to source functionlib\n"; exit 1; }
 
 ## Global Variables ##
 
 readonly script="${0##*/}"
-readonly version="8.4.26079"
-packages=(acpi thermald tlp tlp-rdw)
+readonly version="8.5.26147"
 
 ## Funtions ##
 
 help() {
 	local errcode="${1:-1}"
-	local updated="20 Mar 2026"
+	local updated="27 May 2026"
 	cat << _HELP_
 ${orange}$script${normal} $version ($updated)
 Installs laptop-specific utlities.
@@ -72,6 +64,7 @@ _INTRO_
 }
 
 install_packages() {
+  local packages=("$@")
   local package
   printf "Installing packages:\n"
   for package in "${packages[@]}"; do
@@ -86,6 +79,7 @@ install_packages() {
 }
 
 installed_packages() {
+  local packages=("$@")
   local package
   printf "Package status:\n"
   for package in "${packages[@]}"; do
@@ -128,15 +122,16 @@ start_tlp_service() {
 }
 
 main() {
-  local lhost noOpt opt optstr OPTARG OPTIND
-  lhost="${HOSTNAME:=-$(hostname)}"
+  local noOpt opt optstr OPTARG OPTIND
+  local -r lhost="${HOSTNAME:=-$(hostname)}"
+  local -r packages=(acpi thermald tlp tlp-rdw)
   noOpt=1
   optstr=":dhis"
   while getopts "$optstr" opt; do
     case "$opt" in
       d )
         if is_laptop; then
-          installed_packages
+          installed_packages "${packages[@]}"
         else
           printf "%s is not a laptop. Nothing to do.\n" "$lhost" >&2
         fi
@@ -147,7 +142,7 @@ main() {
       i )
         if is_laptop; then
           intro
-          install_packages
+          install_packages "${packages[@]}"
         else
           printf "%s is not a laptop. Nothing to do.\n" "$lhost" >&2
         fi
