laptop-utils: updated local variables and return codes

diff --git a/laptop-utils b/laptop-utils
--- a/laptop-utils
+++ b/laptop-utils
@@ -1,5 +1,5 @@
 #!/usr/bin/env bash
-##########################################################################
+###############################################################################
 # Script Name  : laptop-utils
 # Description  : Installs laptop-specific utilities
 # Dependencies : None
@@ -7,37 +7,31 @@
 # Author       : Copyright (C) 2023, Richard Romig, LudditeGeek
 # Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
 # Created      : 23 Mar 2023
-# Updated      : 27 May 2026
+# Updated      : 30 Jul 2026
+# Version      : 8.6.26211
 # Comments     : Based on a script by Joe Collins.
 # TODO (rick)  :
 # License      : GNU General Public License, version 2.0
 # License URL  : https://github.com/RickRomig/scripts/blob/main/LICENSE
-##########################################################################
-# This program is free software; you can redistribute it and/or modify
-# it under the terms of the GNU General Public License as published by
-# the Free Software Foundation; either version 2 of the License, or
-# (at your option) any later version.
+###############################################################################
+# This program is free software; you can redistribute it and/or modify# it under
+# the terms of the GNU General Public License as published by the Free Software
+# Foundation; either version 2 of the License, or (at your option) any later
+# version.
 #
-# This program is distributed in the hope that it will be useful,
-# but WITHOUT ANY WARRANTY; without even the implied warranty of
-# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
-# GNU General Public License for more details.
-##########################################################################
+# This program is distributed in the hope that it will be useful, but WITHOUT
+# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
+# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
+###############################################################################
 
-## Load function library ##
-# shellcheck source=/home/rick/bin/functionlib
-source ~/bin/functionlib || { printf "\e[91mERROR:\e[0m Unable to source functionlib\n"; exit 1; }
-
-## Global Variables ##
-
-readonly script="${0##*/}"
-readonly version="8.5.26147"
-
-## Funtions ##
+# shellcheck source=/home/rick/bin/functionlib.bash
+source ~/bin/functionlib.bash || { printf "\e[91mERROR:\e[0m Unable to source functionlib.bash\n"; exit 1; }
 
 help() {
-	local errcode="${1:-1}"
-	local updated="27 May 2026"
+  local -r script="$1"
+  local -r version="$2"
+	local -ri errcode="${3:-1}"
+	local -r updated="30 Jul 2026"
 	cat << _HELP_
 ${orange}$script${normal} $version ($updated)
 Installs laptop-specific utlities.
@@ -46,10 +40,9 @@ ${green}Usage:${normal} $script [-dhis]
 ${orange}Available options:${normal}
   -d  Display installed utilities.
   -h  Show this help message and exit.
-  -i  Install laptop utilities.
+  -i  Install laptop utilities. (acpi thermald tlp tlp-rdw)
   -s  Start TLP service.
 _HELP_
-  intro
   exit "$errcode"
 }
 
@@ -76,6 +69,7 @@ install_packages() {
       printf "%s installed.\n" "${package^^}"
     fi
   done
+  return 0
 }
 
 installed_packages() {
@@ -86,22 +80,24 @@ installed_packages() {
     printf "%s is " "${package^^}"
     installed "$package" && printf "installed.\n" || printf "not installed.\n"
   done
+  return 0
 }
 
 tlp_status() {
   local status=1
   if ! installed tlp; then
-    printf "TLP is not installed.\n"
-    return
+    printf "TLP is not installed.\n" >&2
+    return "$E_INSTALLATION"
   fi
   is_systemd && { grep -qw active <(systemctl status tlp) && status=0; }
   is_sysv && { grep -qw enabled <(tlp-stat -s) && status=0; }
-  if [[ "$status" -eq 0 ]]; then
-    printf "TLP service is active and running.\n"
-    return
+  if [[ "$status" -ne 0 ]]; then
+    printf "Starting TLP service\n"
+    start_tlp_service
+    return "$status"
   fi
-  printf "Starting TLP service\n"
-  start_tlp_service
+  printf "TLP service is active and running.\n"
+  return 0
 }
 
 start_tlp_service() {
@@ -119,53 +115,56 @@ start_tlp_service() {
     printf "Init system is neither Systemd nor SysV.\n"
     printf "Manually start the TLP service.\n"
   fi
+  return 0
 }
 
 main() {
-  local noOpt opt optstr OPTARG OPTIND
+  local -r script="${0##*/}"
+  local -r version="8.6.26211"
+  local -i exit_code=0
+  local opt OPTARG OPTIND
+  local -i noOpt=1
+  local -r optstr=":dhis"
   local -r lhost="${HOSTNAME:=-$(hostname)}"
   local -r packages=(acpi thermald tlp tlp-rdw)
-  noOpt=1
-  optstr=":dhis"
   while getopts "$optstr" opt; do
     case "$opt" in
       d )
         if is_laptop; then
           installed_packages "${packages[@]}"
         else
-          printf "%s is not a laptop. Nothing to do.\n" "$lhost" >&2
+          printf "%s is not a laptop. Nothing to do.\n" "$lhost"
         fi
         ;;
       h )
-        help 0
+        help "$script" "$version" 0
         ;;
       i )
         if is_laptop; then
           intro
           install_packages "${packages[@]}"
         else
-          printf "%s is not a laptop. Nothing to do.\n" "$lhost" >&2
+          printf "%s is not a laptop. Nothing to do.\n" "$lhost"
         fi
         ;;
       s )
         if is_laptop; then
           tlp_status
         else
-          printf "%s is not a laptop. Nothing to do.\n" "$lhost" >&2
+          printf "%s is not a laptop. Nothing to do.\n" "$lhost"
         fi
         ;;
       ? )
         printf "%s Invalid option -%s\n" "$RED_ERROR" "$OPTARG" >&2
-        help "$E_INVALID_ARG"
+        help "$script" "$version" "$E_INVALID_ARG"
     esac
+    exit_code="$?"
 	  noOpt=0
   done
-  [[ "$noOpt" = 1 ]] && { printf "%s No argument passed.\n" "$RED_ERROR" >&2; help "$E_MISSING_ARG"; }
+  [[ "$noOpt" = 1 ]] && { printf "%s No argument passed.\n" "$RED_ERROR" >&2; help "$script" "$version" "$E_MISSING_ARG"; }
   shift "$(( OPTIND - 1 ))"
   over_line "$script $version"
-  exit
+  exit "$exit_code"
 }
-
-## Execution ##
 
 main "$@"
