local-ip-up: removed -a option to scan entire network (use -sd or -ds); updated local variables

diff --git a/local-ip-up b/local-ip-up
--- a/local-ip-up
+++ b/local-ip-up
@@ -7,49 +7,43 @@
 # Author       : Copyright © 2019 Richard B. Romig, LudditeGeek
 # Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
 # Created      : 01 Dec 2019
-# Updated      : 07 Jun 2026
+# Updated      : 30 Jul 2026
+# Version      : 4.14.26211
 # Comments     : Variables for IP range do not work, must be hard coded.
 #              : Local host will respond using arping in the iputils-arping package.
-#              : Local host will not respond using the arping package.
+#              : Local host will not respond using the regular arping package.
 #              : Installing arping package will uninstall iputils-arping & require sudo.
 # TODO (Rick)  :
 # License      : GNU General Public License, version 2.0
 # License URL  : https://github.com/RickRomig/scripts/blob/main/LICENSE
-#############################################################################
-# This program is free software; you can redistribute it and/or modify
-# it under the terms of the GNU General Public License as published by
-# the Free Software Foundation; either version 2 of the License, or
-# (at your option) any later version.
+###############################################################################
+# This program is free software; you can redistribute it and/or modify# it under
+# the terms of the GNU General Public License as published by the Free Software
+# Foundation; either version 2 of the License, or (at your option) any later
+# version.
 #
-# This program is distributed in the hope that it will be useful,
-# but WITHOUT ANY WARRANTY; without even the implied warranty of
-# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
-## GNU General Public License for more details.
-#############################################################################
+# This program is distributed in the hope that it will be useful, but WITHOUT
+# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
+# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
+###############################################################################
 
-## Load function library ##
-# shellcheck source=/home/rick/bin/functionlib
-source ~/bin/functionlib || { printf "\e[91mERROR:\e[0m Unable to source functionlib\n"; exit 1; }
+# shellcheck source=/home/rick/bin/functionlib.bash
+source ~/bin/functionlib.bash || { printf "\e[91mERROR:\e[0m Unable to source functionlib.bash\n"; exit 1; }
 
-## Global Variables ##
-
-readonly script="${0##*/}"
-readonly version="4.13.26158"
 SECONDS=0
 COUNT=0
 
-## Functions ##
-
 help() {
-	local errcode="${1:-1}"
-	local updated="07 Jun 2026"
+  local -r script="$1"
+  local -r version="$2"
+	local -ri errcode="${3:-1}"
+	local -r updated="30 Jul 2026"
 	cat << _HELP_
 ${orange}$script${normal} $version ($updated)
 Scans local network to see which addresses are active.
 
-${green}Usage:${normal} $script [-adhs]
+${green}Usage:${normal} $script [-dhs]
 ${orange}Available options:${normal}
-  -a  Scan entire network.
   -d  Scan DHCP assigned addresses.
   -h  Show this help message and exit.
   -s  Scan static addresses.
@@ -61,6 +55,7 @@ _HELP_
 check_dependencies() {
   local packages=( avahi-daemon avahi-utils libnss-mdns iputils-arping )
   check_packages "${packages[@]}"
+  return 0
 }
 
 arping_check() {
@@ -70,6 +65,8 @@ arping_check() {
 
 scan_static_addresses() {
   local hname ip_addr
+  printf "\nScanning static IP addresses on the network...\n"
+  printf "%s%sIP Address\tHostname%s\n" "$underline" "$green" "$normal"
   for ip_addr in $LOCALNET.{1..25}; do
     if arping_check "$ip_addr"; then
       hname=$(awk '{print $NF}' < <(avahi-resolve -a "$ip_addr" 2>/dev/null) | sed 's/\.local$//')
@@ -92,7 +89,7 @@ scan_static_addresses() {
           "192.168.0.12" ) printf "e6500-deb (i3)\n" ;;
           "192.168.0.13" ) printf "probook-6570b (i3)\n" ;;
           "192.168.0.14" ) printf "hp-8300 (LMDE)\n" ;;
-          "192.168.0.15" ) printf "lenovo-m91p (LMDE)\n" ;;
+          "192.168.0.15" ) printf "dell-9020 (Mint)\n" ;;
           "192.168.0.16" ) printf "hp-8300-usdt (i3 Gitea Server)\n" ;;
           "192.168.0.17" ) printf "hp-800-g1-usdt (Mint)\n" ;;
           "192.168.0.18" ) printf "unassigned\n" ;;
@@ -110,65 +107,60 @@ scan_static_addresses() {
       (( COUNT++ ))
     fi
   done
+  return 0
 }
 
 scan_dhcp_addresses() {
   local hname ip_addr
+  printf "\nScanning DHCP addresses on the network...\n"
+  printf "%s%sIP Address\tHostname%s\n" "$underline" "$green" "$normal"
   for ip_addr in $LOCALNET.{100..199}; do
     if arping_check "$ip_addr"; then
       hname=$(awk '{print $NF} ' < <(avahi-resolve -a "$ip_addr" 2>/dev/null) | sed 's/\.local$//')
       printf "%s\t" "$ip_addr"
-       [[ -n "$hname" ]] &&  printf "%s\n" "$hname" || printf "Unknown host\n"
+       [[ -n "$hname" ]] && printf "%s\n" "$hname" || printf "Unknown host\n"
       (( COUNT++ ))
     fi
   done
+  return 0
 }
 
 main() {
-  local noOpt opt optstr OPTARG OPTIND
+  local -r script="${0##*/}"
+  local -r version="4.14.26211"
+  local opt OPTARG OPTIND
+  local -i exit_code=0
+  local -i noOpt=1
+  local -r optstr=":dhs"
   check_dependencies
-  noOpt=1
-  optstr=":adhs"
   while getopts "$optstr" opt; do
     case "$opt" in
-      a )
-        tput civis
-        printf "\nScanning the network...\n"
-        printf "%s%sIP Address\tHostname%s\n" "$underline" "$green" "$normal"
-        scan_static_addresses
-        scan_dhcp_addresses
-        tput cnorm
-        ;;
       d )
         tput civis
-        printf "\nScanning DHCP addresses on the network...\n"
-        printf "%s%sIP Address\tHostname%s\n" "$underline" "$green" "$normal"
         scan_dhcp_addresses
+        exit_code="$?"
         tput cnorm
         ;;
       h )
-        help 0
+        help "$script" "$version" 0
         ;;
       s )
         tput civis
-        printf "\nScanning static IP addresses on the network...\n"
-        printf "%s%sIP Address\tHostname%s\n" "$underline" "$green" "$normal"
         scan_static_addresses
+        exit_code="$?"
         tput cnorm
         ;;
       ? )
         printf "%s Invalid option -%s\n" "$RED_ERROR" "$OPTARG" >&2
-        help "$E_INVALID_ARG"
+        help "$script" "$version" "$E_INVALID_ARG"
     esac
 	  noOpt=0
   done
-  [[ "$noOpt" = 1 ]] && { printf "%s No argument passed.\n" "$RED_ERROR" >&2; help "$E_MISSING_ARG"; }
+  [[ "$noOpt" = 1 ]] && { printf "%s No argument passed.\n" "$RED_ERROR" >&2; help "$script" "$version" "$E_MISSING_ARG"; }
   shift "$(( OPTIND - 1 ))"
   printf "\n%d active addresses discovered in %s.\n\n" "$COUNT" "$(format_time SECONDS)"
   over_line "$script $version"
-  exit
+  exit "$exit_code"
 }
-
-## Execution ##
 
 main "$@"
