meditation-timer 0.4.0 - sound file is passed to play_sound, plays sound at 5-min intervals.

diff --git a/meditation-timer b/meditation-timer
--- a/meditation-timer
+++ b/meditation-timer
@@ -1,4 +1,4 @@
-#!/usr/bin/env bash
+#!/bin/bash
 ##########################################################################
 # Script Name  : meditation-timer
 # Description  : Counts down remaining time of a meditation session.
@@ -7,22 +7,7 @@
 # Author       : Copyright Richard B. Romig, 06 Jul 2021
 # Email        : rick.romig@gmail.com
 # Comments     : Original script found on Reddit r/dharmmawheel, posted by u/Jhanna4
-# 11 Jul 2021  : Plays sound as a backgroud process.
-# 26 Jul 2021  : Toggles screensaver & dpms, Added countdown before meditation.
-# 18 Nov 2021  : Hides/Restores cursor before/after in countdown & main_timer functions.
-#              : Placed main timer in a function.
-# 23 Nov 2021  : Added functions to set and restore playback volume. (disabled)
-# 13 Mar 2022  : Removed clear command in loops, added carriage return to time counts.
-# 04 May 2022  : Added exit code functionality to usage and input_value functions.
-# 06 Jul 2022  : Fixed arithmetic error in minutes assignment in main_timer function.
-# 17 Jul 2022  : Moved assignment of $1 to min to Check arguments section.
-# 02 Sep 2022  : Added Om emoji to title line.
-# 14 Oct 2022  : Defaults to 20 min. Checks for input value of 0.
-# 16 Oct 2022  : Assigns value to min variable, then checks if 0 or non-digit.
-# 06 Nov 2022  : Changed countdown function to a single line.
-# 07 Nov 2022  : Time is passed to main-timer function rather than global variable.
-#              : Static exit code of 2 in input_value function.
-# TODO (Rick)  :
+# TODO (Rick)  : get_volume() and set_volume()
 # License      : GNU General Public License, version 2.0
 ##########################################################################
 
@@ -42,14 +27,17 @@ fi
 ## Variables ##
 
 _script=$(basename "$0"); readonly _script
-readonly _version="0.3.4"
-readonly _updated="07 Nov 2022"
-readonly colorerr="${lightred}ERROR!${normal}"
+readonly _version="0.4.0"
+readonly _updated="13 Mar 2023"
+readonly med_time="${1:-20}"
+readonly sound_dir="$HOME/bin/files"
+readonly sound_one="Tibetan_bowl.wav"
+readonly sound_two="Low-Wood-Block.wav"
 
-## Functions ##
+## Functions ## 
 
 input_value() {
-  printf "%s Invalid argument\n" "$colorerr" >&2
+  printf "%s Invalid argument\n" "$red_error" >&2
   printf "Please supply a value for minutes, only minutes, and only whole numbers greater than 0.\n" >&2
   exit 2
 }
@@ -64,10 +52,9 @@ set_volume() {
 }
 
 play_sound() {
-  # Play gong sound as a background process.
-  local sound_dir="$HOME/bin/files"
-  local sound_file="Tibetan_bowl.wav"
-  /usr/bin/aplay "$sound_dir/$sound_file" > /dev/null 2>&1 &
+  # Play a sound as a background process.
+  local sound="$1"
+  /usr/bin/aplay "$sound" > /dev/null 2>&1 &
 }
 
 screensaver_off() {
@@ -106,17 +93,15 @@ main_timer() {
     # interval=$(( interval - hours ))
     # weeks=$(( interval / 604800 ))
     printf "\t%02d:%02d:%02d\r" "$hours" "$minutes" "$seconds"
+    [[ $(( sec_rem % 300 )) -eq 0 && "$sec_rem" -gt 0 ]] && play_sound "$sound_dir/$sound_two"
     sleep 1
   done
 }
 
 ## Execution ##
 
-# Check arguments
-
-minutes="${1:-20}"
-if [[ -n ${minutes//[0-9]/} ]] || [[ "$minutes" -eq 0 ]]; then input_value; fi
-
+[[ -n ${med_time//[0-9]/} || "$med_time" -eq 0 ]] && input_value
+# trap 'screensaver_on' SIGINT
 clear
 # Capture original volume setting
 # ovol=$(get_volume)
@@ -125,12 +110,12 @@ clear
 printf "\n\t\U0950  Meditation Timer \U0950\n\n"
 screensaver_off
 countdown
-play_sound
-main_timer "$minutes"
-play_sound
+play_sound "$sound_dir/$sound_one"
+main_timer "$med_time"
+play_sound "$sound_dir/$sound_one"
 sleep 30
 screensaver_on
 # set_volume "$ovol"
 printf "\n\n%s v%s (%s)\n" "$_script" "$_version" "$_updated"
-printf "\UA9 2021-2022 Richard B. Romig\n"
+printf "\UA9 2021-2023 Richard B. Romig\n"
 exit
