meditation-timer: added funtionlib for color; replaced check_alsa() with check_package(); added help option; uses default values if incorrect values entered

diff --git a/meditation-timer b/meditation-timer
--- a/meditation-timer
+++ b/meditation-timer
@@ -7,7 +7,7 @@
 # Author       : Copyright (C) 2021, Richard B. Romig, LudditeGeek@Mosfanet
 # Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
 # Created      : 06 Jul 2021
-# Updated      : 19 Jul 2025
+# Updated      : 13 Sep 2025
 # Comments     : Original script found on Reddit r/dharmmawheel, posted by u/Jhanna4
 #              : Sound does not work with Pipewire audio.
 # TODO (Rick)  : Work on getting sound functions to work on Pipewire.
@@ -26,15 +26,23 @@
 # GNU General Public License for more details.
 ##########################################################################
 
+## Shellcheck Directives ##
+# shellcheck source=/home/rick/bin/functionlib
+
+## Load function library ##
+
+if [[ -x "$HOME/bin/functionlib" ]]; then
+  source "$HOME/bin/functionlib"
+else
+  echo -e "\e[91mERROR:\e[0m functionlib not found!" >&2
+  exit 1
+fi
+
 ## Global Variables ##
 
 script_dir=$(dirname "$(readlink -f "${0}")"); readonly script_dir
 
 ## Functions ##
-
-check_alsa() {
-  dpkg -l alsa-utils >/dev/null 2>&1 && return 0 || return 1
-}
 
 # dpms_enabled() {
 #   xset -q | grep -w Enabled || return 0 || return 1
@@ -46,13 +54,14 @@ is_valid_integer() {
   [[ "$value" -ge 0 || "$value" -le 100 ]] && return 0 || return 1
 }
 
-input_value() {
+usage() {
   local script="$1"
-  printf "%s Invalid argument\n" "$RED_ERROR" >&2
-  printf "Please supply a value for minutes, only minutes, and only integers greater than 0.\n" >&2
-  printf "Usage: %s <minutes> [volume 0=100]\n" "$script"
-  printf "Volume will represent a percentage of the output volume.\n"
-  exit 2
+  local version="$2"
+   printf "%sUsage:%s %s <minutes> [volume 0-100]\n" "$orange" "$normal" "$script"
+  printf "Meditation time is set in minutes. Only enter integers greater than 0. The default is 20 minutes.\n"
+   printf "Volume is a percentage of the output volume. The default is 50%%.\n"
+   printf "If no arguments or incorrect values are entered, the default values will be used.\n"
+  exit_script "$script" "$version"
 }
 
 get_volume() {
@@ -91,6 +100,7 @@ screensaver_on() {
 }
 
 prep_countdown() {
+  # Allow 10 seconds before meditation begins.
   local count
   for count in {10..1}; do printf "\t%02d\r" "$count"; sleep 1; done
 }
@@ -101,6 +111,7 @@ meditation_timer() {
   sec_rem=$(( 60 * min ))
   # local -r audio_file="$script_dir/files/Low-Wood-Block.wav"
   while [[ "$sec_rem" -gt 0 ]]; do
+
     sec_rem=$(( sec_rem - 1 ))
     interval="$sec_rem"
     seconds=$(( interval % 60 ))
@@ -118,34 +129,43 @@ meditation_timer() {
   done
 }
 
+exit_script() {
+  local script="$1"
+  local version="$2"
+  printf "\n\U2638 %s v%s\n" "$script" "$version"
+  printf "\UA9 2021-2025 Richard B. Romig\n"
+  exit
+}
+
 main() {
   trap screensaver_on EXIT
-  local orig_volume
-  local script="${0##*/}"
-  local -r version="2.7.25200"
-  local -r audio_file="$script_dir/files/Tibetan_bowl.wav"
-  local meditation_time="${1:-20}"  # Default time is 20 minutes.
-  [[ "${meditation_time//[0-9]/}" || "$meditation_time" -eq 0 ]] && input_value "$script" # if not a digit or equals 0
-  local  volume="${2:-50}"  # Default volume setting is 50%.
+  local script version audio_file meditation_time orig_volume volume
+  script="${0##*/}"
+  version="2.8.25256"
+  audio_file="$script_dir/files/Tibetan_bowl.wav"
+  # Check arguments and dependencies.
+ meditation_time="${1:-20}"  # Default time is 20 minutes.
+  [[ "$meditation_time" == "-h" || "$meditation_time" == "--help" ]] && usage "$script" "$version"
+  [[ "${meditation_time//[0-9]/}" || "$meditation_time" -eq 0 ]] &&  meditation_time=20 # if not a digit or equals 0
+ volume="${2:-50}"  # Default volume setting is 50%.
   is_valid_integer "$volume" || volume="50"
-  volume+="%"   # convert volume to a percent.
-  check_alsa || { printf "%s Audio utilities not installed. Audio will not function.\n" "$RED_WARNING" >&2; sleep 5; }
+  volume+="%"   # make volume a percent.
+  check_package alsa-utils
   clear
   # Capture original volume setting
   orig_volume=$(get_volume)  # orig_volume is a percentage, ie 87%
   # Set playback volume
   set_volume "$volume"
-  printf "\n\t\U2638 Meditation Timer \U2638 \n\n"
+  printf "\n\t\U2638 %sMeditation Timer%s \U2638 \n\n" "$green" "$normal"
   screensaver_off
   prep_countdown
   play_sound "$audio_file"
   meditation_timer "$meditation_time"
   play_sound "$audio_file"
-  sleep 30
+  sleep 30  # wait for audio file to finish
   set_volume "$orig_volume"
-  printf "\n\n\U2638 %s v%s\n" "$script" "$version"
-  printf "\UA9 2021-2025 Richard B. Romig\n"
-  exit
+  printf "\n"
+  exit_script "$script" "$version"
 }
 
 ## Execution ##
