mint-fortune: updated GPL license & sourcing of function library

diff --git a/mint-fortune b/mint-fortune
--- a/mint-fortune
+++ b/mint-fortune
@@ -7,37 +7,25 @@
 # Author       : Copyright (C) 2019, Richard B. Romig, LudditeGeek@Mosfanet
 # Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
 # Created      : 04 May 2019
-# Updated      : 01 Apr 2026
-# Version      : 1.2.26091
+# Updated      : 31 Jul 2026
+# Version      : 1.3.26212
 # Comments     : does not check com.linuxmint.terminal show-fortunes
 # TODO (Rick)  :
 # License      : GNU General Public License, version 2.0
 # License URL  : https://github.com/RickRomig/scripts/blob/main/LICENSE
-##########################################################################
-# This program is free software; you can redistribute it and/or modify
-# it under the terms of the GNU General Public License as published by
-# the Free Software Foundation; either version 2 of the License, or
-# (at your option) any later version.
+###############################################################################
+# This program is free software; you can redistribute it and/or modify it under
+# the terms of the GNU General Public License as published by the Free Software
+# Foundation; either version 2 of the License, or (at your option) any later
+# version.
 #
-# This program is distributed in the hope that it will be useful,
-# but WITHOUT ANY WARRANTY; without even the implied warranty of
-# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
-# GNU General Public License for more details.
-#####################################################################
+# This program is distributed in the hope that it will be useful, but WITHOUT
+# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
+# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
+###############################################################################
 
-## Shellcheck Directives ##
-# shellcheck source=/home/rick/bin/functionlib
-
-## Load function library ##
-
-if [[ -x "$HOME/bin/functionlib" ]]; then
-  source "$HOME/bin/functionlib"
-else
-  echo -e "\e[91mERROR:\e[0m functionlib not found!" >&2
-  exit 81
-fi
-
-## Functions ##
+# shellcheck source=/home/rick/bin/functionlib.bash
+source ~/bin/functionlib.bash || { printf "\e[91mERROR:\e[0m Unable to source functionlib.bash\n"; exit 1; }
 
 show_fortune() {
   local cow number range
@@ -60,14 +48,14 @@ show_fortune() {
     1 )  command="/usr/games/cowthink" ;;
   esac
   /usr/games/fortune | $command -f $cow
+  return 0
 }
 
 main() {
   local packages=(cowsay fortune-mod)
   check_packages "${packages[@]}"
   [[ -x "/usr/games/fortune" ]] && [[ -x "/usr/games/cowsay" ]] && show_fortune
+  exit 0
 }
-
-## Execution ##
 
 main "$@"
