mk-bash - changed red_error variable to uppercase.

diff --git a/mk-bash b/mk-bash
--- a/mk-bash
+++ b/mk-bash
@@ -7,7 +7,7 @@
 # Author       : Copyright (C) 2023, Richard Romig, Mosfanet
 # Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
 # Created      : unknown
-# Last updated : 20 May 2024
+# Last updated : 31 Oct 2024
 # Comments     : Creates the script in the current working directory.
 # TODO (rick)  :
 # License      : GNU General Public License, version 2.0
@@ -28,8 +28,8 @@ fi
 ## Variables ##
 
 _script=$(basename "$0"); readonly _script
-readonly _version="3.6.24096"
-readonly _updated="20 May 2024"
+readonly _version="3.6.24305"
+readonly _updated="31 Oct 2024"
 readonly conf_dir="$HOME/.config/scripts"
 readonly conf_file="$_script.conf"
 today=$(date +"%d %b %Y"); readonly today
@@ -63,7 +63,7 @@ create_conf() {
 
 usage() {
 	local errcode="${1:-2}"
-	cat << END_HELP
+	cat << _HELP_
 ${green}Usage:${normal} $_script [OPTION]
 ${orange}OPTIONS:${normal}
   -b  Standard BASH script
@@ -74,7 +74,7 @@ ${orange}OPTIONS:${normal}
   -u  Usage instructions
   -v  Enable verbose mode
 $_script $_version ($_updated)
-END_HELP
+_HELP_
   exit "$errcode"
 }
 
@@ -93,7 +93,7 @@ while getopts "$optstr" opt; do
 	case "$opt" in
 		b )
 			filename="$OPTARG"
-			[[ -f "$filename" ]] && { printf "%s %s already exists\n" "$red_error" "$filename" >&2; usage 2; }
+			[[ -f "$filename" ]] && { printf "%s %s already exists\n" "$RED_ERROR" "$filename" >&2; usage 2; }
 			template_file="bash-template.txt"
       show_me "Template: $template_file"
 		;;
@@ -107,7 +107,7 @@ while getopts "$optstr" opt; do
 		;;
 		g )
 			filename="$OPTARG"
-			[[ -f "$filename" ]] && { printf "%s %s already exists\n" "$red_error" "$filename" >&2; usage 2; }
+			[[ -f "$filename" ]] && { printf "%s %s already exists\n" "$RED_ERROR" "$filename" >&2; usage 2; }
 			template_file="bash-getopts.txt"
       show_me "Template: $template_file"
 		;;
@@ -119,16 +119,16 @@ while getopts "$optstr" opt; do
 			show_me "Verbose mode enabled."
 		;;
     : )
-      printf "%s Must supply an argument to -%s.\n" "$red_error" "$OPTARG" >&2
+      printf "%s Must supply an argument to -%s.\n" "$RED_ERROR" "$OPTARG" >&2
       usage 2
     ;;
 		? )
-			printf "%s Invalid option -%s\n" "$red_error" "$OPTARG" >&2
+			printf "%s Invalid option -%s\n" "$RED_ERROR" "$OPTARG" >&2
 			usage 2
 	esac
 	noOpt=0
 done
-[[ "$noOpt" = 1 ]] && { printf "%s No argument passed.\n" "$red_error" >&2; usage 1; }
+[[ "$noOpt" = 1 ]] && { printf "%s No argument passed.\n" "$RED_ERROR" >&2; usage 1; }
 shift "$(( OPTIND - 1 ))"
 
 # [[ -z "$filename" ]] && leave "No script created."
