mk-changelog: udpated error checking

diff --git a/mk-changelog b/mk-changelog
--- a/mk-changelog
+++ b/mk-changelog
@@ -7,7 +7,7 @@
 # Author       : Copyright © 2019 Richard B. Romig, Mosfanet
 # Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
 # Created      : 09 Apr 2019
-# Updated      : 16 Nov 2025
+# Updated      : 05 Feb 2026
 # Comment      : Should be run from the project's main directory.'
 # TODO (rick)  :
 # License      : GNU General Public License, version 2.0
@@ -33,21 +33,21 @@ if [[ -x "$HOME/bin/functionlib" ]]; then
   source "$HOME/bin/functionlib"
 else
   echo -e "\e[91mERROR:\e[0m functionlib not found!" >&2
-  exit 1
+  exit 81
 fi
 
 ## Global Variables ##
 
 script_dir=$(dirname "$(readlink -f "${0}")"); readonly script_dir
 readonly script="${0##*/}"
-readonly version="2.1.25320"
+readonly version="2.2.26036"
 verbose_mode="$FALSE"
 
 ## Functions ##
 
 help() {
-  local errcode="${1:-2}"
-  local updated="16 Nov 2025"
+  local errcode="${1:-1}"
+  local updated="05 Feb 2026"
   cat << _HELP_
 ${orange}$script${normal} $version, updated: $updated
 Creates a changelog file for a project.
@@ -97,7 +97,7 @@ main() {
         project_name="$OPTARG"
         if [[ -f changelog.md ]]; then
           printf "%s changelog.md already exists.\n" "$RED_ERROR" >&2
-          help 2
+          help "$E_FILE_EXISTS"
         else
           show_message "Creating changelog for $project_name"
           create_changelog "$project_name"
@@ -112,15 +112,15 @@ main() {
 			  ;;
 			: )
 				  printf "%s Must supply an argument to -%s.\n" "$RED_ERROR" "$OPTARG" >&2
-				  help 2
+				  help "$E_MISSING_ARG"
         ;;
 			? )
 				printf "%s Invalid option -%s\n" "$RED_ERROR" "$OPTARG" >&2
-				help 2
+				help "$E_INVALID_ARG"
     esac
     noOpt=0
   done
-	[[ "$noOpt" = 1 ]] && { printf "%s No argument passed.\n" "$RED_ERROR" >&2; help 1; }
+	[[ "$noOpt" = 1 ]] && { printf "%s No argument passed.\n" "$RED_ERROR" >&2; help "$E_MISSING_ARG"; }
 	shift "$(( OPTIND - 1 ))"
 	over_line "$script $version"
 	exit
