mk-c-src - removed SC2035 shellcheck directive, no longer needed.

diff --git a/mk-c-src b/mk-c-src
--- a/mk-c-src
+++ b/mk-c-src
@@ -15,7 +15,6 @@
 
 ## Shellcheck Directives ##
 # shellcheck source=/home/rick/bin/functionlib
-# shellcheck disable=SC2034
 
 ## Load function library ##
 
@@ -57,7 +56,7 @@ create_conf() {
   " > "$conf_dir/$conf_file"
 }
 
-usage() {
+help() {
   local errcode="${1:-2}"
 	cat << END_HELP
 ${green}Usage:${normal} $_script [OPTION]
@@ -89,7 +88,7 @@ while getopts "$optstr" opt; do
 	case "$opt" in
 		c )
 			filename="$OPTARG"
-			[[ -f "$filename" ]] && { printf "%s %s already exists\n" "$red_error" "$filename" >&2; usage 2; }
+			[[ -f "$filename" ]] && { printf "%s %s already exists\n" "$red_error" "$filename" >&2; help 2; }
 			template_file="c-template.txt"
 		;;
 		e )
@@ -102,11 +101,11 @@ while getopts "$optstr" opt; do
 		;;
 		p )
 			filename="$OPTARG"
-			[[ -f "$filename" ]] && { printf "%s %s already exists\n" "$red_error" "$filename" >&2; usage 2; }
+			[[ -f "$filename" ]] && { printf "%s %s already exists\n" "$red_error" "$filename" >&2; help 2; }
 			template_file="cpp-template.txt"
 		;;
 		u )
-			usage 0
+			help 0
 		;;
 		v )
 			verbose_mode="$TRUE"
@@ -114,15 +113,15 @@ while getopts "$optstr" opt; do
 		;;
     : )
       printf "%s Must supply an argument to -%s.\n" "$red_error" "$OPTARG" >&2
-      usage 2
+      help 2
     ;;
 		? )
 			printf "%s Invalid option -%s\n" "$red_error" "$OPTARG" >&2
-			usage 2
+			help 2
 	esac
 	noOpt=0
 done
-[[ "$noOpt" = 1 ]] && { printf "%s No argument passed.\n" "$red_error" >&2; usage 1; }
+[[ "$noOpt" = 1 ]] && { printf "%s No argument passed.\n" "$red_error" >&2; help 1; }
 shift "$(( OPTIND - 1 ))"
 
 [[ -z "$filename" ]] && leave "No source code file created."
