mk-changelog - eliminated script conf; implemented main() & create_changelog

diff --git a/mk-changelog b/mk-changelog
--- a/mk-changelog
+++ b/mk-changelog
@@ -4,16 +4,17 @@
 # Description  : Create a changelog file from a template
 # Dependencies : sed
 # Arguments    : Project name
-# Author       : Richard B. Romig, 09 April 2019
-# Email        : rick.romig@gmail.com
-# Comment      :
+# Author       : Copyright © 2019 Richard B. Romig, Mosfanet
+# Email        : rick.romig@gmail.com | eick.romig@mymetronet.net
+# Created      : 09 Apr 2019
+# Updated      : 26 Feb 2025
+# Comment      : Should be run from the project's main directory.'
 # TODO (rick)  :
 # License      : GNU General Public License, version 2.0
 ###############################################################################
 
 ## Shellcheck Directives ##
 # shellcheck source=/home/rick/bin/functionlib
-# shellcheck disable=SC1091
 
 ## Load function library ##
 
@@ -24,77 +25,91 @@ else
   exit 1
 fi
 
-## Variables ##
+## Global Variables ##
 
-_script=$(basename "$0"); readonly _script
-readonly _version="1.0.2"
-readonly _updated="06 Dec 2023"
-readonly conf_dir="$HOME/.config/scripts"
-readonly conf_file="$_script.conf"
-today=$(date +"%d %B %Y"); readonly today
-
-# Data to insert into new bash script
-# template directory, copy_holder, email_addr, email_addr1, coder, license contained in script's .conf file.
+script=$(basename "$0"); readonly script
+readonly version="2.0.25057"
+verbose_mode="$FALSE"
 
 ## Functions ##
 
-create_conf() {
-  [[ -d "$conf_dir" ]] || mkdir -p "$conf_dir"
-  echo "Complete all fields"
-  read -rp "Full name: " copy_holder
-  read -rp "Primary email: " email_addr
-  read -rp "Alternate email: " email_addr1
-  read -rp "Template diretory (full path): " template_dir
-
-  echo "
-  copy_holder='$copy_holder'
-  email_addr='$email_addr'
-  email_addr1='$email_addr1'
-  template_dir='$template_dir'
-  " > "$conf_dir/$conf_file"
-}
-
-usage() {
+help() {
   local errcode="${1:-2}"
-  echo "${orange}Usage:${normal} $_script <project-name>"
-  echo "${orange}Example:${normal} $_script my-project"
+  local updated="26 Feb 2025"
+  cat << _HELP_
+${orange}$script${normal} $version, updated: $updated
+Creates a changelog file for a project.
+
+${green}Usage:${normal} $script <project-name>
+
+${orange}Available options:${normal}
+  -c  Create a changelog file
+      $script -c <project-name>
+  -h  Show this help message and exit
+  -v  Enable verbose mode (Must precede c flag)
+      $script -vc <project-name>
+_HELP_
   exit "$errcode"
 }
 
-## Execution ##
+show_message() {
+	local message="$1"
+	[[ "$verbose_mode" == "$TRUE" ]] && echo "$message"
+}
 
-## Source script configuration file ##
+create_changelog() {
+  local copy_holder email_addr email_addr1 project today template_dir
+  project="$1"
+  copy_holder="Richard B. Romig"
+  email_addr="rick.romig@gmail.com"
+  email_addr1="rick.romig@mymetronet.net"
+  today=$(date +"%d %B %Y")
+  template_dir="$HOME/bin/Templates"
 
-[[ -f "$conf_dir/$conf_file" ]] || create_conf
-source "$conf_dir/$conf_file"
-
-## Check arguments ##
-
-if [[ -z "$1" ]]; then
-  echo "${lightred}Error:${normal} No argment passed." >&2
-  usage 2
-elif [[ "$1" = "-h" || "$1" = "--help" ]]; then
-  echo "$_script v$_version ($_updated)"
-  usage 0
-else
-  project=$1
-fi
-
-# Introduction
-
-echo "$_script v$_version ($_updated)"
-echo "Creating a changelog.md template for project $project"
-
-# Fill in placeholders and create changelog.md
-
-sed -e '1d' \
+  sed -e '1d' \
     -e "s/<PROJECT>/$project/" \
     -e "s/<AUTHOR>/$copy_holder/" \
     -e "s/<EMAIL>/$email_addr/" \
     -e "s/<EMAIL1>/$email_addr1/" \
     -e "s/<DATE>/$today/" "$template_dir/changelog.txt" > changelog.md
+  printf "The changelog.md for %s has been created." "$$project"
+  edit_view_quit changelog.md
+}
 
-echo "The changelog.md for $project has been created."
-edit_view_quit changelog.md
+main() {
+  local noOpt opt optstr project_name
+  noOpt=1
+  optstr=":c:hv"
+  while getopts "$optstr" opt; do
+    case "$opt" in
+      c )
+        project_name="$OPTARG"
+        [[ -f changelog.md ]] && { printf "%s changelog.md already exists.\n" "$RED_ERROR" >&2; help 2; }
+        show_message "Preject: $project_name"
+        create_changelog "$project_name"
+      ;;
+			h )
+				help 0
+			;;
+			v )
+				verbose_mode="$TRUE"
+				show_message "Verbose mode enabled."
+			;;
+			: )
+				printf "%s Must supply an argument to -%s.\n" "$RED_ERROR" "$OPTARG" >&2
+				help 2
+      ;;
+			? )
+				printf "%s Invalid option -%s\n" "$RED_ERROR" "$OPTARG" >&2
+				help 2
+    esac
+  done
+	[[ "$noOpt" = 1 ]] && { printf "%s No argument passed.\n" "$RED_ERROR" >&2; help 1; }
+	shift "$(( OPTIND - 1 ))"
+	over_line "$script $version"
+	exit
+}
 
-exit
+## Execution ##
+
+main "$@"
