mk-fortunes: updated indentation; removed check_arguments, moved code into main()

diff --git a/mk-fortunes b/mk-fortunes
--- a/mk-fortunes
+++ b/mk-fortunes
@@ -7,8 +7,8 @@
 # Author       : Copyright (C) 2019, Richard B. Romig, MosfaNet
 # Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
 # Crated       : 04 May 2019
-# Updated      : 08 Aug 2026
-# Version      : 2.3.26219
+# Updated      : 09 Sep 2026
+# Version      : 2.4.26252
 # Comments     :
 # License      : GNU General Public License, version 2.0
 ## License URL  : https://github.com/RickRomig/scripts/blob/main/LICENSE
@@ -28,62 +28,54 @@
 source ~/bin/functionlib.bash || { printf "\e[91mERROR:\e[0m Unable to source functionlib.bash\n"; exit 1; }
 
 help() {
-  local -r script="$1"
-  local -r version="$2"
-  local -ri errcode="${3:-1}"
-  local -r updated="03 Jul 2026"
-  cat << _HELP_
-${orange}$script${normal} $version, updated: $updated
-Creates fortune cookie files for the fortune program.
+	local -r script="$1"
+	local -r version="$2"
+	local -ri errcode="${3:-1}"
+	local -r updated="09 Sep 2026"
+	cat <<- _HELP_
+	${orange}$script${normal} $version, updated: $updated
+	Creates fortune cookie files for the fortune program.
 
-${green}Usage:${normal} $script <cookie-file>
-${orange}Available options:${normal}
-  -h --help Show this help message and exit
+	${green}Usage:${normal} $script <cookie-file>
+	${orange}Available options:${normal}
+	-h --help	Show this help message and exit
 _HELP_
-  exit "$errcode"
-}
-
-check_arguments() {
-  local -r script="$1"
-  local -r version="$2"
-  if [[ "$#" -eq 0  ]]; then
-    printf "%s No argument passed." >&2 "$RED_ERROR"
-    help "$script" "$version" "$E_MISSING_ARG"
-  elif [[ "$1" = "-h" || "$1" = "--help" ]]; then
-    help "$script" "$version" 0
-  else
-    return 0
-  fi
+	exit "$errcode"
 }
 
 create_cookie_file() {
-  local -r cookiefile="$1"
-  local -r fortunes_d=/usr/share/games/fortunes
-  sudo_login 2
-  printf "Creating %s.dat...\n" "$cookiefile"
-  if strfile -c % "$cookiefile" "$cookiefile.dat"; then
-    sudo cp "$cookiefile" "$cookiefile.dat" "$fortunes_d"/
-    printf "Fortune cookie file created and copied to /%s\n" "$fortunes_d"
-    return 0
-  else
-    printf "Fortune cookie operation failed.\n"
-    return "$E_FILE_ERROR"
-  fi
+	local -r cookiefile="$1"
+	local -r fortunes_d=/usr/share/games/fortunes
+	sudo_login 2
+	printf "Creating %s.dat...\n" "$cookiefile"
+	if strfile -c % "$cookiefile" "$cookiefile.dat" 2>/dev/null; then
+		sudo cp "$cookiefile" "$cookiefile.dat" "$fortunes_d"/
+		printf "Fortune cookie file created and copied to /%s\n" "$fortunes_d"
+		return 0
+	else
+		printf "Fortune cookie operation failed.\n"
+		return "$E_FILE_ERROR"
+	fi
 }
 
 main() {
-  local script="${0##*/}"
-  local version="2.3.26219"
-  local -i exit_code=0
-  check_arguments "$script" "$version"
-  local -r cookiefile="$1"
-  if [[ -f "$cookiefile" ]]; then
-    printf "%s %s not found.\n" "$RED_ERROR" "$cookiefile" >&2
-    help "$script" "$version" "$E_FILENOTFOUND"
-  fi
-  check_package fortune-mod
-  create_cookie_file "$cookiefile"
-  exit_code="$?"
+	local script="${0##*/}"
+	local version="2.4.26252"
+	local -i exit_code=0
+	if [[ "$#" -eq 0  ]]; then
+		printf "%s No argument passed." >&2 "$RED_ERROR"
+		help "$script" "$version" "$E_MISSING_ARG"
+	elif [[ "$1" = "-h" || "$1" = "--help" ]]; then
+		help "$script" "$version" 0
+	fi
+	local -r cookiefile="$1"
+	if [[ -f "$cookiefile" ]]; then
+		printf "%s %s not found.\n" "$RED_ERROR" "$cookiefile" >&2
+		help "$script" "$version" "$E_FILENOTFOUND"
+	fi
+	check_package fortune-mod
+	create_cookie_file "$cookiefile"
+	exit_code="$?"
 	over_line "$script $version"
 	exit "$exit_code"
 }
