mk-fortunes - implemented main() & create_cookie_file(); updated help()

diff --git a/mk-fortunes b/mk-fortunes
--- a/mk-fortunes
+++ b/mk-fortunes
@@ -4,15 +4,16 @@
 # Description  : Create fortune files for the fortune program
 # Dependencies : strfile (fortune-mod)
 # Arguments    : fortune-cookie file (text)
-# Author       : Copyright (C) 2019, Richard B. Romig, 04 May 2019
+# Author       : Copyright (C) 2019, Richard B. Romig, MosfaNet
 # Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
+# Crated       : 04 May 2019
+# Updated      : 27 Feb 2025
 # Comments     :
 # License      : GNU General Public License, version 2.0
 ###############################################################################
 
 ## Shellcheck Directives ##
 # shellcheck source=/home/rick/bin/functionlib
-# shellcheck disable=SC1091
 
 ## Load function library ##
 
@@ -23,49 +24,55 @@ else
   exit 1
 fi
 
-## Variables ##
-
-_script=$(basename "$0"); readonly _script
-readonly _version="1.2.10"
-readonly _updated="05 Feb 2023"
-
 ## Functions ##
 
-usage() {
+help() {
   local errcode="${1:-2}"
-  echo "${orange}Usage:${normal} $_script <cookie-file>"
+  local updated="27 Feb 2025"
+  cat << _HELP_
+${orange}$script${normal} $version, updated: $updated
+Creates fortune cookie files for the fortune program.
+
+${green}Usage:${normal} $script <cookie-file>
+
+${orange}Available options:${normal}
+  -h --help Show this help message and exit
+_HELP_
   exit "$errcode"
+}
+
+create_cookie_file() {
+  local cookiefile="$1"
+  local fortunes_d="/usr/share/games/fortunes"
+  sudo_login 2
+  printf "Creating %s.dat...\n" "$cookiefile"
+  if strfile -c % "$cookiefile" "$cookiefile.dat"; then
+    sudo cp "$cookiefile" "$cookiefile.dat" "$fortunes_d"/
+    printf "Fortune cookie file created and copied to /%s\n" "$fortunes_d"
+  else
+    die "Fortune cookie operation failed." 1
+  fi
+}
+
+main() {
+  local cookiefile script version
+  script=$(basename "$0")
+  version="2.0.25058"
+  if [[ "$#" -eq 0 ]]; then
+    printf "%s No argument passed." >&2 "$RED_ERROR"
+    help 2
+  elif [[ "$1" = "-h" || "$1" = "--help" ]]; then
+    help 0
+  else
+    cookiefile="$1"
+    [[ -f "$cookiefile" ]] || { printf "%s %s not found.\n" "$RED_ERROR" "$cookiefile" >&2; help 1; }
+    check_package fortune-mod
+    create_cookie_file "$cookiefile"
+	  over_line "$script $version"
+	  exit
+  fi
 }
 
 ## Execution ##
 
-check_package forturn-mode
-
-echo "$_script v$_version ($_updated)"
-echo "Creates fortune cookie files for the fortune program"
-
-# Check arguments
-
-if [[ $# -eq 0 ]]; then
-  echo "${lightred}Error:${normal} No argument passed." >&2
-  usage 2
-elif [[ "$1" = "-h" || "$1" = "--help" ]]; then
-  echo "$_script v$_version ($_updated)"
-  usage 0
-else
-  cookiefile=$1
-fi
-
-# Check if cookiefile exists and process if it does
-if [[ -f "$cookiefile" ]]; then
-  if strfile -c % "$cookiefile" "$cookiefile.dat"; then
-    sudo cp "$cookiefile" "$cookiefile.dat" /usr/share/games/fortunes/
-  else
-    die "strfile operation failed." 1
-  fi
-else
-  echo "${lightred}Error:${normal} $cookiefile does not exist. Check spelling." >&2
-  usage 2
-fi
-
-leave "Fortune cookie files created and copied to /usr/share/games/fortunes"
+main "$@"
