v0.2.1 - removed extra newlines.

diff --git a/mount-bu b/mount-bu
--- a/mount-bu
+++ b/mount-bu
@@ -27,8 +27,8 @@ fi
 ## Variables ##
 
 readonly _script=$(basename "$0")
-readonly _version="0.2.0"
-readonly _updated="08 Jul 2022"
+readonly _version="0.2.1"
+readonly _updated="10 Oct 2022"
 readonly mount_location="/media/rick/BU_Drive"
 
 ## Functions ##
@@ -81,7 +81,7 @@ EOL
 ## Execution ##
 
 printf "\U1F427 %s v%s (%s)\n" "$_script" "$_version" "$_updated"
-printf "Mount/Unmount USB Backup drive.\n\n"
+printf "Mount/Unmount USB Backup drive.\n"
 
 if [[ $# -eq 0 ]]; then
   printf "\n\e[91mERROR:\e[0m No argument passed\n" >&2
@@ -111,7 +111,7 @@ else
         fi
         break ;;
       ? )
-        printf "\n\e[91mERROR:\e[0m Invalid option -%s\n" "$OPTARG" >&2
+        printf "\e[91mERROR:\e[0m Invalid option -%s\n" "$OPTARG" >&2
         help 2 ;;
     esac
   done
