mount-bu: mount-point is now a local variable pass to mount_bu() & umount_bu() by main()

diff --git a/mount-bu b/mount-bu
--- a/mount-bu
+++ b/mount-bu
@@ -7,7 +7,7 @@
 # Author       : Copyright (C) 2022, Richard B. Romig, 04 Jul 2022
 # Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
 # Created      : 04 Jul 2022
-# Updated      : 27 Mar 2026
+# Updated      : 27 May 2026
 # Comments     : For use with BU backup script.
 # TODO (Rick)  :
 # License      : GNU General Public License, version 2.0
@@ -24,30 +24,21 @@
 # GNU General Public License for more details.
 ##########################################################################
 
-## Shellcheck Directives ##
+## Load function library ##
 # shellcheck source=/home/rick/bin/functionlib
-
-## Source function library ##
-
-if [[ -x "$HOME/bin/functionlib" ]]; then
-  source "$HOME/bin/functionlib"
-else
-  printf "\e[91mERROR:\e[0m functionlib not found!\n" >&2
-  exit 81
-fi
+source ~/bin/functionlib || { printf "\e[91mERROR:\e[0m Unable to source functionlib\n"; exit 1; }
 
 ## Variables ##
 
 readonly script="${0##*/}"
-readonly version="2.22.26086"
-readonly mount_point="/media/$USER/BU_Drive"
+readonly version="2.23.26147"
 
 ## Functions ##
 
 help() {
   local errcode updated
 	errcode="${1:-1}"
-	updated="27 Mar 2026"
+	updated="27 May 2026"
 	cat << _HELP_
   ${orange}$script${normal} $version, Updated $updated
   Mounts/Unmounts USB backup drive for the BU script.
@@ -66,19 +57,21 @@ _HELP_
 }
 
 mount_bu() {
+  local -r mount_point="$1"
   local usbdrv
-  usbdrv="$(awk '/BU_Drive/ {print $1}' <(lsblk -fs))"
+  usbdrv="$(awk '/BU_Drive/ {print $1}' < <(lsblk -fs))"
   sudo_login 2
   printf "Mounting backup drive: /dev/%s to %s ...\n" "$usbdrv" "$mount_point"
   [[ -d "$mount_point" ]] || sudo mkdir -p "$mount_point"
   sudo mount /dev/"$usbdrv" "$mount_point"
-  printf "Backup drive (/dev/%s) is mounted at %s\n" "$usbdrv" "$(awk '/BU_Drive/ {print $3}' <(mount))"
+  printf "Backup drive (/dev/%s) is mounted at %s\n" "$usbdrv" "$(awk '/BU_Drive/ {print $3}' < <(mount))"
   notify-send -t 2000 -i "$HOME/.icons/usb-drive-fill.png" "BU_Drive" "is mounted"
 }
 
 umount_bu() {
+  local -r mount_point="$1"
   local usbdrv
-  usbdrv=$(awk '/BU_Drive/ {print $1}' <(mount))
+  usbdrv=$(awk '/BU_Drive/ {print $1}' < <(mount))
   sudo_login 2
   printf "Unmounting USB Backup drive at %s ...\n" "$mount_point"
   sudo umount "$mount_point"
@@ -89,7 +82,7 @@ umount_bu() {
 
 bu_status() {
   printf "BU_Drive is "
-  if grep -qw BU_Drive <(lsblk); then
+  if grep -qw BU_Drive < <(lsblk); then
     printf "mounted.\n"
     notify-send -t 2000 -i "$HOME/.icons/usb-drive-fill.png" "BU_Drive" "is mounted"
     return "$TRUE"
@@ -101,8 +94,9 @@ bu_status() {
 }
 
 main() {
-  local noOpt opt optstr OPTARG OPTIND
   grep -qw 'usb' <(lsblk -S -o TRAN) || die "BU_Drive not attached." "$E_DRIVE_ERROR"
+  local noOpt opt optstr OPTARG OPTIND
+  local -r mount_point="/media/$USER/BU_Drive"
   noOpt=1
   optstr=":hmsu"
   while getopts "$optstr" opt; do
@@ -114,7 +108,7 @@ main() {
         if bu_status; then
           printf "No further action necessary.\n"
         else
-          mount_bu
+          mount_bu "$mount_point"
         fi
         ;;
       s )
@@ -122,7 +116,7 @@ main() {
         ;;
       u )
         if bu_status; then
-          umount_bu
+          umount_bu "$mount_point"
         else
           printf "No further action necessary.\n"
         fi
