mount-sshfs 0.3.1 - added EliteBook 850 G3 (22) to list.

diff --git a/mount-sshfs b/mount-sshfs
--- a/mount-sshfs
+++ b/mount-sshfs
@@ -4,9 +4,9 @@
 # Description  : Mount or unmount an SSHFS share.
 # Dependencies : sshfs
 # Arguments    : None
-# Author       : Richard B. Romig, 18 May 2020
-# Email        : rick.romig@gmail.com
-# Comments     : Mount points at ~/mnt/
+# Author       : Copyright (C) 2020 Richard B. Romig, 18 May 2020
+# Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
+# Comments     : Mount points are at ~/mnt/
 # TODO (Rick)  :
 # License      : GNU General Public License, version 2.0
 ##########################################################################
@@ -27,8 +27,8 @@ fi
 ## Variables ##
 
 readonly _script=$(basename "$0")
-readonly _version="0.3.1"
-readonly _updated="15 Dec 2022"
+readonly _version="0.3.2"
+readonly _updated="08 Jan 2023"
 
 ## Functions ##
 
@@ -99,7 +99,8 @@ check_package sshfs
 
 echo "$_script v$_version ($_updated)"
 echo -e "Mount or unmount an SSHFS share.\n"
-options=( "Mount Finance" "Unmount Finance" "Mount ProBook-6570" "Unmount ProBook-6570" "Mount HP-6005" "Unmount HP-6005" "Mount NAS" "Unmount NAS" "Quit" )
+options=( "Mount Finance" "Unmount Finance" "Mount ProBook-6570" "Unmount ProBook-6570" "Mount 850-G3" "Unmount 850-G3" \
+"Mount HP-6005" "Unmount HP-6005" "Mount NAS" "Unmount NAS" "Quit" )
 COLUMNS=60
 PS3="Choose an action: "
 select opt in "${options[@]}"; do
@@ -108,12 +109,14 @@ select opt in "${options[@]}"; do
     2 ) unmount_share "HP-ProBook-6570b"; break ;;
     3 ) mount_share 20 "ProBook-6570b"; break ;;
     4 ) unmount_share "ProBook-6570b"; break ;;
-    5 ) mount_share 11 "HP-6005"; break ;;
-    6 ) unmount_share "HP-6005"; break ;;
-    7 ) mount_share 4 "NASD97167"; break ;;
-    8 ) unmount_share "NASD97167"; break ;;
-    9 ) echo "Exiting. No action taken."; break ;;
-    * ) echo "${lightred}Invalid option.${normal} Choose 1-9." >&2 ;;
+    5 ) mount_share 22 "EliteBook-850"; break ;;
+    6 ) unmount_share "EliteBook-850"; break ;;
+    7 ) mount_share 11 "HP-6005"; break ;;
+    8 ) unmount_share "HP-6005"; break ;;
+    9 ) mount_share 4 "NASD97167"; break ;;
+    10 ) unmount_share "NASD97167"; break ;;
+    11 ) echo "Exiting. No action taken."; break ;;
+    * ) echo "${lightred}Invalid option.${normal} Choose 1-11." >&2 ;;
   esac
 done
 exit
