0.8.0 - Configuration files are downloaded from Gitea server instead of the HP-6005. No need for a temporary directory.

diff --git a/new-config b/new-config
--- a/new-config
+++ b/new-config
@@ -2,10 +2,10 @@
 ###############################################################################
 # Script Name  : new-config
 # Description  : Sets up custom configurations for a new Linux system
-# Dependencies : sshfs
+# Dependencies : curl
 # Arguments    : None
-# Author       : Richard B. Romig, 15 August 2019
-# Email        : rick.romig@gmail.com
+# Author       : Copyright (C) 2019, Richard B. Romig, 15 August 2019
+# Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
 # Comments     :
 # TODO (rick)  : Convert to gethopts
 # License      : GNU General Public License, version 2.0
@@ -27,10 +27,10 @@ fi
 ## Variables ##
 
 _script=$(basename "$0"); readonly _script
-readonly _version="0.7.8"
-readonly _updated="30 Sep 2022"
-readonly svr_ip="11"
-readonly cfg_bu="$HOME/.config/backup"
+readonly _version="0.8.0"
+readonly _updated="13 Oct 2023"
+readonly cfg_bu_dir="$HOME/.config/backup"
+readonly repo_path="configs/raw/branch/main/"
 
 count=0
 
@@ -40,82 +40,55 @@ check_dependencies() {
   check_package sshfs
 }
 
-mod_bashrc() {
-  local head_file="$HOME/bin/files/bashrc-head"
-  local tail_file="$HOME/bin/files/bashrc-tail"
-  local sed_file="$HOME/bin/files/bashrc.sed"
-
-  # Backup original .bashrc
-  cp -pv "$HOME/.bashrc" "$cfg_bu/.bashrc.orig"
-  echo "Original .bashrc backed up to $cfg_bu"
-
-  # Modify the .bashrc
-  sed -i -e "1 { r $head_file" -e "N; }" "$HOME/.bashrc"
-  sed -i -f "$sed_file" "$HOME/.bashrc"
-  cat "$tail_file" >> "$HOME/.bashrc"
-  echo "Customized .bashrc installed in the home directory."
+dl_bashrc() {
+  cp -pv "$HOME/.bashrc" "$cfg_bu_dir/.bashrc.orig"
+  curl -so "$HOME/.bashrc" "$Gitea_URL/$repo_path/.bashrc"
+  printf "Custom .bashrc installed in the home directory.\n"
   (( count++ ))
 }
 
-cp_aliases() {
-  if [[ -f "$HOME/.bash_aliases" ]]; then
-    cp -pv "$HOME/.bash_aliases" "$cfg_bu/.bash_aliases.orig"
-    echo "Original .bash_aliases backed up to $cfg_bu"
-  fi
-  cp -pv "$cfg_src/.bash_aliases" "$HOME/"
-  echo "Customized .bash_aliases added to the home directory."
+dl_aliases() {
+  [[ -f "$HOME/.bash_aliases" ]] && cp -pv "$HOME/.bash_aliases" "$cfg_bu_dir/.bash_aliases.orig"
+  curl -so "$HOME/.bash_aliases" "$Gitea_URL/$repo_path/.bash_aliases"
+  printf "Custom .bash_aliases added to the home directory.\n"
   (( count++ ))
 }
 
-mod_profile() {
-  if [[ -f "$HOME/.profile" ]]; then
-    cp -pv "$HOME/.profile" "$cfg_bu/.profile.orig"
-    echo "Original .profile backed up to $cfg_bu"
-  fi
-  cat "$HOME/bin/files/profile-append" >> "$HOME/.profile"
-  [[ -d "$HOME/.local/state" ]] || mkdir -p  "$HOME/.local/state"
-  echo "Customized .profile installed in the home directory."
+dl_profile() {
+  [[ -f "$HOME/.profile" ]] && cp -pv "$HOME/.profile" "$cfg_bu_dir/.profile.orig"
+  curl -so "$HOME/.profile" "$Gitea_URL/$repo_path/.profile"
+  printf "Custom .profile installed in the home directory.\n"
   (( count++ ))
 }
 
-mod_nanorc() {
-  nano_ver=$(nano --version | awk '/version/ {print $NF}')
-  [[ -d "$cfg_bu/nano" ]] || mkdir -p "$cfg_bu/nano"
-  # Backup  original .nanorc
-  if [[ -f "$HOME/.nanorc" ]]; then
-    cp -pv "$HOME/.nanorc" "$cfg_bu/nano/nanorc.orig"
-    echo ".nanorc backed up to $cfg_bu/nano"
-  elif [[ -f "$HOME/.config/nano/nanorc" ]]; then
-    cp -pv "$HOME/.config/nano/nanorc" "$cfg_bu/nano/nanorc.orig"
-    echo "nanorc backed up to $cfg_bu"
-  fi
-  # Copy and configure nanorc
+dl_nanorc() {
+  [[ -d "$cfg_bu_dir/nano" ]] || mkdir -p "$cfg_bu_dir/nano"
   [[ -d "$HOME/.config/nano" ]] || mkdir -p "$HOME/.config/nano"
-  cp -v /etc/nanorc "$HOME/.config/nano/"
-  sed -i -f "$HOME/bin/files/nano.sed" "$HOME/.config/nano/nanorc"
+  # Backup  original .nanorc
+  [[ -f "$HOME/.nanorc" ]] && cp -pv "$HOME/.nanorc" "$cfg_bu_dir/nano/nanorc.orig"
+  [[ -f "$HOME/.config/nano/nanorc" ]] && cp -pv "$HOME/.config/nano/nanorc" "$cfg_bu_dir/nano/nanorc.orig"
+  # Downlaod nanorc
+  curl -so "$HOME/.config/nano/nanorc" "$Gitea_URL/$repo_path/nano/nanorc"
   # Remove old .nanorc files
-  [[ -f "$HOME/.nanorc" ]] && rm -v "$HOME/.nanorc"
-  [[ -f "$cfg_bu/.nanorc" ]] && rm -v "$cfg_bu/.nanorc"
-  echo "Customized nanorc for nano version $nano_ver added."
+  [[ -f "$HOME/.nanorc" ]] && rm "$HOME/.nanorc"
+  [[ -f "$cfg_bu_dir/.nanorc" ]] && rm "$cfg_bu_dir/.nanorc"
+  printf "Custom nanorc installed.\n"
   (( count++ ))
 }
 
-cp_face() {
-  if [[ -f "$HOME/.face" ]]; then
-    cp -pv "$HOME/.face" "$cfg_bu/.face.orig"
-    echo ".face backed up to $cfg_bu"
-  fi
-  cp -pv "$cfg_src/face" "$HOME/.face"
-  echo "Customized .face added to the home directory."
+dl_face() {
+  [[ -f "$HOME/.face" ]] && cp -pv "$HOME/.face" "$cfg_bu_dir/.face.orig"
+  curl -so "$HOME/.face" "$Gitea_URL/$repo_path/.face"
+  printf ".face added to the home directory.\n"
   (( count++ ))
 }
 
-cinnamon_keybindings() {
+dl_cinnamon_keybindings() {
   if is_cinnamon; then
-    cp -pv "$cfg_src/keybindings-backup.dconf" "$tmp_dir"
-    dconf load /org/cinnamon/desktop/keybindings/ < "$tmp_dir/keybindings-backup.dconf"
-    dconf dump /org/cinnamon/desktop/keybindings/ > "/$HOME/.config/keybindings-backup.dconf"
-    echo "Cinnamon Custom Keybindings installed."
+    local cinnamon_keybindings="keybindings-backup.dconf"
+    curl -so "$HOME/.config/$cinnamon_keybindings" "$Gitea_URL/$repo_path/$cinnamon_keybindings"
+    dconf load /org/cinnamon/desktop/keybindings/ < "$HOME/.config/$cinnamon_keybindings"
+    printf "Cinnamon Keybindings installed.\n"
     (( count++ ))
   else
     echo $'\n'$"The desktop environment is not Cinnamon." >&2
@@ -135,69 +108,63 @@ main() {
     select opt in "${options[@]}"; do
       case "$REPLY" in
         1 )
-          mod_bashrc
+          dl_bashrc
           anykey
-          break ;;
+          break
+        ;;
         2 )
-          cp_aliases
+          dl_aliases
           anykey
-          break ;;
+          break
+        ;;
         3 )
-          cp_face
+          dl_face
           anykey
-          break ;;
+          break
+        ;;
         4 )
-          mod_nanorc
+          dl_nanorc
           anykey
-          break ;;
+          break
+        ;;
         5 )
-          mod_profile
+          dl_profile
           anykey
-          break ;;
+          break
+        ;;
         6 )
-          cinnamon_keybindings
+          dl_cinnamon_keybindings
           anykey
-          break ;;
+          break
+        ;;
         7 )
-          mod_bashrc
-          cp_aliases
-          mod_profile
-          mod_nanorc
-          cp_face
-          cinnamon_keybindings
+          dl_bashrc
+          dl_aliases
+          dl_profile
+          dl_nanorc
+          dl_face
+          dl_cinnamon_keybindings
           anykey
-          break ;;
+          break
+        ;;
         8 )
           if (( count == 0 )); then
-            leave "No custom configuration files installed."
+            printf "No custom configuration files installed.\n"
           else
-            leave "Custom configurations installed."
+            printf "Custom configurations installed.\n"
           fi
-          break ;;
+          break
+        ;;
         * )
-          echo "${lightred}Invalid choice.${normal} Try again" >&2 ;;
+          printf "%s Invalid choice.%s Try again\n" "$lightred" "$normal" >&2
       esac
     done
   done
+  leave "$_script v$_version ($_updated)"
 }
 
 ## Execution ##
 
 check_dependencies
-
-# Check local IP address
-ip_addr="$(local_ip)"
-if [[ "$ip_addr" -eq "$svr_ip" ]]; then
-  cfg_src="/data/installation/configs"
-else
-  cfg_src="$HOME/mnt/HP-6005/installs/configs"
-  mount_server
-fi
-
-# Create directories if they don't exist
-[[ -d "$cfg_bu" ]] || mkdir -p "$cfg_bu"
-tmp_dir=$(mktemp -dq) || die "Failed to create temporary directory."
-tmp_file=$(mktemp -q) || die "Failed to create tempoary file."
-trap unmount_server EXIT
-
+[[ -d "$cfg_bu_dir" ]] || mkdir -p "$cfg_bu_dir"
 main
