no-flatpak - placed getopts in main(); updated help()

diff --git a/no-flatpak b/no-flatpak
--- a/no-flatpak
+++ b/no-flatpak
@@ -27,9 +27,9 @@ fi
 
 ## Variables ##
 
-_script=$(basename "$0"); readonly _script
-readonly _version="1.1.24115"
-readonly _updated="24 Apr 2024"
+script=$(basename "$0"); readonly script
+readonly version="1.1.24115"
+readonly updated="24 Apr 2024"
 readonly pref_file="/etc/apt/preferences.d/noflatpak.pref"
 
 ## Functions ##
@@ -90,49 +90,55 @@ NO_FLATPAK
 }
 
 help() {
-  local errcode="${1:=2}"
-  cat << END_HELP
-${green}Usage:${normal} $_script [OPTION]
+ local errcode updated
+	errcode="${1:-2}"
+	updated="02 Oct 2024"
+	cat << _HELP_
+${green}Usage:${normal} $script [OPTION]
 ${orange}OPTIONS:${normal}
   -e    Enable the installation of flatpak and flatpak packages
   -d    Disable the installation of flatpak and flatpak packages
   -h    Help
   -s    Status of flatpak and flatpak package installation
-$_script v$_version, updated $_updated
-END_HELP
+$script v$version, updated $updated
+_HELP_
   exit "$errcode"
+}
+
+main() {
+  local noOpt opt optstr
+	printf "Enables or disables the installation of flatpak and flatpak packages.\n"
+	check_flatpak_installed
+	noOpt=1
+	optstr=":dehs"
+	while getopts "$optstr" opt; do
+		case "$opt" in
+			d )
+				sudo_login 2
+				disable_flatpak
+			;;
+			e )
+				sudo_login 2
+				enable_flatpak
+			;;
+			h )
+				help 0
+			;;
+			s )
+				printf "\nStatus of flatpak and flatpak packages: "
+				flatpak_status && printf "Flatpaks are enabled.\n" || printf "Flatpaks are disabled.\n"
+			;;
+			? )
+				printf "\n%s Invalid option -%s\n" "$RED_ERROR" "$OPTARG" >&2
+				help 2
+		esac
+		noOpt=0
+	done
+	[[ "$noOpt" = 1 ]] && { printf "%s No argument passed.\n" "$RED_ERROR" >&2; help 1; }
+	shift "$(( OPTIND - 1 ))"
+	leave "$script v$version"
 }
 
 ## Execution ##
 
-printf "Enables or disables the installation of flatpak and flatpak packages.\n"
-check_flatpak_installed
-
-noOpt=1
-optstr=":dehs"
-while getopts "$optstr" opt; do
-	case "$opt" in
-		d )
-			sudo_login 2
-			disable_flatpak
-		;;
-		e )
-			sudo_login 2
-			enable_flatpak
-		;;
-		h )
-			help 0
-		;;
-		s )
-			printf "\nStatus of flatpak and flatpak packages: "
-			flatpak_status && printf "Flatpaks are enabled.\n" || printf "Flatpaks are disabled.\n"
-		;;
-		? )
-			printf "\n%s Invalid option -%s\n" "$red_error" "$OPTARG" >&2
-			help 2
-	esac
-	noOpt=0
-done
-[[ "$noOpt" = 1 ]] && { printf "%s No argument passed.\n" "$red_error" >&2; help 1; }
-shift "$(( OPTIND - 1 ))"
-leave "$_script v$_version"
+main "$@"
