numfiles: updated sourcing of function library

diff --git a/numfiles b/numfiles
--- a/numfiles
+++ b/numfiles
@@ -8,28 +8,24 @@
 # Author       : Copyright (C) 2018, Richard Romig, MosfaNet
 # Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
 # Created      : 22 Nov 2018
-# Updated      : 23 Jun 2026
+# Updated      : 01 Aug 2026
+# Version      : 4.5.26213
 # Comment      :
 # TODO (Rick)  :
 # License      : GNU General Public License, version 2.0
 # License URL  : https://github.com/RickRomig/scripts/blob/main/LICENSE
 ###############################################################################
-# This program is free software; you can redistribute it and/or modify
-# it under the terms of the GNU General Public License as published by
-# the Free Software Foundation; either version 2 of the License, or
-# (at your option) any later version.
+# This program is free software; you can redistribute it and/or modify  it under
+# the terms of the GNU General Public License as published by the Free Software
+# Foundation; either version 2 of the License, or (at your option) any later version.
 #
-# This program is distributed in the hope that it will be useful,
-# but WITHOUT ANY WARRANTY; without even the implied warranty of
-# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
-# GNU General Public License for more details.
+# This program is distributed in the hope that it will be useful, but WITHOUT
+# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
+# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
 ###############################################################################
 
-## Source function library ##
-# shellcheck source=/home/rick/bin/functionlib
-source ~/bin/functionlib || { printf "\e[91mERROR:\e[0m Unable to source functionlib\n"; exit 1; }
-
-## Functions ##
+# shellcheck source=/home/rick/bin/functionlib.bash
+source ~/bin/functionlib.bash || { printf "\e[91mERROR:\e[0m Unable to source functionlib.bash\n"; exit 1; }
 
 num_files() {
 	local ndirs nfiles size
@@ -44,16 +40,15 @@ num_files() {
 	[[ "$ndirs" -eq "1" ]] && printf "directory " || printf "directories "
 	printf "using %s of disk space.\n" "$size"
 	unset ndirs nfiles size
+	return 0
 }
 
 main() {
-	local script="${0##*/}"
-	local version="4.4.26174"
+	local -r script="${0##*/}"
+	local -r version="4.5.26213"
 	num_files
 	over_line "$script $version"
 	exit
 }
-
-## Execution ##
 
 main "$@"
