odt-to-txt: updated indentation

diff --git a/odt-to-txt b/odt-to-txt
--- a/odt-to-txt
+++ b/odt-to-txt
@@ -7,8 +7,8 @@
 # Author       : Copyright (C) 2019, Richard B. Romig, MosfaNet
 # Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
 # Created      : 10 May 2019
-# Updated      : 08 Aug 2026
-# Version      : 3.3.26219
+# Updated      : 09 Sep 2026
+# Version      : 3.4.26252
 # Comments     : Run from a directory containing .odt files to be converted.
 #              : Leaves original .odt files intact.
 # TODO (rick)  :
@@ -29,121 +29,109 @@
 source ~/bin/functionlib.bash || { printf "\e[91mERROR:\e[0m Unable to source functionlib.bash\n"; exit 1; }
 
 check_dependencies() {
-  local packages=(fzf odt2txt)
-  check_packages "${packages[@]}"
-  return 0
+	local -r packages=(fzf odt2txt)
+	check_packages "${packages[@]}"
+	return 0
 }
 
 convert_2_txt() {
-  local odt_file=$1
-  local txt_file="${odt_file%%.*}.txt"
-  /usr/bin/odt2txt "$odt_file" > "$txt_file"
-  echo "$odt_file -> $txt_file"
-  return 0
+	local -r odt_file=$1
+	local -r txt_file="${odt_file%%.*}.txt"
+	/usr/bin/odt2txt "$odt_file" > "$txt_file"
+	echo "$odt_file -> $txt_file"
+	return 0
 }
 
 convert_2_md() {
-  local odt_file=$1
-  local md_file="${odt_file%%.*}.md"
-  /usr/bin/odt2txt "$odt_file" > "$md_file"
-  echo "$odt_file -> $md_file"
-  return 0
+	local -r odt_file=$1
+	local -r md_file="${odt_file%%.*}.md"
+	/usr/bin/odt2txt "$odt_file" > "$md_file"
+	echo "$odt_file -> $md_file"
+	return 0
 }
 
 odt_files_found() {
-  local num_files
-  num_files=$(wc -l < <(find . -maxdepth 1 -type f -iname "*.odt"))
-  (( num_files > 0 )) && return "$TRUE" || return "$FALSE"
-  return 0
+	local -i num_files
+	num_files=$(wc -l < <(find . -maxdepth 1 -type f -iname "*.odt"))
+	(( num_files > 0 )) && return "$TRUE" || return "$FALSE"
 }
 
 list_odt_files() {
-  printf ".odt filse in %s:\n\n" "$PWD"
-  sed 's/^\.\///' < <(find ./ -maxdepth 1 -type f -name "*.odt") | sort
-  return 0
+	printf ".odt filse in %s:\n\n" "$PWD"
+	sed 's/^\.\///' < <(find ./ -maxdepth 1 -type f -name "*.odt") | sort
+	return 0
 }
 
 select_odt_file() {
-  local odt_file
-  odt_file=$(sed 's/^\.\///' < <(find . -maxdepth 1 -type f -name "*.odt") | sort -d | fzf --height 40% --reverse --prompt "Select the file to convert: ")
-  echo "$odt_file"
-  return 0
+	local odt_file
+	odt_file=$(sed 's/^\.\///' < <(find . -maxdepth 1 -type f -name "*.odt") | sort -d | fzf --height 40% --reverse --prompt "Select the file to convert: ")
+	echo "$odt_file"
+	return 0
 }
 
 main() {
-  local -r script="${0##*/}"
-  local -r version="3.3.26219"
-  local options _opt ofile
-
-  check_dependencies
-
-  while true; do
-    clear
-    printf "Converts *.odt files to *.txt or *.md\n"
-    under_line "${lightyellow}Use with care. May overwrite existing .txt or .md files.${normal}" "*"
-    COLUMNS=12
-    printf "\nAvailable operations:\n"
-    options=(
-      "Convert a single .odt file to .txt"
-      "Convert a single .odt file to .md"
-      "Convert all .odt files to .txt"
-      "Convert all .odt files to .md"
-      "Quit and exit"
-    )
-    PS3="Choose an option: "
-    select _opt in "${options[@]}"; do
-      case $REPLY in
-        1 )
-          ofile=$(select_odt_file)
-          printf "Converting %s to text.\n" "$ofile"
-          convert_2_txt "$ofile"
-          anykey
-          break
-          ;;
-        2 )
-          ofile=$(select_odt_file)
-          printf "Converting %s to markdown.\n" "$ofile"
-          convert_2_md "$ofile"
-          anykey
-          break
-          ;;
-        3 )
-          if odt_files_found; then
-            list_odt_files
-            printf "Converting .odt files in %s to text...\n\n" "$PWD"
-            for ofile in *.odt; do
-              convert_2_txt "$ofile"
-            done
-          else
-            printf "No .odt files found.\n"
-          fi
-          anykey
-          break
-          ;;
-        4 )
-          if odt_files_found; then
-            list_odt_files
-            printf "Converting .odt files in %s to markdown...\n\n" "$PWD"
-            for ofile in *.odt; do
-              convert_2_md "$ofile"
-            done
-          else
-            printf "No .odt files found.\n"
-          fi
-          anykey
-          break
-          ;;
-        5 )
-          printf "All done! Exiting the script.\n"
-          break 2
-          ;;
-        * )
-          echo "${lightred}Invalid Option!${normal} Choose 1 - 5" >&2
-      esac
-    done
-  done
-  over_line "$script $version"
-  exit
+	local -r script="${0##*/}"
+	local -r version="3.4.26252"
+	local options _opt ofile
+	check_dependencies
+	while true; do
+		clear
+		printf "Converts *.odt files to *.txt or *.md\n"
+		under_line "${lightyellow}Use with care. May overwrite existing .txt or .md files.${normal}" "*"
+		COLUMNS=12
+		printf "\nAvailable operations:\n"
+		options=(
+			"Convert a single .odt file to .txt"
+			"Convert a single .odt file to .md"
+			"Convert all .odt files to .txt"
+			"Convert all .odt files to .md"
+			"Quit and exit"
+		)
+		PS3="Choose an option: "
+		select _opt in "${options[@]}"; do
+			case $REPLY in
+				1 )
+					ofile=$(select_odt_file)
+					printf "Converting %s to text.\n" "$ofile"
+					convert_2_txt "$ofile"
+					anykey
+					break ;;
+				2 )
+					ofile=$(select_odt_file)
+					printf "Converting %s to markdown.\n" "$ofile"
+					convert_2_md "$ofile"
+					anykey
+					break ;;
+				3 )
+					if odt_files_found; then
+						list_odt_files
+						printf "Converting .odt files in %s to text...\n\n" "$PWD"
+						for ofile in *.odt; do convert_2_txt "$ofile"; done
+					else
+						printf "No .odt files found.\n"
+					fi
+					anykey
+					break ;;
+				4 )
+					if odt_files_found; then
+						list_odt_files
+						printf "Converting .odt files in %s to markdown...\n\n" "$PWD"
+						for ofile in *.odt; do convert_2_md "$ofile"; done
+					else
+						printf "No .odt files found.\n"
+					fi
+					anykey
+					break ;;
+				5 )
+					printf "All done! Exiting the script.\n"
+					break ;;
+				* )
+					echo "${lightred}Invalid Option!${normal} Choose 1 - 5" >&2
+			esac
+		done
+	done
+	over_line "$script $version"
+	exit
 }
 
 main "$@"
