porn-dl: extract_domain() - here-string; site now assigned in download_video()

diff --git a/porn-dl b/porn-dl
--- a/porn-dl
+++ b/porn-dl
@@ -7,7 +7,7 @@
 # Author       : Copyright © 2019, Richard B. Romig, LudditeGeek@Mosfanet
 # Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
 # Created      : 05 Apr 2019
-# Updated      : 27 Jan 2026
+# Updated      : 05 Feb 2026
 # Comments     : match by regex, starting with http:// or https://
 #              : Downloads videos to selected directory under ~/Videos/Pornography/
 # TODO (Rick)  :
@@ -40,8 +40,8 @@ fi
 ## Global Variables ##
 
 readonly script="${0##*/}"
-readonly version="4.4.26027"
-readonly updated="27 Jan 2026"
+readonly version="4.5.26036"
+readonly updated="05 Feb 2026"
 FMENU="fzf --header=$script \
            --layout=reverse \
            --exact \
@@ -83,7 +83,7 @@ script_info() {
   The script will then present a menu of subdirectories under ~/Videos/Pornography/.
   Select the apprpriate subdirectory.
 
-  The the video will be downloaded to the selected sub-directory  The script is
+  The video will be downloaded to the selected sub-directory  The script is
   hard-coded to save the file as title.ext. Spaces in the title will be replaced
   by underscores. Metadata will added to the file.
 
@@ -93,7 +93,6 @@ script_info() {
   Version: $version
   Updated: $updated
 _INFO_
-  exit
 }
 
 check_dependencies() {
@@ -109,9 +108,10 @@ check_dependencies() {
 }
 
 extract_domain() {
+  # Extract domain without www and .com
   local domain fullurl
   fullurl="$1"
-  domain=$(sed 's|^[^/]*//||;s|^www\.||;s|/.*$||;s|\..*$||' <(echo "$fullurl"))
+  domain=$(sed 's|^[^/]*//||;s|^www\.||;s|/.*$||;s|\..*$||' <<< "$fullurl")
   printf "%s" "$domain"
 }
 
@@ -129,7 +129,7 @@ select_directory() {
 download_video() {
   local site url destination
   url="$1"
-  site="$2"
+  site=$(extract_domain "$url")
   clear
 	destination=$(select_directory)
   center_text "== ${site^} Download =="
@@ -145,27 +145,26 @@ download_video() {
 }
 
 main() {
-  local site url
+  local url
   # Check arguments, fetch URL and extract site name
   if [[ $# -eq 0 ]]; then
     printf "%s No argument passed.\n" "$RED_ERROR" >&2
-    help 2
+    help "$E_MISSING_ARG"
   elif [[ "$1" == "--info" || "$1" == "-i" ]]; then
     script_info
   elif [[ "$1" == "--help" || "$1" == "-h" ]]; then
-    help 2
+    help 0
   elif [[ "$1" =~ ^https?:\/\/.* ]]; then
     # match by regex, starts with http:// or https://
     url=$*
-    # Extract domain without www and .com
-    site=$(extract_domain "$url")
     check_dependencies
-    download_video "$url" "$site"
-    over_line "$script $version"
-    exit "$EC"
+    download_video "$url"
   else
-    diehard "Invalid argument. Enter full URL." "$script $version"
+    printf "%s Invalid argument. Enter full URL." "$RED_ERROR" >&2
+    EC="$E_INVALID_ARG"
   fi
+  over_line "$script $version"
+  exit "$EC"
 }
 
 ## Execution ##
