porn-dl - passes site variable to display_title to show site name in title box.

diff --git a/porn-dl b/porn-dl
--- a/porn-dl
+++ b/porn-dl
@@ -7,7 +7,7 @@
 # Author       : Copyright © 2019, Richard B. Romig, LudditeGeek@Mosfanet
 # Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
 # Created      : 05 April 2019
-# Updated      : 04 Oct 2024
+# Updated      : 10 Oct 2024
 # Comments     : match by regex, starts with http:// or https:// or by ID number
 #              : Downloads videos to ~/Videos/Pornography/<category>
 # TODO (Rick)  :
@@ -30,15 +30,16 @@ fi
 ## Global Variables ##
 
 script=$(basename "$0"); readonly script
-readonly version="2.3.24278"
+readonly version="2.4.24284"
 readonly updated="04 Oct 2024"
 readonly porn_dir=$HOME"/Videos/Pornography"
 
 ## Functions ##
 
 display_title() {
+  local site="$1"
   clear
-  box "Porn Site Download" "="
+  box "${site^} Download" "="
   echo "$script v$version"
 }
 
@@ -162,21 +163,24 @@ download_video() {
   local site url subdir
   url="$1"
   site="$2"
-  display_title
+  display_title "$site"
   # Choose the download folder
   subdir=$(choose_destination)
   # Download video to selected folder
   printf "\n%s%sDownloading video from %s to " "$bold" "$blue" "${site^}"
   case "$subdir" in
-    "none" ) dl_2_video "$url" ;;
-    * ) dl_2_subdir "$url" "$subdir"
+    "none" )
+      dl_2_video "$url"
+    ;;
+    * )
+      dl_2_subdir "$url" "$subdir"
   esac
 }
 
 main() {
   # Check arguments, fetch URL and extract site name
   if [[ $# -eq 0 ]]; then
-    echo "$RED_ERROR No argument passed." >&2
+    printf "%s No argument passed.\n" "$RED_ERROR" >&2
     help 2
   elif [[ "$1" == "--info" || "$1" == "-i" ]]; then
     script_info
