porn-dl - updated help() to new format; added text show source site and destination directory.

diff --git a/porn-dl b/porn-dl
--- a/porn-dl
+++ b/porn-dl
@@ -7,7 +7,7 @@
 # Author       : Copyright © 2019, Richard B. Romig, LudditeGeek@Mosfanet
 # Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
 # Created      : 05 April 2019
-# Updated      : 07 Jun 2024
+# Updated      : 22 Jun 2024
 # Comments     : match by regex, starts with http:// or https:// or by ID number
 #              : Downloads videos to ~/Videos/Pornography/<category>
 # TODO (Rick)  :
@@ -29,8 +29,8 @@ fi
 ## Variables ##
 
 _script=$(basename "$0"); readonly _script
-readonly _version="2.0.24160"
-readonly _updated="07 Jun 2024"
+readonly _version="2.1.241174"
+readonly _updated="22 Jun 2024"
 readonly porn_dir=$HOME"/Videos/Pornography"
 
 ## Functions ##
@@ -43,8 +43,11 @@ display_title() {
 
 help() {
   local errcode="${1:-2}"
-  cat <<- END_HELP
-  Usage: $_script [video-url] [video-ID]
+  cat << END_HELP
+${orange}$_script${normal} $_version ($_updated)
+Dowload videos from adult sites.
+
+${green}Usage:${normal} $_script [video_URL] [video_ID]
   ${darkgray}PornHub${normal}
   $_script https://www.pornhub.com/view_video.php?viewkey=ph5ccfa07f0e2a6
   ${darkgray}RedTube${normal}
@@ -52,8 +55,9 @@ help() {
   ${darkgray}SparkBang${normal}
   $_script https://spankbang.com/35tlo/video/luana+lani+comp
 
-  --help or -h will display these instructions.
-  --info or -i will display information about the script.
+${orange}Available options:${normal}
+  -h | --help  displays these instructions.
+  -i | --info  displays information about the script.
 END_HELP
   exit "$errcode"
 }
@@ -128,20 +132,22 @@ choose_destination() {
 }
 
 dl_2_video() {
+  printf "%s...%s\n"  "$porn_dir" "$normal"
   # if /usr/local/bin/yt-dlp -f "bv*+ba/b" --add-metadata -ic --restrict-filename -o "$porn_dir/%(title)s.%(ext)s" "$url"
   if /usr/local/bin/yt-dlp -f "bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best" --add-metadata -ic --restrict-filename -o "$porn_dir/%(title)s.%(ext)s" "$url"
-    then
-      leave "Download successful."
-    else
-      ec="$?"
-      die "Download failed." "$ec"
-    fi
+  then
+    leave "Download successful."
+  else
+    ec="$?"
+    die "Download failed." "$ec"
+  fi
 }
 
 dl_2_subdir() {
-	local domain="$1"
+	local dest_dir="$1"
+	printf "%s...%s\n"  "$porn_dir/$dest_dir" "$normal"
   # if /usr/local/bin/yt-dlp -f "bv*+ba/b" --add-metadata -ic --restrict-filename -o "$porn_dir/$subdir/%(title)s.%(ext)s" "$url"
-  if /usr/local/bin/yt-dlp -f "bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best" --add-metadata -ic --restrict-filename -o "$porn_dir/$domain/%(title)s.%(ext)s" "$url"
+  if /usr/local/bin/yt-dlp -f "bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best" --add-metadata -ic --restrict-filename -o "$porn_dir/$dest_dir/%(title)s.%(ext)s" "$url"
   then
     leave "Download successful."
   else
@@ -151,10 +157,6 @@ dl_2_subdir() {
 }
 
 ## Execution ##
-
-check_dependencies
-
-display_title
 
 # Check arguments, fetch URL and extract site name
 
@@ -174,16 +176,16 @@ else
   die "Invalid argument. Enter full URL." 1 >&2
 fi
 
+check_dependencies
+
+display_title
+
 # Choose the download folder
 subdir=$(choose_destination)
 
 # Download video to selected folder
-echo $'\n'$"${bold}${blue}Downloading from $site ...${normal}"
+printf "\n%s%sDownloading video from %s to " "$bold" "$blue" "${site^}"
 case "$subdir" in
   "none" ) dl_2_video;;
-  * ) dl_2_subdir "$subdir"
-esac
-case "$subdir" in
-  "none" ) dl_2_video ;;
   * ) dl_2_subdir "$subdir"
 esac
