porn-dl: updated error codes

diff --git a/porn-dl b/porn-dl
--- a/porn-dl
+++ b/porn-dl
@@ -7,7 +7,7 @@
 # Author       : Copyright © 2019, Richard B. Romig, LudditeGeek@Mosfanet
 # Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
 # Created      : 05 Apr 2019
-# Updated      : 04 Dec 2025
+# Updated      : 27 Jan 2026
 # Comments     : match by regex, starting with http:// or https://
 #              : Downloads videos to selected directory under ~/Videos/Pornography/
 # TODO (Rick)  :
@@ -34,16 +34,14 @@ if [[ -x "$HOME/bin/functionlib" ]]; then
   source "$HOME/bin/functionlib"
 else
   echo -e "\e[91mERROR:\e[0m functionlib not found!" >&2
-  exit 1
+  exit 81
 fi
-
-set -eu
 
 ## Global Variables ##
 
 readonly script="${0##*/}"
-readonly version="4.3.25338"
-readonly updated="04 Dec 2025"
+readonly version="4.4.26027"
+readonly updated="27 Jan 2026"
 FMENU="fzf --header=$script \
            --layout=reverse \
            --exact \
@@ -56,12 +54,12 @@ FMENU="fzf --header=$script \
            --header-first \
            --bind change:top \
            --prompt"
-ec=0
+EC=0
 
 ## Functions ##
 
 help() {
-  local errcode="${1:-2}"
+  local errcode="${1:-1}"
 	cat << _HELP_
 ${orange}$script${normal} $version ($updated)
 Dowload videos from adult sites to ~/Videos/Pornography subdirectory.
@@ -106,7 +104,7 @@ check_dependencies() {
     printf '\e[A\e[K'
     check_packages "${packages[@]}"
   else
-    die "yt-dlp is not installed." 1
+    die "yt-dlp is not installed." "$E_FILENOTFOUND"
   fi
 }
 
@@ -141,8 +139,8 @@ download_video() {
   then
     printf "Download successful.\n"
   else
-    ec="$?"
-    printf "Download failed. Error: %d\n" "$ec"
+    EC="$?"
+    printf "Download failed. Error: %d\n" "$EC"
   fi
 }
 
@@ -164,7 +162,7 @@ main() {
     check_dependencies
     download_video "$url" "$site"
     over_line "$script $version"
-    exit "$ec"
+    exit "$EC"
   else
     diehard "Invalid argument. Enter full URL." "$script $version"
   fi
