porn-dl - functions to choose destination directory & to download to appropriate directory.

diff --git a/porn-dl b/porn-dl
--- a/porn-dl
+++ b/porn-dl
@@ -3,7 +3,7 @@
 # Script Name  : porn-dl
 # Description  : Download videos from porn sites with best quality
 # Dependencies : yt-dlp
-# Arguments    : Video URL or ID number
+# Arguments    : Video URL
 # Author       : Copyright © 2019, Richard B. Romig, LudditeGeek@Mosfanet
 # Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
 # Created      : 05 April 2019
@@ -16,7 +16,6 @@
 
 ## Shellcheck Directives ##
 # shellcheck source=/home/rick/bin/functionlib
-# shellcheck disable=SC2034
 
 ## Load function library ##
 
@@ -30,7 +29,7 @@ fi
 ## Variables ##
 
 _script=$(basename "$0"); readonly _script
-readonly _version="1.4.24159"
+readonly _version="2.0.24160"
 readonly _updated="07 Jun 2024"
 readonly porn_dir=$HOME"/Videos/Pornography"
 
@@ -42,36 +41,32 @@ display_title() {
   echo "$_script v$_version"
 }
 
-usage() {
+help() {
   local errcode="${1:-2}"
-  cat <<- EOF
+  cat <<- END_HELP
   Usage: $_script [video-url] [video-ID]
   ${darkgray}PornHub${normal}
   $_script https://www.pornhub.com/view_video.php?viewkey=ph5ccfa07f0e2a6
-  $_script ph5ccfa07f0e2a6
   ${darkgray}RedTube${normal}
   $_script https://redtube.com/5431551
-  $_script 5431551
   ${darkgray}SparkBang${normal}
   $_script https://spankbang.com/35tlo/video/luana+lani+comp
-  $_script 35tlo/video/luana+lani+comp
 
   --help or -h will display these instructions.
   --info or -i will display information about the script.
-EOF
+END_HELP
   exit "$errcode"
 }
 
 script_info() {
-  cat <<- EOF
+  cat <<- END_INFO
   $_script uses yt-dlp to download videos from adult sites such as PornHub
-  and RedTube. The video URL or ID is passed to the script on the command line.
-  If the full URL is passed, the script will extract the name of the site for
-  later use. If the video ID is passed, you are presented a menu of supported
-  sites and the ID will be appended to the URL for the chosen site.
+  and RedTube. The video URL is passed to the script on the command line.
+  The script will extract the name of the site for later use.
 
   The script will then present a menu of categories corresponding to
   subdirectories under ~/Videos/Pornography/. Select the category (subdirectory).
+
   The the video will be downloaded to the selected sub-directory  The script is
   hard-coded to save the file as title.ext. Spaces in the title will be replaced
   by underscores. Metadata will also be added to the file.
@@ -85,7 +80,7 @@ script_info() {
 
   Version: $_version
   Updated: $_updated
-EOF
+END_INFO
   exit
 }
 
@@ -95,6 +90,63 @@ check_dependencies() {
     sleep 2
   else
     die "yt-dlp is not installed." 1
+  fi
+}
+
+extract_domain() {
+  local domain fullurl sitename
+  fullurl="$1"
+  domain=$(echo "$fullurl" | sed -e 's|^[^/]*//||' -e 's|^www\.||' -e 's|/.*$||')
+  domain=${domain%%.*}
+  sitename="${domain^}"
+  echo "$sitename"
+}
+
+# shellcheck disable=SC2034
+choose_destination() {
+	local sub_dir opt options
+	COLUMNS=40
+  options=("Anal" "Asian" "Bi Gay Trans" "Full movies" "Kink" \
+  "Masturbation" "Miscellaneous" "Oral" "Pinay" "Straight" "No category")
+  PS3="Choose category: "
+  select opt in "${options[@]}"; do
+    case "$REPLY" in
+      1 ) sub_dir="Anal"; break ;;
+      2 ) sub_dir="Asian"; break ;;
+      3 ) sub_dir="Bi-gay-trans"; break ;;
+      4 ) sub_dir="Full-movies"; break ;;
+      5 ) sub_dir="Kink"; break ;;
+      6 ) sub_dir="Masturbation"; break ;;
+      7 ) sub_dir="Misc"; break ;;
+      8 ) sub_dir="Oral"; break ;;
+      9 ) sub_dir="Pinay"; break ;;
+      10 ) sub_dir="Straight"; break ;;
+      11 ) sub_dir="none"; break ;;
+    esac
+  done
+  echo "$sub_dir"
+}
+
+dl_2_video() {
+  # if /usr/local/bin/yt-dlp -f "bv*+ba/b" --add-metadata -ic --restrict-filename -o "$porn_dir/%(title)s.%(ext)s" "$url"
+  if /usr/local/bin/yt-dlp -f "bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best" --add-metadata -ic --restrict-filename -o "$porn_dir/%(title)s.%(ext)s" "$url"
+    then
+      leave "Download successful."
+    else
+      ec="$?"
+      die "Download failed." "$ec"
+    fi
+}
+
+dl_2_subdir() {
+	local domain="$1"
+  # if /usr/local/bin/yt-dlp -f "bv*+ba/b" --add-metadata -ic --restrict-filename -o "$porn_dir/$subdir/%(title)s.%(ext)s" "$url"
+  if /usr/local/bin/yt-dlp -f "bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best" --add-metadata -ic --restrict-filename -o "$porn_dir/$domain/%(title)s.%(ext)s" "$url"
+  then
+    leave "Download successful."
+  else
+    ec="$?"
+    die "Download failed." "$ec"
   fi
 }
 
@@ -108,79 +160,30 @@ display_title
 
 if [[ $# -eq 0 ]]; then
   echo "${lightred}Error:${normal} No argument passed." >&2
-  usage 2
+  help 2
 elif [[ "$1" == "--info" || "$1" == "-i" ]]; then
   script_info
 elif [[ "$1" == "--help" || "$1" == "-h" ]]; then
-  usage 2
+  help 2
 elif [[ "$1" =~ ^https?:\/\/.* ]]; then
   # match by regex, starts with http:// or https://
-  # \/ in regex will be seen as / in this context
   url=$*
   # Extract domain without www and .com. Capitalize site name
-  site=$(echo "$url" | sed -e 's|^[^/]*//||' -e 's|^www\.||' -e 's|/.*$||')
-  site=${site%%.*}
-  site="${site^}"
+  site=$(extract_domain "$url")
 else
-  # Choose site and match by video ID
-  echo $'\n'$"${bold}${blue}Sites:${normal}"
-  sites=("PornHub" "RedTube" "SpankBang")
-  PS3="Choose site: "
-  select site in "${sites[@]}"; do
-    case "$REPLY" in
-      1 ) url="https://www.pornhub.com/view_video.php?viewkey=$*"; break ;;
-      2 ) url="https://www.redtube.com/$*"; break ;;
-      3 ) url="https://www.spankbang.com/$*"; break ;;
-      * ) echo "Invalid choice. Try again." >&2 ;;
-    esac
-  done
+  die "Invalid argument. Enter full URL." 1 >&2
 fi
 
 # Choose the download folder
-
-echo $'\n'$"${bold}${blue}Categories:${normal}"
-COLUMNS=40
-options=("Anal" "Asian" "Bi Gay Trans" "Full movies" "Kink" \
- "Masturbation" "Miscellaneous" "Oral" "Pinay" "Straight")
-PS3="Choose category: "
-select opt in "${options[@]}"; do
-  case "$REPLY" in
-    1 ) subdir="Anal"; break ;;
-    2 ) subdir="Asian"; break ;;
-    3 ) subdir="Bi-gay-trans"; break ;;
-    4 ) subdir="Full-movies"; break ;;
-    5 ) subdir="Kink"; break ;;
-    6 ) subdir="Masturbation"; break ;;
-    7 ) subdir="Misc"; break ;;
-    8 ) subdir="Oral"; break ;;
-    9 ) subdir="Pinay"; break ;;
-    10 ) subdir="Straight"; break ;;
-    * ) subdir="none"; break ;;
-  esac
-done
+subdir=$(choose_destination)
 
 # Download video to selected folder
-
 echo $'\n'$"${bold}${blue}Downloading from $site ...${normal}"
 case "$subdir" in
-  "none" )
-    # if /usr/local/bin/yt-dlp -f "bv*+ba/b" --add-metadata -ic --restrict-filename -o "$porn_dir/%(title)s.%(ext)s" "$url"
-    if /usr/local/bin/yt-dlp -f "bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best" --add-metadata -ic --restrict-filename -o "$porn_dir/%(title)s.%(ext)s" "$url"
-    then
-      leave "Download successful."
-    else
-      ec="$?"
-      die "Download failed." "$ec"
-    fi
-    ;;
-  * )
-    # if /usr/local/bin/yt-dlp -f "bv*+ba/b" --add-metadata -ic --restrict-filename -o "$porn_dir/$subdir/%(title)s.%(ext)s" "$url"
-    if /usr/local/bin/yt-dlp -f "bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best" --add-metadata -ic --restrict-filename -o "$porn_dir/$subdir/%(title)s.%(ext)s" "$url"
-    then
-      leave "Download successful."
-    else
-      ec="$?"
-      die "Download failed." "$ec"
-    fi
-    ;;
+  "none" ) dl_2_video;;
+  * ) dl_2_subdir "$subdir"
+esac
+case "$subdir" in
+  "none" ) dl_2_video;;
+  * ) dl_2_subdir "$subdir"
 esac
