porn-dl - removed show_title(); combined download_video() and dl_2_video()

diff --git a/porn-dl b/porn-dl
--- a/porn-dl
+++ b/porn-dl
@@ -7,8 +7,8 @@
 # Author       : Copyright © 2019, Richard B. Romig, LudditeGeek@Mosfanet
 # Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
 # Created      : 05 Apr 2019
-# Updated      : 17 Mar 2025
-# Comments     : match by regex, starts with http:// or https://
+# Updated      : 23 Mar 2025
+# Comments     : match by regex, starting with http:// or https://
 #              : Downloads videos to selected directory under ~/Videos/Pornography/
 # TODO (Rick)  :
 # License      : GNU General Public License, version 2.0
@@ -30,8 +30,8 @@ fi
 ## Global Variables ##
 
 script=$(basename "$0"); readonly script
-readonly version="3.2.25076"
-readonly updated="17 Mar 2025"
+readonly version="4.0.25082"
+readonly updated="23 Mar 2025"
 FMENU="fzf --header=$(basename "$0") \
            --layout=reverse \
            --exact \
@@ -44,33 +44,23 @@ FMENU="fzf --header=$(basename "$0") \
            --header-first \
            --bind change:top \
            --prompt"
+ec=0
 
 ## Functions ##
-
-display_title() {
-  local site="$1"
-  clear
-  box "${site^} Download" "="
-  echo "$script v$version"
-}
 
 help() {
   local errcode="${1:-2}"
 	cat << _HELP_
 ${orange}$script${normal} $version ($updated)
-Dowload videos from adult sites.
+Dowload videos from adult sites to ~/Videos/Pornography subdirectory.
 
-${green}Usage:${normal} $script [video_URL] [video_ID]
-  ${darkgray}PornHub${normal}
+${green}Usage:${normal} $script [video_URL|OPTION]
   $script https://www.pornhub.com/view_video.php?viewkey=ph5ccfa07f0e2a6
-  ${darkgray}RedTube${normal}
   $script https://redtube.com/5431551
-  ${darkgray}SparkBang${normal}
-  $script https://spankbang.com/35tlo/video/luana+lani+comp
 
 ${orange}Available options:${normal}
-  -h | --help  displays these instructions.
-  -i | --info  displays information about the script.
+  -h | --help  Show this help message and exit
+  -i | --info  Show information about the script and exit
 _HELP_
   exit "$errcode"
 }
@@ -116,7 +106,7 @@ extract_domain() {
   local domain fullurl
   fullurl="$1"
   domain=$(echo "$fullurl" | sed 's|^[^/]*//||;s|^www\.||;s|/.*$||;s|\..*$||')
-  echo "$domain"
+  printf "%s" "$domain"
 }
 
 select_directory() {
@@ -134,23 +124,17 @@ download_video() {
   local site url destination
   url="$1"
   site="$2"
-  display_title "$site"
+  clear
 	destination=$(select_directory)
+  box "${site^} Download" "="
   printf "\n%s%sDownloading video from %s to " "$bold" "$blue" "${site^}"
 	printf "%s...%s\n" "$destination" "$normal"
-	dl_2_video "$url" "$destination"
-}
-
-dl_2_video() {
-  local url dest_dir
-  url="$1"
-  dest_dir="$2"
-  if /usr/local/bin/yt-dlp -f "bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best" --add-metadata -ic --restrict-filename -o "$dest_dir/%(title)s.%(ext)s" "$url"
+  if /usr/local/bin/yt-dlp -f "bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best" --add-metadata -ic --restrict-filename -o "$destination/%(title)s.%(ext)s" "$url"
   then
-    leave "Download successful."
+    printf "Download successful.\n"
   else
     ec="$?"
-    die "Download failed. Error: $ec" "$ec"
+    printf "Download failed. Error: %d\n" "$ec"
   fi
 }
 
@@ -171,8 +155,10 @@ main() {
     site=$(extract_domain "$url")
     check_dependencies
     download_video "$url" "$site"
+    over_line "$script $version"
+    exit "$ec"
   else
-    die "Invalid argument. Enter full URL." 1
+    diehard "Invalid argument. Enter full URL." "$script $version"
   fi
 }
 
