porn-dl: sourced functionlib.bash; still unusable without curl-cffi

diff --git a/porn-dl b/porn-dl
--- a/porn-dl
+++ b/porn-dl
@@ -1,5 +1,5 @@
 #!/usr/bin/env bash
-##########################################################################
+###############################################################################
 # Script Name  : porn-dl
 # Description  : Download videos from porn sites with best quality
 # Dependencies : yt-dlp fzf ffmpeg
@@ -7,7 +7,8 @@
 # Author       : Copyright © 2019, Richard B. Romig, LudditeGeek@Mosfanet
 # Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
 # Created      : 05 Apr 2019
-# Updated      : 28 May 2026
+# Updated      : 08 Aug 2026
+# Version      : 4.1.26219
 # Comments     : match by regex, starting with http:// or https://
 #              : Follows symlinks to destination directory if present.
 # TODO (Rick)  : Not working on Pornhub or RedTube with yt-dlp version 2026-06-09 and above. Get the following warning and error:
@@ -18,45 +19,31 @@
 # At this point, this script is unusable on my Mint, LMDE, and Debian systems.
 # License      : GNU General Public License, version 2.0
 # License URL  : https://github.com/RickRomig/scripts/blob/main/LICENSE
-##########################################################################
-# This program is free software; you can redistribute it and/or modify
-# it under the terms of the GNU General Public License as published by
-# the Free Software Foundation; either version 2 of the License, or
-# (at your option) any later version.
+###############################################################################
+# This program is free software; you can redistribute it and/or modify it under
+# the terms of the GNU General Public License as published by the Free Software
+# Foundation; either version 2 of the License, or (at your option) any later
+# version.
 #
-# This program is distributed in the hope that it will be useful,
-# but WITHOUT ANY WARRANTY; without even the implied warranty of
-# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
-# GNU General Public License for more details.
-##########################################################################
+# This program is distributed in the hope that it will be useful, but WITHOUT
+# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
+# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
+###############################################################################
 
-## Load function library ##
-# shellcheck source=/home/rick/bin/functionlib
-source ~/bin/functionlib || { printf "\e[91mERROR:\e[0m Unable to source functionlib\n"; exit 1; }
+# shellcheck source=/home/rick/bin/functionlib.bash
+source ~/bin/functionlib.bash || { printf "\e[91mERROR:\e[0m Unable to source functionlib.bash\n"; exit 1; }
 
 ## Global Variables ##
 
-readonly script="${0##*/}"
-readonly version="4.12.26148"
-readonly updated="28 May 2026"
-FMENU="fzf --header=$script \
-           --layout=reverse \
-           --exact \
-           --border=bold \
-           --border=rounded \
-           --margin=5% \
-           --color=dark \
-           --height=95% \
-           --info=hidden \
-           --header-first \
-           --bind change:top \
-           --prompt"
 EC=0
 
 ## Functions ##
 
 help() {
-  local errcode="${1:-1}"
+  local -r script="$1"
+  local -r version="$2"
+  local -ri errcode="${3:-1}"
+  local -r updated="08 Aug 2026"
 	cat << _HELP_
 ${orange}$script${normal} $version ($updated)
 Dowload videos from adult sites to the appropriate subdirectory.
@@ -71,6 +58,7 @@ _HELP_
 }
 
 script_info() {
+  local -r script="$1"
   cat << _INFO_
   $script uses yt-dlp to download videos from adult sites such as PornHub
   and RedTube. The video URL is passed to the script on the command line.
@@ -85,9 +73,6 @@ script_info() {
 
   When the download is completed, success or failure is displayed. If the
   download fails, the script exits with an error code.
-
-  Version: $version
-  Updated: $updated
 _INFO_
 }
 
@@ -109,6 +94,18 @@ extract_domain() {
 }
 
 select_directory() {
+  FMENU="fzf --header=$script \
+           --layout=reverse \
+           --exact \
+           --border=bold \
+           --border=rounded \
+           --margin=5% \
+           --color=dark \
+           --height=95% \
+           --info=hidden \
+           --header-first \
+           --bind change:top \
+           --prompt"
 	local vid_d selected_directory
 	local video_dir=~/Videos/Pornography
   local directories=()
@@ -133,7 +130,7 @@ download_video() {
   color_header "${site^} Download" "ORANGE"
   printf "\n%s%sDownloading video from %s to " "$bold" "$blue" "${site^}"
 	printf "%s...%s\n" "$destination" "$normal"
-  /usr/local/bin/yt-dlp -f "bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best" --add-metadata -ic --restrict-filename -o "$destination/%(title)s.%(ext)s" "$url"; EC="$?"
+  /usr/local/bin/yt-dlp -f "bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best" --add-metadata -ic --restrict-filename -o "$destination/%(title)s.%(ext)s" --impersonate Chrome "$url"; EC="$?"
   if [[ $EC -eq 0 ]]; then
     printf "Download successful.\n"
   else
@@ -141,30 +138,37 @@ download_video() {
   fi
 }
 
-main() {
-  local url
-  local re="^https?:\/\/.*"
-  # Check arguments, fetch URL and extract site name
-  if [[ $# -eq 0 ]]; then
+check_arguments() {
+  if [[  $# -eq 0 ]]; then
     printf "%s No argument passed.\n" "$RED_ERROR" >&2
-    help "$E_MISSING_ARG"
+    help "$script" "$version" "$updated" "$E_MISSING_ARG"
   elif [[ "$1" == "--info" || "$1" == "-i" ]]; then
-    script_info
+    script_info "$script" "$version" "$updated"
+    exit 0
   elif [[ "$1" == "--help" || "$1" == "-h" ]]; then
-    help 0
-  elif [[ $1 =~ $re ]]; then
-    # match by regex, starts with http:// or https://
-    url=$*
-    check_dependencies
-    download_video "$url"
-  else
-    printf "%s Invalid argument. Enter full URL." "$RED_ERROR" >&2
-    EC="$E_INVALID_ARG"
+    help "$script" "$version" "$updated" 0
   fi
-  over_line "$script $version"
-  exit "$EC"
+  return 0
 }
 
-## Execution ##
+main() {
+  local -r script="${0##*/}"
+  local -r version="4.13.26219"
+  local -i exit_code=0
+  local -r re="^https?:\/\/.*"
+  check_arguments "$@"
+  check_dependencies
+  if [[ $1 =~ $re ]]; then
+    # match by regex, starts with http:// or https://
+    local -r url=$*
+    download_video "$url"
+    exit_code="$?"
+  else
+    printf "%s Invalid argument. Enter full URL." "$RED_ERROR" >&2
+    exit_code="$E_INVALID_ARG"
+  fi
+  over_line "$script $version"
+  exit "$exit_code"
+}
 
 main "$@"
