Added appropriate code form pre-commit.sample. Added *.sed to shellcheck exceptions.

diff --git a/pre-commit b/pre-commit
--- a/pre-commit
+++ b/pre-commit
@@ -2,8 +2,21 @@
 
 # Called by git commit to run shellcheck against staged scripts before making commit.
 # Execute from repository's .git/hooks directory
-# Excludes *.md, *.txt, *.conf, *.json, *.lst  files
+# Excludes *.md, *.txt, *.sed, *.conf, *.json, *.lst files
 # Terminates the commit if shellcheck fails.
 
-for file in $(git diff --cached --name-only --diff-filter=AM | grep -Ev '\.md$|\.txt$|\.conf$}\.json$|\.lst$|rc$')
+if git rev-parse --verify HEAD >/dev/null 2>&1; then
+	against=HEAD
+else
+	# Initiial commit: diff against an empty tree object
+	against=$(git hash-object -t tree /dev/null)
+fi
+
+# Redirect ouput to stderr.
+exec 1>&2
+
+for file in $(git diff --cached --name-only --diff-filter=AM | grep -Ev '\.md$|\.txt$|\.sed$|\.conf$\.json$|\.lst$|rc$')
 do shellcheck -x --exclude=SC1001,SC2001 "$file" || exit 1; done
+
+# If there are whitespace errors, print the offending file names and fail.
+exec git diff-index --check --cached "$against" --
