purge-rc: list_headers() shows hwe headers

diff --git a/purge-rc b/purge-rc
--- a/purge-rc
+++ b/purge-rc
@@ -7,7 +7,7 @@
 # Author       : Copyright (C) 2020, Richard B. Romig, LudditeGeek@Mosfanet
 # Email        : rick.romig@gmail.com | eick.romig@mymetronet.net
 # Created      : 27 Sep 2020
-# Updated      : 17 Feb 2026
+# Updated      : 29 May 2026
 # Comments     :
 # TODO (Rick)  :
 # License      : GNU General Public License, version 2.0
@@ -24,23 +24,15 @@
 # GNU General Public License for more details.
 ##########################################################################
 
-## Shellcheck Directives ##
-# shellcheck source=/home/rick/bin/functionlib
-
 ## Source function library ##
-
-if [[ -x "$HOME/bin/functionlib" ]]; then
-  source "$HOME/bin/functionlib"
-else
-  printf "\e[91mERROR:\e[0m functionlib not found!\n" >&2
-  exit 1
-fi
+# shellcheck source=/home/rick/bin/functionlib
+source ~/bin/functionlib || { printf "\e[91mERROR:\e[0m Unable to source functionlib\n"; exit 1; }
 
 ## Functions ##
 
 list_rc_packages() {
   printf "Packages in the 'rc' state:\n"
-  awk '/^rc/ {print $1,$2}' <(dpkg --list) | sort -r
+  awk '/^rc/ {print $1,$2}' < <(dpkg --list) | sort -r
 }
 
 purge_rc_packages() {
@@ -60,13 +52,13 @@ purge_rc_packages() {
 
 list_headers() {
   printf "\n%sInstalled linux headers and images:%s\n" "$green" "$normal"
-  awk '/linux-image/ || /linux-headers/ {print $2}' <(dpkg --list) | sort -r
+  awk '/linux-image/ || /linux-h/ {print $2}' < <(dpkg --list) | sort -r
 }
 
 main() {
   local script="${0##*/}"
-  local -r version="4.12.26048"
-  if grep -q '^rc' <(dpkg --list); then
+  local -r version="4.13.26149"
+  if grep -q '^rc' < <(dpkg --list); then
     list_rc_packages
     purge_rc_packages
   else
