pwfeedback 0.4.1 - modified getopts routine.

diff --git a/pwfeedback b/pwfeedback
--- a/pwfeedback
+++ b/pwfeedback
@@ -4,17 +4,10 @@
 # Description  : Enables/disables display of asterisks when entering password.
 # Dependencies : none
 # Arguments    : [-e] [-d] [-h] [-s] (see help function for details.)
-# Author       : Richard B. Romig, 27 Sep 2020
+# Author       : Copyright (C) 2020, Richard B. Romig, Mosfanet
 # Email        : rick.romig@gmail.com
+# Created      : 27 Sep 2020
 # Comments     : Preferred (default) method is /etc/sudoers.d/0pwfeedback.
-# 07 Sep 2021  : In disable_pwfeedback, added call to visudo to edit sudoers.
-# 07 Oct 2021  : In disable_pwfeedback, removed call to visudo and
-#              : used 'sed' to remove 'pwfeedback' from the sudoers file.
-# 15 Nov 2021  : Corrected error in 0pwfeedback file creation.
-# 25 Feb 2022  : Added `getopts` for command-line options. Added help function.
-# 07 Mar 2022  : Reverted to visudo to change sudoers for safety reasons.
-# 17 Mar 2022  : Added option to display of password feedbak status.
-# 30 Sep 2022  : Changed some variables & printf statements.
 # TODO (Rick)  :
 # License      : GNU General Public License, version 2.0
 ##########################################################################
@@ -35,8 +28,8 @@ fi
 ## Variables ##
 
 _script=$(basename "$0"); readonly _script
-readonly _version="0.4.0"
-readonly _updated="30 Sep 2022"
+readonly _version="0.4.1"
+readonly _updated="29 Mar 2023"
 readonly pwfb_dir="/etc/sudoers.d"
 readonly pwfb_file="0pwfeedback"
 
@@ -99,32 +92,31 @@ END_HELP
 
 printf "Enable/Disable password feedback in the terminal.\n"
 
-if [[ "$#" -eq 0 ]]; then
-  printf "%s No argument passed\n" "$red_error" >&2
-  help 2
-else
-  optstr=":edhs"
-  while getopts "$optstr" opt; do
-    case "$opt" in
-      e )
-        user_in_sudo
-        enable_pwfeedback
-        break ;;
-      d )
-        user_in_sudo
-        disable_pwfeedback
-        break ;;
-      h )
-        help 0 ;;
-      s )
-        user_in_sudo
-        pwfeedback_status
-        break ;;
-      ? )
-        printf "%s Invalid option -%s\n" "$red_error" "$OPTARG" >&2
-        help 2 ;;
-    esac
-  done
-fi
+noOpt=1
+optstr=":edhs"
+while getopts "$optstr" opt; do
+  case "$opt" in
+    e )
+      user_in_sudo
+      enable_pwfeedback
+      ;;
+    d )
+      user_in_sudo
+      disable_pwfeedback
+      ;;
+    h )
+      help 0
+      ;;
+    s )
+      user_in_sudo
+      pwfeedback_status
+      ;;
+    ? )
+      printf "%s Invalid option -%s\n" "$red_error" "$OPTARG" >&2
+      help 2
+  esac
+	noOpt=0
+done
+if [ $noOpt = 1 ];then printf "%s No argument passed.\n" "$red_error" >&2;help 1;fi
 printf "%s v%s (%s)\n" "$_script" "$_version" "$_updated"
 exit
