pwfeedback: main() - replaced double-bracket test with if clause

diff --git a/pwfeedback b/pwfeedback
--- a/pwfeedback
+++ b/pwfeedback
@@ -7,8 +7,8 @@
 # Author       : Copyright (C) 2020, Richard B. Romig, Mosfanet
 # Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
 # Created      : 27 Sep 2020
-# Updated      : 02 Aug 2026
-# Version      : 5.0.26214
+# Updated      : 31 Aug 2026
+# Version      : 5.1.26243
 # Comments     : Preferred (default) method to enable password feedback is /etc/sudoers.d/0pwfeedback.
 # TODO (Rick)  :
 # License      : GNU General Public License, version 2.0
@@ -31,7 +31,7 @@ help() {
   local -r script="$1"
   local -r version="$2"
 	local -ri errcode="${3:-1}"
-	local -r updated="02 Aug 2026"
+	local -r updated="31 Aug 2026"
 	cat << _HELP_
 ${orange}$script${normal} $version ($updated)
 Enable/Disable password feedback in the terminal.
@@ -96,7 +96,7 @@ disable_pwfeedback() {
 
 main() {
   local -r script="${0##*/}"
-  local -r version="5.0.26214"
+  local -r version=" 5.1.26243"
   local -r pwfb_file=/etc/sudoers.d/0pwfeedback
   local -i exit_code=0
   local opt OPTARG OPTIND
@@ -105,17 +105,13 @@ main() {
   while getopts "$optstr" opt; do
     case "$opt" in
       e )
-        enable_pwfeedback "$pwfb_file"
-        ;;
+        enable_pwfeedback "$pwfb_file" ;;
       d )
-        disable_pwfeedback "$pwfb_file"
-        ;;
+        disable_pwfeedback "$pwfb_file" ;;
       h )
-        help "$script" "$version" 0
-        ;;
+        help "$script" "$version" 0 ;;
       s )
-        pwfeedback_status "$pwfb_file"
-        ;;
+        pwfeedback_status "$pwfb_file" ;;
       ? )
         printf "%s Invalid option -%s\n" "$RED_ERROR" "$OPTARG" >&2
         help "$script" "$version" "$E_INVALID_ARG"
@@ -123,7 +119,10 @@ main() {
     exit_code="$?"
 	  noOpt=0
   done
-  [[ "$noOpt" = 1 ]] && { printf "%s No argument passed.\n" "$RED_ERROR" >&2; help "$script" "$version" "$E_MISSING_ARG"; }
+	if (( noOpt == 1 )); then
+		printf "%s No argument passed.\n" "$RED_ERROR" >&2
+		help "$script" "$version" "$E_MISSING_ARG"
+	fi
   shift "$(( OPTIND - 1 ))"
   over_line "$script $version"
   exit "$exit_code"
