pwfeedback - added main(); unknown error when 'set -e' is enabled.

diff --git a/pwfeedback b/pwfeedback
--- a/pwfeedback
+++ b/pwfeedback
@@ -9,6 +9,7 @@
 # Created      : 27 Sep 2020
 # Updated      : 23 Aug 2024
 # Comments     : Preferred (default) method is /etc/sudoers.d/0pwfeedback.
+#              : 'set -e' halts script with unknown error when assigning pwfb variable.
 # TODO (Rick)  :
 # License      : GNU General Public License, version 2.0
 ##########################################################################
@@ -25,11 +26,10 @@ else
   exit 1
 fi
 
-## Variables ##
+## Global Variables ##
 
-_script=$(basename "$0"); readonly _script
-readonly _version="4.5.24236"
-readonly _updated="23 Aug 2024"
+script=$(basename "$0"); readonly script
+readonly version="4.6.24277"
 readonly sudoers_file="/etc/sudoers"
 readonly pwfb_dir="/etc/sudoers.d"
 readonly pwfb_file="0pwfeedback"
@@ -79,49 +79,56 @@ disable_pwfeedback() {
 }
 
 help() {
-  local errcode="${1:-2}"
-  cat << END_HELP
-${orange}$_script${normal} $_version ($_updated)
+  local errcode updated
+	errcode="${1:-2}"
+	updated="03 Oct 2024"
+	cat << _HELP_
+${orange}$script${normal} $version ($updated)
 Enable/Disable password feedback in the terminal.
 
-${green}Usage:${normal} $_script [OPTIONS]
+${green}Usage:${normal} $script [OPTIONS]
 
 ${orange}Available options:${normal}
   -e  Enable password feedback
   -d  Disable password feedback
   -h  Help
   -s  Status of password feedback
-END_HELP
+_HELP_
   exit "$errcode"
+}
+
+main() {
+  local noOpt opt optstr
+  noOpt=1
+  optstr=":edhs"
+  while getopts "$optstr" opt; do
+    case "$opt" in
+      e )
+        sudo_login 2
+        enable_pwfeedback
+      ;;
+      d )
+        sudo_login 2
+        disable_pwfeedback
+      ;;
+      h )
+        help 0
+      ;;
+      s )
+        sudo_login 2
+        pwfeedback_status
+      ;;
+      ? )
+        printf "%s Invalid option -%s\n" "$RED_ERROR" "$OPTARG" >&2
+        help 2
+    esac
+	  noOpt=0
+  done
+  [[ "$noOpt" = 1 ]] && { printf "%s No argument passed.\n" "$RED_ERROR" >&2; help 1; }
+  shift "$(( OPTIND - 1 ))"
+  leave "$script v$version"
 }
 
 ## Execution ##
 
-noOpt=1
-optstr=":edhs"
-while getopts "$optstr" opt; do
-  case "$opt" in
-    e )
-      sudo_login 2
-      enable_pwfeedback
-    ;;
-    d )
-      sudo_login 2
-      disable_pwfeedback
-    ;;
-    h )
-      help 0
-    ;;
-    s )
-      sudo_login 2
-      pwfeedback_status
-    ;;
-    ? )
-      printf "%s Invalid option -%s\n" "$red_error" "$OPTARG" >&2
-      help 2
-  esac
-	noOpt=0
-done
-[[ "$noOpt" = 1 ]] && { printf "%s No argument passed.\n" "$red_error" >&2; help 1; }
-shift "$(( OPTIND - 1 ))"
-leave "$_script v$_version"
+main "$@"
