randpic: valid_folder() refactored to check input folder against an array of invalid directories

diff --git a/randpic b/randpic
--- a/randpic
+++ b/randpic
@@ -7,7 +7,7 @@
 # Author       : Copyright (C) 2019, Richard Romig, Mosfanet
 # Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
 # Created      : 02 Jun 2019
-# Updated      : 31 Mar 2026
+# Updated      : 29 May 2026
 # Comments     :
 # TODO (rick)  :
 # License      : GNU General Public License, version 2.0
@@ -24,17 +24,9 @@
 # GNU General Public License for more details.
 ##########################################################################
 
-## Shellcheck Directives ##
+## Source function library ##
 # shellcheck source=/home/rick/bin/functionlib
-
-## Load function library ##
-
-if [[ -x "$HOME/bin/functionlib" ]]; then
-  source "$HOME/bin/functionlib"
-else
-  echo -e "\e[91mERROR:\e[0m functionlib not found!" >&2
-  exit 81
-fi
+source ~/bin/functionlib || { printf "\e[91mERROR:\e[0m Unable to source functionlib\n"; exit 1; }
 
 ## Functions ##
 
@@ -54,7 +46,7 @@ select_image_dir() {
   local image_d dest_d
   local image_dirs=()
   for image_d in $HOME/Work/images; do
-    [[ -d "$image_d" ]] && image_dirs+=("$(sort -d < <(find "$image_d" -type d -print))")
+    [[ -d "$image_d" ]] && image_dirs+=("$(sort -d < <(find "$image_d" -maxdepth 1 -type d -print))")
   done
 	dest_d=$($FMENU "Select image directory: " < <(printf "%s\n" "${image_dirs[@]}"))
 	printf "%s" "$dest_d"
@@ -62,12 +54,16 @@ select_image_dir() {
 
 valid_folder() {
   local folder="$1"
-  case "$folder" in
-    album-art|backgrounds|DCIM|Facebook|Tech-pics|unsorted|wallpaper|web-site-pics|Zipped|SLIDES )
-      return "$FALSE" ;;
-    * )
-      return "$TRUE"
-  esac
+  local is_valid="$TRUE"
+  local directory=
+  local invalid_dirs=("album-art" "backgrounds" "DCIM" "Facebook" "Tech-pics" "unsorted" "wallpaper" "web-site-pics" "Zipped" "SLIDES")
+  for directory in "${invalid_dirs[@]}"; do
+    if [[ "$directory" == "$folder" ]]; then
+      is_valid="$FALSE"
+      break
+    fi
+  done
+  return "$is_valid"
 }
 
 valid_image() {
@@ -164,7 +160,7 @@ select_images() {
 
 main () {
   local script="${0##*/}"
-  local version="5.2.26090"
+  local version="6.0.26149"
   local image_dir
   check_package imagemagick
   image_dir=$(select_image_dir)
