redtube-dl - added missing call to download_video(); made site a global variable (static)

diff --git a/redtube-dl b/redtube-dl
--- a/redtube-dl
+++ b/redtube-dl
@@ -7,7 +7,7 @@
 # Author       : Copyright © 2019, Richard B. Romig, 05 April 2019
 # Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
 # Created      : 05 April 2019
-# Updated      : 04 Oct 2024
+# Updated      : 10 Oct 2024
 # Comments     : Accepts either full URL or video id such as 5431551
 #              : Downloads to ~/Videos/Pornography/<category>
 # TODO (Rick)  :
@@ -26,18 +26,19 @@ else
   exit 1
 fi
 
-## Variables ##
+## Global Variables ##
 
 script=$(basename "$0"); readonly script
-readonly version="3.3.24278"
+readonly version="3.4.24284"
 readonly updated="04 Oct 2024"
+readonly site="Redtube"
 readonly porn_dir=$HOME"/Videos/Pornography"
 
 ## Functions ##
 
 display_title() {
   clear
-  box "RedTube Download" "="
+  box "$site Download" "="
   echo "$script v$version"
 }
 
@@ -48,7 +49,6 @@ ${orange}$script${normal} $version ($updated)
 Dowload videos from Redtube.com.
 
 ${green}Usage:${normal} $script [video_URL] [video_ID]
-  ${darkgray}PornHub${normal}
   $script https://redtube.com/5431551
   $script 5431551
 
@@ -147,15 +147,17 @@ dl_2_subdir() {
 download_video() {
   local site url subdir
   url="$1"
-  site="Redtube"
   display_title
   # Choose the download folder
   subdir=$(choose_destination)
   # Download video to selected folder
   printf "\n%s%sDownloading video from %s to " "$bold" "$blue" "$site"
   case "$subdir" in
-    "none" ) dl_2_video "$url" ;;
-    * ) dl_2_subdir "$url" "$subdir"
+    "none" )
+      dl_2_video "$url"
+    ;;
+    * )
+      dl_2_subdir "$url" "$subdir"
   esac
 }
 
@@ -163,22 +165,23 @@ download_video() {
 
 main() {
   local url
-# Check arguments and fetch URL
-if [[ $# -eq 0 ]]; then
-  echo "$RED_ERROR No argument passed." >&2
-  help 2
-elif [[ "$1" == "--info" || "$1" == "-i" ]]; then
-  script_info
-elif [[ "$1" == "--help" || "$1" == "-h" ]]; then
-  help 0
-elif [[ "$1" =~ ^https?:\/\/.* ]]; then
-  # match by regex, starts with http:// or https://
-  url=$*
-else
-  # match by video ID
-  url="https://www.redtube.com/$*"
-fi
-check_dependencies
+  # Check arguments and fetch URL
+  if [[ $# -eq 0 ]]; then
+    printf "%s No argument passed.\n" "$RED_ERROR" >&2
+    help 2
+  elif [[ "$1" == "--info" || "$1" == "-i" ]]; then
+    script_info
+  elif [[ "$1" == "--help" || "$1" == "-h" ]]; then
+    help 0
+  elif [[ "$1" =~ ^https?:\/\/.* ]]; then
+    # match by regex, starts with http:// or https://
+    url=$*
+  else
+    # match by video ID
+    url="https://www.redtube.com/$*"
+  fi
+  check_dependencies
+  download_video "$url"
 }
 
 ## Execution ##
