redtube-dl - updated help() to new format; added text show source site and destination directory.

diff --git a/redtube-dl b/redtube-dl
--- a/redtube-dl
+++ b/redtube-dl
@@ -7,7 +7,7 @@
 # Author       : Copyright © 2019, Richard B. Romig, 05 April 2019
 # Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
 # Created      : 05 April 2019
-# Updated      : 08 Jun 2024
+# Updated      : 22 Jun 2024
 # Comments     : Accepts either full URL or video id such as 5431551
 #              : Downloads to ~/Videos/Pornography/<category>
 # TODO (Rick)  :
@@ -29,8 +29,8 @@ fi
 ## Variables ##
 
 _script=$(basename "$0"); readonly _script
-readonly _version="3.0.24160"
-readonly _updated="08 Jun 2024"
+readonly _version="3.1.24174"
+readonly _updated="22 Jun 2024"
 readonly porn_dir=$HOME"/Videos/Pornography"
 
 ## Functions ##
@@ -43,20 +43,24 @@ display_title() {
 
 help() {
   local errcode="${1:-2}"
-  cat <<- EOF
-  Usage: $_script [video-url] [video-ID]
+  cat << END_HELP
+${orange}$_script${normal} $_version ($_updated)
+Dowload videos from Redtube.com.
+
+${green}Usage:${normal} $_script [video_URL] [video_ID]
+  ${darkgray}PornHub${normal}
   $_script https://redtube.com/5431551
   $_script 5431551
 
-  --help or -h will display these instructions.
-  --info or -i will display information about the script.
-$_script v$_version ($_updated)
-EOF
+${orange}Available options:${normal}
+  -h | --help  displays these instructions.
+  -i | --info  displays information about the script.
+END_HELP
   exit "$errcode"
 }
 
 script_info() {
-  cat <<- EOF
+  cat <<- END_INFO
   $_script uses yt-dlp to download videos from the RedTube adult site.
   The video URL or ID is passed to the script on the command line. The default
   URL is https://www.pornhub.com if only the video ID is passed to the script.
@@ -77,7 +81,7 @@ script_info() {
 
   Version: $_version
   Updated: $_updated
-EOF
+END_INFO
   exit
 }
 
@@ -115,31 +119,27 @@ done
 }
 
 dl_2_video() {
-    if /usr/local/bin/yt-dlp -f "bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best" --add-metadata -ic --restrict-filename -o "$porn_dir/$dest_dir/%(title)s.%(ext)s" "$url"
-    then
-      leave "Download successful."
-    else
-      ec="$?"
-      die "Download failed." "$ec"
-    fi
+  printf "%s...%s\n"  "$porn_dir" "$normal"
+  if /usr/local/bin/yt-dlp -f "bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best" --add-metadata -ic --restrict-filename -o "$porn_dir/%(title)s.%(ext)s" "$url"; then
+    leave "Download successful."
+  else
+    ec="$?"
+    die "Download failed." "$ec"
+  fi
 }
 
 dl_2_subdir() {
 	local dest_dir="$1"
-    if /usr/local/bin/yt-dlp -f "bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best" --add-metadata -ic --restrict-filename -o "$porn_dir/$dest_dir/%(title)s.%(ext)s" "$url"
-    then
-      leave "Download successful."
-    else
-      ec="$?"
-      die "Download failed." "$ec"
-    fi
+	printf "%s...%s\n"  "$porn_dir/$dest_dir" "$normal"
+  if /usr/local/bin/yt-dlp -f "bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best" --add-metadata -ic --restrict-filename -o "$porn_dir/$dest_dir/%(title)s.%(ext)s" "$url"; then
+    leave "Download successful."
+  else
+    ec="$?"
+    die "Download failed." "$ec"
+  fi
 }
 
 ## Execution ##
-
-check_dependencies
-
-display_title
 
 # Check arguments and fetch URL
 if [[ $# -eq 0 ]]; then
@@ -157,11 +157,15 @@ else
   url="https://www.redtube.com/$*"
 fi
 
+check_dependencies
+
+display_title
+
 # Choose the download folder
 subdir=$(choose_destination)
 
 # Download video to selected folder
-echo $'\n'$"${bold}${blue}Streaming from RedTube ...${normal}"
+printf "\n%s%sDownloading video from Redtube to " "$bold" "$blue"
 case "$subdir" in
   "none" ) dl_2_video ;;
   * ) dl_2_subdir "$subdir"
