refresh-net: retart_network() corrected process substitution

diff --git a/refresh-net b/refresh-net
--- a/refresh-net
+++ b/refresh-net
@@ -7,12 +7,12 @@
 # Author       : Copyright (C) 2025, Richard B. Romig, LudditeGeek@Mosfanet
 # Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
 # Created      : Unknown
-# Updated      : 10 Feb 2026
+# Updated      : 30 May 2026
 # Comment      :
 # TODO (Rick)  :
 # License      : GNU General Public License, version 2.0
 # License URL  : https://github.com/RickRomig/scripts/blob/main/LICENSE
-##########################################################################
+###############################################################################
 # This program is free software; you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
 # the Free Software Foundation; either version 2 of the License, or
@@ -24,23 +24,15 @@
 # GNU General Public License for more details.
 ###############################################################################
 
-## Shellcheck Directives ##
-# shellcheck source=/home/rick/bin/functionlib
-
 ## Source function library ##
-
-if [[ -x "$HOME/bin/functionlib" ]]; then
-  source "$HOME/bin/functionlib"
-else
-  printf "\e[91mERROR:\e[0m functionlib not found!\n" >&2
-  exit 1
-fi
+# shellcheck source=/home/rick/bin/functionlib
+source ~/bin/functionlib || { printf "\e[91mERROR:\e[0m Unable to source functionlib\n"; exit 1; }
 
 ## Functions ##
 
 restart_network() {
   local init_sys
-  init_sys=$(awk 'match($0, /(systemd|sysvinit)/) { print toupper(substr($0, RSTART, RLENGTH));exit; }' <(strings /sbin/init))
+  init_sys=$(awk 'match($0, /(systemd|sysvinit)/) { print toupper(substr($0, RSTART, RLENGTH));exit; }' < <(strings /sbin/init))
   printf "Restarting network...\n"
   case "$init_sys" in
     "SYSTEMD" )
@@ -56,7 +48,7 @@ restart_network() {
 
 main() {
 	local script="${0##*/}"
-  local version="2.2.26041"
+  local version="2.3.26150"
   sudo_login 2
   check_package strings
   restart_network
