ren-space: updated loal variables, return codes

diff --git a/ren-space b/ren-space
--- a/ren-space
+++ b/ren-space
@@ -7,36 +7,30 @@
 # Author       : Copyright © 2025 Richard B. Romig, Mosfanet
 # Email        : rick.romig@gmail | rick.romig@mymetronet.net
 # Created      : 08 Mar 2025
-# Updated      : 17 Jun 2026
+# Updated      : 02 Aug 2026
+# Version      : 3.4.26214"
 # Comment      :
 # License      : GNU General Public License, version 2.0
 # License URL  : https://github.com/RickRomig/scripts/blob/main/LICENSE
-##########################################################################
-# This program is free software; you can redistribute it and/or modify
-# it under the terms of the GNU General Public License as published by
-# the Free Software Foundation; either version 2 of the License, or
-# (at your option) any later version.
+###############################################################################
+# This program is free software; you can redistribute it and/or modify it under
+# the terms of the GNU General Public License as published by the Free Software
+# Foundation; either version 2 of the License, or (at your option) any later
+# version.
 #
-# This program is distributed in the hope that it will be useful,
-# but WITHOUT ANY WARRANTY; without even the implied warranty of
-# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
-# GNU General Public License for more details.
-##########################################################################
+# This program is distributed in the hope that it will be useful,# but WITHOUT
+# ANY WARRANTY; without even the implied warranty of# MERCHANTABILITY or FITNESS
+# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
+###############################################################################
 
-## Source function library ##
-# shellcheck source=/home/rick/bin/functionlib
-source ~/bin/functionlib || { printf "\e[91mERROR:\e[0m Unable to source functionlib\n"; exit 1; }
-
-## Global Variables ##
-
-readonly script="${0##*/}"
-readonly version="3.3.26168"
-
-## Functions ##
+# shellcheck source=/home/rick/bin/functionlib.bash
+source ~/bin/functionlib.bash || { printf "\e[91mERROR:\e[0m Unable to source functionlib.bash\n"; exit 1; }
 
 help() {
-	local errcode="${1:-1}"
-	local updated="17 Jun 2026"
+	local -r script="$1"
+	local -r version="$2"
+	local -ri errcode="${1:-1}"
+	local -r updated="02 Aug 2026"
 	cat << _HELP_
 ${orange}$script${normal} $version, Upated: $updated
 renames filenames containing spaces, replacing spaces with - or . or _
@@ -61,32 +55,33 @@ replace_spaces() {
 			* )	# Should never occur.
 		esac
 	else
-		printf "No filenames containing spaces found in the current directory.\n" >&2
+		printf "No filenames containing spaces found in the current directory.\n"
+		return 0
 	fi
 }
 
 main() {
-	local noOpt opt optstr OPTARG OPTIND
-	noOpt=1
-	optstr=":dhpu"
+	local -r script="${0##*/}"
+	local -r version="3.4.26214"
+	local opt OPTARG OPTIND
+	local -i noOpt=1
+	local -r optstr=":dhpu"
 	while getopts "$optstr" opt; do
 		case "$opt" in
 			d ) replace_spaces "-" ;;
-			h ) help 0 ;;
+			h ) help "$script" "$version" 0 ;;
 			p ) replace_spaces "." ;;
 			u ) replace_spaces "_" ;;
 			? )
 				printf "%s Invalid option -%s\n" "$RED_ERROR" "$OPTARG" >&2
-				help "$E_INVALID_ARG"
+				help "$script" "$version" "$E_INVALID_ARG"
 		esac
 		noOpt=0
 	done
-	[[ "$noOpt" = 1 ]] && { printf "%s No argument passed.\n" "$RED_ERROR" >&2; help "$E_MISSING_ARG"; }
+	[[ "$noOpt" = 1 ]] && { printf "%s No argument passed.\n" "$RED_ERROR" >&2; help "$script" "$version" "$E_MISSING_ARG"; }
 	shift "$(( OPTIND - 1 ))"
 	over_line "$script $version"
 	exit
 }
-
-## Execution ##
 
 main "$@"
