rename-host - incorporated main(); separated code into modular functions.

diff --git a/rename-host b/rename-host
--- a/rename-host
+++ b/rename-host
@@ -7,11 +7,12 @@
 # Author       : Copyright (C) 2019, Richard B. Romig, LudditeGeek@Mosfanet
 # Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
 # Created      : 06 Nov 2019
-# Updated      : 27 Jun 2024
+# Updated      : 11 Oct 2024
 # Comments     : Changes the hostname in both /etc/hostname and /etc/hosts.
 #              : antiX/MX Linux: /etc/hosts - 127.0.0.1      hostname
 #              : Rules based on hostname(7) man page
 #              : Hostname length limited to 15 characters for NETBIOS compatibility.
+#              : old_host & new_host variables are global.
 # TODO (Rick)  :
 # License      : GNU General Public License, version 2.0
 #############################################################################
@@ -28,16 +29,17 @@ else
   exit 1
 fi
 
-## Variables ##
+## Global Variables ##
 
-_script=$(basename "$0"); readonly _script
-readonly _version="4.5.24179"
+script=$(basename "$0"); readonly script
+readonly version="5.0.24284"
 readonly old_host="${HOSTNAME:-$(hostname)}"
+new_host="foo-bar"
 
 ## Functions ##
 
-name_rules() {
-  cat << END_RULES
+hosthostname_rules() {
+  cat << _RULES_
 
 ${lightblue}Hostname Rules${normal}
   ${orange}*${normal} 5-15 characters (for NETBIOS compatibility)
@@ -46,84 +48,103 @@ ${lightblue}Hostname Rules${normal}
   ${orange}*${normal} no special characters
   ${orange}*${normal} first character cannot be a hyphen or a digit
   ${orange}*${normal} last character cannot be a hyphen
-END_RULES
+_RULES_
+}
+
+get_new_hostname() {
+  local strlen
+  while true; do
+    printf "\nCurrent hostname is %s\n\n" "$old_host"
+
+    read -rp "Enter new hostname: " new_host
+    strlen=${#new_host}
+    if [[ "$strlen" -lt 5 || "$strlen" -gt 15 ]]; then
+      printf "\n%sHostname must be between 5 and 15 characters.\n" "$lightred" "$normal" >&2
+      hostname_rules
+      continue
+    fi
+    # Check new hostname against the rules
+    case "$new_host" in
+      -* )
+        printf "\n%sHostname cannot begin with a hypen.%s\n" "$lightred" "$normal" >&2
+        hostname_rules
+        continue
+      ;;
+      *- )
+        printf "\n%sHostname cannot end with a hyphen.%s\n" "$lightred" "$normal" >&2
+        hostname_rules
+        continue
+      ;;
+      [0-9]* )
+        printf "%s\nHostname cannot begin with a digit.%s\n" "$lightred" "$normal" >&2
+        hostname_rules
+        continue
+      ;;
+      *[^a-zA-Z0-9-]* )
+        printf "\n%sHostname cannot contain any special characters.%s\n" "$lightred" "$normal" >&2
+        hostname_rules
+        continue
+      ;;
+    esac
+
+    # Compare new hostname with the old hostname
+    new_host="${new_host,,}"
+    if [[ "$new_host" == "${old_host,,}" ]]; then
+      printf "%sHostnames are the same.%s\n" "$lightred" "$normal" >&2
+      hostname_rules
+      continue
+    else
+      printf "\n%s%s is a valid hostname.%s\n" "$green" "$new_host" "$normal"
+      break
+    fi
+  done
+}
+
+change_hostname_hosts() {
+  # Make backup copies of the original files and replace old hostname with new hostname
+  sudo sed -i.old "s/$old_host/$new_host/" /etc/hostname
+  sudo sed -i.old "s/$old_host/$new_host/" /etc/hosts
+}
+
+revert_to_old_hostname() {
+  sudo mv /etc/hostname.old /etc/hostname > /dev/null 2>&1
+  sudo mv /etc/hosts.old /etc/hosts > /dev/null 2>&1
+}
+
+remove_old_hostname_hosts() {
+  sudo rm /etc/hostname.old /etc/hosts.old
+}
+
+confirm_hostname_hosts() {
+  local host1 host2
+  host1=$(cat /etc/hostname)
+  host2=$(awk '/127.0.1.1/ {print $2}' /etc/hosts)
+  if [[ -z "$host2" ]]; then
+    host2=$(awk '/127.0.0.1/ {print $2}' /etc/hosts | tail -n1)
+    # Change address for hostname from 127.0.0.1 to 127.0.1.1
+    sudo sed -i '0,/127.0.0.1/! {0,/127.0.0.1/ s/127.0.0.1/127.0.1.1/}' /etc/hosts
+  fi
+  printf "/etc/hostname = %s\t/etc/hosts = %s\n" "$host1" " $host2"
+  if [[ "$host1" == "$new_host" && "$host2" == "$new_host" ]]; then
+    remove_old_hostname_hosts
+    leave "Hostname successfully changed. Reboot to ensure the change takes effect."
+  else
+    revert_to_old_hostname
+    leave "Hostname change was unsuccessful. Reverted to the original hostname."
+  fi
+}
+
+main() {
+  sudo_login 2
+  printf "%s v%s\n" "$script" "$version"
+  printf "Renames the system hostname.\n"
+  hostname_rules
+  get_new_hostname
+  print "\nChanging the hostname from %s to %s ...\n" "$old_host" "$new_host"
+  change_hostname_hosts
+  confirm_hostname_hosts
 }
 
 ## Execution ##
 
-clear
-echo "$_script v$_version"
-echo "Renames the system hostname."
-name_rules
-
-while true; do
-  printf "\nCurrent hostname is %s\n\n" "$old_host"
-
-  read -rp "Enter new hostname: " new_host
-  strlen=${#new_host}
-  if [[ "$strlen" -lt 5 || "$strlen" -gt 15 ]]; then
-    echo $'\n'$"${lightred}Hostname must be between 5 and 15 characters.${normal}" >&2
-    name_rules
-    continue
-  fi
-  # Check new hostname against the rules
-  case "$new_host" in
-    -* )
-      echo $'\n'$"${lightred}}Hostname cannot begin with a hypen.${normal}" >&2
-      name_rules
-      continue
-    ;;
-    *- )
-      echo $'\n'$"${lightred}Hostname cannot end with a hyphen.${normal}" >&2
-      name_rules
-      continue
-    ;;
-    [0-9]* )
-      echo $'\n'$"${lightred}Hostname cannot begin with a digit.${normal}" >&2
-      name_rules
-      continue
-    ;;
-    *[^a-zA-Z0-9-]* )
-      echo $'\n'$"${lightred}Hostname cannot contain any special characters.${normal}" >&2
-      name_rules
-      continue
-    ;;
-  esac
-
-  # Compare new hostname with the old hostname
-  new_host="${new_host,,}"
-  if [[ "$new_host" == "${old_host,,}" ]]; then
-    echo "${lightred}Hostnames are the same.${normal}" >&2
-    name_rules
-    continue
-  else
-    echo $'\n'$"${green}New hostname is a valid hostname.${normal}"
-    break
-  fi
-done
-
-sudo_login 2
-echo $'\n'$"Changing the hostname from $old_host to $new_host ..."
-# Make backup copies of the original files and replace old hostname with new hostname
-sudo sed -i.old "s/$old_host/$new_host/" /etc/hostname
-sudo sed -i.old "s/$old_host/$new_host/" /etc/hosts
-
-# Confirm changes
-host1=$(cat /etc/hostname)
-host2=$(awk '/127.0.1.1/ {print $2}' /etc/hosts)
-if [[ -z "$host2" ]]; then
-  # Change address for hostname from 127.0.0.1 to 127.0.1.1
-  host2=$(awk '/127.0.0.1/ {print $2}' /etc/hosts | tail -n1)
-  sudo sed -i '0,/127.0.0.1/! {0,/127.0.0.1/ s/127.0.0.1/127.0.1.1/}' /etc/hosts
-fi
-echo -e "/etc/hostname = $host1\t/etc/hosts = $host2"
-if [[ "$host1" == "$new_host" && "$host2" == "$new_host" ]]; then
-  # Remove the original hostname and hosts files
-  sudo rm /etc/hostname.old /etc/hosts.old
-  leave "Hostname successfully changed. Reboot to ensure the change takes effect."
-else
-  # Revert to the hold hostname
-  sudo mv /etc/hostname.old /etc/hostname > /dev/null 2>&1
-  sudo mv /etc/hosts.old /etc/hosts > /dev/null 2>&1
-  leave "Hostname change was unsuccessful. Reverted to the original hostname."
-fi
+main "$@"
