scan-range - incorporated main(); changed check_arg_values to return TRUE or FALSE values.

diff --git a/scan-range b/scan-range
--- a/scan-range
+++ b/scan-range
@@ -7,7 +7,7 @@
 # Author       : Copyright (C) 2022, Richard B. Romig, LudditeGeek@Mosfanet
 # Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
 # Created      : 27 Jul 2022
-# Updated      : 23 Jun 2024
+# Updated      : 03 Oct 2024
 # Comments     : Adapted from a script by Dave McKay at howtogeek.com
 # TODO (Rick)  :
 # License      : GNU General Public License, version 2.0
@@ -15,7 +15,6 @@
 
 ## Shellcheck Directives ##
 # shellcheck source=/home/rick/bin/functionlib
-# shellcheck disable=SC1091
 
 ## Load function library ##
 
@@ -26,39 +25,38 @@ else
   exit 1
 fi
 
-## Variables ##
+## Global Variables ##
 
-_script=$(basename "$0"); readonly _script
-readonly _version="2.2.24175"
-readonly _updated="23 Jun 2024"
+script=$(basename "$0"); readonly script
+readonly version="3.0.24277"
 
 ## Functions ##
 
 help() {
-	local errcode="${1:-2}"
-	cat << END_HELP
-${orange}$_script${normal} $_version ($_updated)
+  local errcode updated
+	errcode="${1:-2}"
+	updated="03 Oct 2024"
+	cat << _HELP_
+${orange}$script${normal} $version ($updated)
 Scans a range of IP addresses to determine if they are online.
 
-${green}Usage:${normal} $_script IP1 IP2
-${orange}Example:${normal} $_script 10 20
+${green}Usage:${normal} $script IP1 IP2
+${orange}Example:${normal} $script 10 20
 Takes 2 integers between 1 and 254 (last octets of the local network range)
-END_HELP
+_HELP_
 	exit "$errcode"
 }
 
 check_arg_values() {
+	# returns TRUE only if both octets are digits and within the range of valid IP addresses.
 	local ip1 ip2
 	ip1="$1"
 	ip2="$2"
 	if [[ "$ip1" =~ ^[0-9]+$ && "$ip2" =~ ^[0-9]+$ ]] 2>/dev/null; then
-		if [[ "$ip1" -lt 1 || "$ip2" -ge 255 ]]; then
-			printf "%s Invalid range. Values must be integers between 1 and 254.\n" "$red_error" <&2
-			help "1"
-		fi
+		[[ "$ip1" -ge "$ip2" ]] && return "$FALSE"
+		[[ "$ip1" -lt 1 || "$ip2" -ge 255 ]] && return "$FALSE" || return "$TRUE"
 	else
-		printf "%s Invalid argument. Values must be integers between 1 and 254.\n" "$red_error" <&2
-		help "1"
+		return "$FALSE"
 	fi
 }
 
@@ -75,12 +73,18 @@ scan_range() {
 	done
 }
 
+main() {
+	local addr1 addr2
+	[[ $# -lt 2 ]] &&  { printf "%s Too few arguments passed.\n" "$RED_ERROR" <&2; help 1; }
+	addr1="$1"
+	addr2="$2"
+	check_arg_values "$addr1" "$addr2" || { printf "%s Invalid arguments. Values must be integers between 1 and 254.\n" "$RED_ERROR" <&2; help 2; }
+	check_package iputils-arping
+	scan_range "$addr1" "$addr2"
+	over_line "$script $version"
+	exit
+}
+
 ## Execution ##
 
-[[ $# -lt 2 ]] && help "1"
-check_package iputils-arping
-addr1="$1"
-addr2="$2"
-check_arg_values "$addr1" "$addr2"
-scan_range "$addr1" "$addr2"
-leave "$_script $_version"
+main "$@"
