scan-range: check_arg_values() - made regular expression a variable

diff --git a/scan-range b/scan-range
--- a/scan-range
+++ b/scan-range
@@ -7,7 +7,7 @@
 # Author       : Copyright (C) 2022, Richard B. Romig, LudditeGeek@Mosfanet
 # Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
 # Created      : 27 Jul 2022
-# Updated      : 10 Aug 2025
+# Updated      : 30 Mar 2026
 # Comments     : Adapted from a script by Dave McKay at howtogeek.com
 # TODO (Rick)  :
 # License      : GNU General Public License, version 2.0
@@ -33,19 +33,19 @@ if [[ -x "$HOME/bin/functionlib" ]]; then
   source "$HOME/bin/functionlib"
 else
   printf "\e[91mERROR:\e[0m functionlib not found!\n" >&2
-  exit 1
+  exit 81
 fi
 
 ## Global Variables ##
 
 readonly script="${0##*/}"
-readonly version="3.0.25222"
+readonly version="3.1.26089"
 
 ## Functions ##
 
 help() {
-	local errcode="${1:-2}"
-	local updated="10 Aug 2025"
+	local errcode="${1:-1}"
+	local updated="30 Mar 2026"
 	cat << _HELP_
 ${orange}$script${normal} $version ($updated)
 Scans a range of IP addresses to determine if they are online.
@@ -59,10 +59,10 @@ _HELP_
 
 check_arg_values() {
 	# returns TRUE only if both octets are digits and within the range of valid IP addresses.
-	local ip1 ip2
-	ip1="$1"
-	ip2="$2"
-	if [[ "$ip1" =~ ^[0-9]+$ && "$ip2" =~ ^[0-9]+$ ]] 2>/dev/null; then
+	local ip1="$1"
+	local ip2="$2"
+	local re="^[0-9]+$"
+	if [[ $ip1 =~ $re && "$ip2" =~ $re ]] 2>/dev/null; then
 		[[ "$ip1" -ge "$ip2" ]] && return "$FALSE"
 		[[ "$ip1" -lt 1 || "$ip2" -ge 255 ]] && return "$FALSE" || return "$TRUE"
 	else
@@ -85,10 +85,10 @@ scan_range() {
 
 main() {
 	local addr1 addr2
-	[[ $# -lt 2 ]] && { printf "%s Too few arguments passed.\n" "$RED_ERROR" <&2; help 1; }
+	[[ $# -lt 2 ]] && { printf "%s Too few arguments passed.\n" "$RED_ERROR" <&2; help "$E_MISSING_ARG"; }
 	addr1="$1"
 	addr2="$2"
-	check_arg_values "$addr1" "$addr2" || { printf "%s Invalid arguments. Values must be integers between 1 and 254.\n" "$RED_ERROR" <&2; help 2; }
+	check_arg_values "$addr1" "$addr2" || { printf "%s Invalid arguments. Values must be integers between 1 and 254.\n" "$RED_ERROR" <&2; help "$E_INVALID_ARG"; }
 	check_package iputils-arping
 	scan_range "$addr1" "$addr2"
 	over_line "$script $version"
