show-cron: updated local variables; updated sourcing of functionlib

diff --git a/show-cron b/show-cron
--- a/show-cron
+++ b/show-cron
@@ -8,7 +8,7 @@
 # Author       : Copyright (C) 2018, Richard Romig, Mosfanet
 # Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
 # Created      : 06 Mar 2018
-# Updated      : 27 Mar 2026
+# Updated      : 22 May 2026
 # Comments     : Requires sudo privileges
 # TODO (Rick)  :
 # License      : GNU General Public License, version 2.0
@@ -25,37 +25,29 @@
 # GNU General Public License for more details.
 ####################################################################
 
-## Shellcheck Directives ##
+## Source function library ##
 # shellcheck source=/home/rick/bin/functionlib
-
-## Load function library ##
-
-if [[ -x "$HOME/bin/functionlib" ]]; then
-  source "$HOME/bin/functionlib"
-else
-  printf "\e[91mERROR:\e[0m functionlib not found!\n" >&2
-  exit 81
-fi
+source ~/bin/functionlib || { printf "\e[91mERROR:\e[0m Unable to source functionlib\n"; exit 1; }
 
 ## Functions ##
 
 anacron_jobs() {
-  local count cron_dir interval
-  interval="$1"
-  cron_dir="/etc/cron.$interval"
+  local count
+  local -r interval="$1"
+  local -r cron_dir="/etc/cron.$interval"
   count=$(wc -l < <(find "$cron_dir" -maxdepth 1 -type f -iname \*))
   [[ "$count" -gt 0 ]] && return "$TRUE" || return "$FALSE"
 }
 
 print_anacron_jobs() {
-  local interval="$1"
-  local cron_dir="/etc/cron.$interval"
+  local -r interval="$1"
+  local -r cron_dir="/etc/cron.$interval"
   awk -F/ '{print " " $NF}' < <(find "$cron_dir" -maxdepth 1 -type f -iname \*)
 }
 
 list_anacron_jobs() {
-  local interval="$1"
-  local cron_spool="/var/spool/anacron/cron.$interval"
+  local -r interval="$1"
+  local -r cron_spool="/var/spool/anacron/cron.$interval"
   printf "\n%sAnacron %s:%s Last run on %s\n" "$orange" "${interval^}" "$normal" "$(sudo cat "$cron_spool" 2>/dev/null)"
   if anacron_jobs "$interval"; then
     print_anacron_jobs "$interval"
@@ -73,16 +65,16 @@ show_anacron() {
 }
 
 show_user_cron() {
-  local index max norm_user num_users
+  local index max_users norm_user num_users
   num_users=$(awk -F: '$3 >= 1000 && !($1 == "nobody" && $3 == 65534) {SUM+=1} END {print SUM}' /etc/passwd)
   index=1000  # starting point for regular users
-  max=$(( num_users + index ))
+  max_users=$(( num_users + index ))
 
-  while [[ "$index" -le "$max" ]]; do
+  while [[ "$index" -le "$max_users" ]]; do
     norm_user="$(awk -v pat="$index" -F: '$0~pat{print $1}' /etc/passwd)"
     if [[ "$norm_user" ]]; then
       printf "\n%sCron jobs for %s:%s\n" "$orange" "${norm_user^}" "$normal"
-      grep -v '^#' <(sudo crontab -l -u "$norm_user") | awk '{print " "$1,$2,$3,$4,$5"|"$6}' | column -ts "|"
+      grep -v '^#' < <(sudo crontab -l -u "$norm_user") | awk '{print " "$1,$2,$3,$4,$5"|"$6}' | column -ts "|"
     fi
     (( index++ ))
   done
@@ -90,12 +82,12 @@ show_user_cron() {
 
 show_root_cron() {
   printf "\n%sCron jobs for root:%s\n" "$orange" "$normal"
-  grep -v '^#' <(sudo crontab -l) | awk '{print " "$1,$2,$3,$4,$5"|"$6}' | column -ts "|"
+  grep -v '^#' < <(sudo crontab -l) | awk '{print " "$1,$2,$3,$4,$5"|"$6}' | column -ts "|"
 }
 
 main() {
-  local script="${0##*/}"
-  local version="6.6.26086"
+  local -r script="${0##*/}"
+  local -r version="6.7.26142"
   local lhost="${HOSTNAME:-$(hostname)}"
   sudo_login 0
   clear
