sshin: updated local variables

diff --git a/sshin b/sshin
--- a/sshin
+++ b/sshin
@@ -7,40 +7,34 @@
 # Author       : Copyright (C) 2017, Richard B. Romig, LudditeGeek@Mosfanet
 # Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
 # Created      : 07 Oct 2017  (Joe Collins' original script)
-# Updated      : 08 Jun 2026
+# Updated      : 03 Aug 2026
+# Version      : 3.2.26215
 # Comments     : Based on a script by Joe Collins.
 #              : LOCALNET and valid_ip() are declared in functionlib
 #              : X11 forwarding should be enabled in /etc/ssh/sshd_config
-#              : An invalid IP will exit the script with error code from valid_ip() in functionlib
+#              : An invalid IP will exit the script with error code from valid_ip() in functionlib.bash
 # TODO (rick)  :
 # License      : GNU General Public License, version 2.0
 # License URL  : https://github.com/RickRomig/scripts/blob/main/LICENSE
-##########################################################################
-# This program is free software; you can redistribute it and/or modify
-# it under the terms of the GNU General Public License as published by
-# the Free Software Foundation; either version 2 of the License, or
-# (at your option) any later version.
+###############################################################################
+# This program is free software; you can redistribute it and/or modify it under
+# the terms of the GNU General Public License as published by the Free Software
+# Foundation; either version 2 of the License, or (at your option) any later
+# version.
 #
-# This program is distributed in the hope that it will be useful,
-# but WITHOUT ANY WARRANTY; without even the implied warranty of
-# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
-# GNU General Public License for more details.
+# This program is distributed in the hope that it will be useful, but WITHOUT
+# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
+# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
 ###############################################################################
 
-## Source function library ##
-# shellcheck source=/home/rick/bin/functionlib
-source ~/bin/functionlib || { printf "\e[91mERROR:\e[0m Unable to source functionlib\n"; exit 1; }
-
-# Variables
-
-readonly script="${0##*/}"
-readonly version="3.1.26159"
-
-## Functions ##
+# shellcheck source=/home/rick/bin/functionlib.bash
+source ~/bin/functionlib.bash || { printf "\e[91mERROR:\e[0m Unable to source functionlib.bash\n"; exit 1; }
 
 help() {
-  local errcode="${1:-1}"
-  local updated="08 Jun 2026"
+  local -r script="$1"
+  local -r version="$2"
+  local -ri errcode="${3:-1}"
+  local -r updated="03 Aug 2026"
   cat << _HELP_
 
 ${orange}$script${normal} $version ($updated)
@@ -57,8 +51,8 @@ _HELP_
 }
 
 connect_ssh() {
-  local hostip="$1"
-  local x_opt="${2::1}"
+  local -r hostip="$1"
+  local -r x_opt="${2::1}"  # only take the first character
   if valid_ip "$hostip"; then
     case "${x_opt^}" in
       X )
@@ -70,20 +64,21 @@ connect_ssh() {
         /usr/bin/ssh "$LOCALNET.$hostip"
     esac
   else
-    help "$?"
+    help "$script" "$version" "$?"
   fi
+  return 0
 }
 
 main() {
+  local -r script="${0##*/}"
+  local -r version="3.2.26215"
   local hostip="$1"
   local x_opt="${2:-z}"
-  [[ "$1" == "-h" || "$1" == "--help" ]] && help 0
+  [[ "$1" == "-h" || "$1" == "--help" ]] && help "$script" "$version" 0
   [[ "$hostip" ]] || read -rp "Enter last octet of remote server's IP address. " hostip
   connect_ssh "$hostip" "$x_opt"
   over_line "$script $version"
   exit
 }
-
-# Execution
 
 main "$@"
