syncbin: updated indentation

diff --git a/syncbin b/syncbin
--- a/syncbin
+++ b/syncbin
@@ -7,8 +7,8 @@
 # Author       : Copyright (C) 2020, Richard Romig, 27 Sep 2020
 # Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
 # Created      : 27 Sep 2020
-# Updated      : 28 Aug 2026
-# Version      : 8.6.26240
+# Updated      : 10 Sep 2026
+# Version      : 8.7.26253
 # Comments     : Sync scripts to one, multiple, or all machines on the network.
 #              : For mulitiple IPs, integer arguments are expected.
 #              : For use only within the range of static IP addresses.
@@ -33,34 +33,34 @@ source functionlib.bash || { printf "\e[91mERROR:\e[0m Unable to source function
 SECONDS=0
 
 help() {
-  local -r script="$1"
-  local -r version="$2"
-  local -ri errcode="${3:-1}"
-  local -r updated="28 Aug 2026"
-  cat << _HELP_
-${orange}$script${normal} $version ($updated)
-Synchronizes ~/bin with remote hosts.
+	local -r script="$1"
+	local -r version="$2"
+	local -ri errcode="${3:-1}"
+	local -r updated="10 Sep 2026"
+	cat <<- _HELP_
+	${orange}$script${normal} $version ($updated)
+	Synchronizes ~/bin with remote hosts.
 
-${green}Usage:${normal} $script [OPTION]
-${orange}Available options${normal}
-  OPTION   ACTION
-  -h | --help Show this help message and exit.
-  -a | --all  Synchronize all designated machines on the network.
-  1-255       Last octet of the IP address(es) of the machine(s) to synchronize.
+	${green}Usage:${normal} $script [OPTION]
+	${orange}Available options${normal}
+	OPTION      ACTION
+	-h | --help Show this help message and exit.
+	-a | --all  Synchronize all designated machines on the network.
+	1-255       Last octet of the IP address(es) of the machine(s) to synchronize.
 
-${orange}Examples:${normal}
-  $script -h       # Show this help message and exit.
-  $script --help   # Show this help message and exit.
-  $script -a       # Synchronizes with all designated systems.
-  $script --all    # Synchronizes with all designated systems.
-  $script 13       # Synchronizes with the system with a last octet of 13.
-  $script 12 13 14 # Synchronizes with systems whose last octets are 12, 13, 14.
-${orange}Notes:${normal}
-  1. Multiple IP addresses can be entered.
-  2. This script is limited to the range of static IP addresses (11 - 25).
-  3. Certain addresses within that range have been marked as restricted and are not accessible.
+	${orange}Examples:${normal}
+	$script -h       # Show this help message and exit.
+	$script --help   # Show this help message and exit.
+	$script -a       # Synchronizes with all designated systems.
+	$script --all    # Synchronizes with all designated systems.
+	$script 13       # Synchronizes with the system with a last octet of 13.
+	$script 12 13 14 # Synchronizes with systems whose last octets are 12, 13, 14.
+	${orange}Notes:${normal}
+	1. Multiple IP addresses can be entered.
+	2. This script is limited to the range of static IP addresses on the MosfaNet network (11 - 25).
+	3. Certain addresses within that range have been marked as restricted and are not accessible.
 _HELP_
-  exit "$errcode"
+	exit "$errcode"
 }
 
 transfer_status() {
@@ -74,104 +74,100 @@ transfer_status() {
 }
 
 transfer() {
-  local -ri host_ip="$1"
-  local ip_addr
-  ip_addr="$(local_ip)"
-  # Skip local machine:
-  if [[ "$ip_addr" == "$host_ip" ]]; then
-    printf "%sSkipping Machine %s (local client)%s\n\n" "$green" "$host_ip" "$normal"
-    return "$E_INVALID_HOST"
-  fi
-  # Check for machines and sync if on-line:
-  printf "%sChecking for %s...%s\n" "$green" "$host_ip" "$normal"
-  if ping -c 3 "$LOCALNET.$host_ip" >/dev/null 2>&1; then
-    printf "...Syncing to Machine %s\n" "$host_ip"
-    syncscript "$host_ip"
-  else
-    printf "\n...Skipping %s! Not on network.\n\n" "$host_ip"
-  fi
-  return "$?"
+	local -ri host_ip="$1"
+	local -i ip_addr
+	ip_addr="$(local_ip)"
+	# Skip local machine:
+	if [[ "$ip_addr" == "$host_ip" ]]; then
+		printf "%sSkipping Machine %s (local client)%s\n\n" "$green" "$host_ip" "$normal"
+		return "$E_INVALID_HOST"
+	fi
+	# Check for machines and sync if on-line:
+	printf "%sChecking for %s...%s\n" "$green" "$host_ip" "$normal"
+	if ping -c 3 "$LOCALNET.$host_ip" >/dev/null 2>&1; then
+		printf "...Syncing to Machine %s\n" "$host_ip"
+		syncscript "$host_ip"
+	else
+		printf "\n...Skipping %s! Not on network.\n\n" "$host_ip"
+	fi
+	return "$?"
 }
 
 syncscript() {
-  local -ri hostip="$1"
-
-  case "$hostip" in
-    1|2|3|4|5|6|7|8|9|10 )
-      printf "%s %s is a restricted address. Access denied.\n\n" "$RED_WARNING" $"$LOCALNET.$hostip"
-      ;;
-    16|22|153 )
-      printf "\n%sSyncing Git Repositories...%s\n" "$orange" "$normal"
-      rsync -avh --delete "$HOME"/gitea/ "$LOCALNET.$hostip":gitea/
-      transfer_status "$?"
-      printf "\n...Machine %s Synced!\n\n" "$hostip"
-      ;;
-    15|19 )
-      printf "%s is updated through the Scripts Repository clone.\n\n" "$LOCALNET.$hostip"
-      ;;
-   * )
-      printf "\n%sSyncing ~/bin ...%s\n" "$orange" "$normal"
-      rsync -avh --delete --exclude '.git' --exclude '.gitignore' --exclude '*.log' "$HOME"/bin/ "$LOCALNET.$hostip":bin/
-      transfer_status "$?"
-      printf "\n...Machine %s Synced!\n\n" "$hostip"
-  esac
-  return "$?"
+	local -ri hostip="$1"
+	case "$hostip" in
+		1|2|3|4|5|6|7|8|9|10 )
+			printf "%s %s is a restricted address. Access denied.\n\n" "$RED_WARNING" $"$LOCALNET.$hostip" ;;
+		16|22|153 )
+			printf "\n%sSyncing Git Repositories...%s\n" "$orange" "$normal"
+			rsync -avh --delete "$HOME"/gitea/ "$LOCALNET.$hostip":gitea/
+			transfer_status "$?"
+			printf "\n...Machine %s Synced!\n\n" "$hostip" ;;
+		15|19 )
+			printf "%s scripts are updated through the Scripts Repository clone.\n\n" "$LOCALNET.$hostip" ;;
+		* )
+			printf "\n%sSyncing ~/bin ...%s\n" "$orange" "$normal"
+			rsync -avh --delete --exclude '.git' --exclude '.gitignore' --exclude '*.log' "$HOME"/bin/ "$LOCALNET.$hostip":bin/
+			transfer_status "$?"
+			printf "\n...Machine %s Synced!\n\n" "$hostip"
+	esac
+	return "$?"
 }
 
 sync_one() {
-  local -ri hostip="$1"
-  transfer "$hostip"
-  return "$?"
+	local -ri hostip="$1"
+	transfer "$hostip"
+	return "$?"
 }
 
 sync_some() {
-  local hostip
-  for hostip in "$@"; do transfer "$hostip"; done
-  return "$?"
+	local -i hostip
+	for hostip in "$@"; do transfer "$hostip"; done
+	return "$?"
 }
 
 sync_all() {
-  local octets hostip
-  octets=(11 12 13 14 16 17 18 20 21 22 23 24 25)
-  for hostip in "${octets[@]}"; do transfer "$hostip"; done
-  return "$?"
+	local -i octets=(11 12 13 14 16 17 18 20 21 22 23 24 25)
+	local -i hostip
+	for hostip in "${octets[@]}"; do transfer "$hostip"; done
+	return "$?"
 }
 
 check_host() {
-  local -r main_host="hp-800g2-sff"
-  local -r local_host="${HOSTNAME:-$(hostname)}"
-  local -i ip_addr
-  ip_addr="$(local_ip)"
-  printf "Host: %s%s%s at " "$lightyellow" "$local_host" "$normal"
-  printf "%s%s%s\n\n" "$lightyellow" "$LOCALNET.$ip_addr" "$normal"
-  [[ "$local_host" != "$main_host" ]] && die "Script must be run from $main_host" "$E_INVALID_HOST"
-  return "$?"
+	local -r main_host="hp-800g2-sff"
+	local -r local_host="${HOSTNAME:-$(hostname)}"
+	local -i ip_addr
+	ip_addr="$(local_ip)"
+	printf "Host: %s%s%s at " "$lightyellow" "$local_host" "$normal"
+	printf "%s%s%s\n\n" "$lightyellow" "$LOCALNET.$ip_addr" "$normal"
+	[[ "$local_host" != "$main_host" ]] && die "Script must be run from $main_host" "$E_INVALID_HOST"
+	return "$?"
 }
 
 main() {
-  local -r script="${0##*/}"
-  local -r version="8.6.26240"
-  local -i exit_code=0
-  check_package rsync
- if [[ "$#" -eq 0 ]]; then
-    printf "%s No arguments passed.\n" "$RED_ERROR" >&2
-    help "$script" "$version" "$E_MISSING_ARG"
-  elif [[ "$1" = "-h" || "$1" = "--help" ]]; then
-    help "$script" "$version" 0
-  elif [[ "$1" = "-a" || "$1" = "--all" ]]; then
-    check_host
-    sync_all
-  elif [[ "$#" -gt 1 ]]; then
-    check_host
-    sync_some "$@"
-  else
-    check_host
-    sync_one "$1"
-  fi
-  exit_code="$?"
-  over_line "Script completed in $(format_time $SECONDS)"
-  over_line "$script $version"
-  exit "$exit_code"
+	local -r script="${0##*/}"
+	local -r version="8.7.26253"
+	local -i exit_code=0
+	check_package rsync
+	if [[ "$#" -eq 0 ]]; then
+		printf "%s No arguments passed.\n" "$RED_ERROR" >&2
+		help "$script" "$version" "$E_MISSING_ARG"
+	elif [[ "$1" = "-h" || "$1" = "--help" ]]; then
+		help "$script" "$version" 0
+	elif [[ "$1" = "-a" || "$1" = "--all" ]]; then
+		check_host
+		sync_all
+	elif [[ "$#" -gt 1 ]]; then
+		check_host
+	sync_some "$@"
+	else
+		check_host
+		sync_one "$1"
+	fi
+	exit_code="$?"
+	over_line "Script completed in $(format_time $SECONDS)"
+	over_line "$script $version"
+	exit "$exit_code"
 }
 
 main "$@"
