sync-repos: added EC (exit code) global variable; return on transfer error or if local host

diff --git a/sync-repos b/sync-repos
--- a/sync-repos
+++ b/sync-repos
@@ -7,7 +7,7 @@
 # Author       : Copyright © 2025 Richard B. Romig, Mosfanet
 # Email        : rick.romig@gmail | rick.romig@mymetronet.net
 # Created      : 10 Aug 2025
-# Updated      : 10 Mar 2026
+# Updated      : 01 May 2026
 # Comments     :
 # TODO (Rick)  :
 # License      : GNU General Public License, version 2.0
@@ -24,28 +24,21 @@
 # GNU General Public License for more details.
 ##########################################################################
 
-## Shellcheck Directives ##
-# shellcheck source=/home/rick/bin/functionlib
-
 ## Source function library ##
-
-if [[ -x "$HOME/bin/functionlib" ]]; then
-  source "$HOME/bin/functionlib"
-else
-  printf "\e[91mERROR:\e[0m functionlib not found!\n" >&2
-  exit 81
-fi
+# shellcheck source=/home/rick/bin/functionlib
+source functionlib || { printf "\e[91mERROR:\e[0m Unable to source functionlib\n"; exit 1; }
 
 ## Global Variables ##
 
 readonly script="${0##*/}"
-readonly version="3.3.26069"
+readonly version="3.4.26121"
+EC=0
 
 ## Functions ##
 
 help() {
 	local errcode="${1:-1}"
-	local -r updated="10 Mar 2026"
+	local -r updated="01 May 2026"
 	cat << _HELP_
 ${orange}$script${normal} $version, Upated: $updated
 Synchronixe Git repositories and work directories between local computers.
@@ -72,11 +65,12 @@ valid_host() {
 
 transfer_status() {
   local xfr_status="$1"
-  if [[ "$xfr_status" -eq 0 ]]; then
-		printf "Transfer successful\n"
-	else
+	if [[ "$xfr_status" -gt 0 ]]; then
 		printf "%s A transfer failed. Code: %d. Check network status.\n" "$RED_ERROR" "$xfr_status" >&2
+		EC="$xfr_status"
+		return
 	fi
+	printf "Transfer successful\n"
 }
 
 transfer() {
@@ -87,6 +81,7 @@ transfer() {
   # Skip local machine:
   if [[ "$ip_addr" == "$host_ip" ]]; then
     printf "%sSkipping %s (local client)%s\n\n" "$green" "$remote_host" "$normal"
+		EC="$E_INVALID_HOST"
     return
   fi
   # Check for machines and sync if on-line:
@@ -151,7 +146,7 @@ main() {
 	[[ "$noOpt" = 1 ]] && { printf "%s No argument passed.\n" "$RED_ERROR" >&2; help "$E_MISSING_ARG"; }
 	shift "$(( OPTIND - 1 ))"
 	over_line "$script $version"
-	exit
+	exit "$EC"
 }
 
 ## Execution ##
