syncbin 1.5.5: Allow IP addresses 153 and 227 (DHCP reservations)

diff --git a/syncbin b/syncbin
--- a/syncbin
+++ b/syncbin
@@ -31,8 +31,8 @@ fi
 ## Variables ##
 
 _script=$(basename "$0"); readonly _script
-readonly _version="1.5.4"
-readonly _updated="04 May 2023"
+readonly _version="1.5.5"
+readonly _updated="14 May 2023"
 
 ## Functions ##
 
@@ -104,12 +104,12 @@ sync_script() {
   transfer_status "$exit_status"
 
   case "$hostip" in
-    10|22 )
+    10|22|153 )
       echo $'\n'$"${orange}Syncing Gitea repositoies...${normal}"
       rsync -avzh --delete /home/"$USER"/gitea/ "$localnet.$hostip":gitea/
       exit_status="$?"
       transfer_status "$exit_status"
-      ;;
+    ;;
     24|25|227 )
       echo $'\n'$"${orange}Syncing Homepage...${normal}"
       rsync -avzh --delete /home/"$USER"/Documents/homepage/ "$localnet.$hostip":Documents/homepage/
@@ -130,13 +130,12 @@ sync_script() {
       rsync -avzh --delete --exclude '.git' /home/"$USER"/bin/ "$localnet.$hostip":bin/
       exit_status="$?"
       transfer_status "$exit_status"
-      ;;
+    ;;
    * )
       echo $'\n'$"${orange}Syncing bin...${normal}"
       rsync -avzh --delete --exclude '.git' /home/"$USER"/bin/ "$localnet.$hostip":bin/
       exit_status="$?"
       transfer_status "$exit_status"
-      ;;
   esac
 }
 
@@ -147,13 +146,15 @@ sync_one() {
     case $hostip in
       1|2|3|4|5|6|7|8|9 )
         echo -n "${orange}Warning!${normal} $localnet.$hostip is a restricted address."
-        echo -e " Access denied.\n"; exit ;;
+        echo -e " Access denied.\n"
+        exit
+      ;;
       * )
         echo -e "Synchronizing bin and template directories with $localnet.$hostip:"
         transfer
-        all_done ;;
+        all_done
     esac
-  elif [[ "$hostip" -eq 227 ]]; then
+  elif [[ "$hostip" -eq 153 || "$hostip" -eq 227 ]]; then
     echo -e "Synchronizing bin and template directories with $localnet.$hostip:"
     transfer
     all_done
@@ -172,12 +173,13 @@ sync_some() {
         case "$hostip" in
           1|2|3|4|5|6|7|8|9 )
             echo -n "${orange}Warning!${normal} $localnet.$hostip is a restricted"
-            echo -e " address. Access denied.\n" ;;
+            echo -e " address. Access denied.\n"
+          ;;
           * )
             transfer
-            (( xfr_flag++ )) ;;
+            (( xfr_flag++ ))
         esac
-      elif [[ "$hostip" -eq 227 ]]; then
+      elif [[ "$hostip" -eq 153 || "$hostip" -eq 227 ]]; then
         echo -e "Synchronizing bin and template directories with $localnet.$hostip:"
         transfer
         (( xfr_flag++ ))
@@ -197,7 +199,7 @@ sync_some() {
 sync_all() {
   echo -e "Synchronizing bin and template directories with all systems on the local network.\n"
 
-  octets=(10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25)
+  octets=(10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 227)
   for hostip in "${octets[@]}"; do transfer; done
   all_done
 }
@@ -221,26 +223,24 @@ check_host() {
         "yes" )
           echo $'\n'$"Continuing with the script..."
           shopt -u nocasematch
-          break ;;
+          break
+        ;;
         "no" )
           echo $'\n'$"Synchronization canceled."
           shopt -u nocasematch
-          leave "Exiting the script..." ;;
+          leave "Exiting the script..."
+        ;;
         * )
-          echo "${lightred}Invalid choice.${normal} Enter Yes or No" ;;
+          echo "${lightred}Invalid choice.${normal} Enter Yes or No" >&2
       esac
     done
   fi
 }
 
-check_dependencies(){
-  check_package rsync
-}
-
 ## Execution ##
 
-check_dependencies
-clear
+check_package rsync
+# clear
 
 box "$_script v$_version, ($_updated)"
 
