sync-repos: main() - replace noOpt test with if statement

diff --git a/sync-repos b/sync-repos
--- a/sync-repos
+++ b/sync-repos
@@ -7,8 +7,8 @@
 # Author       : Copyright © 2025 Richard B. Romig, Mosfanet
 # Email        : rick.romig@gmail | rick.romig@mymetronet.net
 # Created      : 10 Aug 2025
-# Updated      : 03 Aug 2026
-# Version      : 3.6.26215
+# Updated      : 28 Aug 2026
+# Version      : 3.7.26240
 # Comments     :
 # TODO (Rick)  :
 # License      : GNU General Public License, version 2.0
@@ -31,7 +31,7 @@ help() {
 	local -r script="$1"
 	local -r version-"$2"
 	local -ri errcode="${3:-1}"
-	local -r updated="03 Aug 2026"
+	local -r updated="28 Aug 2026"
 	cat << _HELP_
 ${orange}$script${normal} $version, Upated: $updated
 Synchronixe Git repositories and work directories between local computers.
@@ -112,7 +112,7 @@ sync_script() {
 
 main() {
 	local -r script="${0##*/}"
-	local -r version="3.6.26215"
+	local -r version="3.7.26240"
 	local -i exit_code=0
 	local -r local_host="${HOSTNAME:-$(hostname)}"
 	local opt OPTARG OPTIND
@@ -133,7 +133,10 @@ main() {
 		exit_code="$?"
 		noOpt=0
 	done
-	[[ "$noOpt" = 1 ]] && { printf "%s No argument passed.\n" "$RED_ERROR" >&2; help "$script" "$version" "$E_MISSING_ARG"; }
+	if (( noOpt == 1 )); then
+		printf "%s No argument passed.\n" "$RED_ERROR" >&2
+		help "$script" "$version" "$E_MISSING_ARG"
+	fi
 	shift "$(( OPTIND - 1 ))"
 	over_line "$script $version"
 	exit "$exit_code"
