syncmosfa: sync_one() - calls help() on failed valid_ip(); sync_some() - refactored

diff --git a/syncmosfa b/syncmosfa
--- a/syncmosfa
+++ b/syncmosfa
@@ -7,7 +7,7 @@
 # Author       : Copyright (C) 2020 Richard Romig, 29 Sep 2020
 # Email        : rick.romig@gmail.com
 # Created      : 29 Sep 2020
-# Last updated : 08 Oct 2025
+# Last updated : 29 Jan 2026
 # Comments     : Can sync to one or all machines on the network.
 #              : LOCALNET is declared in functionlib
 # TODO (rick)  :
@@ -34,20 +34,20 @@ if [[ -x "$HOME/bin/functionlib" ]]; then
   source "$HOME/bin/functionlib"
 else
   printf "\e[91mERROR:\e[0m functionlib not found!\n" >&2
-  exit 1
+  exit 81
 fi
 
 ## Global Variables ##
 
 readonly script="${0##*/}"
-readonly version="4.4.25281"
+readonly version="4.5.26029"
 SECONDS=0
 
 ## Functions ##
 
 help() {
-	local errcode="${1:-2}"
-	local updated="08 Oct 2025"
+	local errcode="${1:-1}"
+	local updated="29 Jan 2026"
 	cat << _HELP_
 ${orange}$script${normal} $version ($updated)
 Syncs directories with machines on the network via SSH
@@ -167,8 +167,7 @@ syncscript() {
 }
 
 sync_one() {
-  local hostip
-  hostip="$1"
+  local hostip="$1"
   if [[ "$hostip" -gt 0 && "$hostip" -lt 10 ]]; then
     printf "%s %s is a restricted address. Access denied.\n" "$RED_WARNING" $"$LOCALNET.$hostip"
     exit
@@ -176,29 +175,25 @@ sync_one() {
     printf "Synchronizing bin and template directories with %s:\n\n" "$LOCALNET.$hostip"
     transfer "$hostip"
     all_done
+  else
+    help "$?"
   fi
 }
 
 sync_some() {
   local hostip
-  echo -e "Synchronizing directories with selected systems on the local network.\n"
+  printf "Synchronizing directories with selected systems on the local network.\n\n"
   for hostip in "$@"; do
-    if [[ "$hostip" -eq "$hostip" ]] 2>/dev/null; then
-      if [[ "$hostip" -gt 0 && "$hostip" -lt 255 ]]; then
-        case "$hostip" in
-          1|2|3|4|5|6|7|8|9 )
-            printf "%s %s is a restricted address. Access denied.\n" "$RED_WARNING" "$LOCALNET.$hostip"
+    if [[ "$hostip" -gt 0 && "$hostip" -lt 255 ]]; then
+      case "$hostip" in
+        1|2|3|4|5|6|7|8|9 )
+          printf "%s %s is a restricted address. Access denied.\n" "$RED_WARNING" "$LOCALNET.$hostip"
           ;;
-          * )
-            transfer "$hostip"
-        esac
-      elif [[ "$hostip" -gt 254 ]]; then
-        printf "%s %s is outside the range of static addresses.\n\n" "$RED_WARNING" "$LOCALNET.$hostip"
-      else
-        printf "%s Invalid argument: %s\n\n" "$RED_ERROR" "$hostip" >&2
-      fi
+        * )
+          transfer "$hostip"
+      esac
     else
-      printf "%sInteger argument expected.\n" "$RED_WARNING" >&2
+      printf "%s Invalid argument: %s\n\n" "$RED_ERROR" "$hostip" >&2
     fi
   done
   all_done
@@ -207,6 +202,7 @@ sync_some() {
 sync_all() {
   local hostip octets
   octets=(11 12 13 14 15 16 17 18 19 20 21 22 23 24 25)
+  printf "Sychronizing directories with all systems with static IP addresses on the local network.\n"
   for hostip in "${octets[@]}"; do
     transfer "$hostip"
   done
