syncrick: transfer_status(): success/failure messages, not die; removed .bashrc/.bash_aliases rsync

diff --git a/syncrick b/syncrick
--- a/syncrick
+++ b/syncrick
@@ -7,7 +7,7 @@
 # Author       : Copyright (C) 2023, Richard Romig, Mosfanet
 # Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
 # Created      : 12 Mar 2023
-# Updated      : 20 Jul 2025
+# Updated      : 10 Aug 2025
 # Comments     :
 # TODO (rick)  :
 # License      : GNU General Public License, version 2.0
@@ -43,9 +43,13 @@ SECONDS=0
 ## Functions ##
 
 transfer_status() {
-  # Exit script if transfer fails.
-  xfr_status="$1"
-  (( xfr_status != 0 )) && die "A transfer failed! Check network status." "$xfr_status"
+  local xfr_status="$1"
+  if [[ "$xfr_status" -eq 0 ]]; then
+		printf "Transfer successful\n"
+	else
+		printf "%s A transfer failed. Code: %d. Check network status.\n" "$RED_ERROR" "$xfr_status" >&2
+		# die "A transfer failed! Check network status." "$xfr_status"
+	fi
 }
 
 syncscript() {
@@ -76,16 +80,6 @@ syncscript() {
   rsync -avh --delete --include="*.kdbx" --exclude="*" "$HOME"/Documents/ "$LOCALNET.$hostip":Documents/
   exit_status="$?"
   transfer_status "$exit_status"
-
-  # printf "\n%sSyncing ~/.bashrc ...%s\n" "$orange" "$normal"
-  # rsync -avh --delete "$HOME"/.bashrc "$LOCALNET.$hostip":
-  # exit_status="$?"
-  # transfer_status "$exit_status"
-
-  # printf "\n%sSyncing ~/.bash_aliases ...%s\n" "$orange" "$normal"
-  # rsync -avh --delete "$HOME"/.bash_aliases "$LOCALNET.$hostip":
-  # exit_status="$?"
-  # transfer_status "$exit_status"
 
   printf "\n%sSyncing ~/.local/share/doc ...%s\n" "$orange" "$normal"
   rsync -avh --delete "$HOME"/.local/share/doc/ "$LOCALNET.$hostip":.local/share/doc/
@@ -197,7 +191,7 @@ check_host() {
 main() {
   local script version
   local -r script="${0##*/}"
-  local -r version="4.6.25201"
+  local -r version="4.7.25222"
   box "$script $version" "-"
   check_host
   over_line "Syncronization completed in $(format_time $SECONDS)" "-"
