sync-repos: sync_script() - exclude ~/Work/images

diff --git a/sync-repos b/sync-repos
--- a/sync-repos
+++ b/sync-repos
@@ -7,7 +7,7 @@
 # Author       : Copyright © 2025 Richard B. Romig, Mosfanet
 # Email        : rick.romig@gmail | rick.romig@mymetronet.net
 # Created      : 10 Aug 2025
-# Updated      : 17 Nov 2025
+# Updated      : 10 Mar 2026
 # Comments     :
 # TODO (Rick)  :
 # License      : GNU General Public License, version 2.0
@@ -33,19 +33,19 @@ if [[ -x "$HOME/bin/functionlib" ]]; then
   source "$HOME/bin/functionlib"
 else
   printf "\e[91mERROR:\e[0m functionlib not found!\n" >&2
-  exit 1
+  exit 81
 fi
 
 ## Global Variables ##
 
 readonly script="${0##*/}"
-readonly version="3.2.25321"
+readonly version="3.3.26069"
 
 ## Functions ##
 
 help() {
-	local errcode="${1:-2}"
-	local -r updated="17 Nov 2025"
+	local errcode="${1:-1}"
+	local -r updated="10 Mar 2026"
 	cat << _HELP_
 ${orange}$script${normal} $version, Upated: $updated
 Synchronixe Git repositories and work directories between local computers.
@@ -120,7 +120,7 @@ sync_script() {
 	transfer_status "$exit_status"
 
   printf "\n%sSyncing ~/Work ...%s\n" "$orange" "$normal"
-  rsync -avh --delete "$HOME"/Work/ "$LOCALNET.$hostip":Work/
+  rsync -avh --delete --exclude="$HOME/Work/imagas" "$HOME"/Work/ "$LOCALNET.$hostip":Work/
   exit_status="$?"
   transfer_status "$exit_status"
 }
@@ -130,7 +130,7 @@ main() {
 	local_host="${HOSTNAME:-$(hostname)}"
 	noOpt="1"
 	optstr=":ghlm"
-	valid_host "$local_host" || { printf "%s Invalid host: %s\n" "$RED_ERROR" "$local_host" >&2; help 1; }
+	valid_host "$local_host" || { printf "%s Invalid host: %s\n" "$RED_ERROR" "$local_host" >&2; help "$E_INVALID_ARG"; }
 	check_package rsync
 	while getopts "$optstr" opt; do
 		case "$opt" in
@@ -144,11 +144,11 @@ main() {
 				transfer "10" "hp-800g2-sff" ;;
 			? )
 				printf "%s Invalid option -%s\n" "$RED_ERROR" "$OPTARG" >&2
-				help 2
+				help "$E_INVALID_ARG"
 		esac
 		noOpt=0
 	done
-	[[ "$noOpt" = 1 ]] && { printf "%s No argument passed.\n" "$RED_ERROR" >&2; help 1; }
+	[[ "$noOpt" = 1 ]] && { printf "%s No argument passed.\n" "$RED_ERROR" >&2; help "$E_MISSING_ARG"; }
 	shift "$(( OPTIND - 1 ))"
 	over_line "$script $version"
 	exit
