syncfin: updated sourcing of functionlib; transfer_status() on error, displays message and returns

diff --git a/syncfin b/syncfin
--- a/syncfin
+++ b/syncfin
@@ -24,32 +24,25 @@
 # GNU General Public License for more details.
 ##########################################################################
 
-## Shellcheck Directives ##
-# shellcheck source=/home/rick/bin/functionlib
-
 ## Source function library ##
-
-if [[ -x "$HOME/bin/functionlib" ]]; then
-  source "$HOME/bin/functionlib"
-else
-  printf "\e[91mERROR:\e[0m functionlib not found!\n" >&2
-  exit 1
-fi
+# shellcheck source=/home/rick/bin/functionlib
+source functionlib || { printf "\e[91mERROR:\e[0m Unable to source functionlib\n"; exit 1; }
 
 ## Global Variables ##
 
 SECONDS=0
+EC=0
 
 ## Functions ##
 
 transfer_status() {
   local xfr_status="$1"
-  if [[ "$xfr_status" -eq 0 ]]; then
-		printf "Transfer successful\n"
-	else
+	if [[ "$xfr_status" -gt 0 ]]; then
 		printf "%s A transfer failed. Code: %d. Check network status.\n" "$RED_ERROR" "$xfr_status" >&2
-		# die "A transfer failed! Check network status." "$xfr_status"
+		EC="$xfr_status"
+		return
 	fi
+	printf "Transfer successful\n"
 }
 
 transfer_to_fin() {
@@ -146,7 +139,7 @@ check_host() {
   elif [[ "$local_host" == "$fin_host" ]]; then
     transfer_to_main "$main_host" "$fin_host"
   else
-    die "Invalid client. $script must be run from either $main_host or $fin_host." 1
+    die "Invalid client. $script must be run from either $main_host or $fin_host." "$E_INVALID_HOST"
   fi
 }
 
@@ -157,7 +150,7 @@ main() {
   check_host
   over_line "Syncronization completed in $(format_time $SECONDS)" "-"
   printf "%s v%s\n" "$script" "$version"
-  exit
+  exit "$EC"
 }
 
 ## Execution ##
