syncrick: added check_host() to launch syncscript to appropriate system.

diff --git a/syncrick b/syncrick
--- a/syncrick
+++ b/syncrick
@@ -7,7 +7,7 @@
 # Author       : Copyright (C) 2023, Richard Romig, Mosfanet
 # Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
 # Created      : 12 Mar 2023
-# Updated      : 07 Apr 2025
+# Updated      : 16 May 2025
 # Comments     :
 # TODO (rick)  :
 # License      : GNU General Public License, version 2.0
@@ -40,27 +40,38 @@ transfer_status() {
 syncscript() {
   local hostip="$1"
 
-  printf "\n%sSyncing aliases...%s\n" "$orange" "$normal"
-   rsync -avh --delete "$HOME"/.bash_aliases "$LOCALNET.$hostip":
+  # Sync Audiobook files.
+  printf "\n%sSyncing Audio Books...%s\n" "$orange" "$normal"
+  rsync -avh --delete "$HOME"/Audiobooks/ "$LOCALNET.$hostip":Audiobooks/
   exit_status="$?"
   transfer_status "$exit_status"
 
-  printf "\n%sSyncing script configuration files...%s\n" "$orange" "$normal"
-  rsync -avh --delete "$HOME"/.config/scripts/ "$LOCALNET.$hostip":.config/scripts/
+  printf "\n%sSyncing Blog directory...%s\n" "$orange" "$normal"
+  rsync -avh --delete "$HOME"/Documents/Blogs/ "$LOCALNET.$hostip":Documents/Blogs/
   exit_status="$?"
   transfer_status "$exit_status"
 
-  printf "\n%sSyncing Password Databases...%s\n" "$orange" "$normal"
-  rsync -avh --delete --include="*.kdbx" --exclude="*" "$HOME"/Documents/ "$LOCALNET.$hostip":Documents/
+  printf "\n%sSyncing Dreams directory...%s\n" "$orange" "$normal"
+  rsync -avh --delete "$HOME"/Documents/Dreams/ "$LOCALNET.$hostip":Documents/Dreams/
   exit_status="$?"
   transfer_status "$exit_status"
 
-  printf "\n%sSyncing homepage directory...%s\n" "$orange" "$normal"
-  rsync -avh --delete "$HOME"/Documents/homepage/ "$LOCALNET.$hostip":Documents/homepage/
+  printf "\n%sSyncing Language directory...%s\n" "$orange" "$normal"
+  rsync -avh --delete "$HOME"/Documents/Language/ "$LOCALNET.$hostip":Documents/Language/
   exit_status="$?"
   transfer_status "$exit_status"
 
-  printf "\n%sSyncing .local/share/doc...%s\n" "$orange" "$normal"
+  printf "\n%sSyncing ~/.bashrc ...%s\n" "$orange" "$normal"
+  rsync -avh --delete "$HOME"/.bashrc "$LOCALNET.$hostip":
+  exit_status="$?"
+  transfer_status "$exit_status"
+
+  printf "\n%sSyncing ~/.bash_aliases ...%s\n" "$orange" "$normal"
+  rsync -avh --delete "$HOME"/.bash_aliases "$LOCALNET.$hostip":
+  exit_status="$?"
+  transfer_status "$exit_status"
+
+  printf "\n%sSyncing ~/.local/share/doc ...%s\n" "$orange" "$normal"
   rsync -avh --delete "$HOME"/.local/share/doc/ "$LOCALNET.$hostip":.local/share/doc/
   exit_status="$?"
   transfer_status "$exit_status"
@@ -75,11 +86,6 @@ syncscript() {
   exit_status="$?"
   transfer_status "$exit_status"
 
-  printf "\n%sSyncing Templates...%s\n" "$orange" "$normal"
-  rsync -avh --delete "$HOME"/Templates/ "$LOCALNET.$hostip":Templates/
-  exit_status="$?"
-  transfer_status "$exit_status"
-
   printf "\n%sSyncing Wallpaper directory...%s\n" "$orange" "$normal"
   rsync -avh --delete "$HOME"/Pictures/wallpaper/ "$LOCALNET.$hostip":Pictures/wallpaper/
   exit_status="$?"
@@ -90,45 +96,13 @@ syncscript() {
   exit_status="$?"
   transfer_status "$exit_status"
 
-  # Sync repositories
-  printf "\n%sSyncing Gitea Repositories...%s\n" "$orange" "$normal"
-  rsync -avh --delete "$HOME"/gitea/ "$LOCALNET.$hostip":gitea/
-  exit_status="$?"
-  transfer_status "$exit_status"
-
-  printf "\n%sSyncing Github Repositories...%s\n" "$orange" "$normal"
-  rsync -avh --delete "$HOME"/Projects/ "$LOCALNET.$hostip":Projects/
-  exit_status="$?"
-  transfer_status "$exit_status"
-
-  # Sync audiobooks files.
-  printf "\n%sSyncing Audio Books...%s\n" "$orange" "$normal"
-  rsync -avh --delete "$HOME"/Audiobooks/ "$LOCALNET.$hostip":Audiobooks/
-  exit_status="$?"
-  transfer_status "$exit_status"
-
-  printf "\n%sSyncing Blogs directory...%s\n" "$orange" "$normal"
-  rsync -avh --delete "$HOME"/Documents/Blogs/ "$LOCALNET.$hostip":Documents/Blogs/
-  exit_status="$?"
-  transfer_status "$exit_status"
-
-  printf "\n%sSyncing Dreams directory...%s\n" "$orange" "$normal"
-  rsync -avh --delete "$HOME"/Documents/Dreams/ "$LOCALNET.$hostip":Documents/Dreams/
-  exit_status="$?"
-  transfer_status "$exit_status"
-
-  printf "\n%sSyncing Journals directory...%s\n" "$orange" "$normal"
-  rsync -avh --delete "$HOME"/Documents/Journals/ "$LOCALNET.$hostip":Documents/Journals/
-  exit_status="$?"
-  transfer_status "$exit_status"
-
   printf "\n%sSyncing Quotes directory...%s\n" "$orange" "$normal"
   rsync -avh --delete "$HOME"/Documents/Quotes/ "$LOCALNET.$hostip":Documents/Quotes/
   exit_status="$?"
   transfer_status "$exit_status"
 
-  printf "\n%sSyncing Language directory...%s\n" "$orange" "$normal"
-  rsync -avh --delete "$HOME"/Documents/Language/ "$LOCALNET.$hostip":Documents/Language/
+  printf "\n%sSyncing Journals directory...%s\n" "$orange" "$normal"
+  rsync -avh --delete "$HOME"/Documents/Journals/ "$LOCALNET.$hostip":Documents/Journals/
   exit_status="$?"
   transfer_status "$exit_status"
 
@@ -146,19 +120,27 @@ syncscript() {
   rsync -avh --delete "$HOME"/Downloads/Code/ "$LOCALNET.$hostip":Downloads/Code/
   exit_status="$?"
   transfer_status "$exit_status"
+
+  printf "\n%sSyncing Projects Repositories...%s\n" "$orange" "$normal"
+  rsync -avh --delete "$HOME"/Projects/ "$LOCALNET.$hostip":Projects/
+  exit_status="$?"
+  transfer_status "$exit_status"
+
+  printf "\n%sSyncing Gitea Repositories...%s\n" "$orange" "$normal"
+  rsync -avh --delete "$HOME"/gitea/ "$LOCALNET.$hostip":gitea/
+  exit_status="$?"
+  transfer_status "$exit_status"
 }
 
 sync_to_laptop() {
-  local main_host lap_host lap_ip wifi_ip
-  main_host="$1"
-  lap_host="$2"
-  lap_ip="22"
-  wifi_ip="153"
-
+  local main_host="$1"
+  local lap_host="$2"
+  local lap_ip="22"
+  local wifi_ip="153"
   if ping -c 3 "$LOCALNET.$lap_ip" >/dev/null 2>&1; then
-     printf "Syncing %s to %s ...\n" "$main_host" "$lap_host"
-     syncscript "$lap_ip"
-     printf "\n%s synced with %s.\n" "$lap_host" "$main_host"
+    printf "Syncing %s to %s ...\n" "$main_host" "$lap_host"
+    syncscript "$lap_ip"
+    printf "\n%s synced with %s.\n" "$lap_host" "$main_host"
   elif ping -c 3 "$LOCALNET.$wifi_ip" >/dev/null 2>&1; then
     printf "Syncing %s to %s ...\n" "$main_host" "$lap_host"
     syncscript "$wifi_ip"
@@ -169,11 +151,9 @@ sync_to_laptop() {
 }
 
 sync_to_main() {
-  local main_host lap_host main_ip
-  main_host="$1"
-  lap_host="$2"
-  main_ip="10"
-
+  local main_host="$1"
+  local lap_host="$2"
+  local main_ip="10"
   if ping -c 3 "$LOCALNET.$main_ip" >/dev/null 2>&1; then
     default_no "Are you sure you want to sync to $main_host?" || leave "Sync to $main_host canceled."
     printf "Syncing %s to %s ...\n" "$lap_host" "$main_host"
@@ -184,26 +164,26 @@ sync_to_main() {
   fi
 }
 
-main() {
-  local lap_host local_host main_host script version
-  script=$(basename "$0")
-  version="4.4.25097"
-  local_host="${HOSTNAME:-$(hostname)}"
-  main_host="hp-800g2-sff"
-  lap_host="hp-850-g3"
-
-  box "$script v$version" "-"
-  printf "Synchronizes files between %s and %s.\n" "$main_host" "$lap_host"
-
-  # Check host
+check_host() {
+  local local_host="${HOSTNAME:-$(hostname)}"
+  local main_host="hp-800g2-sff"
+  local lap_host="hp-850-g3"
   if [[ "$local_host" == "$main_host" ]]; then
     sync_to_laptop "$main_host" "$lap_host"
   elif [[ "$local_host" == "$lap_host" ]]; then
     sync_to_main "$main_host" "$lap_host"
   else
-    die "Invalid client. $script must be run from either $main_host or $lap_host."
+    die "Invalid client. $script must be run from either $main_host or $lap_host." 1
   fi
+}
 
+main() {
+  local script version
+  script=$(basename "$0")
+  version="4.4.25136"
+  box "$script $version" "-"
+  printf "Synchronizes files between %s and %s.\n" "$main_host" "$lap_host"
+  check_host
   over_line "Syncronization completed in $(format_time $SECONDS)" "-"
   printf "%s v%s\n" "$script" "$version"
   exit
