syncmosfa: updated local variables & return codes

diff --git a/syncmosfa b/syncmosfa
--- a/syncmosfa
+++ b/syncmosfa
@@ -7,39 +7,34 @@
 # Author       : Copyright (C) 2020 Richard Romig, 29 Sep 2020
 # Email        : rick.romig@gmail.com
 # Created      : 29 Sep 2020
-# Last updated : 06 Jun 2026
-# Comments     : Can sync to one or all machines on the network.
+# Updated      : 03 Aug 2026
+# Version      : 4.8.26215
+# Comments     : Can sync to one, some, or all machines on the network.
 #              : LOCALNET is declared in functionlib
 # TODO (rick)  :
 # License      : GNU General Public License, version 2.0
 # License URL  : https://github.com/RickRomig/scripts/blob/main/LICENSE
-##########################################################################
-# This program is free software; you can redistribute it and/or modify
-# it under the terms of the GNU General Public License as published by
-# the Free Software Foundation; either version 2 of the License, or
-# (at your option) any later version.
+###############################################################################
+# This program is free software; you can redistribute it and/or modify it under
+# the terms of the GNU General Public License as published by the Free Software
+# Foundation; either version 2 of the License, or (at your option) any later
+# version.
 #
-# This program is distributed in the hope that it will be useful,
-# but WITHOUT ANY WARRANTY; without even the implied warranty of
-# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
-# GNU General Public License for more details.
+# This program is distributed in the hope that it will be useful, but WITHOUT
+# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
+# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
 ###############################################################################
 
-## Source function library ##
-# shellcheck source=/home/rick/bin/functionlib
-source ~/bin/functionlib || { printf "\e[91mERROR:\e[0m Unable to source ~/bin/functionlib\n"; exit 1; }
+# shellcheck source=/home/rick/bin/functionlib.bash
+source ~/bin/functionlib.bash || { printf "\e[91mERROR:\e[0m Unable to source functionlib.bash\n"; exit 1; }
 
-## Global Variables ##
-
-readonly script="${0##*/}"
-readonly version="4.7.26157"
 SECONDS=0
 
-## Functions ##
-
 help() {
-	local errcode="${1:-1}"
-	local updated="06 Jun 2026"
+  local -r script="$1"
+  local -r version="$2"
+	local -ri errcode="${3:-1}"
+	local updated="03 Aug 2026"
 	cat << _HELP_
 ${orange}$script${normal} $version ($updated)
 Syncs directories with machines on the network via SSH
@@ -66,22 +61,23 @@ _HELP_
 }
 
 transfer_status() {
-  local xfr_status="$1"
-  if [[ "$xfr_status" -eq 0 ]]; then
-		printf "Transfer successful\n"
-	else
+  local -i xfr_status="$1"
+	if [[ "$xfr_status" -gt 0 ]]; then
 		printf "%s A transfer failed. Code: %d. Check network status.\n" "$RED_ERROR" "$xfr_status" >&2
+		return "$xfr_status"
 	fi
+	printf "Transfer successful\n"
+	return 0
 }
 
 transfer() {
-  local ip_addr hostip
-  hostip="$1"
-  # Skip local machine:
+  local -ri hostip="$1"
+  local ip_addr
   ip_addr="$(local_ip)"
+  # Skip local machine:
   if [[ "$ip_addr" == "$hostip" ]]; then
     printf "%sSkipping Machine %s (local client)%s\n\n" "$green" "$hostip" "$normal"
-    return
+    return "$E_INVALID_HOST"
   fi
   # Check for machines and sync if on-line:
   printf "%sChecking for %s...%s\n" "$green" "$hostip" "$normal"
@@ -96,79 +92,70 @@ transfer() {
 }
 
 syncscript() {
-  local exit_status hostip
-  hostip="$1"
+  local -r hostip="$1"
 
   printf "\n%sSyncing Password Databases...%s\n" "$orange" "$normal"
   rsync -avh --delete --include="*.kdbx" --exclude="*" "$HOME"/Documents/ "$LOCALNET.$hostip":Documents/
-  exit_status="$?"
-  transfer_status "$exit_status"
+  transfer_status "$?"
 
   printf "\n%sSyncing ~/Pictures/wallpaper... %s\n" "$orange" "$normal"
   rsync -avh --delete "$HOME"/Pictures/wallpaper/ "$LOCALNET.$hostip":Pictures/wallpaper/
-  exit_status="$?"
-  transfer_status "$exit_status"
+  transfer_status "$?"
 
   printf "\n%sSyncing ~/Pictures/backgrounds... %s\n" "$orange" "$normal"
   rsync -avh --delete "$HOME"/Pictures/backgrounds/ "$LOCALNET.$hostip":Pictures/backgrounds/
-  exit_status="$?"
-  transfer_status "$exit_status"
+  transfer_status "$?"
 
   case "$hostip" in
     16|22|153 )
       printf "\n%sSyncing Deb Packages...%s\n" "$orange" "$normal"
       rsync -avh --delete "$HOME"/debpkgs/  "$LOCALNET.$hostip":debpkgs/
-      exit_status="$?"
-      transfer_status "$exit_status"
+      transfer_status "$?"
 
       printf "\n%sSyncing Git Repositories...%s\n" "$orange" "$normal"
       rsync -avh --delete "$HOME"/gitea/ "$LOCALNET.$hostip":gitea/
-      exit_status="$?"
-      transfer_status "$exit_status"
+      transfer_status "$?"
 
       printf "\n%sSyncing Projects Repositories...%s\n" "$orange" "$normal"
       rsync -avh --delete "$HOME"/Projects/ "$LOCALNET.$hostip":Projects/
-      exit_status="$?"
-      transfer_status "$exit_status"
+      transfer_status "$?"
 
       printf "\n%sSyncing ~/Documements/mosfanet ...%s\n" "$orange" "$normal"
       rsync -avh --delete "$HOME"/Documents/mosfanet/ "$LOCALNET.$hostip":Documents/mosfanet/
-      exit_status="$?"
-      transfer_status "$exit_status"
+      transfer_status "$?"
 
       printf "\n%sSyncing ~/Work ...%s\n" "$orange" "$normal"
       rsync -avh --delete --exclude 'images' "$HOME"/Work/ "$LOCALNET.$hostip":Work/
-      exit_status="$?"
-      transfer_status "$exit_status"
+      transfer_status "$?"
       ;;
     11|12|13|14|15|19|20|23 )
       printf "\n%sSyncing ~/Documements/mosfanet ...%s\n" "$orange" "$normal"
       rsync -avh --delete "$HOME"/Documents/mosfanet/ "$LOCALNET.$hostip":Documents/mosfanet/
-      exit_status="$?"
-      transfer_status "$exit_status"
+      transfer_status "$?"
 
       printf "\n%sSyncing ~/Work ...%s\n" "$orange" "$normal"
       rsync -avh --delete --exclude 'images' "$HOME"/Work/ "$LOCALNET.$hostip":Work/
-      exit_status="$?"
-      transfer_status "$exit_status"
+      transfer_status "$?"
       ;;
     * )
       # 17, 21, 24. 25 exclusions
       printf "\nExcluded from sync. Mosfanet and Work directories were not synchronized.\n"
   esac
+
+	return 0
 }
 
 sync_one() {
-  local hostip="$1"
+  local -ri hostip="$1"
   if [[ "$hostip" -gt 0 && "$hostip" -lt 10 ]]; then
     printf "%s %s is a restricted address. Access denied.\n" "$RED_WARNING" $"$LOCALNET.$hostip"
-    exit
+    return "$E_INVALID_HOST"
   elif valid_ip "$hostip"; then
     printf "Synchronizing bin and template directories with %s:\n\n" "$LOCALNET.$hostip"
     transfer "$hostip"
-    all_done
+    return 0
   else
-    help "$?"
+    help "$script" "$version" "$?"
   fi
 }
 
@@ -186,9 +173,10 @@ sync_some() {
       esac
     else
       printf "%s Invalid argument: %s\n\n" "$RED_ERROR" "$hostip" >&2
+      return "$E_INVALID_ARG"
     fi
   done
-  all_done
+  return 0
 }
 
 sync_all() {
@@ -198,29 +186,26 @@ sync_all() {
   for hostip in "${octets[@]}"; do
     transfer "$hostip"
   done
-  all_done
-}
-
-all_done() {
-  box "All directories synced!" "-"
-  printf "Script completed in %s\n" "$(format_time $SECONDS)"
+  return 0
 }
 
 check_host() {
-  local main_host local_host ip_addr
-  main_host="hp-800g2-sff"
-  local_host="${HOSTNAME:-$(hostname)}"
+  local -r main_host="hp-800g2-sff"
+  local -r local_host="${HOSTNAME:-$(hostname)}"
+  local -i ip_addr
   ip_addr="$(local_ip)"
   printf "Host: %s%s%s at " "$lightyellow" "$local_host" "$normal"
   printf "%s%s%s\n\n" "$lightyellow" "$LOCALNET.$ip_addr" "$normal"
-  [[ "$local_host" != "$main_host" ]] && leave "Script must be run from $main_host!"
+  [[ "$local_host" != "$main_host" ]] && die "Script must be run from $main_host" "$E_INVALID_HOST"
 }
 
 main() {
+  local -r script="${0##*/}"
+  local -r version="4.8.26215"
   check_package rsync
   if [[ "$#" -eq 0 ]]; then
     printf "%s No arguments passed.\n" "$RED_ERROR" >&2
-    help 2
+    help "$script" "$version" "$E_MISSING_ARG"
   elif [[ "$1" == "-h" || "$1" == "--help" ]]; then
     help 0
   elif [[ "$1" == "-a" || "$1" == "--all" ]]; then
@@ -233,10 +218,9 @@ main() {
     check_host
     sync_one "$1"
   fi
+  over_line "Script completed in $(format_time $SECONDS)"
   over_line "$script $version"
   exit
 }
-
-## Execution ##
 
 main "$@"
