system-info 3.2.7: Changed lhost declaration. removed `;;` from default case in case-statements.

diff --git a/system-info b/system-info
--- a/system-info
+++ b/system-info
@@ -27,9 +27,9 @@ fi
 ## Variables ##
 
 _script=$(basename "$0"); readonly _script
-readonly _version="3.2.6"
-readonly _updated="11 Apr 2023"
-lhost="$(uname -n)"; readonly lhost
+readonly _version="3.2.7"
+readonly _updated="02 May 2023"
+readonly lhost="${HOSTNAME:-$(hostname)}"
 readonly info_file="$HOME/$lhost.info"
 today=$(date +'%d %B %Y'); readonly today
 
@@ -61,7 +61,6 @@ save_info() {
         break ;;
       * )
         echo "${lightred}Invalid choice!${normal} 1 = Yes | 2 = No" >&2
-        ;;
     esac
   done
 }
@@ -90,7 +89,6 @@ rename_mnt_pt() {
         break ;;
       * )
         echo "${lightred}Invalid choice!${normal} Choose 1, 2, 3, or 4" >&2
-        ;;
     esac
   done
 }
@@ -105,7 +103,7 @@ ff_fix() {
       2 ) hd_ff="3.5 inch"; break ;;
       3 ) hd_ff="less than 1.8 inch"; break ;;
       4 ) break ;;
-      * ) echo "${lightred}Invalid choice!${normal} Choose 1, 2, 3, or 4" >&2 ;;
+      * ) echo "${lightred}Invalid choice!${normal} Choose 1, 2, 3, or 4" >&2
     esac
   done
 }
