Changed capacity line in ssd_hd_info() to use tr to remove parentheses around hard drive size instead of sed.

diff --git a/system-info b/system-info
--- a/system-info
+++ b/system-info
@@ -27,8 +27,8 @@ fi
 ## Variables ##
 
 _script=$(basename "$0"); readonly _script
-readonly _version="3.4.2"
-readonly _updated="20 Dec 2023"
+readonly _version="3.4.3"
+readonly _updated="22 Dec 2023"
 readonly lhost="${HOSTNAME:-$(hostname)}"
 readonly info_file="$HOME/$lhost.info"
 today=$(date +'%d %B %Y'); readonly today
@@ -42,7 +42,7 @@ check_dependencies() {
 }
 
 # shellcheck disable=SC2317 # Don't warn about unreachable commands in this function
-# ShellCheck may incorrectly believe that code is unreachable if it's invoked by variable name or in a trap.
+# ShellCheck may incorrectly believe that code is unreachable if it's invoked by a variable name or in a trap.
 cleanup() {
   [[ -f "$tmp_file" ]] && rm -f "$tmp_file"
   [[ -f "$hd_data" ]] && rm -f "$hd_data"
@@ -113,7 +113,7 @@ ff_fix() {
         break
       ;;
       * )
-        printf "%s Invalid choice!$ Choose 1, 2, 3, or 4\n1" >&2 "$red_error"
+        printf "%s Invalid choice! Choose 1, 2, 3, or 4\n" >&2 "$red_error"
     esac
   done
 }
@@ -185,14 +185,14 @@ ssd_hd_info() {
     printf "%s\n" "$(grep -w dev "$hd_data")"
     printf "   %-15s%s\n" "Model Number:" "$(awk -F: '/Model/ {print $NF}' "$hd_data" | sed 's/^ *//g')"
     printf "   %-15s%s\n" "Serial Number:" "$(awk -F: '/Serial N/ {print $NF}' "$hd_data" | sed 's/^ *//g')"
-    printf "   %-15s%s\n" "Capacity:" "$(awk '/GB/ {print $(NF-1),$NF}' "$hd_data" | sed 's/[)(]//g')"
+    printf "   %-15s%s\n" "Capacity:" "$(awk '/GB/ {print $(NF-1),$NF}' "$hd_data" | tr -d '()')" # sed 's/[)(]//g')"
     hd_ff=$(awk -F: '/Form Factor/ {print $NF}' "$hd_data" | sed 's/^ //')
     [[ -z "$hd_ff" ]] && ff_fix
     printf "   %-15s%s" "Form Factor:" "$hd_ff"
     hd_rpm=$(awk -F: '/Rotation/ {print $NF}' "$hd_data" | sed 's/^ //')
     case "$hd_rpm" in
-    	[0-9]* ) printf " %s-rpm Hard Disk Drive\n" "$hd_rpm" ;;
-    	* ) printf " %s\n" "$hd_rpm" ;;
+      [0-9]* ) printf " %s-rpm Hard Disk Drive\n" "$hd_rpm" ;;
+      * ) printf " %s\n" "$hd_rpm"
     esac
 	done
 }
