system-info: updated indentation

diff --git a/system-info b/system-info
--- a/system-info
+++ b/system-info
@@ -7,8 +7,8 @@
 # Author       : Copyright (C) 2022, Richard B. Romig, Mosfanet
 # Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
 # Created      : 15 Jul 2022
-# Updated:     : 24 Aug 2026
-# Versin       : 7.4.26236
+# Updated:     : 10 Sep 2026
+# Versin       : 7.5.26253
 # Comments     : Should be run locally, not remotely. (DESKTOP_SESSION)
 #              : Will not get desktop session info in an SSH connection.
 # TODO (Rick)  :
@@ -34,90 +34,90 @@ TMP_FILE=$(mktemp -q) || die "Failed to create temporary file." "$E_TEMP_FILE"  
 
 check_dependencies() {
 	local packages=( lshw ieee-data wmctrl )
-  check_packages "${packages[@]}"
-  [[ -b /dev/sda ]] && check_package hdparm
-  [[ -c /dev/nvme0 ]] && check_package nvme-cli
-  return 0
+	check_packages "${packages[@]}"
+	[[ -b /dev/sda ]] && check_package hdparm
+	[[ -c /dev/nvme0 ]] && check_package nvme-cli
+	return 0
 }
 
 # ShellCheck may incorrectly believe that code is unreachable if it's invoked by a variable name or in a trap.
 # shellcheck disable=SC2317 # Don't warn about unreachable commands in this function
 clean_up() {
-  [[ -f "$TMP_FILE" ]] && rm -f "$TMP_FILE"
-  [[ -f "$HD_DATA" ]] && rm -f "$HD_DATA"
+	[[ -f "$TMP_FILE" ]] && rm -f "$TMP_FILE"
+	[[ -f "$HD_DATA" ]] && rm -f "$HD_DATA"
 }
 
 save_info() {
-  local -r main_host="hp-800g2-ssf"
-  local -ri main_ip="10"
-  local -i ip_addr
-  printf "\n"
-  if default_yes "Save system information to ~/${INFO_FILE##*/}?"; then
-    printf "Writing system information to ~/%s\n" "${INFO_FILE##*/}"
-    cp -v "$TMP_FILE" "$INFO_FILE"
-    chmod 664 "$INFO_FILE"
-    if default_yes "Copy ${INFO_FILE##*/} to $main_host?"; then
-      ip_addr=$(local_ip)
-      [[ "$ip_addr" != "$main_ip" ]] && scp -p "$INFO_FILE" rick@"$LOCALNET.$main_ip":Documents/mosfanet/Computers/info/
-    else
-      printf "System information was not written to ~/%s\n" "$main_host"
-    fi
-  else
-    printf "System information was not written to ~/%s\n" "${INFO_FILE##*/}"
-  fi
-  return 0
+	local -r main_host="hp-800g2-ssf"
+	local -ri main_ip="10"
+	local -i ip_addr
+	printf "\n"
+	if default_yes "Save system information to ~/${INFO_FILE##*/}?"; then
+		printf "Writing system information to ~/%s\n" "${INFO_FILE##*/}"
+		cp -v "$TMP_FILE" "$INFO_FILE"
+		chmod 664 "$INFO_FILE"
+		if default_yes "Copy ${INFO_FILE##*/} to $main_host?"; then
+			ip_addr=$(local_ip)
+			[[ "$ip_addr" != "$main_ip" ]] && scp -p "$INFO_FILE" rick@"$LOCALNET.$main_ip":Documents/mosfanet/Computers/info/
+		else
+			printf "System information was not written to ~/%s\n" "$main_host"
+		fi
+	else
+		printf "System information was not written to ~/%s\n" "${INFO_FILE##*/}"
+	fi
+	return 0
 }
 
 rename_mnt_pt() {
-  local ts_drv _opt
-  ts_drv=$(awk '/timeshift/ {print $3}' < <(mount))
-  printf "\nRename the mountpoint for %s to:\n" "$ts_drv"
-  PS3="Select the appropriate mountpoint: "
-  select _opt in "/home" "/data" "/ (root)" "/run/timeshift/backup"; do
-    case $REPLY in
-      1 )
-        sed -i '/timeshift/s/run\/timeshift\/backup/home/' "$TMP_FILE"
-        printf "%s mountpoint changed to /home\n" "$ts_drv"
-        break ;;
-      2 )
-        sed -i '/timeshift/s/run\/timeshift\/backup/data/' "$TMP_FILE"
-        printf "%s mountpoint changed to /data\n" "$ts_drv"
-        break ;;
-      3 )
-        sed -i '/timeshift/s/run\/timeshift\/backup//' "$TMP_FILE"
-        printf "%s mountpoint changed to /\n" "$ts_drv"
-        break ;;
-      4 )
-        printf "%s mountpoint left as is." "$ts_drv"
-        break ;;
-      * )
-        printf "%s Invalid choice! Select 1, 2, 3, or 4\n" >&2 "$RED_ERROR"
-    esac
-  done
-  return 0
+	local ts_drv _opt
+	ts_drv=$(awk '/timeshift/ {print $3}' < <(mount))
+	printf "\nRename the mountpoint for %s to:\n" "$ts_drv"
+	PS3="Select the appropriate mountpoint: "
+	select _opt in "/home" "/data" "/ (root)" "/run/timeshift/backup"; do
+		case $REPLY in
+			1 )
+				sed -i '/timeshift/s/run\/timeshift\/backup/home/' "$TMP_FILE"
+				printf "%s mountpoint changed to /home\n" "$ts_drv"
+				break ;;
+			2 )
+				sed -i '/timeshift/s/run\/timeshift\/backup/data/' "$TMP_FILE"
+				printf "%s mountpoint changed to /data\n" "$ts_drv"
+				break ;;
+			3 )
+				sed -i '/timeshift/s/run\/timeshift\/backup//' "$TMP_FILE"
+				printf "%s mountpoint changed to /\n" "$ts_drv"
+				break ;;
+			4 )
+				printf "%s mountpoint left as is." "$ts_drv"
+				break ;;
+			* )
+				printf "%s Invalid choice! Select 1, 2, 3, or 4\n" >&2 "$RED_ERROR"
+		esac
+	done
+	return 0
 }
 
 fix_hd_ff() {
-  local _opt options hd_ff
-  printf "Form factor not displayed in Hard Disk Information.\n" >&2
-  PS3="Select form factor: " >&2
-  options=( "2.5 inch" "3.5 inch" "less than 1.8 inch" "ignore")
-  select _opt in "${options[@]}"; do
-    case "$REPLY" in
-      1 ) hd_ff="2.5 inch"; break ;;
-      2 ) hd_ff="3.5 inch"; break ;;
-      3 ) hd_ff="less than 1.8 inch"; break ;;
-      4 ) : ; break ;;
-      * ) printf "%s Invalid choice! Choose 1, 2, 3, or 4\n" >&2 "$RED_ERROR"
-    esac
-  done
-  echo "$hd_ff"
-  return 0
+	local _opt hd_ff
+	local -r options=( "2.5 inch" "3.5 inch" "less than 1.8 inch" "ignore")
+	printf "Form factor not displayed in Hard Disk Information.\n" >&2
+	PS3="Select form factor: " >&2
+	select _opt in "${options[@]}"; do
+		case "$REPLY" in
+			1 ) hd_ff="2.5 inch"; break ;;
+			2 ) hd_ff="3.5 inch"; break ;;
+			3 ) hd_ff="less than 1.8 inch"; break ;;
+			4 ) : ; break ;;
+			* ) printf "%s Invalid choice! Choose 1, 2, 3, or 4\n" >&2 "$RED_ERROR"
+		esac
+	done
+	echo "$hd_ff"
+	return 0
 }
 
 mfg_info() {
-  local dmi_dir mfg_version mfg_serial
-	dmi_dir=/sys/class/dmi/id
+	local -r dmi_dir=/sys/class/dmi/id
+	local mfg_version mfg_serial
 	mfg_version=$(< $dmi_dir/product_version)
 	[[ "${mfg_version// }" ]] || mfg_version="Not specified"
 	mfg_serial=$(sudo cat $dmi_dir/product_serial)
@@ -126,130 +126,130 @@ mfg_info() {
 	printf "%-14s %s\n" "Product name:" "$(< $dmi_dir/product_name)"
 	printf "%-14s %s\n" "Version:" "$mfg_version"
 	printf "%-14s %s\n" "Serial number:" "$mfg_serial"
-  return 0
+	return 0
 }
 
 os_info() {
-  local desktop root_part created_date
-  desktop="$DESKTOP_SESSION"
-  [[ "$desktop" == "bunsenlabs" || "$desktop" == "lightdm-xsession" ]] && desktop=$(awk '/Name/ {print $2}' < <(wmctrl -m))
-  root_part=$(awk '$NF == "/" {print $1}' < <(df -P))
+	local desktop root_part created_date
+	desktop="$DESKTOP_SESSION"
+	[[ "$desktop" == "bunsenlabs" || "$desktop" == "lightdm-xsession" ]] && desktop=$(awk '/Name/ {print $2}' < <(wmctrl -m))
+	root_part=$(awk '$NF == "/" {print $1}' < <(df -P))
 	created_date=$(awk '/created:/ {print $(NF-2),$(NF-3),$NF}' < <(sudo /usr/sbin/tune2fs -l "$root_part"))
 	printf "\n%-19s %s\n" "Operating System:" "$(uname -o)"
 	printf "%-19s %s\n" "Distribution:" "$(get_distribution)"
-  printf "%-19s %s\n" "Desktop:" "$desktop"
+	printf "%-19s %s\n" "Desktop:" "$desktop"
 	printf "%-19s %s\n" "Filesystem created:" "$created_date"
-  return 0
+	return 0
 }
 
 cpu_info() {
-  local arch model threads
-  model=$(awk -F: '/Model name:/ {print $NF}' < <(/usr/bin/lscpu) | sed 's/^[[:space:]]*//g;s/([^)]*)//g')
-  arch=$(awk '/Architecture:/ {print $NF}' < <(/usr/bin/lscpu))
-  threads=$(awk '/CPU\(s\):/ {print $NF;exit}' < <(/usr/bin/lscpu))
+	local arch model threads
+	model=$(awk -F: '/Model name:/ {print $NF}' < <(/usr/bin/lscpu) | sed 's/^[[:space:]]*//g;s/([^)]*)//g')
+	arch=$(awk '/Architecture:/ {print $NF}' < <(/usr/bin/lscpu))
+	threads=$(awk '/CPU\(s\):/ {print $NF;exit}' < <(/usr/bin/lscpu))
 	printf "\n%-9s %s, %s, %s threads \n" "CPU:" "$model" "$arch" "$threads"
-  return 0
+	return 0
 }
 
 memory_info() {
-  local mem_max mem_type phys_mem
+	local mem_max mem_type phys_mem
 	phys_mem=$(awk '/System/ {print $(NF-2)}' < <(sudo /usr/bin/lshw -class memory -short -quiet) | sed 's/GiB/ GiB/')
 	# mem_type=$(awk '/Type:/ {print $NF; exit}' < <(sudo dmidecode --type 17))
   mem_type=$(awk 'NR == 16 {print $NF}' < <(sudo dmidecode --type 17))
 	# mem_max=$(awk -F: '/Capacity/ {print $NF; exit}' < <(sudo dmidecode --type 16))
   mem_max=$(awk -F: 'NR == 10 {print $NF}' < <(sudo dmidecode --type 16) | sed 's/^ //')
 	printf "%-9s %s %s (%s maximum)\n" "Memory:" "$phys_mem" "$mem_type" "$mem_max"
-  return 0
+	return 0
 }
 
 graphics_info() {
 	printf "%-9s %s\n" "Graphics:" "$( awk -F: '/VGA/ {print $NF}' < <(/usr/bin/lspci) | sed 's/^ //')"
-  return 0
+	eturn 0
 }
 
 mac_mfgr() {
-  local mfgr oui_file
-  local -r mac_addr="${1^^}"
-  local -r oui_file="/usr/share/ieee-data/oui.csv"
-  oui_addr=$(sed 's/://g' < <(cut -d':' -f1,2,3 <<< "$mac_addr"))
-  mfgr=$(cut -d',' -f3 < <(grep -m 1 "$oui_addr" "$oui_file"))
-  [[ "$mfgr" ]] || mfgr="Unspecified"
-  echo "$mfgr"
-  return 0
+	local -r mac_addr="${1^^}"
+	local -r oui_file=/usr/share/ieee-data/oui.csv
+	local mfgr oui_file
+	oui_addr=$(sed 's/://g' < <(cut -d':' -f1,2,3 <<< "$mac_addr"))
+	mfgr=$(cut -d',' -f3 < <(grep -m 1 "$oui_addr" "$oui_file"))
+	[[ "$mfgr" ]] || mfgr="Unspecified"
+	echo "$mfgr"
+	return 0
 }
 
 wired_info() {
-  local eth_int ethernet_dev e_mac e_mfg
+	local eth_int ethernet_dev e_mac e_mfg
 	eth_int=$(awk '/name: e/ {print $NF}' < <(sudo /usr/bin/lshw -class network -quiet))
 	if [[ "$eth_int" ]]; then
 		ethernet_dev=$(awk -F: '/Ethernet controller/ {print $NF}' < <(/usr/bin/lspci) | sed 's/^ //')
 		e_mac=$(< /sys/class/net/"${eth_int}"/address)
 		e_mfg=$(mac_mfgr "$e_mac")
 		printf "\nEthernet: %s\n" "$ethernet_dev"
-    printf "   %-13s %s\n" "Device name:" "$eth_int" "MAC address:" "$e_mac" "Manufacturer:" "$e_mfg"
+		printf "   %-13s %s\n" "Device name:" "$eth_int" "MAC address:" "$e_mac" "Manufacturer:" "$e_mfg"
 	fi
-  return 0
+	return 0
 }
 
 wireless_info() {
-  local wifi_int wireless_dev w_mac w_mfg
+	local wifi_int wireless_dev w_mac w_mfg
 	wifi_int=$(awk '/name: w/ {print $NF}' < <(sudo /usr/bin/lshw -class network -quiet))
 	if [[ "$wifi_int" ]]; then
 		wireless_dev=$(awk -F: '/Network controller/ {print $NF}' < <(/usr/bin/lspci) | sed 's/^ //')
 		w_mac=$(< /sys/class/net/"${wifi_int}"/address)
 		w_mfg=$(mac_mfgr "$w_mac")
 		printf "\nWireless: %s\n" "$wireless_dev"
-	  printf "   %-13s %s\n" "Device name:" "$wifi_int" "MAC address:" "$w_mac" "Manufacturer:" "$w_mfg"
+		printf "   %-13s %s\n" "Device name:" "$wifi_int" "MAC address:" "$w_mac" "Manufacturer:" "$w_mfg"
 	fi
-  return 0
+	return 0
 }
 
 ssd_hd_info() {
-  local disk hd_ff hd_rpm model
-  HD_DATA=$(mktemp -q) || die "Failed to create temporary file." "$E_TEMP_DIR"
+	local disk hd_ff hd_rpm model
+	HD_DATA=$(mktemp -q) || die "Failed to create temporary file." "$E_TEMP_DIR"
 	printf "\nHard Disk Information:\n"
 	for disk in /dev/sd[a-z]; do
-    tee "$HD_DATA" > /dev/null < <(sudo hdparm -I "${disk}" 2>/dev/null)
-    printf "%s\n" "$(sed 's/\/dev\///;s/:$//' < <(grep -w dev "$HD_DATA"))"
-    model="$(sed 's/^ *//g' < <(awk -F: '/Model/ {print $NF}' "$HD_DATA"))"
-    vendor="$(get_vendor "$model")"
-    printf "   %-15s%s\n" "Vendor:" "$vendor"
-    printf "   %-15s%s\n" "Model Number:" "$model"
-    printf "   %-15s%s\n" "Serial Number:" "$(sed 's/^ *//g' < <(awk -F: '/Serial N/ {print $NF}' "$HD_DATA"))"
-    printf "   %-15s%s\n" "Capacity:" "$(tr -d '()' < <(awk '/GB/ {print $(NF-1),$NF}' "$HD_DATA"))"
-    hd_ff=$(sed 's/^ //' < <(awk -F: '/Form Factor/ {print $NF}' "$HD_DATA"))
-    [[ "$hd_ff" ]] || hd_ff=$(fix_hd_ff)
-    printf "   %-15s%s" "Form Factor:" "$hd_ff"
-    hd_rpm=$(sed 's/^ //' < <(awk -F: '/Rotation/ {print $NF}' "$HD_DATA"))
-    case "$hd_rpm" in
-      [0-9]* ) printf " %s-rpm Hard Disk Drive\n" "$hd_rpm" ;;
-      * ) printf " %s\n" "$hd_rpm"
-    esac
+	tee "$HD_DATA" > /dev/null < <(sudo hdparm -I "${disk}" 2>/dev/null)
+	printf "%s\n" "$(sed 's/\/dev\///;s/:$//' < <(grep -w dev "$HD_DATA"))"
+	model="$(sed 's/^ *//g' < <(awk -F: '/Model/ {print $NF}' "$HD_DATA"))"
+	vendor="$(get_vendor "$model")"
+	printf "   %-15s%s\n" "Vendor:" "$vendor"
+	printf "   %-15s%s\n" "Model Number:" "$model"
+	printf "   %-15s%s\n" "Serial Number:" "$(sed 's/^ *//g' < <(awk -F: '/Serial N/ {print $NF}' "$HD_DATA"))"
+	printf "   %-15s%s\n" "Capacity:" "$(tr -d '()' < <(awk '/GB/ {print $(NF-1),$NF}' "$HD_DATA"))"
+	hd_ff=$(sed 's/^ //' < <(awk -F: '/Form Factor/ {print $NF}' "$HD_DATA"))
+	[[ "$hd_ff" ]] || hd_ff=$(fix_hd_ff)
+	printf "   %-15s%s" "Form Factor:" "$hd_ff"
+	hd_rpm=$(sed 's/^ //' < <(awk -F: '/Rotation/ {print $NF}' "$HD_DATA"))
+	case "$hd_rpm" in
+		[0-9]* ) printf " %s-rpm Hard Disk Drive\n" "$hd_rpm" ;;
+		* ) printf " %s\n" "$hd_rpm"
+	esac
 	done
-  return 0
+	return 0
 }
 
 nvme_info() {
-  local nvme_data devline model
-  printf "\nNVMe Information:\n"
-  nvme_data=$(tail -n+3 < <(sudo /usr/sbin/nvme list) | xargs)
-  for devline in "${nvme_data[@]}"; do
-    printf "%s\n" "$(awk -F'/' '{print $3}' <<< "$devline")"
-    model=$(awk '{print $4}' <<< "$devline")
-    printf "   %-15s%s\n" "Vendor:" "$(get_vendor "$model")"
-    printf "   %-15s%s\n" "Model Number:" "$model"
-    printf "   %-15s%s\n" "Serial Number:" "$(awk '{print $3}' <<< "$devline")"
-    printf "   %-15s%s\n" "Capacity:" "$(awk '/dev/ {print $(NF-7),$(NF-6)}' <<< "$devline")"
-  done
-  return 0
+	local nvme_data devline model
+	printf "\nNVMe Information:\n"
+	nvme_data=$(tail -n+3 < <(sudo /usr/sbin/nvme list) | xargs)
+	for devline in "${nvme_data[@]}"; do
+		printf "%s\n" "$(awk -F'/' '{print $3}' <<< "$devline")"
+		model=$(awk '{print $4}' <<< "$devline")
+		printf "   %-15s%s\n" "Vendor:" "$(get_vendor "$model")"
+		printf "   %-15s%s\n" "Model Number:" "$model"
+		printf "   %-15s%s\n" "Serial Number:" "$(awk '{print $3}' <<< "$devline")"
+		printf "   %-15s%s\n" "Capacity:" "$(awk '/dev/ {print $(NF-7),$(NF-6)}' <<< "$devline")"
+	done
+	return 0
 }
 
 # shellcheck disable=SC2001 # See if you can use ${variable//search/replace} instead.
 # This would eliminate all whitespace in the string
 get_vendor() {
-  local model="${1^^}"
-  local id
-  local re="[[:space:]]+"
+	local -r model="${1^^}"
+	local id
+	local -r re="[[:space:]]+"
 	declare -rA vendor_list=(
 		[CS]="PNY"
 		[CT]="Crucial"
@@ -266,67 +266,67 @@ get_vendor() {
 		[ST]="Seagate"
 		[WD]="Western Digital"
 	)
-  model=$(sed 's/[[:space:]]*$//' <<< "$model")
-  [[ $model =~ $re ]] && model=$(cut -d' ' -f2 <<< "$model")
-  id=$(cut -c1-2 <<< "$model")
+	model=$(sed 's/[[:space:]]*$//' <<< "$model")
+	[[ $model =~ $re ]] && model=$(cut -d' ' -f2 <<< "$model")
+	id=$(cut -c1-2 <<< "$model")
 	printf "%s" "${vendor_list[$id]}"
-  return 0
+	return 0
 }
 
 partition_info() {
 	printf "\nPartition Information:\n"
 	/usr/bin/lsblk -o NAME,SIZE,TYPE,ROTA,MOUNTPOINT,MODEL,SERIAL
-  return 0
+	return 0
 }
 
 battery_info() {
-  local battery_name battery_path battery_data battery_serial
-  printf "\nBattery Information:\n"
-  battery_name=$(awk -F/ '/BAT/ {print $NF}' < <(find /sys/class/power_supply/ -name "BAT*"))
-  if [[ -z "$battery_name" ]]; then
-    printf "No battery detected\n"
-    return 0
-  fi
-  battery_path="/sys/class/power_supply/$battery_name"
-  battery_data=$(< "$battery_path"/uevent)
-  battery_serial=$(awk -F= '/SERIAL/ {print $NF}' <<< "$battery_data")
-  [[ -z "$battery_serial" || "$battery_serial" == " " ]] && battery_serial="Not specified"
-  printf "%s\n" "$battery_name"
-  printf "   %-15s%s\n" "Manufacturer:" "$(sed 's/^ //' < <(awk -F= '/MANUFACTURER/ {print $NF}' <<< "$battery_data"))"
-  printf "   %-15s%s\n" "Model name:" "$(awk -F= '/MODEL/ {print $NF}' <<< "$battery_data")"
-  printf "   %-15s%s\n" "Serial number:" "$battery_serial"
-  printf "   %-15s%s\n" "Technology:" "$(awk -F= '/TECHNOLOGY/ {print $NF}' <<< "$battery_data")"
-  return 0
+	local battery_name battery_path battery_data battery_serial
+	printf "\nBattery Information:\n"
+	battery_name=$(awk -F/ '/BAT/ {print $NF}' < <(find /sys/class/power_supply/ -name "BAT*"))
+	if [[ -z "$battery_name" ]]; then
+		printf "No battery detected\n"
+		return 0
+	fi
+	battery_path="/sys/class/power_supply/$battery_name"
+	battery_data=$(< "$battery_path"/uevent)
+	battery_serial=$(awk -F= '/SERIAL/ {print $NF}' <<< "$battery_data")
+	[[ -z "$battery_serial" || "$battery_serial" == " " ]] && battery_serial="Not specified"
+	printf "%s\n" "$battery_name"
+	printf "   %-15s%s\n" "Manufacturer:" "$(sed 's/^ //' < <(awk -F= '/MANUFACTURER/ {print $NF}' <<< "$battery_data"))"
+	printf "   %-15s%s\n" "Model name:" "$(awk -F= '/MODEL/ {print $NF}' <<< "$battery_data")"
+	printf "   %-15s%s\n" "Serial number:" "$battery_serial"
+	printf "   %-15s%s\n" "Technology:" "$(awk -F= '/TECHNOLOGY/ {print $NF}' <<< "$battery_data")"
+	return 0
 }
 
 main() {
-  local -r script="${0##*/}"
-  local -r version="7.4.26236"
-  trap clean_up EXIT
-  sudo_login 2
-  check_dependencies
-  clearscreen
-  {
-	  printf "System information for %s, as of %(%d %B %Y)T\n\n" "$LOCAL_HOST" -1
-	  mfg_info
-	  os_info
-	  cpu_info
-	  memory_info
-	  graphics_info
-	  wired_info
-	  wireless_info
-    [[ -b /dev/sda ]] && ssd_hd_info
-    [[ -c /dev/nvme0 ]] && nvme_info
-	  partition_info
-	  is_laptop && battery_info
-	  over_line "$script $version"
-  } | tee "$TMP_FILE"
+	local -r script="${0##*/}"
+	local -r version="7.5.26253"
+	trap clean_up EXIT
+	sudo_login 2
+	check_dependencies
+	clearscreen
+	{
+		printf "System information for %s, as of %(%d %B %Y)T\n\n" "$LOCAL_HOST" -1
+		mfg_info
+		os_info
+		cpu_info
+		memory_info
+		graphics_info
+		wired_info
+		wireless_info
+		[[ -b /dev/sda ]] && ssd_hd_info
+		[[ -c /dev/nvme0 ]] && nvme_info
+		partition_info
+		is_laptop && battery_info
+		over_line "$script $version"
+	} | tee "$TMP_FILE"
 
-  # Change lsblk timeshift mountpoint to normal partition name.
-  grep -q '/run/timeshift/backup' "$TMP_FILE" && rename_mnt_pt
-  # Save system info to file in the home directory?
-  save_info
-  exit
+	# Change lsblk timeshift mountpoint to normal partition name.
+	grep -q '/run/timeshift/backup' "$TMP_FILE" && rename_mnt_pt
+	# Save system info to file in the home directory?
+	save_info
+	exit
 }
 
 main "$@"
