system-info: updated locla variables & return codes; renamed ff_fix() to fix_hd_ff()

diff --git a/system-info b/system-info
--- a/system-info
+++ b/system-info
@@ -7,46 +7,41 @@
 # Author       : Copyright (C) 2022, Richard B. Romig, Mosfanet
 # Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
 # Created      : 15 Jul 2022
-# Updated:     : 26 Jun 2026
-# Comments     : Should be run locally, not remotely.
+# Updated:     : 04 Aug 2026
+# Versin       : 7.3.26216
+# Comments     : Should be run locally, not remotely. (DESKTOP_SESSION)
 #              : Will not get desktop session info in an SSH connection.
 # TODO (Rick)  :
 # License      : GNU General Public License, version 2.0
 # License URL  : https://github.com/RickRomig/scripts/blob/main/LICENSE
 ###############################################################################
-# This program is free software; you can redistribute it and/or modify
-# it under the terms of the GNU General Public License as published by
-# the Free Software Foundation; either version 2 of the License, or
-# (at your option) any later version.
+# This program is free software; you can redistribute it and/or modify it under
+# the terms of the GNU General Public License as published by the Free Software
+# Foundation; either version 2 of the License, or (at your option) any later
+# version.
 #
-# This program is distributed in the hope that it will be useful,
-# but WITHOUT ANY WARRANTY; without even the implied warranty of
-# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
-# GNU General Public License for more details.
+# This program is distributed in the hope that it will be useful, but WITHOUT
+# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
+# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
 ###############################################################################
 
-## Load function library ##
-# shellcheck source=/home/rick/bin/functionlib
-source ~/bin/functionlib || { printf "\e[91mERROR:\e[0m Unable to source functionlib\n"; exit 1; }
-
-## Global Variables ##
+# shellcheck source=/home/rick/bin/functionlib.bash
+source ~/bin/functionlib.bash || { printf "\e[91mERROR:\e[0m Unable to source functionlib.bash\n"; exit 1; }
 
 readonly LOCAL_HOST="${HOSTNAME:-$(hostname)}"
 readonly INFO_FILE="$HOME/$LOCAL_HOST.info"
 TMP_FILE=$(mktemp -q) || die "Failed to create temporary file." "$E_TEMP_FILE"  # For INFO_FILE
-
-## Functions ##
 
 check_dependencies() {
 	local packages=( lshw ieee-data wmctrl )
   check_packages "${packages[@]}"
   [[ -b /dev/sda ]] && check_package hdparm
   [[ -c /dev/nvme0 ]] && check_package nvme-cli
+  return 0
 }
 
-# Don't warn about unreachable commands in this function
 # ShellCheck may incorrectly believe that code is unreachable if it's invoked by a variable name or in a trap.
-# shellcheck disable=SC2317
+# shellcheck disable=SC2317 # Don't warn about unreachable commands in this function
 cleanup() {
   [[ -f "$TMP_FILE" ]] && rm -f "$TMP_FILE"
   [[ -f "$HD_DATA" ]] && rm -f "$HD_DATA"
@@ -54,10 +49,10 @@ cleanup() {
 
 save_info() {
   local -r main_host="hp-800g2-ssf"
-  local -r main_ip="10"
-  local ip_addr
+  local -ri main_ip="10"
+  local -i ip_addr
   printf "\n"
-  if default_yes "Save system information to ~/${INFO_FILE##*/}"; then
+  if default_yes "Save system information to ~/${INFO_FILE##*/}?"; then
     printf "Writing system information to ~/%s\n" "${INFO_FILE##*/}"
     cp -v "$TMP_FILE" "$INFO_FILE"
     chmod 664 "$INFO_FILE"
@@ -70,6 +65,7 @@ save_info() {
   else
     printf "System information was not written to ~/%s\n" "${INFO_FILE##*/}"
   fi
+  return 0
 }
 
 rename_mnt_pt() {
@@ -98,37 +94,30 @@ rename_mnt_pt() {
         printf "%s Invalid choice! Select 1, 2, 3, or 4\n" >&2 "$RED_ERROR"
     esac
   done
+  return 0
 }
 
-ff_fix() {
+fix_hd_ff() {
   local _opt options hd_ff
   printf "Form factor not displayed in Hard Disk Information.\n" >&2
   PS3="Select form factor: " >&2
   options=( "2.5 inch" "3.5 inch" "less than 1.8 inch" "ignore")
   select _opt in "${options[@]}"; do
     case "$REPLY" in
-      1 )
-        hd_ff="2.5 inch"
-        break ;;
-      2 )
-        hd_ff="3.5 inch"
-        break ;;
-      3 )
-        hd_ff="less than 1.8 inch"
-        break ;;
-      4 )
-        :
-        break ;;
-      * )
-        printf "%s Invalid choice! Choose 1, 2, 3, or 4\n" >&2 "$RED_ERROR"
+      1 ) hd_ff="2.5 inch"; break ;;
+      2 ) hd_ff="3.5 inch"; break ;;
+      3 ) hd_ff="less than 1.8 inch"; break ;;
+      4 ) : ; break ;;
+      * ) printf "%s Invalid choice! Choose 1, 2, 3, or 4\n" >&2 "$RED_ERROR"
     esac
   done
   echo "$hd_ff"
+  return 0
 }
 
 mfg_info() {
   local dmi_dir mfg_version mfg_serial
-	dmi_dir="/sys/class/dmi/id"
+	dmi_dir=/sys/class/dmi/id
 	mfg_version=$(< $dmi_dir/product_version)
 	[[ "${mfg_version// }" ]] || mfg_version="Not specified"
 	mfg_serial=$(sudo cat $dmi_dir/product_serial)
@@ -137,6 +126,7 @@ mfg_info() {
 	printf "%-14s %s\n" "Product name:" "$(< $dmi_dir/product_name)"
 	printf "%-14s %s\n" "Version:" "$mfg_version"
 	printf "%-14s %s\n" "Serial number:" "$mfg_serial"
+  return 0
 }
 
 os_info() {
@@ -147,8 +137,9 @@ os_info() {
 	created_date=$(awk '/created:/ {print $(NF-2),$(NF-3),$NF}' < <(sudo /usr/sbin/tune2fs -l "$root_part"))
 	printf "\n%-19s %s\n" "Operating System:" "$(uname -o)"
 	printf "%-19s %s\n" "Distribution:" "$(get_distribution)"
-  printf "%-19s %s\n" "Desktop:" "${desktop^}"
+  printf "%-19s %s\n" "Desktop:" "$desktop"
 	printf "%-19s %s\n" "Filesystem created:" "$created_date"
+  return 0
 }
 
 cpu_info() {
@@ -157,20 +148,23 @@ cpu_info() {
   arch=$(awk '/Architecture:/ {print $NF}' < <(/usr/bin/lscpu))
   threads=$(awk '/CPU\(s\):/ {print $NF;exit}' < <(/usr/bin/lscpu))
 	printf "\n%-9s %s, %s, %s threads \n" "CPU:" "$model" "$arch" "$threads"
+  return 0
 }
 
 memory_info() {
   local mem_max mem_type phys_mem
-	phys_mem=$(awk '/System/ {print $(NF-2)}' < <(sudo /usr/bin/lshw -class memory -short -quiet) | sed 's/GiB/ GB/')
+	phys_mem=$(awk '/System/ {print $(NF-2)}' < <(sudo /usr/bin/lshw -class memory -short -quiet) | sed 's/GiB/ GiB/')
 	# mem_type=$(awk '/Type:/ {print $NF; exit}' < <(sudo dmidecode --type 17))
   mem_type=$(awk 'NR == 16 {print $NF}' < <(sudo dmidecode --type 17))
 	# mem_max=$(awk -F: '/Capacity/ {print $NF; exit}' < <(sudo dmidecode --type 16))
   mem_max=$(awk -F: 'NR == 10 {print $NF}' < <(sudo dmidecode --type 16) | sed 's/^ //')
 	printf "%-9s %s %s (%s maximum)\n" "Memory:" "$phys_mem" "$mem_type" "$mem_max"
+  return 0
 }
 
 graphics_info() {
 	printf "%-9s %s\n" "Graphics:" "$( awk -F: '/VGA/ {print $NF}' < <(/usr/bin/lspci) | sed 's/^ //')"
+  return 0
 }
 
 mac_mfgr() {
@@ -181,6 +175,7 @@ mac_mfgr() {
   mfgr=$(cut -d',' -f3 < <(grep -m 1 "$oui_addr" "$oui_file"))
   [[ "$mfgr" ]] || mfgr="Unspecified"
   echo "$mfgr"
+  return 0
 }
 
 wired_info() {
@@ -193,6 +188,7 @@ wired_info() {
 		printf "\nEthernet: %s\n" "$ethernet_dev"
     printf "   %-13s %s\n" "Device name:" "$eth_int" "MAC address:" "$e_mac" "Manufacturer:" "$e_mfg"
 	fi
+  return 0
 }
 
 wireless_info() {
@@ -205,6 +201,7 @@ wireless_info() {
 		printf "\nWireless: %s\n" "$wireless_dev"
 	  printf "   %-13s %s\n" "Device name:" "$wifi_int" "MAC address:" "$w_mac" "Manufacturer:" "$w_mfg"
 	fi
+  return 0
 }
 
 ssd_hd_info() {
@@ -221,7 +218,7 @@ ssd_hd_info() {
     printf "   %-15s%s\n" "Serial Number:" "$(sed 's/^ *//g' < <(awk -F: '/Serial N/ {print $NF}' "$HD_DATA"))"
     printf "   %-15s%s\n" "Capacity:" "$(tr -d '()' < <(awk '/GB/ {print $(NF-1),$NF}' "$HD_DATA"))"
     hd_ff=$(sed 's/^ //' < <(awk -F: '/Form Factor/ {print $NF}' "$HD_DATA"))
-    [[ "$hd_ff" ]] || hd_ff=$(ff_fix)
+    [[ "$hd_ff" ]] || hd_ff=$(fix_hd_ff)
     printf "   %-15s%s" "Form Factor:" "$hd_ff"
     hd_rpm=$(sed 's/^ //' < <(awk -F: '/Rotation/ {print $NF}' "$HD_DATA"))
     case "$hd_rpm" in
@@ -229,6 +226,7 @@ ssd_hd_info() {
       * ) printf " %s\n" "$hd_rpm"
     esac
 	done
+  return 0
 }
 
 nvme_info() {
@@ -243,10 +241,11 @@ nvme_info() {
     printf "   %-15s%s\n" "Serial Number:" "$(awk '{print $3}' <<< "$devline")"
     printf "   %-15s%s\n" "Capacity:" "$(awk '/dev/ {print $(NF-7),$(NF-6)}' <<< "$devline")"
   done
+  return 0
 }
 
-# See if you can use ${variable//search/replace} instead. (This would eliminate all whitespace in the string)
-# shellcheck disable=SC2001
+# shellcheck disable=SC2001 # See if you can use ${variable//search/replace} instead.
+# This would eliminate all whitespace in the string
 get_vendor() {
   local model="${1^^}"
   local id
@@ -271,35 +270,38 @@ get_vendor() {
   [[ $model =~ $re ]] && model=$(cut -d' ' -f2 <<< "$model")
   id=$(cut -c1-2 <<< "$model")
 	printf "%s" "${vendor_list[$id]}"
+  return 0
 }
 
 partition_info() {
 	printf "\nPartition Information:\n"
 	/usr/bin/lsblk -o NAME,SIZE,TYPE,ROTA,MOUNTPOINT,MODEL,SERIAL
+  return 0
 }
 
 battery_info() {
   local battery_name battery_path battery_data battery_serial
   printf "\nBattery Information:\n"
   battery_name=$(awk -F/ '/BAT/ {print $NF}' < <(find /sys/class/power_supply/ -name "BAT*"))
-  if [[ "$battery_name" ]]; then
-    battery_path="/sys/class/power_supply/$battery_name"
-    battery_data=$(< "$battery_path"/uevent)
-    battery_serial=$(awk -F= '/SERIAL/ {print $NF}' <<< "$battery_data")
-    [[ -z "$battery_serial" || "$battery_serial" == " " ]] && battery_serial="Not specified"
-    printf "%s\n" "$battery_name"
-    printf "   %-15s%s\n" "Manufacturer:" "$(sed 's/^ //' < <(awk -F= '/MANUFACTURER/ {print $NF}' <<< "$battery_data"))"
-    printf "   %-15s%s\n" "Model name:" "$(awk -F= '/MODEL/ {print $NF}' <<< "$battery_data")"
-    printf "   %-15s%s\n" "Serial number:" "$battery_serial"
-    printf "   %-15s%s\n" "Technology:" "$(awk -F= '/TECHNOLOGY/ {print $NF}' <<< "$battery_data")"
-  else
+  if [[ -z "$battery_name" ]]; then
     printf "No battery detected\n"
+    return 0
   fi
+  battery_path="/sys/class/power_supply/$battery_name"
+  battery_data=$(< "$battery_path"/uevent)
+  battery_serial=$(awk -F= '/SERIAL/ {print $NF}' <<< "$battery_data")
+  [[ -z "$battery_serial" || "$battery_serial" == " " ]] && battery_serial="Not specified"
+  printf "%s\n" "$battery_name"
+  printf "   %-15s%s\n" "Manufacturer:" "$(sed 's/^ //' < <(awk -F= '/MANUFACTURER/ {print $NF}' <<< "$battery_data"))"
+  printf "   %-15s%s\n" "Model name:" "$(awk -F= '/MODEL/ {print $NF}' <<< "$battery_data")"
+  printf "   %-15s%s\n" "Serial number:" "$battery_serial"
+  printf "   %-15s%s\n" "Technology:" "$(awk -F= '/TECHNOLOGY/ {print $NF}' <<< "$battery_data")"
+  return 0
 }
 
 main() {
   local -r script="${0##*/}"
-  local -r version="7.2.26177"
+  local -r version="7.3.26216"
   trap cleanup EXIT
   sudo_login 2
   check_dependencies
@@ -317,7 +319,7 @@ main() {
     [[ -c /dev/nvme0 ]] && nvme_info
 	  partition_info
 	  is_laptop && battery_info
-	  printf "\n%s v%s\n" "$script" "$version"
+	  over_line "$script $version"
   } | tee "$TMP_FILE"
 
   # Change lsblk timeshift mountpoint to normal partition name.
@@ -326,7 +328,5 @@ main() {
   save_info
   exit
 }
-
-## Execution ##
 
 main "$@"
