system-status: corrected process substitution

diff --git a/system-status b/system-status
--- a/system-status
+++ b/system-status
@@ -7,7 +7,7 @@
 # Author       : Copyright (C) 2018,Richard Romig, LudditeGeek@Mosfanet
 # Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
 # Created      : 17 Nov 2018
-# Updated      : 27 Apr 2026
+# Updated      : 31 May 2026
 # Comments     : Inspired by Joe Collins and Luke Smith
 # License      : GNU General Public License, version 2.0
 # License URL  : https://github.com/RickRomig/scripts/blob/main/LICENSE
@@ -23,23 +23,15 @@
 # GNU General Public License for more details.
 #####################################################################
 
-## Shellcheck Directives ##
+## source function library ##
 # shellcheck source=/home/rick/bin/functionlib
-
-## Source function library ##
-
-if [[ -x "$HOME/bin/functionlib" ]]; then
-  source "$HOME/bin/functionlib"
-else
-  printf "\e[91mERROR:\e[0m functionlib not found!\n" >&2
-  exit 81
-fi
+source ~/bin/functionlib || { printf "\e[91mERROR:\e[0m Unable to source functionlib\n"; exit 1; }
 
 ## Functions ##
 
 check_drivetemp() {
-  grep -qw drivetemp <(sensors) || sudo modprobe drivetemp
-  grep -qw drivetemp /etc/modules || sudo tee -a /etc/modules <<< echo drivetemp  # | sudo tee -a /etc/modules
+  grep -qw drivetemp < <(sensors) || sudo modprobe drivetemp
+  grep -qw drivetemp /etc/modules || sudo tee -a /etc/modules <<< echo drivetemp
   printf "drivetemp module - [OK]\n"
   sleep 1
   printf '\e[A\e[K'
@@ -53,19 +45,19 @@ check_dependencies() {
 }
 
 memory_usage() {
-	printf "\n%sMemory usage:%s %s\n" "$orange" "$normal" "$(awk '/^Mem:/ {print $3 " / " $2}' <(/usr/bin/free -h) | sed 's/i//g')"
+	printf "\n%sMemory usage:%s %s\n" "$orange" "$normal" "$(awk '/^Mem:/ {print $3 " / " $2}' < <(/usr/bin/free -h) | sed 's/i//g')"
   printf "%sProcess%s\t\t%sPercentage%s\n" "$underline" "$normal" "$underline" "$normal"
-	head -n 5 <(ps axch -o cmd:15,%mem --sort=-%mem)
+	head -n 5 < <(ps axch -o cmd:15,%mem --sort=-%mem)
 }
 
 cpu_usage() {
   local cores cpu_usage cpu_use
   cores="$(grep -c "^processor" /proc/cpuinfo)"
-  cpu_usage="$(awk 'BEGIN {sum=0} {sum+=$3}; END {print sum}' <(ps aux))"
+  cpu_usage="$(awk 'BEGIN {sum=0} {sum+=$3}; END {print sum}' < <(ps aux))"
   cpu_use="$((${cpu_usage/\.*} / ${cores:-1}))" # 1 core is the default value
 	printf "\n%sCPU usage: %s%s%%\n" "$orange" "$normal" "$cpu_use"
   printf "%sProcess%s\t\t%sPercentage%s\n" "$underline" "$normal" "$underline" "$normal"
-  head -n 5 <(ps axch -o cmd:15,%cpu --sort=-%cpu)
+  head -n 5 < <(ps axch -o cmd:15,%cpu --sort=-%cpu)
 }
 
 cpu_temperature(){
@@ -127,11 +119,12 @@ sata_temperature() {
 
 disk_usage() {
 	printf "\n%sDisk usage:%s\n" "$orange" "$normal"
-  sed -n '1p;/^\//p' <(/usr/bin/df -hT -x fuse.portal)
+  sed -n '1p;/^\//p' < <(/usr/bin/df -hT -x fuse.portal)
 }
 
 show_header() {
   local local_host="${HOSTNAME:-$(hostname)}"
+  clearscreen
   printf "%s%sSystem Status%s\n" "$bold" "$lightyellow" "$normal"
   printf "%s%-16s%s\n" "$orange" "Computer name:" "$local_host"
   printf "%-16s%s\n" "Distribution:" "$(get_distribution)"
@@ -141,9 +134,9 @@ show_header() {
 show_footer() {
   local last_boot up_time
   local -r script="${0##*/}"
-  local -r version="6.19.26117"
-  last_boot=$(awk '{print $(NF-1),$NF}' <(/usr/bin/who -b))
-  up_time=$(cut -d' ' -f2- <(/usr/bin/uptime -p))
+  local -r version="6.20.26151"
+  last_boot=$(awk '{print $(NF-1),$NF}' < <(/usr/bin/who -b))
+  up_time=$(cut -d' ' -f2- < <(/usr/bin/uptime -p))
   printf "\n%sUp since:%s %s (%s)\n" "$orange" "$normal" "$last_boot" "$up_time"
   over_line "$script $version"
   exit
@@ -153,7 +146,6 @@ main() {
   check_dependencies
   local sensor_json
   sensor_json="$(sensors -j 2>/dev/null)"
-  # sudo_login 1
   show_header
   memory_usage
   cpu_usage
