system-info - incorporated main()

diff --git a/system-info b/system-info
--- a/system-info
+++ b/system-info
@@ -7,7 +7,7 @@
 # Author       : Copyright (C) 2022, Richard B. Romig, Mosfanet
 # Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
 # Created      : 15 Jul 2022
-# Updated:     : 24 Aug 2024
+# Updated:     : 03 Oct 2024
 # Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
 # Comments     : Rewrite of version 2.5.0
 #              : Will not get desktop session info from an SSH connection. Run locally.
@@ -25,14 +25,6 @@ else
   printf "\e[91mERROR:\e[0m functionlib not found!\n" >&2
   exit 1
 fi
-
-## Global Variables ##
-
-_script=$(basename "$0"); readonly _script
-readonly _version="3.8.24237"
-readonly lhost="${HOSTNAME:-$(hostname)}"
-readonly info_file="$HOME/$lhost.info"
-today=$(date +'%d %B %Y'); readonly today
 
 ## Functions ##
 
@@ -270,36 +262,45 @@ battery_info() {
   fi
 }
 
+main() {
+  local script version lhost info_file today
+  script=$(basename "$0")
+  version="3.9.24277"
+  lhost="${HOSTNAME:-$(hostname)}"
+  info_file="$HOME/$lhost.info"
+  today=$(date +'%d %B %Y')
+
+  tmp_file=$(mktemp -q) || die "Failed to create temporary file." 1
+  trap cleanup EXIT
+  sudo_login 2
+  check_dependencies
+  clear
+  {
+	  printf "System information for %s, as of %s\n\n" "$lhost" "$today"
+	  mfg_info
+	  os_info
+	  cpu_info
+	  memory_info
+	  graphics_info
+	  wired_info
+	  wireless_info
+    if [[ -b /dev/sda ]]; then
+      hd_data=$(mktemp -q) || die "Failed to create temporary file." 1
+      ssd_hd_info
+    fi
+    [[ -c /dev/nvme0 ]] && nvme_info
+	  partition_info
+	  is_laptop && battery_info
+	  printf "\n%s v%s\n" "$script" "$version"
+  } | tee "$tmp_file"
+
+  # Change lsblk timeshift mountpoint to normal partition name.
+  grep -q '/run/timeshift/backup' "$tmp_file" && rename_mnt_pt
+  # Save system info to file in the home directory?
+  save_info
+  exit
+}
+
 ## Execution ##
 
-tmp_file=$(mktemp -q) || die "Failed to create temporary file." 1
-trap cleanup EXIT
-sudo_login 2
-check_dependencies
-clear
-{
-	printf "System information for %s, as of %s\n\n" "$lhost" "$today"
-	mfg_info
-	os_info
-	cpu_info
-	memory_info
-	graphics_info
-	wired_info
-	wireless_info
-  if [[ -b /dev/sda ]]; then
-    hd_data=$(mktemp -q) || die "Failed to create temporary file." 1
-    ssd_hd_info
-  fi
-  [[ -c /dev/nvme0 ]] && nvme_info
-	partition_info
-	is_laptop && battery_info
-	printf "\n%s v%s\n" "$_script" "$_version"
-} | tee "$tmp_file"
-
-# Change lsblk timeshift mountpoint to normal partition name.
-grep -q '/run/timeshift/backup' "$tmp_file" && rename_mnt_pt
-
-# Save system info to file in the home directory?
-save_info
-
-exit
+main "$@"
