system-info: mac_mfgr() process substitution for oui_addr & mfg variables; battery_info() process substitution for Manufacturer

diff --git a/system-info b/system-info
--- a/system-info
+++ b/system-info
@@ -7,7 +7,7 @@
 # Author       : Copyright (C) 2022, Richard B. Romig, Mosfanet
 # Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
 # Created      : 15 Jul 2022
-# Updated:     : 26 Apr 2026
+# Updated:     : 10 Jun 2026
 # Comments     : Should be run locally, not remotely.
 #              : Will not get desktop session info in an SSH connection.
 # TODO (Rick)  :
@@ -27,7 +27,7 @@
 
 ## Load function library ##
 # shellcheck source=/home/rick/bin/functionlib
-source functionlib || { printf "\e[91mERROR:\e[0m Unable to source functionlib\n"; exit 1; }
+source ~/bin/functionlib || { printf "\e[91mERROR:\e[0m Unable to source functionlib\n"; exit 1; }
 
 ## Global Variables ##
 
@@ -50,7 +50,6 @@ check_dependencies() {
 cleanup() {
   [[ -f "$TMP_FILE" ]] && rm -f "$TMP_FILE"
   [[ -f "$HD_DATA" ]] && rm -f "$HD_DATA"
-  # [[ -f "$NVME_JSON" ]] && rm -f  "$NVME_JSON"
 }
 
 save_info() {
@@ -75,7 +74,6 @@ save_info() {
 
 rename_mnt_pt() {
   local ts_drv _opt
-  # ts_drv=$(mount | awk '/timeshift/ {print $3}' | cut -d' ' -f1)
   ts_drv=$(awk '/timeshift/ {print $3}' < <(mount))
   printf "\nRename the mountpoint for %s to:\n" "$ts_drv"
   PS3="Select the appropriate mountpoint: "
@@ -176,36 +174,36 @@ graphics_info() {
 }
 
 mac_mfgr() {
-  local mac_addr mfgr oui_addr oui_file
-  mac_addr="${1^^}"
-  oui_file="/usr/share/ieee-data/oui.csv"
-	oui_addr=$(cut -d ':' -f1,2,3 <<< "$mac_addr" | sed 's/://g')
-  mfgr=$(grep -m 1 "$oui_addr" "$oui_file" | cut -d',' -f3 )
+  local mfgr oui_file
+  local -r mac_addr="${1^^}"
+  local -r oui_file="/usr/share/ieee-data/oui.csv"
+  oui_addr=$(sed 's/://g' < <(cut -d':' -f1,2,3 <<< "$mac_addr"))
+  mfgr=$(cut -d',' -f3 < <(grep -m 1 "$oui_addr" "$oui_file"))
   [[ "$mfgr" ]] || mfgr="Unspecified"
   echo "$mfgr"
 }
 
 wired_info() {
-  local eth_int ethernet_dev e_mac e_man
+  local eth_int ethernet_dev e_mac e_mfg
 	eth_int=$(awk '/name: e/ {print $NF}' < <(sudo /usr/bin/lshw -class network -quiet))
 	if [[ "$eth_int" ]]; then
 		ethernet_dev=$(awk -F: '/Ethernet controller/ {print $NF}' < <(/usr/bin/lspci) | sed 's/^ //')
 		e_mac=$(< /sys/class/net/"${eth_int}"/address)
-		e_man=$(mac_mfgr "$e_mac")
+		e_mfg=$(mac_mfgr "$e_mac")
 		printf "\nEthernet: %s\n" "$ethernet_dev"
-    printf "   %-13s %s\n" "Device name:" "$eth_int" "MAC address:" "$e_mac" "Manufacturer:" "$e_man"
+    printf "   %-13s %s\n" "Device name:" "$eth_int" "MAC address:" "$e_mac" "Manufacturer:" "$e_mfg"
 	fi
 }
 
 wireless_info() {
-  local wifi_int wireless_dev w_mac w_man
+  local wifi_int wireless_dev w_mac w_mfg
 	wifi_int=$(awk '/name: w/ {print $NF}' < <(sudo /usr/bin/lshw -class network -quiet))
 	if [[ "$wifi_int" ]]; then
 		wireless_dev=$(awk -F: '/Network controller/ {print $NF}' < <(/usr/bin/lspci) | sed 's/^ //')
 		w_mac=$(< /sys/class/net/"${wifi_int}"/address)
-		w_man=$(mac_mfgr "$w_mac")
+		w_mfg=$(mac_mfgr "$w_mac")
 		printf "\nWireless: %s\n" "$wireless_dev"
-	  printf "   %-13s %s\n" "Device name:" "$wifi_int" "MAC address:" "$w_mac" "Manufacturer:" "$w_man"
+	  printf "   %-13s %s\n" "Device name:" "$wifi_int" "MAC address:" "$w_mac" "Manufacturer:" "$w_mfg"
 	fi
 }
 
@@ -235,7 +233,6 @@ ssd_hd_info() {
 
 nvme_info() {
   local nvme_data devline model
-  # NVME_JSON=$(mktemp -q) || die "Failed to create temporary file." "$E_TEMP_DIR"
   printf "\nNVMe Information:\n"
   nvme_data=$(tail -n+3 < <(sudo /usr/sbin/nvme list) | xargs)
   for devline in "${nvme_data[@]}"; do
@@ -291,11 +288,11 @@ battery_info() {
     battery_serial=$(awk -F= '/SERIAL/ {print $NF}' <<< "$battery_data")
     [[ -z "$battery_serial" || "$battery_serial" == " " ]] && battery_serial="Not specified"
     printf "%s\n" "$battery_name"
-    printf "   %-15s%s\n" "Manufacturer:" "$(awk -F= '/MANUFACTURER/ {print $NF}' <<< "$battery_data" | sed 's/^ //')"
+    printf "   %-15s%s\n" "Manufacturer:" "$(sed 's/^ //' < <(awk -F= '/MANUFACTURER/ {print $NF}' <<< "$battery_data"))"
     printf "   %-15s%s\n" "Model name:" "$(awk -F= '/MODEL/ {print $NF}' <<< "$battery_data")"
     printf "   %-15s%s\n" "Serial number:" "$battery_serial"
     printf "   %-15s%s\n" "Technology:" "$(awk -F= '/TECHNOLOGY/ {print $NF}' <<< "$battery_data")"
-else
+  else
     printf "No battery detected\n"
   fi
 }
