system-info: implemented here-strings in nvme_info(), get_vendor(), & battery_info()

diff --git a/system-info b/system-info
--- a/system-info
+++ b/system-info
@@ -7,7 +7,7 @@
 # Author       : Copyright (C) 2022, Richard B. Romig, Mosfanet
 # Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
 # Created      : 15 Jul 2022
-# Updated:     : 09 Mar 2026
+# Updated:     : 18 Mar 2026
 # Comments     : Should be run locally, not remotely.
 #              : Will not get desktop session info in an SSH connection.
 # TODO (Rick)  :
@@ -45,7 +45,8 @@ check_dependencies() {
   [[ -c /dev/nvme0 ]] && check_package nvme-cli
 }
 
-# shellcheck disable=SC2317 # Don't warn about unreachable commands in this function
+# shellcheck disable=SC2317
+# Don't warn about unreachable commands in this function
 # ShellCheck may incorrectly believe that code is unreachable if it's invoked by a variable name or in a trap.
 cleanup() {
   [[ -f "$tmp_file" ]] && rm -f "$tmp_file"
@@ -236,17 +237,17 @@ nvme_info() {
   printf "\nNVMe Information:\n"
   nvme_data=$(sudo /usr/sbin/nvme list | tail -n+3)
   for devline in "${nvme_data[@]}"; do
-    printf "%s\n" "$(echo "$devline" | awk '/dev/ {print $1}' | cut -d'/' -f3)"
-    model="$(echo "$devline" | awk '/dev/ {print $4,$5}' | sed 's/ [0-9].*$//')"
+    printf "%s\n" "$(awk '/dev/ {print $1}' <<< "$devline" | cut -d'/' -f3)"
+    model=$(awk '/dev/ {print $4,$5}' <<< "$devline" | sed 's/ [0-9].*$//')
     printf "   %-15s%s\n" "Vendor:" "$(get_vendor "$model")"
     printf "   %-15s%s\n" "Model Number:" "$model"
-    printf "   %-15s%s\n" "Serial Number:" "$(echo "$devline" | awk '/dev/ {print $3}')"
-    printf "   %-15s%s\n" "Capacity:" "$(echo "$devline" | awk '/dev/ {print $(NF-7),$(NF-6)}')"
+    printf "   %-15s%s\n" "Serial Number:" "$(awk '/dev/ {print $3}' <<< "$devline")"
+    printf "   %-15s%s\n" "Capacity:" "$(awk '/dev/ {print $(NF-7),$(NF-6)}' <<< "$devline")"
   done
 }
 
 # shellcheck disable=SC2001
-# See if you can use ${variable//search/replace} instead. (This eliminates all whitespace in the string)
+# See if you can use ${variable//search/replace} instead. (This woulf eliminate all whitespace in the string)
 get_vendor() {
   local model="${1^^}"
   local id
@@ -266,9 +267,9 @@ get_vendor() {
 		[ST]="Seagate"
 		[WD]="Western Digital"
 	)
-  model="$(sed 's/[[:space:]]*$//' <(echo "$model"))"
-  [[ "$model" =~ [[:space:]]+ ]] && model="$(cut -d' ' -f2 <(echo "$model"))"
-  id="$(cut -c1-2 <(echo "$model"))"
+  model=$(sed 's/[[:space:]]*$//' <<< "$model")
+  [[ "$model" =~ [[:space:]]+ ]] && model=$(cut -d' ' -f2 <<< "$model")
+  id=$(cut -c1-2 <<< "$model")
 	printf "%s" "${vendor_list[$id]}"
 }
 
@@ -287,18 +288,18 @@ battery_info() {
     battery_serial=$(awk -F= '/SERIAL/ {print $NF}' <(echo "$battery_data"))
     [[ -z "$battery_serial" || "$battery_serial" == " " ]] && battery_serial="Not specified"
     printf "%s\n" "$battery_name"
-    printf "   %-15s%s\n" "Manufacturer:" "$(awk -F= '/MANUFACTURER/ {print $NF}' <(echo "$battery_data") | sed 's/^ //')"
-    printf "   %-15s%s\n" "Model name:" "$(awk -F= '/MODEL/ {print $NF}' <(echo "$battery_data"))"
+    printf "   %-15s%s\n" "Manufacturer:" "$(awk -F= '/MANUFACTURER/ {print $NF}' <<< "$battery_data" | sed 's/^ //')"
+    printf "   %-15s%s\n" "Model name:" "$(awk -F= '/MODEL/ {print $NF}' <<< "$battery_data")"
     printf "   %-15s%s\n" "Serial number:" "$battery_serial"
-    printf "   %-15s%s\n" "Technology:" "$(awk -F= '/TECHNOLOGY/ {print $NF}' <(echo "$battery_data"))"
-  else
+    printf "   %-15s%s\n" "Technology:" "$(awk -F= '/TECHNOLOGY/ {print $NF}' <<< "$battery_data")"
+else
     printf "No battery detected\n"
   fi
 }
 
 main() {
   local -r script="${0##*/}"
-  local -r version="5.2.26069"
+  local -r version="5.3.26067"
   local -r lhost="${HOSTNAME:-$(hostname)}"
   local -r info_file="$HOME/$lhost.info"
 
@@ -317,7 +318,7 @@ main() {
 	  wired_info
 	  wireless_info
     if [[ -b /dev/sda ]]; then
-      hd_data=$(mktemp -q) || die "Failed to create temporary file." 1
+      hd_data=$(mktemp -q) || die "Failed to create temporary file." "$E_TEMP_DIR"
       ssd_hd_info
     fi
     [[ -c /dev/nvme0 ]] && nvme_info
