system-status: updated local variables & return codes; added show_temperatures() to combine temperature functions

diff --git a/system-status b/system-status
--- a/system-status
+++ b/system-status
@@ -7,27 +7,25 @@
 # Author       : Copyright (C) 2018,Richard Romig, LudditeGeek@Mosfanet
 # Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
 # Created      : 17 Nov 2018
-# Updated      : 26 Jun 2026
-# Comments     : Inspired by Joe Collins and Luke Smith
+# Updated:     : 04 Aug 2026
+# Versin       : 7.0.26216
+# Comments     : Inspired by Joe Collins' and Luke Smith's YouTube videos
+# TODO (Rick)  :
 # License      : GNU General Public License, version 2.0
 # License URL  : https://github.com/RickRomig/scripts/blob/main/LICENSE
-##########################################################################
-# This program is free software; you can redistribute it and/or modify
-# it under the terms of the GNU General Public License as published by
-# the Free Software Foundation; either version 2 of the License, or
-# (at your option) any later version.
+###############################################################################
+# This program is free software; you can redistribute it and/or modify it under
+# the terms of the GNU General Public License as published by the Free Software
+# Foundation; either version 2 of the License, or (at your option) any later
+# version.
 #
-# This program is distributed in the hope that it will be useful,
-# but WITHOUT ANY WARRANTY; without even the implied warranty of
-# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
-# GNU General Public License for more details.
-#####################################################################
+# This program is distributed in the hope that it will be useful, but WITHOUT
+# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
+# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
+###############################################################################
 
-## source function library ##
-# shellcheck source=/home/rick/bin/functionlib
-source ~/bin/functionlib || { printf "\e[91mERROR:\e[0m Unable to source functionlib\n"; exit 1; }
-
-## Functions ##
+# shellcheck source=/home/rick/bin/functionlib.bash
+source ~/bin/functionlib.bash || { printf "\e[91mERROR:\e[0m Unable to source functionlib.bash\n"; exit 1; }
 
 check_drivetemp() {
   grep -qw drivetemp < <(sensors) || sudo modprobe drivetemp
@@ -35,6 +33,7 @@ check_drivetemp() {
   printf "drivetemp module - [OK]\n"
   sleep 1
   printf '\e[A\e[K'
+  return 0
 }
 
 check_dependencies() {
@@ -42,12 +41,14 @@ check_dependencies() {
   check_packages "${packages[@]}"
   # Check drivetemp modules for SATA drives.
   [[ -b /dev/sda ]] && check_drivetemp
+  return 0
 }
 
 memory_usage() {
 	printf "\n%sMemory usage:%s %s\n" "$orange" "$normal" "$(awk '/^Mem:/ {print $3 " / " $2}' < <(/usr/bin/free -h) | sed 's/i//g')"
   printf "%sProcess%s\t\t%sPercentage%s\n" "$underline" "$normal" "$underline" "$normal"
 	head -n 5 < <(ps axch -o cmd:15,%mem --sort=-%mem)
+  return 0
 }
 
 cpu_usage() {
@@ -58,10 +59,11 @@ cpu_usage() {
 	printf "\n%sCPU usage: %s%s%%\n" "$orange" "$normal" "$cpu_use"
   printf "%sProcess%s\t\t%sPercentage%s\n" "$underline" "$normal" "$underline" "$normal"
   head -n 5 < <(ps axch -o cmd:15,%cpu --sort=-%cpu)
+  return 0
 }
 
 cpu_temperature(){
-  local sensor_json="$1"
+  local -r sensor_json="$1"
 	if grep -q 'k10temp-pci-00c3' <<< "$sensor_json"; then
 		printf "%-10s%2.1f\U2103 \n" "CPU:" "$(jq -r '."k10temp-pci-00c3"."temp1"."temp1_input"' <<< "$sensor_json")"
 	elif grep -q 'dell_smm-virtual-0' <<< "$sensor_json"; then
@@ -73,11 +75,12 @@ cpu_temperature(){
   else
     printf "%-10sNot available\n" "CPU:"
 	fi
+  return 0
 }
 
 gpu_temperature() {
   # Only machines 10, 12, and 22 display GPU temperature.
-  local sensor_json="$1"
+  local -r sensor_json="$1"
   if grep -q 'nouveau-pci-0100' <<< "$sensor_json"; then
     printf "%-10s%2.1f\U2103 \n" "GPU:" "$(jq -r '."nouveau-pci-0100"."temp1"."temp1_input"' <<< "$sensor_json")"
   elif grep -q 'pch_skylake-virtual-0' <<< "$sensor_json"; then
@@ -85,11 +88,12 @@ gpu_temperature() {
   else
     printf "%-10sNot available\n" "GPU:"
   fi
+  return 0
 }
 
 nvme_temperature() {
-	local drive drv_name sensor_json
-  sensor_json="$1"
+	local drive drv_name
+  local -r sensor_json="$1"
 	for drive in /dev/nvme0n[0-9]; do
 		drv_name=$(awk -F/ '{print $NF}' <<< "$drive")
 		if grep -q 'nvme-pci-0300' <<< "$sensor_json"; then
@@ -98,11 +102,12 @@ nvme_temperature() {
       printf "%-10sNot available\n" "$drv_name:"
 		fi
 	done
+  return 0
 }
 
 sata_temperature() {
-	local drive drv_name sensor_json
-  sensor_json="$1"
+	local drive drv_name
+  local -r sensor_json="$1"
 	for drive in /dev/sd[a-z]; do
 		drv_name=$(awk -F/ '{print $NF}' <<< "$drive")
 		if grep -q 'drivetemp-scsi-0-0' <<< "$sensor_json"; then
@@ -115,26 +120,39 @@ sata_temperature() {
       printf "%-10sNot available\n" "$drv_name:"
 		fi
 	done
+  return 0
+}
+
+show_temperatures() {
+  local sensor_json
+  sensor_json="$(sensors -j 2>/dev/null)"
+	printf "\n%sTemperatures:%s\n"  "$orange" "$normal"
+  cpu_temperature "$sensor_json"
+  gpu_temperature "$sensor_json"
+  [[ -c /dev/nvme0 ]] && nvme_temperature "$sensor_json"
+  [[ -b /dev/sda ]] && sata_temperature "$sensor_json"
 }
 
 disk_usage() {
 	printf "\n%sDisk usage:%s\n" "$orange" "$normal"
   sed -n '1p;/^\//p' < <(/usr/bin/df -hT -x fuse.portal)
+  return 0
 }
 
 show_header() {
-  local local_host="${HOSTNAME:-$(hostname)}"
+  local -r local_host="${HOSTNAME:-$(hostname)}"
   clearscreen
   printf "%s%sSystem Status%s\n" "$bold" "$lightyellow" "$normal"
   printf "%s%-16s%s\n" "$orange" "Computer name:" "$local_host"
   printf "%-16s%s\n" "Distribution:" "$(get_distribution)"
   printf "%-16s%s%s\n" "Kernel version:" "$(uname -sr)" "$normal"
+  return 0
 }
 
 show_footer() {
-  local last_boot up_time
   local -r script="${0##*/}"
-  local -r version="6.21.26177"
+  local -r version="7.0.26216"
+  local last_boot up_time
   last_boot=$(awk '{print $(NF-1),$NF}' < <(/usr/bin/who -b))
   up_time=$(cut -d' ' -f2- < <(/usr/bin/uptime -p))
   printf "\n%sUp since:%s %s (%s)\n" "$orange" "$normal" "$last_boot" "$up_time"
@@ -144,20 +162,12 @@ show_footer() {
 
 main() {
   check_dependencies
-  local sensor_json
-  sensor_json="$(sensors -j 2>/dev/null)"
   show_header
   memory_usage
   cpu_usage
-	printf "\n%sTemperatures:%s\n"  "$orange" "$normal"
-  cpu_temperature "$sensor_json"
-  gpu_temperature "$sensor_json"
-  [[ -c /dev/nvme0 ]] && nvme_temperature "$sensor_json"
-  [[ -b /dev/sda ]] && sata_temperature "$sensor_json"
+  show_temperatures
   disk_usage
   show_footer
 }
-
-## Execution ##
 
 main "$@"
