upper2lower - changed red_error variable to uppercase.

diff --git a/upper2lower b/upper2lower
--- a/upper2lower
+++ b/upper2lower
@@ -7,7 +7,7 @@
 # Author       : Copyright © 2018, Richard Romig
 # Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
 # Created      : 2018
-# Updated      : 03 Oct 2024
+# Updated      : 31 Oct 2024
 # Comment      :
 # License      : GNU General Public License, version 2.0
 ##############################################################################
@@ -27,14 +27,14 @@ fi
 ## Global Variables ##
 
 script=$(basename "$0"); readonly script
-readonly version="3.3.24277"
+readonly version="3.3.24305"
 
 ## Functions ##
 
 help() {
   local errcode updated
 	errcode="${1:-2}"
-	updated="03 Oct 2024"
+	updated="31 Oct 2024"
 	cat << _HELP_
 ${orange}$script${normal} $version, Upated: $updated
 Renames filenames in the current directory to all lowercase.
@@ -82,7 +82,7 @@ lc_selected() {
 main() {
 	local file_name
 	if [[ $# -eq 0 ]]; then
-		printf "%s No argument passed.\n" "$red_error" >&2
+		printf "%s No argument passed.\n" "$RED_ERROR" >&2
 		help 1
 	elif [[ $# -eq 1 ]]; then
 		case "$1" in
