upper2lower - added main(); separate functions to convert one, all, or selected files.

diff --git a/upper2lower b/upper2lower
--- a/upper2lower
+++ b/upper2lower
@@ -7,7 +7,7 @@
 # Author       : Copyright © 2018, Richard Romig
 # Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
 # Created      : 2018
-# Updated      : 28 Jun 2024
+# Updated      : 03 Oct 2024
 # Comment      :
 # License      : GNU General Public License, version 2.0
 ##############################################################################
@@ -24,28 +24,29 @@ else
   exit 1
 fi
 
-## Variables ##
+## Global Variables ##
 
-_script=$(basename "$0"); readonly _script
-readonly _version="3.2.24180"
-readonly _updated="28 Jun 2024"
+script=$(basename "$0"); readonly script
+readonly version="3.3.24277"
 
 ## Functions ##
 
 help() {
-  local errcode="${1:-2}"
-  cat << END_HELP
-${orange}$_script${normal} $_version, Upated: $_updated
+  local errcode updated
+	errcode="${1:-2}"
+	updated="03 Oct 2024"
+	cat << _HELP_
+${orange}$script${normal} $version, Upated: $updated
 Renames filenames in the current directory to all lowercase.
 
-${green}Usage:${normal} $_script [option] [filename1] [filename2] ...
+${green}Usage:${normal} $script [option] [filename1] [filename2] ...
 ${orange}Options:${normal}
   --all    change all files in the current directory.
   --help   display this help message.
 One or more filenames may be entered to be renamed.
-$_script Filename	# Renames filename to lowercase
-$_script Filename1 Filename2	# Renames Filename1 and Filename2 to lowercase
-END_HELP
+$script Filename	# Renames filename to lowercase
+$script Filename1 Filename2	# Renames Filename1 and Filename2 to lowercase
+_HELP_
   exit "$errcode"
 }
 
@@ -54,38 +55,58 @@ upper_to_lower() {
 	if [[ -f "$filename" ]]; then
 		rename -v 'y/A-Z/a-z/' "$filename"
 	else
-		printf "%s %s not found.\n" "$red_error" "$filename" >&2
+		printf "%s %s not found.\n" "$RED_ERROR" "$filename" >&2
 	fi
+}
+
+lc_all() {
+	printf "Renaming all files in the current directory to lowercase.\n"
+	find . -maxdepth 1 -type f -exec rename -v 'y/A-Z/a-z/' {} + | sed 's/\.\///g'
+}
+
+lc_one() {
+	local file_name
+	file_name="$1"
+	printf "Renaming %s to lowercase.\n" "$file_name"
+	upper_to_lower "$file_name"
+}
+
+lc_selected() {
+	printf "Renaming selected files to lowercase.\n"
+	for file_name in "$@"
+	do
+		upper_to_lower "$file_name"
+	done
+}
+
+main() {
+	local file_name
+	if [[ $# -eq 0 ]]; then
+		printf "%s No argument passed.\n" "$red_error" >&2
+		help 1
+	elif [[ $# -eq 1 ]]; then
+		case "$1" in
+			-a|--all )
+				lc_all
+			;;
+			-h|--help )
+				help 0
+			;;
+			-* )
+				printf "%s Invalid argument, %s\n" "$RED_ERROR" "$1" >&2
+				help 1
+			;;
+			* )
+				file_name="$1"
+				lc_one "$file_name"
+		esac
+	else
+		lc_selected "$@"
+	fi
+	over_line "$script v$version"
+	exit
 }
 
 ## Execution ##
 
-if [[ $# -eq 0 ]]; then
-	printf "%s No argument passed.\n" "$red_error" >&2
-  help 1
-elif [[ $# -eq 1 ]]; then
-	case "$1" in
-		"--all" )
-			printf "Renaming all files in the current directory to lowercase.\n"
-			find . -maxdepth 1 -type f -exec rename -v 'y/A-Z/a-z/' {} + | sed 's/\.\///g'
-		;;
-		"--help" )
-			help 0
-		;;
-		--* )
-			printf "%s Invalid argument, %s\n" "$red_error"  "$1" >&2
-			help 1
-		;;
-		* )
-			file_name="$1"
-			printf "Renaming %s to lowercase.\n" "$file_name"
-			upper_to_lower "$file_name"
-	esac
-else
-	printf "Renaming selected files to lowercase.\n"
-	for file_name in "$@"; do
-		upper_to_lower "$file_name"
-	done
-fi
-
-leave "$_script v$_version"
+main "$@"
