verify-iso: verify_iso() checks for ISO directory or link; select_directory/select_iso() removed checks for directory

diff --git a/verify-iso b/verify-iso
--- a/verify-iso
+++ b/verify-iso
@@ -34,7 +34,7 @@ source ~/bin/functionlib || { printf "\e[91mERROR:\e[0m Unable to source functio
 ## Global Variables ##
 
 readonly script="${0##*/}"
-readonly version="12.5.26152"
+readonly version="13.0.26152"
 FMENU="fzf --header=$script \
            --layout=reverse \
            --exact \
@@ -72,17 +72,14 @@ _HELP_
 
 select_directory() {
 	local dist_d selected_dir
-  local local_host="${HOSTNAME:-$(hostname)}"
-	local iso_dir=~/Downloads/ISO
-	# [[ "$local_host" == "dell-9020" ]] && iso_dir=/data/ISO
+	local iso_dir="$1"
 	local iso_dirs=()
 	for dist_d in $iso_dir; do
-		case "$local_host" in
-			dell-9020 )
-				[[ -d "$dist_d" ]] && iso_dirs+=("$(sort -d < <(find -L "$dist_d" -maxdepth 2 -type d -print))") ;;
-			* )
-				[[ -d "$dist_d" ]] && iso_dirs+=("$(sort -d < <(find "$dist_d" -maxdepth 2 -type d -print))")
-		esac
+		if [[ -L "$iso_dir" ]]; then
+			iso_dirs+=("$(sort -d < <(find -L "$dist_d" -maxdepth 2 -type d -print))")
+		else
+			iso_dirs+=("$(sort -d < <(find "$dist_d" -maxdepth 2 -type d -print))")
+		fi
 	done
 	selected_dir=$($FMENU "Select distribution directory: " < <(printf "%s\n" "${iso_dirs[@]}"))
 	printf "%s" "$selected_dir"
@@ -93,7 +90,7 @@ select_iso() {
 	iso_d="$1"
 	local iso_files=()
 	for iso_files in $iso_d; do
-		[[ -d "$iso_d" ]] && iso_files+=("$(sort -d < <(find "$iso_d" -type f -iname "*.iso" -printf "%f\n"))")
+		iso_files+=("$(sort -d < <(find "$iso_d" -type f -name "*.iso" -printf "%f\n"))")
 	done
 	selected_iso=$($FMENU "Select ISO file: " < <(printf "%s\n" "${iso_files[@]}"))
 	printf "%s" "$selected_iso"
@@ -162,8 +159,10 @@ check_extension() {
 }
 
 verify_iso() {
-	local checksum isofile iso_dir
-	iso_dir=$(select_directory)
+	local checksum isofile iso_dir isoDir
+	isoDir=~/Downloads/ISO
+	[[ -d "$isoDir" ]] || { printf "%s ISO directory not found.\n" "$RED_ERROR"; "$E_FILENOTFOUND"; return; }
+	iso_dir=$(select_directory "$isoDir")
 	isofile=$(select_iso "$iso_dir")
 	[[ "$isofile" ]] || { printf "%s No ISO file selected.\n" "$RED_ERROR" >&2; EC="$E_MISSING_ARG"; return; }
 	checksum=$(select_checksum "$iso_dir")
@@ -176,7 +175,8 @@ verify_iso() {
 		printf "%s Invalid checksum extension.\nExtension must be one of the following: .md5 .sha1 .sha256 .sha512\n" "$RED_ERROR" >&2
 		EC="$E_INVALID_ARG"
 		return
-	elif ! check_checksum "$iso_dir/$checksum"; then
+	fi
+	if ! check_checksum "$iso_dir/$checksum"; then
 		printf "%s Too many lines in checksum file.\nReduce the file to a single line.\n" "$RED_ERROR" >&2
 		EC="$E_FILE_ERROR"
 		return
