verify-iso - updated local variables in functions; updated help()

diff --git a/verify-iso b/verify-iso
--- a/verify-iso
+++ b/verify-iso
@@ -6,7 +6,7 @@
 # Arguments    : see help function
 # Author       : Copyright (C) 2022, Richard B. Romig, LudditeGeek@Mosfanet
 # Crated       : 09 Apr 2022
-# Updated      : 23 May 2024
+# Updated      : 27 Jun 2024
 # Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
 # Comments     : Each ISO file must have its own checksum file.
 #              : Checksum file must be one line only for ISO being checked.
@@ -31,8 +31,8 @@ fi
 ## Global Variables ##
 
 _script=$(basename "$0"); readonly _script
-readonly _version="9.0.24144"
-readonly _updated="23 May 2024"
+readonly _version="9.1.24179"
+readonly _updated="27 Jun 2024"
 readonly iso_d="$HOME/Downloads/ISO/"
 
 ## Functions ##
@@ -40,31 +40,39 @@ readonly iso_d="$HOME/Downloads/ISO/"
 help() {
 	local errcode="${1:-2}"
 	cat << END_HELP
-${green}Usage:${normal} $_script [OPTION]
-${orange}OPTIONS:${normal}
-	-h	Display help
-	-v	Verify ISO and checkfile
-Checksum files must be a single line specifically for the ISO file you wish to check,
-and must have a file extension of .md5, .sha256. or .sha512.
-For ease of identifying them, the basename should match the basename name of the ISO.
+${orange}$_script${normal} $_version, Upated: $_updated
+Verifies SHA256/SHA512/MD5 checksums with ISO files.
 
-$_script $_version (Updated $_updated)
+${green}Usage:${normal} $_script [OPTION]
+
+${orange}Available options:${normal}
+  -h  Display help
+  -v  Verify ISO with checksum
+
+  * Checksum files must be a single line specifically for the ISO file you wish to check.
+  * Checksum files must have a file extension of .md5, .sha256. or .sha512.
+  * The basename of the checksum file should match the basename name of the ISO.
+
 END_HELP
   exit "$errcode"
 }
 
 select_iso() {
+	local isofile
 	isofile=$(find "$iso_d" -maxdepth 3 -type f -iname "*.iso" -print | sort -d | fzf --height 40% --reverse --prompt "Select the ISO file to check: ")
+	echo "$isofile"
 }
 
 select_checksum() {
+	local checksum
 	checksum=$(find "$iso_d" -maxdepth 3 -type f -name "*.md5" -or -name "*.sha*" | sed 's/\.\///' | sort -d | fzf --height 40% --reverse --prompt "Select the checksum file: ")
+	echo "$checksum"
 }
 
 check_sha256() {
-	local iso_sha src_sha
-	local iso_file="$1"
-	local sha_file="$2"
+	local iso_sha src_sha iso_file sha_file
+	iso_file="$1"
+	sha_file="$2"
   dots "."
 	iso_sha=$(/usr/bin/sha256sum "$iso_file" | awk '{print $1}')
 	src_sha=$(awk '{print $1}' "$sha_file")
@@ -76,9 +84,9 @@ check_sha256() {
 }
 
 check_sha512() {
-	local iso_sha src_sha
-  local iso_file="$1"
-	local sha_file="$2"
+	local iso_sha src_sha iso_file sha_file
+  iso_file="$1"
+	sha_file="$2"
   dots "."
 	iso_sha=$(/usr/bin/sha512sum "$iso_file" | awk '{print $1}')
 	src_sha=$(awk '{print $1}' "$sha_file")
@@ -90,9 +98,9 @@ check_sha512() {
 }
 
 check_md5() {
-	local iso_md5 src_md5
-  local iso_file="$1"
-  local md5_file="$2"
+	local iso_md5 src_md5 iso_file sha_file
+  iso_file="$1"
+  md5_file="$2"
   dots "."
   iso_md5=$(/usr/bin/md5sum "$iso_file" | awk '{print $1}')
   src_md5=$(awk '{print $1}' "$md5_file")
@@ -114,16 +122,16 @@ status_msg() {
 }
 
 check_checksum() {
-	local lines
-  local file="$1"
+	local lines file
+  file="$1"
   lines=$(wc -l "$file" | cut -d' ' -f1)
   [[ "$lines" -eq 1 ]] && return "$TRUE" || return "$FALSE"
 }
 
 compare_checksums() {
-	local iso="$1"
-	local chk="$2"
-	local ext
+	local ext chk iso
+	iso="$1"
+	chk="$2"
 	ext="${checksum##*.}"
 	printf "Comparing checksums."
 	case "$ext" in
@@ -146,18 +154,21 @@ compare_checksums() {
 }
 
 verify() {
-	select_iso
-	select_checksum
+	isofile=$(select_iso)
+	checksum=$(select_checksum)
 	printf "\n%-18s %s\n" "Selected ISO:" "$(basename "$isofile")"
 	printf "%-18s %s\n\n" "Selected Checksum:" "$(basename "$checksum")"
 	check_checksum "$checksum" || diehard "Too many lines in checksum file." "Reduce file to a single line." "$_script $_version"
 	compare_checksums "$isofile" "$checksum"
 }
 
+show_title() {
+	box "$_script v$_version"
+	printf "Verifies SHA256/SHA512/MD5 checksums with ISO files.\n"
+}
+
 ## Execution ##
 
-box "$_script v$_version"
-printf "Verifies SHA256/SHA512/MD5 checksums with ISO files.\n"
 noOpt=1
 optstr=":hv"
 while getopts "$optstr" opt; do
@@ -166,11 +177,12 @@ while getopts "$optstr" opt; do
 			help 0
 		;;
 		v )
+			show_title
 			check_package fzf
 			verify
 		;;
 		? )
-			printf "%s Invalid option -%s\n" "$red_error" "$OPTARG" >&2
+			printf "%s Invalid option: -%s\n" "$red_error" "$OPTARG" >&2
 			help 2
 	esac
 	noOpt=0
