verify-iso - select_iso_directory prints selected directory. exit_msg() renamed to status_msg() and exit command removed. pushd & popd output redirected to /dev/null. popd failure will print error message but will not exit script.

diff --git a/verify-iso b/verify-iso
--- a/verify-iso
+++ b/verify-iso
@@ -6,8 +6,8 @@
 # Arguments    : see help function
 # Author       : Copyright (C) 2022, Richard B. Romig, 09 Apr 2022
 # Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
-# Comments     : Checksum file must be one line only for ISO being checked.
-#              : Each ISO file must have its own checksum file.
+# Comments     : Each ISO file must have its own checksum file.
+#              : Checksum file must be one line only for ISO being checked.
 #              : Checksum files must have one of the following extensions:
 #              : .md5, .sha256, or .sha512
 #              : Options for fuzzy finder (fzf) and zenity
@@ -31,13 +31,13 @@ fi
 ## Global Variables ##
 
 _script=$(basename "$0"); readonly _script
-readonly _version="0.8.0"
-readonly _updated="31 Jan 2024"
+readonly _version="0.1.0"
+readonly _updated="05 Feb 2024"
 
 ## Functions ##
 
 help() {
-	errcode="${1:-2}"
+	local errcode="${1:-2}"
 	cat << END_HELP
 ${green}Usage:${normal} $_script [OPTION]
 ${orange}OPTIONS:${normal}
@@ -71,25 +71,70 @@ select_iso_directory() {
 	)
 	select opt in "${options[@]}"; do
 		case "$REPLY" in
-			1 )	pushd "$iso_dir/Linux/$opt" || die "pushd failed!"; break ;;
-			2 )	pushd "$iso_dir/Linux/$opt" || die "pushd failed!"; break ;;
-			3 )	pushd "$iso_dir/Linux/$opt" || die "pushd failed!"; break ;;
-			4 )	pushd "$iso_dir/Linux/$opt" || die "pushd failed!"; break ;;
-			5 )	pushd "$iso_dir/Linux/$opt" || die "pushd failed!"; break ;;
-			6 )	pushd "$iso_dir/Linux/$opt" || die "pushd failed!"; break ;;
-			7 )	pushd "$iso_dir/Linux/$opt" || die "pushd failed!"; break ;;
-			8 ) pushd "$iso_dir/Linux/$opt" || die "pushd failed!"; break ;;
-			9 )	pushd "$iso_dir/Linux/$opt" || die "pushd failed!"; break ;;
-			11 ) pushd "$iso_dir/$opt" || die "pushd failed!"; break ;;
-			12 ) iso_dir="$PWD" || die "pushd failed!"; break ;;
+			1 )
+				pushd "$iso_dir/Linux/$opt" > /dev/null || die "pushd failed!"
+				printf "\n%-18s %s/Linux/%s\n" "ISO directory:" "$iso_dir" "$opt"
+				break
+			;;
+			2 )
+				pushd "$iso_dir/Linux/$opt" > /dev/null || die "pushd failed!"
+				printf "\n%-18s %s/Linux/%s\n" "ISO directory:" "$iso_dir" "$opt"
+				break
+			;;
+			3 )
+				pushd "$iso_dir/Linux/$opt" > /dev/null || die "pushd failed!"
+				printf "\n%-18s %s/Linux/%s\n" "ISO directory:" "$iso_dir" "$opt"
+				break
+			;;
+			4 )
+				pushd "$iso_dir/Linux/$opt" > /dev/null || die "pushd failed!"
+				printf "\n%-18s %s/Linux/%s\n" "ISO directory:" "$iso_dir" "$opt"
+				break
+			;;
+			5 )
+				pushd "$iso_dir/Linux/$opt" > /dev/null || die "pushd failed!"
+				printf "\n%-18s %s/Linux/%s\n" "ISO directory:" "$iso_dir" "$opt"
+				break
+			;;
+			6 )
+				pushd "$iso_dir/Linux/$opt" > /dev/null || die "pushd failed!"
+				printf "\n%-18s %s/Linux/%s\n" "ISO directory:" "$iso_dir" "$opt"
+				break
+			;;
+			7 )
+				pushd "$iso_dir/Linux/$opt" > /dev/null || die "pushd failed!"
+				printf "\n%-18s %s/Linux/%s\n" "ISO directory:" "$iso_dir" "$opt"
+				break
+			;;
+			8 )
+				pushd "$iso_dir/Linux/$opt" > /dev/null || die "pushd failed!"
+				printf "\n%-18s %s/Linux/%s\n" "ISO directory:" "$iso_dir" "$opt"
+				break
+			;;
+			9 )
+				pushd "$iso_dir/Linux/$opt" > /dev/null || die "pushd failed!"
+				printf "\n%-18s %s/Linux/%s\n" "ISO directory:" "$iso_dir" "$opt"
+				break
+			;;
+			11 )
+				pushd "$iso_dir/Linux/$opt" > /dev/null || die "pushd failed!"
+				printf "\n%-18s %s/Linux/%s\n" "ISO directory:" "$iso_dir" "$opt"
+				break
+			;;
+			12 )
+				pushd "$iso_dir/Linux/$opt" > /dev/null || die "pushd failed!"
+				printf "\n%-18s %s/%s\n" "ISO directory:" "$iso_dir" "$opt"
+				break
+			;;
 			* ) printf "Invalid option. Choose 1 - %d\n" "${#options[@]}"
 		esac
 	done
-	printf "\n"
 }
 
 select_iso() {
 	local num_iso
+	local opt
+	local options
 	num_iso=$(find ./ -maxdepth 1 -type f -name "*.iso" | wc -l)
 	[[ "$num_iso" = 0 ]] && diehard "No ISO files found." "Change to a directory containing the ISO file to be checked." "$_script $_version ($_updated)"
 
@@ -114,7 +159,7 @@ fzf_select_iso() {
 	local num_iso
 	num_iso=$(find ./ -maxdepth 1 -type f -name "*.iso" | wc -l)
 	[[ "$num_iso" = 0 ]] && diehard "No ISO files found." "Change to a directory containing the ISO file to be checked." "$_script $_version ($_updated)"
-	isofile=$(find ./ -type f -name "*.iso" -print | sed 's/\.\///' | fzf --prompt "Select the ISO file to check: ")
+	isofile=$(find ./ -type f -name "*.iso" -print | sed 's/\.\///' | fzf --height 40% --reverse --prompt "Select the ISO file to check: ")
 }
 
 zen_select_iso() {
@@ -128,7 +173,9 @@ zen_select_iso() {
 }
 
 select_checksum() {
-	local num_iso
+	local num_files
+	local opt
+	local options
 	num_files=$(find ./ -maxdepth 1 -type f -name "*.md5" -or -name "*.sha*" | wc -l)
 	[[ "$num_files" = 0 ]] && diehard "No checksum files found." "$_script $_version ($_updated)"
 
@@ -150,9 +197,10 @@ select_checksum() {
 }
 
 fzf_select_checksum() {
+	local num_files
 	num_files=$(find ./ -maxdepth 1 -type f -name "*.md5" -or -name "*.sha*" | wc -l)
 	[[ "$num_files" = 0 ]] && diehard "No checksum files found." "$_script $_version ($_updated)"
-	checksum=$(find ./ -maxdepth 1 -type f -name "*.md5" -or -name "*.sha*" | sed 's/\.\///' | fzf --prompt "Select the checksum file: ")
+	checksum=$(find ./ -maxdepth 1 -type f -name "*.md5" -or -name "*.sha*" | sed 's/\.\///' | fzf --height 40% --reverse --prompt "Select the checksum file: ")
 }
 
 zen_select_checksum() {
@@ -204,20 +252,20 @@ check_md5() {
   [[ "$iso_md5" == "$src_md5" ]] && return "$TRUE" || return "$FALSE"
 }
 
-exit_msg() {
-  local errcode="${1:-0}"
-  if [[ "$errcode" -eq 0 ]]; then
+status_msg() {
+  local status="${1:-0}"
+  if [[ "$status" -eq 0 ]]; then
 		printf "%sThe checksums match.%s\n" "$green" "$normal"
   else
 		printf "%sThe checksums do not match.%s\n" "$lightred" "$normal"
 		printf "Verify checksum with the ISO download site.\n"
   fi
   printf "\n%s v%s (%s)\n" "$_script" "$_version" "$_updated"
-  exit "$errcode"
 }
 
 check_checksum() {
   local file="$1"
+	local lines
   lines=$(wc -l "$file" | cut -d' ' -f1)
   [[ "$lines" -eq 1 ]] && return "$TRUE" || return "$FALSE"
 }
@@ -229,15 +277,15 @@ compare_checksums() {
 	case "$ext" in
 	  "md5" )
 	    check_md5 "$isofile" "$checksum"
-	    exit_msg "$?"
+	    status_msg "$?"
 	  ;;
 	  "sha256" )
 	    check_sha256 "$isofile" "$checksum"
-	    exit_msg "$?"
+	    status_msg "$?"
 	  ;;
 	  "sha512" )
 	    check_sha512 "$isofile" "$checksum"
-	    exit_msg "$?"
+	    status_msg "$?"
 	  ;;
 	  * )
 	    printf "\n"
@@ -292,5 +340,5 @@ printf "%-18s %s\n" "Selected ISO:" "$isofile"
 printf "%-18s %s\n\n" "Selected Checksum:" "$checksum"
 check_checksum "$checksum" || diehard "Too many lines in checksum file." "Reduce file to a single line." "$_script $_version ($_updated)"
 compare_checksums
-popd || die "popd failed!" 1
-leave "$_script $_version (Updated $_updated)"
+popd > /dev/null || printf "%s popd failed!" "$red_error" >&2
+exit
