weather 0.6.0 - Created a function to display message when curl times out when trying to connect.

diff --git a/weather b/weather
--- a/weather
+++ b/weather
@@ -27,8 +27,8 @@ fi
 ## Variables ##
 
 _script=$(basename "$0"); readonly _script
-readonly _version="0.5.11"
-readonly _updated="26 Mar 2023"
+readonly _version="0.6.0"
+readonly _updated="16 Sep 2023"
 
 ## Functions ##
 
@@ -39,6 +39,13 @@ check_dependencies() {
 
 cleanup() {
   [[ -f "$tmp_file" ]] && rm "$tmp_file"
+}
+
+timeout_exit() {
+  local wx_loc; wx_loc="$(echo "$1" | sed 's/+/ /g')"
+  printf "Current weather data for %s is not available.\n" "$wx_loc"
+  printf "Try again later.\n\n"
+  exit 1
 }
 
 show_help() {
@@ -110,11 +117,8 @@ current_wx() {
     printf "%15s: %s\n" "Sunrise" "$sunrise"
     printf "%15s: %s\n\n" "Sunset" "$sunset"
   else
-    printf "Current weather data for %s is not available.\n" "$wx_loc" | sed 's/+/ /g'
-    printf "Try again later.\n\n"
-    exit 1
+    timeout_exit "$wx_loc"
   fi
-  anykey
 }
 
 wx_forecast() {
@@ -123,15 +127,11 @@ wx_forecast() {
   clear
   box "$_script v$_version ($_updated)"
   printf "\n"
-  # curl -s "$url/$wx_loc" | sed '1 s/:.*//;/Follow/d'
   if curl -so "$tmp_file" "$url/$wx_loc"; then
     sed '1 s/:.*//;/Follow/d' "$tmp_file"
   else 
-    printf "Weather forecast for %s is not available.\n" "$wx_loc" | sed 's/+/ /g'
-    printf "Try again later.\n\n"
-    exit 1
+    timeout_exit "$wx_loc"
   fi
-  anykey
 }
 
 temp_color() {
@@ -211,11 +211,26 @@ while true; do
   PS3="Choice: "
   select opt in "Current conditions" "3-day forecast" "Usage/Help" "Quit"; do
     case $REPLY in
-      1 ) current_wx "$(echo $location | sed 's/ /+/g')"; break ;;
-      2 ) wx_forecast "$(echo $location | sed 's/ /+/g')"; break ;;
-      3 ) show_help; anykey; break ;;
-      4 ) leave "" ;;
-      * ) printf "%s Invalid choice. Choose 1, 2, 3, or 4\n" "$red_error" >&2
+      1 )
+        current_wx "$(echo "$location" | sed 's/ /+/g')"
+        anykey
+        break
+      ;;
+      2 )
+        wx_forecast "$(echo "$location" | sed 's/ /+/g')"
+        anykey
+        break
+      ;;
+      3 )
+        show_help
+        anykey
+        break
+      ;;
+      4 )
+        leave ""
+      ;;
+      * )
+        printf "%s Invalid choice. Choose 1, 2, 3, or 4\n" "$red_error" >&2
     esac
   done
 done
