weather: added GPL2 notice and licensce url.

diff --git a/weather b/weather
--- a/weather
+++ b/weather
@@ -7,10 +7,11 @@
 # Author       : Copyright (C) 2021, Richard B. Romig, LudditeGeek@Mosfnet
 # Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
 # Created      : 14 Jul 2021
-# Updated      : 04 Jul 2025
+# Updated      : 14 Jul 2025
 # Comments     : Based on a script by Kris Occhipinti https://filmsbykris.com
 #              : 3-day forecast is ASCII text and does not scale.
 # License      : GNU General Public License, version 2.0
+# License URL  : https://github.com/RickRomig/scripts/blob/main/LICENSE
 ##########################################################################
 
 ## Shellcheck Directives ##
@@ -30,9 +31,44 @@ set -eu
 ## Global Variables ##
 
 readonly script="${0##*/}"
-readonly version="6.15.25185"
+readonly version="6.16.25195"
 
 ## Functions ##
+
+help() {
+  local updated="14 Jul 2025"
+	cat << _HELP_
+${orange}$script${normal} $version, Upated: $updated
+Displays current weather and 3-day forecast for a location.
+
+${green}Usage:${normal} $script [location]
+
+${orange}Examples:${normal}
+$script  # No argument uses default location
+$script Cincinnati
+$script New+York
+$script "Los Angeles"
+
+* Locations with spaces must have a '+' in place of the space or be enclosed in double quotes.
+* A US state can be indicated with a comma after the city name.
+  Kettering,OH or Kettering, OH
+* If no location is passed, the default location will be used.
+* 3-digit airport codes can be used as a location (LAX, ATL, DAY).
+* Menu options include current conditions, 3-day forecast, change locations, and help.
+* For help: $script -h or $script --help or Choice 4 in the menu.
+
+_HELP_
+}
+
+show_notice() {
+  local script_dir
+  script_dir=$(dirname "$(readlink -f "${0}")")
+	printf "%s\n" "$script"
+	printf "Displays current weather and 3-day forecast for a location.\n"
+	printf "Copyright (C) 2021, Richard B. Romig\n"
+	printf "Email: rick.romig@gmail.com\n\n"
+	cat "$script_dir/files/gpl_notice.txt"
+}
 
 check_dependencies() {
   local packages=( curl jq )
@@ -56,31 +92,6 @@ is_url_accessible() {
   url="$1"
   result=$(curl --head --connect-timeout 8 --max-time 14 --silent --output /dev/null --write-out '%{http_code}' "$url")
   [[ "$result" -eq 200 ]] && return "$TRUE" || return "$FALSE"
-}
-
-help() {
-  local updated="04 Jul 2025"
-	cat << _HELP_
-${orange}$script${normal} $version, Upated: $updated
-Displays current weather and 3-day forecast for a location.
-
-${green}Usage:${normal} $script [location]
-
-${orange}Examples:${normal}
-$script  # No argument uses default location
-$script Cincinnati
-$script New+York
-$script "Los Angeles"
-
-* Locations with spaces must have a '+' in place of the space or be enclosed in double quotes.
-* A US state can be indicated with a comma after the city name.
-  Kettering,OH or Kettering, OH
-* If no location is passed, the default location will be used.
-* 3-digit airport codes can be used as a location (LAX, ATL, DAY).
-* Menu options include current conditions, 3-day forecast, change locations, and help.
-* For help: $script -h or $script --help or Choice 4 in the menu.
-
-_HELP_
 }
 
 wx_forecast() {
@@ -242,6 +253,7 @@ menu() {
       "3-day forecast"
       "Change location"
       "Usage/Help"
+      "GPL 2 Notice"
       "Quit"
     )
     PS3="Choice: "
@@ -270,11 +282,15 @@ menu() {
           break
           ;;
         5 )
+          show_notice
+          break
+          ;;
+        6 )
           printf "%sMOTD:%s " "$darkgray" "$normal"
           leave ""
           ;;
         * )
-          printf "%s Invalid choice. Choose 1, 2, 3, 4, or 5\n" "$RED_ERROR" >&2
+          printf "%s Invalid choice. Choose 1, 2, 3, 4, 5 or 6\n" "$RED_ERROR" >&2
       esac
     done
   done
