weather 0.5.9 - in wx_forecast, flipped then and else instructions, removed anykey from show_help, added to menu choice 3. Does not clear screen on exit.

diff --git a/weather b/weather
--- a/weather
+++ b/weather
@@ -20,7 +20,7 @@
 if [[ -x "$HOME/bin/functionlib" ]]; then
   source "$HOME/bin/functionlib"
 else
-  echo -e "\e[91mERROR:\e[0m functionlib not found!" >&2
+  printf "\e[91mERROR:\e[0m functionlib not found!\n" >&2
   exit 1
 fi
 
@@ -52,7 +52,6 @@ Example 3: $_script "Los Angeles"
 * If no location is passed, the default location will be used.
 For help: $_script -h or $_script --help, or Choice 3 in the menu.
 END_HELP
-  anykey
 }
 
 current_wx() {
@@ -125,13 +124,13 @@ wx_forecast() {
   box "$_script v$_version ($_updated)"
   printf "\n"
   # curl -s "$url/$wx_loc" | sed '1 s/:.*//;/Follow/d'
-  if ! curl -so "$tmp_file" "$url/$wx_loc"; then
-    printf "Weather forecast for %s is not available.\n\n" "$wx_loc" | sed 's/+/ /g'
-    exit 1
-  else 
+  if curl -so "$tmp_file" "$url/$wx_loc"; then
     sed '1 s/:.*//;/Follow/d' "$tmp_file"
+  else 
+    printf "Weather forecast for %s is not available.\n" "$wx_loc" | sed 's/+/ /g'
+    printf "Try again later.\n\n"
+    exit 1
   fi
-  
   anykey
 }
 
@@ -214,8 +213,8 @@ while true; do
     case $REPLY in
       1 ) current_wx "$(echo $location | sed 's/ /+/g')"; break ;;
       2 ) wx_forecast "$(echo $location | sed 's/ /+/g')"; break ;;
-      3 ) show_help; break ;;
-      4 ) clear; exit ;;
+      3 ) show_help; anykey; break ;;
+      4 ) exit ;;
       * ) printf "%s Invalid choice. Choose 1, 2, 3, or 4\n" "$red_error" >&2
     esac
   done
