write-iso: main() - replaced getopts with case statement for help and dryrun options

diff --git a/write-iso b/write-iso
--- a/write-iso
+++ b/write-iso
@@ -1,17 +1,16 @@
 #!/usr/bin/env bash
 ##########################################################################
 # Script Name  : write-iso
-# Description  : Copies an ISO file to a USB drive using dd
+# Description  : Writes an ISO image to a USB drive using dd
 # Dependencies : fzf
 # Arguments    : see help function
 # Author       : Copyright (C) 2023, Richard B. Romig, LudditeGeek@Mosfanet
 # Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
 # Created      : 18 Feb 2023
-# Updated      : 09 Aug 2026
-# Version      : 14.0.26221
+# Updated      : 10 Aug 2026
+# Version      : 14.1.26222
 # Comments     : Testing indicates USB drive needs to be mounted.
-#              : Works with fuzzy finder (fzf).
-#              : To test without writing to USB drive, use the -d option to enable a dry run.
+#              : To test without writing to USB drive, dnter -d or --dryrun option to enable a dry run.
 #              : After a dryrun, USB drive will remain mounted.
 # TODO (Rick)  :
 # License      : GNU General Public License, version 2.0
@@ -49,27 +48,25 @@ help() {
 	local -r script="$1"
 	local -r version="$2"
 	local -ri errcode="${3:-1}"
-	local -r updated="09 Aug 2026"
+	local -r updated="10 Aug 2026"
 	cat << _HELP_
 ${orange}$script${normal} $version, Upated: $updated
-Writes ISO to a USB drive
+Writes an ISO image to a USB drive
 
-${green}Usage:${normal} $script [-dw] [-h] [-w]
+${green}Usage:${normal} $script [OPTION]
 ${orange}Available options:${normal}
-  -d  Enable Dry Run simulation (-dw for a dry run)
-  -h  Show this help message and exit
-  -w  Write ISO to USB device (-dw for a dry run)
-
+  -d | --dryrun  Enable Dry Run simulation
+  -h | --help    Show this help message and exit
 _HELP_
   exit "$errcode"
 }
 
 select_directory() {
-	local -r iso_dir="$1"
+	local -r isoDir="$1"
 	local dist_d selected_dir
 	local iso_dirs=()
-	for dist_d in $iso_dir; do
-		if [[ -L "$iso_dir" ]]; then
+	for dist_d in $isoDir; do
+		if [[ -L "$isoDir" ]]; then
 			iso_dirs+=("$(sort -d < <(find -L "$dist_d" -maxdepth 2 -type d -print))")
 		else
 			iso_dirs+=("$(sort -d < <(find "$dist_d" -maxdepth 2 -type d -print))")
@@ -122,7 +119,7 @@ unmount_usb() {
 
 list_usb_contents() {
 	local -r usbpart="$1"
-	local drvlabel # usbdevice
+	local drvlabel
 	drvlabel=$(awk -v pat="$usbpart" -F/ '$0 ~ pat {print $NF}' < <(lsblk))
   printf "\nContents of /dev/%s:\n" "$usbpart"
 	printf "Disk label: %s\n" "$drvlabel"
@@ -134,12 +131,14 @@ simulate_dd() {
 	local -r iso="$1"
 	local -r usb="$2"
 	local -r mount_name="$3"
+	printf "\n%sPerforming a dryrun simulation.\n" "$orange" "$normal"
+	printf "The ISO will NOT be written to USB drive.%s\n" "$normal"
   printf "\nWriting %s to /dev/%s (SIMULATED) ..." "${iso##*/}" "$usb"
   dots "." &
 	DOTS_PID="$!"
   sleep 15
   kill_dots
-  printf "%s written to /dev/%s (SIMULATED)\n"  "${iso##*/}" "$usb"
+  printf "%s written to /dev/%s (SIMULATED)\n" "${iso##*/}" "$usb"
 	return 0
 }
 
@@ -209,42 +208,21 @@ write_iso() {
 
 main() {
 	local -r script="${0##*/}"
-	local -r version="14.0.26221"
+	local -r version="14.1.26222"
 	local -i exit_code=0
 	local -r isoDir=~/Downloads/ISO
-  local opt OPTARG OPTIND
-	local -i noOpt=1
-	local -r optstr=":dhw"
-	while getopts "$optstr" opt; do
-		case "$opt" in
-			d )
-				DRYRUN="$TRUE"
-				printf "%sPerforming a dryrun simulation.\n" "$orange" "$normal"
-				printf "The ISO will NOT be written to USB drive.%s\n\n" "$normal"
-				;;
-			h )
-				help "$script" "$version" 0
-				;;
-			w )
-				box "$script $version" "-"
-				printf "Writes ISO to a USB drive.\n\n"
-				check_package fzf
-				[[ $(grep 'usb' < <(lsblk -S -o TRAN)) = *usb* ]] || die "No USB drive connected." "$E_NOT_DETECTED"
-				[[ -d "$isoDir" ]] || die "Main ISO directory not found." "$E_FILENOTFOUND"
-				select_iso_usb "$isoDir"
-				;;
-			? )
-				printf "%s Invalid option: -%s\n" "$RED_ERROR" "$OPTARG" >&2
-				help "$script" "$version" "$E_INVALID_ARG"
-		esac
-		exit_code="$?"
-		noOpt=0
-	done
-	if (( noOpt == 1 )); then
-		printf "%s No argument passed.\n" "$RED_ERROR" >&2
-		help "$script" "$version" "$E_MISSING_ARG"
-	fi
-	shift "$(( OPTIND - 1 ))"
+	case "$1" in
+		-h | --help ) help "$script" "$version" 0 ;;
+		-d | --dryrun ) DRYRUN="$TRUE" ;;
+		* ) printf "Invalid option (ignored)\n"
+	esac
+	box "$script $version" "-"
+	printf "Writes an ISO image to a USB drive.\n\n"
+	check_package fzf
+	[[ $(grep 'usb' < <(lsblk -S -o TRAN)) = *usb* ]] || die "No USB drive connected." "$E_NOT_DETECTED"
+	[[ -d "$isoDir" ]] || die "Main ISO directory not found." "$E_FILENOTFOUND"
+	select_iso_usb "$isoDir"
+	exit_code="$?"
 	over_line "$script $version"
 	exit "$exit_code"
 }
