write-iso 0.2.2 - Replaced select loop with while-loop using read and case to choose whether to write the ISO file. User must type `yes` or `no`.

diff --git a/write-iso b/write-iso
--- a/write-iso
+++ b/write-iso
@@ -26,28 +26,28 @@ fi
 ## Variables ##
 
 _script=$(basename "$0"); readonly _script
-readonly _version="0.2.1"
-readonly _updated="14 Jun 2023"
+readonly _version="0.2.2"
+readonly _updated="15 Jun 2023"
 
 ## Functions ##
 
 write_dd() {
 	local usb="$1"
 	local iso="$2"
-	printf "Writing %s to %s...\n" "$iso_file" "$usb_drive"
+	printf "Writing %s to /dev/%s...\n" "$iso_file" "$usb_drive"
 	sudo dd if="$iso" of="/dev/$usb" status=progress bs=16M oflag=sync
 	printf "%s written to /dev/%s.\n" "$iso" "$usb"
 }
 
 ## Execution ##
 
-echo "$_script v$_version ($_updated)"
-echo "Writes ISO to a USB drive."
+printf "%s v%s (%s)\n" "$_script" "%_version" "$_updated"
+printf "Writes ISO to a USB drive.\n"
 [[ $(lsblk -S -o TRAN | grep 'usb') = *usb* ]] || die "No USB drive connected." 1
 
 # List ISO files and select
 printf "\nAvailable ISO files in %s:\n" "$PWD"
-ls ./*glob*.iso > /dev/null 2>&1 || diehard "No ISO files found." "Change to a directory containing ISO files."
+ls ./*.iso > /dev/null 2>&1 || diehard "No ISO files found." "Change to a directory containing ISO files."
 find ./ -maxdepth 1 -type f -name "*.iso" -print | sed 's/\.\///'
 read -rp "ISO file to write: " iso_file
 
@@ -56,26 +56,23 @@ printf "\nChoose a USB drive:\n"
 lsblk -o NAME,SIZE,TYPE,HOTPLUG | awk '/disk/ {print $1,$2,$4}'
 printf "A '1' in the 3rd column indicates the drive is a removable device (USB).\n"
 read -rp "USB device to write to (sdX): " usb_drive
-printf "You selected %s. If you continue, all data will be erased from this device.\n\n" "$usb_drive"
-echo -e "Select option 1 only if you are ${bold}${orange}ABSOLUTELY${normal} sure you want to proceed.\n"
+printf "You selected /dev/%s. If you continue, all data will be erased from this device.\n\n" "$usb_drive"
+echo -e "Answer 'yes' only if you are ${bold}${orange}ABSOLUTELY${normal} sure you want to proceed.\n"
 
-COLUMNS=40
-options=("Write ISO to USB" "Cancel and exit")
-PS3="Choice: "
-select opt in "${options[@]}"; do
-  case $REPLY in
-  	1 )
-    	user_in_sudo
-    	write_dd "$iso_file" "$usb_drive"
-    	break
+while true; do
+  read -rp "Write $iso_file to /dev/$usb_drive? " yn
+  case "$yn" in 
+    yes )
+      user_in_sudo
+      write_dd "$iso_file" "$usb_drive"
+      break
     ;;
-    2 )
+    no )
       printf "Operation canceled. No action taken.\n"
       break
     ;;
     * )
-      echo "${lightred}Invalid choice.${normal} Select 1 or 2."
+      printf "%s Invalid choice. Enter yes or no.\n" "$red_error" >&2
   esac
 done
-
 exit
