write-iso - Added popd to return to starting directory.

diff --git a/write-iso b/write-iso
--- a/write-iso
+++ b/write-iso
@@ -297,5 +297,5 @@ else
 	printf "Operation canceled. No action taken.\n"
 	fi
 fi
-
+popd || die "popd failed!" 1
 leave "$_script v$_version (Updated: $_updated)"
