write-iso - Separate functions for selecting ISO and USB drive with select menu, fuzzy finder (fzf), and zenity. Added getopts for options, including option for a dryrun where nothing is written to a drive. Added menu to select ISO diretory.

diff --git a/write-iso b/write-iso
--- a/write-iso
+++ b/write-iso
@@ -2,14 +2,14 @@
 ##########################################################################
 # Script Name  : write-iso
 # Description  : Copies an ISO file to a USB drive using dd
-# Dependencies : None
-# Arguments    : None
+# Dependencies : fzf (optional), zenity (optional)
+# Arguments    : see help function
 # Author       : Copyright (C) 2023, Richard B. Romig, 18 Feb 2023
 # Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
-# Comments     : Run script from a directory containing the ISO file.
-#              : Testing indicates USB drive should be mounted.
-#              : Works with fuzzy finder (fzf), if installed.
-#              : To test without writing to USB drive, comment call to write_dd and uncomment call to simulate_dd
+# Comments     : Testing indicates USB drive should be mounted.
+#              : Works with fuzzy finder (fzf) or zenity, if installed.
+#              : To test without writing to USB drive, use the -d option to enable a dryrun.
+#              : After a dryrun, USB drives will not be unmounted.
 # TODO (Rick)  :
 # License      : GNU General Public License, version 2.0
 ##########################################################################
@@ -30,57 +30,137 @@ fi
 ## Global Variables ##
 
 _script=$(basename "$0"); readonly _script
-readonly _version="0.4.2"
-readonly _updated="20 Jan 2024"
+readonly _version="0.5.0"
+readonly _updated="01 Feb 2024"
 user=$(whoami)
+dryrun="$FALSE"
 
 ## Functions ##
 
-select_iso() {
-	num_iso=$(find ./ -maxdepth 1 -type f -name "*.iso" | wc -l)
-	[[ "$num_iso" = 0 ]] && diehard "No ISO files found." "Change to a directory containing the ISO file to be checked." "$_script $_version ($_updated)"
-	
-	if exists fzf; then
-		isofile=$(find ./ -type f -name "*.iso" -print | sed 's/\.\///' | fzf --prompt "Select the ISO file to write: ")
-	else
-		PS3="Please select an ISO file: "
-		options=($(find ./ -maxdepth 1 -name "*.iso" | sed 's/\.\///'))
-		select opt in "${options[@]}" "Quit"; do
-			if (( REPLY == 1 + ${#options[@]} )); then
-				printf "No ISO file selected. Operation canceled. Exiting the script."
-				leave "$_script $_version (updated: $_updated)"
-			elif (( REPLY > 0 && REPLY <= ${#options[@]} )); then
-				isofile="$opt"
-				break
-			else
-				printf "Invalid option. Choose 1 - %d\n" "${#options[@]}" 
-			fi
-		done
-	fi
+cleanup() {
+	[[ -f devfile ]] && rm -f devfile
 }
 
+select_iso_directory() {
+	local iso_dir="${HOME}/Downloads/ISO"
+	under_line "ISO Directories" "*"
+	PS3="Select an ISO directory: "
+	COLUMNS=60
+	options=(
+		"antiX-Linux"
+		"ArchLabs"
+		"Artix"
+		"BunsenLabs"
+		"Debian"
+		"Linux_Lite"
+		"Mint"
+		"MX_Linux"
+		"Tails"
+		"Ubuntu"
+		"Utilities"
+		"Current directory"
+	)
+	select opt in "${options[@]}"; do
+		case "$REPLY" in
+			1 )	pushd "$iso_dir/Linux/$opt" || die "pushd failed!"; break ;;
+			2 )	pushd "$iso_dir/Linux/$opt" || die "pushd failed!"; break ;;
+			3 )	pushd "$iso_dir/Linux/$opt" || die "pushd failed!"; break ;;
+			4 )	pushd "$iso_dir/Linux/$opt" || die "pushd failed!"; break ;;
+			5 )	pushd "$iso_dir/Linux/$opt" || die "pushd failed!"; break ;;
+			6 )	pushd "$iso_dir/Linux/$opt" || die "pushd failed!"; break ;;
+			7 )	pushd "$iso_dir/Linux/$opt" || die "pushd failed!"; break ;;
+			8 ) pushd "$iso_dir/Linux/$opt" || die "pushd failed!"; break ;;
+			9 )	pushd "$iso_dir/Linux/$opt" || die "pushd failed!"; break ;;
+			11 ) pushd "$iso_dir/$opt" || die "pushd failed!"; break ;;
+			12 ) iso_dir="$PWD" || die "pushd failed!"; break ;;
+			* ) printf "Invalid option. Choose 1 - %d\n" "${#options[@]}"
+		esac
+	done
+	printf "\n"
+}
+
+# List available ISO files and select file to write
+
+select_iso() {
+	local num_iso
+	num_iso=$(find ./ -maxdepth 1 -type f -name "*.iso" | wc -l)
+	[[ "$num_iso" = 0 ]] && diehard "No ISO files found." "Change to a directory containing the ISO file to be checked." "$_script $_version ($_updated)"
+
+	under_line "ISO files:" "*"
+	PS3="Please select an ISO file: "
+	options=($(find ./ -maxdepth 1 -name "*.iso" | sed 's/\.\///' | sort -u))
+	select opt in "${options[@]}" "Quit"; do
+		if (( REPLY == 1 + ${#options[@]} )); then
+			printf "No ISO file selected. Operation canceled. Exiting the script."
+			leave "$_script $_version (updated: $_updated)"
+		elif (( REPLY > 0 && REPLY <= ${#options[@]} )); then
+			isofile="$opt"
+			break
+		else
+			printf "Invalid option. Choose 1 - %d\n" "${#options[@]}"
+		fi
+	done
+	printf "\n"
+}
+
+fzf_select_iso() {
+	local num_iso
+	num_iso=$(find ./ -maxdepth 1 -type f -name "*.iso" | wc -l)
+	[[ "$num_iso" = 0 ]] && diehard "No ISO files found." "Change to a directory containing the ISO file to be checked." "$_script $_version ($_updated)"
+	isofile=$(find ./ -type f -name "*.iso" -print | sed 's/\.\///' | fzf --prompt "Select the ISO file to check: ")
+}
+
+zen_select_iso() {
+	local file
+	file=$(zenity --file-selection --file-filter='ISO files (iso) | *.iso' --file-filter='All files | *' --title="Select an ISO file.")
+	case "$?" in
+		0 ) isofile="$(basename "$file")" ;;
+		1 ) echo "$file not selected." ;;
+		-1 ) echo "$file not selected"
+	esac
+}
+
+# List removable devices and select device to write to
 select_usb() {
-	if exists fzf; then
-		usb_device=$(lsblk -o HOTPLUG,TYPE,NAME,SIZE,LABEL | awk '$2 == "disk" && $1 == "1" {print $0}' | awk '{$1=$1}1' | sed 's/1//' | fzf --prompt "Select the USB drive to write to: ")
-		usb_device=$(echo "$usb_device" | awk '{print $2}')
-	else
-		printf "Available drives:\n"
-		lsblk -o HOTPLUG,TYPE,NAME,SIZE,LABEL | awk '$2 == "disk" && $1 == "1" {print $0}' | awk '{$1=$1}1' | sed 's/1//'
-		print_line "-" 40
-		PS3="Please select an available USB drive: "
-		options=($(lsblk -o NAME,TYPE,HOTPLUG | awk '$2 == "disk" && $3 == "1" {print $1}'))
-		select opt in "${options[@]}" "Quit"; do
-			if (( REPLY == 1 + ${#options[@]} )); then
-				printf "No USB device selected. Operation canceled. Exiting the script.\n"
-				leave "$_script v$_version ($_updated)"
-			elif (( REPLY > 0 && REPLY <= ${#options[@]} )); then
-				usb_device="$opt"
-				break
-			else
-				printf "Invalid option. Choose 1 - %d\n" "${#options[@]}" 
-			fi
-		done
-	fi
+	printf "Available drives:\n"
+	lsblk -o HOTPLUG,TYPE,NAME,SIZE,LABEL | awk '$2 == "disk" && $1 == "1" {print $0}' | awk '{$1=$1}1' | sed 's/1//;s/disk //'
+	print_line "-" 40
+	PS3="Please select an available USB drive: "
+	options=($(lsblk -o NAME,TYPE,HOTPLUG | awk '$2 == "disk" && $3 == "1" {print $1}'))
+	select opt in "${options[@]}" "Quit"; do
+		if (( REPLY == 1 + ${#options[@]} )); then
+			printf "No USB device selected. Operation canceled. Exiting the script.\n"
+			leave "$_script v$_version ($_updated)"
+		elif (( REPLY > 0 && REPLY <= ${#options[@]} )); then
+			usb_device="$opt"
+			break
+		else
+			printf "Invalid option. Choose 1 - %d\n" "${#options[@]}"
+		fi
+	done
+}
+
+fzf_select_usb() {
+	usb_device=$(lsblk -o HOTPLUG,TYPE,NAME,SIZE,LABEL | awk '$2 == "disk" && $1 == "1" {print $0}' | awk '{$1=$1}1' | sed 's/1//' | fzf --prompt "Select the USB drive to write to: ")
+	usb_device=$(echo "$usb_device" | awk '{print $2}')
+}
+
+zen_select_usb() {
+	# usb_device=$(zenity --list --title "Choose USB device:" --column=Device $(lsblk -o HOTPLUG,TYPE,NAME,SIZE,LABEL | awk '$2 == "disk" && $1 == "1" {print $0}' | awk '{$1=$1}1' | sed 's/1//'))
+	# usbdev=$(zenity --list --title "Choose USB device:" --column=Device $(lsblk -o NAME,TYPE,HOTPLUG | awk '$2 == "disk" && $3 == "1" {print $1}')); echo $usbdev
+	usbdev=$(lsblk -o HOTPLUG,TYPE,NAME,SIZE | awk '$2 == "disk" && $1 == "1" {print $3,$4}')
+	echo "$usbdev" | \
+	awk '{
+	    print NR;
+	    for(i=1;i<=NF;i++){
+	        print $i;
+	    }
+	}' | \
+	zenity --list \
+	--title="USB Devices" \
+	--column="Index" --column="Device" --column="Size" \
+	--print-column=2 > devfile  2>/dev/null
+	usb_device=$(cat devfile)
 }
 
 write_dd() {
@@ -105,59 +185,117 @@ simulate_dd() {
   kill "$!"
   tput cnorm
   printf "\n%s written to /dev/%s (SIMULATED)\n"  "$isofile" "$usb_device"
-  printf "\nContents of /dev/%s\n\n" "$usb_device"
+  printf "\nContents of /dev/%s:\n" "$usb_device"
   ls "/media/$user/$mount_name"
-
+}
 
 mount_usb() {
   [[ -d "/media/$user/$mount_name" ]] || sudo mkdir -p "/media/$user/$mount_name"
 	sudo mount "/dev/$usbpart" "/media/$user/$mount_name" 2>/dev/null
 	printf "USB drive /dev/%s is mounted at /media/$user/%s\n" "$usbpart" "$mount_name"
-}}
+}
 
 unmount_usb() {
-	sudo umount "/dev/$usbpart"	&& printf "USB drive unmounted.\n" # /media/$user/"$mount_name"
+	sudo umount "/dev/$usbpart" && printf "USB drive unmounted.\n" # /media/$user/"$mount_name"
 	[[ -d "/media/$user/$mount_name" ]] && sudo rmdir "/media/$user/$mount_name"
 	printf "It's now safe to remove the USB drive.\n"
 }
 
+help() {
+	errcode="${1:-2}"
+	cat << END_HELP
+${green}Usage:${normal} $_script [OPTION]
+${orange}OPTIONS:${normal}
+	-d	Enable Dry Run simulation
+	-f	Select with Fuzzy Finder (fzf)
+	-h	Display help
+	-s	Select with Select Menu
+	-z	Select with Zenity dialog
+$_script $_version (Updated $_updated)
+END_HELP
+  exit "$errcode"
+}
+
 ## Execution ##
 
-sudo_login 2
+trap cleanup EXIT
 
 printf "Writes ISO to a USB drive.\n\n"
 
 # Check if a USB drive is connected
 [[ $(lsblk -S -o TRAN | grep 'usb') = *usb* ]] || diehard "No USB drive connected." "Insert and mount the target USB drive." "$_script v$_version ($_updated)"
 
-# List available ISO files and select file to write
-select_iso
-printf "Selected ISO: %s\n\n" "$isofile"
+noOpt=1
+optstr=":dfhsz"
+while getopts "$optstr" opt; do
+	case "$opt" in
+		d )
+			dryrun="$TRUE"
+			printf "%sPerforming a dryrun, USB drive will NOT be written to%s.\n\n" "$orange" "$normal"
+		;;
+		f )
+			if exists fzf; then
+				select_iso_directory
+				fzf_select_iso
+				fzf_select_usb
+			else
+				leave "fzf (Fuzzy Finder) is not installed on this system."
+			fi
+		;;
+		h )
+			help 0
+		;;
+		s )
+			select_iso_directory
+			select_iso
+			select_usb
+		;;
+		z )
+			if exists zenity; then
+				select_iso_directory
+				zen_select_iso
+				zen_select_usb
+			else
+				leave "Zenity is not installed on this system."
+			fi
+		;;
+		? )
+			printf "%s Invalid option -%s\n" "$red_error" "$OPTARG" >&2
+			help 2
+	esac
+	noOpt=0
+done
+[[ "$noOpt" = 1 ]] && { printf "%s No argument passed.\n" "$red_error" >&2; help 1; }
+shift "$(( OPTIND - 1 ))"
 
-# List removable devices and select device to write to
-select_usb
-printf "Selected device: /dev/%s\n%sIf you continue, ALL data will be erased from this device.%s\n\n" "$usb_device" "$orange" "$normal"
-printf "Answer 'yes' only if you are %s%sABSOLUTELY%s sure you want to proceed.\n\n" "$bold" "$orange" "$normal"
+# [[ "$dryrun" == "$FALSE" ]] && sudo_login 2
+printf "Selected ISO: %s\n\n" "$isofile"
+printf "Selected device: /dev/%s\n" "$usb_device"
 
 # Mount selected USB drive if not already mounted.
 usbpart="${usb_device}1"
 if mount | grep -q "$usbpart" > /dev/null 2>&1; then
 	mount_name=$(lsblk | grep "$usbpart" | cut -d'/' -f4- )
 else
+	sudo_login 2
 	mount_name="$(date +%y%b%d)"
 	mount_usb #"/dev/$usbpart"
 fi
 
 # Confirm action or cancel
-if yes_or_no "Write $isofile to /dev/$usb_device?"; then
-  # simulate_dd "$isofile" "$usb_device"
-  write_dd "$isofile" "$usb_device"
+if [[ "$dryrun" == "$TRUE" ]]; then
+	simulate_dd "$isofile" "$usb_device"
 else
-  printf "Operation canceled. No action taken.\n"
+	printf "%sIf you continue, ALL data will be erased from device %s.%s\n\n" "$orange" "$usb_device" "$normal"
+	printf "Answer 'yes' only if you are %s%sABSOLUTELY%s sure you want to proceed.\n\n" "$bold" "$orange" "$normal"
+	if yes_or_no "Write $isofile to /dev/$usb_device?"; then
+		sudo_login 2
+		write_dd "$isofile" "$usb_device"
+		printf "Unmounting the USB Drive from /dev/%s/%s\n" "$user"  "$mount_name"
+		mount | grep -q "/dev/$usbpart" > /dev/null 2>&1 && unmount_usb
+	else
+	printf "Operation canceled. No action taken.\n"
+	fi
 fi
-
-# unmount the USB Drive
-printf "Unmounting the USB Drive from /dev/%s/%s\n" "$user"  "$mount_name"
-mount | grep -q "/dev/$usbpart" > /dev/null 2>&1 && unmount_usb
 
 leave "$_script v$_version (Updated: $_updated)"
