yt-dl: select_directory() looks for directories in /data if host is dell-9020

diff --git a/yt-dl b/yt-dl
--- a/yt-dl
+++ b/yt-dl
@@ -7,7 +7,7 @@
 # Author       : Copyright © 2019, Richard B. Romig, 05 April 2019
 # Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
 # Created      : 05 Apr 2019
-# Updated      : 15 Apr 2026
+# Updated      : 12 May 2026
 # Comments     : Accepts both full URLs and video id's such as AQcQgfvfF1M
 #              : Downloads to selected directory under ~/Videos/
 # TODO (Rick)  :
@@ -27,13 +27,13 @@
 
 ## Load function library ##
 # shellcheck source=/home/rick/bin/functionlib
-source functionlib || { printf "\e[91mERROR:\e[0m Unable to source functionlib\n"; exit 1; }
+source ~/bin/functionlib || { printf "\e[91mERROR:\e[0m Unable to source functionlib\n"; exit 1; }
 
 ## Global Variables ##
 
 readonly script="${0##*/}"
-readonly version="7.6.26105"
-readonly updated="15 Apr 2026"
+readonly version="7.7.26132"
+readonly updated="12 May 2026"
 FMENU="fzf --header=$script \
            --layout=reverse \
            --exact \
@@ -107,8 +107,10 @@ extract_domain() {
 
 select_directory() {
 	local vid_d selected_directory
+  local local_host="${HOSTNAME:-$(hostname)}"
 	local video_dir=$HOME"/Videos"
   local directories=()
+  [[ "$local_host" == "dell-9020" ]] && video_dir="/data/Videos"
   for vid_d in $video_dir; do
     [[ -d "$vid_d" ]] && directories+=("$(sort -d < <(find "$video_dir" -path "$video_dir/Pornography" -prune -o -type d))")
   done
