yt-dl-playlist - updated help(), argument checks, script title information.

diff --git a/yt-dl-playlist b/yt-dl-playlist
--- a/yt-dl-playlist
+++ b/yt-dl-playlist
@@ -6,15 +6,18 @@
 # Arguments    : Video URL
 # Author       : Copyright © 2020, Richard B. Romig, 28 May 2020
 # Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
+# Created      : 28 May 2020
+# Updated      : 28 Jun 2024
 # Comments     : Accepts only full URL
 #              : Downloads to current working directory
+#              : Video Playlist
+#              : yt-dlp -i -f mp4 --output "%(title)s.%(ext)s" --yes-playlist "$url"
 # TODO (Rick)  : Hangs after first file in playlist is downloaded.
 # License      : GNU General Public License, version 2.0
 ###############################################################################
 
 ## Shellcheck Directives ##
 # shellcheck source=/home/rick/bin/functionlib
-# shellcheck disable=SC1091
 
 ## Load function library ##
 
@@ -28,15 +31,27 @@ fi
 ## Variables ##
 
 _script=$(basename "$0"); readonly _script
-readonly _version="0.2.1"
-readonly _updated="09 Sep 2023"
+readonly _version="2.1.24180"
+readonly _updated="28 Jun 2024"
 
 ## Functions ##
 
-usage() {
+help() {
   local errcode="${1:-2}"
   echo "Usage: $_script [video-url]"
   echo "$_script https://www.youtube.com/watch?v=8hLlU0EML4U"
+  cat << END_HELP
+${orange}$_script${normal} $_version, Updated: $_updated
+Downloads mp3 audio from a playlist of YouTube videos to current working diretory.
+
+${green}Usage:${normal} $_script [OPTION] [video-url]
+
+${orange}Available options:${normal}
+  -h | --help  Show this help text.
+
+$_script https://www.youtube.com/watch?v=qmRRDig_9nE&list=RDqmRRDig_9nE&start_radio=1
+
+END_HELP
   exit "$errcode"
 }
 
@@ -53,37 +68,30 @@ check_dependencies() {
 
 check_dependencies
 
-if [[ -z "$1" ]]; then
+if [[ "$#" -eq 0 ]]; then
   echo $'\n'$"${bold}${lightred}Error:${normal} No argument passed." >&2
-  usage 2
+  help 2
 elif [[ "$1" == "--help" || "$1" == "-h" ]]; then
-  usage 0
+  help 0
 elif [[ "$1" =~ ^https?:\/\/.* ]]; then
   # match by regex, starts with http:// or https://
-  # \/ in regex will be seen as / in this context
   url=$*
 else
   echo "${bold}${lightred}Error:${normal} Invalid argument. Must be full URL." >&2
-  usage 2
+  help 2
 fi
 
 ## Execution ##
 
 clear
-box "YouTube Audio Playlist Download"
-echo "$_script v$_version"
-echo "($_updated)"
-echo $'\n'$"${bold}${blue}Downloading mp3 audio for $URL${normal}"
+box "$_script v$_version" "*"
+under_line "* YouTube Audio Playlist Download *" "*"
+echo $'\n'$"Downloading mp3 audio for $url"
 # if /usr/local/bin/yt-dlp --add-metadata -xic --embed-thumbnail \
 # --restrict-filename --audio-format mp3 --output "%(title)s.%(ext)s" \
 # --yes-playlist "$url"; then
-if /usr/local/bin/yt-dlp --ignore-errors --format bestaudio --extract-audio \
- --restrict-filename --audio-format mp3 --audio-quality 160K \
- --output "%(title)s.%(ext)s" --yes-playlist "$url"; then
+if /usr/local/bin/yt-dlp --ignore-errors --format bestaudio --extract-audio --restrict-filename --audio-format mp3 --audio-quality 160K --output "%(title)s.%(ext)s" --yes-playlist "$url"; then
   leave "Download successful."
 else
-  ec="$?"
-  die "Download failed." "$ec"
+  die "Download failed." "$?"
 fi
-# Video Playlist
-# yt-dlp -i -f mp4 --output "%(title)s.%(ext)s" --yes-playlist "$url"
