yt-dl-playlist - implemented main() & download_playlist()

diff --git a/yt-dl-playlist b/yt-dl-playlist
--- a/yt-dl-playlist
+++ b/yt-dl-playlist
@@ -4,10 +4,10 @@
 # Description  : Download a playlist of YouTube audio files to current directory
 # Dependencies : yt-dlp
 # Arguments    : Video URL
-# Author       : Copyright © 2020, Richard B. Romig, 28 May 2020
+# Author       : Copyright © 2020, Richard B. Romig, Mosfanet
 # Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
 # Created      : 28 May 2020
-# Updated      : 28 Jun 2024
+# Updated      : 31 Dec 2024
 # Comments     : Accepts only full URL
 #              : Downloads to current working directory
 #              : Video Playlist
@@ -28,30 +28,25 @@ else
   exit 1
 fi
 
-## Variables ##
+## Global Variables ##
 
-_script=$(basename "$0"); readonly _script
-readonly _version="2.1.24180"
-readonly _updated="28 Jun 2024"
+script=$(basename "$0"); readonly script
+readonly version="3.0.24366"
 
 ## Functions ##
 
 help() {
   local errcode="${1:-2}"
-  echo "Usage: $_script [video-url]"
-  echo "$_script https://www.youtube.com/watch?v=8hLlU0EML4U"
-  cat << END_HELP
-${orange}$_script${normal} $_version, Updated: $_updated
-Downloads mp3 audio from a playlist of YouTube videos to current working diretory.
+  local updated="31 Dec 2024"
+  cat << _HELP_
+${orange}$script${normal} $version, Updated: $updated
+Downloads mp3 audio from a playlist of YouTube videos to current working directory.
 
-${green}Usage:${normal} $_script [OPTION] [video-url]
+${green}Usage:${normal} $script [OPTION] [video-url]
 
 ${orange}Available options:${normal}
   -h | --help  Show this help text.
-
-$_script https://www.youtube.com/watch?v=qmRRDig_9nE&list=RDqmRRDig_9nE&start_radio=1
-
-END_HELP
+_HELP_
   exit "$errcode"
 }
 
@@ -64,34 +59,38 @@ check_dependencies() {
   fi
 }
 
+download_playlist() {
+  local playlist_url
+  box "YouTube Audio Playlist Download" "*"
+  printf "\nDownloading mp3 audio for %s\n" "$playlist_url"
+  # if /usr/local/bin/yt-dlp --add-metadata -xic --embed-thumbnail --restrict-filename --audio-format mp3 --output "%(title)s.%(ext)s"  --yes-playlist "$url"
+  if /usr/local/bin/yt-dlp --ignore-errors --format bestaudio --extract-audio --restrict-filename --audio-format mp3 --audio-quality 160K --output "%(title)s.%(ext)s" --yes-playlist "$playlist_url"
+  then
+    printf "Download successful\n"
+  else
+    printf "Download failed\n"
+  fi
+}
+
+main() {
+  local url
+  check_dependencies
+  if [[ "$#" -eq 0 ]]; then
+    printf "%s No argument passed \n" "$RED_ERROR" >&2
+    help 2
+  elif [[ "$1" == "--help" || "$1" == "-h" ]]; then
+    help 0
+  elif [[ "$1" =~ ^https?:\/\/.* ]]; then
+    url="$*"
+  else
+    printf "%s Invalid argument. Must be full URL.\n" "$RED_ERROR" >&2
+    help 1
+  fi
+  download_playlist "$url"
+  over_line "$script v$version" "-"
+  exit
+}
+
 ## Execution ##
 
-check_dependencies
-
-if [[ "$#" -eq 0 ]]; then
-  echo $'\n'$"${bold}${lightred}Error:${normal} No argument passed." >&2
-  help 2
-elif [[ "$1" == "--help" || "$1" == "-h" ]]; then
-  help 0
-elif [[ "$1" =~ ^https?:\/\/.* ]]; then
-  # match by regex, starts with http:// or https://
-  url=$*
-else
-  echo "${bold}${lightred}Error:${normal} Invalid argument. Must be full URL." >&2
-  help 2
-fi
-
-## Execution ##
-
-clear
-box "$_script v$_version" "*"
-under_line "* YouTube Audio Playlist Download *" "*"
-echo $'\n'$"Downloading mp3 audio for $url"
-# if /usr/local/bin/yt-dlp --add-metadata -xic --embed-thumbnail \
-# --restrict-filename --audio-format mp3 --output "%(title)s.%(ext)s" \
-# --yes-playlist "$url"; then
-if /usr/local/bin/yt-dlp --ignore-errors --format bestaudio --extract-audio --restrict-filename --audio-format mp3 --audio-quality 160K --output "%(title)s.%(ext)s" --yes-playlist "$url"; then
-  leave "Download successful."
-else
-  die "Download failed." "$?"
-fi
+main "$@"
