yt-dl-audio: updated error checking

diff --git a/yt-dl-audio b/yt-dl-audio
--- a/yt-dl-audio
+++ b/yt-dl-audio
@@ -7,7 +7,7 @@
 # Author       : Copyright © 2019, Richard B. Romig, LudditeGeek@Mosfanet
 # Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
 # Created      : 14 Nov 2019
-# Updated      : 21 Jul 2025
+# Updated      : 06 Feb 2026
 # Comments     : Accepts both full URLs and video id's such as AQcQgfvfF1M
 #              : Downloads to current working directory
 # TODO (Rick)  :
@@ -34,19 +34,20 @@ if [[ -x "$HOME/bin/functionlib" ]]; then
   source "$HOME/bin/functionlib"
 else
   echo -e "\e[91mERROR:\e[0m functionlib not found!" >&2
-  exit 1
+  exit 81
 fi
 
 ## Global Variables ##
 
 readonly script="${0##*/}"
-readonly version="3.3.25202"
+readonly version="3.4.26037"
+EC=0
 
 ## Functions
 
 help() {
-  local errcode="${1:-2}"
-  local -r updated="21 Jul 2025"
+  local errcode="${1:-1}"
+  local -r updated="06 Feb 2026"
   cat << _HELP_
 ${orange}$script${normal} $version, Updated: $updated
 Downloads mp3 audio from YouTube videos to current working diretory.
@@ -69,20 +70,20 @@ check_dependencies() {
     printf '\e[A\e[K'
     check_package ffmpeg
  else
-    die "yt-dlp is not installed." 1
+    die "yt-dlp is not installed." "$E_FILENOTFOUND"
   fi
 }
 
 download_audio() {
-  local ec url
+  local url
   url="$1"
   box "* YouTube Audio Download *" "*"
   printf "\nDownloading mp3 audio from %s to %s...\n" "$url" "$PWD"
   if /usr/local/bin/yt-dlp --add-metadata -xic --embed-thumbnail --restrict-filename --audio-format mp3 --output "%(title)s.%(ext)s" "$url"; then
     printf "Download successful.\n"
   else
-    ec="$?"
-    printf "Download failed. Error: %d" "$ec"
+    EC="$?"
+    printf "Download failed. Error: %d" "$EC"
   fi
 }
 
@@ -90,20 +91,20 @@ main() {
   local url
   if [[ "$#" = 0 ]]; then
     printf "%s No argument passed.\n" "$RED_ERROR" >&2
-    help 2
+    help "$E_MISSING_ARG"
   elif [[ "$1" == "--help" || "$1" == "-h" ]]; then
     help 0
   elif [[ "$1" =~ ^https?:\/\/.* ]]; then
     # match by regex, starts with http:// or https://
     audio_url=$*
   else
-    # match by video ID
+    # match by YouTube video ID
     audio_url="https://www.youtube.com/watch?v=$*"
   fi
   check_dependencies
   download_audio "$audio_url"
   over_line "$script v$version" "-"
-  exit
+  exit "$EC"
 }
 
 # Execution
