yt-dl-audio: added check_arguments()

diff --git a/yt-dl-audio b/yt-dl-audio
--- a/yt-dl-audio
+++ b/yt-dl-audio
@@ -7,8 +7,8 @@
 # Author       : Copyright © 2019, Richard B. Romig, LudditeGeek@Mosfanet
 # Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
 # Created      : 14 Nov 2019
-# Updated      : 04 Sep 2026
-# Version      : 3.9.26247
+# Updated      : 10 Sep 2026
+# Version      : 3.10.26253
 # Comments     : Accepts both full URLs and video id's such as AQcQgfvfF1M
 #              : Downloads to current working directory
 # TODO (Rick)  :
@@ -48,6 +48,19 @@ _HELP_
   exit "$errcode"
 }
 
+check_arguments() {
+	if [[  $# -eq 0 ]]; then
+		printf "%s No argument passed.\n" "$RED_ERROR" >&2
+		help "$script" "$version" "$updated" "$E_MISSING_ARG"
+	elif [[ "$1" == "--info" || "$1" == "-i" ]]; then
+		script_info "$script" "$version" "$updated"
+		exit 0
+	elif [[ "$1" == "--help" || "$1" == "-h" ]]; then
+		help "$script" "$version" "$updated" 0
+	fi
+	return 0
+}
+
 check_dependencies() {
 	[[ -x /usr/local/bin/yt-dlp ]] || die "yt-dlp is not installed." "$E_FILENOTFOUND"
 	printf "yt-dlp [OK]\n"
@@ -73,21 +86,18 @@ download_audio() {
 
 main() {
 	local -r script="${0##*/}"
-	local -r version="3.9.26247"
+	local -r version="3.10.26253"
 	local -i exit_code=0
 	local audio_url
 	local -r re="^https?:\/\/.*"
-	if [[ "$#" -eq 0 ]]; then
-		printf "%s No argument passed.\n" "$RED_ERROR" >&2
-		help "$script" "$version" "$E_MISSING_ARG"
-	elif [[ "$1" == "--help" || "$1" == "-h" ]]; then
-		help "$script" "$version" 0
-	elif [[ $1 =~ $re ]]; then
+	check_arguments "$@"
+	check_dependencies
+	if [[ $1 =~ $re ]]; then
 		# match by regex, starts with http:// or https://
-		audio_url="$*"
+		local -r url=$*
 	else
 		# match by YouTube video ID
-		audio_url="https://www.youtube.com/watch?v=$*"
+		local -r url="https://www.youtube.com/watch?v=$*"
 	fi
 	check_dependencies
 	download_audio "$audio_url"
