Updated script with modified getopts procedures.

diff --git a/Templates/bash-getopts b/Templates/bash-getopts
--- a/Templates/bash-getopts
+++ b/Templates/bash-getopts
@@ -1,14 +1,15 @@
 ## Shell Template ##
-#!/bin/bash
+#!/usr/bin/env bash
 ##########################################################################
 # Script Name  : <FILE>
 # Description  :
 # Dependencies :
 # Arguments    :
-# Author       : Copyright (C) <YEAR> <AUTHOR>, <TODAY>
+# Author       : Copyright (C) <YEAR> <AUTHOR>, <ORG>
 # Email        : <EMAIL> | <EMAIL1>
-# Comments     :
+# Created      : <TODAY>
 # Last updated : <TODAY>
+# Comments     :
 # TODO (<CODER>)  :
 # License      : <LICENSE>
 ##########################################################################
@@ -68,53 +69,47 @@ app_version() {
 # clear
 
 
-if [[ "$#" -eq 0 ]]; then
-	# printf "%s No argument passed.\n" "$red_error"  >&2
-	echo "${lightred}ERROR:${normal} No argument passed." >&2
-	help 1
-else
-	optstr=":hirsu"
-	# optstr=":h:i:r:s:u"
-	while getopts "$optstr" opt; do
-		case "$opt" in
-			h )
-				help 0
-				;;
-			i )
-				# argI="$OPTARG"
-				exists application && leave "Application $(app_version) is already installed."
-				install_application
-				apply_settings	# optional custom configuration
-				break	# Remove break if multiple options or if functions exit
-				;;
-			r )
-				# argR="$OPTARG"
-				exists application || leave "Application is not installed."
-				remove_application
-				break	# Remove break if multiple options or if functions exit
-				;;
-			s )
-				apply_settings
-				break	# Remove break if multiple options or if functions exit
-				;;
-			u )
-				exists application || leave "Application is not installed."
-				update_application
-				break	# Remove break if multiple options or if functions exit
-				;;
-			: )
-				# printf "%s Must supply an argument to -%s.\n" "$red_error" "$OPTARG" >&2
-			    echo "${lightred}ERROR:${normal} Must supply an argument to -${OPTARG}." >&2
-			    help 2
-			    ;;
-			? )
-				# printf "%s Invalid option -%s\n" "$red_error" "$OPTARG" >&2
-				echo "${lightred}ERROR:${normal} Invalid option -${OPTARG}" >&2
-				help 2
-				;;
-		esac
-	done
-fi
+noOpt=1
+optstr=":hirsu"
+# optstr=":h:i:r:s:u"
+while getopts "$optstr" opt; do
+	case "$opt" in
+		h )
+			help 0
+			;;
+		i )
+			# argI="$OPTARG"
+			exists application && leave "Application $(app_version) is already installed."
+			install_application
+			apply_settings	# optional custom configuration
+			;;
+		r )
+			# argR="$OPTARG"
+			exists application || leave "Application is not installed."
+			remove_application
+			;;
+		s )
+			apply_settings
+			;;
+		u )
+			exists application || leave "Application is not installed."
+			update_application
+			;;
+		: )
+			# printf "%s Must supply an argument to -%s.\n" "$red_error" "$OPTARG" >&2
+			  echo "${lightred}ERROR:${normal} Must supply an argument to -${OPTARG}." >&2
+			  help 2
+			  ;;
+		? )
+			# printf "%s Invalid option -%s\n" "$red_error" "$OPTARG" >&2
+			echo "${lightred}ERROR:${normal} Invalid option -${OPTARG}" >&2
+			help 2
+			;;
+	esac
+	noOpt=0
+done
+# if [ $noOpt = 1 ];then echo "${lightred}ERROR:${normal} No argument passed." >&2;help 1;fi
+if [ $noOpt = 1 ];then printf "%s No argument passed.\n" "$red_error" >&2;help 1;fi
 # echo -e "$_script v$_version ($_updated)"
 printf "%s v%s (%s)\n" "$_script" "$_version" "$_updated"
 exit
diff --git a/lm20-snaps b/lm20-snaps
--- a/lm20-snaps
+++ b/lm20-snaps
@@ -28,8 +28,8 @@ fi
 ## Variables ##
 
 _script=$(basename "$0"); readonly _script
-readonly _version="0.2.3"
-readonly _updated="12 Mar 2023"
+readonly _version="0.2.4"
+readonly _updated="29 Mar 2023"
 readonly pref_file="/etc/apt/preferences.d/nosnap.pref"
 
 ## Functions ##
@@ -105,39 +105,36 @@ END_HELP
 
 ## Execution ##
 
-clear
 box "$_script v$_version ($_updated)"
 printf "Enables or disables the installation of snapd and Snap packages in Linux Mint 20 and later.\n"
 
 if lm20_plus; then
-  if [[ $# -eq 0 ]]; then
-    printf "\n%s No argument passed\n" "$red_error" >&2
-    help 2
-  else
-    optstr=":dehs"
-    while getopts "$optstr" opt; do
-      case "$opt" in
-        d )
-          user_in_sudo
-          disable_snaps
-          break ;;
-        e )
-          user_in_sudo
-          enable_snaps
-          break ;;
-        h )
-          help 0
-          break ;;
-        s )
-          printf "\nStatus of snapd and snap packages: "
-          snap_status && printf "Snaps are enabled.\n" || printf "Snaps are disabled.\n"
-          break ;;
-        ? )
-          printf "\n%s Invalid option -%s\n" "$red_error" "$OPTARG" >&2
-          help 2 ;;
-      esac
-    done
-  fi
+  noOpt=1
+  optstr=":dehs"
+  while getopts "$optstr" opt; do
+    case "$opt" in
+      d )
+        user_in_sudo
+        disable_snaps
+        break ;;
+      e )
+        user_in_sudo
+        enable_snaps
+        break ;;
+      h )
+        help 0
+        break ;;
+      s )
+        printf "\nStatus of snapd and snap packages: "
+        snap_status && printf "Snaps are enabled.\n" || printf "Snaps are disabled.\n"
+        break ;;
+      ? )
+        printf "\n%s Invalid option -%s\n" "$red_error" "$OPTARG" >&2
+        help 2 ;;
+    esac
+	  noOpt=0
+  done
+  if [ $noOpt = 1 ];then printf "%s No argument passed.\n" "$red_error" >&2;help 1;fi
   exit
 else
   die "This script is only for use with Linux Mint 20 or later." 1
diff --git a/local-ip-up b/local-ip-up
--- a/local-ip-up
+++ b/local-ip-up
@@ -30,8 +30,8 @@ fi
 ## Variables ##
 
 _script=$(basename "$0"); readonly _script
-readonly _version="0.4.3"
-readonly _updated="03 Feb 2023"
+readonly _version="0.4.4"
+readonly _updated="29 Mar 2023"
 
 ## Functions ##
 
@@ -118,50 +118,49 @@ EOT
 
 ## Execution ##
 
-check_dependencies
-
 SECONDS=0
 count=0
 
-if [[ $# -eq 0 ]]; then
-  echo "${lightred}ERROR:${normal} No argument passed." >&2
-  help 2
-else
-  optstr=":adhs"
-  while getopts "$optstr" opt; do
-    case "$opt" in
-      a )
-        tput civis
-        echo $'\n'$"Scanning  the network ..."
-        echo -e "${underline}${green}IP Address\tHostname${normal}"
-        scan_static_addresses
-        scan_dhcp_addresses
-        tput cnorm
-        ;;
-      d )
-        tput civis
-        echo $'\n'$"Scanning DHCP addresses on the network ..."
-        echo -e "${underline}${green}IP Address\tHostname${normal}"
-        scan_dhcp_addresses
-        tput cnorm
-        ;;
-      h )
-        help 0
-        ;;
-      s )
-        tput civis
-        echo $'\n'$"Scanning static IP addresses on the network ..."
-        echo -e "${underline}${green}IP Address\tHostname${normal}"
-        scan_static_addresses
-        tput cnorm
-        ;;
-      ? )
-        echo "${lightred}ERROR:${normal} Invalid option -${OPTARG}" >&2
-        help 2
-        ;;
-    esac
-  done
-fi
+noOpt=1
+optstr=":adhs"
+while getopts "$optstr" opt; do
+  case "$opt" in
+    a )
+      check_dependencies
+      tput civis
+      echo $'\n'$"Scanning  the network ..."
+      echo -e "${underline}${green}IP Address\tHostname${normal}"
+      scan_static_addresses
+      scan_dhcp_addresses
+      tput cnorm
+      ;;
+    d )
+      check_dependencies
+      tput civis
+      echo $'\n'$"Scanning DHCP addresses on the network ..."
+      echo -e "${underline}${green}IP Address\tHostname${normal}"
+      scan_dhcp_addresses
+      tput cnorm
+      ;;
+    h )
+      help 0
+      ;;
+    s )
+      check_dependencies
+      tput civis
+      echo $'\n'$"Scanning static IP addresses on the network ..."
+      echo -e "${underline}${green}IP Address\tHostname${normal}"
+      scan_static_addresses
+      tput cnorm
+      ;;
+    ? )
+      echo "${lightred}ERROR:${normal} Invalid option -${OPTARG}" >&2
+      help 2
+      ;;
+  esac
+	noOpt=0
+done
+if [ $noOpt = 1 ];then printf "%s No argument passed.\n" "$red_error" >&2;help 1;fi
 
 printf "\n%s active addresses discovered in %s.\n\n" "$count" "$(format_time SECONDS)"
 leave "$_script v$_version ($_updated)"
diff --git a/mount-bu b/mount-bu
--- a/mount-bu
+++ b/mount-bu
@@ -27,8 +27,8 @@ fi
 ## Variables ##
 
 _script=$(basename "$0"); readonly _script
-readonly _version="0.2.2"
-readonly _updated="22 Jan 2023"
+readonly _version="0.2.3"
+readonly _updated="29 Mar 2023"
 readonly mount_location="/media/rick/BU_Drive"
 
 ## Functions ##
@@ -36,7 +36,7 @@ readonly mount_location="/media/rick/BU_Drive"
 mount_bu() {
   lsblk -o NAME,SIZE,TYPE,MOUNTPOINT
   printf "\n"
-  read -rp "Select the drive to mount (Enter to cancel): " usbdrv
+  read -rp "Enter the device name to mount (Enter to cancel): " usbdrv
   [[ -z "$usbdrv" ]] && leave "Operation canceled."
   user_in_sudo
   printf "Mounting %s to %s ...\n" "$usbdrv" "$mount_location"
@@ -80,40 +80,38 @@ EOL
 
 ## Execution ##
 
-printf "\U1F427 %s v%s (%s)\n" "$_script" "$_version" "$_updated"
+printf "%s v%s (%s)\n" "$_script" "$_version" "$_updated"
 printf "Mount/Unmount USB Backup drive.\n"
 
-if [[ $# -eq 0 ]]; then
-  printf "\n\e[91mERROR:\e[0m No argument passed\n" >&2
-  help 2
-else
-  optstr=":hmsu"
-  while getopts "$optstr" opt; do
-    case "$opt" in
-      h )
-        help 0
-        break ;;
-      m )
-        if bu_status; then
-          printf "No further action necessary.\n"
-        else
-          mount_bu
-        fi
-        break ;;
-      s )
-        bu_status
-        break ;;
-      u )
-        if bu_status; then
-          umount_bu
-        else
-          printf "No further action necessary.\n"
-        fi
-        break ;;
-      ? )
-        printf "\e[91mERROR:\e[0m Invalid option -%s\n" "$OPTARG" >&2
-        help 2 ;;
-    esac
-  done
-fi
+noOpt=1
+optstr=":hmsu"
+while getopts "$optstr" opt; do
+  case "$opt" in
+    h )
+      help 0
+      ;;
+    m )
+      if bu_status; then
+        printf "No further action necessary.\n"
+      else
+        mount_bu
+      fi
+      ;;
+    s )
+      bu_status
+      ;;
+    u )
+      if bu_status; then
+        umount_bu
+      else
+        printf "No further action necessary.\n"
+      fi
+      ;;
+    ? )
+      printf "\e[91mERROR:\e[0m Invalid option -%s\n" "$OPTARG" >&2
+      help 2 ;;
+  esac
+	noOpt=0
+done
+if [ $noOpt = 1 ];then printf "%s No argument passed.\n" "$red_error" >&2;help 1;fi
 exit
diff --git a/snippets/use_getopts b/snippets/use_getopts
--- a/snippets/use_getopts
+++ b/snippets/use_getopts
@@ -29,21 +29,17 @@ while getopts "$optstr" opt; do
 			# argI="$OPTARG"
 			install_application
 			apply_settings	# optional custom configuration
-			break	# Remove break if multiple options or functions exit
 			;;
 		r )
 			# argR="$OPTARG"
 			remove_application
-			break	# Remove break if multiple options or functions exit
 			;;
 		s )
 			apply_settings
-			break	# Remove break if multiple options or functions exit
 			;;
 		u )
 			exists application || leave "Application is not installed. run '$_script -i' to install."
 			update_application
-			break	# Remove break if multiple options or functions exit
 			;;
 		: )
 			# printf "\e[91mERROR:\e[0m Must supply an argument to -%s.\n" "$OPTARG" >&2
@@ -52,8 +48,8 @@ while getopts "$optstr" opt; do
 		    help 2
 		    ;;
 		? )
-			# printf "\e[91mERROR:\e[0m Invalid option -%s\n" $OPTARG >&2
-			# printf %s Invalid option -%s\n" "$red_error" $OPTARG >&2
+			# printf "\e[91mERROR:\e[0m Invalid option -%s\n" "$OPTARG" >&2
+			# printf "%s Invalid option -%s\n" "$red_error" "$OPTARG" >&2
 			echo "${lightred}ERROR:${normal} Invalid option -${OPTARG}" >&2
 			help 2
 	esac
