Templates/bash-getopts: changed case format and made printf default instead of echo.

diff --git a/Templates/bash-getopts b/Templates/bash-getopts
--- a/Templates/bash-getopts
+++ b/Templates/bash-getopts
@@ -67,8 +67,6 @@ app_version() {
 ## Execution ##
 
 # clear
-
-
 noOpt=1
 optstr=":hirsu"
 # optstr=":h:i:r:s:u"
@@ -76,35 +74,34 @@ while getopts "$optstr" opt; do
 	case "$opt" in
 		h )
 			help 0
-			;;
+		;;
 		i )
 			# argI="$OPTARG"
 			exists application && leave "Application $(app_version) is already installed."
 			install_application
 			apply_settings	# optional custom configuration
-			;;
+		;;
 		r )
 			# argR="$OPTARG"
 			exists application || leave "Application is not installed."
 			remove_application
-			;;
+		;;
 		s )
 			apply_settings
-			;;
+		;;
 		u )
 			exists application || leave "Application is not installed."
 			update_application
-			;;
+		;;
 		: )
-			# printf "%s Must supply an argument to -%s.\n" "$red_error" "$OPTARG" >&2
-			  echo "${lightred}ERROR:${normal} Must supply an argument to -${OPTARG}." >&2
-			  help 2
-			  ;;
-		? )
-			# printf "%s Invalid option -%s\n" "$red_error" "$OPTARG" >&2
-			echo "${lightred}ERROR:${normal} Invalid option -${OPTARG}" >&2
+			# echo "${lightred}ERROR:${normal} Must supply an argument to -${OPTARG}." >&2
+			printf "%s Must supply an argument to -%s.\n" "$red_error" "$OPTARG" >&2
 			help 2
-			;;
+	  ;;
+		? )
+			# echo "${lightred}ERROR:${normal} Invalid option -${OPTARG}" >&2
+			printf "%s Invalid option -%s\n" "$red_error" "$OPTARG" >&2
+			help 2
 	esac
 	noOpt=0
 done
